### ISSUE TITLE
Who are the people behind MapLibre?

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#100]
Currently there is a COMMUNITY.md file which says who are the members of the steering committee and there are the members of the GitHub organization. These two lists are not identical which is confusing to me. Also, I have heard in talks that big companies like Microsoft and Elastic Search are supporting the project but I can't find this written anywhere.

As a feedback I suggest to compile a list companies that back the project for example in the form of paying some contributors to work on MapLibre. Also a list of the individuals who have commit rights and a way of contacting them would be helpful.

**Comment by rbrundritt** [comment]
Its still early days for MapLibre, so lots of things in the works. Currently the steering committee is working to get this project onboarded with an open source foundation. Once that happens the project will be in a better position to receive financial support/sponsorship. Listing companies who support/sponsor a project is kind of like advertising, so it might make sense to wait until the project can receive financial support and then list those companies.

**Comment by JannikGM** [comment]
> That said, the main people behind this project is the steering committee..

Yes, and those people should be reachable; see my thoughts in the last paragraph of https://github.com/maplibre/maplibre-gl-js/issues/102#issuecomment-802887370

> ..and the 300+ people who have already made contributions (code/issues...) to this project.

Most of the contributions came to mapbox, not the maplibre project.

So far, maplibre had very few contributors, so it really needs to focus on growing the community to find more maintainers.

**Comment by wipfli** [comment]
@nyurik if [I understand you](https://github.com/maplibre/maplibre-gl-js/issues/98#issuecomment-799679396) correctly things will become clearer in the future. Do you know when the next sync happens with the steering committee? Or maybe @klokan do you know this? Thanks in advance.

**Comment by rbrundritt** [comment]
Right now the main focus is to get an initial stable release out of MapLibre based on the last open source version of Mapbox. Once all that is done, then PR's that expand the functionality is likely to happen. See the Projects tab to see where the current focus is.

Most of the people on steering committee are contactable in the Slack group for this project: https://app.slack.com/client/T029HV94T/C01G3D28DAB

I'm not on the steering committee and certainly can't speak on their behalf, but I have meet with them many times to offer support and gain insights into the direction and overall thinking for this project. Personally I feel they are doing a good job taking the lead for this project. I understand that it may feel like things are moving slow, but there is a lot of little things that need to be sorted out first to ensure there is a stable release that is backwards compatible, and also setting this up as a truly open source project that's part of an open source foundation. 

I'm sure there are many reasons why there hasn't been a lot of contributions directly to this project yet. One key one is that this is a fairly recent change and many/most are still using the last open source version from Mapbox and haven't had a need yet to upgrade. Many companies are likely still figuring out what path to take moving forward; pay for Mapbox and get the new features or join this new community and be able to more easily contribute in the future. Rome wasn't created in a day, but I feel good about the vision for this project.

**Comment by wipfli** [comment]
From what I understand when discussing with @klokan and @nyurik, MapLibre is maintained by individuals and a bunch of companies have an interest that the project lives on. Probably this will get clearer once the website is online.
