### ISSUE TITLE
CJK-fonts text offset ignored

### ISSUE THREAD

**Issue by Kanahiro** [maplibre/maplibre-gl-js#1002]
Thanks for your great contributions. CJK fonts become shown in v2.1.6 but another problem occurs.

**maplibre-gl-js version**: v2.1.6

**browser**: Chrome 97.0.4692.99

### Steps to Trigger Behavior

 1. add layer to show text in CJK fonts and set text-offset to it
 2. text-offset looks ignored

### Link to Demonstration

same style apllied to two versions maplibre-gl-js

v2.1.6: https://jsbin.com/regowuluwo/edit?html,output
v1.15.2: https://jsbin.com/duzinusoda/edit?html,output

**Comment by HarelM** [comment]
Thanks for taking the time to report this!
Here's the screenshots from the js bin: 1.15.2:
![image](https://user-images.githubusercontent.com/3269297/153812829-2dde3b7f-f754-49a5-bc17-aa0dc67456a1.png)
2.1.6
![image](https://user-images.githubusercontent.com/3269297/153812871-a0088ce0-c6e8-43f6-bf2a-eea47f17c539.png)
I don't recall changing anything in the area of text-offset though :-(

Since the style file is very large, is there any change you could create a style file that only contains this issue?
If you could do that it will help easing the process of creating a render test in order to make sure this won't break in the future.

**Comment by HarelM** [comment]
Thanks!! Sorry for nagging, but can you create a small geojson source with limited features (1-2) and use that so the entire code will be in that page (I.e. Inline style)?

**Comment by Kanahiro** [comment]
v2.1.6
https://jsbin.com/kikegoresi/1/edit?html,output

v1.15.2
https://jsbin.com/kiwuvudubi/edit?html,output

Are these good?
And I realize `text offset ignored` may be wrong because CJK-text is misplaced when vertical text-offset is zero.
You can see in above samples CJK fonts is anytime placed somewhat upper than alphabets.

**Comment by HarelM** [comment]
@Kanahiro Great! Thanks!

**Comment by Kanahiro** [comment]
https://github.com/maplibre/maplibre-gl-js/blob/925b85e33790dd232570cff9fc5c5925d6a6cdc9/src/render/glyph_manager.ts#L206

This looks caused by this line.
Although I'm not familiar with [tiny-sdf](https://github.com/mapbox/tiny-sdf), I think tiny-sdf metrics structure has been changed, is right?

We could adjust in interger-value manually but must be careful to [backport](https://github.com/mapbox/mapbox-gl-js/blob/e86256403f19b30590ee457aaa9ba871ab027792/src/render/glyph_manager.js#L255) `mapbox-gl-js`.

**Comment by HarelM** [comment]
Thanks for digging into this.
We have upgraded tiny-sdf from version 1.x to 2.x and I think this is what introduced these breaking changes.
unfortunately we can't backport the code from mapbox.
I'll see if I can open an issue in the tiny-sdf repo to see if they can guide us on how to solve this properly.
Thanks again for pushing this forward!

**Comment by HarelM** [comment]
I've opened the following issue.
https://github.com/mapbox/tiny-sdf/issues/44
Worst case, we can revert to version 1.x I guess...

**Comment by HarelM** [comment]
Quoting the relevant part of the above issue:
The adjustment GL JS uses is basically `top = glyphTop - 27`.
@Kanahiro can you check if this solves this issue and maybe create a PR with the fix?

**Comment by Kanahiro** [comment]
I've just published my PR, please check it.

**Comment by HarelM** [comment]
Thanks!!! I've added my comments there.
