### ISSUE TITLE
CI fails due to breaking changes in json import

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#1008]
See Node 16.14 breaking changes related to json.
We need to decide if we freeze the node version or risk such future breaking changes.
Currently I think it only applies to render tests (and maybe query).
`import info from './package.json' assert { type: 'json' };`

**Comment by HarelM** [comment]
Doesn't look like typescript accepts this.
I'll see if I can revert to 16.13 and avoid this breaking change...

**Comment by astridx** [comment]
Would it be a solution to use the option `version <=16.13`?

https://docs.npmjs.com/cli/v8/configuring-npm/package-json#version

**Comment by HarelM** [comment]
Yes, partially, render tests are still failing. I'll replace the images. See #1009

**Comment by birkskyum** [comment]
fixed in #1431
