### ISSUE TITLE
[Bug] Markers jump in 1 pixel after map zooming

### ISSUE THREAD

**Issue by khmm12** [maplibre/maplibre-gl-js#1014]
Greetings 👋

## The problem

I found weird markers behaviour. After map zooming they jump in 1px. 

<details>

<summary>gif</summary>

![2022-02-18 17 48 18](https://user-images.githubusercontent.com/4437249/154799165-1f0b31bf-ee18-41f6-b52c-636be015d917.gif)

</details>

## Reason

It happens because screen coordinates are rounded after map movement ([see](https://github.com/maplibre/maplibre-gl-js/blob/964bbef052cf787b7e00f6fa4eeca3e14f340828/src/ui/marker.ts#L467)).

Reproducible on:
- Macbook Pro 2015 15
- macOS, Google Chrome 98
- mapbox-gl v1 / maplibre-gl-js v1 / maplibre-gl-js v2

But it should be noticeable everywhere due to subpixel rendering.

## Solution

Round screen coordinates during movement taking into account [Window.devicePixelRatio](https://developer.mozilla.org/ru/docs/Web/API/Window/devicePixelRatio). Theoretically it should solve [stuttering during zooming](https://github.com/maplibre/maplibre-gl-js/blob/964bbef052cf787b7e00f6fa4eeca3e14f340828/src/ui/marker.ts#L464) (which happens on HiDPI screens only?).

```ts
const pixelRatio = (typeof window !== 'undefined' && window.devicePixelRatio) || 1;

export function roundPixel(pixel: number): number {
  return Math.round(pixel * pixelRatio) / pixelRatio;
}
```

```ts
 DOM.setTransform(this._element, `${anchorTranslate[this._anchor]} translate(${roundPixel(this._pos.x)}px, ${roundPixel(this._pos.y)}px) ${pitch} ${rotation}`);
```

**Comment by HarelM** [comment]
@khmm12 any chance you could create a PR for this? Preferably with a test to reproduce the issue.

**Comment by timokorkalainen** [comment]
Would this also be the reason why my markers keep wiggling when rotating a pitched map? Here's an example: https://youtu.be/eEmTnzdDWf0

I can also see the 1 pixel movement after zooming.

**Comment by HarelM** [comment]
I tend to say that these are different problems, but I'm not sure, there's not a lot of code there, and the round above does not happen in move event...

**Comment by timokorkalainen** [comment]
Thanks! If I get to investigate this more I will open another issue if necessary.

**Comment by Pheonor** [comment]
Why do not just replace the position round at the end of the movement with a round adapted to Hi-DPI screen with something like:
`            this._pos = this._pos.mult(window.devicePixelRatio).round().div(window.devicePixelRatio);`
