### ISSUE TITLE
Zoom center not under cursor when terrain is on

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#1024]
When zooming on a terrain 3d map, the zoom center is not under the cursor. I think the map zooms to the center of the map. This behavior is different from how MapLibre worked so far, where the geo position under the cursor would not change during zooming.

Steps to reproduce:

Go to https://wipfli.github.io/maplibre-terrain3d/#2.28/28.5/-35.63/0/21

Put cursor above USA

Zoom in

Instead of magnifying the US, it goes into the atlantic...

**Comment by wipfli** [comment]
Also happens when no terrain source is present. I wonder if we could add a render test / if there should not already be one which covers this behavior...

**Comment by wipfli** [comment]
Maybe the following failing browser test is related to this issue:

```
> jest -c ./jest.config.e2e.js ./test/integration/browser

 FAIL  test/integration/browser/browser.test.ts (7.153 s)
  browser tests
    ✕ chromium - Drag to the left (2162 ms)
    ✓ chromium Zoom: Double click at the center (1831 ms)
    ✕ chromium - CJK Characters (1887 ms)

  ● browser tests › chromium - Drag to the left

    expect(received).toBeCloseTo(expected, precision)

    Expected: -35.15625
    Received: 0

    Expected precision:    4
    Expected difference: < 0.00005
    Received difference:   35.15625

      77 |             });
      78 |
    > 79 |             expect(center.lng).toBeCloseTo(-35.15625, 4);

```

**Comment by HarelM** [comment]
I tend to agree that the failing test is a good indication of something that isn't right. I also thought it is related.

**Comment by HarelM** [comment]
Also, not sure if it is the same issue or not, but the following also doesn't work as expected:
1. Use pitch and don't look at the map straight from the top
2. Rorate the map from a mobile device using 2 fingers
3. At the end of the movement the map "jumps" a bit.

**Comment by HarelM** [comment]
I think the change in `handler_manager.ts` is the root cause of this issue.
Comparing the old code to the new code seems like there are some stuff different when not using terrain.
https://github.com/maplibre/maplibre-gl-js/blob/a2962024cac1f9dcad9ae43a95704d63b2f29523/src/ui/handler_manager.ts#L439L466
Also it might be that when using terrain the freeze part may not be the expected UX.
@prozessor13 I remember you wrote something about this, right?

If I add something like the following ugly code:
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/3269297/155858761-4f20cc5f-2746-4142-9bdf-92c8135dc28e.png">
I'm able to pass the test, but I'm not sure this is the right approach...

**Comment by prozessor13** [comment]
This are two different problems:

1) The small jump at the end of movement comes from two possible reaseons:
   * To get the geo-coordinate under the mouse-pointer i use a *coordsFramebuffer* where all tile coordinates are rendered as rgb-encoded values in a hidden framebuffer. So maybe in titled maps the rendered pixels are distorted by terrain and so the grabbed pixel is not as accurate as its need to be.
   * other possible reason is the new created `transform.recalculateZoom` method, which calculates the new zoomlevel in respect of the camera-height and the center-elevation.

2) `setLocationAtPoint` currently does not handle terrain. So i created a workaround in *handler_manager* that in 3d mode, the map is not dragged by the picked geo-coordinate, instead it will be dragged by pixel. For me personally, especially in fully tilted maps, this is a much more "natural" way to move the map. In cesium & mapboxgl2 i find it annoying to drag the horizon in one step into the map-center. I am always completely lose the orientation.
But this is definitely a big open issue, as well as calculate the 3D boundingbox, and even more complicated, implement `fitBounds3D`.

My personal opinion in these 2 things is, that they are not *major blockers* but definitely important to fix. I think with a sparring-partner i am able to implentent this issues, but without it will sure take a lot of time to digg into the math behind this problems.

@HarelM i will think about and test your changes next week!

**Comment by HarelM** [comment]
When using a mobile device, rotating the map jumps after every rotation, **I** believe this is a show stopper.
Feel free to experience this in the link @wipfli sent with the demo site.
When I tried it, I almost immediately said that I can't publish it to my users this way.
Since this is an opt-in feature we might consider merging this to `main` in order to reduce future merge problems etc, but from a UX perspective, IMHO, this is still not ready to be used in production.
Please do not consider this as a criticism to the amazing work you have done, and I did try to better understand the code in order to help fixing this, but it will take me more time to truly understand it in order to help right now.
I totally agree about the pixel movement instead of place movement you mention, it makes a lot more sense to move the map according to the pixel you selected and not the place to keep the user's orientation when no looking straight from the top.

**Comment by prozessor13** [comment]
No problem ;) I agree with you!

the problem of this is in `setLocationAtPoint` as well. This problem occours also on *"web-devices"*, when you tilt the map with a swipe effet. e.g. leave the mousebutton before mouse-movement ends. (do you know what i mean?)

On mobile devices you tilt and rotate both with two fingers, so technically you tilt always a litte bit when you rotate. And on mobile devices you always swipe a little bit, so the issue happens on mobile devices much much more often.

Solution: fix `setLocationAtPoint` or make a hack to disable tilt-swipe on mobile devices.

So, if there is no hurry, i will try to fix the issue.

**Comment by HarelM** [comment]
@wipfli is your github pages up-to-date? I don't seem to be able to reproduce this issue any more, so if this is not the latest version it's weird, if it is then it explain it.
Make sure you refresh the page properly to get the latest version...?

**Comment by wipfli** [comment]
Persists for me. Steps to reproduce on ubuntu chrome and firefox:

```
gh pr checkout 1022
npm ci
npm run build-dev
npm run start-server
``` 
Open http://0.0.0.0:9966/debug/terrain.html#11.53/47.2767/11.3279 

Put mouse cursor to top left corner of the map

Zoom in with ctrl+scroll

Map zooms to center of viewport. It should however zoom to the mouse cursor. 

I think this is why the browser test fails.

**Comment by HarelM** [comment]
Ahh, yes, sorry, this is the original issue you reported. I added another one which is not related apparently, my bad...

**Comment by wipfli** [comment]
I can confirm that in 2D mode the zoom works. I tried it with http://localhost:9966/debug/extrusion-query.html#4.26/45.14/16.35/10.4

As you said @prozessor13, in 3D the zoom still goes to the center of the viewport.

**Comment by wipfli** [comment]
Since zoom works as before in 2D mode, I think this is no longer a blocking issue for the terrain3d pull request.

**Comment by HarelM** [comment]
Agree.

**Comment by HarelM** [comment]
I think we should keep this open though to know that we still have an issue here in the 3D...

**Comment by HarelM** [comment]
@wipfli is the original post you created here still an issue?
BTW do we have an example of 3D in the docs repo?

**Comment by wipfli** [comment]
Yes, the zoom center in v2.3.0 is still at the viewport center and not under the mouse cursor.

There is no terrain 3d example in the docs and the docs is still at v2.1.9 which is the last version before the main release of the terrain 3d branch.

**Comment by Oreilles** [comment]
> 2. `setLocationAtPoint` currently does not handle terrain. So i created a workaround in _handler_manager_ that in 3d mode, the map is not dragged by the picked geo-coordinate, instead it will be dragged by pixel. For me personally, especially in fully tilted maps, this is a much more "natural" way to move the map. In cesium & mapboxgl2 i find it annoying to drag the horizon in one step into the map-center. I am always completely lose the orientation.

I find rather confusing that the “drag to pan" behavior is different depending on whether you have terrain enabled or not... On the aforementioned link https://wipfli.github.io/maplibre-terrain3d/#10.21/46.4984/9.9973/47.1/76, switching between the two modes completely changes the dragging experience. I think consistency should be prioritized over personal preferences - would it be possible to make the terrain-enabled dragging experience match the initial one ? Should a new issue be opened in that regard ?

**Comment by HarelM** [comment]
Please open a different discussion (not an issue at this point) on this, it's not related to this issue.

**Comment by Coneys** [comment]
Hello, is this issue fixed? I use 2.4 version of Maplibre gl and still scrolling on map with 3D terrain zooms to center instead of cursor position.
Should I wait for next release, or should it work already?

**Comment by HarelM** [comment]
There is a pre-release with this fix.

**Comment by paulsUsername** [comment]
Do you know will this fixed be merged soon?
