### ISSUE TITLE
[Terrain3D] Dips instead of peaks

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#1027]
Matterhorn is a dip instead of a peak!

https://wipfli.github.io/maplibre-terrain3d/#14.26/45.97677/7.65702/-175.9/59

![image](https://user-images.githubusercontent.com/53421382/155770816-1ee4879d-60cb-40e0-a86d-2b2fc927f774.png)

There are other locations with strange holes, too:

https://wipfli.github.io/maplibre-terrain3d/#12.84/46.55414/8.07538/106.5/46

https://wipfli.github.io/maplibre-terrain3d/#13.52/46.63727/8.0968/176.9/44

Is that a problem with the data or with the renderer?

**Comment by HarelM** [comment]
Are you sure this is not a problem with the tiles' data in any way?

**Comment by wipfli** [comment]
I am not... What would be a good way to debug this?

**Comment by HarelM** [comment]
Since these tiles are rgb you should be able to open a specific tile in some photo editor/viewer and see the color? I'm not 100% sure how easy this is...

**Comment by acalcutt** [comment]
I tested this against the TerrainRGB mbtiles I created and it looks fine there ( https://wifidb.net/demo/terrain_dips/test.html#14.26/45.97677/7.65702/-175.9/59 )

**Comment by prozessor13** [comment]
I think this is not a Terrain3D issue, instead a data issue. I will close the Issue.
