### ISSUE TITLE
[Terrain3D] What source encodings and types are supported?

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#1028]
From the debug example, I see that the source type `raster-dem` and encoding `mapbox` are supported. Do we also support other source types? For example, the cesium quantized mesh format https://github.com/CesiumGS/quantized-mesh?
```js
map.on('load', () => {
    map.addSource('terrain', {
        'type': 'raster-dem',
        'tiles': ['https://vtc-cdn.maptoolkit.net/terrainrgb/{z}/{x}/{y}.webp'],
        'encoding': 'mapbox',
        'maxzoom': 14,
        'minzoom': 4
    });
    map.addTerrain('terrain', {exaggeration: 0.33});
}); 
```

**Comment by HarelM** [comment]
Not sure this is about terrain but hill-shading in general, isn't it? Also I'm not sure this is an issue but more of a discussion...?

**Comment by prozessor13** [comment]
As i know `mapbox` and `terrarium` is supported. During development i made a `mtk` encoding, but i removed it and use `exaggeration: 0.33` instead.

Here is the documentation:
https://maplibre.org/maplibre-gl-js-docs/style-spec/sources/#raster-dem-encoding

I will close the issue.
