### ISSUE TITLE
[Terrain 3D] Implement horizon logic with respect of earthradius

### ISSUE THREAD

**Issue by prozessor13** [maplibre/maplibre-gl-js#1029]
If the horizon is visible, currently too much data is loaded with no benefit. (e.g. no one cares about details on the horizon).

Major tasks:
- [x] calculate horizon with some factor for the earth-radius
- [x] calculate far-clipping-plane

Minor tasks:
- [ ] update transform.coveringTiles to not load tiles behind horizon. UPDATE. I putted this to the minor tasks, because it effects only a very low amount of additionally processed tiles.
- [ ] reduce Symbol redering near horizon
- [ ] draw sky

I will make a checkin when the 3rd major task ist finished (may at the end of next week).

**Comment by prozessor13** [comment]
Yes you are right, earth-radius is not critical, and i already do a really pragmatic calculation :)

    // calculate pixel height of the visible horizon, multiplied by a static factor to simulate the earth-radius.
    // The calculated value is the horizontal line from the camera-height to sea-level.
    getHorizon() {
        return Math.tan(Math.PI / 2 - this._pitch) * this.cameraToCenterDistance * 0.85;
    }

**Comment by HarelM** [comment]
@prozessor13 this is now solved right? Can I close this issue?

**Comment by HarelM** [comment]
Closing this as I think this is solved, if this is not the case please let me know and I'll reopen.
