### ISSUE TITLE
Where can I report harassment?

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#103]
First, I don't feel harassed, don't worry. I just want to point out that in online conversations maybe somewhere in a hidden Slack room it can happen quickly that the tone is not appropriate or that people say things in an unnecessarily crude way. For me as an outsider it is really important that the conversations I find are friendly and welcoming. But if something bad happens, there should be a way of reporting it. Currently the CODE-OF-CONDUCT.md says that Be kind, thoughtful and respectul to everyone. This is a good start but not enough.

As a feedback I suggest to use a more complete code of conduct such as for example Contributor Covenant. It is important to nominate a person who is responsible for enforcing the code of conduct and to share a way of contacting them.

**Comment by rbrundritt** [comment]
To assist in pulling content together for a code of conduct, here is Microsoft's open source code of conduct page used for all Microsoft open source projects: https://opensource.microsoft.com/codeofconduct/

Feel free to reuse what you like. 

As for reporting issues, a possible idea is to have them report it to one of the members of the steering committee: https://github.com/maplibre/maplibre-gl-js/blob/main/COMMUNITY.md#steering-committee
