### ISSUE TITLE
[Terrain 3D] Fails with single raster layer

### ISSUE THREAD

**Issue by RNMBuser** [maplibre/maplibre-gl-js#1036]
Try replacing the style in the example with the following and see what happens:

`
style: {
        'version': 8,
        'sources': {
          'raster-tiles': {
            'type': 'raster',
            'tiles': [
              'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            ],
            'tileSize': 256,
          }
        },
        'layers': [
          {
            'id': 'simple-tiles',
            'type': 'raster',
            'source': 'raster-tiles',
            'minzoom': 0,
            'maxzoom': 22
          }
        ]
      } 
`

**Comment by HarelM** [comment]
Thanks for sharing your feedback!
Can you share more details on what's not working exactly? Maybe a screenshot? "the whole map goes wrong" is not a very good way to describe a problem...

**Comment by acalcutt** [comment]
I tried your example style and that is quite strange ( https://wifidb.net/demo/terrain_raster/test.html )

Testing the same page with my style, which includes a raster source works as expected ( https://wifidb.net/demo/terrain_raster/test2.html )

**Comment by wipfli** [comment]
Here is a working example:

https://wipfli.github.io/maplibre-terrain3d/osm-raster.html#12.5/46.70503/8.26163/72.8/44

```json
{
    "version": 8,
    "sources": {
        "raster-tiles": {
            "type": "raster",
            "tiles": [
                "https://tile.openstreetmap.org/{z}/{x}/{y}.png"
            ],
            "tileSize": 256,
        },
        "demotiles": {
            "url": "https://demotiles.maplibre.org/tiles/tiles.json",
            "type": "vector"
        }
    },
    "layers": [
        {
            "id": "simple-tiles",
            "type": "raster",
            "source": "raster-tiles",
            "minzoom": 0,
            "maxzoom": 22
        },
        {
            "id": "a-vector-layer",
            "type": "line",
            "source": "demotiles",
            "source-layer": "geolines"
        }
    ]
}
```

**Comment by wipfli** [comment]
It seems that terrain3d requires at least one vector layer. I added a vector layer above the raster layer and then it worked.

**Comment by wipfli** [comment]
Can someone try https://wipfli.github.io/maplibre-terrain3d/osm-raster.html#12.5/46.70503/8.26163/72.8/44 on safari on an iPhone or iPad? I have a hunch that it will crash there...

**Comment by samuel-git** [comment]
@wipfli your link works on Safari Mac and iPhone without crashing. While zooming/rotating works on Mac, on latest iOS Safari the viewport changes unexpectedly after release of two finger touch interactions. 
Reproduce:
1. Open https://wipfli.github.io/maplibre-terrain3d/osm-raster.html#12.5/46.70503/8.26163/72.8/44
2. Zoom in with two fingers or rotate with two fingers
3. Relase fingers from screen and the map position yankes somewhere else

**Comment by HarelM** [comment]
Two finger pitch issue is described here: #1024

**Comment by HarelM** [comment]
@RNMBuser can you check if the latest version solves this? and if so close this issue?

**Comment by HarelM** [comment]
Closing this as I think this is solved, if this is not the case please let me know and I'll reopen.
