### ISSUE TITLE
maplibre-gl-csp-worker.js referenced in docs does not exist

### ISSUE THREAD

**Issue by RowanTate** [maplibre/maplibre-gl-js#1042]
**maplibre-gl-js version**: 2.1.6

**browser**: N/A

The file referenced in the CSP document for the `mapboxgl.workerUrl` does not seem to exist

URL: https://unpkg.com/maplibre-gl@2.1.6/dist/maplibre-gl-csp-worker.js

![image](https://user-images.githubusercontent.com/69771917/156286559-0621d933-c6bc-439e-9df3-d974fa0c9ae6.png)

**Comment by wipfli** [comment]
Can you check if `v2.1.7` solves the problem?
