### ISSUE TITLE
Mapbox and Terrarium elevation tiles give different results

### ISSUE THREAD

**Issue by RNMBuser** [maplibre/maplibre-gl-js#1047]
Mapbox elevation tiles: 
<img width="994" alt="mapbox3d" src="https://user-images.githubusercontent.com/33594690/156788558-d1f26067-4656-41d2-b86b-4cd338dcc994.png">

Terrarium looks shallower:
<img width="993" alt="terrarium3d" src="https://user-images.githubusercontent.com/33594690/156788578-017f5d49-2259-4853-8ed6-a5abef250605.png">

**Comment by acalcutt** [comment]
Have you tried adjusting the exaggeration option? in the mapbox tiles I made I have to set exageration to 1, while the mtk example included I think sets exaggeration to 0.33.

map.addTerrain('terrain', {exaggeration: 1});    <--exaggeration in addTerrain
map.addControl(
        new maplibregl.TerrainControl({
            id: 'terrain',
            options: {
                exaggeration: 1    <--exaggeration in TerrainControl
            }
        })
    );

**Comment by RNMBuser** [comment]
It does work, but I though that it should work the same out of the box.

**Comment by acalcutt** [comment]
Untill recently,  mtk had its own encoding which was slightly different than the mapbox one. when you used the "mtk" encoding I'm pretty sure it did behave the same way with the exaggeration of 1

However, recently when they were trying to make the tests pass, the mtk encoding was removed and they started using the mapbox encoding instead with the lower exaggeration to make up for the difference in encoding.

so originally Terrain3d supported mapbox, terrarium, and mtk encoding support and they did behave the same way with  exaggeration being 1. but now that the mtk encoding option has been removed, and they are using mapbox encoding for the example, they had to adjust the exaggeration to make up for the encoding difference.

**Comment by acalcutt** [comment]
Here is an example with the old mtk encoding, before it was removed
( https://stackblitz.com/edit/web-platform-ouaala )

You can see in this exaggeration is 1, but the source terrain encoding is mtk, which was slightly different than the mapbox encoding.

**Comment by acalcutt** [comment]
I think if you omit the exaggeration option or set it to 1 the Terrarium and a real Mapbox encoded would be the same.

However, the maptoolkit source used is the example is not quite standard mapbox encoding and needs adjustment to exaggeration

**Comment by HarelM** [comment]
Is this a real issue or can this be closed?

**Comment by prozessor13** [comment]
To reduce irritation, it will be good to use a *terrainrgb* source with the standard mapbox encoding, so the demo-page uses `exaggeration: 1`. Any proposals which source to use?

Technically I think it can be closed.

**Comment by HarelM** [comment]
Closing this as I don't think there's something to fix here, please correct me if I'm wrong and I'll reopen.

**Comment by acalcutt** [comment]
@wipfli I know you mentioned this in the other thread but I didn't want to pollute that thread. 

I was wondering, to avoid confusion could we put "MTK" encoding back? was there a reason it was removed in https://github.com/maplibre/maplibre-gl-js/commit/84674ef7df31c1c209404d1015b3d30cb5f7e79d other than to make the tests pass?. It's really not a lot of code changes... I think the main one is the 

```
    _unpackMTK(r: number, g: number, b: number) {
        return ((r * 256 * 256 + g * 256.0 + b) * 0.03 - 10000.0);
    }
```
vs the mapbox
```
    _unpackMapbox(r: number, g: number, b: number) {
        // unpacking formula for mapbox.terrain-rgb:
        // https://www.mapbox.com/help/access-elevation-data/#mapbox-terrain-rgb
        return ((r * 256 * 256 + g * 256.0 + b) / 10.0 - 10000.0);
    }
```

It justs feels like putting MTK encoding back would at least make the example more proper, where exaggeration would be 1 with all sources.

**Comment by wipfli** [comment]
A good looking map with a exaggeration value of 1 is something I would support. Can you make a pull request against terrain3d?

**Comment by HarelM** [comment]
@wipfli @acalcutt where are we with this issue?

**Comment by acalcutt** [comment]
I think this can be closed personally. It was really more of a example issue since the original examples used MTK terrain which needed a lower exaggeration. Our current examples, [demotiles](https://github.com/maplibre/demotiles/tree/gh-pages/terrain-tiles) and [debug page](https://github.com/maplibre/maplibre-gl-js/blob/main/test/debug-pages/terrain.html) no longer use this lower exaggeration, so I think it will lead to less confusion. 

depending on the terrain used, exaggeration could be something to try and adjust, which did work for the user who opened this.

**Comment by acalcutt** [comment]
Just one note if anyone stumbles across this, the syntax has changed a bit for exaggeration, it low looks like this in the current version of maplibre.

```
map.setTerrain({source: 'terrain_source', exaggeration: 1}); <--exaggeration in setTerrain

map.addControl(
    new maplibregl.TerrainControl({
        source: 'terrain_source',
        exaggeration: 1 <--exaggeration in TerrainControl
    })
);
```
