### ISSUE TITLE
map.updateImage() does not update options.pixelRatio

### ISSUE THREAD

**Issue by cigone-openindoor** [maplibre/maplibre-gl-js#1052]
When wanting to update the pixelRatio, this code is OK:
```
                if (map.hasImage('blue-wall')) {
                    map.removeImage('blue-wall');
                    map.addImage('blue-wall', blue_wall_image, {
                        pixelRatio: ratio
                    });
                }
```
... But when trying in this way, just with updateImage(), the new pixelRatio is not taken into account:
```
                if (map.hasImage('blue-wall')) {
                    map.updateImage('blue-wall', blue_wall_image, {
                        pixelRatio: ratio
                    });
                }
```
So I suggest to take options.pixelRatio changes to really update the image info.

**Comment by HarelM** [comment]
Can you please share a JSbin or codepen with an example of the issue?

**Comment by cns-solutions-admin** [comment]
updateImage has no 3rd parameter with image options.

**Comment by HarelM** [comment]
It is not clear what is expected here, if this is an enhancement request, please elaborate, the current example is an incorrect usage of the API.
