### ISSUE TITLE
[Terrain 3D] queryRenderedFeatures doesn't work as expected when terrain is on

### ISSUE THREAD

**Issue by RNMBuser** [maplibre/maplibre-gl-js#1075]
See the following tackblitz (which uses the map click event that calls queryRenderedFeatures internally.

Click each point and see it highlighted. Press the terrain control and it doesn't work well any more.

https://stackblitz.com/edit/web-platform-ibrq3f

**Comment by wipfli** [comment]
Thanks!

**Comment by HarelM** [comment]
@RNMBuser can you check if the latest version solves this? and if so close this issue?
Thanks for taking the time to test this!!

**Comment by HarelM** [comment]
Closing this as I think this is solved. If this is not the case please let me know and I'll reopen.
