### ISSUE TITLE
Heatmap not working

### ISSUE THREAD

**Issue by prozessor13** [maplibre/maplibre-gl-js#1081]
There exists already a discussion about that: https://github.com/prozessor13/maplibre-gl-js/issues/46

**Comment by HarelM** [comment]
@acalcutt @prozessor13 does this issue still exists?

**Comment by acalcutt** [comment]
It works fine without terrain enabled and no longer gives an error, but heatmap still doesn't work right with terrain enabled.

Heres an example page
https://stackblitz.com/edit/web-platform-c7xcln?file=index.html

In this example initially terrain is off and the heatmap looks fine. If you change the pitch is still looks ok. However if you enable terrain and try to change the pitch. you can see the heatmap kind of floats and isn't really in the correct place.

**Comment by prozessor13** [comment]
Heatmap is still an open issue in terrain, and i think i will not find time to fix this in the near future. sorry!
If someone is motivated to implement it, i can act as a sparring partner.

**Comment by HarelM** [comment]
Assigned M bounty.
Link to parent Bounty: https://github.com/maplibre/maplibre/issues/189

**Comment by tempranova** [comment]
Hey there, I'm willing to take this one on!

**Comment by HarelM** [comment]
Enjoy!

**Comment by tempranova** [comment]
Unfortunately, after messing around with this a whole bunch, I think it's beyond my current understanding of how the library works! I'll have to ask to be unassigned from this one for now until I have some more experience. Apologies!

**Comment by HarelM** [comment]
No problem. Thanks for trying!

**Comment by HarelM** [comment]
There are some bounties related to writing tests for PRs that are missing tests but have new and good functionality, writing these unit tests should be fairly technical and shouldn't be too complicated.
It would be great if you could help there, it will also push forward the release of 3.0.

**Comment by dipakpatil1509** [comment]
Hey @HarelM, I would be glad to work on this issue. Can you please assign this issue to me?

**Comment by HarelM** [comment]
Done. Good luck!

**Comment by Samarth1696** [comment]
Hey, @dipakpatil1509 ! Are you still working on it?

**Comment by dipakpatil1509** [comment]
> Hey, @dipakpatil1509 ! Are you still working on it?

Hey, I am still working on this but not actively. If you are willing to take it, please assign it to your name...

**Comment by HarelM** [comment]
Let me know if I should assign this to someone else.

**Comment by Samarth1696** [comment]
Thanks for the update, @dipakpatil1509 . If you're open to reassignment, I'd be interested in taking on this issue. Let me know if you have any insights or progress you'd like to share before I start working on it.

**Comment by Samarth1696** [comment]
Yes, @HarelM . I'm interested in working on this issue. Could you please assign it to me?

**Comment by Samarth1696** [comment]
I have worked with map but not worked on map's core functionalities but I will figure it out somehow. Just need little guidance for that.

**Comment by HarelM** [comment]
Seeing the discussion in the PR, I'm increasing the bounty for this fix to large (L).

**Comment by Samarth1696** [comment]
Thank you!! ^^

**Comment by Samarth1696** [comment]
Adding my invoice link here:
https://opencollective.com/maplibre/expenses/217718
