### ISSUE TITLE
MapLibre alternatives in readme

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#1085]
I think it would be nice to list some alternatives to MapLibre GL JS in the readme. What comes to mind?

* Mapbox GL JS
* Leaflet
* OpenLayers
* Protomaps
* any others... ?

**Comment by HarelM** [comment]
Cesium

**Comment by wipfli** [comment]
Google maps

**Comment by nyurik** [comment]
TBH, I would only list open source implementations

**Comment by wipfli** [comment]
Kepler, deck.gl

**Comment by wipfli** [comment]
https://github.com/tangrams/tangram thanks @ambientlight for the hint

**Comment by jailln** [comment]
[iTowns](https://github.com/iTowns/itowns)

**Comment by HarelM** [comment]
@wipfli what's the status of this issue?

**Comment by wipfli** [comment]
Let's close this. Fortunately there is no second open-source fork of Mapbox GL JS at the moment which I know of...
