### ISSUE TITLE
Can't find typescript declaration file for maplibre-gl-style-spec?

### ISSUE THREAD

**Issue by achou11** [maplibre/maplibre-gl-js#1107]
Hi all! I'm trying to use `@maplibre/maplibre-gl-style-spec` but I'm getting a TS error saying that there's no declaration file for the module when I write this:

```ts
import { validate } from '@maplibre/maplibre-gl-style-spec'
```

Error:

```
Could not find a declaration file for module '@maplibre/maplibre-gl-style-spec'. '/Users/andrewchou/GitHub/digidem/mapeo-mapserver/node_modules/@maplibre/maplibre-gl-style-spec/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/maplibre__maplibre-gl-style-spec` if it exists or add a new declaration (.d.ts) file containing `declare module '@maplibre/maplibre-gl-style-spec';`ts(7016)
```

Here's the TSConfig (TS version 4.4.2):

```json
{
  "compilerOptions": {
    "lib": [
      "es2019",
      "es2020.promise",
      "es2020.bigint",
      "es2020.string",
      "ESNext.Promise"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": true,
    "noEmitOnError": true,
    "target": "es2019",
    "strict": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "pretty": true,
    "outDir": "dist",
    "typeRoots": ["./node_modules/@types", "./types"]
  }
}
```

Is there something I'm doing incorrectly in terms of config/usage? The expectation is that TS can pick up the types for the module.

Also, is this the proper module to use if I'm interested in using the TS style spec types?

**Comment by achou11** [comment]
After some poking around, my guess is that there needs to be some updates to the module's `package.json` configuration. Not an expert in this, but noticed that there's no `types` field in the `package.json`, and even if there was, it wouldn't have a declaration file to point that encompasses the module (`types.ts` is helpful but only for the style-spec type defs)

**Comment by HarelM** [comment]
There's a need to generate the types and then add them to the style-spec package like we are doing for the main package.
Can you clarify the use case of using just this package and not maplibre-gl? I'm honestly not sure why we are meditating this package...

**Comment by achou11** [comment]
ah makes sense! 

> Can you clarify the use case of using just this package and not maplibre-gl?

yeah, the [project](https://g
ithub.com/digidem/mapeo-mapserver) I'm working on is just a tileset + styles server and doesn't need the web-specific tooling of maplibre-gl. The specific package is helpful for working with the various style spec types in TS and also to do validation

**Comment by HarelM** [comment]
Cool, dts-bundle-generator is the tool we use for generating the types.
Feel free to send a PR that generates the types for the style-spec and I'll be happy to review it. :-)

**Comment by HarelM** [comment]
I've just create a PR to address this. This time with checking the generated types after creating after I was able to make the maplibre-gl code do the same :-)

**Comment by wipfli** [comment]
The types file was somehow not uploaded to npm. Maybe we need to adjust the publishing script? https://unpkg.com/browse/@maplibre/maplibre-gl-style-spec@17.0.0/dist/

**Comment by HarelM** [comment]
I guess the following line is needed now in style-spec publish:
https://github.com/maplibre/maplibre-gl-js/blob/84cb60f6f2ecc5802cc49ba347d2d43698baa59f/.github/workflows/release.yml#L56
I was under the impression postinstall takes care of that as part of npm ci command...

**Comment by HarelM** [comment]
I've opened a new PR to solve this, hopefully :-)

**Comment by wipfli** [comment]
`index.d.ts` is now in https://unpkg.com/browse/@maplibre/maplibre-gl-style-spec@17.0.1/dist/ :) Thanks @HarelM for fixing this stuff...
