### ISSUE TITLE
Add tilemap files support to avoid non-existing tiles loading

### ISSUE THREAD

**Issue by tapok26** [maplibre/maplibre-gl-js#111]
## Motivation

I have an issue with a vector tile source that contains some data for some country:

Vector tiles server has tiles for country's capital at 12 zoom level.
Other region's tiles exist only for <= 10 zoom level.

If I set `maxzoom: 12` for my source, map works well, but only for capital region.
I see blank map for non-capital regions.

## Design Alternatives

As a workaround I can add 2 sources (specifying `maxzoom: 10` for the first one and `minzoom: 10, maxzoom: 12, bounds: [capital-bounds]` for the second ) and duplicate all layers for them.

Unfortunately it generates a new error - layers overlay.

## Design

I want maplibre to add new optional property for sources - `tilemap` that will specify an URL to load it.
It could be cumbersome, but it will solve the root issue

https://developers.arcgis.com/rest/services-reference/vector-tilemap.htm

**Comment by JannikGM** [comment]
I believe you could handle this by using the transform request API: https://docs.mapbox.com/mapbox-gl-js/api/properties/#requestparameters

I'm not sure if it already supports aborting a request, but even if it can't, then you could re-route it to a local Blob URL with an empty tile (or point at a `/empty.vtf` on the server and hope that network caching is enabled).

That said, the whole "only fetch specific tiles" has more problems: mapbox must be handle to properly handle different zoom levels at the same time and a globally configured overscale might not be suitable.

**Comment by HarelM** [comment]
I tend to agree this is a special use case that can be "worked around". Either by the above transformRequest or the addProtocol.
Or simply generate all tiles to zoom 12, it shouldn't be too complicated...
I'm in favor of closing this issue...

**Comment by tapok26** [comment]
I've tried to make a workaround with transformRequest option, but it had no results.

Every time mapbox try to load 12-level zoom tile for non-capital region I change request in order to load appropriate 10-level zoom tile.

Such a way occurs tile duplications on my map.
The tiles with 10 zoom level are put in the places where tiles with 12 zoom level is supposed to be.

¯\_(ツ)_/¯

**Comment by HarelM** [comment]
Hmm... Interesting.
I would say that generating zoom 12 is probably the best option.
I'm not sure what was the implementation of transform Request but you might need to regenerate a zoom 12 tile that is part of the zoom 10 tile.
Also you might consider using the new addProtocol method...

**Comment by JannikGM** [comment]
> Every time mapbox try to load 12-level zoom tile for non-capital region I change request in order to load appropriate 10-level zoom tile.

That won't work. Instead, you have to make the request fail, so mapbox is forced to use another zoom level.
However, that other zoom level must have been loaded into mapbox already, and your overscale must be configured to allow using it on another level. There are a bunch of caveats as explained in my previous comment.

>  Also you might consider using the new addProtocol method...

That'd be interesting, but it *probably* has the same issues as the transform request API: you can reject / can filter tiles, but you can't redirect tiles / can't force adding tiles?

**Comment by JannikGM** [comment]
Reopening.

I still believe this is a valid motivation and maplibre should be able to handle this use-case.

I'm not sure if direct tilemap support is really necessary though. I think focus should be a on good underlying API which could easily be used to implement this feature.
We also had similar discussions about manually pre-fetching tiles (https://github.com/AbelVM/maplibre-preload) which is not ideal because it appears to be too hard to inject tiles or filter tile requests. Even if it's possible to do this using one of the existing features (custom-procotols maybe?), we have a documentation issue as there's no good example on how to handle this.

**Comment by wipfli** [comment]
I think it is OK to close this. @tapok26 I can recommend https://github.com/onthegomap/planetiler for custom tile generation.
