### ISSUE TITLE
ContextMenu event is not triggered on a long press on mobile

### ISSUE THREAD

**Issue by paulgreg** [maplibre/maplibre-gl-js#1125]
**maplibre-gl-js version**: 2.1.7

**browser**: Chrome Mobile

### Steps to Trigger Behavior

 1. declare a contextmenu event on a map
 2. do a long touch on a mobile device
 3. contextmenu event is not trigerred

### Link to Demonstration

https://jsfiddle.net/paulgreg/ksw5jxec/1/

```
var map = new maplibregl.Map({
container: 'map',
style: 'https://demotiles.maplibre.org/style.json'
})
map.on('contextmenu', () => alert('contextmenu event works'))

```

### Expected Behavior

Doing a long press on the map should display an alert with text 'contextmenu event works'.

On a desktop browser, a right click is triggering that event.

Note : it is a regression on mapbox-gl JS since version 1.10 (see [issue 10179](https://github.com/mapbox/mapbox-gl-js/issues/10179))

### Actual Behavior

Nothing is happening.

**Comment by HarelM** [comment]
Duplicate if #373

**Comment by Caerbannog** [comment]
The problem is still present in Maplibre v3.0.1:
https://jsfiddle.net/v7Ldwzfu/1/
