### ISSUE TITLE
Change CustomLayerInterface onRemove and onAdd to required

### ISSUE THREAD

**Issue by nreese** [maplibre/maplibre-gl-js#1126]
CustomLayerInterface renderingMode, onRemove, onAdd, and prerender are marked as required in typescript but are optional in documentation and implementation.

[Review comment](https://github.com/maplibre/maplibre-gl-js/pull/1122#issuecomment-1078194303) for [PR to type CustomLayerInterface renderingMode, onRemove, onAdd, and prerender optional](https://github.com/maplibre/maplibre-gl-js/pull/1122) suggested making onRemove and onAdd required. Since this change would be a breaking change, lets move the conversation to this issue instead of typescript fix PR.

**Comment by drwestco** [comment]
I'll argue for the -1 side. When writing a class that implements this interface, being forced to stub out one or more of these methods when the class has nothing to do for that action is an unwelcome burden. I can see `renderingMode` and `onAdd` almost always being used, but not so for `prerender` and `onRemove`.

**Comment by nreese** [comment]
-1 for the change.

API has been stable for a while with no one asking for any changes. I think the typescript types just need to be updated to reflect existing use of optional in documentation and implementation.

**Comment by HarelM** [comment]
Not a very interesting issue...
Closing...
