### ISSUE TITLE
Raster layers use low resolution tiles 

### ISSUE THREAD

**Issue by RNMBuser** [maplibre/maplibre-gl-js#1137]
When changing the view angle, the raster layers uses low-z tiles. This is a real problem for sites using raster tiles.

Steps to reproduce: use the usual 3D Terrain demo, and change the style as following:

    style: { 'version': 8, 'sources': { 'raster-tiles': { 'type': 'raster', 'tiles': [ 'https://tile.openstreetmap.org/{z}/{x}/{y}.png' ], 'tileSize': 256, } }, 'layers': [ { 'id': 'simple-tiles', 'type': 'raster', 'source': 'raster-tiles', 'minzoom': 0, 'maxzoom': 22 } ] },

The screenshot was taken at : terrain.html#12.06/47.31596/11.40244/-9.2/49

<img width="1458" alt="Screen Shot 2022-03-31 at 13 57 31" src="https://user-images.githubusercontent.com/33594690/161043301-7b637eed-1bde-4213-9e79-182021246627.png">

**Comment by prozessor13** [comment]
I think the decrease of zoom-level (= Level of Detail) in relation of the distance to the camera is too agressive. All the code is in transform.coveringTiles, but currently i have no time to dive into this problem.

**Comment by RNMBuser** [comment]
@prozessor13 Does this affect only raster tiles or vector tiles as well?

**Comment by prozessor13** [comment]
duplicate https://github.com/maplibre/maplibre-gl-js/issues/1540. Closing this issue.
