### ISSUE TITLE
Map is being corrupted after moving to a terrain mode with raster tiles 

### ISSUE THREAD

**Issue by comlib1** [maplibre/maplibre-gl-js#1162]
Hi team, thanks for the great work!

I have started testing the terrain branch lately and I'm having some issues with the combination of raster tiles + clustered symbol layer.

**Configuration:** It was tested with several terrain configurations and sources and it's always happening.

**Version:** I have tested it in the latest code in the `terrain3d` branch 

There are 2 main issues:

1. When changing to a terrain mode, I'm adding a line to the map and a few markers, suddenly a half-transparent layer is added to the map and every Symbol feature on the map is not working anymore... Symbol icons are not loaded and a cluster circle becomes a strange dot on the map... It always happens when I'm changing to terrain mode and I start adding the markers and lines to the map. In 2d mode, it never happens... 
2.  When zooming in and the pinch is around 50... the tiles at the bottom of the map are not loaded and an empty white area is presented.

Adding screenshots:
**Before the map is being corrupted:**
<img width="665" alt="Screen Shot 2022-04-06 at 8 15 14" src="https://user-images.githubusercontent.com/103095083/161903888-f4723077-29f7-4268-9c92-706abbdec574.png">

**After the map is being corrupted**(dots instead of clustered circle and a white half transparent layer):
<img width="549" alt="Screen Shot 2022-04-06 at 8 14 06" src="https://user-images.githubusercontent.com/103095083/161902986-1bf5090b-d5f9-467b-9e66-2486f896bd32.png">
<img width="827" alt="Screen Shot 2022-04-06 at 8 24 15" src="https://user-images.githubusercontent.com/103095083/161903018-52a663f6-1fea-4a1f-a5a5-03773ba6a7c0.png">

**The white area in the bottom:**
<img width="1144" alt="Screen Shot 2022-04-06 at 8 37 46" src="https://user-images.githubusercontent.com/103095083/161903203-8187fe25-c417-40ac-a9da-af23272b1f93.png">

Thank you all!

**Comment by HarelM** [comment]
Please link to a stackblitz or jsbin so we will be able to reproduce the issue.

**Comment by comlib1** [comment]
Hi, so after testing it again it seems like it's not related only to the terrain functionality.
It's happening randomly when I'm adding a new line to the map and sometimes (but more rare) only when im just scrolling the map.
I wasn't able to reproduce it on `stackblitz` its probably may relate to my environment... what may be the reason for that? i was mostly concerned about the half-transparent layer which added to the map. 
It also happened when I used a vector layer but this time it wasn't only the half-transparent layer but all the symbols in the map were corrupted.  
I don't see any errors in the console.
Is there any option to set a debug mode for the logs to see more logs from the maplibre?

I'm adding screenshots before and after:
**Before:**
<img width="707" alt="Screen Shot 2022-04-07 at 9 37 33" src="https://user-images.githubusercontent.com/103095083/162135686-65bfc47b-0028-4d1e-9db5-300a2ae7d851.png">

**After:**

<img width="723" alt="Screen Shot 2022-04-07 at 9 37 19" src="https://user-images.githubusercontent.com/103095083/162135723-82b0183c-a704-4e75-8165-39a0addb1b0e.png">

**Comment by wipfli** [comment]
Can you share your code?

**Comment by HarelM** [comment]
There's no debug logs, you can use the dev js file in the npm package so the sources are easily read, but if there's no console error then it might not be a maplibre error.
Your best bet would be to create a minimal reproduction using stackblitz/codepen/jsbin of this issue, otherwise there's not much we can do to help...

**Comment by comlib1** [comment]
Ok, so I have some direction.  when I'm reproducing it and then start adding markers to the map in terrain mode, I'm getting the following error:
```
maplibre-gl.js?c951:54057 Uncaught TypeError: Cannot read properties of undefined (reading 'unproject')
    at eval (maplibre-gl.js?c951:54057:1)
```

In the dev source its the following code:
```
        if (this._map.style && this._map.style.terrain && !this._opacityTimeout)
          this._opacityTimeout = setTimeout(() => {
            const lnglat = this._map.unproject(this._pos);
            const metresPerPixel = 40075016.686 * Math.abs(Math.cos(this._lngLat.lat * Math.PI / 180)) / Math.pow(2, this._map.transform.tileZoom + 8);
            this._element.style.opacity = lnglat.distanceTo(this._lngLat) > metresPerPixel * 20 ? '0.2' : '1.0';
            this._opacityTimeout = null;
          }, 100);
      }
      /**
```
<img width="1024" alt="Screen Shot 2022-04-07 at 21 28 05" src="https://user-images.githubusercontent.com/103095083/162271969-eb6e86f9-2864-4e0f-babd-a4cd822600f3.png">

**Comment by comlib1** [comment]
Hi, Any idea? 
Another thing I tell is that every time it's happening all the Symbols in the mab is not printed well. for example, if I have a line on the map with width and color, it's being printed but without the color and width and a thin black line is printed on the map without its styling, and if there are symbols across the line (like dots and arrows) they are not printed as well.. any chance it's relating to CSS?  are symbols on the map have any connection to the CSS? how did they load? and what may be the cause for them to be corrupted?

**Comment by wipfli** [comment]
I have a hard time understanding the problem. Please create a minimal example on stackblitz or similar which reproduces the issue you have.

**Comment by wipfli** [comment]
I will close this issue for now. Feel free to re-open it once you have a minimal example that allows others to reproduce the problem.

**Comment by comlib1** [comment]
@wipfli So finally I managed to resolve this issue... and I think it is something that is worth documenting or being aware of...
When using Vuejs and the map is stored in the state ... you might find your map or map styles broken.
It occurs when vuejs attempts to make your maplibre object observable...
So the solution will be whether not to store the map in the state or, **before** adding it to the store, add the following field:  `map._isVue = true `
Credits to this [issue](https://github.com/mapbox/mapbox-gl-js/issues/6872) in the Mapbox project.

**Comment by HarelM** [comment]
This is specific to a certain wrapper and not to this project.
The following tutorial for example (first google search results) might have this documented, if not, you can ask them to add it there:
https://documentation.maptiler.com/hc/en-us/articles/4413873409809-How-to-display-a-map-in-Vue-js-using-MapLibre-GL-JS
Or maybe add this to the following wrapper:
https://github.com/razorness/vue-maplibre-gl
