### ISSUE TITLE
Fix canvas source not working with some canvas size

### ISSUE THREAD

**Issue by rinfante77** [maplibre/maplibre-gl-js#120]
To reproduce the error:

1) Create a canvas source and raster like https://docs.mapbox.com/mapbox-gl-js/example/canvas-source/ 
2) replace the canvas with one with the following dimensions: 

<canvas id="canvasID" width="256" height="256">Canvas not supported</canvas>

The canvas should be unavailable.

**Comment by HarelM** [comment]
Some characters are not presented in this issue.
Please use backtick: "`" on code parts

**Comment by HarelM** [comment]
Also the issue is not clear, can you provide a full jsbin/codepen reproduction?

**Comment by rinfante77** [comment]
Reopened by mistake.
