### ISSUE TITLE
Implement new logic for displaying the MapLibre logo

### ISSUE THREAD

**Issue by klokan** [maplibre/maplibre-gl-js#121]
In #82 the new MapLibre SVG logo was pushed - on request of @nyurik 

Currently, it is only displayed if a TileJSON of sources contains "mapbox_logo"
https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/control/logo_control.js#L64

We may want to define a new logic for the purpose of MapLibre open-source project.
Perhaps having in the constructor the logic to turn it on/off - with an agreed default?

Maybe we can push into TileJSON spec the URL to the logo to be displayed?

**Comment by dbrgn** [comment]
The source mentions:

```js
/**
 * A `LogoControl` is a control that adds the Mapbox watermark
 * to the map as required by the [terms of service](https://www.mapbox.com/tos/) for Mapbox
 * vector tiles and core styles.
```

I may be blind, but which part of the [TOS](https://www.mapbox.com/legal/tos/) actually mentions this logo requirement? Furthermore, if it's still there, would the MapLibre logo fulfil that?

The attribution is already present in the lower right corner ("© Mapbox © OpenStreetMap"), shouldn't that be sufficient?

**Comment by jbelien** [comment]
The link on the logo also still sends to https://www.mapbox.com/ 
https://github.com/maplibre/maplibre-gl-js/blob/c47d053f010fe221a511a44a44333b5d29e447dc/src/ui/control/logo_control.js#L33

**Comment by wipfli** [comment]
Thanks for pointing this out @jbelien. Would you like to open a pull request for this?

**Comment by habi** [comment]
I tried to make a PR correcting the link in the line that @jbelien found.

**Comment by tunnelpuzzle** [comment]
Is there an update on this? Right now the Maplibre logo control is displayed if you use a Mapbox data source which doesn't really make sense.

**Comment by HarelM** [comment]
@tunnelpuzzle can you make a PR to fix this? Better if you could do it over the typescript branch as this branch will hopefully get into main soon.
