### ISSUE TITLE
Non-Earth maps/projections (flat maps)?

### ISSUE THREAD

**Issue by GarrettAlbright** [maplibre/maplibre-gl-js#1228]
**maplibre-gl-js version**: All

### Question

I'm investigating MapLibre as a more performant alternative for Leaflet for a client project (in particular we're finding maps which have very many markers are rather slow and cumbersome to use). The project does not display Earth maps; rather, maps representing levels or "worlds" in video games with markers indicating locations of collectible items and such. (We host our own tilesets for the maps.) Thus the maps never represent anything other than flat rectangles. We store marker locations as X, Y points in our database corresponding with the map being shown at the maximum zoom level.

With Leaflet this is possible using the [Simple CRS](https://leafletjs.com/examples/crs-simple/crs-simple.html), but as far as I can tell, this is not possible in MapBox; even if we cajoled the `maxBounds` option to force the map to only show an area much smaller than the real world, we still have the issue of MapLibre only using a map projection which would not show the lines of latitude and longitude as a grid of perfect squares, such that we couldn't accurately position our markers according to the X, Y locations we have stored for them.

Am I wrong? Is there a way to display an undistorted "flat" map in MapLibre and accurately place our markers without too much trouble?

**Comment by wipfli** [comment]
That is an interesting use case. Maybe your question is related to custom projections. https://roadmap.maplibre.org/c/91-custom-coordinate-system-epsg-non-mercator-projection

**Comment by wipfli** [comment]
By the way you might want to pack the points into vector tiles with something like tippecanoe or planetiler...

**Comment by GarrettAlbright** [comment]
> That is an interesting use case. Maybe your question is related to custom projections. https://roadmap.maplibre.org/c/91-custom-coordinate-system-epsg-non-mercator-projection

I do think allowing for a different projection is part of this, yes. MapBox has an [equirectangular projection](https://docs.mapbox.com/mapbox-gl-js/guides/projections/#equirectangular) which seems like it'd do what we need.

> By the way you might want to pack the points into vector tiles with something like tippecanoe or planetiler...

I'm not sure what you're saying here. Are you saying we should make vectorized tiles instead of just using the bitmaps we're using now? While that might be a plan for the future, our current goal is just to find a faster mapping system which can match the functionality of what we currently have. From there we can start considering improvements like that. :)

**Comment by HarelM** [comment]
Is this a duplicate of #168?

**Comment by GarrettAlbright** [comment]
> Is this a duplicate of #168?

Partially, though importantly, for my needs, "another way to project the globe" is not what I'm asking for; I'm asking for "a way to show a flat plane." Or, if it helps to think of it that way, "a way to show a map that is already projected" can also work.

By the way, in case it helps anyone else, what I ended up doing for my client is keeping Leaflet but using [Leaflet.PixiOverlay](https://github.com/manubb/Leaflet.PixiOverlay) to show markers. This uses [PixiJS](http://www.pixijs.com) for drawing stuff which renders to either WebGL or the browser canvas; we ended up forcing the canvas approach because most of our markers used different marker images and this was causing issues with WebGL not wanting to use that many textures.

**Comment by HarelM** [comment]
I think #168 is basically it, if you can specify coordinates system which will create flat plane you're good to go.
Also, as mentioned in the linked issue d3 can also help here I believe.
Feel free to add you use case to the linked issue.
Closing...

**Comment by dberardo-com** [comment]
Is it possible to load a PNG and use that as a plane? I need to place markers on a PNG and allow the user to zoom in.

I have different "layers" of pngs and even some svgs, so I would like to use a map like system that can handle layers in a x/y reference plane. 

Is this something mapgl can handle or is it required for everything to have lat,long coordinates?

**Comment by HarelM** [comment]
Yes, you can split the png into tiles and load it as a raster source, there are tools that can do that for you too.

**Comment by dberardo-com** [comment]
You mean something like this? https://stackoverflow.com/questions/70873570/mapbox-raster-image-quality-changes-with-zoom-level/70873733

So if I got it right, I can include any PNG easily as a raster without the need of cutting it into tiles, but this will screw up resolution in case of zooming I guess, for which o might have to split it into tiles.

Do raster layers also accept svgs or is that another layer?

And how about the x,y coordinate system? Is Cartesian a valid system in mapgl?

**Comment by HarelM** [comment]
You can also use image source. None of those support svg.
you can use screen coordinates or mercator as x,y.
But going forward, this isn't the right place to take about it. 
You can open a discussion or post a question on our slack channel.

**Comment by dberardo-com** [comment]
alright @HarelM  i have tried to provide some more info here, hope to get some help: https://github.com/maplibre/maplibre-gl-js/discussions/6081
