### ISSUE TITLE
Configurable general ErrorEvent handler

### ISSUE THREAD

**Issue by hodossy** [maplibre/maplibre-gl-js#1230]
## Motivation

If any error happens, it is just printed to the console. Listening to such events is possible, but you need to know the type of the error in advance to do so, moreover it can be lots of different types. Using the library on mobile without console access makes it difficult to track app errors related to maplibre-gl.js. I am using Angular, where we can collect any error logs via a global error handler, but we cannot channel maplibre errors there.

## Design

```javascript
var map = new Map({});
map.onerror = (err) => console.error(err); // do whatever you want
// or
var map = new Map({onError: (err) => console.error(err)});
```

### Implementation

Change https://github.com/maplibre/maplibre-gl-js/blob/main/src/util/evented.ts#L139 

(I am not sure about C++ implementation)

What is you opinion on this? Is it something you would accept to the codebase?

**Comment by HarelM** [comment]
Basically, all the events are documented and you could register to all of them and achieve this.
Having said that, there are methods that can throw and they won't be part of these events, so I don't think this is super simple in general.
I would recommend creating a plugin for this.
If many will find it useful we could incorporate this into this library.

**Comment by hodossy** [comment]
Sure, I understand. I will then use the currently available `error` listener for now.
