### ISSUE TITLE
Restrict heatmap to an arbitrary area

### ISSUE THREAD

**Issue by vadmbertr** [maplibre/maplibre-gl-js#124]
Hi!
Thanks a lot for this fork.

I'm using the heatmap layer and I would like to restrict the coloring to an arbitrary area (let say a polygon shape). To make it clearer: inisde the polygon coloring would follow the heatmap-color property of the layer and outside the polygon I'd like to have a transparent or greyed color. I also attached a picture reflecting it (note that the actual heatmap I have inside the polygon is quite different).
Is there any way I could do it?

Vadim

![heatmap](https://user-images.githubusercontent.com/36510417/112818037-61bfb000-9083-11eb-957c-bc714020bf89.png)

**Comment by nickpeihl** [comment]
This appears to be a user question, and I think we'd like to direct questions to the [Discussions](https://github.com/maplibre/maplibre-gl-js/discussions) section. Would you be willing to post this there instead? This allows us to use issues for verified bug reports and feature requests.

If you want to post this as a feature request, I think we might need to know more about the use case. Why is this necessary and how might others benefit from it?
