### ISSUE TITLE
A bug with `.off()` method being ignored when called in a short time after `.on()`?

### ISSUE THREAD

**Issue by smellyshovel** [maplibre/maplibre-gl-js#1240]
**maplibre-gl-js version**: Latest (2.1.9)

**browser**: Chrome 99

### Steps to Trigger Behavior

 1. Try to frequently (multiple times a second) register and unregister a click event listener.

### Link to Demonstration

https://codesandbox.io/s/quizzical-bouman-vw2g8o?file=/src/index.js

### Expected Behavior

Registered event listeners should be unregistered 

### Actual Behavior

Seems like event listeners are not detached properly. If you try to slowly step by step register an EL, click a map, unregister it, then everything works fine. Though if you do that frequent enough, the ELs don't get unregistered and that leads to `click`s being captured even after the `off` method was invoked.

https://user-images.githubusercontent.com/9782236/169579830-62cdf986-d083-4a6e-9b97-d1a170fe74b1.mp4

**Comment by smellyshovel** [comment]
It looks like a bug to me, though I look at the `Evented`'s sources and I don't see no asynchronicity going on there, so I doubt any racing-condition could be the case. Is that me missing something?

**Comment by smellyshovel** [comment]
There's also [this line](https://github.com/maplibre/maplibre-gl-js/blob/main/src/util/evented.ts#L8). But does it really do what it's intended to?

**Comment by HarelM** [comment]
I'm not sure the code in code pen is without bugs.
Defining the function when registering the event doesn't create a new function every time?

**Comment by smellyshovel** [comment]
@HarelM indeed moving the function outside solves the issue, though I'm wondering why it's so...

**Comment by HarelM** [comment]
Also the relevant line you linked can be easily checked in the console :-)

**Comment by smellyshovel** [comment]
@HarelM thanks for the tip anyways, I think that the issue is indeed not maplibre-related. The Evented interface is simple enough not to provide any bugs. Sorry for bothering :)
