### ISSUE TITLE
Parent child tile loading policy

### ISSUE THREAD

**Issue by am2222** [maplibre/maplibre-gl-js#1243]
**maplibre-gl-js version**: latest

### Question
Hi,
so I have faced this problem several times in different projects, lets say we have a set of points, we convert them to the TMS vector tiles, so clearly each parent tiles includes data from its children, when we load them on the map using tms tiles in each zoom level we are loading duplicate data since the parent tile might have been loaded before, Is there any way to avoid this behavior? We can cache the loaded tiles and check their relation with the newly requested tiles, but I am not sure if this is a good solution.

**Comment by HarelM** [comment]
Can you elaborate with a use case or an example?
This is a bit too vague for me...

**Comment by candux** [comment]
@am2222 I'm not sure if I understood you correctly. You convert points to Vector Tiles for zoom-levels `a` to `b`. If you browse the map on zoom-level `b` and zoom out to `a` you load the same data again and you want to avoid that, correct?

As far as I know, there is no way to avoid loading that duplicated data. In most cases you have different kind of data in tiles on different zoom-levels.

If tiles on zoom-level `a` contain all points anyway, you can just only export till level `a`. Maplibre will load the parent tile if you are on a higher zoom-level. Notice that you will have worse precision in this case. Depending on your levels and use-case this can be a problem.

**Comment by am2222** [comment]
Hi @HarelM ,
Sorry for the late reply,
So lets say we have a point layer in database with `n` point,  We convert them into the tiles. lets say we don't do any simplification on any of zoom layers. So technically we will have all the point in first tile (0,0,0) and as we zoom in number of points in each tile decreases. Data in the children tiles are the same as the parents only less since their area is 1/4 of the parent tile.
Now if someone wants to see your map, if they start from zoom 0, they technically download and rendering the entire data, So we don't need to send the requests to the server anymore since parent tile (in this case 0,0,0) has already downloaded data and we just need to query parent tile to be able to access data for the children tiles. 
I guess this scenario can be done in the source layer, for each requested tile, we check if its parent tiles are loaded we query data from that tile instead of sending a query to the server.
However, I am not sure of this method actually helps with performance or not, clearly if the vertical distance (child's zoom - parent's zoom) is higher than certain amount it can be faster to request server instead of querying lots of data from the tile.

**Comment by am2222** [comment]
@candux Thanks for your reply, yes that is what I meant, So that is actually a good idea to set `maxlevel` and maplibre takes care of that over zoom renders, But I am not sure why precision changes here? Does maplibre uses rendered tiles for overzoom rendering or it uses the original point objects?  If it uses original point objects It should not effect the precision, correct?

**Comment by wipfli** [comment]
The precision of the location of a point in Mapbox Vector Tiles depends on the zoom level, see https://docs.mapbox.com/help/glossary/zoom-level/#zoom-levels-and-geographical-distance. For example, if you have a point on zoom level 8 and you are at the equator, the latitude will be +/- 300 m precise. The same point at zoom level 14 would be +/- 5 meters precise.
