### ISSUE TITLE
Adjusting the position of attribution to keep it visible

### ISSUE THREAD

**Issue by ellenhp** [maplibre/maplibre-gl-js#1255]
**maplibre-gl-js version**: 2.1.9

### Question

I posted a maps project I'm working on to Hacker News and several people correctly complained that my OSM attribution wasn't working correctly when some of my UI covered up the map. Is there any way to move the map attribution around to accommodate a place card being shown over the bottom of the map? I can't use either of the top positions do to UI up there either. I tried setPadding and it seems to offset what MapLibre considers to be the center of the map, but it doesn't move the attribution so it can be seen.

See: https://github.com/ellenhp/headway/issues/3

**Comment by acalcutt** [comment]
You could move attribution to the top like this https://maplibre.org/maplibre-gl-js-docs/example/attribution-position/

Basically you disable the default attribution control, then add your own to whatever corner you would like

**Comment by wipfli** [comment]
Love maps discussions on hacker news. Can you share the link?

**Comment by ellenhp** [comment]
Like I said above, neither of the two top positions will work for me, and both bottom positions are covered by the place card. It's extremely difficult for a non-frontend developer like me to get maplibre to have a non-zero height other than by making it take the entire screen with `100vh`, so I'm kind of at a loss for how to do this.

**Comment by tuukka** [comment]
> Love maps discussions on hacker news. Can you share the link?

https://news.ycombinator.com/item?id=31536217

> I tried setPadding and it seems to offset what MapLibre considers to be the center of the map, but it doesn't move the attribution so it can be seen.

I have noticed that many (mobile) maps open panels on the bottom of the map and compensate by moving the bottom controls upwards. I think it should be separate from the padding though: there should be padding between the panel and map content, but some controls should be right above the panel.

Incidentally, another reason why the attribution is not visible in mobile browsers is `height: 100vh` and is being discussed at #1253.

**Comment by ellenhp** [comment]
I was able to fix this with some javascript hacks. For anyone who finds it in the future, [this](https://github.com/ellenhp/headway/commit/3c89bfa8ac71133730afadc94e43e5e394a2f9bd) might be a helpful example. I haven't yet tested on mobile so I might still be affected by #1253

**Comment by ellenhp** [comment]
I think this can be closed now. It may be appropriate to spin off a feature request though because this should be much easier than it is, IMO. I would consider taking a look myself but I'm an awful web developer so I'm not sure I'd get anywhere.
