### ISSUE TITLE
SVG images without explicit `width` and `height` attributes in the `svg` tag will not display in Firefox

### ISSUE THREAD

**Issue by JannikGM** [maplibre/maplibre-gl-js#126]
SVG images without explicit `width` and `height` in the `svg` tag will not display in Firefox.

I'm not sure if an issue exists on upstream mapbox; my search for "svg firefox" did not yield any results.

However, this issue is also being discussed here: https://bugzilla.mozilla.org/show_bug.cgi?id=700533
That bug report discussion also links to https://webcompat.com/issues/64352 which is about mapbox-gl-js.
A related issue is https://bugzilla.mozilla.org/show_bug.cgi?id=1659371 which would probably also lead to different visuals in different browsers.

This bug lead to critical indicators missing on our maps - without any errors. Depending on the usage-scenario of the maps, this could be very bad and dangerous (imagine "track closure signs" on a map used by railway companies).

---

This is the maplibre code which triggers the bug:
https://github.com/maplibre/maplibre-gl-js/blob/2112766af5d68a7ea885156c8c186c72a4e912ca/src/util/browser.js#L39-L49

*(The related Firefox / gecko code appears to be here: https://github.com/mozilla/gecko-dev/blob/bc8cc2fbdec52e662683fe0a84e06e9678183ff9/dom/canvas/CanvasRenderingContext2D.cpp#L4485-L4501 and here: https://github.com/mozilla/gecko-dev/blob/7ef5cefd0468b8f509efe38e0212de2398f4c8b3/dom/canvas/CanvasImageCache.cpp#L323-L326)*

---

Here's a dirty file to reproduce the issue (expects maplibre running with `yarn run start-debug`):

- Works in Chrome
- Works in Safari
- Does not work in Firefox

```html
<!DOCTYPE html>
<html>
<head>
    <title>Mapbox GL JS debug page</title>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel='stylesheet' href='http://localhost:9966/dist/maplibre-gl.css' />
    <style>
        body { margin: 0; padding: 0; }
        html, body, #map { height: 100%; }
    </style>
</head>

<body>
<div id='map'></div>

<script src='http://localhost:9966/dist/maplibre-gl-dev.js'></script>
<script src='http://localhost:9966/debug/access_token_generated.js'></script>
<script>

var map = window.map = new maplibregl.Map({
    container: 'map',
    zoom: 0.5,
    center: [0, 0],
    style: 'mapbox://styles/mapbox/streets-v10',
    hash: true
});

// Create an image from SVG
const svgImage = new Image(100, 100)
svgImage.onload = () => {
    map.addImage('svg', svgImage)
}
function svgStringToImageSrc (svgString) {
    return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svgString)
}
svgImage.src = svgStringToImageSrc(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 75 86.532">
  <g id="group" data-name="group">
    <g id="arrow">
      <path d="M38.477.643l36.432,84.4A1.065,1.065,0,0,1,73.4,86.385l-34.362-19.8a3.083,3.083,0,0,0-3.076,0L1.6,86.385A1.065,1.065,0,0,1,.091,85.041L36.523.643A1.064,1.064,0,0,1,38.477.643Z"/>
    </g>
  </g>
</svg>`);

// Create a GeoJSON source with an simple lineString.
var geojson = {
    'type': 'FeatureCollection',
    'features': [
        {
            'type': 'Feature',
            'geometry': {
                'type': 'LineString',
                'coordinates': [[0, 0], [90, 0]]
            }
        }
    ]
};

map.on('load', function () {
    map.addSource('line', {
        'type': 'geojson',
        'data': geojson
    });

    // add the line
    map.addLayer({
        'id': 'line-line',
        'type': 'line',
        'source': 'line',
        'layout': {
            'line-cap': 'round',
            'line-join': 'round'
        },
        'paint': {
            'line-color': '#ed6498',
            'line-width': 5,
            'line-opacity': 0.8
        }
    });

    // add the line
    map.addLayer({
        'id': 'line-direction',
        'type': 'symbol',
        'source': 'line',
        'layout': {
            'icon-image': 'svg',
            'icon-size': 1.0,
            'symbol-placement': 'line',
            'icon-rotate': 90,
            'symbol-spacing': 30,

            // The following are purely for performance reasons
            'icon-allow-overlap': true,
            'icon-ignore-placement': true,
            'symbol-z-order': 'source'
        },
        'paint': {
            'icon-opacity': 1.0,
            'icon-opacity-transition': { 'duration': 500 }
        }
    });

});

</script>
</body>
</html>
```

My dirty workaround was this (note the addition of `"px"` to the existing workaround from one of the links above):

```js
// Workaround for https://bugzilla.mozilla.org/show_bug.cgi?id=700533
// From https://webcompat.com/issues/64352
function ensureSVGWidthHeight(svgElem) {
    if(!svgElem.getAttribute('width') || !svgElem.getAttribute('height')) {
        var viewBox = svgElem.getAttribute('viewBox');
        if(viewBox) {
            var match = viewBox.match(/\w+ \w+ (\w+) (\w+)/);
            var viewBoxWidth = match[1];
            var viewBoxHeight = match[2];
            svgElem.setAttribute('width', viewBoxWidth + "px");
            svgElem.setAttribute('height', viewBoxHeight + "px");
        }
    }
    return svgElem;
}

function svgStringToImageSrc (svgString) {
    var parser = new DOMParser();
    var svgXML = parser.parseFromString(svgString, "image/svg+xml");
    const fixedSvgXML = ensureSVGWidthHeight(svgXML.rootElement);
    const fixedSvgString = new XMLSerializer().serializeToString(fixedSvgXML);
    return 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(fixedSvgString)
}
```

However, this still doesn't solve many issues, so we can't easily intergrate this fix in maplibre:
- Other image formats also exist, so we might have to do type-guessing based on various factors to know if we have to apply our fix.
- SVG can also be loaded via URL, so all SVG images would have to fetched and modified first.
- Images can sometimes reference other images internally, and this was not tested (I believe SVG can contain another SVG internally? And other image formats can potentially also do it).
- The image is stretched differently in Chrome and Firefox; I assume we'd have to use the `Image()` size inside the SVG to fix this issue. This also suggests that even SVGs with existing `width` and `height` attributes display differently in Firefox and Chrome (although I did not test it).

I also tried to get into a different code path using https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/createImageBitmap but got security errors or nothing showed up.
Maybe someone else has an idea or better luck with finding a suitable workaround.

**Comment by rbrundritt** [comment]
This makes sense. If an SVG doesn't have a width or height, it generally will fill all available space when displayed in a browser DOM. Since map is rendered on a HTML5 canvas, width and height should be specified in the SVG. The easiest solution is to make that a requirement in the SVG string itself rather than to try and handle this within the map. 

Note that SVG's via data URI's have a lot of limitations due to inconsistent behavior across browsers. The main one being the requirement for width/height properties. My team has been using SVG's with the HTML5 canvas for nearly 6 years now and this has been one consistent requirement to get this to work across browsers.
