### ISSUE TITLE
Interactive area of symbols with interpolated size at fractional zoom levels

### ISSUE THREAD

**Issue by eriz0065** [maplibre/maplibre-gl-js#128]
**maplibre-gl-js version**: 1.14.0-rc.1

**browser**: chrome, edge

### Steps to Trigger Behavior

 1. Add a point source to map
 2. Add a symbol layer with icon-size determined by interpolation (e.g. "icon-size": ["interpolate", ["linear"], ["zoom"], 15, 0, 16, 0.5]) 
 3. The interactive area at fractional zoom levels (i.e. the box around the symbol for which mouse events are triggered) is larger than the actual icon size

### Link to Demonstration
https://codepen.io/eriz0065/pen/VwPMvdj
Open the console, mouseover and mouseout events at fractional zoom levels between 15 and 16 are triggered in a larger area with respect to actual icon size.

### Expected Behavior
Mouse events related are triggered considering the actual size of the layer symbol; mapbox from version 2.0.0 support this.

**Comment by a-maggioni** [comment]
I confirm that I can still reproduce this problem with version 2.1.1

**Comment by HarelM** [comment]
@drwestco I know you've been playing with this kind of stuff.
Any chance you can take a look at this issue?

**Comment by drwestco** [comment]
The interactive area is determined by the symbol's collision box. Collision boxes are only recomputed at integer zoom levels; changing the size of a collision box affects layout and running a new layout pass at each fractional zoom level would incur a huge performance penalty.

Now it should be possible to address this specific case - modify queryRenderedFeatures to perform a filtering pass and check whether the point is within the actual symbol bounds.

**Comment by HarelM** [comment]
Cool! Thanks for the info!
Can I close this one then?

**Comment by drwestco** [comment]
Yeah, unless there's a strong use case for this, I'd close it.
