### ISSUE TITLE
Implement copyright violation checker as part of CI

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre-gl-js#129]
MapLibre need to prevent accidental copy/pasting of code from Mapbox 2.0 code.  This feature should run during the CI PR workflow, doing a diff with the new 2.0 code to make sure the code wouldn't violate Mapbox's copyright.

**Comment by ambientlight** [comment]
@marcelnormann: I was looking into adapting https://github.com/platisd/duplicate-code-detection-tool that would scan over PR-vs-PRsAbovePRID (rather then file-vs-files) for this purpose, I will further feedback on it soon as I haven't really experimented with it  yet

**Comment by marcelnormann** [comment]
@ambientlight My idea so far was to extract all the lines of code from mapbox-gl-js that has been added after the license change and then run a search of code blocks in our PRs against it. Maybe it is a better idea to extract also all new lines of code from the maplibre repo so far and run your tool against both. Then similarity should be near to 0%.

**Comment by klokan** [comment]
We should extract all the code committed into Mapbox GL JS after their 2.0 release - and index it with a "plagiarism checker" used for schools assignments - as part of the CI / PR checks - and then check the new code in the PR against the index.
- https://github.com/dodona-edu/dolos
- https://github.com/manuel-freire/ac2
or similar...

IMHO these tools don't handle individual files usually they work with blocks, and they also ignore different formatting of the source code - which may be practical...

**Comment by ambientlight** [comment]
> @ambientlight My idea so far was to extract all the lines of code from mapbox-gl-js that has been added after the license change and then run a search of code blocks in our PRs against it. Maybe it is a better idea to extract also all new lines of code from the maplibre repo so far and run your tool against both. Then similarity should be near to 0%.

This sounds like a better idea then mine, the similarity might not be near 0% exactly though, I wonder if common programming constructs will bump it to some base 5%-10%.

**Comment by wipfli** [comment]
Lets keep this one closed for now. After the TypeScript migration, I don't know if it will even be possible to get a copyright checker to work. Also the two projects will diverge over time more and more so that a comparison will become harder and harder.
