### ISSUE TITLE
Option for maxBounds to constrain the map center instead of edges

### ISSUE THREAD

**Issue by burleight** [maplibre/maplibre-gl-js#1290]
## Motivation

If `maxBounds` is set, and the map container has an aspect ratio that is different to `maxBounds`, the map can't show the full extent of the bounds. 

I'd like an option for maxBounds to behave like Openlayers' View constrain center option, where the map may show areas outside of the bounds, so long as the map center is within them. This would allow me to create maps that upon start up show the full extent of the data I'm creating visualisations for, while also restricting the camera bounds.

### Implementation

I suggest adding an option parameter to `setMaxBounds` and the `Map` constructor called `maxBoundsOptions`, which has a constrain center property:

`map.setMaxBounds(someBounds, { constrainCenter: true  })`

### Workaround

I haven't implemented a workaround, but I think I can get the result I want by taking my desired `maxBounds` and stretching it to the aspect ratio of the map container.

**Comment by HarelM** [comment]
Shouldn't you use setBounds and not setMaxBounds?

**Comment by burleight** [comment]
I thought `options.bounds` only sets the initial bounds, it doesn't prevent people scrolling away:

> `options.bounds` The initial bounds of the map. If bounds is specified, it overrides center and zoom constructor options.

**Comment by HarelM** [comment]
The use case is for a "static" map? I'm trying to better understand the issue here...

**Comment by burleight** [comment]
See here https://observablehq.com/d/710f89611acfab86

The first map shows what I'd like to achieve.

**Comment by HarelM** [comment]
The first map allows you to zoom out and isn't really constrained.
You can achieve that be setting zoom and center, can't you?
I'm probably missing something obvious...

**Comment by HarelM** [comment]
@burleight can you please elaborate? Otherwise I'll need to close this issue due to lack of information...

**Comment by HarelM** [comment]
No extra data was provided, closing...
