### ISSUE TITLE
Memory keeps increasing while I am seeing a terrain 3D map with interaction on zoom, tilt(pitch), and rotation

### ISSUE THREAD

**Issue by ubukawa** [maplibre/maplibre-gl-js#1291]
**maplibre-gl-js version**: v2.2.0-pre.2

### Question
Thank you for your great work on developing terrain 3D visualization!  
I have created my terrain 3D map with MapLibre GL JS version 2.2.0-pre.2.  
I can see 3D terrain with two raster tiles, but **I found that the memory keeps increasing while I keep browsing map.**
(I used both Google Chrome and Microsoft Edge, but I saw the same issue with the both browser.)  
Map drawing gets slow and sometimes it stops.  

I am not sure if this is the issue of my own map, but do you have any advice on how I can improve this?  

* Map: https://ubukawa.github.io/shikoku/map-3.html  
* Style: https://ubukawa.github.io/shikoku/std3.json
* My web browsers: Google Chrome Version 102.0.5005.63 (Official Build) (64-bit), Microsoft Edge Version 102.0.1245.30 (Official build) (64-bit)
* RGB elevation tiles: I made it by myself from ALOS 30meter resolution DEM, using mapbox/rio-rgbify
* Pictures

![2022-06-02-14](https://user-images.githubusercontent.com/59204379/171650209-d3293e6c-f6cf-45fb-ad17-b9e19640763f.png)

![2022-06-02-edge](https://user-images.githubusercontent.com/59204379/171650141-b19ab197-da29-41b6-956d-761b5a3120aa.png)

Thank you very much for your kind attention and kind advice!

**Comment by HarelM** [comment]
I think I felt the same when using in my app - I.e. It crashed after playing with it for a while, so I thought it might be a memory increase of solve sort.
Any help debugging this and getting to the bottom of this would be extremely helpful!

**Comment by prozessor13** [comment]
The 3D Engine caches last rendered textures, may there is a bug releasing deprecated textures?

https://github.com/maplibre/maplibre-gl-js/blob/main/src/source/terrain_source_cache.ts#L53

I also noticed crashes on mobile-devices with low memory. I will have a look onto this!

**Comment by HarelM** [comment]
Thanks @prozessor13!
While your assumption is probably correct as you know the code well enough to identify places you think memory might be used without being released I would love to see that we can reach this conclusion using chrome dev tools or something similar.
I hope this is possible, this way we can identify the code that causes the leak and make sure we are fixing the right thing. :-)
I personally was never able to find memory leaks or bad performance with these tools but I tried it a few years back and it might be better now.
