### ISSUE TITLE
3D model loading problem in the terrain map - MapLibre V2 -

### ISSUE THREAD

**Issue by Takieddinex** [maplibre/maplibre-gl-js#1294]
I try to load my 3D models on a map without and with terrain but I encounter a huge problem when I use the terrain background or my models disappear and they are put on another scale completely different from the map.

Without terrain Ok : 
![image](https://user-images.githubusercontent.com/95845810/171805652-c9831708-3425-427e-bfb9-54ac49368dbd.png)

With terrain NOT Ok : 
![image](https://user-images.githubusercontent.com/95845810/171805740-1a37ffdc-9059-4afb-828c-4dc4c6d1c5d9.png)

**Comment by HarelM** [comment]
If you switch the terrain only on and off does it change the map position?
Also a way to reproduce it would help a lot.

**Comment by Takieddinex** [comment]
the models are correctly placed on the map but once I activate the terrain the models are placed on a large scale and the map navigation does not work correctly

**Comment by acalcutt** [comment]
@Takieddinex 

I tested combining terrain with the three.js 3d model example and I don't seem to get the same issues you are having ( https://stackblitz.com/edit/web-platform-wtfbbt?file=index.html ). The 3d model remains where it should be with terrain enabled, though I do notice it sometimes gets placed under the ground level. I'm not seeing anything like your example where it gets very large and you loose control of the map.

Do you have  live example of your map with the issue?

**Comment by HarelM** [comment]
We need a way to reproduce this issue, without that we won't be able to fix this issue.
Is this the same as #1654?

**Comment by HarelM** [comment]
No response, assuming this is a duplicate of #1654.
If this is not the case please reopen the bug or add data to the linked issue.
