### ISSUE TITLE
all line features from a geojson have the same color

### ISSUE THREAD

**Issue by xrmx** [maplibre/maplibre-gl-js#1308]
**maplibre-gl-js version**: 2.1.9

**browser**: firefox / chrome

### Steps to Trigger Behavior

Draw on a map more than one line feature using a different color for each

### Link to Demonstration

http://jsbin.com/negifequli/edit

### Expected Behavior

each line has its own color

### Actual Behavior

all lines are of the same color

**Comment by HarelM** [comment]
This is because this is not the right way to do what you want.
Please consult with the documents and examples before opening an issue.

instead of adding a layer per feature you should add a single layer for all features with the following code:
```js
map.addLayer({
                            'id': 'rides-lines',
                            'type': 'line',
                            'source': 'rides',
                            'layout': {
                                 'line-join': 'round',
                                 'line-cap': 'round'
                            },
                            'paint': {
                                // This is the relevant part
                                'line-color': ['get', 'stroke'],
                            },
                        });
```

**Comment by xrmx** [comment]
Sorry for the noise. I have the line-color reference in front of me (https://maplibre.org/maplibre-gl-js-docs/style-spec/layers/#paint-line-line-color) and being using map libre for the first time I didn't recognize "Supports feature-state and interpolate" as something useful.
