### ISSUE TITLE
Increasing icon-size blurs/pixelates symbol layer icon

### ISSUE THREAD

**Issue by f1sh1918** [maplibre/maplibre-gl-js#1311]
Hello,

i'm using maplibre with spritesheet in @1x and @2x. (check the style source) The spritesheet uses the standard maki svg icons.
For scaling up the icons i use the `icon-size` property.
It looks like the scaling algorithm that uses `icon-size` does not work properly.

**maplibre-gl-js version**: 2.1.9
**browser**: Chrome + Firefbox

### Steps to Trigger Behavior

 1. Increase the `icon-size` in the symbol layer

### Link to Demonstration

https://codepen.io/andreas-fischer/pen/XWZwXJR

### Expected Behavior
The icon gets scaled up properly. At least for `icon-size`up to `2`

### Actual Behavior
The icon / edges get pixelated / blurry by increasing the icon-size

**Comment by HarelM** [comment]
Can you elaborate on the issue here? It is unclear what is expected and current behavior.

**Comment by HarelM** [comment]
No extra info was provided. Closing...
