### ISSUE TITLE
Image source content is not loaded properly if not utilized 'quickly enough' on Safari 

### ISSUE THREAD

**Issue by simon-milleto** [maplibre/maplibre-gl-js#1314]
**maplibre-gl-js version**: 2.1.9 || 1.15.3

**browser**: Safari 14.1

### Steps to Trigger Behavior

 1. Create a map and add raster source with layer `layout: {visibility: 'none'}`
 2. Wait for 2s
 3. Set visibility to `visible`
 4. The layer will not be displayed

### Link to Demonstration

https://codepen.io/simonmilleto/pen/yLvWxGb?editors=1010

### Expected Behavior
After the `setLayoutProperty` the layer should be visible

### Actual Behavior
The layer is not visible

It looks like this issue is linked to this one https://github.com/mapbox/mapbox-gl-js/issues/10685 (yes I used the same title).
I could reproduce the same error with mapbox@1.13.2 but it works with last mapbox v2

**Comment by HarelM** [comment]
From what I've read in the linked issue the solution is to load the image into the image source and not keep it as HTMLImageElement.
Feel free to submit a PR.
Note that we can't copy code from mapbox v2.

**Comment by simon-milleto** [comment]
I submitted a [PR](https://github.com/maplibre/maplibre-gl-js/pull/1323) and targeted the v1.x since it's a fix from mapbox v1.x

**Comment by HarelM** [comment]
There are unanswered question in the PR that should solve this issue. Please take the time to respond to them...

**Comment by HarelM** [comment]
See comments in #2419.
Seems like this is no longer an issue.
If this is, please provide a way to reproduce and comment on the linked PR (which I'm about to close).
