### ISSUE TITLE
deck.gl layer is not visible with Terrain

### ISSUE THREAD

**Issue by karatemir** [maplibre/maplibre-gl-js#1317]
I am using MapLibre (version 2.2.0-pre.2) to render 3D terrain as described in [here](https://bertt.wordpress.com/2022/05/24/custom-maplibre-terrain-tiles/). I also have a Deck.gl [TripsLayer](https://deck.gl/docs/api-reference/geo-layers/trips-layer/) that I have added, basically a simple 3D trajectory describing some motion. The problem is I cannot see the TripLayer when terrain is on. However, if I toggle off the Terrain using the disable button, Deck.gl layer shows properly. 

Is this normal expected behavior?

**Comment by HarelM** [comment]
I'm guessing that the TripLayer is rendered inside the terrain or something.
Terrain obviously doesn't support everything...
Feel free to investigate how this should be made and share an example. :-)

**Comment by prozessor13** [comment]
As Harel said, i also assume that the trips layer is rendered below terrain (on elevation zero, sealevel). There may be two possible fixes:
* add terrain to deck.gl as well, and render the deck.gl layer above the maplibre map.
* implent render-to-texture for deck.gl layers and drape that textures onto maplibre terrain (i think is a lot of work, but may deck.gl has this functionallity already implemented, dont know)

**Comment by HarelM** [comment]
No example provided so there's no actual way to help here.
Converting this into a discussion.
