### ISSUE TITLE
Investigate performance of symbol placement on lines

### ISSUE THREAD

**Issue by JannikGM** [maplibre/maplibre-gl-js#133]
*Consider this low priority.*

I looked into implementation of 'line-center' for an unrelated issue in our companys mapbox fork.
While looking at it, I got the impression that this is non-optimized code that could be made faster.
I did not check how often this function gets called or how much time it takes in total, but even for the case where it's only ran once for tile setup, this is still something that could potentially be improved.

Specifically, the [property is checked in `addFeature`](https://github.com/maplibre/maplibre-gl-js/blob/fd16a60a748fb00f4e2e5559e1e42bfa1d27ed83/src/symbol/symbol_layout.js#L415-L451).

`addFeature` then internally uses [`getCenterAnchor`](https://github.com/maplibre/maplibre-gl-js/blob/fd16a60a748fb00f4e2e5559e1e42bfa1d27ed83/src/symbol/get_anchors.js#L35) to find the line-center.
That routine does not do any sort of memoization and is not ideal. (it keeps recomputing line segment lengths for example; it also has no cache when requesting the center for same feature).

`addFeature` function gets called from `performSymbolLayout`, which (as far as I remember) is a potential bottleneck for our application. Hence this issue.

**Comment by rbrundritt** [comment]
The angleWindowSize & labelLength could be pulled out and be computed before the loop in the line-center addFeature loop. Although these are pretty simple calculations and unless using MultiLineStrings, will likely only be called once per line, so this would likely not make much of a difference, if any.

Digging through the source code, it looks like the addFeature function is only called once per feature when it is added to the source. With this in mind, caching the length likely wouldn't provide any benefit and would only increase memory usage.
