### ISSUE TITLE
Failing Integration Tests

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#1349]
The integration tests are maybe the ones that fail most often for no good reason. Here are some recent failing runs:

* https://github.com/maplibre/maplibre-gl-js/runs/7146239578?check_suite_focus=true
* https://github.com/maplibre/maplibre-gl-js/runs/7146239578?check_suite_focus=true
* https://github.com/maplibre/maplibre-gl-js/runs/7146168019?check_suite_focus=true

I wonder if there is a way to make these tests more stable?

**Comment by HarelM** [comment]
@wipfli is this still relevant? I feel like the test are OK lately...
We can alway retry a failing test I guess...?

**Comment by wipfli** [comment]
The integration tests were not so bad lately. Maybe this is thanks to an operating system change? I don't know. Anyway, we can close this...
