### ISSUE TITLE
User's heading/bearing

### ISSUE THREAD

**Issue by CuAnnan** [maplibre/maplibre-gl-js#1358]
## Motivation
At present there doesn't appear to be a means of getting a user's compass heading, which is a fairly standard navigation tool. It is possible to get the _map's_ bearing, but not the user's.

## Design Alternatives
The navigator.geolocation.getCurrentPosition actually includes bearing as a property. Please expose this.

**Comment by HarelM** [comment]
Getting the bearing is a hardware related implementation, you can get it in several ways depending on the environment you run in (cordova, react-native, browser) etc.
I don't see how this should be in this library.
Simply use the relevant API like the one you mentioned above...

**Comment by CuAnnan** [comment]
It's a lot harder for me to write a piece of code that says "Under the image you add at my location, add an image for the bearing at the data.coords.bearing angle".
That image isn't exposed _at all_.

**Comment by CuAnnan** [comment]
Further. The docs, for data as it passed to the event handler, link directly to the MDN for GeolocationPosition

**Comment by HarelM** [comment]
I'm having a hard time following. Please link to the relevant docs, examples etc...
Here's the code in using in my app that uses cordova:
https://github.com/IsraelHikingMap/Site/blob/1513d6095ede4e9ccb701eaf7dbeee386f912b1e/IsraelHiking.Web/src/application/services/device-orientation.service.ts#L71

**Comment by drwestco** [comment]
This was discussed in the Slack channel. The current approach to do this through the GeolocateControl is:
1. When creating the GeolocateControl, use `options.showUserLocation=false` to hide the auto-displayed user location icon
2. Add an event handler to `GeolocateControl.geolocate`, to get a notification whenever the control successfully locates the user.
3. In response to the event, use the GeolocactionPosition passed to the event handler, and add/update your shape/marker based on lat/lng/heading.

**Comment by laem** [comment]
Suite in https://github.com/maplibre/maplibre-gl-js/issues/3086
