### ISSUE TITLE
Ionic framework turn by turn navigation

### ISSUE THREAD

**Issue by bmarcco** [maplibre/maplibre-gl-js#136]
Hi, I am working on a navigation application in Ionic (Angular), OpenStreetMap and I use Valhalla as a routing machine, now I wonder if there is a possibility to use Maplibre-GL-JS to get navigation similar to the image below?
![sjOIv](https://user-images.githubusercontent.com/63052506/115017358-b7cf8880-9eb6-11eb-9b75-cb46a2a0ccfa.png)

**Comment by wipfli** [comment]
Mapbox has a [directions plugin](https://github.com/mapbox/mapbox-gl-directions), see this [example](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions). Probably we could make this plugin work with ```maplibre-gl-js```.

However, you will still need an API to get the directions data from.

**Comment by bmarcco** [comment]
I currently have something [similar](https://i.postimg.cc/t4L2P9YW/Capture.png), but I need a text or voice message before the turn, as in the picture above.

**Comment by cigone-openindoor** [comment]
For close road routing resolution, browser side processing - without routing Rest API - could be enough.

**Comment by bmarcco** [comment]
I'm already using the routing Rest API, and I won't see it on my web browser. The preview will be in the android application created with Ionic.

**Comment by HarelM** [comment]
I've migrated ngx-maolibre-gl which should help in this case.
What else are you missing?
