### ISSUE TITLE
stopPropagation when clicking marker with popup

### ISSUE THREAD

**Issue by rinfante77** [maplibre/maplibre-gl-js#1360]
To reproduce the problem:

1) Create a polygon with mapbox draw like here https://maplibre.org/maplibre-gl-js-docs/example/mapbox-gl-draw/ .

2) On top of it create a maker with a popup https://maplibre.org/maplibre-gl-js-docs/example/set-popup/.

When clicking the marker, then the polygon is also selected.

The click event of the marker should open the popup and stop the event propagation.

**Comment by HarelM** [comment]
Isn't this up to you to call `event.stopPropogation()`?
I'm failing to see the issue here.
Can you please share a jsbin/codepen?

**Comment by rinfante77** [comment]
I was able to solve this getting the event of the div and calling stoppropagation, thanks
