### ISSUE TITLE
Map does not fit its html container when used in a modal window or a collapsable div

### ISSUE THREAD

**Issue by escomputers** [maplibre/maplibre-gl-js#1363]
**maplibre-gl-js version**: 1.15.2

### Question
I noticed that map fits well its HTML container when statically placed into the page as usual.
But if I want to show it in a modal window or place it into a collapsable div, it does not resize automatically to its container window. Only after resizing the browser window manually, map fits container correctly.

I tested it in all major versions of most used browsers.
I don't know if it could be marked as a bug or it's just something I need to correct on my project (any help/suggestion appreciated)
Video explains what I wrote

https://user-images.githubusercontent.com/4378005/177783072-534c1565-3b0f-43cb-86b8-386ddebe93ef.mp4

**Comment by axekan** [comment]
You likely initialize the map before opening the modal, making the container have 0 height when the map loads in. That leads to the map taking on the standard width and height instead of anything relating to the container. You probably need to wait for the modal to open before loading the map.

**Comment by escomputers** [comment]
@axekan Thank you so much, I solved following your suggestions
