### ISSUE TITLE
Add extent function for each layers

### ISSUE THREAD

**Issue by kochizufan** [maplibre/maplibre-gl-js#1364]
## Motivation

OpenLayers can set extent to each layers.
Example can be seen in this url:
https://jsfiddle.net/kochizufan/ucw948e6/

This is so useful so I want to have it in MapLibre too.

**Comment by HarelM** [comment]
Can you better explain the use case and problem statement?
I'm not familiar with the extent definition of open layers, and maybe other who may read this issue too.

**Comment by kochizufan** [comment]
![image](https://user-images.githubusercontent.com/2221431/185822434-b553bd44-7b85-4e66-b03b-471d08aa3c3a.png)
Left window is maplibre and right window is openlayers.
As you can see, openlayers showing area is limited with this setting:

```
      extent: ol.proj.transformExtent([139.486540, 36.185698, 139.526540, 36.205698], 'EPSG:4326', 'EPSG:3857')
```

Sorry, I have less knowledge about maplibre's style, so if there are already such specification on maplibre style, please ignore this request.

**Comment by HarelM** [comment]
What about min max bounds?

**Comment by HarelM** [comment]
I'm pretty sure the above comment solves this issue.
No more info was providede.
Closing...
