### ISSUE TITLE
import clearStorage function

### ISSUE THREAD

**Issue by catalinconstant** [maplibre/maplibre-gl-js#1371]
how do I import clearStorage function ?
import {
  clearStorage
} from 'maplibre-gl'; give the following error: 
Module '"maplibre-gl"' has no exported member 'clearStorage'.

**maplibre-gl-js version**: 2.2.0-pre.3

**Comment by anuragvohraec** [comment]
> try the following:
> 
> ```ts
> import maplibregl from 'maplibre-gl'
> maplibregl.clearStorage()
> ```


Give me following error:
```
[!] Error: 'default' is not exported by node_modules/maplibre-gl/dist/maplibre-gl.js,
```

**Comment by anuragvohraec** [comment]
Ok I sorted this problem.
I m using rollup us my module bundler, and seems the maplibrejs uses commonjs specifications inside, so it needs a plugin to bundle it all togther. I used [@rollup/plugin-commonjs](https://www.npmjs.com/package/@rollup/plugin-commonjs) , and it solved my issue.
