### ISSUE TITLE
GeoJson Feature property with null value becomes "null" as string literal when querying rendered features

### ISSUE THREAD

**Issue by codytodonnell** [maplibre/maplibre-gl-js#1376]
This issue was originally raised and resolved in mapbox (see https://github.com/mapbox/mapbox-gl-js/issues/8497) but is still an issue in maplibre.

**maplibre-gl-js version**: 1.15.3

**browser**: Google Chrome

### Steps to Trigger Behavior

1. Set source data with a GeoJson FeatureCollection
2. The collection contains at least one feature with a property with a `null` value
3. When the feature is returned by `map.queryRenderedFeatures()`, the properties that originally had `null` values now have the literal `"null"` string as their value.

### Expected Behavior

The value should remain as `null`.

### Actual Behavior

The value became `"null"` as a literal string.

**Comment by HarelM** [comment]
Can you check if this is still the case with the latest version?
Seems like this issue is with a dependency package and I believe the latest version has all the packages up-to-date.

**Comment by HarelM** [comment]
No response, assuming this is fixed in latest version.
