### ISSUE TITLE
Duplicate keyframes in css file

### ISSUE THREAD

**Issue by maxlibin** [maplibre/maplibre-gl-js#1378]
**maplibre-gl-js version**: Main branch

looks like there are quite a few css duplications for keyframes `maplibregl-spin` from: https://github.com/maplibre/maplibre-gl-js/blob/main/src/css/maplibre-gl.css#L467

line 467 - 485

`maplibregl-user-location-dot-pulse` https://github.com/maplibre/maplibre-gl-js/blob/main/src/css/maplibre-gl.css#L900

line 900 - 910

happy to help to cleanup if is true.

**Comment by HarelM** [comment]
Strange... Feel free to send a PR to clean them.
IT would also be helpful if you could find out when they were duplicated...

**Comment by maxlibin** [comment]
> Strange... Feel free to send a PR to clean them. It would also be helpful if you could find out when they were duplicated...

It was committed from this PR: https://github.com/maplibre/maplibre-gl-js/pull/1004

**Comment by HarelM** [comment]
Ahh, now I understand, thanks!!
