### ISSUE TITLE
modify the cluster property true/false

### ISSUE THREAD

**Issue by IhsenBen** [maplibre/maplibre-gl-js#1384]
Hi
 seems like there's no way to modify the cluster property on the source without resetting the whole thing, is it possible to do something like this instead:

map.addSource('some id', {
    type: 'geojson',
    data: geodata,
    cluster: true,
    clusterMaxZoom: 14,
    clusterRadius: 50,
  });
//
//
**map.getSource('some id').setCluster(false)**

**Comment by HarelM** [comment]
I have a feeling this was already retorted, any change you can have a look?

**Comment by IhsenBen** [comment]
> I have a feeling this was already retorted, any change you can have a look?

Yes, I did look into the docs before posting this issue

**Comment by HarelM** [comment]
Somewhat related: #429

**Comment by IhsenBen** [comment]
Hi again
Can I work on this, please?

**Comment by HarelM** [comment]
Sure, enjoy! 😀

**Comment by IhsenBen** [comment]
> Sure, enjoy! 😀
Just made a pull request, tell me if I need to modify anything
#1998

**Comment by SnailBones** [comment]
Looks like this should be closed since https://github.com/maplibre/maplibre-gl-js/pull/1998 has been merged.

**Comment by IhsenBen** [comment]
> Looks like this should be closed since https://github.com/maplibre/maplibre-gl-js/pull/1998 has been merged.

Yes, I added the feature, maybe when it's released?
