### ISSUE TITLE
Remove support for old filter expression syntax.

### ISSUE THREAD

**Issue by cns-solutions-admin** [maplibre/maplibre-gl-js#1385]
There is quite some code supporting the old filter expressions (https://maplibre.org/maplibre-gl-js-docs/style-spec/other/#other-filter), which have been deprecated for years.
Support for them should be dropped in 2.x

**Comment by HarelM** [comment]
I would recommend posing this in the slack channel to get this more visible and get more input.
Removing support for these kind of filters might prove problematic, much like my attempt to remove the css mapbox prefix...

**Comment by zstadler** [comment]
I'm afraid I don't see the value in removing the support for the deprecated expressions.

IMO, it is inflicting pain on customers/users without providing any added value to them.
I also do not see how removing the code will have a significant impact on Maplibre, such that could justify this pain.

Moreover, https://maplibre.org/maplibre-gl-js-docs/style-spec/other/#other-filter, mentioned above, clearly says:
> **filters defined with this syntax will continue to work**

without any mention of an End-of-Life process.

**Comment by jleedev** [comment]
If these are indeed deprecated, then it should log a warning. A formal deprecation policy (which doesn't exist yet?) could say, "deprecated items will produce a warning, and indicate that they may be removed in a major version".

The value in removing this, it's easy to accidentally use the old syntax, and then attempting to mix the two produces a confusing error.

```javascript
map.setFilter(
  'countries-fill',
  ['any', ['==','CONTINENT','Europe'], ['==',['get','CONTINENT'],'Africa']],
)
Error: layers.countries-fill.filter[2][1]: string expected, array found
```

**Comment by zstadler** [comment]
All the Maplibre styles I'm aware of are using the old style, including:
- Maplibre demo map ([example](https://github.com/maplibre/demotiles/blob/8b1861a24ceff231da86f5e117192915b8adae44/style.json#L385-L392])) @petr-pokorny-1
- All 7 [Maptiler styles](https://www.maptiler.com/maps) @klokan 
- The OpenStreetMap Americana Style ([example](https://github.com/ZeLonewolf/openstreetmap-americana/blob/64b650e026cea3e1af17eeac8ab89d4aa3295ad8/src/layer/oneway.js#L9-L25)) @ZeLonewolf
- [Swisstopo style](https://vectortiles.geo.admin.ch/styles/ch.swisstopo.leichte-basiskarte.vt/style.json) and swiss-map ([example](https://github.com/wipfli/swiss-map/blob/4bd78287a513b4f5f61a8bbdf4930473de81bd3a/style.json#L18-L25)) @wipfli 
- Both Israel Hiking Map styles ([example](https://github.com/IsraelHikingMap/VectorMap/blob/8a79298f798365ff8a59cec56a6dabbec4504f28/Styles/IHM.json#L38-L46)) @zstadler 

Implementing this PR will introduce a backward incompatibility that will require them and many other Maplibre users to either avoid updating their Maplibre version or receive unpleasant error messages, learn the new syntax, and  convert the styles  to the new syntax. 

On the other hand, the above mentioned drawback is an unclear error message for code that never worked that will be seen by developers that didn't read the deprecation note:

> **Expression syntax and the deprecated syntax below cannot be mixed in a single filter definition.**

If the wording of the error message is a significant problem, a separate issue can be opened for improving it. Unlike the change suggester here, fixing the error message will have no negative impact on existing loyal users of Maplibre.

**Comment by ZeLonewolf** [comment]
I had no idea we were using an "old" syntax, and it would be helpful to show a few examples of old and new.

**Comment by cns-solutions-admin** [comment]
Ad mixing old and new filters: this could be improved by checking not only the first condition, but rather, whether everything could be a old filter.

In that case the above example would be a (valid) new filter, although a rather useless one: ['==','CONTINENT','Europe'] is always false.

**Comment by HarelM** [comment]
I've labeled it as need more info as I think there's more input needed here.
I'll take it to the steering committee meeting to see what they say about it.

**Comment by ZeLonewolf** [comment]
I would like to see a strategy where deprecated features first throw a warning (in the console) indicating that the functionality will be removed in a future version.

**Comment by klokan** [comment]
I don't think it is a good idea to deprecate these.
Hundreds of map styles are using it...

Are there tools automatically converting this syntax to the new expressions?

**Comment by HarelM** [comment]
The code itself does the conversion/migration, I'm sure it can be easily extracted to a cli tool if needed.

**Comment by wipfli** [comment]
Migration can probably be done automatically with https://github.com/maplibre/maplibre-gl-js/blob/main/src/style-spec/README.md#gl-style-migrate

**Comment by ZeLonewolf** [comment]
Americana's gl-js code is generated programmatically, so I'm not sure that can be converted automatically?

**Comment by jleedev** [comment]
@ZeLonewolf Right, you would have to look at the generated style and then update the source by hand.

I started in https://github.com/ZeLonewolf/openstreetmap-americana/pull/527, need to handle the exponentials next.

**Comment by zstadler** [comment]
I don't think removing the support for the original filter syntax is a good idea

This the "deprecation" message is only a preference statement from Mapbox, as it clearly says

> filters defined with this syntax will continue to work

Let's not look at the term "deprecation" out of its specific context.

There thread still has no reference of the potential benefits of removing the support for the original filter syntax.

**Comment by zstadler** [comment]
I don't think removing the support for the original filter syntax is a good idea

This the "deprecation" message is only a preference statement from Mapbox, as it clearly says

> filters defined with this syntax will continue to work

Let's not look at the term "deprecation" out of its specific context.

This thread still has no reference of the potential benefits of removing the support for the original filter syntax.

**Comment by cns-solutions-admin** [comment]
The old expressions really seem to be used a lot, also by public services like maptiler.com.
So we probably shouldn't remove the old filter expressions, but rather make sure that the check for old/new is improved, as mentioned above (https://github.com/maplibre/maplibre-gl-js/issues/1385#issuecomment-1195337056)

**Comment by HarelM** [comment]
Technical steering committee that was held today decided not to remove these filters.
So I'm closing this issue as the discussion is mainly around removing the "old" filters.
Feel free to open a new issues with the exact scenario that is problematic so we can track that differently.
I would say that checking the style can be done with other tools maybe? even the style-spec cli (although I think it uses the same code), but again, this can be tracked elsewhere...
