### ISSUE TITLE
NPM package @maplibre/maplibre-gl-style-spec

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#139]
I think we need a package on NPM about the style spec. This would be similar to ```@mapbox/mapbox-gl-style-spec```. The maplibre docs website needs this package.

The package source code is in ```src/style-spec```.

Can we set up some github action to automatically build and publish this?

**Comment by wipfli** [comment]
@msbarry and @nyurik what do you think?

**Comment by wipfli** [comment]
Note that the style spec has its own version and changelog. The style spec is at ```v13.17.0``` while the main repo is at ```v1.14.0```

**Comment by kylebarron** [comment]
Just a note that the Mapbox-hosted style spec appears to still be openly licensed. The [NPM page](https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec) still says ISC license.

**Comment by wipfli** [comment]
Thanks for the hint. The problem is that the style spec contains information relevant for the docs website https://maplibre.org/maplibre-gl-js-docs. And I expect that Mapbox and MapLibre will diverge so that we need our own style spec.

**Comment by wipfli** [comment]
The mapbox NPM package includes all the files of the ```src/style-spec``` folder after building.

https://unpkg.com/browse/@mapbox/mapbox-gl-style-spec@13.17.0/

**Comment by msbarry** [comment]
It also contains which version of Mac, iOS, android, and web support each feature, which I'd expect to diverge over time. Makes sense to publish a new one that reflects the current state of the native and js maplibre projects.

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/pull/140

**Comment by rbrundritt** [comment]
A couple of thoughts on this topic:

Pros for doing this:

- With Mapbox now doing 3D, it is likely that they will start introducing more style spec features around that which may not apply to MapLibre
- Currently the style spec is an "open standard" or at least it was before the recent license change of Mapbox GL JS (believe Mapbox merged the style spec into this SDK). In the past there was talk about making the style spec a real open standard via the OGC, but I believe Mapbox wasn't interested in doing this. Perhaps the MapLibre fork of this would be a good candidate. There are a few companies involved in this project who are OGC members that can help move this forward. Doing this would help validate the MapLibre version as the standard follow if you want to support open standards.

Cons:

- Potential deviation from Mapbox for similar features. We both may end up introducing a style for the same functionality, but implement/name it differently.
- Added complexity for other projects that support style expressions and would need to either support both or choose one. For example; Maputnik, QGIS, all the things listed here: https://github.com/mapbox/awesome-vector-tiles

**Comment by wipfli** [comment]
Thanks for your input. I guess the basic question that we have to ask ourselves is this:

Should MapLibre be fully compatible with Mapbox?

My current understanding is that the answer is _No_ and that paths have already separated with Mapbox GL JS going to version 2.

**Comment by wipfli** [comment]
This package is needed because of the way the documentation website works. If you go to

https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#types-array

you will find a table with the supported SDKs. This content is dynamically generated here

https://github.com/maplibre/maplibre-gl-js-docs/blob/main/docs/components/expressions.js#L1

which in turn uses the data that was defined here

https://github.com/maplibre/maplibre-gl-js/blob/main/src/style-spec/reference/v8.json#L2635

**Comment by wipfli** [comment]
Thanks for the feedback in https://github.com/maplibre/maplibre-gl-js/pull/146#issuecomment-829512449 @nyurik

**Comment by wipfli** [comment]
I would say we remove `--mapbox-api-supported` for the  `gl-style-validate` utility.

**Comment by wipfli** [comment]
The MapLibre style spec is published now at https://www.npmjs.com/package/@maplibre/maplibre-gl-style-spec. Thanks @nyurik for your help.
