### ISSUE TITLE
Fix typescript issues in jest test files

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#1391]
Tests files are not passing typescript checks apparently since it uses swc which isn't a type checker.

We need to fix that by either moving to ts-node or at least run type checking on the test code in a CI step.

This is in continue to the following thread:
https://github.com/maplibre/maplibre-gl-js/pull/1390

**Comment by birkskyum** [comment]
ts-jest typecheck is replaced by `npm run typecheck` (#1431 )

**Comment by HarelM** [comment]
I think this was solved, wasn't it?
Closing, reopen in case I'm wrong...
