### ISSUE TITLE
Map.querySourceFeatures: all parameters should be optional

### ISSUE THREAD

**Issue by cns-solutions-admin** [maplibre/maplibre-gl-js#1393]
According to the documentation of Map.querySourceFeatures the fields sourceLayer (if not a vector tile source) and filter of parameters are optional. 

In the called querySourceFeatures in tile.ts one can see that changing the declaration has no negative consequences, it is just like the whole param(eter)s were not defined.

**Comment by HarelM** [comment]
This is from the docs:
![image](https://user-images.githubusercontent.com/3269297/181017995-5ce8c6e2-74ef-4d1a-bfdc-2899ec402a47.png)


So I don't think I understand the same thing you did. It is required if you pass the `params` which is what is current in the typescript code.
I agree about the `params.filter` being optional.

**Comment by cns-solutions-admin** [comment]
Functionally sourceLayer is required, if the sourceId references a vector tile layer - the same as in a layer spec. it is only required for vector tile spec. (and makes no sense for all other layers).

Implementation was: it is required, if a params object is given - this makes no sense whatsoever.

Implementation before and now: if it is a vector tile layer and no sourceLayer is given, nothing is returned.

So, if you are really pedantic, you can rewrite the documentation as: "the sourceLayer is optional, but if you want to get features from a vector tile layer, you also have to specify a sourceLayer and it better be existing (otherwise you will get nothing). And BTW the sourceId also has to exist, specifying a random string won't be of much use." ;-)

**Comment by HarelM** [comment]
Fair enough. Thanks for taking the time to improve this lib, truly appreciated!

**Comment by HarelM** [comment]
This is waiting for #1394 to be merged.
