### ISSUE TITLE
fill-extrusion breaking change between v1 and v2

### ISSUE THREAD

**Issue by Pessimistress** [maplibre/maplibre-gl-js#1426]
Interleaving with deck.gl custom layers (depth occlusion) broke between 1.15.3 and 2.0.0. For reference the feature works with mapbox-gl v1 and v2.

Expected:

<img width="700" alt="image" src="https://user-images.githubusercontent.com/2059298/182440764-7ff91b9c-dd57-40f0-925c-18506c18e452.png">

Actual:

<img width="651" alt="image" src="https://user-images.githubusercontent.com/2059298/182440647-7e757a54-9526-499e-b444-e41deb6c8df9.png">

See demo at:
https://codepen.io/Pessimistress/pen/ExEoQXL

**maplibre-gl-js version**: 1.15.3, 2.0.0, latest

### Question

The [custom layer example](https://codepen.io/Pessimistress/pen/xxWVWgV) works so the change either happened to near/far plane calculation (deck.gl calculates its own matrices) or depth-buffer related GL parameters.

I am unable to find any documentation about this change. The breaking commit is 20k lines so would appreciate some pointers :)

**Comment by HarelM** [comment]
The typescript migration is mainly cosmetic and there shouldn't be major changes there, but it was a big change and this does issue is basically saying there was a breaking change.
If you know how this extrusion works I would advise to try and look there as I have little knowledge in that aspect unfortunately. Your help in knowledge in deck.gl might also help here.
If you could create a simpler example maybe it will be easier to debug the changes in the code flow.

**Comment by HarelM** [comment]
Ahh, yes, I removed it since there was a problem referencing the package.json file in the typescript migration. I think I noted that in the release notes...
Not sure what the solution my be for this issue though.

**Comment by Pessimistress** [comment]
I understand that the removal is intended. If you can agree that exposing the version identifier is still useful, I can open a PR to inject the version number via rollup config.

**Comment by HarelM** [comment]
I have no objection to bring back the version of it doesn't break anything.
Feel free to create a PR :-)

**Comment by birkskyum** [comment]
We can make typescript behave like this #1471

**Comment by birkskyum** [comment]
Ping me if 2.3.0 needs more changes to resolve this.

**Comment by Pessimistress** [comment]
@birkskyum Thank you!
