### ISSUE TITLE
Any way to add multiple default (SVG) markers to one SVG DOM?

### ISSUE THREAD

**Issue by stodge** [maplibre/maplibre-gl-js#144]
**maplibre-gl-js version**: 1.14.0

### Question

When adding a default marker, it is inserted into the HTML DOM as an entire SVG DOM. So, multiple markers are each added as separate SVG DOMs. Is there any way to create one SVG DOM (e.g. as a map layer), and each default marker is added to it, so there is only one SVG DOM?

**Comment by razorness** [comment]
You can use `map.addImage` to add your SVGs as image and use them with `SymbolLayer`.

```javascript
const img = new Image(w, h);
img.onload = () => map.addImage('myId',  img, {pixelRatio: window.devicePixelRatio});
img.onerror = console.error;
img.src = mySvgDataUrl;
```

**Comment by stodge** [comment]
Thanks, I'll take a look.

**Comment by rbrundritt** [comment]
I agree with razorness, converting the SVG to an image will is the simplest option, and if you do that, then it makes sense to use the a symbol layer for increased performance. 

This assumes that your SVG's won't be using CSS classes or have dynamically changing CSS styles (i.e. change stroke color on hover). If you need to have different "states" for an SVG, you can still create images for each state and use an expression in a symbol layer to select which image you want to use.

**Comment by razorness** [comment]
In case of using a style switch (f.e. to switch between a vector style and satellite raster style) you will have to re-add your images after every switch.
