### ISSUE TITLE
 Duplicate identifier 'ExpressionSpecification' in the new Maplibre-gl 2.2.0

### ISSUE THREAD

**Issue by petrot** [maplibre/maplibre-gl-js#1462]
**maplibre-gl-js version**: 2.2.0

**browser**:

### Steps to Trigger Behavior

 1. Simply run `ionic serve` with Andular /Ionic app

### Link to Demonstration

After call the ionic serve, a got the following errors:

```
] Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:218:21 - error TS2300: Duplicate identifier 'ExpressionSpecification'.
[ng] 
[ng] 218 export declare type ExpressionSpecification = [
[ng]                         ~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
[ng] 
[ng] Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:1597:21 - error TS2300: Duplicate identifier 'ExpressionSpecification'.
[ng] 
[ng] 1597 export declare type ExpressionSpecification = {
[ng]                          ~~~~~~~~~~~~~~~~~~~~~~~
[ng] 
```

### Expected Behavior

Works as expected.

### Actual Behavior

Build failure

**Comment by HarelM** [comment]
This was probably introduced in the following PR #1390.
Feel free to send a PR to fix this. I hope to get to it in the coming days.
Sorry for the inconvenience.
Meanwhile you can use version 2.2.0-pre.3 I think.

**Comment by wipfli** [comment]
Reproduced in https://github.com/wipfli/maplibre-typescript

**Comment by wipfli** [comment]
I turned on daily dependabot updates in https://github.com/wipfli/maplibre-typescript so next time we have a TypeScript problem in a pre-release I will get an alert. Though does dependabot actually use prereleases?

**Comment by HarelM** [comment]
I think we're should figure out how to test it as part of the CI. Unfortunately, this is not the first time we break the typings :-(

**Comment by petrot** [comment]
Thank you guys! :)

**Comment by HarelM** [comment]
No problem, but the types are not perfect apparently, I just stumbled across an issue with my code when updating to the latest version.
But, we'll get better with time :-)
