### ISSUE TITLE
MapboxDraw does not work with Terrain

### ISSUE THREAD

**Issue by cns-solutions-admin** [maplibre/maplibre-gl-js#1464]
Version 2.2.0:

If there is a terrain, MapboxDraw does not work - the mouse pointer does not change and nothing is drawn.

**Comment by HarelM** [comment]
Please provide a reproduction using jsbin/stackblitz etc.
Also an error that is thrown into the console would be helpful...

**Comment by cns-solutions-admin** [comment]
Updated to maplibre 2.3.0: works now.
