### ISSUE TITLE
Add a build script to build all

### ISSUE THREAD

**Issue by cns-solutions-admin** [maplibre/maplibre-gl-js#1467]
It seems that there is no simple way to build maplibre-gl. Instead it seems to be necessary to
* npm run generate-typings
* npm run build-dev
* npm run build-prod
* npm run build-csp
* npm run build-css

It would be nice to have "build" script that does all that.
Additionally it should be called from a "prepare" script.
This way a "npm pack" will prepare = build everything and pack it in an archive.

**Comment by HarelM** [comment]
Depends on the need, these are available.
CI runs them all, but not in every run...
In any case, if you want to add another script to the package.json feel free. There are already a ton there :-)

**Comment by cns-solutions-admin** [comment]
Adding the full build to "prepare" is not a good idea, as according to https://docs.npmjs.com/cli/v8/using-npm/scripts#npm-pack, prepare is called for nearly all commands including install.
Maybe we should add it to 'prepack'?

**Comment by HarelM** [comment]
I think this is good enough... You can add some notes to readme if you want.
I don't think prepare is a good direction as well.
