### ISSUE TITLE
Disable cooperative gestures in fullscreen

### ISSUE THREAD

**Issue by xjcb-de** [maplibre/maplibre-gl-js#1488]
The `cooperativeGestures` feature (https://github.com/maplibre/maplibre-gl-js/issues/234) is great! It is super helpful when integrating a map in a website.
It can be even more useful when it automatically disables itself after the user put the map in full-screen mode (via clicking on a `maplibregl.FullscreenControl()` button).

Because once the map is in full-screen mode the user won't accidentally move the map since it is the only thing visible on the screen. It only makes the map harder to use at this point.

So my suggestion is to have the map in full-screen mode just work as if the cooperative gestures were never enabled in the first place. When the full-screen is closed, cooperative gestures should again function normally.

**Comment by HarelM** [comment]
This is waiting for code review fixes from here: #1487
