### ISSUE TITLE
Ctrl + scroll zooms the page, not the map

### ISSUE THREAD

**Issue by xjcb-de** [maplibre/maplibre-gl-js#1491]
When the `cooperativeGestures` feature is enabled, users have to scroll **and** press <kbd>ctrl</kbd> for zooming the map.
The problem is that sometimes <kbd>ctrl</kbd> + scroll doesn't zoom the map but instead zooms the whole page.

This should not happen, but happens when:
- the browser window is not in focus or
- the map is used in an iframe, but the iframe is not in focus

![simplescreenrecorder-2022-08-14_21 06 37](https://user-images.githubusercontent.com/72317350/184551828-9db95183-2597-491f-b706-3c19967f9d98.gif)

**maplibre-gl-js version**: 2.3.0
**browser**: firefox, chromium

**Comment by HarelM** [comment]
Yup :-) I had a feeling ctrl+scroll might not do the right thing :-)
Feel free to submit a PR to fix this.

**Comment by HarelM** [comment]
Can't this be solved be not allowing the user to change the size of the page - something with the html headers, viewport metadata something?
I'm not sure this is something that should be handled as part of this library.

**Comment by HarelM** [comment]
No extra info was provided. I think the last comment is the right solution.
Closing for now, I'll be happy to reopen in the future if need be.
