### ISSUE TITLE
non-Mapbox sources are billed in v1.x

### ISSUE THREAD

**Issue by hyperknot** [maplibre/maplibre-gl-js#1507]
I've just figured out a bug in Mapbox GL JS which is also present in Maplibre 1.0. I'm copying it below.
https://github.com/mapbox/mapbox-gl-js/issues/12171

---

### Steps to Trigger Behavior

Load a non-Mapbox source with Mapbox access token specified in v1.x.
The load will be billed by Mapbox.

### Detail
The bug is a missing bracket on the 2nd line here:
https://github.com/mapbox/mapbox-gl-js/blob/50adf1cc14e5aef09099f15c5cb803eaa5f72a48/src/util/mapbox.js#L392-L397

This means everyone who used 1.x with an access token was billed for non-Mapbox source loads. 

Simple bug - probably thousands of dollars billed in error to customers.

Note: using Prettier would have made it obvious to see this bug.

**Comment by HarelM** [comment]
We can't change this file as it will violate Mapbox terms and conditions.
Only Mapbox can change it.
You are welcome to use version 2.x of this library which doesn't communicate with Mapbox at all.
Sorry...
