### ISSUE TITLE
Event 'contextmenu' triggered after rotate/pitch

### ISSUE THREAD

**Issue by cns-solutions-admin** [maplibre/maplibre-gl-js#1511]
Version: 1.x and 2.x up to current 2.2.0

The "contextmenu" event is triggered, even if the mouse was dragged and the map rotated or pitched.
This corresponds to https://github.com/mapbox/mapbox-gl-js/issues/7221.

browser: chrome, firefox
operating system: windows

Probably does not happen on other OS (https://github.com/mapbox/mapbox-gl-js/issues/8824)?

### Steps to Trigger Behavior

1. press and hold right mouse button on map
2. move the mouse to rotate the map
3. release right mouse button

### Link to Demonstration

https://jsfiddle.net/martinatcns/1cjp9a46/5/

### Expected Behavior

No contextmenu event fired

### Actual Behavior

On Windows, contextmenu event is fired

### Workaround

```
let shouldOpen = false;
map.on('mousedown', e => shouldOpen = e.originalEvent.button === 2);
map.on('rotate', () => shouldOpen = false);
map.on('pitch', () => shouldOpen = false);
map.on('contextmenu', e => {
	if (shouldOpen) {
		shouldOpen = false;
		// do whatever you want to do
		...
	}
});
```

The workaround in the mapbox issue is not sufficient:
* it opens the context menu, if the map is pitched (and not rotated)
* it does not open the context menu,  if before the current right-click the map was autorotated (e.g. to 0-rotation)

**Comment by HarelM** [comment]
I can't reproduce it in chrome/macos but it doesn't mean it's not there.
I suggest to open a PR and have a test to cover this behavior.

**Comment by cns-solutions-admin** [comment]
Yes, as already mentioned in the description, this seems to be a problem in windows only. It does not happen in Linux (Mint) either.

Based on comment https://github.com/mapbox/mapbox-gl-js/issues/3803#issuecomment-267720890 I create a new version of the demonstration, which logs the original events:
* https://jsfiddle.net/martinatcns/1cjp9a46/6/

In Windows the browser event contextmenu seems to be triggered after mouseup, in Linux (MacOS?) already after mousedown:

Events in Linux:
* mousedown
* contextmenu
* (mousemove)
* map context menu event (if not moved or so)
* mouseup

Events in Windows:
* mousedown
* (mousemove)
* mouseup
* map context menu event (always)
* contextmenu

**Comment by HarelM** [comment]
Can you reproduce this on a "plain" canvas (i.e. a html canvas without maplibre and all this stuff)?
If so then this is a bug in chrome on windows and not here...

**Comment by cns-solutions-admin** [comment]
The example's events are those of the plain div. It is NOT a bug of windows browsers, but just different behaviour (I don't think it is specified when the contextment event is triggered).

The code in maplibre (map_events.ts, BlockableMapEventHandler) already accounts for this difference in order, but it fails to prevent the map's contextmenu event to be triggered after rotate/pitch in Windows. 

I did no further analysis, but I assume that the rotate/pitch handlers cass the reset() method, which won't have any consequence in Windows.
