### ISSUE TITLE
Raster is blurred if 3D terrain is active and map is on the edge of valid terrain data

### ISSUE THREAD

**Issue by zdila** [maplibre/maplibre-gl-js#1515]
**maplibre-gl-js version**: 2.3.0

**browser**: Chrome, Vivaldi, Firefox

### Steps to Trigger Behavior

 1. use 3D terrain with some raster tiles
 2. go to the edge of the valid terrain data

![image](https://user-images.githubusercontent.com/636095/185460970-6a6ef81e-3978-48a6-ac1b-2389d14f92b7.png)

### Link to Demonstration

https://labs.maptiler.com/samples/maplibre/terrain/#style=satellite&lat=49.20184073&lng=20.12510777&zoom=13.93&bearing=-44.04&pitch=70.00&3d=true

https://labs.maptiler.com/samples/maplibre/terrain/#style=gray-shading&lat=49.20184073&lng=20.12510777&zoom=13.93&bearing=-44.04&pitch=70.00&3d=true

### Expected Behavior

Tiles should be sharp (normal)

### Actual Behavior

Tiles are very blurred. Rotating/moving the map to terrain-covered position helps and tiles become immediately sharp.

**Comment by HarelM** [comment]
Yea, I've seen this too.
Isn't this a duplicate #1137?

**Comment by zdila** [comment]
For me #1137 looks to be a different thing because in "my" case the tiles are much more blurred and it affects all the tiles, also the nearest.

**Comment by HarelM** [comment]
I get this, but I've seen when testing the 3D branch this behavior as well.
I believe it is the same issue, I don't think it's worth keeping two issues for this.
In case there's a solution to the other issue but this keep happening we can always open/re-open...
Closing in favor of #1137.
I suggest to add the info provided here over there, it won't hurt...
![image](https://user-images.githubusercontent.com/3269297/185464417-db83dfd3-ac26-4651-a08f-0a1070d85c84.png)

**Comment by zdila** [comment]
Yes, sometimes it is rendered correctly also for me.
