### ISSUE TITLE
Usage of Typescript annotations

### ISSUE THREAD

**Issue by kircher1** [maplibre/maplibre-gl-js#1519]
### Question

There are parts of the code base that aren't using type annotations e.g., parameters/return of...

```ts
function drawFillTiles(painter, sourceCache, layer, coords, depthMode, colorMode, isOutline)
```

Is the idea to opportunistically update these, or are these being left without types intentionally?

**Comment by HarelM** [comment]
The code was migrated from "flow". We do our best to improve the situation as we go along.
Any PR that adds typings is welcome!
I try to add typings each time I touch shine part of the code.
In any case, I don't think this should remain an issue. Can you please convert this to a discussion?

**Comment by kircher1** [comment]
Ok, good to know! I will try and update some of these cases in the render code. Thanks for the quick clarification.

By the way, I used the question template of the issue. I'm not sure what's better posed as a question here or a discussion topic. The two seem like they could overlap. You've answered my question though, so I'm closing this. Thanks!
