### ISSUE TITLE
3d buildings example runtime error

### ISSUE THREAD

**Issue by chrisamow** [maplibre/maplibre-gl-js#152]
loading this link in the browser:
https://maplibre.org/maplibre-gl-js-docs/example/3d-buildings/

the following error can be seen in the console:
```
instrument.ts:129 Error: layers.3d-buildings: source "composite" not found
    at Object.Bn [as emitValidationErrors] (validate_style.js:37)
    at Ue (style.js:46)
    at i._validate (style.js:1211)
    at i.addLayer (style.js:677)
    at r.addLayer (map.js:1888)
    at r.<anonymous> ((index):27)
    at r.Ct.fire (evented.js:119)
    at r._render (map.js:2511)
    at map.js:2629
```
from linux
observed on chrome Version 77.0.3865.120 (Official Build) (64-bit)
firefox 77.0.1

**Comment by wipfli** [comment]
Nice, thanks for contributing this bug report. Do you know how to fix this? If yes, feel free to edit https://github.com/maplibre/maplibre-gl-js-docs/blob/main/docs/pages/example/3d-buildings.html and create a pull request in the [docs repo](https://github.com/maplibre/maplibre-gl-js-docs/).

**Comment by chrisamow** [comment]
@wipfli Sure thing!  Unfortunately, I couldn't find any hints on solutions with the existing docs and references I saw related to source configuration.  I don't mind doing some debugging if you have some guidance?  Thanks!

**Comment by wipfli** [comment]
Maybe we can fix this together :)

The error message means that it cannot find a source called `conposite`. And indeed the style does not have this source. But what happens if you replace `composite` with `openmaptiles` in the example code?

**Comment by chrisamow** [comment]
Great idea!  :)

Well, it's amazing how easy it is when someone knows what they are doing - that seems to fix it - is there any downside to that as a solution?  Want me to submit a PR for the sample?

Thanks!!

**Comment by wipfli** [comment]
Thanks. Glad to hear this 😸 I think this solution is fine. If you could make a pull request to the docs repo it would be great. Let me know if you need help with this.

**Comment by HarelM** [comment]
Can we close this issue then? Seems like this was fixed...?
