### ISSUE TITLE
Pitfalls Terrain Generation

### ISSUE THREAD

**Issue by cns-solutions-admin** [maplibre/maplibre-gl-js#1547]
I had some problems with the quite short description of the terrain tile generation (https://demotiles.maplibre.org/terrain-tiles/).
It should be improved.

My final working solution (replace apt with your distribution's package manager):
* get proj, gdal, e.g. apt install proj-bin proj-data gdal-bin gdal-data
* other prerequisites: apt install python3-pip sqlite3
* get rasterio (rio) < 3 (otherwise you get an error: densify_pts must be at least 2 if the output is geograpic), e.g. apt install rasterio (gave me 1.1.3, which worked)
* get rio-rgbify: pip install rio-rgbify
* in the script replace "rio" with "rasterio"
* ignore warnings, when running the script:
```
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/mercantile/__init__.py:77: FutureWarning: Mercantile 2.0 will require tile x and y to be within the range (0, 2 ** zoom)
  warnings.warn(
/usr/lib/python3/dist-packages/rasterio/__init__.py:223: NotGeoreferencedWarning: Dataset has no geotransform set. The identity matrix may be returned.
```

**Comment by HarelM** [comment]
I don't think terrain generation is part of this repo...
Please use slack or other method to communicate your issues.

**Comment by cns-solutions-admin** [comment]
The description for the tile generation is linked from the terrain example and is on the maplibre.org domain. So where else than here add an issue for a better description?

**Comment by HarelM** [comment]
One of those:
https://github.com/maplibre/maplibre.github.io
https://github.com/maplibre/maplibre-gl-js-docs
