### ISSUE TITLE
workerUrl for csp not working in esbuild

### ISSUE THREAD

**Issue by httpete** [maplibre/maplibre-gl-js#1550]
Hi,

esbuild yells at us if we try to do

maplibregl.workerUrl = "path/to/worker.js"

"cannot assign to import"

It looks like MapBoxGL lets you assign a workerclass instead of a url. Can yours do that?

**Comment by HarelM** [comment]
We'll need more info in order to understand what you mean... Please provide code pen of both options.
In theory (assuming we haven't break this), this should work as it did in mapbox 1.13.

**Comment by httpete** [comment]
Thanks @HarelM 

So MapBox has: https://docs.mapbox.com/mapbox-gl-js/api/properties/#workerclass

It is specifically designed to do what I am saying. We use esbuild, and the distribution you have of the 

https://unpkg.com/browse/maplibre-gl@2.3.0/dist/maplibre-gl-csp.js

Only ships an IFFE / UMD version. It would be better if you could distribute multiple package formats, so we can slowly move to ESM. 

Here, there is a thread describing why:
https://github.com/evanw/esbuild/issues/891

The other alternative is to provide another way to set the worker url or worker class without the = assignment, so it can work with ESM bundlers. esbuild is a huge player in the space today.

**Comment by httpete** [comment]
The way to reproduce this is to simply try to use the sample csp mgl.workerUrl= "" method in a project that uses esbuild. Anyone will hit this error.

**Comment by HarelM** [comment]
This is still to vague. Can you please create a stackblitz reproduction?

**Comment by httpete** [comment]
After review, I found that if you import it via:

```
import maplibreGl from "maplibre-gl/dist/maplibre-gl-csp";
maplibreGl.workerUrl = '/js/webworker.js';
```

it works. But if you do this:

```
import * as maplibreGl from "maplibre-gl/dist/maplibre-gl-csp";

maplibreGl.workerUrl = '/js/webworker.js';
```
It doesn't.
