### ISSUE TITLE
2.3.0 3D terrain fix breaks panning : (

### ISSUE THREAD

**Issue by openSourcerer9000** [maplibre/maplibre-gl-js#1555]
Thanks to all who contributed in fixing #1241 and fixing the 3D terrain feature. Unfortunately, a breaking change got introduced where after panning the map, it will glitch and jump back to the exact same spot. Trying with the arrow keys is even jankier, it will just scoot around randomly, usually in the opposite direction of which arrow you press. Both are shown in the video below. 

When I don't add the 3D terrain, everything works just fine. In the previous version where the 3D terrain was making tiles disappear (#1241), panning the map had no issues, so this breaking change was introduced with 2.3.0.

https://user-images.githubusercontent.com/61931826/186980479-b5d70441-38dd-446d-8991-013f60c140af.mp4

**maplibre-gl-js version**:
2.3.0
**browser**:
chrome
### Steps to Trigger Behavior
Add 3D terrain, try to pan the map

**Comment by HarelM** [comment]
Can you please share a jsbin/codepen/stackblitz reproduction?

**Comment by HarelM** [comment]
No response and I don't think this issue exists in latest version.
In case there's an issue please open a new one.
