### ISSUE TITLE
Terrain not shown in style-spec in docs

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#1563]
This part of the style spec doesn't seem to appear anywhere in the docs

https://github.com/maplibre/maplibre-gl-js/blob/1c592d4c28f6acd55529a4a3541d255434bdbb34/src/style-spec/reference/v8.json#L3825-L3857

**Comment by HarelM** [comment]
Probably a doc generation issue, isn't it? I suggest to see what needs to be added to docs repo, I doubt it's a problem here, don't you?

**Comment by birkskyum** [comment]
That is a very good point. I'll move it there - just made an issue before I forgot about it.

**Comment by birkskyum** [comment]
https://github.com/maplibre/maplibre-gl-js-docs/issues/267
