### ISSUE TITLE
Something broken when 3D terrain enabled. 

### ISSUE THREAD

**Issue by junhaotong** [maplibre/maplibre-gl-js#1577]
3D terrain broken in a special place

https://user-images.githubusercontent.com/20011131/187213424-972d1f1c-d670-484b-af53-3ac33e36f57e.mov

**maplibre-gl-js version**: 2.4.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. zoom in & zoom out

### Link to Demonstration
https://codepen.io/junhaotong-the-typescripter/pen/jOzjgqy

**Comment by junhaotong** [comment]
I guess the main problem is there have some empty space.

<img width="1640" alt="Screen Shot 2022-08-29 at 17 39 15" src="https://user-images.githubusercontent.com/20011131/187214713-c6321859-1326-4a15-b301-23608b93b322.png">

**Comment by HarelM** [comment]
When moving from this specific place the problem doesn't reproduce.
I think it might be an end of the tile issue or DEM issue, not sure of course.
But it's easy to reproduce

**Comment by HarelM** [comment]
There seems to be a gap between the tiles, so I would say that this is an invalid data...
![image](https://user-images.githubusercontent.com/3269297/187216373-589402e5-1255-4d0d-b7cb-ee6bc9e80123.png)

**Comment by HarelM** [comment]
No response, closing as suspected problem in DEM.
