### ISSUE TITLE
Handling High DPI Raster Tiles

### ISSUE THREAD

**Issue by boldtrn** [maplibre/maplibre-gl-js#158]
## Motivation

Most raster tile servers offer high dpi tiles by adding `@2x` to the request. Unfortunately, maplibre only supports this for Mapbox URLs, see: https://github.com/maplibre/maplibre-gl-js/blob/main/src/util/mapbox.js#L109

It would be great if it would be possible to specify if a raster url supports high dpi tiles.

For example Leaflet supports this by adding `{r}` to the URL scheme.

### Implementation

- We would need a way to mark if a raster source supports high dpi tiles
- Then we would need to add the high dpi parameter, for high dpi screens.

**Comment by kylebarron** [comment]
Seems a duplicate of https://github.com/maplibre/maplibre-gl-js/issues/141?

**Comment by boldtrn** [comment]
Ah yes indeed, thanks for pointing that out 👍
