### ISSUE TITLE
Broken sourcemap generation from Plugin Import Assert when building

### ISSUE THREAD

**Issue by BAschl** [maplibre/maplibre-gl-js#1582]
When building the project the generation of sourcemaps for debugging (setting breakpoints) doesn't work anymore.
I tried it with a fresh clone and even on another machine.

My current workaround is commenting out `importAssertionsPlugin(),` in `rollup_plugins.ts`

My guess is, that `Could not parse JSON file` in the log (see below) is related, as it also vanishes when doing the workaround.

**maplibre-gl-js version**: 2.4

### Steps to Trigger Behavior

 1. Build project (production or development, doesn't matter)
 2. See log (or try setting a breakpoint in your IDE)

### Expected Behavior

Sourcemaps get generated

### Actual Behavior

Sourcemaps don't get generated. Breakpoints can't be set.
Log:
```
[...]\maplibre-gl-js> npm run build-dev
Debugger attached.

> maplibre-gl@2.4.0 build-dev
> rollup --configPlugin @rollup/plugin-typescript -c --environment BUILD:dev

Debugger attached.

src/index.ts, src/source/worker.ts → rollup/build/maplibregl...
(!) Broken sourcemap
https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as "rollup-plugin-import-assert") should generate accompanying sourcemaps
(!) Circular dependencies
src/style-spec/expression/parsing_context.ts -> src/style-spec/expression/compound_expression.ts -> src/style-spec/expression/parsing_context.ts
src/style-spec/validate/validate.ts -> src/style-spec/validate/validate_function.ts -> src/style-spec/validate/validate.ts
src/style-spec/validate/validate.ts -> src/style-spec/validate/validate_function.ts -> src/style-spec/validate/validate_object.ts -> src/style-spec/validate/validate.ts
...and 11 more
(!) Plugin json: Could not parse JSON file
package.json
src/style-spec/reference/v8.json
created rollup/build/maplibregl in 17.8s

rollup/maplibregl.js → dist/maplibre-gl-dev.js...
created dist/maplibre-gl-dev.js in 1.3s
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
```

**Comment by HarelM** [comment]
Due to the event nature of this library and the speed it's running I usually don't use breakpoints personally, but rather console.log.
Also there's the ability to simply creat a breakpoint I the browser when using the dev.js file.
I agree this is not ideal, don't get me wrong, but there are workarounds.
I'm not an expert with rollup so feel free to dig into it and fix it :-)

**Comment by pgoldberg** [comment]
Trying to fix this upstream here: https://github.com/calebdwilliams/rollup-plugin-import-assert/pull/8

If/when that gets merged and released, I'll open a PR to bump the dependency here!

**Comment by HarelM** [comment]
Thanks for taking the time to look into it!

**Comment by nicky132** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/34881461/209529141-a345a9ba-1c32-4f7e-9449-3101220b3fcb.png">

why only i got “Could not resolve entry module (rollup.config.js)” error message,but your building  seem work  fine

**Comment by HarelM** [comment]
Did you try running npm and not yarn?
