### ISSUE TITLE
browser integration test "CJK Characters" always fail

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#1592]
I cannot get this browser integration test "CJK Characters" to pass at all, Linux or windows.
Upon further investigation I think this line is the problem:
<code>map.getCanvas().toDataURL()</code>

toDataURL is always going to give slightly different strings depends on OS/browser versions etc. Therefore when it comes to compare using tipple equal later, the conditions are always false even though they are visually the same.

Has anyone experience the similar problem and/or working on a fix? Thanks

**Comment by HarelM** [comment]
I think @birkskyum tired to solve this.
Feel free to try and improve this.
I made it so it passes on CI, it conflicted with running locally.
Any help in this aspect would be appreciated!

**Comment by birkskyum** [comment]
@zhangyiatmicrosoft , you're right. This test will break every time it's on a new machine, which at this point is every machine that isn't the CI runner so it's an exception from the other render tests. You can either ignore it and enjoy that your code will still work on the CI, or you can setup your machine to pass the test. That would mean doing the following:

1. Capture the content as it is rendered on your machine. One way to do it is to console.log() it.
2. Copy the content from the terminal.
3. Save it in a HTML file. This file you can open in a browser to confirm that the font is rendered.
4. Add the HTML file to the list of files the test is compared against.

<img width="1005" alt="Screen Shot 2022-08-30 at 20 40 04" src="https://user-images.githubusercontent.com/74932975/187517894-b6ed8604-30aa-4cf4-82e7-60f564818e9a.png">

**Comment by zhangyiatmicrosoft** [comment]
Thanks
