### ISSUE TITLE
Add lookAt(3D point of interest, camera attitude) camera function

### ISSUE THREAD

**Issue by AbelVM** [maplibre/maplibre-gl-js#1599]
Inspired by [this gist](https://bl.ocks.org/andrewharvey/a0b56df5d605d86facc3da9723a9ef6e), I think that a `lookAt` function would be a sleek and neat functionality to add to the new set of native camera functionalities.

This function will allow the users to set the PoV just by giving the 3D point of interest and the camera attitude. In the example from the reference, the point of interest is located at the rooftop of the 3D building:
![image](https://user-images.githubusercontent.com/9017165/187859376-3443b2b6-ce87-456a-ac05-84f9dbf2fff6.png)
(Img. credits: @andrewharvey)

I've just edited the referenced code within this tiny function to add that functionality to MapLibre in an easy and harmless way :nerd_face: . It takes an `options` object as input as described in the comments

```javascript
/*

    This function sets the camera PoV based on the 3D point the user want to focus on
    and the attitude of the camera.

    Based on: https://bl.ocks.org/andrewharvey/a0b56df5d605d86facc3da9723a9ef6e

    Parameters:
    * center: latlng object of the observed point,
    * elevation: meters above sea level of the observed point (default: 0)
    * exageration: if Terrain3D is used, this should be the same exageration value (default: 1)
    * bearing: camera bearing (default 0)
    * pitch: camera pitch (default: 45)
    * hover: number of zoom levels to back off the camera (default: 2)

*/
const lookat = function (o) {
    // Defaults
    const defaultconfig = {
        'bearing': 0,
        'pitch': 45,
        'elevation': 0,
        'exageration': 1,
        'hover': 2
    };
    o = Object.assign(defaultconfig, o);

    const
        r = Math.PI / 180,
        e = o.elevation * o.exageration,
        d = e / Math.tan(o.pitch * r),
        dx = d * Math.sin(o.bearing * r),
        dy = d * Math.cos(o.bearing * r);
    const
        mercatorCenter = new globalThis.maplibregl.MercatorCoordinate.fromLngLat(o.center, 0),
        mercatorCenterProjected = new globalThis.maplibregl.MercatorCoordinate(
            mercatorCenter.x + (dx * mercatorCenter.meterInMercatorCoordinateUnits()),
            mercatorCenter.y + (-dy * mercatorCenter.meterInMercatorCoordinateUnits()),
            0);
    this.easeTo({
        'center': mercatorCenterProjected.toLngLat(),
        'bearing': o.bearing,
        'pitch': o.pitch
    });
    /*
        Dolly zoom:
        Ref: https://en.wikipedia.org/wiki/Dolly_zoom#Calculating_distances
    */
    const
        circumferenceAtEquator = 2 * Math.PI * 6378137,
        zoom = Math.log2(circumferenceAtEquator / (2 * e * Math.tan(this.transform._fov / 2)));
    this.setZoom(zoom - o.hover);
};
globalThis.maplibregl.Map.prototype.lookAt = lookat;
```

For the example above, the we should call the function like:

```javascript
mymap.lookAt({
    'center': [ 151.2015, -33.8620 ],
    'elevation': 1000,
    'bearing': 90
});
```

**Comment by HarelM** [comment]
Wasn't this just implemented? With camera options...

**Comment by AbelVM** [comment]
AFAIK 
* Current function set the camera at a given point and attitude
*  `lookAt` function set the camera so **you are looking to a given 3D point**

**Comment by HarelM** [comment]
I mean #1427

**Comment by AbelVM** [comment]
You're right, I didn't realize it's quite the same as `calculateCameraOptionsFromTo` , but... That function asks for a lot of parameters that I, as user, might not know (like the optimal (x, y, z) of the camera). 

Mine just asks the user for the 3D point of interest and the desired attitude of the camera, simplifying the dev experience

**Comment by HarelM** [comment]
It's more robust, you can wrap it with your easy to use function.
Closing...
