### ISSUE TITLE
Suppress error messages for missing raster tiles

### ISSUE THREAD

**Issue by mactrem** [maplibre/maplibre-gl-js#160]
Returning http status code 204 (no content) with no body for missing tiles is used in many mapserver implementations like TileServer GL (https://github.com/maptiler/tileserver-gl/issues/46) and also proposed by the OGC API Tiles (https://github.com/opengeospatial/ogcapi-tiles/blob/master/core/standard/requirements/core/REQ_tc-success.adoc).    
This is particularly the case for raster tile sources  where heterogenous maximum zoom levels are common.   
MapLibre doesn't explicitly handle the 204 status for raster tiles which leads to a large number of error messages in the dev console.   

### Expected Behavior
No errors are thrown when a mapserver returns 204 for a missing raster tile and therefore no error messages in the dev console

### Actual Behavior
![image](https://user-images.githubusercontent.com/75912142/119965946-19e9d600-bfab-11eb-98a9-da84b275d39e.png)

**Comment by frank-unovica** [comment]
+1

**Comment by HarelM** [comment]
The following PR might be relevant to this issue:
- #8335
