### ISSUE TITLE
Hillshade rendering bug in Brave

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#1601]
In Brave, the hill-shade sometimes causes this issue, but not in all cases:

It's working here (in Brave as well):
https://jsfiddle.net/0v8hpatL/1/
<img width="565" alt="Screen Shot 2022-09-01 at 22 44 34" src="https://user-images.githubusercontent.com/74932975/188009051-c1c2398f-7cb0-4aff-92d6-016fac9d373b.png">

It's not working here with same code - just in codepen instead:
https://codepen.io/birkskyum-1471370946/pen/oNdNgLq

<img width="911" alt="Screen Shot 2022-09-01 at 22 43 21" src="https://user-images.githubusercontent.com/74932975/188008994-ffa02f63-e73a-4234-a5cb-97cf4ead9fa5.png">

The hillshade also makes trouble in our online 3d terrain examples, but only in some cases. It's present on our docs site, but not in the local debug-pages:
https://maplibre.org/maplibre-gl-js-docs/example/3d-terrain/

Brave with Chromium 105:
<img width="684" alt="Screen Shot 2022-08-26 at 10 53 01" src="https://user-images.githubusercontent.com/74932975/186866696-a81c51a9-6e1d-4c51-8cba-72040ba3b946.png">
<img width="527" alt="Screen Shot 2022-08-26 at 11 05 23" src="https://user-images.githubusercontent.com/74932975/186869183-0bfb78a0-c3ba-4c13-9378-3a11b9be5547.png">

**Comment by HarelM** [comment]
Why opening an issue here and not in brave's issue tracker (I hope they have one)?

**Comment by birkskyum** [comment]
You're so right - I've put it here instead: https://github.com/brave/brave-browser/issues/25149

These spikes seem to b similar, and I can see other projects have them too.
