### ISSUE TITLE
Terrain elevation tile stiching

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#1602]
https://stackblitz.com/edit/typescript-oepgsb?file=index.html

There appears to be an issue where the tiles further away are on a different zoom level, so when zooming out the tiles in the viewport doesn't update at the same time leading to inconsistencies in the mesh between tiles. 

In the example, deck.gl can be toggled to render the same terrain, and the issue is less pronounced there, so we might want a better strategy for requesting the elevation rgb tiles.

<img width="388" alt="Screen Shot 2022-09-01 at 23 28 04" src="https://user-images.githubusercontent.com/74932975/188016264-c6a56896-3bc3-453a-b972-b2c4c02245c9.png">

**Comment by HarelM** [comment]
Are you sure this is not a data issue? The problem can be seen in both deck.gl and maplibre...

**Comment by birkskyum** [comment]
I believe it's because they both suffer from the same issue with 3d tiles at different zoom levels not aligning.

**Comment by prozessor13** [comment]
Yep, this happens on borders of different zoomlevels. This could be easy fixed, creating a small border in the 3d-mesh down to sea-level on every render-to-texture tile.

current mesh:
![IMG-2535](https://user-images.githubusercontent.com/45103/188307692-c61d1edc-e2c9-4f93-b134-037b3220e9ce.JPG)

mesh with border to sea-level
![IMG-2536](https://user-images.githubusercontent.com/45103/188307708-d80e5e44-a052-4443-a935-4b5b0e529a81.JPG)

**Comment by HarelM** [comment]
I wouldn't go to sea level due to dead sea problem being under the sea level, but sure, we could create a surface with a few (hunderd) meters at the edge I guess...
I have no clue how to do it, but this sounds like it should solve the problem :-)

**Comment by birkskyum** [comment]
because of the elevation offset hack the dead sea is actually rendered above sea level

**Comment by prozessor13** [comment]
I sayed down to *sea-level* but i am wrong, something like 10 pixels should be enough, every pixel more may costs performance.

**Comment by birkskyum** [comment]
There's also the option to request more tiles of the same zoom level, depending on how expensive that would be.

**Comment by HarelM** [comment]
When the pitch is allowing you to see many tiles this becomes problematic... The original reason for different zoom level tiles is performance :-)
