### ISSUE TITLE
404 link to Community.md file

### ISSUE THREAD

**Issue by gregsadetsky** [maplibre/maplibre-gl-js#1617]
Hey,

https://github.com/maplibre/maplibre-gl-js/blob/main/COMMUNITY.md

currently has a link to

https://github.com/maplibre/maplibre/blob/main/COMMUNITY.md

which is 404.

I'm unsure whether it'd be better to link to https://github.com/maplibre/maplibre/ simply, or some file in that repo e.g., CHARTER.md..? I'd be happy to open a PR with an updated link.

Cheers

**Comment by HarelM** [comment]
Any PR would be welcome!
The community page is here basically :-)
https://maplibre.org/community/
