### ISSUE TITLE
Hill shade too opaque in some camera situation

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#1635]
Move the camera around in our hill shade example to see these 'step' effects where the hill shade suddenly changes. When close to the mountains, the completely opaque hill shade is too much.

http://0.0.0.0:9966/test/debug-pages/terrain-hillshade.html#10.72/47.259/11.6009/77.1/70

<img width="1099" alt="Screen Shot 2022-09-11 at 20 42 26" src="https://user-images.githubusercontent.com/74932975/189543897-d14c955b-1536-443a-94a8-cb4aef1a6ea4.png">
<img width="1022" alt="Screen Shot 2022-09-11 at 20 42 19" src="https://user-images.githubusercontent.com/74932975/189543898-605f49fa-aef2-4317-98ff-3e9cbfc46368.png">
<img width="1066" alt="Screen Shot 2022-09-11 at 20 42 11" src="https://user-images.githubusercontent.com/74932975/189543899-786b66c5-794d-4a40-b9ea-d13bdbecce9c.png">
<img width="1160" alt="Screen Shot 2022-09-11 at 20 42 06" src="https://user-images.githubusercontent.com/74932975/189543900-99e9f20b-3036-4d8c-8b98-5c7b42f8a190.png">

**Comment by prozessor13** [comment]
I think this is a duplicate: https://github.com/maplibre/maplibre-gl-js/issues/1540

**Comment by birkskyum** [comment]
I look at it, and I couldn't tell. The problem here isn't that it is re-evaluated, which seems to be the problem in the other issue, but rather that it's calculated wrong.

**Comment by prozessor13** [comment]
i think it is the same problem. The missing stencil when rendering raster or hillshading tiles.

**Comment by birkskyum** [comment]
Alright, then let's keep it in #1540 .
