### ISSUE TITLE
Push tiles to server

### ISSUE THREAD

**Issue by D4no0** [maplibre/maplibre-gl-js#164]
Currently maplibre implements the sources standard and works based on a **pull** system. This however introduces a lot of problems, especially when you want to visualize data in realtime, or to throttle the number of requests. Is there a possible way to **push** mvt tiles to the frontend manually?

**Comment by definiteIymaybe** [comment]
`maplibre-gl-js` is a rendering library, designed to work on the client side. Your question relates to the server side of things.

As for pull vs. push: pulling from the client makes more sense to me: it it the client that knows which tiles are needed to render the current map view, what tiles it has in cache and so on. You can try and implement some "push"-solution using, say, websockets, but I feel that:
- you will anyway need to tell the server which tiles are needed for the current view (which is effectively what you do now by what you call "pulling") – and do it for every client.
- the problem that you are trying to solve is outside of the `maplibre-gl-js`.

It feels like what you are trying to achieve is solvable just by cache headers. And if you have tiles re-rendered in real-time (which also raises questions) and want to implement preemptive downloads on the client – why don't you just calculate the deltas and re-request them on the client?

**Comment by D4no0** [comment]
I didn't manage to solve the problem with the cache, the solutions provided [here](https://github.com/mapbox/mapbox-gl-js/issues/2633) doesn't seem to work, the solution with deletion of cache that introduces flicker is not good enough. The second solution provided at the end of the issue just infinetly requests new tiles.

**Comment by definiteIymaybe** [comment]
I believe that if you share some example, illustrate your problem and describe what you are trying to achieve, you will get some help. In [Discussions](https://github.com/maplibre/maplibre-gl-js/discussions) here or elsewhere. I just don't see how this is an issue with the library.

**Comment by D4no0** [comment]
Having to access private methods and hack internal functionality is an **issue** with the library, if there is no official support yet for this, it is acceptable.
