### ISSUE TITLE
map.setTerrain() throws error at max zoom

### ISSUE THREAD

**Issue by 321ckatz123** [maplibre/maplibre-gl-js#1650]
**maplibre-gl-js version**: 2.4

**browser**: Chrome 105

### Steps to Trigger Behavior

 1. Zoom the map all the way out (so you see multiple world copies) using your mouse wheel with terrain on with the map height relatively small (like 200px high in the example)
 2. See console errors (you should get something like `Uncaught Error: x=-1419415165, y=-1073741824, z=-1 outside of bounds. 0<=x<0.5, 0<=y<0.5 0<=z<=25`)
 3. If you turn terrain off, the error will go away

### Link to Demonstration
https://jsbin.com/jitorijofo/edit?html,output

**Comment by HarelM** [comment]
I think terrain uses Z - 2 tiles for optimization in some points, and in this case it uses negative Z by mistake.
Feel free to submit a PR to fix this.

**Comment by sebastianoscarlopez** [comment]
Maybe the real issue is that MapLibre allows negative zoom. How about fixing this issue by putting a constraint that zoom always must be greater than 0

Please take a look at this pr #1733
