### ISSUE TITLE
Incorrect distance field of view calculation for negative elevation

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#1655]
This is in continue to the following PR which removed the elevation offset from terrain 3D: https://github.com/maplibre/maplibre-gl-js/pull/1578

The situation can be see in the following diagram:
![IMG-2568](https://user-images.githubusercontent.com/45103/190119557-5c8b47ed-48f0-4436-921b-7f0efed2f3fc.JPG)

And can be reproduced in the local environment here when running `npm run start-debug`
http://localhost:9966/test/debug-pages/terrain-satellite.html#13.45/31.54164/35.33225/49.6/54

More info in the following comment:
https://github.com/maplibre/maplibre-gl-js/pull/1578#issuecomment-1246503321

**Comment by prozessor13** [comment]
I did not analyzed in detail, but for documentation here is an example where the far-clipping plane is not correct:

http://localhost:9966/test/debug-pages/terrain-satellite.html#10.23/43.0154/9.1969/-97

**Comment by HarelM** [comment]
There's also this strange artifact around there, not sure it is related to this issue but might be a problem with the DEM:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/3269297/193256875-be64863a-bee6-4302-850f-c3cf212cc24a.png">
http://localhost:9966/test/debug-pages/terrain-satellite.html#11.53/42.7216/9.247/173.4/73

**Comment by prozessor13** [comment]
I think the spikes are a data-problem.

And i think the far-clipping-plane error is because the dem-tiles have the bathymetry included (e.g. contains negative-coordinates, like the dea-sea).

**Comment by HarelM** [comment]
Assigning bounty M.
Link to parent Bounty: https://github.com/maplibre/maplibre/issues/189

**Comment by typebrook** [comment]
> I did not analyzed in detail, but for documentation here is an example where the far-clipping plane is not correct:
> 
> http://localhost:9966/test/debug-pages/terrain-satellite.html#10.23/43.0154/9.1969/-97

Attach image for this case:
![Screenshot_2023-05-26-10-29-25_1920x1080](https://github.com/maplibre/maplibre-gl-js/assets/19887090/927de63b-2b43-4ea6-aeeb-d5602707fae4)

**Comment by HarelM** [comment]
I think I manages to think about a solution while looking at the code.
There's a method of calculating the minimum DEM for a tile.
If we store that along side the elevation in the terrain object we can use that when calculating the FOV.
I'm not sure the code is correct, but it seems to behaving nicely in general.
I'll open a draft PR later today so that other can see the horrible code I wrote :-)
cc: @maxammann.

**Comment by HarelM** [comment]
I've opened a PR for feedback: #2858
cc: @acalcutt, can you check if this fixes the issue you've seen with the bathymetry stuff?

**Comment by birkskyum** [comment]
Where is the reproduction found now? The link suggested http://localhost:9966/test/debug-pages/terrain-satellite.html#13.45/31.54164/35.33225/49.6/54 doesn't appear to be working anymore

**Comment by HarelM** [comment]
I've took the page from an old version of the repo, added it, fixed the bug and removed the page as I'm not sure we are allowed to use that data in the examples.
You can take a look at the commits in my PR.

**Comment by maxammann** [comment]
If this is not urgent, then I can review the changes. Though right now there is not much time I can invest.

**Comment by HarelM** [comment]
I was looking for your input since you said you were looking in this code.
I generally would like to push this bug fix through...

**Comment by acalcutt** [comment]
I will also try to take a look at this soon. I just got back from a week of vacation.

**Comment by HarelM** [comment]
Removed bounty as this is mostly solved by the linked PR.
Any chance for a review on it? Would be great to have it merged and released...
