### ISSUE TITLE
Wrong elevation math when lowest point is beside the center.

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#1656]
As mentioned here by @prozessor13 :  https://github.com/maplibre/maplibre-gl-js/pull/1578#issuecomment-1246503321

The elevation calculated in transform.ts is not in all cases correct. 
See: http://localhost:9966/test/debug-pages/terrain-satellite.html#13.45/31.54164/35.33225/49.6/54
There are white areas of the dead sea.

The code works when the center is in the dead sea (-450m), but not when the dead sea is beside the center. The part on the sketch below seems to be still missing. To calculate the red part, you must either know the minimum elevation in the current scene or use a constant for this, e.g., 450m.

![image](https://user-images.githubusercontent.com/74932975/190855058-2b6b58cd-5ce2-4c91-a242-63208a837a0b.png)

**Comment by HarelM** [comment]
@birkskyum this is the same as #1655.
I asked to open and then opened one anyway. My bad.
Please choose which to close :-)
