### ISSUE TITLE
A way to query elevation at a point

### ISSUE THREAD

**Issue by freedmand** [maplibre/maplibre-gl-js#1677]
## Motivation

I am experimenting with an application to identify steep hills in the map area. I can already use [`map.queryRenderedFeatures`](https://maplibre.org/maplibre-gl-js-docs/api/map/#map#queryrenderedfeatures) to identify roads, but for the next step I'd like to identify elevation at points along roads. For this, an API that allows calculating the elevation at lat/lon points would be very useful.

## Design Alternatives

* The developer can refetch elevation tiles directly and re-run calculations, but this would be wasteful
* It may be possible to fetch the terrain that's being rendered and use `transform.getElevation` and pass the terrain in (I wasn't able to find out how to do this, but guidance would be appreciated if it's feasible)

## Design

Something like this would be the easiest for the end user:

* `map.getElevationAtPoint(point)`

As for implementation, I am not familiar enough with the code yet to understand the easiest path forward, but from what I can tell all these calculations are happening at various points already. The level of effort may be low for someone familiar with the code.

### Mock-Up

`map.getElevationAtPoint(point)`

### Concepts

This could be added to the documentation as an instance method on `map`.

### Implementation

From what I can gather, we may be able to utilize the existing `transform.getElevation` function and pass the terrain in. These methods and properties exist at some point, but how they fit together would be the scope of this issue.

**Comment by birkskyum** [comment]
We quite recently moved the terrain object to sit on the map:  https://github.com/maplibre/maplibre-gl-js/pull/1628

So by passing map.terrain and a coordinate to getElevation, I believe you can get the elevation points.

When you have had time to try it, please let me know if that solved your issue.

**Comment by freedmand** [comment]
This works! Thank you for the quick response! I had to build the main branch locally and link it to incorporate the changes. I will close this issue, but curious: is there another main release planned soon, or a dist build off the latest main changes?

**Comment by birkskyum** [comment]
The next release will be a major (so 3.0.0), and it's not quite ready. We could potentially make a prerelease earlier ( #1679 ), but otherwise, you might in 2.4.0 be able to find the terrain as map.style.terrain.

**Comment by birkskyum** [comment]
There is a 3.0.0-pre.0 out now
