### ISSUE TITLE
Documentation error for map.getCenter

### ISSUE THREAD

**Issue by curran** [maplibre/maplibre-gl-js#169]
In https://maplibre.org/maplibre-gl-js-docs/api/map/#map#getcenter, the sample code reads:

```js
var {longitude, latitude} = map.getCenter();
```

However, this code does not work (for MapLibre version 1.14.0). The following does work:

```js
const { lng, lat } = map.getCenter(); 
```

I propose to update the sample code to the version that works.

Thanks!

**Comment by curran** [comment]
Oops! Wrong repo. Closing in favor of https://github.com/maplibre/maplibre-gl-js-docs/issues/52

**Comment by wipfli** [comment]
No actually this is the right repo :)

**Comment by wipfli** [comment]
API docstrings are part of `maplibre-gl-js`, i.e. the public API is documented in the source code:

https://github.com/maplibre/maplibre-gl-js/blob/b7d376a6ae7e97e0ca2a3c8d4627b87b35b5fb62/src/ui/camera.js#L153-L156

**Comment by wipfli** [comment]
@curran please open a pull request if you would like to update this.

**Comment by wipfli** [comment]
The workflow to update the docs in this case is:

* make pull request with new docstring
* merge change into main
* publish new release on NPM
* update maplibre-gl-js-docs to use new release on NPM
* republish maplibre-gl-js-docs

**Comment by curran** [comment]
Thank you for point the way to where the sample code is defined.

Submitted a PR: https://github.com/maplibre/maplibre-gl-js/pull/170
