### ISSUE TITLE
Regression introduced in 2.2.0-pre.1 (Cancel pending GeoJSON requests when GeoJSONSource.setData() is called)

### ISSUE THREAD

**Issue by robinsummerhill** [maplibre/maplibre-gl-js#1693]
The pull request https://github.com/maplibre/maplibre-gl-js/pull/1102 introduced a regression in v2.2.0-pre.1 and is present up to the latest version (2.4.0). 

The pull request introduced a change to cancel a running request when GeoJSONSource.setData is called. This appears to abort the previous request (sourcedataabort event is emitted) but does not trigger the new request and leaves the source in a 'stuck' state with isSourceLoaded=false and no features on map.

**maplibre-gl-js version**:
2.2.0-pre.1-2.4.0
**browser**:
Chrome
### Steps to Trigger Behavior

See linked Stackblitz below for a minimal demonstration of the regression. A map is created and a new geoJSON source/layer is added. Calling `source.setData` after a delay works as expected (circles appear on map). However, reducing the delay to the point where the initial geoJSON data is still loading causes the source to enter a stuck state. A `sourcedataabort` event is emitted followed by a `sourcedata` event with `isSourceLoaded=false`. The second request for data is not started and no features appear on map.

Modifying the Stackblitz demo to use maplibre-gl@2.1.9 shows the expected behaviour.

### Link to Demonstration
https://stackblitz.com/edit/js-zzktcr?devToolsHeight=33&file=index.js

### Expected Behavior
Calling GeoJSONSource.setData() should work in all cases, whether source is currently loading or not.

### Actual Behavior
Calling GeoJSONSource.setData() when a previous request is running breaks the source.

**Comment by HarelM** [comment]
Thanks for taking the time to report this!
@vanilla-lake let me know if this is something you can take care of.
@robinsummerhill if there's a possibility for you to create a test in the unit test for geojson source to reproduce this is would be amazing.

**Comment by vanilla-lake** [comment]
@HarelM Sure, I can look into that.

**Comment by vanilla-lake** [comment]
Just an update: I think I found the cause of the issue. I should be able to create a PR including both the fix and a unit test tomorrow.

**Comment by HarelM** [comment]
Thanks for the update @vanilla-lake! Truly appreciated!

**Comment by vanilla-lake** [comment]
No worries @HarelM! 🙂
