### ISSUE TITLE
Layout benchmark broken (again)

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#1709]
Very similar to previous two issues reported:
https://github.com/maplibre/maplibre-gl-js/pull/1293
https://github.com/maplibre/maplibre-gl-js/issues/1254

1. npm run ci
2. npm run start-bench
3. open web browser at http://localhost:9966/bench/versions?#Layout
4. console will show 

<code>
benchmarks_generated.js:33 Uncaught TypeError: this.map.setTerrain is not a function
    at Jt._load (benchmarks_generated.js:33:102708)
    at benchmarks_generated.js:33:101895
</code>

The said script is https://maplibre.org/maplibre-gl-js/benchmarks/main/benchmarks_generated.js
NOT coming from my local box.

**Comment by HarelM** [comment]
Seems like this is related to a recent change with 3D terrain and the fact that the bench is using a map stub and that it needs to run manually. See #982 for more info.
I'll see if I can create a PR that fixes this... :-(

**Comment by HarelM** [comment]
Feel free to review my PR :-)

**Comment by HarelM** [comment]
@zhangyiatmicrosoft it would be great if you could make sure this is now fixed after the following actions is completed:
https://github.com/maplibre/maplibre-gl-js/actions/runs/3199696952
Thanks!!

**Comment by zhangyiatmicrosoft** [comment]
Confirm that this is working now. Thanks again for the quick fix!

**Comment by HarelM** [comment]
No problem. Thanks for reporting this!!
