### ISSUE TITLE
Geoprtail vector tiles shown at the bad lattitude

### ISSUE THREAD

**Issue by SuperPat45** [maplibre/maplibre-gl-js#171]
**maplibre-gl-js version**: latest

**browser**: Firefox, Chrome

### Steps to Trigger Behavior

I try to integrate geoportail vetor tiles with maplibrejs, but tiles are not shown correctly:
Here is the style in question:  https://wxs.ign.fr/choisirgeoportail/static/vectorTiles/styles/PLAN.IGN/epure.json

### Link to Demonstration

Try to zoom and dezoom in this example:
https://jsfiddle.net/w7m82q3h/

### Expected Behavior

I think Maplibre should handle it correctly like OpenLayers does.

### Actual Behavior

At minimal zoom it is ok
At zoom3, It seems that the northern and southern hemispheres tiles are reversed, Antarctica is shown where Europa is.

**Comment by spourquier** [comment]
Hi
As a workaround and according to the [documentation](https://maplibre.org/maplibre-gl-js-docs/style-spec/sources/#vector-scheme), on the `scheme` property of your `source`, use the value `xyz` (or remove `scheme` property) instead of `tms` and it should work with all IGN styles.

**Comment by kylebarron** [comment]
Nothing renders for me in your example, but most likely you need to change
```
"scheme": "tms"
```
to
```
"scheme": "xyz"
```
in your style

**Comment by SuperPat45** [comment]
Ok, thanks
