### ISSUE TITLE
MapLibre GL JS v3

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#1716]
MapLibre GL JS v3 is coming. This is a tracking issue for things around v3...

**Comment by wipfli** [comment]
Are we going to maintain v2 once v3 is out? Like dependabot updates and security patches?

**Comment by HarelM** [comment]
> Are we going to maintain v2 once v3 is out? Like dependabot updates and security patches?

I don't see a good reason to do that.

**Comment by acalcutt** [comment]
I tested [v3.0.0-pre.1](https://github.com/maplibre/maplibre-gl-js/releases/tag/v3.0.0-pre.1) a bit yesterday and performance seemed good. didn't experience any crashed, where before I'd see one once and a while.

**Comment by wipfli** [comment]
We might want to check if plugins still work.

**Comment by HarelM** [comment]
Css changes might have caused them to break, but if this is the only problem one can use a css file of an older version I guess...

**Comment by neodescis** [comment]
Is there a list of breaking changes expected to ship in 3.0 yet?

**Comment by HarelM** [comment]
Just the current changelog breaking change entiries. But there might be others as we proceed.

**Comment by wipfli** [comment]
I think at the January monthly meeting we discussed that v3 should be released roughly in 2 months. @HarelM do you think we can release MapLibre GL JS v3.0.0 by the time of the next monthly meeting?

**Comment by HarelM** [comment]
Hard to tell, there are still a few open items I would like to see if I can get into the version.

**Comment by wipfli** [comment]
I think it would be good to take what we have now and make a release. We can have another major release in 6 to 12 months. What do you think, @HarelM ?

Also, is the splitting out of the style spec repo blocking a release of MapLibre GL JS at the moment?

**Comment by HarelM** [comment]
I thought about it too recently, I generally agree we should create a release, I was hoping we could add sky and another open PR.
Style spec is not blocking.
I'll see if I can push the last things forward and carve out a release.

**Comment by wipfli** [comment]
Thank you!

**Comment by wipfli** [comment]
I know I should not worry too much about things like last activity, but 7 months on NPM just looks a bit bad...

![image](https://user-images.githubusercontent.com/53421382/227544116-f74a5415-09df-4632-abea-83eab7e0b9ed.png)

**Comment by birkskyum** [comment]
@wipfli , at least npm it looks worse than it is, and not the opposite. A further inspection will also show a full year of linear growth in usage; that the vast majority are on the latest stable version; and that the last release was just 2 months ago.

**Comment by birkskyum** [comment]
Closed by #2579
