### ISSUE TITLE
Remove "mapbox://" from tests and debug pages

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#1731]
What's the plan to support URLs start with "mapbox://"

There are about two dozens of these, mostly in tests which do not work currently, for example:
src\style-spec\migrate\v8.test.ts
test\debug-pages\featurestate.html
test\debug-pages\multiple.html
...

Are these assets owned by Mapbox? If we cannot use them anymore, can we make new ones for OSS community?

**Comment by HarelM** [comment]
In this repo we should remove them and replace with regular ones.
There is a plugin for anyone that would like to use it in production that is not part of this repo.

**Comment by zhangyiatmicrosoft** [comment]
I can make these changes. Just need to know where to download those assets? For example: 'mapbox://mapbox.satellite'
Does the oss community have copyright to use them?

**Comment by wipfli** [comment]
We can use tiles donated by MapTiler for such use-cases. See examples in the docs website, for example this one: https://maplibre.org/maplibre-gl-js-docs/example/satellite-map/

**Comment by wipfli** [comment]
Also, if we just need some map, we can use the demo tiles style which are hosted in the MapLibre GitHub repo. See https://maplibre.org/maplibre-gl-js-docs/example/simple-map/

**Comment by wipfli** [comment]
I used the demotiles style for the shield rotation debug page... https://github.com/maplibre/maplibre-gl-js/blob/main/test/debug-pages/shield-rotation.html

**Comment by acalcutt** [comment]
I also added some more detailed vector tiles to the demotiles site recently that I hoped could be useful in some tests.

examples,
https://demotiles.maplibre.org/tiles-omt/
https://demotiles.maplibre.org/terrain-tiles/

these use osm-bright based styles here
https://demotiles.maplibre.org/styles/osm-bright-gl-style/style.json (without terrain)
https://demotiles.maplibre.org/styles/osm-bright-gl-terrain/style.json (with terrain)

they only cover a small region though, in the N047E011 area...so they may only work for specific use cases.

**Comment by tmcw** [comment]
I get why this project won't use mapbox tiles for demos, but is there a strong reason why the `mapbox://` URL scheme is not supported? It'd certainly make it easier for existing GL users to convert.

**Comment by wipfli** [comment]
@tcmw see #290

**Comment by wipfli** [comment]
And #1226

**Comment by freeExec** [comment]
And what if you implement the registration of your own protocols. It wouldn't be bad when developing a style. In a development environment, it would point to the address of the test machine. And production to your address. And the style looked the same.

**Comment by wipfli** [comment]
Good idea, @freeExec. If you make an example or a plugin, feel free to share it in the Slack channel and at http://github.com/maplibre/awesome-maplibre...

**Comment by acalcutt** [comment]
From #1226, this https://www.npmjs.com/package/maplibregl-mapbox-request-transformer seems interesting, would that allow support of the mapbox urls?

https://github.com/maplibre/maplibre-gl-js/discussions/1226#discussioncomment-3837966

**Comment by HarelM** [comment]
Can this issue be closed? I think the plugin add the relevant support, and if not, it can always be imporved.

**Comment by HarelM** [comment]
Sorry, my bad, this is about replacing pages and docs that has those. I'll change the title of this issue.

**Comment by zhangyiatmicrosoft** [comment]
I think all debug pages are deleted now
