### ISSUE TITLE
Typescript issue: setTerrain() options should not be mandatory

### ISSUE THREAD

**Issue by Jonibigoud** [maplibre/maplibre-gl-js#1781]
**maplibre-gl-js version**: 2.4

### Steps to Trigger Behavior

 setTerrain() without any options parameter

### Expected Behavior

No typescript error because options are not mandatory:

![Sans titre](https://user-images.githubusercontent.com/9034321/198251584-be406b72-22bb-4cd1-93cc-212967105f1c.png)

### Actual Behavior

Typescript error: "1 argument required but only 0 present"

### Resolution

maybe add a "?" to line 10149 of file "maplibre-gl.d.ts"  👍 

	setTerrain(options?: TerrainSpecification): Map;

**Comment by HarelM** [comment]
You should pass null. It's more declarative this way...
