### ISSUE TITLE
TypeScript declaration file for GeoJSON types is missing

### ISSUE THREAD

**Issue by mactrem** [maplibre/maplibre-gl-js#180]
Moving the TypeScript declaration file from the DefinitelyTyped into the MapLibre repo (#130) causes a missing reference to the GeoJSON typings, so the GeoJSON types has to be installed separately when working with GeoJSON sources in a Typescript project
![image](https://user-images.githubusercontent.com/75912142/123242227-1a11be80-d4e2-11eb-80c3-eecd5d5537e2.png)
 
The GeoJSON types are referenced via a seperate declaration file and had been referenced via devDependencies when deployed via DefinitelyTyped
https://github.com/maplibre/maplibre-gl-js/blob/85d4700306cb41ce4e69910b65247d9f4ac2e5d3/src/index.d.ts#L16

There are different solutions possible, but i would suggest to add  the GeoJSON typings as a dev dependency to the project.

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue.
I've seen this too, I think, when I migrated ngx-maplibre-gl here.
Can be seen here:
https://github.com/maplibre/ngx-maplibre-gl/blob/260c005f6b52fe64bab6fdc835c3fe929e549b73/package.json#L54
Feel free to submit a PR with the solution you think will help as many platforms as possible and I'll review it.
