### ISSUE TITLE
Improve handling of vector tile 5xx responses

### ISSUE THREAD

**Issue by mfedderly** [maplibre/maplibre-gl-js#1811]
## Motivation

Currently if a request for a vector tile returns a 5xx status code, it will stop trying to reload that tile until the map is interacted with. The user-facing effect is that transient server issues can cause data to disappear from the map and not return until the map has been zoomed in/out or panned. This is especially noticeable on maps where the vector data updates periodically.

Similar to #1579

### Implementation

One possible implementation is to rework SourceCache._tileLoaded to look for 5xx status codes and call `tile.setExpiryData` and `this._setTileReloadTimer` to try again later. It is potentially tricky to pick a good delay here, one option is to just make it a map option.

## Commentary

Has anyone else hit this same problem? Is there a better fix than the implementation proposed above? I'm happy to provide the PR once we settle on an approach.

**Comment by HarelM** [comment]
What if the server is actually down? Trying to retry may cause the server, once up again to fail due to too many requests. Also there's no guaranty that it's a glitch, so continuing to retry might be in vain...
I'm not sure I have a good solution for this though... :-/

**Comment by mfedderly** [comment]
Yeah I was hoping to get a better answer. I think sometimes people do exponential backoff when they run into issues, that seems tricky to implement though.

**Comment by HarelM** [comment]
I think the current solution and design is fine. Closing, feel free to open a different issue with a design proposal to push this forward.
