### ISSUE TITLE
Unify npm packages under the same prefix including this one

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#184]
### Question

Do we want to change the npm package name of this library to be with a prefix of `@maplibre`?
If so, do we want to call it `@maplibre/maplibre-gl` or maybe something like:
`@maplibre/main` or `@maplibre/core`.

The motivation behind adding a prefix to this library as well is that every contributor that creates a package under this org will not need to think twice if to add this prefix or not...

The discussion started on this thread (for reference):
https://github.com/maplibre/maplibre-gl-leaflet/pull/12#issuecomment-867882208

**Comment by wipfli** [comment]
Even though I am in favor of your suggestion, I think it is maybe a bit too much to ask everyone to change their import again.

Users coming from mapbox had to change `import mapboxgl from 'mapbox-gl'` to `import maplibregl from 'maplibre-gl'`, which they would have to change now a second time I guess.

**Comment by HarelM** [comment]
True, but the later we postpone it (if we decide to change the name) the more users will have to change it twice. Currently it seems that this package is not being used widely, according to the npm statistics so the sooner we do it the better.
Let's be honest, it's mostly search and replace...

**Comment by wipfli** [comment]
That's true. Everyone sits on mapbox `v1.13` or earlier...

**Comment by astridx** [comment]
Pro: In my eyes, we could ask Maplibre users to make such a change. It would have to be documented and then there is also the deprecated message. It's not that an application breaks. Users just have to change something when they update. I see that correctly, right?
Contra: However, the change also causes additional work in this project. Someone would have to work on that here. 

**If we were to vote,** I would vote to leave the main repo as it is and give all the dependent ones the prefix. That way we don't have any additional work and there is a clear rule for the dependent projects.

**Comment by wipfli** [comment]
Regarding plugins, we have now https://www.npmjs.com/package/@maplibre/maplibre-gl-leaflet available online. 

Is everyone happy with the convention `@maplibre/<plugin-name>`? If yes, I suggest publishing `@maplibre/maplibre-gl-compare`.

**Comment by HarelM** [comment]
I prefer to avoid the duplication of the word maplibre...

**Comment by astridx** [comment]
I am happy with `@maplibre/maplibre-gl-compare`.

@HarelM is right. It is not optimal that the word `maplibre `occurs twice. I briefly considered renaming the plugin `Compare`. Then I dropped the idea. Not everyone uses `Node`. Some use the JavaScript file in the `dist `folder. Then the name in combination with `Maplibre` is much better. You can already tell from the name what is in the plugin. With the `node package`,  I like the prefix, because this way everything that belongs to `Maplibre `is stored together in the` node_modules` folder.

**Comment by HarelM** [comment]
The file name in the dist folder can stay the same, be maplibre-gl-compare.js in this case, but package name can, and should be in my opinion, be with the @ maplibre prefix, but without repeating maplibre afterwards.
I.e. @ maplibre/compare or @ maplibre/compare-gl or @ maplibre/gl-compare, they all work for me...
My opinion only, of course...

**Comment by wipfli** [comment]
I like the format `@maplibre/maplibre-gl-compare` because it looks like what mapbox and their open-source contributors did.

**Comment by HarelM** [comment]
I think that mapbox naming isn't great. I like `@angular/...`'s a lot better...

**Comment by HarelM** [comment]
Steering committee meeting decision was to keep current naming.
Closing.
