### ISSUE TITLE
Typescript error: Cannot find name 'RequestTransformFunction' 

### ISSUE THREAD

**Issue by aprilmay** [maplibre/maplibre-gl-js#186]
After switching an Angular project to maplibre-gl and ngx-maplibre-gl, the build process fails with this error:

`Error: node_modules/maplibre-gl/src/index.d.ts:338:47 - error TS2304: Cannot find name 'RequestTransformFunction'.`

Defining the missing definition in index.d.ts, like below, seems to fix the issue (i'm not a typescript guru):

`export type TransformRequestFunction = (url: string, resourceType: ResourceType) => RequestParameters;`

Thanks to all contributors for this project!

**Comment by wipfli** [comment]
Thanks for sharing this. Would you like to make a pull request with this? I am sure @HarelM is happy to review it.

**Comment by HarelM** [comment]
You're probably right.
I'm not getting this error, but it might be related to the fact that I don't use this method in my code.
This was introduced by @thaddmt.
@thaddmt care to fix this?
Also a PR can do the job as well...

**Comment by thaddmt** [comment]
Ah my bad had no idea, I believe that function is already defined here - https://github.com/maplibre/maplibre-gl-js/blob/main/src/index.d.ts#L800 so it should be a matter of changing type to reference that one. I can make the change

**Comment by HarelM** [comment]
@thaddmt go ahead. :-) Thanks for the quick response!

**Comment by aprilmay** [comment]
@thaddmt : thanks for the fix :-)
