### ISSUE TITLE
The optional endIndex of the slice expression is missing in types.

### ISSUE THREAD

**Issue by leonekmi** [maplibre/maplibre-gl-js#1886]
**maplibre-gl-js version**: 2.4.0

### Steps to Trigger Behavior

 1. Use the [`slice`](https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#slice) expression anywhere.
 2. Add an end index somewhere.
 3. TypeScript does not accept it.

### Expected Behavior

The optional second index of the [`slice`](https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#slice) expression should be accepted. It actually works.

### Actual Behavior

While it does work, TypeScript rejects it as the second optional `index` is not included in the types. A workaround is to use `@ts-ignore`

**Comment by HarelM** [comment]
There are some issues with the definitions.
Your best approach would be to create a PR to solve this and a test to verify this won't break.
You can take a look at some previous PRs that aim to fix similar problems.
