### ISSUE TITLE
Error when using interpolate with expression as values

### ISSUE THREAD

**Issue by tengl** [maplibre/maplibre-gl-js#1888]
**maplibre-gl-js version**: 2.4.0

**browser**:  any

### Steps to Trigger Behavior

 1. See demonstration link.
 2. The layer with the expression depends on a property in the GeoJson data.
 3. There is an warning saying that "Type 'string' is not assignable to type 'number'.ts(2322)".
 4. The `ExpressionSpecification` of type `"interpolate"` it should allow expressions as interpolation values, like this:
 ```
[
	"interpolate",
	InterpolationSpecification,
	number | ExpressionSpecification,
	...(number | number[] | ColorSpecification | ExpressionSpecification)[]
]
```
 6. The code works though (there should be a red line between Stockholm and Åland).

### Link to Demonstration

https://codesandbox.io/s/maplibre-gl-typeings-bug-620nzp?file=/src/index.ts

### Expected Behavior
No warnings.

### Actual Behavior
Got warnings.

**Comment by HarelM** [comment]
Any help with the typings of the expressions would be greatly appreciated.
The current situation is far from perfect...

**Comment by tengl** [comment]
I can do a PR for regular "interpolate". I don't know about the others (hcl, lab) though, and don't have time to test.

**Comment by tengl** [comment]
I added a test, but it doesn't fail. The error is only in the editor. I guess it would have failed compile if it was in strict mode, but it is set to `false` in `tsconfig.json`. 

```typescript
compileTimeCheck(['interpolate', ['linear'], ['get', 'point_count'], 2, ['/', 2, ['get', 'point_count']], 10, ['*', 4, ['get', 'point_count']]]);
```

Is it enough with the editor check?

**Comment by tengl** [comment]
I added a PR.
