### ISSUE TITLE
"Circular dependencies" warning on build

### ISSUE THREAD

**Issue by rotu** [maplibre/maplibre-gl-js#1896]
**maplibre-gl-js version**: 3.0.0-pre.1

**browser**: N/A

### Steps to Trigger Behavior

 1. `npm run build-dev`

### Link to Demonstration

https://github.com/maplibre/maplibre-gl-js/actions/runs/3590257945/jobs/6043468440#step:5:11

### Expected Behavior

The build succeeds with no warnings

### Actual Behavior

There are warnings in the Rollup build log about circular dependencies. I am unsure if these are benign or not:

> (!) Circular dependencies
> src/style-spec/expression/parsing_context.ts -> src/style-spec/expression/compound_expression.ts -> src/style-spec/expression/parsing_context.ts
> src/style-spec/validate/validate.ts -> src/style-spec/validate/validate_function.ts -> src/style-spec/validate/validate.ts
> src/style-spec/validate/validate.ts -> src/style-spec/validate/validate_function.ts -> src/style-spec/validate/validate_object.ts -> src/style-spec/validate/validate.ts
> ...and 11 more

**Comment by HarelM** [comment]
Yup... good luck fixing those... :-/

**Comment by VehpuS** [comment]
@rotu Do you need help looking into these?

**Comment by rotu** [comment]
@VehpuS I appreciate the offer! No, I don't plan on digging deeper on this right now.

**Comment by zhangyiatmicrosoft** [comment]
#2154

**Comment by zhangyiatmicrosoft** [comment]
#2156

**Comment by zhangyiatmicrosoft** [comment]
#2163

**Comment by zhangyiatmicrosoft** [comment]
#2169

**Comment by zhangyiatmicrosoft** [comment]
#2188
