### ISSUE TITLE
2.1.9. -> 2.4.0 Expression types break interpolated text-offset

### ISSUE THREAD

**Issue by micaminoff** [maplibre/maplibre-gl-js#1899]
**maplibre-gl-js version**: 2.4.0

### Steps to Trigger Behavior

```TS
map((fontSize): LayerSpecification['layout'] => ({
                'text-field': ['get', 'name'],
                'text-size': fontSize || 16,
                'symbol-placement': 'point',
                'text-allow-overlap': true,
                'text-offset': [
                    'interpolate',
                    ['linear'],
                    ['zoom'],
                    16,
                    ['literal', [0, 1]],
                    17,
                    ['literal', [0, 2]],
                    18,
                    ['literal', [0, 3]],
                    19,
                    ['literal', [0, 4]],
                ],
            }))
```

 1. Write the above code (or similar) with maplibre-gl 2.1.9 in package, TS allows compilation
 2. Upgrade maplibre to 2.4.0.
 3. TS no longer allows compilation
 
TS complains that `Type '"interpolate"' is not assignable to type '"rgba"'.ts(2322)` with the above snippet. Reading the mapbox-gl spec the above structure seems to be in line with the spec.

In maplibre-gl.d.ts the path to the problem is `SymbolLayerSpecification.layout.text-offset` where the DataDrivenPropertyValueSpecification is an ExpressionSpecification. Looking at the typings, I assume the error is due to the third argument in the text-offset property since ['zoom'] is not a number and TS tries to fit it to rgba instead of text-offset. However, the [docs](https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/#interpolate) refer to numeric expressions as an accepted input "The input may be any numeric expression (e.g., ["get", "population"])"

I assume this has to do with PR #1510 #1509

**Comment by HarelM** [comment]
Yes, these PR introduced some problems.
The best approach is to see if this exists in the latest code (as there were some fixes in that area) and if not, create a PR to solve this.

**Comment by kevinschaul** [comment]
Hi all, apologies for the PR that did not actually test the issue. I am struggling to invent a test that checks whether typescript allows compilation. But I am near certain that this issue no longer exists with the current code.

When running version 2.4.0, @micaminoff 's example code outputs the following typescript warning:
```
$ npm run build-dev       

> maplibre-gl@2.4.0 build-dev
> rollup --configPlugin @rollup/plugin-typescript -c --environment BUILD:dev

loaded rollup.config.ts with warnings
(!) Plugin typescript: @rollup/plugin-typescript TS2322: Type '"interpolate"' is not assignable to type '"rgba"'.
src/symbol/placement.ts: (666:25)

666                         'interpolate',
                            ~~~~~~~~~~~~~

...
```

But when running 0c3c8a16c3cf430d98cb2c94e446003eb3117689, the same code does not output the warning:

```
$ npm run build-dev

> maplibre-gl@3.0.0-pre.2 build-dev
> rollup --configPlugin @rollup/plugin-typescript -c --environment BUILD:dev --bundleConfigAsCjs


src/index.ts, src/source/worker.ts → rollup/build/maplibregl...

...
```

**Comment by HarelM** [comment]
You just need to add the expression here and check if the typecheck passes:
https://github.com/maplibre/maplibre-gl-js/blob/66e1009d30c24f83b280faad53dac3aed7cc5b8b/src/style-spec/feature_filter/feature_filter.test.ts#L16
I would advise to add a test, even if it passes...
