### ISSUE TITLE
Documentation [Tracking Issue]

### ISSUE THREAD

**Issue by lseelenbinder** [maplibre/maplibre-gl-js#19]
This is designed to track the state of the documentation for the fork.

- [ ] https://github.com/maplibre/maplibre-gl-js-docs/issues/1
- [ ] Deploy to <somewhere> (maplibre.github.io/docs ?)

**Comment by markgis** [comment]
Is the plan to take docs from Mapbox website piecemeal and update all references to maplibre?

Or would it be better to re write them from scratch and bring in certain sections just using the mapbox docs as a guide? Happy to help with that project, if I can.

**Comment by lseelenbinder** [comment]
The docs are BSD, so there's no issue reusing them, as long as we remove references to Mapbox, as we are doing in the codebase.

**Comment by nyurik** [comment]
I would propose we create a new repo and push the content of the original one up to 1.13, **instead of** using the github fork feature. This way it is not tagged as a fork in github, and not linked back. This is an irony of wording -- github "fork" is different than project "fork".  The first is about closely related stuff that could (hopefully) rejoin. Here projects are divorcing for good without the intention of re-merging (unless upstream changes their licensing terms again?).

Unless anyone objects, I will do this shortly.

**Comment by lseelenbinder** [comment]
Fine by me @nyurik. I thought we could ask GitHub to remove the link, though?

**Comment by nyurik** [comment]
we could, but easier to do it right from the start, without the extra hassle :)

**Comment by nyurik** [comment]
Oh, I just saw that that repo has already been forked, so yeah, might as well ask github, and plus force-push to remove newer information

**Comment by wipfli** [comment]
One thing I love about mapbox is their great documentation. Can I somehow help setting up the maplibre [documentation](https://github.com/maplibre/maplibre-gl-js-docs)? I would be happy to go through the repo an start changing the names.

**Comment by wipfli** [comment]
The examples in the documentation rely on a data source to get the raster and vector tiles. Is the consensus that these will be supplied by MapTiler? Like for example the [```simple-map.html```](https://github.com/maplibre/maplibre-gl-js-docs/blob/main/docs/pages/example/simple-map.html) could then look like this:

```html
<div id="map"></div>
<script>
    var map = new maplibregl.Map({
        container: 'map', // container id
        style: 'https://api.maptiler.com/maps/streets/style.json?key=olPbAXB9QkZuFSDG4x2V', // style URL
        center: [-74.5, 40], // starting position [lng, lat]
        zoom: 9 // starting zoom
    });
</script>
```

See https://github.com/maplibre/maplibre-gl-js-docs/issues/2.

**Comment by wipfli** [comment]
Actually this might be the wrong place to discuss about documentation since now there is a separate repo for this. If you see it this way @lseelenbinder please cross-reference the docs repo and close this issue here.
