### ISSUE TITLE
quertRenderedFeatures is not typed well

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#1900]
**maplibre-gl-js version**: 2 and above

**browser**: any

### Steps to Trigger Behavior

 1. using typescript type `map.queryRenderedFeatures(`
 2. Look at the auto complete
 3. `options` is defined as `any` :-(

### Expected Behavior
 I should be able to know what to pass to the function from the definitions
### Actual Behavior
I don't know.
The jsdocs are good, and the comments inside the function tells that this is a flow limitation, but I trend to think this is possible with typescript.

There might be a need to change this method if we can't type it well as it is not a great API currently... 3.x is the opportunity to do so in theory...

**Comment by guybeh** [comment]
Hello @HarelM,
I think that in the steps to trigger behavior, in the #1 step, it should be ```map.queryRenderedFeatures```

**Comment by beharguy** [comment]
Hello @HarelM,
I think in Steps to Trigger Behavior, #1 step, should be ```map.queryRenderedFeatures(```

**Comment by beharguy** [comment]
Following the code a bit I see a connection between the `options` parameter in this function and the `params` parameter in ```queryRenderedFeatures```  at ```query_features.ts```, which also receives the `availableImages: Array<string>` property.
It should also be added to the jsdocs, are they auto generated or should they be added manually?

**Comment by HarelM** [comment]
The jsdocs and the types are separated, you need to use typescript to allow auto complete etc, and jsdoc to allow more info, and there are cases where the two do not match unfortunately.
In any case, for this specific issue, there's a need to better type the method, the jsdoc provide examples that can be revered engineered to understand what should be the typing here.
Feel free to send a PR if you would like to help solve this. :-)
