### ISSUE TITLE
Projects

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#191]
Do we still want the GitHub Projects? https://github.com/maplibre/maplibre-gl-js/projects

They have not been updated in a long time. I suggest we close them.

**Comment by HarelM** [comment]
We need to decide how to better manage this library.
We can probably simply merge what's working and implemented, I don't mind managing this in a more kanban style...
I think you can close the project for now until we decide how to proceed...

**Comment by wipfli** [comment]
Closed them.
