### ISSUE TITLE
marker CSS Classes not rendering correctly in pixel 6/7 latest chrome/webview with latest maplibre-gl

### ISSUE THREAD

**Issue by cbairy** [maplibre/maplibre-gl-js#1911]
**maplibre-gl-js version**: 2.4.0

**browser**: Pixel 6/7 Latest Chrome or Latest WebView Version 107.0.5304.121

### Steps to Trigger Behavior

 1. We are plotting the center marker and location markers on canvas within div elements. div with center marker has class "marker center maplibregl-marker mapboxgl-marker maplibregl-marker-anchor-center mapboxgl-marker-anchor-center" and other markers have class "marker maplibregl-marker mapboxgl-marker maplibregl-marker-anchor-center mapboxgl-marker-anchor-center" and other markers have an icon element inside the div.
 
![image](https://user-images.githubusercontent.com/3469880/205918131-6da666b1-d220-4132-99e0-119fcd5d025a.png)

Elements
![image](https://user-images.githubusercontent.com/3469880/205918249-1c4180f7-5706-4132-b3b4-192b9e622c62.png)

 2. We see that the map is plotted with round purple marker for centre icon (first div under map container) and for the rest its a white marker with icon inside the div. This behaviour is the same across many versions of Chrome/webview.
 3. Issue happens only with Pixel 6 or Pixel 7 where all the div under map container are shown as round purple dots.
 4. This is the snippet we use to create each marker element within the container
`
dataset.markers.forEach((marker) => {
                // Each marker has geo location except the 1st in the list or center marker
                const markerCoordinates = marker.coordinates.toString();
                const markerId = marker.primaryKeyValue ? markerCoordinates : 'center';
                const markersAtCoordCount = this.markerCoordinatesMap.has(markerCoordinates) ? 
                this.markerCoordinatesMap.get(markerCoordinates).length + 1 : 1;
                const el = document.createElement('div');
                el.id = markerId;
                // css class marker center to make icons with purple background
                el.className = markerId === 'center' ? 'marker center' : 'marker';
                if (markerId !== 'center') {
                    el.role = 'text';
                    let icon;
                    if (markersAtCoordCount === 1) {
                        icon = `<i class="cxgo-redwood-icons marker-icon" aria-hidden="true">${marker.iconName}</i>`;
                    } else {
                        icon = `<i class="oj-ux-ico-new-version cxgo-redwood-icons marker-icon" aria-hidden="true"></i>`;
                    }
                    el.innerHTML += icon;
                    el.addEventListener('click', (event) => {
                        event.stopPropagation();
                        const globalBodyElem = document.getElementById(
                            'globalBody'
                        );
                        globalBodyElem.dispatchEvent(
                            new CustomEvent('mapPinSelect', {
                                detail: marker,
                                bubbles: true,
                            })
                        );
                    });
                }
                if (this.markersIdMap.has(markerId)) {
                    const existingMarker = this.markersIdMap.get(markerId);
                    existingMarker.pin.remove();
                    this.markersIdMap.delete(markerId);
                }
                // marker.coordinates is array of [lat,lng]. But, setLngLat() expects array of [lng,lat]. Hence, [marker.coordinates[1],marker.coordinates[0]]
                const pinMarker = new mapboxgl.Marker(el)
                    .setLngLat([marker.coordinates[1],marker.coordinates[0]])
                    .addTo(this.mapObject);
                this.markersIdMap.set(markerId, {
                    pin: pinMarker,
                    coordinates: marker.coordinates,
                });
                if (this.markerCoordinatesMap.has(markerCoordinates)) {
                    const arrayOfObjectsAtCoord = this.markerCoordinatesMap.get(
                        markerCoordinates
                    );
                    arrayOfObjectsAtCoord.push({
                        id: markerId,
                        pin: pinMarker,
                        objectName: marker.objectName,
                    });
               } else {
                   this.markerCoordinatesMap.set(markerCoordinates,[{
                        id: markerId,
                        pin: pinMarker,
                        objectName: marker.objectName,
                   }]);
               }
            });
`

CSS Classes:
`
.marker {
    height: 24px;
    width: 24px;
    box-sizing: border-box;
    border: 1px solid #846a92;
    border-radius: 50%;
    background-color: #ffffff;
    z-index: 1;
    filter: drop-shadow(0px 4px 3px rgba(0, 0, 0, 0.35));
}
.center {
    background-color: #846a92;
    border: 2px solid #ffffff;
    z-index: 2;
}
`

### Expected Behavior
As seen in pixel 4a and other android devices
<img width="418" alt="Other-Devices-Map" src="https://user-images.githubusercontent.com/3469880/205920308-ed086aed-04d4-4098-a33d-c25ca63774d6.png">

### Actual Behavior
Seen in Pixel 6a
<img width="331" alt="pixel6a" src="https://user-images.githubusercontent.com/3469880/205921751-5c3f0d1e-5c40-489e-8372-a74d45a9661e.png">

**Comment by HarelM** [comment]
Sounds like a bug in chrome, did you report it in their issue tracker?

**Comment by HarelM** [comment]
No response, closing, feel free to ask to re-open if this is still and issue and if you believe this to be a maplibre issue.
