### ISSUE TITLE
Ubuntu 22.04 causes browser and render tests to fail

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#1913]
Recent CI pull request are failing the render test and browser test.
Short research to why, revealed that this is due to the change in github actions that uses `ubuntu-latest` from version 20.04 to 22.04.
This version has a lot of changes, some are in the UI and probably rendering libraries (might also be related to the CJK fonts).
We still would like to make sure we support the latest version of ubuntu in the tests so there might be some configuration needed for the CI to pass the tests on latest ubuntu, or some bugs to open to ubuntu for creating breaking changes in rendering, IDK.

**maplibre-gl-js version**: from main branch

**browser**: Chrome

### Steps to Trigger Behavior
 1. Open a PR

### Link to Demonstration
#1910 for example

### Expected Behavior
CI should pass with latest ubuntu version (22.04 currently)

### Actual Behavior
CI fails

In order to facilitate development, as a current workaround I've hardcoded the ubuntu version in render and browser CI pipelines to version 20.04. This shouldn't be the long-term solution. #1912

**Comment by zhangyiatmicrosoft** [comment]
37 failed render tests on my u22 machine with intel gpu.
Dont know if other are seeing the same number. I found they vary depending on the GPU.
Is pipeline running on u22 VM?

**Comment by HarelM** [comment]
The pipeline ran on u22 for about 4 days until I noticed the failure caused by the github action VM image change.
I've reverted the CI to run on u20 so the tests are passing.
@zhangyiatmicrosoft Can you share the html or some screenshots to see the changes in the images that fail when running on u22?

**Comment by HarelM** [comment]
Never the less, this needs to pass on both u20 and u22, I just don't know what caused the tests to start failing between 20 and 22...

**Comment by HarelM** [comment]
Thanks for sharing the results!
The difference seems to be in raster accuracy and text.
Changing the TH is not an option as it would be too permissive.
Adding the pictures is a possibility, but it feels like a workaround. Any chance you can maybe investigate if there's a parameter we can use to get the previous results?

**Comment by HarelM** [comment]
Fair enough, feel free to create a PR with the needed images.

**Comment by zhangyiatmicrosoft** [comment]
#1948

**Comment by HarelM** [comment]
Thanks for taking this on @zhangyiatmicrosoft !!

**Comment by HarelM** [comment]
Closed by #1948
