### ISSUE TITLE
The control `maplibregl.FullscreenControl` doesn't work on Safari Mobile

### ISSUE THREAD

**Issue by roblabs** [maplibre/maplibre-gl-js#1919]
**maplibre-gl-js version**: `2.4.0`

**browser**: Safari mobile.  Tested on 1) ❌ iPhone Simulator, 2) ✅ iPad Simulator, 3) ❌ iPhone device

### Steps to Trigger Behavior

 1. On a iPhone mobile device, navigate to https://maplibre.org/maplibre-gl-js-docs/example/fullscreen/ and note there is no `FullScreenControl` (the four arrow control, see screen shot for how it works on iPad)
 2. If you have access to Xcode on macOS you can also use the Simulator app and run `xcrun simctl openurl booted https://maplibre.org/maplibre-gl-js-docs/example/fullscreen` to test the URL.
 3. Using Safari's *Enter Responsive Design Mode* is not appropriate here as it does not simulate a device.

### Expected Behavior

Full Screen control shows up on Safari Mobile

### Actual Behavior

No Full Screen control

---

### Link to Demonstration

![image](https://user-images.githubusercontent.com/118112/206590657-0363782f-ebe2-4980-9178-ea43724606a2.png)

**Comment by roblabs** [comment]
Further info on debugging this issue:  [Safari Development mode](https://developer.apple.com/safari/tools/) has a way to enable the Safari Web Inspector on a Simulator or device.  I was able to enable that mode and get a little more info.


Safari Web Inspector on a) an iPhone device, and b) Simulator both report this warning:

> *This device does not support fullscreen mode.*


And the signature of the warning line in the Typescript code _looks_ like this line 300

https://github.com/maplibre/maplibre-gl-js/blob/11a1262601d9842efb4f6a44fed40fcb55fc2462/src/util/util.ts#L297-L303

---

![image](https://user-images.githubusercontent.com/118112/206591731-a27f2a0f-b028-44e2-9a61-54d16ce53b78.png)

**Comment by HarelM** [comment]
Can I close this issue then? I believe this is due to lack of support from the iPhone browser for this feature...

**Comment by roblabs** [comment]
Please leave open, or label it as a _won't fix_ by MapLibre.  If it's closed or not going to be addressed, then that should be documented on our `FullscreenControl` demo page with a statement that Safari Mobile is not supported.  I don't recommend that.

I recommend leaving open and review options to fix.  As well, I recommend we add more mobile testing on real devices for other major mobile operating systems.

> @HarelM  — Can I close this issue then? I believe this is due to lack of support from the iPhone browser for this feature...

**Comment by VehpuS** [comment]
I think that a workaround is possible, assuming it is acceptable as an inclusion to the library. Maybe look into the solution implemented by [this react component](https://github.com/stereobooster/mobile-safari-fullscreen)?

It is based on solutions discussed in [this article](https://www.eventbrite.com/engineering/mobile-safari-why/).

**Comment by HarelM** [comment]
The linked library references React, which is a large dependency we definitely don't want.
Having said that, if we can use some css and basic js to solve this, it might be a possible solution.
Having said that, I'm not super keen to workaround a know safari bug...

**Comment by kevinschaul** [comment]
I think this was fixed by #1678. Running version 3.0.0-pre.1, I see the fullscreen control on my iPhone in Safari.

**Comment by HarelM** [comment]
I'll close this, if the PR doesn't solve this feel free to reopen

**Comment by roblabs** [comment]
Thanks @kevinschaul for pointing out the fix from #1678.  And @caspg for the original fix.  

This will work for our mobile customers.  I had only been testing releases, but when it lands in 3.x it will be good to go.

<img width=61.8% alt="" src="https://user-images.githubusercontent.com/118112/216422457-fec0b88d-cb8c-42ad-b638-cb9972285b5f.png">
