### ISSUE TITLE
lint issue in one_finger_touch_drag.ts

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#1933]
This file has lint issue: src\ui\handler\one_finger_touch_drag.ts

I see "npm run lint" is enabled in pipeline. Wonder how did it pass?

<code>
 11:36  warning  'lastPoint' is defined but never used. Allowed unused args must match /^_/u  @typescript-eslint/no-unused-vars
  11:54  warning  'point' is defined but never used. Allowed unused args must match /^_/u      @typescript-eslint/no-unused-vars
</code>

**Comment by HarelM** [comment]
It's a warning, we need to change the rules to be errors I believe.

**Comment by VehpuS** [comment]
In any case this is solved by a pull request (https://github.com/maplibre/maplibre-gl-js/pull/1908) I'm working on, as part of a larger refactor.

**Comment by HarelM** [comment]
Fixed by #1908
