### ISSUE TITLE
Black squares visible instead of tiles with mapbox maps containing geo-references image 

### ISSUE THREAD

**Issue by igal1c0de4n** [maplibre/maplibre-gl-js#1936]
Using https://github.com/rowanwins/maplibregl-mapbox-request-transformer 
I load a mapbox map created via mapbox studio, where an image has been geo-referenced as a top layer.

### Expected Behavior
Map should correctly display tiles around the geo-referenced image 

### Actual Behavior
Map (version v2.0.0 and above) display black tiles around the geo-referenced image.

With maplibre-gl.js v1.15.2, the map renders well:
https://jsfiddle.net/tivoni/k60nr18x/6/

With maplibre-gl.js v2.0.0 and above, black tiles appear around the geo-referenced image:
https://jsfiddle.net/tivoni/k60nr18x/

I have access to more maps on mapbox studio with georeferenced layers - all showing exactly the same issue.

Expected (v1.15.2):
<img width="960" alt="Screenshot 2022-12-14 at 1 23 57 AM" src="https://user-images.githubusercontent.com/1245766/207466719-f99b79c5-0704-4054-bb16-d7f2a24c99af.png">

Actual (v2 and above):
<img width="911" alt="Screenshot 2022-12-14 at 1 19 51 AM" src="https://user-images.githubusercontent.com/1245766/207466163-17ba3c40-d1df-483b-8c77-03ee9bc782a6.png">

**Comment by HarelM** [comment]
Version 2 no longer supports the mapbox:// protocol.
There's is a community plugin for that if needed.

**Comment by igal1c0de4n** [comment]
I'm already using https://github.com/rowanwins/maplibregl-mapbox-request-transformer
Is this the community plugin you referred to?

Both jsfilddles I provided use this plugin - which translates the mapbox requests also in the maplibre v1.15.2 case.
Since the converted tiles requests work well in that case, my conclusion that the plugin supports well these maps.

I believe this issue was incorrectly closed. 
@HarelM Can you review?

**Comment by HarelM** [comment]
Thanks for the info, I'll look closer, I missed that plugin part.

**Comment by HarelM** [comment]
Checkout the network tab:
The background of the building is not transparent:
![image](https://user-images.githubusercontent.com/3269297/207547418-4d7af6bd-8420-4d0e-957c-72f2d4fa1dfe.png)

**Comment by igal1c0de4n** [comment]
How does it get to be transparent with the older maplibregl version?

**Comment by HarelM** [comment]
Feel free to open an issue in the plugin code, or better yet open a PR there to fix this.
MapLibre no longer supports Mapbox protocol.
Moveover, Mapbox-gl is a great product and their team is doing a great job, using their rendering library should be your default when using their data, not MapLibre...
Closing...

**Comment by igal1c0de4n** [comment]
@HarelM May I ask what indicates to you that the issue resides in the plugin, and not in maplibregl-js?

**Comment by HarelM** [comment]
There were no changes to webp between 1.x and 2.x versions.
The example here is using a plugin that might or might not work correctly.
If you would like to produce an example that doesn't use the plugin and mapbox protocol and shows this issue I'll be happy to look into it.

**Comment by igal1c0de4n** [comment]
I ask because going over the plugin code:
https://github.com/rowanwins/maplibregl-mapbox-request-transformer/blob/main/src/index.js

There's no reference to any logic which selects the type of image tiles (webp/jpg/png). 
Hence maplibregl-js must be deciding what type of image to request. 
The plugin is a simple request url converter, not more

**Comment by igal1c0de4n** [comment]
perhaps helpful, when loading a maptiler style with maplibregl-js v2.4.0 the georeferenced images appear without black tiles.
maplibregl-js v2.4.0 is requesting PNG image tiles  - not JPG. 

PNG supports transparency...

Still it's interesting, why is maplibregl-js requesting JPGs? 
This is especially concerning given that webp is available (and works!)

**Comment by igal1c0de4n** [comment]
Is there a way to easily confirm that `webpSupported.supported === true` in:

https://github.com/maplibre/maplibre-gl-js/blob/main/src/util/ajax.ts#L367
![Screenshot 2022-12-15 at 12 04 39 AM](https://user-images.githubusercontent.com/1245766/207724877-9dda3450-00bc-4c51-89c0-c5a12756c22a.png)

**Comment by igal1c0de4n** [comment]
> I don't know if it was converted correctly into the plugin code or not, but if it's not there then it's probably missing...

The plugin is not producing `webpSupported`, also it can't access this internal maplibre construct. I can't see how such a test execute in the plugin context (?)

**Comment by HarelM** [comment]
You can look/take the code from here:
https://github.com/maplibre/maplibre-gl-js/blob/ee5f6679f26207bd36ae9ba1b34bbf4b2deb96a8/src/util/webp_supported.ts
I'm sure there are better ways to do it nowadays, this code is probably old and too complicated.
Looking at this probably indicates that this is a non issues now:
https://www.lambdatest.com/web-technologies/webp
More info can be found here as well, not sure how recent this is though:
https://stackoverflow.com/questions/5573096/detecting-webp-support

**Comment by igal1c0de4n** [comment]
@HarelM thanks for the resources.
After reviewing everything, I found that the requested mapbox style points to the [`.json` resource](https://api.mapbox.com/v4/mapme1.9x3arx2f.json?secure&access_token=pk.eyJ1IjoibWFwbWUxIiwiYSI6ImNrdWR1bXVnaDBwazIycnJ2cXBjZG01eTMifQ.LU2BPEtK88RvGwfyAHVoqw)  which includes:
```json
"tiles": [
  "https://a.tiles.mapbox.com/v4/mapme1.9x3arx2f/{z}/{x}/{y}.jpg?access_token=..."
```
If this the reason mapboxgl-js requests `.jpg` tiles, I'm inclined to accept that maplibregl-js behaves as expected.

Moving forward I can use final advice; please advise:
1. Should I consult mapbox's tech support to modify the tiles url template returned in the `json` resource to something like:
```
  "https://a.tiles.mapbox.com/v4/mapme1.9x3arx2f/{z}/{x}/{y}.webp?access_token=..."
```
2. Use `transformRequest` to convert `.jpg` tiles request urls to `.webp` urls.
Would you recommend this approach?
(I am viewing this as a hack - not a huge fan)

Also, any ideas how maplibre v1.15.2 "knows" to request `.webp` tiles for this style instead of the `.jpg` tiles specified in the style's `.json`?
