### ISSUE TITLE
Errors running the MapLibre GL style utilities

### ISSUE THREAD

**Issue by zstadler** [maplibre/maplibre-gl-js#1963]
**maplibre-gl-js version**:

@maplibre/maplibre-gl-style-spec@17.0.1

**browser**:
NA

### Steps to Trigger Behavior
Following the instructions at the [README](https://github.com/maplibre/maplibre-gl-js/blob/main/src/style-spec/README.md) for _MapLibre GL style specification & utilities_.

 1. `sudo npm install @maplibre/maplibre-gl-style-spec --global`
 2. Any of the following commands:
    - `gl-style-validate`
    - `gl-style-format`
    - `gl-style-migrate`
    - `gl-style-composite`

### Expected Behavior
The programs should print their help messages because no argument were given.

_Note_: This is a minimal reproduction scenario for the fact that the programs also do not run with proper arguments.

### Actual Behavior
The programs produce an error like this:
```$ gl-style-validate
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /usr/local/lib/node_modules/@maplibre/maplibre-gl-style-spec/bin/gl-style-validate
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:65:15)
    at Loader.getFormat (internal/modules/esm/loader.js:116:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:247:31)
    at async Loader.import (internal/modules/esm/loader.js:181:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

**Comment by zstadler** [comment]
For our reference, the Mapbox version of the tools run without an error and show the appropriate help text.

For example,
```
/tmp$ sudo npm install @mapbox/mapbox-gl-style-spec --global

added 11 packages, and audited 12 packages in 5s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
/tmp$ gl-style-validate
usage:
  gl-style-validate file.json
  gl-style-validate < file.json

options:
--json  output errors as json
--mapbox-api-supported  validate compatibility with Mapbox Styles API
```

**Comment by wipfli** [comment]
The tool used to work. If you find a way to fix it, it would be great to also make a test

**Comment by zstadler** [comment]
Unfortunately I'm unfamiliar with the dotnet environment.

Could it be a side effect of the transition to TypeScript?

**Comment by acalcutt** [comment]
When I try to run the bin file here on npm 16.17.0, it gives me this error

`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension "" for /root/.nvm/versions/node/v16.15.0/lib/node_modules/@maplibre/maplibre-gl-style-spec/bin/gl-style-migrate. Loading extensionless files is not supported inside of "type":"module" package.json contexts. The package.json file /root/.nvm/versions/node/v16.15.0/lib/node_modules/@maplibre/maplibre-gl-style-spec/package.json caused this "type":"module" context. Try changing /root/.nvm/versions/node/v16.15.0/lib/node_modules/@maplibre/maplibre-gl-style-spec/bin/gl-style-migrate to have a file extension. Note the "bin" field of package.json can point to a file with an extension, for example {"type":"module","bin":{"gl-style-migrate":"./bin/gl-style-migrate.js"}}`

Could we do like it says and give the files in https://github.com/maplibre/maplibre-gl-js/tree/main/src/style-spec/bin an extension, then fix the bin fields in https://github.com/maplibre/maplibre-gl-js/blob/main/src/style-spec/package.json#L26-L29 to point to the extensioned file?

**Comment by acalcutt** [comment]
I tested adding a cjs extension to this files, which seems to work for gl-style-validate and gl-style-format. At least, the help for these show now in my test release @acalcutt/maplibre-gl-style-spec@17.0.3

gl-style-migrate and gl-style-composite do not show help, but looking at the code there isn't anything to actually show help in the code like the other files have. in the mapbox release is seems like help was added after the fork.

While this works changing to cjs extension, these files are pretty small. it might be a good idea to update these to ESM syntax and use a js (or mjs?) extension.

**Comment by acalcutt** [comment]
@zstadler I've been working on updating these scripts in https://github.com/maplibre/maplibre-gl-js/pull/1971 

I've published them in @acalcutt/maplibre-gl-style-spec@17.0.6 . Any chance you can try this release and tell me if it works as expected? Do you know if there are any example files somewhere to test these scripts?

**Comment by zstadler** [comment]
Hi @acalcutt,

Thank you for fixing the scripts!

I've tested all scripts with a few of styles [here](https://github.com/IsraelHikingMap/VectorMap/tree/master/Styles). They all work flawlessly. 

I was pleasantly surprised to see that ` gl-style-migrate` would replace the ["deprecated" expressions](https://maplibre.org/maplibre-gl-js-docs/style-spec/other/) with the [new ones](https://maplibre.org/maplibre-gl-js-docs/style-spec/expressions/). Once the fixed scripts are published, we can refer to them [in the docs](https://maplibre.org/maplibre-gl-js-docs/style-spec/other/#function) and the (now closed) related issue #1385.

`gl-style-composite` is of no use to me. As far as I can tell, the script aims at reducing the tile consumption costs for MapBox customers by replacing several sources with a single "composite" source. IMO, this script can and should be removed from the MapLibre repository.

**Comment by zstadler** [comment]
@HarelM,
Please remove the `enhancement` label.
Thanks!

**Comment by acalcutt** [comment]
I think the 'publish-style-spec' action needs to be run for this to officially be fixed.

**Comment by HarelM** [comment]
I've ran the action, there should be a new version with the fixes. Let me know if this is not the case.

**Comment by acalcutt** [comment]
looks successful, seems to work for me.

**Comment by acalcutt** [comment]
I was thinking about the information about 'gl-style-migrate' updating depreciated expressions. 

My theme is based on some of the themes mentioned in https://github.com/maplibre/maplibre-gl-js/issues/1385 , so I was wondering if 'gl-style-validate' would show any errors in the theme, but it didn't list any like I thought it would. I then ran my style through 'gl-style-migrate' and it did update quite a bit of syntax in the expressions. I'd have to research more if it actually did what it was supposed to do though.
