### ISSUE TITLE
Deprecated github release action

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#1969]
We currently use the deprecated https://github.com/actions/create-release in release.yml , and it triggers deprecation warnings in our CI because it uses node 12, and in the summer 2023 all action has to use min. node 16. [more info](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)

We should move to one of the recommended alternatives.

**Comment by birkskyum** [comment]
From our CI 
<img width="1075" alt="Screenshot 2022-12-20 at 12 28 56" src="https://user-images.githubusercontent.com/74932975/208656632-a5552e52-82a3-4912-91d7-7a8d0c10da55.png">

**Comment by mohitsaxenaknoldus** [comment]
I am working on this, I'll raise a PR for this soon.

**Comment by mohitsaxenaknoldus** [comment]
@birkskyum PR: https://github.com/maplibre/maplibre-gl-js/pull/1982
