### ISSUE TITLE
Unimplemented type: 3 error with ESRI basemap service

### ISSUE THREAD

**Issue by kissmygritts** [maplibre/maplibre-gl-js#197]
**maplibre-gl-js version**: 1.15.0

**browser**: Brave (chrome), Firefox, Safari

### Steps to Trigger Behavior

1. Create a map
2. use a basemap from ESRI basemap service (this works, can load the basemap)
3. add a source and layer for geometry labels (this is when the error is thrown)

### Link to Demonstration

I've created several examples of what I expect to happen in both Mapbox and Maplibre with and without ESRI basemaps. I've hard coded a label as "label" but commented out the dynamic look up for the property I want to use for the label and it works with the maptiler basemap.

1. Works, maplibre and maptiler basemap: https://codepen.io/kissmygritts/pen/ZEKWMWj
2. Doesn't work, maplibre and ESRI basemap: https://codepen.io/kissmygritts/pen/rNmervJ
3. Works, mapbox and maptiler basemap: https://codepen.io/kissmygritts/pen/zYwqJbO
4. Doesn't work, mapbox and ESRI basemap: https://codepen.io/kissmygritts/pen/RwVaYzg

### Expected Behavior

The map should display labels and centroids when adding a symbol layer to the map. I don't think the problem is the data I am using since it works when I use a maptiler basemap. And it works if the symbol layer is commented out and the centroid layer is left alone.

### Actual Behavior

All layers specified in the map are displayed on the map.

Thanks

**Comment by HarelM** [comment]
Can you check if this used to work in maplibre 1.13 or mapbox 1.13? or earlier mapbox versions?
I don't think there was a big modification in this library...

**Comment by kylebarron** [comment]
This happens when you try to load gzipped vector tiles without extracting them, and is not an issue with Maplibre GL JS https://github.com/mapbox/tippecanoe/issues/582#issuecomment-394126100

**Comment by kissmygritts** [comment]
@kylebarron how do I extract them? 

The `Content-Encoding` header is set to `gzip` for all tiles loaded from my server and the ESRI basemap server (according to this https://github.com/mapbox/mapbox-gl-js/issues/3696#issuecomment-263325173).  `Accept-Encoding` header is set to `gzip, deflate, br` for all requests (to my server and ESRI and Maptiler).

**Comment by kylebarron** [comment]
I don't know; I haven't looked into it deeply, I just remembered that `Unimplemented type: 3` is almost always the gzipping issue.

**Comment by kissmygritts** [comment]
I agree. It isn’t an issue with the mapbox or maplibre code. I don’t think it is my server causing the issue since it works with Maptiler basemaps. Hopefully it is something with the ESRI basemaps.

**Comment by AbelVM** [comment]
Using Chrome 91 / ubuntu with your examples:
* maplibre + esri
![image](https://user-images.githubusercontent.com/9017165/124918970-f1b3b500-dff5-11eb-9cec-a3461b273f5b.png)
* mapbox + esri
![image](https://user-images.githubusercontent.com/9017165/124919021-04c68500-dff6-11eb-95b4-6bee7639caf0.png)

**Comment by kissmygritts** [comment]
I'm going to close this issue as I think it is clear the problem has to do with the actual vector tiles from ESRI rather than the maplibre library. If I do get any feedback from ESRI I'll report back here.

**Comment by kylebarron** [comment]
I believe the error comes from vector-tile-js, which might still be open source from Mapbox

**Comment by 321ckatz123** [comment]
@kissmygritts I actually ran into the same issue but appear to have solved it. As long as use one of the fonts as described here: https://developers.arcgis.com/javascript/latest/labeling/ it actually works.

I would guess there's some weird "fallback" issue that has a bug if it doesn't actually "know" of the font.
