### ISSUE TITLE
3D terrain when active fail to show and image source and warnings appears in console

### ISSUE THREAD

**Issue by navilaufm** [maplibre/maplibre-gl-js#1979]
**maplibre-gl-js version**: 2.4.0

**browser**: Mac Chrome 108.0.5359.124 (Official Build) (arm64)

### Steps to Trigger Behavior

 1. A map with an image overlay source shows ok, but when enabling the terrain 3d option it does not shows the image source complete.
![image](https://user-images.githubusercontent.com/61478833/209065277-ee8ce523-68ee-46ce-8ad7-9fa18c9e2b92.png)

when adding the 3D terrain source with the following code (full code in sample links):
<img width="664" alt="image" src="https://user-images.githubusercontent.com/61478833/209065375-7ad6ea21-3a1d-452b-822e-d1f4b4f43ecb.png">

the image does not show complete:
![image](https://user-images.githubusercontent.com/61478833/209065415-f1f68677-54d1-4ce3-8d34-14ab88b8005e.png)

and the following appears in console:
`83209271-e541-4d31-9f74-52a1663491ad:1 Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently`

 
### Link to Demonstration
without 3D
https://climaya.com/maplibre/mapl.html?url=https://nube1.on.gt/icon/min_temp_72.png&lon=-98&lat=17&z=4.6&p=28.5&x1=-120.125&x2=-49.875&y1=-0.125&y2=35.125&opacity=0.5

With 3D enabled image overlay does not show complete and opacity is not respected.
https://climaya.com/maplibre/mapl.html?url=https://nube1.on.gt/icon/min_temp_72.png&lon=-98&lat=17&z=4.6&p=28.5&x1=-120.125&x2=-49.875&y1=-0.125&y2=35.125&opacity=0.5&d3=1

**Comment by HarelM** [comment]
Is this the same as #1559 by any chance? It looks the same from the description, but I'm not sure.
If so, please close this one and add info to the other.

**Comment by navilaufm** [comment]
Added my comments to https://github.com/maplibre/maplibre-gl-js/issues/1559
