### ISSUE TITLE
Remove the `gl-style-composite` utility

### ISSUE THREAD

**Issue by zstadler** [maplibre/maplibre-gl-js#1981]
## Motivation
The `gl-style-composite` utility is `mapbox://`-specific optimization tool. It is used to reduce the tile consumption costs for MapBox customers by replacing several sources with a single "composite" source. See the [MapBox API](https://docs.mapbox.com/api/maps/vector-tiles/#retrieve-vector-tiles) for some details.

The code clearly handled only `mapbox://` sources:

https://github.com/maplibre/maplibre-gl-js/blob/80e232a64716779bfff841dbc18fddc1f51535ad/src/style-spec/composite.ts#L14-L16

IMO it need not and should not be released as part of the MapLibre release.

Related to #1963

**Comment by acalcutt** [comment]
I thought this had to do with labeling placement ( https://blog.mapbox.com/improved-label-placement-in-mapbox-studio-caf930aa84ea )

Is that how it works, it combines sources?

**Comment by zstadler** [comment]
Yes.

It saves the references to `mabox://` sources that passed the above test

https://github.com/maplibre/maplibre-gl-js/blob/80e232a64716779bfff841dbc18fddc1f51535ad/src/style-spec/composite.ts#L18-L19

If there are more than one, it deletes the existing sources

https://github.com/maplibre/maplibre-gl-js/blob/80e232a64716779bfff841dbc18fddc1f51535ad/src/style-spec/composite.ts#L25-L27

Then it creates a new source with a URL composed of the original, now deleted, sources

https://github.com/maplibre/maplibre-gl-js/blob/80e232a64716779bfff841dbc18fddc1f51535ad/src/style-spec/composite.ts#L29-L34

and replaces the source in each layer with the newly created source

https://github.com/maplibre/maplibre-gl-js/blob/80e232a64716779bfff841dbc18fddc1f51535ad/src/style-spec/composite.ts#L36-L38

**Comment by HarelM** [comment]
People using mapbox stuff can use their tools, I'm sure this is still part of the mapbox style spec package, no need to keep it here.
Feel free to submit a PR to remove this.

**Comment by zstadler** [comment]
This looks like a migration tool for people who used multiple MapBox sources before their API allowed composite sources.
In any case, this is a MapBox specific tool for users of their API. Naturally, it is available from MapBox.

**Comment by zstadler** [comment]
> People using mapbox stuff can use their tools, I'm sure this is still part of the mapbox style spec package, no need to keep it here. Feel free to submit a PR to remove this.

To avoid code conflicts, I'll submit a PR after #1963 is resolved, probably by #1971.

For all I care, #1971 can also do the removal. Actually, I prefer that 😉

**Comment by acalcutt** [comment]
I removed the binary and the readme test in #1971 . I'm sure there is more to remove, like composite.ts but i'm not sure what that involves.
