### ISSUE TITLE
CSS renaming in version 1.15.1 breaks dependency compatibility

### ISSUE THREAD

**Issue by jimmyangel** [maplibre/maplibre-gl-js#199]
**maplibre-gl-js version**: 1.15.1

**browser**: Any

### Steps to Trigger Behavior

 1. Define maplibre dependency in package.json (e.g., "maplibre-gl": ">=1.14.0)
 2. Define additional dependency in package.json (e.g., "mapbox-gl-style-switcher": "^1.0.8")
 3. npm install will upgrade to maplibre version 1.15.1 which contains breaking changes, in this case, mapbox-gl-style-switcher expects names of css classes to begin with ```mapboxgl-``` but they have been renamed to ```maplibregl-```

### Expected Behavior

Non-breaking changes when going from 1.14 to 1.15

### Actual Behavior

All library dependencies that rely on mapbox class names stop working. Temporary workaround is to pin the dependency to ```"maplibre-gl": "=1.14.0"``` which is not ideal.

Breaking changes should be introduced in major version increases, i.e.., 2.0.0 and above.

**Comment by astridx** [comment]
Thanks for reporting this.
It is related to #83.

**Comment by jimmyangel** [comment]
Thank you very much!
