### ISSUE TITLE
Resolve peer dependencies on mapbox-gl-js by packages we depend on 

### ISSUE THREAD

**Issue by snickell** [maplibre/maplibre-gl-js#20]
`mapbox-gl-js` has a circular dep relationship (via peer deps) with @mapbox/mapbox-gl-supported and @mapbox/mapbox-gl-rtl-text.

When we build:
```
[4/5] Linking dependencies...
warning " > @mapbox/mapbox-gl-supported@1.5.0" has unmet peer dependency "mapbox-gl@>=0.32.1 <2.0.0".
warning " > @mapbox/mapbox-gl-rtl-text@0.2.3" has unmet peer dependency "mapbox-gl@>=0.32.1 <2.0.0".
```

Not sure what effects this will have, it might or might not be a v1.13.0 blocker? Relevant to #5

**Comment by msbarry** [comment]
Should we move these as sub packages into this repo?
