### ISSUE TITLE
Distributed source map broken since v2.2.0-pre.4

### ISSUE THREAD

**Issue by neodescis** [maplibre/maplibre-gl-js#2005]
It seems that source map generation is broken, and has been for a few months.

**maplibre-gl-js version**:
v2.2.0-pre4 through v3.0.0-pre2

### Steps to Trigger Behavior

 1. Download the affected versions from npm
 2. Open the file dist/maplibre-gl.js.map
 3. You can see that after v2.2.0-pre3, the source map has almost nothing in it. For v2.2.0-pre3, it was still working.

### Link to Demonstration

https://unpkg.com/maplibre-gl@2.2.0-pre.3/dist/maplibre-gl.js.map
https://unpkg.com/maplibre-gl@2.2.0-pre.4/dist/maplibre-gl.js.map
https://unpkg.com/maplibre-gl@3.0.0-pre.2/dist/maplibre-gl.js.map

**Comment by HarelM** [comment]
Is this the same as #1582 ?

**Comment by neodescis** [comment]
I think so, but it looks like it's not fixed? The latest v3.0.0-pre2 still has the same incomplete source map.

**Comment by rotu** [comment]
Same symptom, multiple causes. Related discussion here:

https://github.com/maplibre/maplibre-gl-js/pull/1951#issuecomment-1363587909

**Comment by neodescis** [comment]
This has been working as of 3.x.
