### ISSUE TITLE
Top-level export `Map` conflicts with built in Javascript type

### ISSUE THREAD

**Issue by rotu** [maplibre/maplibre-gl-js#2025]
## Motivation
It is natural to use a named import in esm. Unfortunately, this conflicts with the built-in javascript `Map` class, which can result in developer confusion and typescript issues.

```
import {Map} from "maplibre-gl";
```

## Design Options

1. Rename the main map constructor and type to something like `MapLibre`, `MapView` or `MapPane`.
2. Leave the type as-is and provide the recommendation to `import { Map as MapLibre } from "maplibre-gl`.
3. Don't export the Map constructor and instead expose a factory method like `createMap`.

**Comment by HarelM** [comment]
Yea, I've experienced this as well, not sure what should be the right solution though.
`Map` is a very reasonable name.
But I think I managed to use both in the same file IIRC.
Use `Map` for the drawn map, and `Map<key, value>` for the hash-map.

**Comment by HarelM** [comment]
You can use `global.Map` for the hash type.
I don't think we'll ever change that although this collides with a global object.

**Comment by birkskyum** [comment]
I use import { Map as MLMap } from 'maplibre-gl'
