### ISSUE TITLE
Illegal attempt to monkey-patch a module with Jest

### ISSUE THREAD

**Issue by rotu** [maplibre/maplibre-gl-js#2043]
When attempting to run the load_sprite test with ES modules enabled, the test suites fail. This is because the tests, via Jest, attempt to make changes to a module.

```NODE_OPTIONS="$NODE_OPTIONS --experimental-vm-modules" jest --no-cache src/style/load_sprite.test.ts```

```
 FAIL   jsdom  src/style/load_sprite.test.ts
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'arrayBufferToImageBitmap' of object '[object Module]'

      at node_modules/jest-mock/build/index.js:734:33
          at Set.forEach (<anonymous>)
```

https://github.com/maplibre/maplibre-gl-js/blob/541d530f3b4f54dded43902a6aba65576adefa3d/src/style/load_sprite.test.ts#L7-L10

note there are some commit changes that need to be made as well to get jest to get as far as the above:

https://github.com/rotu/maplibre-gl-js/commit/881203c8854d0251c615697a3e345b677e89baa8

**Comment by HarelM** [comment]
I believe this no longer it relevant, I think I solved all the jest warning and error during test run.
