### ISSUE TITLE
Build warning about byte alignment

### ISSUE THREAD

**Issue by rotu** [maplibre/maplibre-gl-js#2053]
In the course of building the project, the following warnings are emitted:
```
$ npm run generate-struct-arrays
> maplibre-gl@3.0.0-pre.3 generate-struct-arrays
> ts-node build/generate-struct-arrays.ts

Warning: The layout StructArrayLayout3i6 is not aligned to 4-bytes boundaries.
Warning: The layout StructArrayLayout3ui6 is not aligned to 4-bytes boundaries.
Warning: The layout StructArrayLayout3i6 is not aligned to 4-bytes boundaries.
Warning: The layout StructArrayLayout3ui6 is not aligned to 4-bytes boundaries.
Warning: The layout StructArrayLayout1ui2 is not aligned to 4-bytes boundaries.
```

These warnings seem to originate from:
https://github.com/maplibre/maplibre-gl-js/commit/791a42baafc8aa47deca60ccf06baa43a805a543

The warnings should either be fixed or removed.

**Comment by prozessor13** [comment]
Sorry, i cannot help with this issue, but what i can say is, that not only 3D-Points are using StructArrayLayout3i6, also SymbolLineVertexArray. Dont know why there is a warning?
Sure the points can use floats instead of int, then they are 4bytes-aligned, but it would double the vertexarray size.
