### ISSUE TITLE
Style spec references code from maplibre-gl

### ISSUE THREAD

**Issue by rotu** [maplibre/maplibre-gl-js#2054]
The following identifiers are defined in the `maplibre-gl` package but are referenced from the style spec. ~~Their definitions should be moved to the style spec~~. The code needs to be reorganized to prevent the style spec from being dependent on the implementation:

- `CanonicalTileID`
- `MercatorCoordinate`
- `EXTENT`

**Comment by rotu** [comment]
Once resolved, I'd like to enforce this from happening again by enabling the eslint [import/no-relative-packages rule](https://github.com/import-js/eslint-plugin-import/blob/HEAD/docs/rules/no-relative-packages.md)

**Comment by rotu** [comment]
The build scripts for style-spec live in the maplibre-gl package. They should probably also be moved within the style spec subpackage.

**Comment by wipfli** [comment]
Place in style spec which reference maplibre-gl-js code are:

https://github.com/maplibre/maplibre-gl-js/blob/862e92bc32673671612ebe12a9f8e9e0cdd35d72/src/style-spec/expression/evaluation_context.ts#L4

https://github.com/maplibre/maplibre-gl-js/blob/862e92bc32673671612ebe12a9f8e9e0cdd35d72/src/style-spec/expression/index.ts#L26

https://github.com/maplibre/maplibre-gl-js/blob/862e92bc32673671612ebe12a9f8e9e0cdd35d72/src/style-spec/expression/definitions/within.ts#L7

https://github.com/maplibre/maplibre-gl-js/blob/862e92bc32673671612ebe12a9f8e9e0cdd35d72/src/style-spec/feature_filter/feature_filter.test.ts#L5-L7

https://github.com/maplibre/maplibre-gl-js/blob/862e92bc32673671612ebe12a9f8e9e0cdd35d72/src/style-spec/feature_filter/index.ts#L3

**Comment by wipfli** [comment]
Removing `CanonicalTileID` and the others from gl js is probably a breaking change, so we should do it as part of v3, #1716

**Comment by HarelM** [comment]
Wht are these referenced? Moving the style spec to a different repo will also help solving this.

**Comment by wipfli** [comment]
Ah the references are just the places where file in the `src/style-spec` folder import something from outside the `src/style-spec` folder. So these are the places where the style-spec package depends on maplibre-gl-js.

**Comment by wipfli** [comment]
Some of these circular dependencies were introduced here: https://github.com/mapbox/mapbox-gl-js/pull/9428

**Comment by rotu** [comment]
> Wht are these referenced? Moving the style spec to a different repo will also help solving this.

1. Moving the style spec to another repo won’t solve this. The other way round. Solving this is required to move the code to another repo.
2. Moving to another repo is also unnecessary to enforce this separation. The eslint `import/no-relative-packages` is sufficient.
3. I’m not sure that it’s correct to move CanonicalTileID to style-spec. As far as I can tell, this logic belongs in the style implementation, not style-spec.

**Comment by rotu** [comment]
@wipfli, could you fix the refs in `feature_filter.test`? I tried and I don't understand the code well enough to disentangle this.

**Comment by wipfli** [comment]
EXTENT seems to be hardcoded in a bunch of places.

**Comment by wipfli** [comment]
And the class mercator coordinate defined here:

https://github.com/maplibre/maplibre-gl-js/blob/ff99b076b2dde5c0cc4078d6e0917f29919e5a89/src/geo/mercator_coordinate.ts#L77

Might be similar to this point module or how it is called and maybe could be factored out.

**Comment by birkskyum** [comment]
The style-spec actually compiles without importing anything from maplibre-gl-js at this point.

This is obtained by having MercatorCoordinate is inside of style-spec here:
https://github.com/maplibre/maplibre-gl-style-spec/blob/main/src/coordinates/mercator_coordinate.ts

Only the type of CanonicalTileID is used in style-spec, so there is an interface ICanonicalTileID here, which is imported maplibre-gl-js as well:
https://github.com/maplibre/maplibre-gl-style-spec/blob/main/src/tiles_and_coordinates.ts

Also, the LngLat type is necessary for MercatorCoordinate, so it's also to be found in style-spec here: 
https://github.com/maplibre/maplibre-gl-style-spec/blob/main/src/coordinates/lng_lat.ts
