### ISSUE TITLE
map.getFreeCameraOptions is not a function

### ISSUE THREAD

**Issue by nicky132** [maplibre/maplibre-gl-js#2055]
**maplibre-gl-js version**:3.0.0-pre.3

**browser**:Google Chrome 版本 108.0.5359.125（正式版本） （64 位）

### Steps to Trigger Behavior

 1.
 2.
 3.

### Expected Behavior
no error
### Actual Behavior

`
var customLayer = {
            id: '3d-model',
            type: 'custom',
            renderingMode: '3d',
            onAdd: function(map, gl) {
                camera = new THREE.PerspectiveCamera();
                scene = new THREE.Scene();
                var cube = new THREE.Mesh(
                    new THREE.BoxGeometry( 300, 300, 300 ),
                    new THREE.MeshNormalMaterial()
                );
                scene.add(cube)
                let cube1 = cube.clone();
                cube1.material = new THREE.MeshNormalMaterial();
                cube1.translateX(1000);
                scene.add(cube1)
                map = map;
                // use the Mapbox GL JS map canvas for three.js
                renderer = new THREE.WebGLRenderer({
                    canvas: map.getCanvas(),
                    context: gl,
                    antialias: true
                });
                renderer.autoClear = false;
                raycaster = new THREE.Raycaster();
                //threemap
                window.tb = new Threebox(
                    map,
                    gl,
                    {
                    defaultLights: true,
                    enableSelectingFeatures: true,
                    enableSelectingObjects: true,
                    enableDraggingObjects: true,
                    enableRotatingObjects: true,
                    enableTooltips: true
                    }
                );
                var options = {
                    obj: 'models/Soldier.glb',
                    type: 'gltf',
                    scale: 20,
                    units: 'meters',
                    rotation: { x: 90, y: 0, z: 0 },
                    anchor: 'center'//default rotation
                }
                tb.loadObj(options, (model) => {
                    soldier = model.setCoords(origin);
                    // Listening to the events
                    soldier.addEventListener('SelectedChange', onSelectedChange, false);
                    soldier.addEventListener('Wireframed', onWireframed, false);
                    soldier.addEventListener('IsPlayingChanged', onIsPlayingChanged, false);
                    soldier.addEventListener('ObjectDragged', onDraggedObject, false);
                    soldier.addEventListener('ObjectMouseOver', onObjectMouseOver, false);
                    soldier.addEventListener('ObjectMouseOut', onObjectMouseOut, false);
                    soldier.addEventListener('ObjectChanged', onObjectChanged, false);
                    tb.add(soldier);
                })
            },
            render: function(gl, matrix) {
            var m = new THREE.Matrix4().fromArray(matrix);
            var l = new THREE.Matrix4()
                .makeTranslation(
                modelTransform.translateX,
                modelTransform.translateY,
                modelTransform.translateZ
                )
                .scale(
                new THREE.Vector3(
                    modelTransform.scale,
                    -modelTransform.scale,
                    modelTransform.scale
                )
                );
            camera.projectionMatrix = m.clone().multiply(l);
            camera.matrixWorldInverse = new THREE.Matrix4();
            renderer.resetState();
            const freeCamera = map.getFreeCameraOptions();
            console.log("freeCamera",freeCamera)
            let cameraPosition = new THREE.Vector4(freeCamera.position.x, freeCamera.position.y, freeCamera.position.z, 1);
            cameraPosition.applyMatrix4(l.invert());
            let direction = mouse.clone().applyMatrix4(camera.projectionMatrix.clone().invert());
            direction.divideScalar(direction.w);
            raycaster.set(cameraPosition, direction.sub(cameraPosition).normalize());

            const intersects = raycaster.intersectObjects( scene.children );
            console.log('Intersection count:', intersects.length)
            for ( let i = 0; i < intersects.length; i ++ ) {
                intersects[ i ].object.material.wireframe = true;
            }
            renderer.render(scene, camera);
            for ( let i = 0; i < intersects.length; i ++ ) {
                intersects[ i ].object.material.wireframe = false;
            }
            tb.update();
            }
        }
`

![1673341623004_D00BEB3B-F2D0-432d-8900-2C2F809CAEC6](https://user-images.githubusercontent.com/34881461/211508722-3e939f55-20da-4c81-bc51-96ea309242c6.png)
![1673341641336_A5F5DDBC-10E5-4e1b-9016-11017DC47BD3](https://user-images.githubusercontent.com/34881461/211508755-86212521-9a78-4f29-bd38-395b8138fcea.png)

**Comment by HarelM** [comment]
What is freeMapOptions?

**Comment by nicky132** [comment]
> 

https://github.com/nicky132/threejs-mapbox-demos/blob/main/index_running.html
Just like this demo,hope someone do something about maplibre2 or threebox to works perfectly

**Comment by HarelM** [comment]
This is for mapbox, not maplinre... I'm failing to understand this issue...

**Comment by nicky132** [comment]
> 



> **maplibre-gl-js version**:3.0.0-pre.3
> 
> **browser**:Google Chrome 版本 108.0.5359.125（正式版本） （64 位）
> 
> ### Steps to Trigger Behavior
> 
> ### Link to Demonstration
> ### Expected Behavior
> no error
> 
> ### Actual Behavior
> ` var customLayer = { id: '3d-model', type: 'custom', renderingMode: '3d', onAdd: function(map, gl) { camera = new THREE.PerspectiveCamera(); scene = new THREE.Scene(); var cube = new THREE.Mesh( new THREE.BoxGeometry( 300, 300, 300 ), new THREE.MeshNormalMaterial() ); scene.add(cube) let cube1 = cube.clone(); cube1.material = new THREE.MeshNormalMaterial(); cube1.translateX(1000); scene.add(cube1) map = map; // use the Mapbox GL JS map canvas for three.js renderer = new THREE.WebGLRenderer({ canvas: map.getCanvas(), context: gl, antialias: true }); renderer.autoClear = false; raycaster = new THREE.Raycaster(); //threemap window.tb = new Threebox( map, gl, { defaultLights: true, enableSelectingFeatures: true, enableSelectingObjects: true, enableDraggingObjects: true, enableRotatingObjects: true, enableTooltips: true } ); var options = { obj: 'models/Soldier.glb', type: 'gltf', scale: 20, units: 'meters', rotation: { x: 90, y: 0, z: 0 }, anchor: 'center'//default rotation } tb.loadObj(options, (model) => { soldier = model.setCoords(origin); // Listening to the events soldier.addEventListener('SelectedChange', onSelectedChange, false); soldier.addEventListener('Wireframed', onWireframed, false); soldier.addEventListener('IsPlayingChanged', onIsPlayingChanged, false); soldier.addEventListener('ObjectDragged', onDraggedObject, false); soldier.addEventListener('ObjectMouseOver', onObjectMouseOver, false); soldier.addEventListener('ObjectMouseOut', onObjectMouseOut, false); soldier.addEventListener('ObjectChanged', onObjectChanged, false); tb.add(soldier); }) }, render: function(gl, matrix) { var m = new THREE.Matrix4().fromArray(matrix); var l = new THREE.Matrix4() .makeTranslation( modelTransform.translateX, modelTransform.translateY, modelTransform.translateZ ) .scale( new THREE.Vector3( modelTransform.scale, -modelTransform.scale, modelTransform.scale ) ); camera.projectionMatrix = m.clone().multiply(l); camera.matrixWorldInverse = new THREE.Matrix4(); renderer.resetState(); const freeCamera = map.getFreeCameraOptions(); console.log("freeCamera",freeCamera) let cameraPosition = new THREE.Vector4(freeCamera.position.x, freeCamera.position.y, freeCamera.position.z, 1); cameraPosition.applyMatrix4(l.invert()); let direction = mouse.clone().applyMatrix4(camera.projectionMatrix.clone().invert()); direction.divideScalar(direction.w); raycaster.set(cameraPosition, direction.sub(cameraPosition).normalize());
> 
> ```
>         const intersects = raycaster.intersectObjects( scene.children );
>         console.log('Intersection count:', intersects.length)
>         for ( let i = 0; i < intersects.length; i ++ ) {
>             intersects[ i ].object.material.wireframe = true;
>         }
>         renderer.render(scene, camera);
>         for ( let i = 0; i < intersects.length; i ++ ) {
>             intersects[ i ].object.material.wireframe = false;
>         }
>         tb.update();
>         }
>     }
> ```
> 
> `
> 
> ![1673341623004_D00BEB3B-F2D0-432d-8900-2C2F809CAEC6](https://user-images.githubusercontent.com/34881461/211508722-3e939f55-20da-4c81-bc51-96ea309242c6.png) ![1673341641336_A5F5DDBC-10E5-4e1b-9016-11017DC47BD3](https://user-images.githubusercontent.com/34881461/211508755-86212521-9a78-4f29-bd38-395b8138fcea.png)



> This is for mapbox, not maplinre... I'm failing to understand this issue...

Yes,you're right,but i want to use maplibre map engine instead of mapbox.
eg:https://codesandbox.io/s/react-threebox-handle-scale-3d-object-forked-hej5mv
This demo only works well with maplibre1.15.2,when i changed maplibre1.15.2 to maplibre2.4.0,some error message showed up.
So i also use latest version maplibre with this project,which is maplibre2.4.0

**Comment by HarelM** [comment]
Sorry, you'll need to investigate the differences.
In general, the API didn't change a lot, you can consult the change log file.

**Comment by birkskyum** [comment]
It's a great feature this getFreeCameraOptions() that mapbox added

**Comment by birkskyum** [comment]
@nicky132, if you're interested in making ThreeJS demos work with maplibre, I believe you'd be able to achieve this with the transformCameraUpdate introduced here #2535  - you can try it out with maplibre 3.0.0-pre.8. It's just a hook that allow some access to the camera transform before the update to the camera position is applied.

Also, since this ticket was opened, maplibre moved to webgl2, so the webgl2renderer in threejs can be used now.
