### ISSUE TITLE
Add a method to enable / disable cooperativeGestures

### ISSUE THREAD

**Issue by raphaelMalie** [maplibre/maplibre-gl-js#2057]
## Motivation

I have a button on my map to toggle a full screen mode (position:fixed; width+height:100%).

My use case is that I need to have cooperativeGestures enabled when my map is inlined somewhere in my page, but I want to disable it when the full screen mode is enabled.

There is currently no clean way to enable or disable cooperativeGestures programmatically.

This is the dirty way I have to do when I toggle cooperativeGestures :
```
if (fullscreen) {
	// This part is not optimal, but it's OK
	map._cooperativeGestures = false;

	// This part is really uggly...
	map.handlers._handlersById.touchPan._minTouches = 1;
} else {
	map._cooperativeGestures = true;
	map.handlers._handlersById.touchPan._minTouches = 2;
}
```

I can live with that, but I won't sleep well :smiling_face_with_tear: 

## Design Alternatives

We could have something like that :
```
map.enableCooperativeGestures();
map.disableCooperativeGestures();
```

Or (same way than interactions) :
```
map.cooperativeGestures.enable();
map.cooperativeGestures.disable();
```

If it's too complicated, please at least improve the part in **TouchPanHandler**. Instead of computing **TouchePanHandler._minTouches** in the constructor, compute it on the fly by checking if cooperativeGestures are still enabled or not.

**Comment by HarelM** [comment]
I generally understand the request and agree this is needed.
Can you find something similar that can be toggled on/off in the current API so that this API "feels" the same?
If so, please feel free to submit a PR.
There is also this PR which is waiting for review fixes.
Feel free to push it forward by creating a new PR with it as well if this interest you.
Thanks!

**Comment by raphaelMalie** [comment]
Thank you for your feedback, I will try to propose a clean PR soon to add this feature.

**Comment by magnolo** [comment]
i am also looking forward to this feature. But also would be awesome to change the text for the informational screen dynamically. For example if the user changes language. 

something like:

`
map.setCooperativeGestures( boolean | GestureOptions )
`

a set-named function would feel like to fit to other option updates like setCenter or setMaxBounds

thank you for all your effort

**Comment by HarelM** [comment]
That's an excellent point.

**Comment by magnolo** [comment]
I was really thankfull, that this option was there, but now its gone? So i cant change cooperativeGestures dynamically?

**Comment by HarelM** [comment]
It's in a different place, see changelog.

**Comment by magnolo** [comment]
oh man... thank you thank you for your fast answer.
