### ISSUE TITLE
Add a way to trigger a (synchronous) redraw

### ISSUE THREAD

**Issue by pakb** [maplibre/maplibre-gl-js#206]
## Motivation

As stated in [this Mapbox's issue](https://github.com/mapbox/mapbox-gl-js/issues/7893) some of us would like to have a way to trigger a redraw when we see it fit.
An exemple would be to use a Maplibre instance under another framework (i.e. Openlayers) and we want this master framework to be responsible of interpolating different WMS/WMTS layers with different CRS together, where Maplibre is here to render background vector tiles.
In this case, if we move the map, the two framework do not sync their redraw. This can result in "laggy" panning / zooming.

A solution that was proposed by the Openlayers community back then was to use some internal API function of Mapbox (see [this example on openlayers.org](https://openlayers.org/en/latest/examples/mapbox-layer.html))

This would clearly ease the integration of Maplibre in different frameworks (either mapping or UI, the issue on Mapbox's repo was more about React than Openlayers).

**Comment by HarelM** [comment]
The best approach would be to send a PR with tests included. If exposing such a simple method is the solution I'm all for it.

**Comment by lseelenbinder** [comment]
I think this is an excellent idea, and I'm agreed with @HarelM that with a PR, we should be able to merge without much difficulty.

**Comment by snickell** [comment]
Total agreement with @HarelM from me too, very happy to do review on this feature.... at least I would be this week haha. But I really support any efforts to add minimal hooks to avoid jenk and tear, I think that's exactly the find of polish I'd like to see going forward, neat project @pakb
