### ISSUE TITLE
Any plan to move to WebGL2 ?

### ISSUE THREAD

**Issue by AbelVM** [maplibre/maplibre-gl-js#2075]
## Motivation

* Inspired by: 
  * https://github.com/mapbox/mapbox-gl-js/pull/12514
  * https://github.com/mapbox/mapbox-gl-js/issues/8581

### Concepts

* Whats new: https://webgl2fundamentals.org/webgl/lessons/webgl2-whats-new.html
* Browsers support: https://caniuse.com/webgl2

### Implementation

* Intro: https://webgl2fundamentals.org/webgl/lessons/webgl1-to-webgl2.html

**Comment by HarelM** [comment]
See https://github.com/maplibre/maplibre-gl-js/pull/1891
Feel free to review it.

**Comment by AbelVM** [comment]
My fault! Just came across that PR.

Sorry for the noise, I'm closing this issue
