### ISSUE TITLE
Ability to prevent vector tile server requests beyond max zoom

### ISSUE THREAD

**Issue by gmcquatcgis** [maplibre/maplibre-gl-js#2080]
## Motivation
Noticed that requests are made to the server for vector tiles that are beyond max zoom even though the reparseOverzoom option is set to false. We would like the option to avoid the redundant server calls.

## Design
Pick the option in the vector source constructor.

### Mock-Up
Not required.

### Implementation
Link to PR: https://github.com/maplibre/maplibre-gl-js/pull/2081

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue and the PR you sent.
See my comments there. For clarity, let's continue the discussion on the linked PR (#2081)

**Comment by gmcquatcgis** [comment]
Thanks! Since reparseOverscaled wasn't in the public API and the server I'm using is preventing caching, I'll close this issue. Note that this issue was simply that that requests were being made, not that they were being made beyond the max zoom. Since they weren't being cached, all requests were going to our server. We'd like to prevent it but after review, I'm not convinced the proposed changes were the correct way to go about it.
