### ISSUE TITLE
Style switching using `setStyle` breaks dragging navigation behavior when used with terrain

### ISSUE THREAD

**Issue by DEV-ONI** [maplibre/maplibre-gl-js#2099]
Thank you very much for the library, I am experiencing a weird issue that seems to be a bug.
I attempting to use terrain with vector tiles as per the Maptiler guide and it works, but when I try implementing "style switching" for the `style`, I get the below behavior.

I am wondering if I am missing something here or if I have found a bug.
We are hoping to use this lib for our project, but style switching is essential for our needs

**maplibre-gl-js version**: 2.4.0

**browser**: Chrome 109.0.5414.119

### Minimum Rep Example:
https://codesandbox.io/s/maplibre-gl-terrain-bug-vb90sf?file=/src/Map.js

### Demo:
https://vimeo.com/792889655

### Steps to Trigger Behavior:
 1. Initialize a map with maplibre-gl-js and add a terrain source and `setTerrain`
 2. Navigating using the mouse (dragging) is normal
 3. Switch the style using `setStyle` and `setTerrain` once again
 4. Navigating using the mouse (dragging) causes zoom-in **_and even resetting to the original position_ as shown in video** (This does not occur in Step 2 no matter how many times I tried. Please see 0:40 in attached video)
 
 **Note:**
 When removing `setTerrain`, the problem does not occur.

### Expected Behavior
Switching styles with terrain affects the way navigation behaves

### Actual Behavior
Switching styles with terrain should not affect navigation

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue!
The example you provided needs a key.
It would be better to send an example that doesn't need a key, preferably using the demo tiles repo.
While I see the problem in the video we still need a simpler example to test with.

**Comment by DEV-ONI** [comment]
This seems to have been resolved in 3, though I cannot pinpoint why.
Also, could someone point me to where I can find free terrain tiles? The demo terrain tiles do not seem to be complete

**Comment by acalcutt** [comment]
> Also, could someone point me to where I can find free terrain tiles? The demo terrain tiles do not seem to be complete

If you are lucky, google may let you download the TerrainRGB tiles I made from my google drive
https://drive.google.com/drive/folders/1Uo5xyFd8it7UH3pSmBiWP4lfZdM9OmhA 
( jaxa_terrainrgb.mbtiles )
though it is a pretty big file

These were made from GeoTIffs from [JAXA AW3D30](https://www.eorc.jaxa.jp/ALOS/en/dataset/aw3d30/aw3d30_e.htm) using these scripts that use glad and rio rgbify
https://github.com/acalcutt/jaxa_AW3D30_to_MBTiles/blob/main/create_terrainrgb.sh
https://github.com/acalcutt/jaxa_AW3D30_to_MBTiles/blob/main/create_terrainrgb.sh


I have also seen these alternative terrarium tiles out these
https://registry.opendata.aws/terrain-tiles/terrarium

**Comment by HarelM** [comment]
Resolved according to @DEV-ONI
