### ISSUE TITLE
Using text-translate in symbol paint doesn't update collision boxes

### ISSUE THREAD

**Issue by timsluis** [maplibre/maplibre-gl-js#210]
When adding a `text-translate` property to a layer the collision boxes won't move together with the labels. Also click and hovers are registered on the original place of the label before the translate.

<img width="216" alt="Screenshot 2021-07-14 at 11 03 00" src="https://user-images.githubusercontent.com/235880/125595298-d255d130-5dc2-4224-9ec1-c4f14223c62d.png">

**maplibre-gl-js version**: 1.15.2 

**browser**: Chrome 91

### Steps to Trigger Behavior

 1. Add a symbol layer
 2. Provide a `text-translate` on the paint property of a layer

### Link to Demonstration

See: https://codepen.io/timsluis/pen/qBmRYQM

### Expected Behavior

Collision boxes are updated.

### Actual Behavior

Collision boxes are not updated and labels flow over each other.

**Comment by wipfli** [comment]
Wasn't there something related in the terrain3d pull request? @timsluis would you be interested in fixing this?

**Comment by mrflix** [comment]
The bug is still very much there: I'm using both `text-translate` and `icon-translate` to offset symbols so that the pin points to the exact location. I would like to use `icon-offset` and `text-offset` instead, but I can't because I use `text-variable-anchor` and `text-radial-offset` for dynamic label placement and that overwrites `text-offset`.

This is the result of using `text-translate` and `icon-translate`:
![Screenshot 2023-12-21 at 13 47 58](https://github.com/maplibre/maplibre-gl-js/assets/60777/8be799ce-a385-4143-a5ed-5c3c12a444c0)
Outlined in 🟦 is the original position, 🟥 the translated position. The mouseover and click area is 🟦.
So only the bottom right of the visual area can be clicked 😟

**Comment by HarelM** [comment]
Reopening.
I think it's somewhat related to:
- https://github.com/maplibre/maplibre-gl-js/issues/3456

The collision box logic is not great in general...

**Comment by mrflix** [comment]
@kubapelc thanks for looking into this and sharing your work. I tested it with http://kvaleya.gitlab.io/maplibre/aligndemo2/maplibre-gl-dev.js. Unfortunately the labels all move into the top left corner of the canvas:

![Screenshot 2024-03-12 at 11 20 24](https://github.com/maplibre/maplibre-gl-js/assets/60777/97416509-beb7-4d3a-b40d-a05f1817e23d)

These are my layout and paint settings: (I removed some text formatting and styling that I think doesn't influence the position – e.g. text-size, text-font, text-field, text-opacity)
```js
{
  layout: {
    'text-variable-anchor': ['left', 'right', 'bottom', 'top'],
    'text-radial-offset': 1.25,
    'text-optional': true,
    'text-overlap': 'cooperative'
  },
  paint: {
    'text-translate': ["interpolate", ["linear", 1],
      ["zoom"], 8, ["literal", [-2, -1.7]], 17, ["literal", [-20, -17]],
    ],
  }
}
```

**Comment by kubapelc** [comment]
@mrflix Hi, is the bug still present if you use the [maplibre build](https://kvaleya.gitlab.io/maplibre/aligndemo3/maplibre-gl-dev.js) from https://kvaleya.gitlab.io/maplibre/aligndemo3/combineddemo.html ? I had a bug in text-variable-anchor handling that was causing the symbols to be placed in the top left corner, it should now be fixed.

**Comment by mrflix** [comment]
@kubapelc the click areas seem to be correct now but the text is placed incorrectly:
![Screenshot 2024-04-08 at 16 55 06](https://github.com/maplibre/maplibre-gl-js/assets/60777/6b14a107-fb21-4563-b08a-23b7ac75e09b)
How it should be placed: ([live version](https://www.chateauroyalberlin.com/en/art-and-restaurants-guide))
![Screenshot 2024-04-08 at 16 52 32](https://github.com/maplibre/maplibre-gl-js/assets/60777/d9d55a35-8f62-4ce4-b174-deb8aae47a3d)

**Comment by kubapelc** [comment]
@mrflix I fixed another bug with `text-variable-anchor` + `text-translate` interaction: [maplibre build](https://kvaleya.gitlab.io/maplibre/aligndemo4/maplibre-gl-dev.js). This should fix the wrong placement. But I think `text-variable-anchor` + `text-translate` + `text-pitch-alignment: 'map'` will still behave in weird ways, but that doesn't seem to be used in your map.

**Comment by kubapelc** [comment]
I've (hopefully) finished adapting symbols for globe, see the PR mention, and now I'm fairly confident that most reasonable combinations of text, icon, `text/icon-translate`, `text/icon-translate-anchor`, `text-variable-anchor`, `text-pitch-alignment`, `text-rotation-alignment` should work, along with proper collisions and click areas. If you want to try it out, see here:

[Globe demo](https://kvaleya.gitlab.io/maplibre/globe/globedemo.html)

[MapLibre build used in globe demo](https://kvaleya.gitlab.io/maplibre/globe/maplibre-gl.js) (different build than was is linked in the previous comment).
