### ISSUE TITLE
Select feature from custom style layer.

### ISSUE THREAD

**Issue by userVF** [maplibre/maplibre-gl-js#2100]
Hi All!

The question about ability to select feature that drawn directly via `shaders` as in the [example](https://maplibre.org/maplibre-gl-js-docs/example/custom-style-layer/) and get some property value from that feature.
I.e:
```
map.on('click', 'custom_style_layer', function(e) {  
    console.log(e.features[0]['some_property'])
})
```
Is there way to do it?

**Comment by HarelM** [comment]
Is this an actual issue? A feature request?
I think this should start as a discussion, and if you find something that is not working as expected or needs improvement then an issue is the right approach, but it's not clear from the above description.

**Comment by userVF** [comment]
Thanks for reply.
Of course, it's discussion topic rather than actual issue.

**Comment by HarelM** [comment]
Moved to #2105
