### ISSUE TITLE
(Windows only) three render tests failed

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#2102]
<code>npm run test-render -- --report</code> on windows 10. Total of 3 failure and two of them are cosmetic. "tests/debug/tile-raster" does appear to be a real bug.

See full report:
https://samplecodes.blob.core.windows.net/samplecodes/2023-01-26-rendertest-win10-results.html

(Side note: is there a way to use HTML as attachment so dont have to host it outside of GitHub?)

**Comment by HarelM** [comment]
The images are base64 encoded so the html file is self sufficient, you can simply change the extension to txt and upload the file here.
Didn't the tests used to compete successfully on Windows not too long ago.
I think there might be a need to add another step to run the render tests on Windows as party of the CI to avoid this.
Feel free to submit a PR to fix the tests and add a CI run.

**Comment by zhangyiatmicrosoft** [comment]
Upon deeper look, actually all 3 failures are legit --- hover over and leave will see the font size changes.
They might not be test-framework issues but real bugs on windows.

Since majority of end users are on Windows, CI and primary dev environments should be Windows as well.

**Comment by HarelM** [comment]
I strongly disagree about the last statement. CI should run **also** on Windows, primary dev is moving away from Windows in all the industry.
Companies that take their developers seriously give them macs, Windows is working hard to make wsl a first citizen, and these are just small examples.
But this is besides the point here, we should make sure CI runs in all major dev platforms.
Having said that, render test are running on node env and not in the browser, so this completely misses the point, in theory, but it runs fast.
I would advise to simply use wsl on Windows when developing any thing related to npm (including maplibre), the difference in the time it takes to do the small operations is a lot. We have benched marked it in my company and saw a huge benefit.

**Comment by zhangyiatmicrosoft** [comment]
Actually CI executes render tests in xvfb, another level of virtualization, getting even further from real consumer browsers.

**Comment by wipfli** [comment]
Windows, macos, linux are all widely used it seems. https://survey.stackoverflow.co/2022/#section-most-popular-technologies-operating-system

**Comment by rotu** [comment]
I don't know that xvfb is the problem here. But I'd definitely feel better about the render tests if they ran in actual Chromium and Firefox rather than headless-gl.

**Comment by zhangyiatmicrosoft** [comment]
> I don't know that xvfb is the problem here. But I'd definitely feel better about the render tests if they ran in actual Chromium and Firefox rather than headless-gl.

Absolutely agree.  js-dom/node-canvas/gl and finally xvfb, how many layers of simulations. :)
In this case node-canvas did have a bug and somehow shielded away on CI by xvfb, and just revealed on windows. See
https://github.com/Automattic/node-canvas/commit/4c276e07f570ee6a727f88dcc67251823895c671
Test of the fix: #2139

two options: 
1) Dont do anything now. Wait for the next release of canvas and enable windows render test in CI
2) merge 2138 and enable windows render test in CI now.

Suggestions?

**Comment by HarelM** [comment]
I prefer to add Windows and not wait for a version to come out...

**Comment by zhangyiatmicrosoft** [comment]
awesome. Thank you please merge 2139.
