### ISSUE TITLE
Browser tests should be using screenshots / snapshots

### ISSUE THREAD

**Issue by rotu** [maplibre/maplibre-gl-js#2129]
## Motivation

The browser tests currently use verbose snapshot code. This does not integrate well with test-runners and makes adding new tests more daunting than it should be.

E.g. the following should be a single-line assertion:

https://github.com/maplibre/maplibre-gl-js/blob/8571571fb4cedfecc678e3dfe4ebf28a04d20684/test/integration/browser/browser.test.ts#L167-L188

Additionally, it would be nice to move the render tests to a test runner that integrates better with CI and IDE workflows.

## Design Alternatives

It would be nice to use one of the following libraries to compare screenshots:

- https://playwright.dev/docs/test-snapshots
- https://www.npmjs.com/package/jest-screenshot
- https://github.com/americanexpress/jest-image-snapshot

If we use the Playwright `expect(page).toHaveScreenshot()`, it requires launching the tests with the Playwright test runner instead of the Jest test runner.

If we use the Jest `expect(await page.screenshot()).toMatchImageSnapshot()`, the snapshot locations may not be as configurable as we like (in general, the location of the file is based on the path to the `*.test.js` file.

**Comment by HarelM** [comment]
We can also consider cypress

**Comment by rotu** [comment]
Fwiw the playwright runner presents some incompatibilities with how it handles Typescript and ESM - but it would be nice if we could use its snapshot and multi-browser configuration from within the Jest runner.

**Comment by birkskyum** [comment]
@rotu , do you think puppeteer would be more compatible here? Puppeteer's strategy is to stay Jest compatible, whereas Playwright mainly support their own playwright/test

**Comment by rotu** [comment]
@birkskyum I really don’t care what framework we use as long as the code is easier to understand and run.
