### ISSUE TITLE
Build test and windows variation has been deleted 

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#2138]
@rotu @HarelM #2044 just removed all build tests from CI as well as my work in #2125 

Please correct it? Thanks

**Comment by rotu** [comment]
I saw your PR and I thought I merged it correctly:
https://github.com/maplibre/maplibre-gl-js/actions/runs/4087918421/jobs/7048998185

**Comment by zhangyiatmicrosoft** [comment]
Oh nvm... found it. Sorry for the false alarm.

**Comment by rotu** [comment]
Sorry for worrying you! One of my big motivators here was simplifying what you see when a PR is launched. It should be *much* easier to add Windows to the build matrix for various jobs now!

If there's any way to make the CI even easier to interpret, I'm for it!
