### ISSUE TITLE
If both ‘line-pattern’ and 'line-color' are set, they will not take effect

### ISSUE THREAD

**Issue by Yuki-Zhao** [maplibre/maplibre-gl-js#2158]
https://codesandbox.io/s/amazing-boyd-6yv6p3?file=/index.html

**Comment by HarelM** [comment]
Can you clarify what is the expected vs actual outcome?
For me, this seems reasonable that they don't work together as one is an image and the other is  plain color...

**Comment by Yuki-Zhao** [comment]
I want to fill the line with symbols and allow it to change colors。For example, i can fill a line with a train track symbol, but i want to support the color that the line energy symbol fills。

symbol layer，If both ‘icon-image’ and 'icon-color' are set, they will take effect。https://codesandbox.io/s/distracted-sara-8151ef?file=/index.html。

**Comment by HarelM** [comment]
You can use symbol with placement line to show symbols on a line, can't you?

**Comment by Yuki-Zhao** [comment]
The symbol will not fit the line.
The white area is what I look forward to.  https://codesandbox.io/s/currying-http-t1rd21

**Comment by laofan1ku** [comment]
> 我建议将其分解成 3 个图标 - 圆圈、“>”和“<”，并在所有这些图标下方规划一条线。不确定它会解决问题，但它可能会有所 帮助 ...... SDF 图标将允许您设置符号的颜色以配线。 以下是我网站上的一些示例： ![图片](https://user-images.githubusercontent.com/3269297/218089966-67758c5f-03c3-4b18-8bf6-e675e9db0fc3.png) ![图片](https://user-images.githubusercontent.com/3269297/218090063-779b9f4e-87c2-4a48-b903-3f60d4111759.png)
where are your site?  Could you show me a demo?

**Comment by HarelM** [comment]
Https://Israelhiking.osm.org.il/

**Comment by laofan1ku** [comment]
Does the left navigation line consist of symbolLayer and lineLayer ?

**Comment by HarelM** [comment]
https://github.com/IsraelHikingMap/Site/blob/0c8ed983fdcd821943accdc6b8a10e94f3d291a2/IsraelHiking.Web/src/application/components/map/layers-view.component.html#L71L115

**Comment by laofan1ku** [comment]
thanks, Same as I think.

**Comment by HarelM** [comment]
Seems like this was solved.
Closing.
If this is not the case please let me know and I'll re-open.
