### ISSUE TITLE
[Typescript] Remove access token and telemetry

### ISSUE THREAD

**Issue by turtle0x1** [maplibre/maplibre-gl-js#216]
**maplibre-gl-js version**:^1.14.0

**browser**: any

### Steps to Trigger Behavior

 1. Init a map with `accessToken: 'no-token'`
 3. See a HTTP request to mapbox servers

### Expected Behavior
Setting is ignored and HTTP call to mapbox servers never happens.

Thanks for setting up this fork, your timing couldn't be better & its appreciated.

This is probably a duplicate of a wider issue but all HTTP calls to mapbox should be removed ASAP as it an "information leak" to some extent.

**Comment by HarelM** [comment]
Thanks for taking the time to open this issue.
We are planning on removing the access token from the code, which I believe should solve this, right?
This will happen in version 2.0 I guess...

**Comment by turtle0x1** [comment]
Hey, ill be honest - I paid 0 attention when adding mapbox-gl or maplibre to my project.

Removing the `accessToken` code should do it (or at least it is if the dev follows it all the way down)

Whenever you get round to it - I get it, im not sponsoring it - removing the access token is enough to stop HTTP calls. (but thats the same as mapbox - i teseted that much before I opended)

Feel free to close this issue if its noise :smile:

**Comment by HarelM** [comment]
I've changed the name of this issue to better define the requirements.
I'll be addressing this in my next PR.

**Comment by stevage** [comment]
Wait, I don't really understand the rationale for removing `accessToken`. This means that any `mapbox://` URLs stop working? And the only way to use Mapbox styles is to manually embed the access token in a full url, sometihng like:

```
style: "https://api.mapbox.com/styles/v1/user/mystyleid/?access_token=pk.eymykeyhere"
```

is that right? Why is this necessary?

**Comment by HarelM** [comment]
There are two aspects of this PR:
1. Telemetry - current library before this change sends usage statistics to mapbox. I don't think I need to clarify how wrong that is.
2. Usage of mapbox API and data with a token - if you are using mapbox data you should use their product and pay them, they deserve it for their hard work, also see #41 for info on why. I'll continue this thread in the breaking change discussion with your permission.

**Comment by stevage** [comment]
Yeah, of course getting rid of the Mapbox telemetry code.

(I don't think you need my permission to continue a discussion elsewhere, feel free...)

**Comment by HarelM** [comment]
I'm just being polite :-) The relevant discussion can be seen here: https://github.com/maplibre/maplibre-gl-js/discussions/290
