### ISSUE TITLE
[BUG] ImageManager fails to populate callback when styleimagemissing populates an image

### ISSUE THREAD

**Issue by ZeLonewolf** [maplibre/maplibre-gl-js#2164]
While troubleshooting the fix for #2159, I discovered a bug in ImageManager._notify(), which is responsible for retrieving images from the image manager.

ImageManager uses the following algorithm:
1. Attempt to retrieve an image and save the result
2. If the image is not present, fire a '[styleimagemissing](https://maplibre.org/maplibre-gl-js-docs/example/add-image-missing-generated/)' event and log a warning.
3. Send the saved image to the caller as a callback

However, it is possible that the handler for `styleimagemissing` has invoked map.addImage() to add the missing image.

In this case, the algorithm does two incorrect things:

1. A warning is incorrectly written to the console indicating that an image could not be loaded, even though it was loaded by the `styleimagemissing` handler
2. A `null` is returned to the caller instead of the newly-loaded image.

This logic is below:

https://github.com/maplibre/maplibre-gl-js/blob/98f17bfccca46ac7b30cf896973c8ad7ee92b566/src/render/image_manager.ts#L199-L224

### Proposed fix

Proposed is that the algorithm change to:
1. Attempt to retrieve an image and save the result
2. If the image is not present, fire a '[styleimagemissing](https://maplibre.org/maplibre-gl-js-docs/example/add-image-missing-generated/)' event
3. If `styleimagemissing` has generated the requested image, save the result, otherwise log a warning
4. Send the saved image to the caller as a callback

### Impact if not fixed

1. For implementations that invoke addImage() in the `styleimagemissing` handler, the first instance of a newly-requested image will return a null instead of the requested image, while the second and subsequent instances will return normally. The impact on the map will depend on how the client handles null images. In testing I've observed garbled buffer data drawn to the map where I expect an image to appear.
2. Incorrect warnings are written to the console.

**Comment by 1ec5** [comment]
Previously reported in https://github.com/mapbox/mapbox-gl-js/issues/6231#issuecomment-500473919.
