### ISSUE TITLE
MapLibreGl loading

### ISSUE THREAD

**Issue by ltoshev** [maplibre/maplibre-gl-js#217]
Hi

I load the maplibre dynamically based on whether the page on my site has a map or not.

getContent("https://unpkg.com/maplibre-gl@1.14.0/dist/maplibre-gl.css", function (code1) {
                        console.log('css libre loaded');
                        var s = document.createElement('link');
                        s.type = 'text/css';
                        s.rel = "stylesheet";
                        s.innerHTML = code1;
                        var x = document.getElementsByTagName('script')[0];
                        x.parentNode.insertBefore(s, x);

                        getContent("https://unpkg.com/maplibre-gl@1.14.0/dist/maplibre-gl.js", function (code) {
                            debugger;
                            console.log('js libre loaded');
                            var s = document.createElement('script');
                            s.type = 'text/javascript';
                            s.innerHTML = code;
                            var x = document.getElementsByTagName('script')[0];
                            x.parentNode.insertBefore(s, x);
                            $this.isInit = true;
                            $this.startInit = false;
                            deferred.resolve(true);
                        });
                    });

After the deferred is resolved, I try to access the window.maplibregl and the lib is not defined. What is wrong with it?

The scripts load and are available on the page, as seen in network. Why the global is not define after that moment?

**Comment by HarelM** [comment]
It had changed in recent versions.
Can you check if `mapboxgl` variable is working on that example?

**Comment by ltoshev** [comment]
I've tried maplibregl as defined here in the sample: https://maplibre.org/maplibre-gl-js-docs/api/

mapboxgl is neither defined. I tried with the version given in the above link i.e. 1.15.2

**Comment by ltoshev** [comment]
Here is a screenshot:

![image](https://user-images.githubusercontent.com/1788597/126642936-86011ea5-7070-4bf0-81d1-dece55057637.png)

I am following the Amazon Location Services tutorial to get the map going with ALS.

**Comment by HarelM** [comment]
Sorry, I don't know how to help you with this... :-(
I'm using angular and loading this through npm and webpack...
Not sure what getcontext does and if it returns a text or binary or what, and if the browser doesn't block this external script added in the body...
Maybe `eval(code)` is the right way to load the code...?
You'll need to play around with it I guess... Sorry...

**Comment by wipfli** [comment]
Thanks for looking into MapLibre GL JS. I think you should make an example on codepen, write a question on stackoverflow and post a link to it in the slack channel.
