### ISSUE TITLE
Marker moves when zooming

### ISSUE THREAD

**Issue by jedgar1mx** [maplibre/maplibre-gl-js#2190]
**maplibre-gl-js version**: 2.4.0

**browser**: Firefox, Chrome

### Steps to Trigger Behavior

 1. Create map
 2. Add marker
 3. Zoom in and out

### Link to Demonstration
https://youtube.com/shorts/AIF7YqqSS1s?feature=share

### Expected Behavior
Marker should stick to the correct coordinates despite of the zoom level.
### Actual Behavior
Marker moves out of place during zooming.

**Comment by jedgar1mx** [comment]
Look like a point layer doesn't have this issue so it's weird that it only happens with marker.

**Comment by acalcutt** [comment]
Can you provide an example, like a stackblitz/codepen page?

Looking at https://maplibre.org/maplibre-gl-js-docs/example/add-a-marker/ it seems like it uses 2.4.0 and sets a marker, but it doesn't seem to have the same issue. I also tried the codepen example on that page and it seems to work there.

**Comment by jedgar1mx** [comment]
Quick update, it looks like I was missing some styles. I had issues loading the full style sheet inside the `shadowRoot` of my `customeElement` so I had to split it and it looks like I missed some.

**Comment by ferdicus** [comment]
if anyone should encounter the same issue and can't compute the cryptic messages in this ticket:
make sure to follow the installation steps and not only include the JS part but also the CSS one 👍🏿

**Comment by basarozcan** [comment]
Anyone who needs long story short:

If you have the same issue, you should be sure, imported the default css file of maplibregl. When I wrote that it can be imported  like below:
`<link rel='stylesheet' href='https://unpkg.com/maplibre-gl@5.2.0/dist/maplibre-gl.css' />`

Information about importing maplibrgle correctly is here:
[Map Libre GL Docs](https://maplibre.org/maplibre-gl-js/docs/)
