### ISSUE TITLE
Use @maplibre/maplibre-gl-style-spec in MapLibre GL JS

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#2194]
Make maplibre-gl-js use the style-spec through the published style-spec npm package instead of references files in the nested subdirectory.

- Point all references to style-spec towards the [npm package ](https://www.npmjs.com/package/@maplibre/maplibre-gl-style-spec)
- It might be necessary to expose additional private apis from if there are classes that can be reached form the repo but not the style-spec package

This will make it easier to migrate the style spec later on.

**Comment by HarelM** [comment]
Link to bounty:
https://github.com/maplibre/maplibre/issues/191

**Comment by birkskyum** [comment]
Here are two things that has to happen:

The style-spec actually use: import type {CanonicalTileID} from ‘src/source/tile_id’; which is part of maplibre-gl-js. If we aim to not have style-spec depend on maplibre-gl-js, something has to change here. Example here: https://github.com/maplibre/maplibre-gl-js/blob/9d107a5f5651b6adfa49a87419dc7648a57249da/src/style-spec/expression/evaluation_context.ts#L4

A new version of /src/style-spec should be made so that the style-spec npm package is in sync. A “minor” release is probably the right semver, because the directory contain unpublished features such changes such as https://github.com/maplibre/maplibre-gl-js/pull/1805

**Comment by HarelM** [comment]
Importing a type (assuming this is only what we do) means we only import the definition.
If this class is a util class used by this library, it should probably be defined in style-spec, if only the type is being used we can create an interface and use that, in theory. We can also convert the functions in this class to static methods - functional programming style.
Bottom line, we need to better understand how and why it is used.

**Comment by birkskyum** [comment]
This is used throughout the style-spec. If we entertain the idea of having interfaces, in practice it would mean including the following in style-spec, and them importing and implementing them in gl-js:

```ts
export interface ICanonicalTileID {
    equals(id: ICanonicalTileID): {};
    url(urls: Array<string>, pixelRatio: number, scheme: string | null): {};
    isChildOf(parent: ICanonicalTileID): {};
    getTilePoint(coord: IMercatorCoordinate): {};
    toString(): {};
}

export interface IMercatorCoordinate {
    fromLngLat(lngLatLike: ILngLatLike, altitude: number): {};
    toLngLat(): {};
    toAltitude(): {};
    meterInMercatorCoordinateUnits(): {};
}

export type ILngLatLike = ILngLat | {
    lng: number;
    lat: number;
} | {
    lon: number;
    lat: number;
} | [number, number];

export interface ILngLat {
    wrap(): {};
    toArray(): {};
    toString(): {};
    distanceTo(lngLat: ILngLat): {};
    convert(input: ILngLatLike): ILngLat;
}
```

**Comment by birkskyum** [comment]
OpenCollective: https://opencollective.com/maplibre/expenses/132829
