### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by majdal** [maplibre/maplibre-gl-js#220]
## Motivation

Currently, languages that use a right-to-left script, such as Arabic and Hebrew, are rendered left-to-right. This is a classic problem (see [notarabic.com](https://www.notarabic.com/)), but it would be heartening if the commitment to Libre also included a commitment to inclusive design.

## Design Alternatives

[Mapbox-gl-rtl-text](https://github.com/mapbox/mapbox-gl-rtl-text/) has an (incomplete) fix to this issue. It works well for the default fonts, but breaks when using custom fonts. 

I don't have the technical skills to think of specific implementation solutions, but I'm happy to discuss and help conceptualizing it with whomever would be able to help.

**Comment by lseelenbinder** [comment]
I would definitely like to see the RTL plugin be included by default (or some other variant), but I haven't looked into it deeper.

Could you elaborate about how it breaks?

**Comment by HarelM** [comment]
I'm using Hebrew for a long time with mapbox and now with maplibre.
I admit I'm not using custom fonts, but I'm not sure what that means exactly...
The RTL plugin is a port of intl, I think, and I'm not even sure how easy it is to change it.
Please provide a minimal example using jsbin/codepen/stackblitz so we can better understand what the issue is.

As a side note, I don't think the first paragraph is in place, especially without checking who's maintaining this library first... As a Hebrew speaker, code writer and site owner I can't say I wasn't offended a bit... :-(

**Comment by majdal** [comment]
Thanks for the quick responses! 

Here's a quick very basic example: https://codepen.io/majdal/pen/jOmGjVq

All the place labels are rendered left to right. For example, Damascus, which should be written as دمشق is rendered as ق ش د م, making it basically completely illegible. The screenshot below shows it. 

Fixing this is already a win. As for the custom fonts, I'll have to dig a bit further into how Mapbox Studio serves the fonts, because previously I had only used it through the GUI. It seems like I might have to play with the [glyphs](https://maplibre.org/maplibre-gl-js-docs/style-spec/glyphs/) style specification? But to demonstrate, I'm using the libre font [Cairo](https://fonts.google.com/specimen/Cairo?subset=arabic) to render the labels in the second screenshot (from Mapbox Studio). The word القدس (Jerusalem) has three segments in Arabic. The first and last segment are rendered in the default font, while the middle segment is rendered with the Cairo custom font. 

![broken rendering](https://user-images.githubusercontent.com/360058/126716154-41733738-6559-4ad5-b157-bd653e61db80.png)
![custom font](https://user-images.githubusercontent.com/360058/126717462-377baab1-9c57-4838-951a-1174cecf7f88.png)

P.S. Funnily enough, Github is rendering the above two paragraphs that contain bidirectional content as right-to-left, even though they're mostly left-to-right. A small window into what the web feels like to RTL language speakers 😅

**Comment by HarelM** [comment]
I haven't seen the usage of mapbox-gl-rtl-text
In the above example.
While I agree this is not optimal that this is not part of this library by default, there's still an easy fix to the problem above...
Please update the codepen and let me know if there's other issues you encounter.

**Comment by HarelM** [comment]
Any updates on this? Can I close this issue?

**Comment by majdal** [comment]
Hi Harel - Please don't close the issue. I'll update the example ASAP.

**Comment by yeegor-restrata** [comment]
@HarelM this issue still persists. Hebrew text is rendered in a wrong direction, even with the default font!
See an example here: https://jsfiddle.net/a1er8uhy/1/
Greece, for example, should be יוון, but it's rendered as ןווי.

**Comment by HarelM** [comment]
@yeegor-restrata not reading the documentation is the issue here, not the code, sorry... You need to add the RTL plugin and use a font with Hebrew characters.
Here's a live example of this working, I assure you Hebrew is supported.
https://israelhiking.osm.org.il/
