### ISSUE TITLE
LngLat class toArray method return type

### ISSUE THREAD

**Issue by maxdacruz** [maplibre/maplibre-gl-js#2233]
The toArray method on the class LngLat should return an [number,number] type instead of the number[] to stay consistent with the doc and the LngLatLike type which only accepts a [number,number] type.

**Comment by HarelM** [comment]
Sounds right, can you open a PR to fix this?

**Comment by maxdacruz** [comment]
Will do should be done by the end of the week.

**Comment by HarelM** [comment]
Fixed by #2234
