### ISSUE TITLE
Momentum scrolling seems instant on MacOS with reduced motion

### ISSUE THREAD

**Issue by joepio** [maplibre/maplibre-gl-js#2238]
**maplibre-gl-js version**: 2.4.0 (also [posted this on MapBoxGL](https://github.com/mapbox/mapbox-gl-js/issues/12602))

**browser**: Chrome, safari (on MacOS)

### Steps to Trigger Behavior

1. Turn on reduced motion on macOS accessibility settings
 1. Open a map on MacOS (e.g. https://maplibre.org/)
 2. Drag over the map with the mouse, let go while making the dragging motion (don't wait with letting go until movement has stopped)
 3. You will see the map skips over an area, dependent on your speed (see video below)

### Link to Demonstration

Note how the map instantly teleports to a new location when the cursor changes from 'dragging' to 'normal'.

https://user-images.githubusercontent.com/2183313/222200309-4769a50b-d649-4a4b-bdf7-bd73c2c4d901.mov

### Expected Behavior

There are two ways dragging and letting go while having momentum should work:

1. Freeze the position when the mouse button is let go. 
2. Momentum scrolling, even when reduced motion is on.

### Actual Behavior

Map 'teleports' to position further then where the mouse is let go. I suspect that it instantly teleports to the calculated 'momentum' position (where it should come to a stop), but the animation is 0ms long. But this is just a guess coming from someone who doesn't know the internals of course.

**Comment by HarelM** [comment]
I don't think maplibre has versions 2.12, 2.13...
Can you clarify the following please:
"Turn on reduced motion on macOS accessibility settings"?
Can this be tested using the following media query?
https://a11y-101.com/development/reduced-motion#:~:text=On%20a%20Mac%20you%20go,turn%20on%22Reduce%20Motion%22.

**Comment by joepio** [comment]
@HarelM 

> I don't think maplibre has versions 2.12, 2.13...

You're right, it's the latest version (if that's the one on maplibre.org).

> Can you clarify the following please: "Turn on reduced motion on macOS accessibility settings"?

On a mac, go to accessibility settings, then to `display` then tick `reduce motion`

> Can this be tested using the following media query?

And not sure what you mean with can this be tested?

Anyways, I'm pretty sure this is the culprit: https://github.com/maplibre/maplibre-gl-js/blob/04ea214c92518c8245fcc2552bd0da8b3cde9d3c/src/ui/camera.ts#L1098

**Comment by HarelM** [comment]
You're probably right, feel free to sumbit a PR that fixes this if you have a good to solve this.

**Comment by HarelM** [comment]
Fixed by #3068.
