### ISSUE TITLE
bugs and improvement areas of PerformanceUtils 

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#2256]
We are conducting very thorough perf evaluations especially for initial loading time and FPS and found that PerformanceUtils (https://github.com/maplibre/maplibre-gl-js/blob/main/src/util/performance.ts) has the following bugs and areas to improve:

1) minor: each time getPerformanceMetrics() is called Line 45 and 46 add measures but line 47,48 only retrieve the first set of measures anyway.
2) medium: line 19, the target fps is 30 from several years ago, should consider update to 60 per modern FPS standard.
3) big bug: getPerformanceMetrics is only meaningful for the first time loading before any other map interactions. Reason: variable <code>lastFrameTime</code> is not reset between different "round of renderings". Consider the following case:
- users load the map, wait several seconds and zoom/pan
- line 29 <code>currTimestamp - lastFrameTime</code> generates a very large bogus number, which messes up fps and dropped frame calculations after.

Propose immediate fix:
- fix 1 and 2
- add totalFrame counter to the output

Any idea how to reset the numbers for "round of rendering" and address 3?

**Comment by HarelM** [comment]
you can use `clearMetrics` to clear stuff - if I read this file it looks like the intended usage is for a single measurement (i.e. not do stuff in parallel), am I missing anything?

**Comment by HarelM** [comment]
Can you share part of the code you are using to do the measurements?

**Comment by zhangyiatmicrosoft** [comment]
For example, it takes 10 Map._render calls (each has its own frame) to reach to the inital "fullLoad".
At the 10th frame, we marked _loaded and  _fullyLoaded as true. Everybody happy.
In PerformanceUtils, lastFrameTime is marked at this frame10.

5 seconds later, user start panning.

In the 11th frame (first frame of the panning), this code is stateless, it does not know it is the "first of this round or interactions", so cannot perform any reset, so line 29 produces a very large number, messing up all FPS calculations afterwards:
<code>currTimestamp - lastFrameTime</code>

Yes like you said we need call <code>clearMetrics</code>, but where?
Other than initial load, each frame is stateless, does not know what happened before and what's going to happen next.

**Comment by zhangyiatmicrosoft** [comment]
Elaborate on "frame is stateless" -- Map.triggerRepaint generates a frame, other than manual, two primary sources of this call
- A sub frame from _render, in that the previous frame determines it did not finish rendering and still "something dirty"
- A new frame originated by update -> triggerRepaint. This can came from tens of places, and not predictable.

To finish one user action (pan) or one programming call (data change), a set of frames with random mix of these two will be needed. 
I have yet to find a way within the frame to know whether it is the first or last --- therefore I think they are all stateless.

**Comment by HarelM** [comment]
What about calling clear and get according to events? touchstart, dragstart, moveend, idle? Does that not work as well?

**Comment by HarelM** [comment]
I believe this was fixed by #2295.
If there are more things to solve please separate to different issues or simply open the relevant PRs.
