### ISSUE TITLE
DoubleClick/DoubleTap zooms don't disable

### ISSUE THREAD

**Issue by zta6** [maplibre/maplibre-gl-js#2259]
**maplibre-gl-js version**: 2.4.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. map.doubleClickZoom.disable(), map.doubleClickZoom.isEnabled() returns false
 2. double click the map. See that it still zooms
 3. map.doubleClickZoom.isEnabled() returns true. Double clicking re-enables the double click zoom action. 

### Expected Behavior
Double Click Zoom is disabled when `disable()` is called

### Actual Behavior
Double click zoom is not disabled. 

There is a mapbox bug for this: https://github.com/mapbox/mapbox-gl-draw/issues/691

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue!
Can you please add a jsbin/stackblitz/codepen reproduction?

**Comment by Chaitu-Tatipamula** [comment]
can i work on this

**Comment by HarelM** [comment]
Sure! Go ahead!

**Comment by zta6** [comment]
For reference it looks like this PR: https://github.com/mapbox/mapbox-gl-draw/pull/696
is the one that fixed the mapbox bug.

**Comment by zta6** [comment]
this may be the source: https://github.com/mapbox/mapbox-gl-draw/blob/main/src/modes/simple_select.js#L137 ??

**Comment by HarelM** [comment]
If this is still relevant I'll be happy to reopen this issue.
Closing for now.

**Comment by cckolon** [comment]
I'm still seeing this in `mapbox-gl` v 3.2.0 and with `mapbox-gl-draw` v 1.4.3. Disabling double click zoom works without the draw component, but fails with the draw component added. Disabling on load worked in my case, but this is still definitely an issue.
