### ISSUE TITLE
Transparent polygons overdraw at higher zooms levels.

### ISSUE THREAD

**Issue by smcallis** [maplibre/maplibre-gl-js#2281]
I'm running on top of maplibre-gl@latest, so 2.4.0, and I've got a problem I just can't seem to fix.  I've got some polygons I'm drawing transparently.  It seems like maplibre overdraws them as I zoom in though.  You can see this here:

Before:
![image](https://user-images.githubusercontent.com/804394/225773166-64e22905-eb1c-4a66-bc6e-aa706c4e7007.png)

Zoom in one level:
![image](https://user-images.githubusercontent.com/804394/225773144-9e26e362-725f-4ee1-bfaa-d48862d54456.png)

I'm clipping my polygons to the tile extents, and I've got debug statements that indicate I'm not producing any vertices that are outside the tile extents, so I'm not sure where this is coming from unless it's drawing on top of the parent tile for some reason, but it only does it sometimes.   I'm pretty stumped.

**Comment by HarelM** [comment]
Please provide a minimal reproduction scenario in jsbin/codepen/stackblitz to showcase the issue.

**Comment by smcallis** [comment]
Yeah I don't see any way to hardcode a tile into the javascript, it wants a url to query which I can't give it.  I'm attaching the two tiles shows overlapping in the picture if that helps at all.
[tile_4_5_8.mvt.gz](https://github.com/maplibre/maplibre-gl-js/files/11051968/tile_4_5_8.mvt.gz)
[tile_5_11_16.mvt.gz](https://github.com/maplibre/maplibre-gl-js/files/11051969/tile_5_11_16.mvt.gz)

**Comment by HarelM** [comment]
You can probably use `addProtocol` for that?
You can try to reproduce this in the tests in the repo, we have some tiles as assets in the tests folder, and we use them in the render tests.
If you could create a branch that can reproduce this issue in a test it would be very helpful to try and solve...
You can also maybe host these tiles in a github repo...?

**Comment by smcallis** [comment]
Thanks for the tip on `addProtocol`, that worked well but I had to play some shenanigans gzipping+base64 encoding my data to get it crammed in there.  Regardless, I got it working: https://jsbin.com/kanujacage/2  I only needed the one tile to show the rendering glitch I'm seeing.

**Comment by HarelM** [comment]
I'm not 100% sure, but I have the feeling this is the same bug as the following: #1830
I think the shape at the lower left corner is intersecting itself and this is why you get this issue.
While I agree the linked bug should be solved I think you should be able to overcome this by making sure the data is "valid".

**Comment by smcallis** [comment]
I ran [vtvalidate](https://github.com/mapbox/vtvalidate) on it and it didn't return any errors.  I'll break out the geometry manually and check that it doesn't overlap.  The squares are [S2](https://s2geometry.io/) cells so they shouldn't overlap, but I've been wrong before :grin:

**Comment by smcallis** [comment]
Ugh I figured out what it was, I had a bug that was inserting the same polygon multiple times, whoops.  Thanks for helping me track it down at any rate =D
