### ISSUE TITLE
Use default mouse cursor for buttons

### ISSUE THREAD

**Issue by zdila** [maplibre/maplibre-gl-js#2320]
Controls (eg. zoom control) uses `cursor: pointer` on buttons. Instead default (arrow) cursor should be used there. According to W3C the pointer cursor should only be used for links. 

See eg. https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default/105027#105027

**Comment by benesg** [comment]
W3C says that the pointer should only be used on links, but I disagree.

Almost every site uses `cursor: pointer` to indicate some sort of interaction. If you look at GitHub, the "Comment" or "Star" buttons as well the controls to format the text (bold, italic etc.) use it, even though those are not links.

In my opinion, it's generally known and accepted that this indicates some sort of interaction. I even think some users may wonder if they can click the button if it doesn't have `cursor: pointer`.

**Comment by HarelM** [comment]
This can be easily overwritten using css, so I think I'll leave it to the developers to decide the required behavior...
