### ISSUE TITLE
The ::marker is visible in my <div>, what is it and how to get rid of it?

### ISSUE THREAD

**Issue by J4gQBqqR** [maplibre/maplibre-gl-js#2323]
![图片](https://user-images.githubusercontent.com/77554817/229259396-24480f11-7d51-44d6-a340-c281723921ab.png)
![图片](https://user-images.githubusercontent.com/77554817/229259436-e5007a54-816f-4d14-84af-b59cb1f98d06.png)

I am injecting the map using the "id" attribute of an `<figure>` element. There is an extra marker showing up in my flex row beside the map, what is this? Is this behavior expected?

Thanks for your help.

**Comment by HarelM** [comment]
Please share a jsbin/codepen/stackblitz

**Comment by J4gQBqqR** [comment]
I figured out this is because I missed adding the href in stylesheet html header.
