### ISSUE TITLE
Can we set priority to the POI label (point of interest)?  To display labels & icon for selected or rendered POI's?

### ISSUE THREAD

**Issue by satya-auti** [maplibre/maplibre-gl-js#2343]
Can we set priority to the POI label (point of interest)?  To display labels for selected or rendered POI's?

I have show the stable POI label on map. Once the poi is display on the map after a specific zoom then it needs to be stable till the last zoom (max zoom).

Is this possible using maplibre-gl-js?

**Comment by HarelM** [comment]
You can draw a label/poi on top of the existing ones I think. Not sure I fully understand the question here.
