### ISSUE TITLE
Deprecated stylelint rules

### ISSUE THREAD

**Issue by rotu** [maplibre/maplibre-gl-js#2351]
We're using stylelint rules that [have been deprecated](https://github.com/stylelint/stylelint/pull/6504) in favor of Prettier.
This causes visible warnings at build time

e.g. https://github.com/maplibre/maplibre-gl-js/actions/runs/4609553050/jobs/8146841553#step:6:10

> > stylelint src/css/maplibre-gl.css
> 
> Deprecation warnings:
>  - The "block-opening-brace-space-before" rule is deprecated.
>  - The "declaration-block-semicolon-newline-after" rule is deprecated.
>  - The "indentation" rule is deprecated.

**Comment by HarelM** [comment]
I think this was resolved. Feel free to update this issue if this is not the case.
