### ISSUE TITLE
GeolocationControl._setupUI crashes when used with react-map-gl and mapStyle fails to load

### ISSUE THREAD

**Issue by bgeihsgt** [maplibre/maplibre-gl-js#2357]
Please note that we don't have a consistent repro for this, but we have seen this crash occur in our production error logging.

**maplibre-gl-js version**: 2.4.0

**browser**: Safari/Mobile Safari

### Steps to Trigger Behavior

 1.  Use `react-map-gl` version `7.0.21`
 2.  In Safari, hit a case where mapStyle fails to fetch. In our case, we're using api.maptiler.com
 

### Link to Demonstration

We don't have a live demonstration because it requires a specific intermittent failure mode. But here is what we're seeing:

Our error log crashes with:

```
UnhandledPromiseRejectionWarning: TypeError: undefined is not an object (evaluating 'this._map._getUIString')
```

This is happening inside `_setupUI` within `GeolocateControl`. (Our code uses a structure like `<Map><GeolocateControl /></Map>` ). Each error log we see is accompanied by a failure to load the api.maptiler.com map style JSON.

In inspecting through the `react-map-gl` code, I noticed this code snippet:

https://github.com/visgl/react-map-gl/blob/v7.0.21/src/components/geolocate-control.ts#L80-L85

It looks like this is firing, but `this._map` is not defined due to the fetch failure.

### Expected Behavior

It doesn't crash in this failure case

### Actual Behavior

It crashes

**Comment by HarelM** [comment]
Seems like the code there uses an internal method, which doesn't seem like a good idea.
I've also seen the following bug, which lacks tests and a PR in order to be resolved properly: #2294.
I think it's far easier to simply create a location control, but it might be just me :-)

**Comment by bgeihsgt** [comment]
Thanks @HarelM. Agree that `react-map-gl` probably should not call internal methods like this :)

Note I attached a PR here that at least doesn't crash if `_setupUI` doesn't have a `_map` instance.

**Comment by HarelM** [comment]
See my comments there - if the invocation is not done correctly, the fix should not be in this library...

**Comment by bgeihsgt** [comment]
@HarelM fair enough. I'll file against `react-map-gl`

**Comment by Pessimistress** [comment]
I just want to note here that react-map-gl does not call `_setupUI`. It simply wraps the method to work around a mapbox-gl bug *in case* it is called. I believe that #2358 would have resolved this issue.

**Comment by HarelM** [comment]
Adding a null check without a test or a proper reproduction is a patch, not a fix.
If there is a way to reproduce this using only maplibre code while using the public API, then sure, let's fix it here, if not then the fix can be made in the calling library, which is what was suggested in the PR.

**Comment by Pessimistress** [comment]
I'm not arguing about the criteria to merge a PR into this repo. I'm simply saying that react-map-gl is not the "calling library" in this case. I'm happy to help with reproducing it in maplibre-gl only, but I believe @bgeihsgt has the most context here.

**Comment by HarelM** [comment]
I'm confused... Can you explain the following link then?
https://github.com/visgl/react-map-gl/blob/v7.0.21/src/components/geolocate-control.ts#L80-L85
In any case, we agree a proper reproduction is needed.

**Comment by Pessimistress** [comment]
> Can you explain the following link then

This code rewrites `gc._setupUI`, but does not call it. The React wrapper calls `new GeolocateControl()`, then `map.addControl()`. It does not set `_map`, nor call `_setupUI`.

`_setupUI` is only ever called internally by https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/control/geolocate_control.ts#L108

**Comment by Pessimistress** [comment]
Adding some of my observations:

I am very skeptical about the claim that `control._map` would be null if fetch fails. `control._map` is only cleared when the control is removed from the map.

You can see the same error message in the following repro: https://codepen.io/Pessimistress/pen/wvYKWaE?editors=1011

In vanilla JS you normally wouldn't do something like this, but with React a component could be unmounted quickly due to state change from e.g. `useEffect`. In fact, in React [StrictMode](https://legacy.reactjs.org/docs/strict-mode.html) a component is intentionally mounted - dismounted - mounted again to highlight potential problems in the implementation. `GeolocateControl` is the only control that initializes its UI elements asynchronously. It's not unreasonable to check if the control has been removed in an async callback function (`_setupUI` in this case).
