### ISSUE TITLE
`interpolate-hcl` uses non-standard D65 illuminant

### ISSUE THREAD

**Issue by ChrisLoer** [maplibre/maplibre-gl-js#2382]
The RGB -> HCL code in https://github.com/maplibre/maplibre-gl-js/blob/main/src/style-spec/util/color_spaces.ts forked out of `d3-color` in 2016. It uses the D65 illuminant in all of its intermediate color spaces. In 2018 `d3-color` was [patched](https://github.com/d3/d3-color/pull/46) to convert from D65 to D50 (see discussion at https://github.com/d3/d3-color/issues/42). The [CSS spec recommends using D50](https://drafts.csswg.org/css-color/#predefined-to-lab-oklab) to convert to LAB (which is the step before converting to HCL).

The spirit of the Mapbox/MapLibre Style Spec is generally to follow CSS behavior where possible, so I expect this is the behavior we'd actually want. However, with the current behavior in place, migrating might be a bit trickier -- is it OK to change color behavior for existing maps? Is it OK for the behavior of MapLibre to diverge from Mapbox GL?

Here's an example of how the difference plays out, interpolating between `["#1518e4", "#A96011"]` with the same input values to the interpolation -- the visual effect is to have less distinction as you traverse the color space between the two endpoints:

**Using D50 (this is generated with Protomaps.js -- notice the wide range of purples)**
![Screenshot 2023-01-06 at 5 19 18 PM](https://user-images.githubusercontent.com/375121/211124664-631b1d6a-3dc8-4ea1-a32f-566074a630e1.png)

**Using D65 (this is generated with MapLibre GL JS -- notice how the values seem to cluster closer to red or blue)**
![Screenshot 2023-01-06 at 5 19 08 PM](https://user-images.githubusercontent.com/375121/211124666-935c58c5-6cd5-445b-8fc3-c5808e32d653.png)

I'm happy to work on a PR for this if we think it's a change that should go into MapLibre.

cc @HarelM @ibesora

**Comment by HarelM** [comment]
I think this was just solved in the maplibre style and there's an open PR here: https://github.com/maplibre/maplibre-gl-js/pull/2376

**Comment by ChrisLoer** [comment]
Oh, cool! But I'm looking at https://github.com/kajkal/maplibre-gl-style-spec/blob/c34a895e6e3f138a404b1554a37d4ca3ab1a2a58/src/util/color_spaces.ts#L34-L42 and it looks to me like it's still using D65? There are different ways to do it, but I was expecting something like https://github.com/d3/d3-color/blob/958249d3a17aaff499d2a9fc9a0f7b8b8e8a47c8/src/lab.js#L5-L13.

I am not an expert in color spaces at all (in fact I'm color blind, I can barely even see these differences), so it's easy for me to get confused here.

**Comment by HarelM** [comment]
Cc @kajkal.
I don't have deep knowledge about color interpolation...

**Comment by kajkal** [comment]
As far as I'm concerned, I think you've hit the perfect moment when it comes to making changes with colors. Recently, I've been working on adding support for CSS Color 4 and, in the process, I've slightly improved the existing code related to color interpolation [#94](https://github.com/maplibre/maplibre-style-spec/pull/94).
Personally, I believe that the use of color spaces other than sRGB in mapbox/maplibre was not a commonly used feature, because I refuse to believe that [such interpolation results](https://kajkal.github.io/maplibre-gl-style-spec-color-demo/) have not bothered anyone who actually used them in recent years. 

When you're done you can add your bundle to [the collection](https://github.com/kajkal/maplibre-gl-style-spec-color-demo/blob/d8081d01630cffacbd8dcd663c7fa2bde1614ea0/index.html#L8-L16) to easily illustrate the difference between the versions :)

**Comment by wipfli** [comment]
Nice demo!

**Comment by wipfli** [comment]
Did a lot of render tests break when you introduced the new interpolation?

**Comment by kajkal** [comment]
@wipfli Not too many, 3 in maplibre-style-spec and 4 in maplibre-gl-js (where there is a plan to move these tests to maplibre-style-spec [#97](https://github.com/maplibre/maplibre-style-spec/pull/97)).

**Comment by ChrisLoer** [comment]
That is a great demo @kajkal ! It took me a while to figure out what's going wrong, but it looks to me like the totally broken interpolation you're seeing is only for style properties that use a color ramp texture (I think that's line-gradient and heatmaps). The reason is that the rgb->hcl->interpolate->back-to-rgb path can leave small negative values for some of the RGB values. This is obviously not correct (what does it even mean?) but I think on other code pathways it basically ends up being a rounding error. On the color ramp pathway, it gets clamped to an 8 bit uint, so it overflows to 255, causing those dramatic discontinuities.

At Felt, we definitely use interpolate-hcl (it's consistent with color interpolation in the rest of our app, and also I _think_ it's just perceptually superior for interpolation). We don't run into this behavior because we don't use line gradients or heatmaps yet. A common case for us would be in a choropleth map.

Great to see this is an area of active development!

**Comment by ChrisLoer** [comment]
Aha, and I see that you added clamping on the way back to RGB that would prevent this: https://github.com/maplibre/maplibre-style-spec/pull/94/files#diff-1ea8753eaadd1cd8c60e59e66ccde779f029fbc78b12d363865d3b009351b271R91

OK, so the path forward here for me to try to do the d50 modification is probably to open a PR against maplibre-style-spec with the changes, then build a bundle with that pulled in so we can use it for comparison in your tool?

**Comment by kajkal** [comment]
I'm not the decision maker here but to me your plan sounds great 😅 
> When you're done you can add your bundle to [the collection](https://github.com/kajkal/maplibre-gl-style-spec-color-demo/blob/d8081d01630cffacbd8dcd663c7fa2bde1614ea0/index.html#L8-L16)

Don't treat this part as some kind of requirement. I just thought it would help to visualize the changes and make sure that the results are visually satisfactory.

As for the bundle, you can easily make it locally by changing https://github.com/maplibre/maplibre-gl-js/blob/e50a264b2174e8534d265e47b13d55fdc79ee5a9/package.json#L24 to the location of the style repo with the generated dist folder:
```json
"@maplibre/maplibre-gl-style-spec": "file:../maplibre-gl-style-spec",
```
at least that's how I did it.

**Comment by ChrisLoer** [comment]
Cool -- I drafted up an initial version of the changes and looking at the tests it looks very roughly right (but I think we probably want to visually benchmark against some internal tool like `d3-color`).

The change relies on being very trusting with importing new magic numbers, but is basically pretty simple: https://github.com/felt/maplibre-style-spec/pull/1/files

 I had trouble getting the package built and incorporated into maplibre-gl the way you suggested. This error in the maplibre-style-spec tests might point to something to do with the typescript config?

```
  ● @maplibre/maplibre-gl-style-spec npm package › files build

    expect(received).toMatchInlineSnapshot(snapshot)

    Snapshot name: `@maplibre/maplibre-gl-style-spec npm package files build 1`

    - Snapshot  - 1
    + Received  + 0

    @@ -11,9 +11,8 @@
        "gl-style-validate.cjs.map",
        "gl-style-validate.mjs",
        "gl-style-validate.mjs.map",
        "index.cjs",
        "index.cjs.map",
    -   "index.d.ts",
        "index.mjs",
        "index.mjs.map",
```

Meanwhile on the maplibre-gl side, an `npm install` pointing to `file:../maplibre-style-spec` generates a lot of typescript compile errors, e.g.:

```
TSError: ⨯ Unable to compile TypeScript:
../maplibre-style-spec/dist/index.cjs:3:10 - error TS2304: Cannot find name 'define'.

3   typeof define === 'function' && define.amd ? define(['exports', 'color-string', '@mapbox/unitbezier'], factory) :
...
```

I haven't opened a PR against maplibre/maplibre-style-spec yet because I need to figure that stuff out. I'm OOO all next week so might not get a chance to wrap this up right away.

**Comment by kajkal** [comment]
In maplibre-gl-style-spec:
`npm run build` - to build `.js`s bundles
`npm run generate-style-spec` - idk to generate some more types or something
`npm run generate-typings` - to build `index.d.ts` bundle (the test you mentioned calls for it)
then your `maplibre-gl-style-spec/dist` folder should have all the necessary files.

Next in maplibre-gl-js:
`npm run build-dist` - to build everything possible

Sometimes my changes from maplibre-gl-style-spec did not append correctly to the final bundle `maplibre-gl.js` (or its easier-to-read equivalent `maplibre-gl-dev.js`). In this case, manually deleting the `node_modules/@maplibre` folder before `build-dist` helped. I was using pnpm so some magic caching was probably to blame.

**Comment by kajkal** [comment]
@wipfli 
> Did a lot of render tests break when you introduced the new interpolation?

I checked and not a single render test showed that something had changed with color interpolation :)

**Comment by ChrisLoer** [comment]
I ended up running the test by just swapping out the file in node_modules, and at first I thought nothing was happening (although I made an unminified build so I could easily verify the new code was in the bundle).

I put in debug log statements to look at the values being generated for the color ramp, and could see they were slightly different -- but I couldn't actually see the difference until I recorded a video going back and forth between the two (this is me recording switching between two tabs with d50 vs d65, it's d50 when "Example set 1" is highlighted). The recoding is slightly lossy so it's not perfect, but you can see the difference in "interpolate-hcl" and "interpolate-lab" -- look in the part halfway between blue and white, and you can see with d65 it basically looks whiter all across the spectrum.

https://user-images.githubusercontent.com/375121/234122348-6985f893-c596-4f69-b043-5920a86fae3a.mov

Honestly -- I can see the difference, and I think d50 is more correct, but this looks very subtle to me. I think @kajkal 's earlier fixes were way more important, and I'm not still sure if this is a big deal.

**Comment by kajkal** [comment]
@ChrisLoer I added your changes from https://github.com/felt/maplibre-style-spec/pull/1 to the color demo bundle collection. I also added the option to compare changes using the `maplibre-gl-compare` plugin:
https://kajkal.github.io/maplibre-gl-style-spec-color-demo/swipe.html

The changes do indeed seem subtle, however, I think it would be worth switching to D50. 
It would be nice to include these changes in v3.0.0 so that potentially breaking changes with colors can be made in a single release.

**Comment by ChrisLoer** [comment]
Oh wow, nice touch with the swipe interface! When you updated the color unit tests, did you follow a particular strategy (e.g. looking for testing specific colors), or did you just run them again and copy over new values?

**Comment by kajkal** [comment]
I assume you are asking about tests from [`color_spaces.test.ts`](https://github.com/maplibre/maplibre-style-spec/blob/4f849afbbb176a3964d0a14f4733ffd611118937/src/util/color_spaces.test.ts). I was inspired by the color selection from the [CSS Color 4 specification tests](https://github.com/web-platform-tests/wpt/tree/61ddd54575ca06baf63ec46ee28fe13ee014c2f4/css/css-color), but only for the input data, the output data was generated by the existing code.

**Comment by ChrisLoer** [comment]
OK, I put the PR up at https://github.com/maplibre/maplibre-style-spec/pull/146!

**Comment by birkskyum** [comment]
@ChrisLoer , can this be closed?

**Comment by birkskyum** [comment]
Closed by https://github.com/maplibre/maplibre-style-spec/pull/146 (change to style spec)
Closed by https://github.com/maplibre/maplibre-gl-js/pull/2503 (update style spec in GL JS)
