### ISSUE TITLE
GeolocateControl throws if removed too quickly

### ISSUE THREAD

**Issue by Pessimistress** [maplibre/maplibre-gl-js#2387]
**maplibre-gl-js version**: 2.4.0

**browser**: Chrome 111.0

### Steps to Trigger Behavior

 1. Create a GeolocateControl
 2. Add the control to a map
 3. Remove the control immediately from the map

In the console an error is printed:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_getUIString')
    at GeolocateControl._setupUI (maplibre-gl.js:35:380829)
    at maplibre-gl.js:35:374467
```

### Link to Demonstration

[codepen](https://codepen.io/Pessimistress/pen/wvYKWaE?editors=1011)

### Expected Behavior

No error in the console.

### Actual Behavior

`GeolocateControl._setupUI` is fired conditionally after a promise:
https://github.com/maplibre/maplibre-gl-js/blob/c62155b28818ac5777e4853cffe2892a0ae59487/src/ui/control/geolocate_control.ts#L108

While the promise is being resolved, it's possible that the control has been removed, leading to `_map` being undefined.

More context can be found in the original discussion thread: #2357

> In vanilla JS you normally wouldn't do something like this, but with React a component could be unmounted quickly due to state change from e.g. `useEffect`. In fact, in React [StrictMode](https://legacy.reactjs.org/docs/strict-mode.html) a component is intentionally mounted - dismounted - mounted again to highlight potential problems in the implementation. GeolocateControl is the only control that initializes its UI elements asynchronously. It's not unreasonable to check if the control has been removed in an async callback function (_setupUI in this case).

**Comment by HarelM** [comment]
Great repudiation, thanks!
Feel free to submit a PR to fix this along a test that is basically described here in this issue.
