### ISSUE TITLE
[TypeScript 5.0.2] "setData" definition is missing for setting data to source

### ISSUE THREAD

**Issue by jakub-gawryl** [maplibre/maplibre-gl-js#2395]
I'm trying to use code as below:

```typescript
import { Map } from 'maplibre-gl';

const sourceId = 'SOME_SOURCE_ID';

// init map
const map = new Map({
  container: 'xx',
  style: ''
});

// add empty source
map.addSource(sourceId, {
  type: 'geojson',
  data: {
    type: 'geojson',
    data: {
      features: [],
      type: 'FeatureCollection'
    }
  }
});

// get source
const source = map.getSource(sourceId);
/**
 * after hover on source i get:
 * const source: Source | undefined
 */

// trying to update source data:
source.setData({
  features: [],
  type: 'FeatureCollection'
});

/*
Now i'm getting error:
Property 'setData' does not exist on type 'Source'.ts(2339)

and indeed i can't see any definition of `setData` there:
https://github.com/maplibre/maplibre-gl-js/blob/main/src/source/source.ts#L35-L64
*/
```

For now I resolved it by using `// @ts-ignore` but it's not the most elegant solution :)

**maplibre-gl-js version**: 2.4.0

**browser**: ---

### Steps to Trigger Behavior

 1. use package manager to install latest maplibre-gl (yarn in my case)
 2. use code above

### Link to Demonstration

---

### Expected Behavior

`source.setData` should not report any error

### Actual Behavior

VS Code reports an error `Property 'setData' does not exist on type 'Source'.ts(2339)`

**Comment by HarelM** [comment]
Get source can return a few types of sources, you need to cast to the relevant one.

**Comment by jakub-gawryl** [comment]
@HarelM thanks for response.
Yea this is good hint, but I'd need to cast to eg. ` as GeoJSONSource | undefined`.
Maybe would be better to update `getResource` definition to something like
```typescript
getSource<T>(id: string): T | undefined;
```

(or more advanced case to fallback to `Source` if `T` is not provided, but i'm not that advanced yet :))

and then use brackets casting:

```typescript
const source = map.getSource<GeoJSONSource>(SOURCE_ID);
```

**Comment by HarelM** [comment]
The difference are minor from my point of view (you still need to supply the type before the method instead of after), but an overload can be defined to accommodate for this, feel free to submit a PR. 😀

**Comment by jakub-gawryl** [comment]
the more i work with this lib, the more i see that your approach to casting is a bit more convinient  :)
Thanks, andthis issue can be closed 👍
