### ISSUE TITLE
Split tests run to optimize CI run time

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#2411]
Currently the split between the tests is not optimal and if a test fails the entire workflow needs to run again.
Also some workflows can run in parallel to reduce the total time the CI runs. the following is the longest run (on windows):
![image](https://user-images.githubusercontent.com/3269297/232467846-c6e42ec0-c2de-4837-bd88-c4efdffa5bb2.png)
@rotu, any chance you can take care of this?

**Comment by HarelM** [comment]
Acceptance criteria:
Tests are split so that the longest run is a separate CI.
Assigning M bounty.
Requires #2482

**Comment by birkskyum** [comment]
Did the github syntax wrong. Can this be assigned and closed?

**Comment by birkskyum** [comment]
OC https://opencollective.com/maplibre/expenses/138080
