### ISSUE TITLE
NPM and Node version update

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#2416]
Is there a simple way for everyone to tell which version of npm and node are on in CI pipeline? 

I am guessing it is npm 8 and node 18, so now node released 19 half year ago, how often do we update?

My dev box got updated to 19 and npm 9 because of other projects I am working on. Now two render tests are failing, which I assume we will need fix sooner or later.

**Comment by IvanSanchez** [comment]
https://github.com/maplibre/maplibre-gl-js/blob/e3bf0b9c3e5805e4ff167271f3e1288778611be8/.github/workflows/release.yml#L23

You can `git blame` that line to see how frequently it's been changing.

**Comment by HarelM** [comment]
We generally change with the change of LTS, and 19 (or odd numbers for that matter) usually don't get to be LTS, so we'll update when 20 is released I guess...
