### ISSUE TITLE
3D objects not rendering becuase of buffer issue- issue was resolved with mapbox

### ISSUE THREAD

**Issue by RussellMiddleton33** [maplibre/maplibre-gl-js#2421]
**maplibre-gl-js version**:
2.4.0

**browser**:
Chrome

### Steps to Trigger Behavior

 1. Try rendering a .gltf or .glb file that has a larger amount of verticies and you get this error: 
 
 "WebGL-0x1140084ea00] GL_INVALID_OPERATION: Insufficient buffer size."

### Expected Behavior
3D model will load

### Actual Behavior
3D model does not load unless it is a really small 3D model.

Thanks for your help!

**Comment by RussellMiddleton33** [comment]
issue appears to be fixed when using mapbox as I don't get the same issue there. Slight difference in the codebase with src/gl/vertex_buffer.js most likley by addind the assert function

**Comment by HarelM** [comment]
Please add a stackblittz or similar reproduction.

**Comment by HarelM** [comment]
No reproduction, closing, if the relevant info will be provided I'll be more than happy to re-open this.
