### ISSUE TITLE
map.addLayer with a vector tile source throws a type error:  '"vector"' is not assignable to type '"raster-dem"'

### ISSUE THREAD

**Issue by tyrauber** [maplibre/maplibre-gl-js#2442]
In a typescript app,  adding a vector tile source using `map.addLayer` throws a type error:
> type: '"vector"' is not assignable to type '"raster-dem"'

### Steps to Trigger Behavior

```
map.current.on('load', function () {
  map.current.addLayer({
    id: 'points',
    type: 'circle',
    source: {
      type: 'vector',
      tiles: [URL + '/v1/points/{z}/{x}/{y}']
    },
    'source-layer': 'points',
    paint: {
      'circle-color': 'red'
    },
  });
});
```
### Work Around

Add the style source on map style initialization.

**maplibre-gl-js version**: 2.4.0
**browser**: Chrome

**Comment by jleedev** [comment]
The example here doesn't compile: https://github.com/maplibre/maplibre-gl-js/blob/7bd37421c51c8dd234880817b167c43407630d82/src/ui/map.ts#L1144-L1158

It gives: `Type '"vector"' is not assignable to type '"image"'.ts(2322)`

Refactoring slightly makes the error more clear:

~~~ts
  const source: VectorSourceSpecification =  {
    type: 'vector',
    url: 'https://demotiles.maplibre.org/tiles/tiles.json'
  };
  map.addLayer({
    id: 'points-of-interest',
    source,
    'source-layer': 'poi_label',
    type: 'circle',
  });
~~~

Error:

~~~
Type 'VectorSourceSpecification' is not assignable to type 'string & (string | SourceSpecification | undefined)'.
  Type 'VectorSourceSpecification' is not assignable to type 'string & VectorSourceSpecification'.
    Type 'VectorSourceSpecification' is not assignable to type 'string'.ts(2322)
~~~

It looks like https://github.com/maplibre/maplibre-gl-js/pull/1392 got the type wrong — it requires the `source` property to both be a string _and_ a (string or SourceSpecification or undefined), which it never can be unless it's a string.

Using `Omit` could work.

~~~ts
addLayer(layer: (Omit<LayerSpecification, "source"> & {source?: string | SourceSpecification}))
~~~

**Comment by HarelM** [comment]
Ahh, interesting, I though writing `LayerSpecification & {source?: string | SourceSpecification}` means that it will do an "|" in the source field, seems that it does a "&".
Any chance you can submit a PR to fix this?
