### ISSUE TITLE
Tiles with `raster-fade-duration: 0` inappropriately held for underzooming

### ISSUE THREAD

**Issue by ChrisLoer** [maplibre/maplibre-gl-js#2445]
When you zoom out on a raster layer, MapLibre holds on to underzoomed child tiles for the "raster fade duration" so that it can apply a cross fade. In the case where the fade-duration is 0, it shouldn't hold onto them at all once the parent is loaded, but its logic to do that incorrectly _always_ retains when fade-duration is 0:

https://github.com/maplibre/maplibre-gl-js/blob/c03607bad8a0d6574e9738b23fa84f3620713df5/src/source/source_cache.ts#L560

The tiles will stay in the pyramid potentially indefinitely, although only while in the viewport and within the "max underzooming" range. Here's an example of a satellite layer with higher-zoom (cloudy) tiles persistently drawn where we should have lower zoom tiles:

![image](https://user-images.githubusercontent.com/375121/234374493-89242af5-f690-484c-9bd0-b14d24afe41e.png)

At Felt, we're working around this by using `raster-fade-duration: 1` which isn't visibly different but avoids the logic error.

I believe the correct logic should be:

```
if (!tile || !tile.fadeEndTime || tile.fadeEndTime <= browser.now()) continue;
```

a.k.a. "don't hold for fading, _if_ (1) the tile is already out of the pyramid, (2) the tile doesn't have a fade duration set, or (3) the tile has a fade duration set, but it's expired"

cc @ibesora

**Comment by HarelM** [comment]
Javascript `!` operation is tricky as I'm sure you know. `0`, `null` and `undefined` all return true if you place a `!` operation before them, in both proposals this will not work, I think - you'll need to explicitly check for undefined i.e. `fadeEndTime === undefined`.
In any case, this looks like a bug that would love a PR :-)
