### ISSUE TITLE
First click event on the map is not being registered.

### ISSUE THREAD

**Issue by akexinad** [maplibre/maplibre-gl-js#2460]
When I click on the map for the first I am unable to see the map's event object in the console. The click is happening because the popup appears and the app re-renders due to a `setState` call.

Here is a link to a codesandbox: https://codesandbox.io/s/interesting-gwen-u0t911?file=/src/App.tsx

The code:

```
import { Map } from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import React, { useEffect, useRef, useState } from 'react';

export const VanillaMap = () => {
	const mapContainer = useRef();
	const map = useRef<Map>(null);
	const [lng] = useState(139.753);
	const [lat] = useState(35.6844);
	const [zoom] = useState(14);
	const [clicked, setClicked] = useState(false);

	useEffect(() => {
		if (map.current) return;

		map.current = new Map({
			container: mapContainer.current as HTMLElement,
			style: 'https://demotiles.maplibre.org/style.json',
			center: [lng, lat],
			zoom,
		});
	});

	const handleClick = () => {
		map.current.once('click', (e) => {
			console.log('clicked', e);
		});

		setClicked((prevState) => !prevState);
	};

	return (
		<>
			<div
				ref={mapContainer}
				style={{
					width: '100%',
					height: 'calc(100vh - 300px)',
				}}
				className="map"
				onClick={handleClick}
			/>
			{clicked && <h3 data-testid="pop-up">position selected</h3>}
		</>
	);
};
```

**maplibre-gl-js version**: 2.4.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. Let the page refresh until you can see the map.
 2. Click on the map.
 3. The event object will only appear in the console after the second click.

**Comment by HarelM** [comment]
Please provide a reproduction that does not have a react wrapper as there might be issue with the wrapper code and not this library.
Also Assigning events to the map object needs to happen after map load I think (not sure though, but it's probably safer).

**Comment by akexinad** [comment]
Issue closed as this issue does not exist in it's vanilla iteration.

**Comment by ferdicus** [comment]
if it's any help (i know this is old and closed):
i believe the issue stems from you setting up the map click handler within your `handleClick` function which executes when the map div is clicked, so the flow looks as follows:

* `map` loaded => `handleClick` set up for the `div` that `map` renders in
* user clicks on the map => `handleClick` is executed and the click handler that you defined for the map (`map.once`....) is being set up
* now, the following click on the map will set up the next click handler, but the one that was set up during the last click is executed
