### ISSUE TITLE
Double-tap-and-drag-to-zoom gesture registers even when taps are far away

### ISSUE THREAD

**Issue by mz8i** [maplibre/maplibre-gl-js#2474]
The detection of the mobile gesture of double-tap-and-drag-to-zoom (single finger zoom) behaves in an incorrect way.

A problem with the current logic is visible in a particular use case: a map with points that the user can select.

**maplibre-gl-js version**: 2.4

**browser**: any (tested on Firefox 112, Chrome 112)

### Steps to Trigger Behavior

 1. Display a map with points the user can select by tapping
 2. Tap on a point to select it
 3. Quickly tap elsewhere on the map and start dragging to pan the map
 4. The map starts zooming instead

### Link to Demonstration

This [CodeSandbox](https://codesandbox.io/s/react-map-gl-deck-gl-points-prx0sp?file=/src/App.tsx) demonstrates such a use-case. Note that the example uses `react-map-gl` and `deck.gl` to display the points, but that's not relevant as the interaction logic is still handled by `maplibre-gl-js`.

Here's a video (recorded on mobile) of the user trying to select one of the points and then quickly pan the map. The first pan is successful because the user waits a bit longer. The second pan doesn't work because the user drags shortly after tapping on a point. This gets registered as the zooming gesture. But the zooming gesture should only be registered if the two taps are roughly in the same place - similar to how a double-tap is detected.

https://user-images.githubusercontent.com/36160844/235488260-6a7972d2-c2fe-415a-a60e-2f6e3a33a464.mp4

### Expected Behavior

When a second tap starts far away from the first tap, it should not get registered as the mobile single-finger zoom gesture - even if the taps are close to each other in time.

### Actual Behavior

The zoom gesture is registered, which is unexpected behaviour.

### Solution

Having looked at the code, the problem is that 
https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/handler/tap_drag_zoom.ts
doesn't use the `MAX_DIST` constraint that is used in `TapRecognizer`.

Seems like an easy fix, I will submit a PR to address this.

**Comment by HarelM** [comment]
Thanks! This seems unrelated to point selection I believe, using click -> click far + drag also reproduces this issue, right?
Feel free to submit a PR. don't forget to write a test and a changelog entry. 💪

**Comment by mz8i** [comment]
Yes you are correct, I just gave the point selection as an example of such a "tap pattern" is likely to occur!

But it is reproducible on any sort of maplibre map.

**Comment by mz8i** [comment]
Fix was released in [v3.2.0](https://github.com/maplibre/maplibre-gl-js/releases/tag/v3.2.0)
