### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by jimbok8** [maplibre/maplibre-gl-js#2477]
I am getting the following error in `Console`:
`Unable to preventDefault inside passive event listener invocation.`
This happens on map panning using mouse left-click-drag.
Please can someone advise me on how to get rid of this error?
Thanks.
Jim

**Comment by HarelM** [comment]
No reproduction, closing, if the relevant info will be provided I'll be more than happy to re-open this.

**Comment by tzetter** [comment]
I ran into this exact issue and concluded that it was the Sentry replayIntegration that caused it.

**Comment by rbrundritt** [comment]
I've just had this brought to my attention and was able to reproduce it in several apps. Here is a simple codepen that reproduces the issue: https://codepen.io/rbrundritt/pen/yyLQQrv Simply click on the text above a circle and two alerts will appear, one for each layer. I tried many variations to try and work around this but had no luck.

**Comment by HarelM** [comment]
I don't think this is the description of this issue.
You can use: `e.preventDefault()` and `e.defaultPrevented`. Unfortunately, it seems that the events continue the propagation between layers...
