### ISSUE TITLE
PR 2455 and fadeEndTime

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#2480]
@ibesora @HarelM, Regarding the merged PR #2455 issue #2445

The UT is mocking fadeEndTime to be 0, however in real application, it is always undefined. I made test based on sample:
https://maplibre.org/maplibre-gl-js-docs/example/map-tiles/
and adding <code>
'paint': {
                    'raster-fade-duration': 0
                }
</code>

Upon deeper look, fadeEndTime is only being set here:
https://github.com/maplibre/maplibre-gl-js/blob/7bd37421c51c8dd234880817b167c43407630d82/src/source/tile.ts#LL126C1-L132C6

and in this function when duration is 0, line 128 is always true and returned --- therefore line 131 is never hit and remain undefined, aligning with my observation above.

<b>Conclusion</b> --- PR 2455 did not make any difference in real application. :)

In fact there is another UT to check when tile.fadeEndTime is undefined --- I suspect this test case is obsolete and should be updated.
https://github.com/maplibre/maplibre-gl-js/blob/7bd37421c51c8dd234880817b167c43407630d82/src/source/source_cache.test.ts#LL762C5-L762C83

Second --- I am not sure why render test failed in one of the iterations. They all pass for me, before or after applying the condition changed in #2455, because there are two baselines anyway (expected, and expected_ubuntu22). If they need to updated, both should be included in the PR

Third and edge case, <code>browser.now()</code> should be moved to before line 556.
https://github.com/maplibre/maplibre-gl-js/blob/7bd37421c51c8dd234880817b167c43407630d82/src/source/source_cache.ts#LL560C16-L560C16
The reason is that there are so many tiles to check, and browser.now() is down to microseconds which is incrementing constantly. We want all tiles in this loop to be measured in the same standard.

Hope I did not miss anything. Thanks. :)

**Comment by HarelM** [comment]
Cc @ChrisLoer 
Let me know if the merged PR fixed the issue or not.
The fixe in general seemed reasonable to me, but if this was a miss please let us know what should be the correct fix in this case.

**Comment by zhangyiatmicrosoft** [comment]
Again in this block:
https://github.com/maplibre/maplibre-gl-js/blob/7bd37421c51c8dd234880817b167c43407630d82/src/source/tile.ts#LL126C1-L132C6

tile.fadeEndTime with undefined vaule is very confusing and error prone. This part has not been updated for years.

I'd propose to change Tile class and init fadeEndTime same as timeAdded in its ctor. 
All subsequent code in registerFadeDuration or source_cache will be much simpler and easy to read. :)

**Comment by HarelM** [comment]
Sounds like a good idea...

**Comment by zhangyiatmicrosoft** [comment]
@ibesora if you agree to all proposals, I will start a PR.
We use raster tiles extensively and could benefit from this fix. Thanks

**Comment by pramilk** [comment]
Here is a repro using latest main branch code.
This sample, loads page at zoom 12 and then on Idle changes it to zoom 10.

With fade duration 0
https://perfmeasure.blob.core.windows.net/maplibre-sample/maplibreLocal_WithFade_0.html

<img width="394" alt="image" src="https://user-images.githubusercontent.com/15951646/236914806-a559abff-3b48-40a3-88d2-2c087a0ada18.png">

With fade Duration 1
https://perfmeasure.blob.core.windows.net/maplibre-sample/maplibreLocal_WithFade_1.html

<img width="413" alt="image" src="https://user-images.githubusercontent.com/15951646/236914853-148b9c94-d5c7-4c33-bc4e-34f5f22a3550.png">

**Comment by zhangyiatmicrosoft** [comment]
Nice repro. Thanks!

**Comment by ibesora** [comment]
> @ibesora if you agree to all proposals, I will start a PR. We use raster tiles extensively and could benefit from this fix. Thanks

Yeah, let me know if I can help with that. And thanks for the deep investigation

**Comment by zhangyiatmicrosoft** [comment]
#2501
