### ISSUE TITLE
Replace Playwright with Puppeteer

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#2481]
Replace Playwright (Chromium) with Puppeteer (Chrome /  'new' headless mode), to speed up integration (query, browser) tests, gl stats and benchmarks

**Comment by HarelM** [comment]
Assigning bounty L
Direction:
https://github.com/maplibre/maplibre/issues/192

**Comment by birkskyum** [comment]
Can I take on this task?

**Comment by HarelM** [comment]
Enjoy!

**Comment by birkskyum** [comment]
OC https://opencollective.com/maplibre/expenses/138071
