### ISSUE TITLE
text-allow-overlap partially ignored for symbol layer

### ISSUE THREAD

**Issue by drwestco** [maplibre/maplibre-gl-js#249]
**maplibre-gl-js version**: 0.14 rc3+ 0.15, etc. (issue inherited from mapbox-gl-js)

**browser**: all

Copy of https://github.com/mapbox/mapbox-gl-js/issues/10089

### Steps to Trigger Behavior

 1. Starting with the example at https://docs.mapbox.com/mapbox-gl-js/example/filter-markers-by-input/, modify the layer layout properties to have:
`    
'icon-allow-overlap': true,
'text-allow-overlap': false,
'text-optional': true,
`
 2. Zoom out so the icons + layers start to collide

### Link to Demonstration

Simpler repro, separating icons and labels into two layers. I thought adding the labels after adding the icons might make it behave better, but no luck. https://jsbin.com/qavizac

![image](https://user-images.githubusercontent.com/743030/106367900-e1870380-62fa-11eb-940c-34ce40454beb.png)

If I skip the icon layer and just add the labels, I think it illustrates what's going wrong here. text-allow-overlap is being ignored (at least partially), as the bold labels are allowed to overlap the base map neighborhood labels.

![image](https://user-images.githubusercontent.com/743030/106368140-5ad32600-62fc-11eb-97c5-6596a4526191.png)

### Expected Behavior

Per the options, I'd expect the icons to be allowed to overlap, but not the text. The text should disappear when it starts to overlap other text or icons. 

### Actual Behavior

Some of the text is removed as expected; other text is allowed to overlap the icons. Here, the bottom-right MUSIC label is correctly removed, but BICYCLE sticks around and is drawn atop the theatre icon.

![image](https://user-images.githubusercontent.com/743030/98751786-a1585a80-2375-11eb-9efb-742a414bece6.png)

**Comment by drwestco** [comment]
This is especially problematic with clusters of overlapping symbols. Icons are drawn back-to-front, and it looks like the text labels are places in the same order. What this means is usually it's the label for the first placed symbol that gets drawn on top of a bunch of icons, instead of the label for the top-most icon.

**Comment by HarelM** [comment]
Is this the same or similar to this issue/PR:
https://github.com/maplibre/maplibre-gl-js/pull/145
I would advise to try and use the branch which has the fix in the PR and see if it solves this issue...

**Comment by drwestco** [comment]
No. That PR (#145) is done at the draw phase; this is a bug in the symbol placement phase. With that PR in place, this issue still occurs, though it's now possible for icons to overlap text, since the draw order changes from icon,icon,...,icon,text,text,...,text to icon,text,icon,text,...,icon,text

The PR is good for icons containing text, as interleaved icon/text drawing is exactly what you want there. It doesn't help the text labels scenarios, though.

**Comment by HarelM** [comment]
I see, in that case the best approach would be to try and fix it and send a PR...

**Comment by drwestco** [comment]
Yup. Trying to familiarize myself with the placement code now. If anyone on the project already knows how this portion of the code functions, would appreciate some assistance.

**Comment by drwestco** [comment]
I think I see what's going on here, and it applies to icon-allow-overlap as well as text-allow-overlap. Symbols in layers are placed front-to-back. If a foreground layer has (text|icon)-allow-overlap:false, its symbols will be placed first. If a background symbol layer then has (text|icon)-allow-overlap:true, its symbols will be allowed to overlap the already-placed foreground symbols; a background symbol is not allowed to knock out an already-placed foreground symbol.

Here, the green icon has allow-overlap:false; the red icons have allow-overlap:true
![image](https://user-images.githubusercontent.com/743030/133113009-e84a2f1c-c379-4c92-ba73-21d528cdb06e.png)

It works as expected if fg/bg layers have allow-overlap flipped. With foreground (green) allow-overlap:true, and background (red) allow-overlap:false
![image](https://user-images.githubusercontent.com/743030/133114260-048f611b-70cf-431b-973a-799ba5cf5700.png)

It seems the correct behavior would be to only allow symbols to overlap if either of the following conditions were true:
1. ignore-placement is true for a foreground symbol.
2. allow-overlap is true for BOTH foreground and background symbols.

**Comment by HarelM** [comment]
Was this fixed as part of #347? Can this issue be closed?

**Comment by drwestco** [comment]
Yeah, I tried to link it so it would be closed when that PR was merged. Guess it didn't take..
