### ISSUE TITLE
Don't show cooperativeGestures messages when scrollZoom is disabled 

### ISSUE THREAD

**Issue by htrex** [maplibre/maplibre-gl-js#2498]
When scrollZoom is programmatically enabled/disabled, cooperativeGestures should behave consequently.

When using MapLibre 2.4.0 with scrollZoom disabled and cooperativeGestures enabled the map still shows the cooperativeGestures messages when the user scrolls  over the map, but in that case CTRL+scrollwheel  triggers the web browser page zoom, not the map zoom.

**Comment by HarelM** [comment]
Interesting. Feel free to open a PR to fix this issue.
