### ISSUE TITLE
Include Minified Build in NPM dist directory

### ISSUE THREAD

**Issue by curran** [maplibre/maplibre-gl-js#25]
FWIW I was poking around the [`dist` directory on UNPKG](https://unpkg.com/browse/maplibre-gl@1.13.0-rc.3/dist/) and noticed there is no minified JS build there.

That would be nice to have, for pulling into hosted examples like [VizHub: MapLibre GL Starter](https://vizhub.com/curran/b2df51fad8754d7197dd60fb55258a97) and on other platforms like CodePen, JSFiddle, etc.

Related to https://github.com/maplibre/maplibre-gl-js/issues/5

**Comment by nyurik** [comment]
I have no objections to add `maplibre.min.js` to the `dist` dir, but from the looks of it they are already minified -- note the `mapbox-gl-unminified.js` which is much bigger.

**Comment by curran** [comment]
Ah yes! My bad. I saw the non-minified preamble but didn't see that the rest of it was minified.

![image](https://user-images.githubusercontent.com/68416/101922360-fd441800-3b9b-11eb-8dfb-2f073e7e1462.png)


Closing.
