### ISSUE TITLE
Activating 3D terrain distorts 3D building parts

### ISSUE THREAD

**Issue by zstadler** [maplibre/maplibre-gl-js#2513]
_**Note:** I Edited the description, updated screenshots, and removed no-longer-necessary references to https://github.com/openmaptiles/openmaptiles/issues/1541_

When Activating 3D Terrain, 3D building parts are enlarged and strange overlaps may occur:

![image](https://github.com/maplibre/maplibre-gl-js/assets/1304610/3a9f3b9f-ab6e-4283-9da8-8d3e17ab74c4)

Compare with the same location and viewpoint, with 3D Terrain inactive

![image](https://github.com/maplibre/maplibre-gl-js/assets/1304610/8f68762d-db97-4bf6-8d5b-af13d8f8581b)

**maplibre-gl-js version**:
2.4.0

**browser**:
Chrome 113.0.5672.93
Firefox 112.0.2 

### Steps to Trigger Behavior

- Open https://codepen.io/zstadler/pen/OJBEKJL
- Move the code panes to the left
   <image width="33%" src="https://github.com/maplibre/maplibre-gl-js/assets/1304610/9124e7ee-d213-445a-bc6c-d600f3e2ba91"/>
- Click on the 3D terrain button several times to activate and deactivate the terrain mode in turn.

### Expected Behavior

The shapes and the relative positions of the 3D building parts should not change when 3D terrain is activated or deactivated.

### Actual Behavior

See the above differences

**Comment by HarelM** [comment]
Thanks for taking the time to report this.
Adding L bounty.
Bounty direction:
https://github.com/maplibre/maplibre/issues/189

**Comment by prozessor13** [comment]
Each fill-extrusion object is elevated by the altitude at its centroid coordinate. The centroid is calculated in https://github.com/maplibre/maplibre-gl-js/blob/main/src/data/bucket/fill_extrusion_bucket.ts#L162 . So, if a building has several parts, the centroid should somehow the same value. May this can be a data-value, or an expression in style. I dont know, but i think the current maplibre tools/logic is not sufficient to fix this issue.

**Comment by HarelM** [comment]
Interesting, thanks for the valuable input @prozessor13!

**Comment by zstadler** [comment]
@prozessor13,
If we look at this animated gif, we can see the "ceilings" are moving up while the "floors" are moving move when 3D terrain is activated.

![2023-05-16 18_13_32-3D Terrain — Mozilla Firefox](https://github.com/maplibre/maplibre-gl-js/assets/1304610/1df928e5-9fae-4584-a545-9e8d336868ab)

**Comment by prozessor13** [comment]
I think the "ceilings" moving up because of terrain. the floors are moving down because of https://github.com/maplibre/maplibre-gl-js/blob/main/src/shaders/fill_extrusion.vertex.glsl#L31. But you are right, here is a bug/problem: https://github.com/maplibre/maplibre-gl-js/blob/main/src/shaders/fill_extrusion.vertex.glsl#L39
The `baseDelta` offset should only applied for base 0, and even with this fix it will generate errors for buildings below terrain (if this is an issue??). In general, without some `baseDelta` logic, you get really a lot of ugly artefacts in heavy terrain. Are you willed to test/fixing this?

**Comment by zstadler** [comment]
I'm planning to claim this bounty once the paper work is completed.
Thanks for your patience.

**Comment by HarelM** [comment]
I have submitted the following expense request on behalf of @zstadler:
https://opencollective.com/maplibre/expenses/156265
@zstadler please approve that this was requested by you.

**Comment by zstadler** [comment]
Thank you for submitting the request on my behalf
