### ISSUE TITLE
Remove WebGL1 usages and complete the migration to WebGL2

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#2515]
There is a lot of conditional logic in the codebase, which is there to accommodate WebGL1 which isn't supported anymore.

All this code should be cleaned up, while allowing the unit tests enough mocking to run with the StackGL (webgl1 node implementation)

**Comment by HarelM** [comment]
Adding M bounty.
Direction: https://github.com/maplibre/maplibre/issues/270

**Comment by birkskyum** [comment]
I believe the existing PR's cover all cases of WebGLRenderingContext / webgl1 extensions.

**Comment by HarelM** [comment]
THANKS!

**Comment by birkskyum** [comment]
OC https://opencollective.com/maplibre/expenses/139066
