### ISSUE TITLE
sourcedata's event.isSourceLoaded is only true for last emission when the tiles for all sources are loaded

### ISSUE THREAD

**Issue by ambientlight** [maplibre/maplibre-gl-js#2539]
**maplibre-gl-js version**: 3.0.0-preview.7 as of 66fc5fedf0cee27a8d9aa1c706f972827f15bef7

sourcedata's `event.isSourceLoaded` may be incorrect, as it doesn't actually reflect the load state of the source (of `event.sourceId`) if your style contains more than one source or the sprites are not loaded. Observe that the event actually takes https://github.com/maplibre/maplibre-gl-js/blob/e43e6ef2e71e93bf3b23bca2c4600f069370136a/src/style/style.ts#L744 which will only be set to true on the complete load of all sources (including tiles for all source and sprites). In tests, this normally corresponds to only the last invocation (provided that sprites are not loading), something like:
```
...
source1: false
source2: false
source2: false
source1: false
source1: true
```

Judging from https://github.com/maplibre/maplibre-gl-js/commit/bacb46d0afbc8f2a7db8a30aa3ac3e6fd20a8f34 which is from https://github.com/mapbox/mapbox-gl-js/pull/4254, it has been flipped from the expected `sourceCache.loaded()`. However the original issue that the PR was deemed to resolve doesn't look to be relevant anymore. Flipping the value of the isSourceLoaded to  `sourceCache.loaded()` resolves the issue, where all last loads will be set to true for each source, the above becomes expected:

```
...
source1: false
source2: false
source2: true
source1: false
source1: true
```

### Steps to Trigger Behavior

 1. instantiate the map with a style that contains more then one source.
 2. log the sourcedata events: 
    ```js
    map.on('sourcedata', event => console.log(`${event.sourceId}: ${event.isSourceLoaded}`));
    ```
 3. browse around beyond the visible viewport, observe the logs in the console where only last sourcedata emission has `isSourceLoaded` set to true.

### Link to Demonstration

Navigate to https://glasssh.blob.core.windows.net/repro/event_repro.html, open devtools' console, browse around, check the log messages printed.

### Expected Behavior
Event emission from the each source's last pending tile load from https://github.com/maplibre/maplibre-gl-js/blob/22909c817d55e2a1e172b12a43d792db3e23b40b/src/source/source_cache.ts#L281 should result in `event.isSourceLoaded` set to true. The value of `event.isSourceLoaded` should be logically equivalent to `map.isSourceLoaded(event.sourceId)`.

### Actual Behavior
Event emission from tile load result in `event.isSourceLoaded` set to `true` only once the entire style's https://github.com/maplibre/maplibre-gl-js/blob/e43e6ef2e71e93bf3b23bca2c4600f069370136a/src/style/style.ts#L437 returns true

### Comment
This sounds like the trivial fix unless I am missing something. However this is a breaking change, and the current state may be feel confusingly two-fold (when the entire `style.loaded()` is true, it also implies that any individual source is loaded), however given that the event-driven logic like: 
```
map.on('sourcedata', event => event.sourceId === 'something' && event.isSourceLoaded ? doSomethingWithTileData() : doNothing());
```
could be a common pattern for people to do something with tile data once all tiles in viewport are loaded for a given source, I think we should fix this.

**Comment by HarelM** [comment]
I think I observed this bug a long time ago when I used mapbox, see the following issue in a mapbox angular wrapper I used:
https://github.com/Wykks/ngx-mapbox-gl/issues/206#issuecomment-584332991
I think it's worth the breaking change, and since we haven't released 3.0, we still have a window here.
