### ISSUE TITLE
No 3D buildings with 3D Terrain if located below sea level

### ISSUE THREAD

**Issue by zstadler** [maplibre/maplibre-gl-js#2544]
3D buildings located below sea level turn into 2D footprints (at sea level) when 3D Terrain is activated.

![SeaLevel-bug](https://github.com/maplibre/maplibre-gl-js/assets/1304610/8f482f9b-b51d-4f4d-a0ba-0d5ece9016ac)

**maplibre-gl-js version**:
From 3.0.0-pre.1 
to 3.0.0-pre.7

**browser**:
Chrome 113.0.5672.93
Firefox 113.0.1 (64-bit)
### Steps to Trigger Behavior
- Open [this example on Codepen](https://codepen.io/zstadler/pen/oNaPMro?editors=0010)
- Move the code panes to the left
   <image width="33%" src="https://github.com/maplibre/maplibre-gl-js/assets/1304610/9124e7ee-d213-445a-bc6c-d600f3e2ba91"/>
- Click on the 3D terrain button several times to activate and deactivate the terrain mode in turn.

**Comment by zstadler** [comment]
@birkskyum, could this be related to #1578?

**Comment by zstadler** [comment]
This bug may have been caused by 

https://github.com/maplibre/maplibre-gl-js/blob/22909c817d55e2a1e172b12a43d792db3e23b40b/src/shaders/fill_extrusion.vertex.glsl#L39-L40
where `ele` is included in the `max(0.0, ...)`

and it may be fixed in PR #2541
https://github.com/maplibre/maplibre-gl-js/blob/a3a3000d7c00a1421989fe9a5649c726eb354524/src/shaders/fill_extrusion.vertex.glsl#L39-L40
Where `max(0.0, ...)` is applied only on  the feature's own `base` and `height`, which are relative to the ground level.

**Comment by zstadler** [comment]
This issue is indeed resolved by PR #2541. See [this codepen example](https://codepen.io/zstadler/pen/rNqqyvm?editors=0010) and compare with the above.

![Sealevel-fix](https://github.com/maplibre/maplibre-gl-js/assets/1304610/6fd6aa6a-f507-46be-9967-2ff444a8c376)

**Comment by birkskyum** [comment]
It looks like all three buildings are much taller in 3d - is that the exaggeration?

**Comment by zstadler** [comment]
The animations I added, demonstrating the fix and the bug, were inaccurate in the sense that the style did not have a "background" layer. Therefore all "10 .meters high basements" were seen as if they a part of the above-ground building.

I've updated the style and the animations.
