### ISSUE TITLE
How to use maplibre-gl to implement a map sphere ?

### ISSUE THREAD

**Issue by gengyanlei** [maplibre/maplibre-gl-js#2546]
How to use maplibre-gl to implement a map  sphere?
![image](https://github.com/maplibre/maplibre-gl-js/assets/22360785/c887fed0-68f0-47ca-a536-63671621b351)

**Comment by HarelM** [comment]
Duplicate of #307?

**Comment by gengyanlei** [comment]
I saw that mapbox-gl implemented globe vector-tile, which felt very cool. Looking forward to maplibre implementing it.

**Comment by HarelM** [comment]
Please close this issue if this is a duplicate.
