### ISSUE TITLE
Improve test harness

### ISSUE THREAD

**Issue by zstadler** [maplibre/maplibre-gl-js#2556]
## User Story
When adding a new test or preparing a PR, the "checks" interface on GitHub is essential. Its importance is even higher if the tests contributor needs to rely on the checks results to create expected results of render tests

From my initial experience with such a flow, there are two improvements I'd like to request:

- [x] Always include the actual rendering results in the artifact created for failing tests, including failures caused by a missing expected results or a mismatch in the size of the expected result.
- [x] Add a list of failing tests after their count. 
- [x] Add a description for running tests in GitHub to [`test/integration/README.md`](https://github.com/maplibre/maplibre-gl-js/blob/main/test/integration/README.md)

## Rationale
- Having the actual rendering result in the artifact, even if the expected is missing or otherwise inappropriate allows
   1. Visually check that the test produces the correct new expected result by looking at the test artifact
   2. Allow using the actual result from GitHub as the new expected result by saving the image from the test artifact
- It is not easy to find a few failing tests in a list of hundreds of passing tests
   ![image](https://github.com/maplibre/maplibre-gl-js/assets/1304610/ce4a4214-eb57-41da-b570-f72cc92f64ba)
- When tests fail on Github, users may not know where to look for details of the failures

## Impact

- Improve the effectiveness of test writing and lower the bar for tests contributors.
- Improve the effectiveness of debugging PRs render tests failures on GitHub

**Comment by HarelM** [comment]
Thanks for sharing your feedback!
The entire test execution and report (html) creation is done in a single file, it's very basic and doesn't use external libraries extensively.
https://github.com/maplibre/maplibre-gl-js/blob/f87a530804aac97765d16f72d26693ac27223fa6/test/integration/render/run_render_tests.ts#L681
Feel free to submit a PR against it.
