### ISSUE TITLE
Allow the use of GLSL 3.0 shaders for gradual migration

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#2576]
In order to gain the performance benefits WebGL2 has to offer through ie UBOs, the first thing that has to happen is updating all the shaders to [GLSL ES 3.0](https://registry.khronos.org/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf).

Some initial work has to happen to the shader compilation setup before the approx 60 shaders can be ported, and that initial work is what this ticket is all about.

We currently have a GLSL 1.0 _prelude, and some checks for GLSL 1.0 `attributes` etc. in the boilerplate, that makes it hard to do a gradual shader migration.

The aim of this ticket is to make our boilerplate (fragment/vertex compilation, program linking, prelude etc.) support GLSL 3.0 _and_ GLSL 1.0 shaders at the same time, so that we can migrate the shaders little by little instead of a big swap.

This is a prerequisite for actually porting the shaders  ( see #2562 )

In order to complete this ticket, it should be possible to add `#version 300 es` in the top of a shader and get access to GLSL 3.0 in that particular shader, while still allowing the remaining GLSL 1.0 shaders to compile and link.

It's possible to achieve this by modifying shaders.ts and program.ts - no changes to the _prelude's should be needed.

**Comment by birkskyum** [comment]
Up for unlocking this at an L

**Comment by HarelM** [comment]
Acceptance criteria:
One shader is converted to version 3 so that we know it's feasible while the other stay in version 1.
Let's complete this and reassess #2562 
Bounty direction: https://github.com/maplibre/maplibre/issues/270
