### ISSUE TITLE
While zooming in, raster layer doesn't cancel tile requests that are not needed resulting in slow loading of tiles

### ISSUE THREAD

**Issue by timsluis** [maplibre/maplibre-gl-js#2577]
Since version 3.0.0-pre.4, tile requests of a raster layer are not cancelled anymore when (quickly) zooming in. When zooming in quickly, many tiles will be loaded before the actually needed tiles are loaded resulting in a long wait before the raster images are shown. It might also use more data. I think the problem is introduced in this PR: https://github.com/maplibre/maplibre-gl-js/pull/2097.

**maplibre-gl-js version**: 3.0.0-pre.9

**browser**: Chrome 113.0.5672.126

### Steps to Trigger Behavior
 1. Load a raster source/layer, ie. Mapbox satellite. Open console on the network tab
 2. Open the map on a low zoom level, zoom in very quickly.
 3. Check the console for the large amount of consecutive requests and notice how long it takes before the images are shown (compared to maplibre 3.0.0-pre.3).

### Expected Behavior
Quickly showing the right raster images.

### Actual Behavior
A lot of requests happen after the right tiles are fetched, which results in a long wait before the images are shown.

**Comment by HarelM** [comment]
Might be related to the following fix: #2511

**Comment by timsluis** [comment]
Yes, you're right! Didn't scroll through the PR's, my bad. 

Any idea when it might be merged?

**Comment by HarelM** [comment]
If you can test to see that it solves the issue it will be great. There aren't a lot of comments there, hopefully soon.
Cc @pramilk .

**Comment by pramilk** [comment]
https://github.com/maplibre/maplibre-gl-js/pull/2511 is now ready for review. Sorry for delay, we were testing the fix internally to make sure there is no additional issues.

**Comment by birkskyum** [comment]
@timsluis , it'll likely be part of a 3.0 stable release within a few days.

**Comment by birkskyum** [comment]
Closed by #2511

**Comment by birkskyum** [comment]
@timsluis , you can use it now - v3.0.0
