### ISSUE TITLE
Basic Starter Example

### ISSUE THREAD

**Issue by curran** [maplibre/maplibre-gl-js#26]
## Motivation

People who want to get started with this do not have a quick startup guide or working example.

## Design Alternatives

Add a link in the README to either:

 * Startup guide page / tutorial, or
 * Working starter example in some hosted code place

### Implementation

Here's a working basic example: [VizHub: MapLibre GL Starter](https://vizhub.com/curran/b2df51fad8754d7197dd60fb55258a97)

I welcome you all to link to this, include it in this repo, port it into other platforms, etc.

**Comment by bothness** [comment]
I would strongly suggest that there should be a vanilla demo with map tiles that aren't from a commercial service that requires an access key (see my note [here](https://github.com/maplibre/maplibre-gl-js/issues/6#issuecomment-742431766))... ie. there should be a demo using OSM or Stamen raster tiles. I'm not sure if there are any vector tile sources that would meet this criteria. [NextZen](https://www.nextzen.org/) offers a free fair usage service, but still requires an API key.

**Comment by markgis** [comment]
Would the plan be to use an external docs site or use github docs? Should this thread be here - https://github.com/maplibre/maplibre-gl-js/issues/19 ?

I hope to have some time over weekend, so happy to get involved but currently don't know where we would be pushing any docs.

**Comment by curran** [comment]
My API key is in use in the demo linked from the README, and the traffic seems to overload the free tier.

![image](https://user-images.githubusercontent.com/68416/102103098-8e182f00-3dfa-11eb-81c7-5b3f5208bddc.png)

>map tiles that aren't from a commercial service

Yes please! What are some examples of freely served vector tiles with no API key?

**Comment by markgis** [comment]
@curran stamen has free key less map tiles. http://maps.stamen.com/

Looking at their readme they require attribution for use, they are under - CC BY 3.0 license.

I think someone has already started to fork the documentation, is it worth adding your example as a live demo to that?

**Comment by kylebarron** [comment]
[Carto also has key-less vector map tiles](https://carto.com/basemaps/)

> Our basemaps can be used for free in applications and visualizations for non-commercial use

**Comment by curran** [comment]
Demo linked from README is currently broken due to API key on free tier.

https://codepen.io/snickell/pen/dypOWzj

**Comment by bothness** [comment]
Hi all. I've put together a code pen based on @snickell's example, but with OpenStreetMap raster tiles (no need for a key). This style pattern should be easy to adapt for any raster tile source.

https://codepen.io/bothness/pen/ExgwzEG

I also changed the setup so that it loads the JS via an HTML script tag, to maximise browser compatibility for anyone who copy-pastes the code.

**Comment by LazerTiberius** [comment]
> @snickell Demo linked from README is currently broken due to API key on free tier.
> 
> https://codepen.io/snickell/pen/dypOWzj
> 
> @klokan has graciously offered a free API key for use here.
> 
> Perhaps the two of you can connect and instantiate a new API key in the demo?

It would be better if the example does not import into the global namespace and overwrite the native Map constructor.
