### ISSUE TITLE
API docs - validateStyle option should be boolean

### ISSUE THREAD

**Issue by ptomulik** [maplibre/maplibre-gl-js#2621]
It looks like there is a mistake in API docs:

https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/map.ts

the ``validateStyle`` option is described to be ``stiring``, but everything else suggests that it should rather be ``boolean``.

**Comment by HarelM** [comment]
Yup, seems like a typo here:
https://github.com/maplibre/maplibre-gl-js/blob/ff65fb3596c59130e460a12663acc02820b39e8e/src/ui/map.ts#L273
Feel free to submit a PR
