### ISSUE TITLE
mapbox-gl-draw demo display abnormal

### ISSUE THREAD

**Issue by CNFeffery** [maplibre/maplibre-gl-js#2626]
In the example of `mapbox-gl-draw` ( https://maplibre.org/maplibre-gl-js-docs/example/mapbox-gl-draw/ ), the control button displays abnormal as below:

![image](https://github.com/maplibre/maplibre-gl-js/assets/49147660/1a69c60f-4419-47a0-b1a5-9db8a38bc107)

And cannot trigger the drawing function properly🤔.

**Comment by HarelM** [comment]
Seems like a duplicate of #2601...?

**Comment by CNFeffery** [comment]
> Seems like a duplicate of #2601...?

Yes, the downgrade to version ^2.0.0 appears to have temporarily solved the problem.
