### ISSUE TITLE
Zoom in/out Clusters issue with fonts | or documentation update

### ISSUE THREAD

**Issue by koufopoulosf** [maplibre/maplibre-gl-js#2627]
Hello all,

Thank you very much for your valuable contribution on this library.

I have noticed this issue on the example of the official docs: https://maplibre.org/maplibre-gl-js-docs/example/cluster/

When we zoom in/out, it seems that this problem is caused:

![image](https://github.com/maplibre/maplibre-gl-js/assets/66564413/03e84eb1-1a80-4976-8943-275b7700671e)

Meanwhile, another implementation that I found: https://www.jawg.io/docs/integration/maplibre-gl-js/cluster/

Seems to solve that issue.

Do we know why is that happening on the first case and if it's fixable?

Thanks in advance for your valuable time.

Have a great day! :)

**Comment by koufopoulosf** [comment]
Thanks for the feedback! I will give it a try!

**Comment by Hamzakhan001** [comment]
@HarelM 

Thank you for your effort. I've used the same property you mentioned but it isn't bringing results.

`  map.addLayer({
            id: 'cluster-count',
            type: 'symbol',
            source: 'datapoints',
            filter: ['has', 'point_count'],
            layout: {
                   Some code here 
            },
            paint: {
                 "text-opacity-transition": {"duration":  0 ,  "delay":  0}
           }
         });`
         
   I've done the same for another layer that is actually displaying circles & property used there was:
   
   `"circle-opacity-transition": {"duration": 0 , "delay": 0}`

But not bringing any improvement.

**Comment by HarelM** [comment]
Bummer. The other example is using images (symbol layer) and not circles, it might explain why it works well, IDK, worth a shot...
You can also use supercluster and html elements instead.

**Comment by HarelM** [comment]
Yes, super cluster is a simple library to cluster stuff, it's platform independent.
The following uses Angular binding with supercluster and html clusters:
https://maplibre.org/ngx-maplibre-gl/demo/ngx-cluster-html
There's also this example, but it doesn't use supercluster as a separate library but uses the supercluster that is integrated into maplibre:
https://maplibre.org/maplibre-gl-js-docs/example/cluster-html/

**Comment by koufopoulosf** [comment]
@HarelM First link does not work.

So Maplibre internally uses and supports the same superclusters repo? (This one https://github.com/mapbox/supercluster)

Hm, I guess then we can style the clusters of the last example you mentioned?

Thanks!

**Comment by HarelM** [comment]
Go to https://maplibre.org/ngx-maplibre-gl/ click demo, search for cluster:
Not sure why the link is not working as expected... :-/
![image](https://github.com/maplibre/maplibre-gl-js/assets/3269297/8862ae97-d6cc-4001-9229-e942791c6c03)

**Comment by koufopoulosf** [comment]
@HarelM Accessing the previous link from mobile shows 404 File not Found. I turned desktop view on mobile to access the page.

**Comment by koufopoulosf** [comment]
I get this issue on mobile phone with desktop view (on mobile view it shows 404 Not Found): [https://ibb.co/6YtVxgb](url)

**Comment by HarelM** [comment]
I don't understand your last comments, sorry... Bottomline, you can use html with supercluster with maplibre or use a cluster source. there is a bug with the transition of the text vs transition of the circles, no argue here...

**Comment by koufopoulosf** [comment]
@HarelM What I said is that I cannot open this link from mobile phone as it shows 404 File not Found:

https://maplibre.org/ngx-maplibre-gl/demo/ngx-cluster-html

Okay, I will give it a try. Thanks!

**Comment by HarelM** [comment]
>Go to https://maplibre.org/ngx-maplibre-gl/ click demo, search for cluster:

I wrote this above the picture above...

**Comment by koufopoulosf** [comment]
Yep I found that, I mentioned in case it was a bug on mobile phones.

Can we use superclusters like the first video on maplibre-gl-js:

https://blog.mapbox.com/clustering-millions-of-points-on-a-map-with-supercluster-272046ec5c97

?

Thanks!

**Comment by birkskyum** [comment]
@koufopoulosf , yes you can do that.

**Comment by koufopoulosf** [comment]
@birkskyum if is there any tutorial on react + typescript on how to achieve that, I would really appreciate it 🙏

**Comment by birkskyum** [comment]
Just to clarify, do you ask how to use supercluster to generate the cluster data, or how to achieve a visual style like in the video.

**Comment by koufopoulosf** [comment]
@birkskyum how to achieve a visual style like in the video. Main issue for me is that on clusters of the official docs, there is a "bug" with the transition of the text vs transition of the circles. So solving that + using supercluster lib would be the best. If any react + typescript examples exist, that would be more than welcome!🙏

**Comment by birkskyum** [comment]
@koufopoulosf , this might help with the transition issue. https://codesandbox.io/s/react-map-cluster-w87mrc?file=/src/App.js

**Comment by koufopoulosf** [comment]
@birkskyum Thank you very much!!
