### ISSUE TITLE
There is no method `supported` available for MapLibre v3 any more

### ISSUE THREAD

**Issue by burantino** [maplibre/maplibre-gl-js#2628]
Hello! 

Problem description:

Last version of MapLibre (3.0) seems does not work on old systems (like Windows 7), at least i have one of the examples.
I presume it is connected with switching to the WebGL 2.
When i have tried to introduce graceful degradation for such an old systems, i realised that method `supported` referenced in [this example](https://maplibre.org/maplibre-gl-js-docs/example/check-for-support/) does not exist anymore.

Is it something intentional or we just forget to port this method for v.3.0?

**maplibre-gl-js version**:
3.0.1

**browser**:
all of them

### Steps to Trigger Behavior
 1. Open this [link](https://maplibre.org/maplibre-gl-js-docs/example/check-for-support/) :)

### Link to Demonstration
 1. Open this [link](https://maplibre.org/maplibre-gl-js-docs/example/check-for-support/) :)

### Expected Behavior
to have `supported` method on Map object

### Actual Behavior
there is no `supported` method on Map object

**Comment by HarelM** [comment]
It is intentional, the `supported` method can be used by referencing the relevant package, but the package is not relevant anymore to this project, there are other ways to test webgl2 that is not part of this package.

**Comment by HarelM** [comment]
See the breaking changes in the changelog of version 3.0:
https://github.com/maplibre/maplibre-gl-js/blob/main/CHANGELOG.md
Closing this issue, if you think there's an issue please specify it...

**Comment by burantino** [comment]
Should we fix samples page then? As it is just broken currently and creating this type of confusion :)

**Comment by HarelM** [comment]
Yes, sure, good idea! 
Feel free to open a PR against the docs repo to solve this.
