### ISSUE TITLE
[Typescript] _interpolationType is not defined anywhere?

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#264]
Part of Typescript migration.
The following property is used: `_interpolationType` in `symbol_style_layer.ts` but I couldn't find who sets it...
Might be a migration from older version thingy? I don't know.
I think the code around it should be removed...

**Comment by drwestco** [comment]
Just a typo? CompositeExpression has an interpolationType property, without the leading underscore.

**Comment by HarelM** [comment]
It might be a typo, but does this mean that currently this gets `undefined`? If so can't we simply pass undefined?
https://github.com/maplibre/maplibre-gl-js/blob/84f118deaa8a52a671db75ec6730abcace7742fd/src/style/style_layer/symbol_style_layer.ts#L129

**Comment by drwestco** [comment]
Yeah, to preserve current behavior, it's always undefined. Just wondering if there's some intended functionality that's been missing since this typo was introduced.

**Comment by HarelM** [comment]
I still want to research this...

**Comment by HarelM** [comment]
Waiting for the following PR to be merged: #1525
