### ISSUE TITLE
Style serialization will miss changes to paint properties that don't require re-layout

### ISSUE THREAD

**Issue by ChrisLoer** [maplibre/maplibre-gl-js#2651]
When @zhangyiatmicrosoft added lazy serialization in #2306, `_updateLayer` was modified to clear the in-memory serialization whenever a layer changed:

https://github.com/maplibre/maplibre-gl-js/blob/d9f276f9fa4960a91ebb502da7559f147f7a58dd/src/style/style.ts#L1195-L1197

The problem is that in `setPaintProperty`, we only call `_updateLayer` if the layer requires re-layout:

https://github.com/maplibre/maplibre-gl-js/blob/d9f276f9fa4960a91ebb502da7559f147f7a58dd/src/style/style.ts#L1071-L1074

I ran into this as a problem trying to change a layer's `raster-resampling` property back and forth between `nearest` and `linear` by updating the style JSON (ie using `setStyle`, not `setPaintProperty`). With the first change, from `nearest` to `linear`, the style diff picked up the change and modified the paint property, but it skipped clearing `this._serializedLayers`. Then, trying to change back to `nearest`, it diffed against the originally serialized value, didn't see any change, and didn't do anything.

I think the simple fix here is just to promote `this._serializedLayers = null` to be called either way in `setPaintProperty`, but it'd be nice to have @zhangyiatmicrosoft 's eyes on this to look for other cases where something like this might be necessary (I'm not very familiar with the original lazy-serialization PR and what kind of audit we did to figure out where the state had to be reset).

cc @ibesora

**Comment by ChrisLoer** [comment]
The workaround we're using is to reach into the map's private variables and explicitly clear `_serializedLayers` before we set the map's style, forcing a serialization every time (I believe getting us back pretty close to the MapLibre 2.x behavior).

**Comment by HarelM** [comment]
Let's wait for @zhangyiatmicrosoft 's input here.

**Comment by HarelM** [comment]
@zhangyiatmicrosoft can you please comment on this?

**Comment by HarelM** [comment]
@ChrisLoer will #3993 solve this? I can't get @zhangyiatmicrosoft response unfortunately...
