### ISSUE TITLE
Isometric projection

### ISSUE THREAD

**Issue by fr-an-k** [maplibre/maplibre-gl-js#2659]
## User Story

We developed an infrastructure/building project management app.

## Rationale

It would be preferable to be able to choose isometric (orthogonal) projection so that distance is equal everywhere.
Accurate insight in dimension and detail is important, for some common map uses as well, like choosing a route.
It would also enable a side view of 3d content, if the pitch setting allows.

It should be quite easy to change, probably just a few lines, but I don't know enough about orthogonal projection or maplibre internals.

## Impact

Low, but worth considering.

**Comment by wipfli** [comment]
Did you look into the `map.fow` option? See https://github.com/wipfli/field-of-view-demo
