### ISSUE TITLE
[Typescript] generate xxx_style_layer_properties.ts

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#266]
Before the typescript migration there were generated files, these files were generated from the style spec file in order to make sure the code, types etc are in sync.
After the migration to script this generated code is no longer working.
There's a question here if to invest time in making it work again or manually make sure the style and code are in sync.
The script(s?) are in the build folder (generate-struct-array.js and maybe more).
They also need conversion as they generated flow code and not typescript...

**Comment by HarelM** [comment]
Style spec is defined in a json file (v8.json) for example.
In order to have good typings in the code of this project this json file is converted to a series of generated typescript files. These files are referenced and allow safer implantations.
This is the part where we struggled with the typescript typings in the properties.ts file I think it was.
The codegen allows the code to reflect the spec automatically without any manual errors.

**Comment by wipfli** [comment]
Cool thanks!
