### ISSUE TITLE
Warning message EXT_sRGB extension not supported

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#2678]
Build latest main branch, "npm run start" and use broswer to hit debug page
http://localhost:9966/test/debug-pages/debug.html

Open dev tool and notice this warning on console:
<img width="361" alt="image" src="https://github.com/maplibre/maplibre-gl-js/assets/37553549/89056e2c-1a1f-4c6a-862d-9860757d0b78">

Very likely a remanent from
https://github.com/maplibre/maplibre-gl-js/pull/2656

@birkskyum BTW deeply appreciate the work to restore webgl1 support. I will collect more statistics ASAP.

**Comment by birkskyum** [comment]
Thanks for sharing this - you're very right that it's a remanent. This was an attempt to resolve an issue with the heatmap in webgl1, but it was eventually another change that made the difference.
