### ISSUE TITLE
Plugins breaking because of removed css class

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#2682]
I noticed mapbox-gl-draw is breaking, because it injects an element with classes `mapboxgl-ctrl-group mapboxgl-ctrl` which doesn't work after v3. We might have to fork a substancial amount of plugins due to this.

**Comment by birkskyum** [comment]
Found that for this specific plugin, a simple workaround of a adding the maplibre class does the trick.

```ts
map.addControl(Draw, "top-right");

const mapboxglControlGroup = document.getElementsByClassName(
  "mapboxgl-ctrl-group"
);

for (let i = 0; i < mapboxglControlGroup.length; i++) {
  let element = mapboxglControlGroup[i];
  element.className = "maplibregl-ctrl maplibregl-ctrl-group";
}
```

**Comment by HarelM** [comment]
I think this is somewhat related to #2601

**Comment by birkskyum** [comment]
Does indeed seem like a duplicate
