### ISSUE TITLE
Maplibre official website plugin error

### ISSUE THREAD

**Issue by bk201lucifer** [maplibre/maplibre-gl-js#2685]
[https://maplibre.org/maplibre-gl-js-docs/example/mapbox-gl-draw/](url)
This looks like a style issue
![maplibre](https://github.com/maplibre/maplibre-gl-js/assets/63433257/2f9a253b-70fb-45b1-9f2b-5615bff94388)

**Comment by HarelM** [comment]
That's probably the same issue as #2601 :-(

**Comment by bk201lucifer** [comment]
Yes, thank you
