### ISSUE TITLE
Add "npm run completion" for shell completion about test cases

### ISSUE THREAD

**Issue by typebrook** [maplibre/maplibre-gl-js#2686]
## User Story

I am trying to learn running tests in this repo.
Based on [integration/README.md]:
> To run a subset of tests or an individual test, you can pass a specific subdirectory to the test-render script. For example, to run all the tests for a given property, e.g. circle-radius:
$ npm run test-render circle-radius

Looks like there are hundred of valid test cases in `test/`, and it is hard to quickly check each subdirectory. To make typing test name faster, shell completion maybe useful here

## Rationale

Some modern CLI tool has subcommand to gernerate completion for a specific shell, for example: [hugo]
```bash
# Generate completion script for bash, and append to bashrc
hugo completion bash >>~/.bashrc

# Press tab for autocompletion
> hugo <TAB>                                                                                                                
completion       -- Generate the autocompletion script for the specified shell
config           -- Print the site configuration
convert          -- Convert your content to different formats
deploy           -- Deploy your site to a Cloud provider.
gen              -- A collection of several useful generators.
help             -- Help about any command
import           -- Import your site from others.
list             -- Listing out various types of content
mod              -- Various Hugo Modules helpers.
new              -- Create new content for your site
server           -- A high performance webserver
version     env  -- Print Hugo version and environment info
```

So in this case, maybe we can add a new npm script `completion`:
```bash
# Helper message about how to generate completion script, and how to use it in shell RC file
npm run completion

# Generate completion for zsh
npm run completion zsh >>~/.zshrc

# Quickly get test cases by autocompletions
npm run test-render <TAB>
tms
video
debug
image
empty
canvas
filter
within
extent
geojson
...
```

## Impact

This npm script only generate script for a specific shell to STDOUT, the purpose is just to make typing quickly when debugging. It won't affect anything else.

[integration/README.md]: https://github.com/maplibre/maplibre-gl-js/blob/main/test/integration/README.md#running-specific-tests
[hugo]: https://gohugo.io/commands/hugo_completion/

**Comment by HarelM** [comment]
Tests are folders... You can get auto complete using ,/-TAB- , can't you?

**Comment by typebrook** [comment]
Yes, default completion behavior of each shell works for pathname. But in this case, I need to type full path from root directory, for example:
```
> npm run test-render test/integration/render/tests/<TAB>
background-color/                  hillshade-shadow-color/            regressions/
background-opacity/                icon-anchor/                       remove-feature-state/
background-pattern/                icon-color/                        retina-raster/
background-visibility/             icon-halo-blur/                    runtime-styling/
basic-v9/                          icon-halo-color/                   satellite-v9/
```

And then manually delete `test/integration/render/tests/` to get valid test command:
```
> npm run test-render circle-radius/literal
``` 

The new completion script just make this flow faster.

**Comment by typebrook** [comment]
Oh...So `npm run` can be executed other than root folder. I didn't know that. Then I don't think new completion scripts are necessary. Sorry to bother...
