### ISSUE TITLE
Style serialization throws if called between `Map._updateStyle` and `Style._load`

### ISSUE THREAD

**Issue by ChrisLoer** [maplibre/maplibre-gl-js#2692]
When `Map._updateStyle` is called (from `setStyle`), it creates a new `Style` object that doesn't yet have a `stylesheet` property set, and then calls either `loadJSON` or `loadURL`, which run asynchronously:

https://github.com/maplibre/maplibre-gl-js/blob/67944511634488e7ff05fd9de6f9d3d455dc90ec/src/ui/map.ts#L1576-L1584

Only when they finish (on the next frame for the JSON version, later for the URL version) does the `stylesheet` property get set in `Style.load`:

https://github.com/maplibre/maplibre-gl-js/blob/67944511634488e7ff05fd9de6f9d3d455dc90ec/src/style/style.ts#L308-L309

In between those two points in time, any call to `Style.serialize()` will throw an exception when it tries to dereference properties of an undefined `stylesheet`:

https://github.com/maplibre/maplibre-gl-js/blob/67944511634488e7ff05fd9de6f9d3d455dc90ec/src/style/style.ts#L1162-L1171

I believe the right behavior in this case should be to return undefined, either from `Style.serialize()` or from `Map.getStyle()` (which already returns undefined if the style isn't set at all).

After diagnosing this and writing it up, it does feel like a pretty small edge case, but it showed up for us in our production app's error reporting because (1) it's possible for user input to trigger a style update that skips diffing (i.e. gets you into the state where `stylesheet` is temporarily undefined, and (2) we have interactive elements that query `getStyle()` (so users could fulfill both conditions with some bad luck). It's easy to workaround on our end just by peaking in to check for the `stylesheet` before calling `getStyle()`.

cc @ibesora and @zhangyiatmicrosoft (just because I tagged you on the earlier style serialization issue, although this one's not too closely related).

**Comment by HarelM** [comment]
Guarding this method when a style is undefined sounds like the right approach to me.
I'm not sure what triggers the `serialize`, but if it's a public API then it should be better guarded.
Would be nice to have a use case to talk about rather than reports that something failed though. :-)
In any case, please add a test when you fix this.

**Comment by ChrisLoer** [comment]
> Would be nice to have a use case to talk about rather than reports that something failed though. :-)

The case where it was failing for us is very idiosyncratic and easily worked around -- not really a use case, so much as us just running into something not working quite as expected. But the two things we have that trigger it are:

- A `setStyle` call that doesn't go through the normal diffed updated. Most things can diff in place, but some calls like `setSprite` require a style rebuild.
- We call `getStyle()` on every mouse move as part of our logic to determine which cursor to show (as part of logic that joins results from queryRenderedFeatures against our app's internal state). This wasn't really necessary -- it just happened to be the way the logic was implemented and it ended up stress-testing this pathway.

**Comment by HarelM** [comment]
Fixed by #2712
