### ISSUE TITLE
Remove "mapbox" strings from the codebase

### ISSUE THREAD

**Issue by curran** [maplibre/maplibre-gl-js#27]
## Motivation

There are instances of "mapbox" and "Mapbox" sprinled all throughout the codebase as variable names and in strings.

Also, in the `dist` directory, the output files still have "mapbox" in them.

The issue is that this suggests some connection to Mapbox, the company.

## Design Alternatives

It would be great to replace all instances of 
 * "mapbox" with "maplibre"
 * "Mapbox" with "Maplibre"

### Implementation

Phases:

 * [ ] Update built files published to NPM to not have mapbox in the name.
 * [ ] Update internal variable names that would not break anything.
 * [ ] Update class names in styles.

**Comment by nyurik** [comment]
We have been using `MapLibre` as the capitalized name. Otherwise sure, sounds good, just not as part of the first release.

**Comment by snickell** [comment]
I think this is the opposite of a good first issue, its very hard to do this well, particularly since its not something we're doing in the first release?

**Comment by nyurik** [comment]
> I think this is the opposite of a good first issue, its very hard to do this well, particularly since its not something we're doing in the first release?

thx, agree, at first i thought this was about documentation (i.e. comments)

**Comment by HarelM** [comment]
I still want to do this. It's progressing slowly but steadily.

**Comment by HarelM** [comment]
I've search and saw that there are about 4K mentions of mapbox in the code.
This will not be tracked by this issue.
We'll try our best to remove them as we go.
Closing...
