### ISSUE TITLE
Interrupting a scroll zoom causes the next scroll zoom to return to the prior zoom level

### ISSUE THREAD

**Issue by c-mirai** [maplibre/maplibre-gl-js#2709]
**maplibre-gl-js version**: 3.1.0

**browser**: Chrome

### Steps to Trigger Behavior
 1. Initiate a mouse wheel zoom
 2. Interrupt the zoom by calling map.stop(), map.flyTo(), map.jumpTo(), map.setZoom(), etc
 3. Change the zoom with another method, such as map.flyTo()
 4. Initiate another mouse wheel zoom

### Link to Demonstration

https://jsbin.com/gituvujaga/edit?html,js,output

### Expected Behavior

1. Scroll once. The camera zooms very far in.
2. Scroll again. The camera zooms in/out relative to where it currently is.

### Actual Behavior

1. Scroll once. The camera zooms very far in.
2. Scroll again. The camera snaps back to where it was when the zoom got interrupted.

As a workaround, deleting the `map.scrollZoom._targetZoom` property after interrupting the zoom yields the expected behavior.

**Comment by HarelM** [comment]
I'm unable to reproduce using the provided example, can you add a video of the issue?
Generally speaking, seems like a missing `reset` somewhere I guess...
Feel free to submit a PR that fixes this.

**Comment by c-mirai** [comment]
Here's a demo I recorded:

https://github.com/maplibre/maplibre-gl-js/assets/6272793/23eb5e6b-633f-48e7-a98e-cae431cefc05

It may be dependent on your specific mouse wheel. I'll try to make an example that doesn't depend on user input.

**Comment by c-mirai** [comment]
I could not figure out how to get the map to accept a synthetic WheelEvent, but here is a demo with some console output so we can see if the wheel events are somewhat similar.

https://jsbin.com/fivoqihepo/edit?js,console,output

https://github.com/maplibre/maplibre-gl-js/assets/6272793/866679a2-1ea7-454c-8c1a-e9a23eea927a

**Comment by HarelM** [comment]
I've looked at this issue again, and this can't be reproduced if the `flyTo` is not happening inside the `zoom` event.
You can try and reproduce it in the following example page where every time you scroll to the relevant article you initiate a flyTo, when stopping this `flyTo` using scroll, you are left in the expected position.
 https://maplibre.org/maplibre-gl-js/docs/examples/scroll-fly-to/
Let me know if I got it wrong.

**Comment by HarelM** [comment]
Ok, more digging into this and I found the root cause, I think:
The reason for this is that the state of zoom handler is not cleaned well.
It has a finished check that only if arrived the clear target zoom is applied.
When using flyto inside the zoom event, the state of the handler becomes corrupted since `reset` is being called but doesn't clear the state well.
So the solution is relatively simple - clear the state correctly in the `reset` method.
I'll open a PR shortly to fix this.
