### ISSUE TITLE
v3.0.1 - Error message running on Firefox

### ISSUE THREAD

**Issue by jwoodwardtfx** [maplibre/maplibre-gl-js#2713]
I've hit the following error when running MapLibre GL JS v3.0.1 in Firefox (specifically, GeckoView on Android).

![Error](https://github.com/maplibre/maplibre-gl-js/assets/18282135/b5772d2a-4c0e-4b03-91f2-6a0f24c6e3dd)

When this happens, it seems to get stuck in this state and this error seems to stop map tiles being loaded until the map is resized or reloaded. It doesn't always do this, normally when the map is being panned.

Previously, we have used MapLibre v2.4 and I don't believe we had this issue.

Any thoughts?

**Comment by HarelM** [comment]
Try 3.1, it might be related to webgl 1 stuff...

**Comment by jwoodwardtfx** [comment]
Just tried v3.1 and it behaves the same. I'll go back to v2.4 and see if I can reproduce on that, just to be sure.

It feels like it's getting stuck processing a tile, and that blocks the queue. The error message is repeated over and over every few seconds (see the attached screenshot). I set the map to track my location as I drove home, so there are not many tile requests going on, I assume there is an error each time it tries to load a new tile.

![ErrorsRepeated](https://github.com/maplibre/maplibre-gl-js/assets/18282135/ffc85fcb-4ad0-4cff-b75b-fa38420f9b7c)

I managed to get it to redraw and stop the error by zooming out, panning somewhere where tiles have never been loaded,  and going back to my location again. I wonder if doing this cause the tile queue to be emptied.

**Comment by jwoodwardtfx** [comment]
I've checked and can't reproduce this fault in 2.4 (so far). What more information do you need to root cause this?

**Comment by HarelM** [comment]
a jsbin and detailed steps to reproduce.
between 3.0 and 2.4 there where a bunch of pre-releases, I would recommend trying to find the last one that didn't fail and then hopefully find the commit that caused this issue.

**Comment by jwoodwardtfx** [comment]
Thanks, I'll try to do this. I'm working back through the versions to see where the issue was introduced. Just confirmed that the problem is present with **3.0.0-pre5**. The failure isn't deterministic and not easily repeatable, but I have reproduced on various makes/models of phones (running various builds of Android, with various versions of Firefox).

**Comment by jwoodwardtfx** [comment]
I've tested all the pre-releases back through to 3.0-pre.0. All show the issue, but I've also gone round and tested v2.4 again and can now get this one to show the issue as wekk. So, I've started looking in other places....

I titled this issue "Firefox", but, technically, we are using GeckoView (which is Mozilla's WebView for Android based on the same internals as Firefox).

We've moved from v108 to v114/v115 of the GeckoView component, and I now believe it is this that is causing this issue. I haven't managed to get v108 to fail (yet). I'll try and reproduce on stock Firefox, but the issue may specific go GeckoView.

To help with this, does anyone know what the piece of code that is generating the error is doing in MapLibre? Is it to do with tile loading/tile load cancellations?

**Comment by HarelM** [comment]
`r.blob` is probably related to some fetch request. But I don't see why this should fail, maybe the headers returned by the server?
If you can create a JSBin I might be able to have a better understanding of what went wrong...

**Comment by jwoodwardtfx** [comment]
I'm more certain this is a Firefox/GeckoView issue. Reverting to v108 of Firefox/GeckoView and the issue goes away.

I've started running with the debug build of MapLibre. What I see is that on rare occasions validateOrFetch() attempts to load a new tile, using a Request, but the returned Response from "then" promise to the fetch() isn't a Response at all, but an Exception. This Exception doesn't have a blob() function, hence the error I see reported by MapLibre.

This Exception is shown the Firefox console as: [Exception... "Success" nsresult: "0x0 (NS_OK)" location: "<unknown>" data: no] (at around line 1130 of the debug build of v3.1.0, inside validateOrFetch())

I'll see if I can get some traction from the Firefox team as to what is going on.

**Comment by HarelM** [comment]
Thanks for the update!
I'll be closing this issue now, if this is still a bug in this lib let me know and I'll reopen.

**Comment by dro0o** [comment]
@HarelM I'm also seeing this issue when reviewing tileserver-gl's tile viewers, which as of tileserver-gl 4.4.10 are using maplibre 2.4.0

I've noticed the issue only in Firefox and only while the wifi connection has been disabled.

**Comment by HarelM** [comment]
Without a reproduction there's little I can do...

**Comment by jwoodwardtfx** [comment]
I'm certain this is a Firefox/GeckoView issue. Please, push this with Mozilla, as I've not had a lot of traction on my ticket. It seems that newer Firefox is deciding not to bother trying to load resources if it's network manager decides there is no Wi-Fi/Cellular, which seems wrong as the content may be locally served.

**Comment by HarelM** [comment]
Did you open a ticket there?
I'll be happy to +1 it.

**Comment by jwoodwardtfx** [comment]
I've just checked, and it's not even been given a severity yet... It normally takes a few weeks for someone to pick it up. It may be that my issue is too specific to GeckoView (which is the component we use) and a ticket against Firefox-on-Android may get more traction.

https://bugzilla.mozilla.org/show_bug.cgi?id=1843001
