### ISSUE TITLE
[Typescript]: Test publish style-spec

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#275]
After typescript gets merged, we should test `publish-style-spec.yml` with a release candidate for example.

**Comment by wipfli** [comment]
Seems like publishing worked: https://www.npmjs.com/package/@maplibre/maplibre-gl-style-spec

**Comment by wipfli** [comment]
Is this now a pre-release or just a normal release? Does NPM even have the notion of pre-releases?

**Comment by HarelM** [comment]
I don't know. Good question. I think that people know they shouldn't use rc.1 if they want something stable, right...?

**Comment by wipfli** [comment]
One needs to run for example `npm publish --tag next` if one wants to avoid the new version being tagged as `latest`.
