### ISSUE TITLE
({  controls: { polygon: true... } }) doesn't draw tools

### ISSUE THREAD

**Issue by Vika22** [maplibre/maplibre-gl-js#2761]
Hello there.
Starting from 3.0 version I'm facing with issue to draw the polygon or dot using draw tools however it work fine for the previous version 2.4.
I'm also noticed that this functionality is not working on the sample provided on your site: https://maplibre.org/maplibre-gl-js-docs/example/mapbox-gl-draw/
Could you please confirm that functionality wasn't removed in new release version and it still works fine?

Thank you.

**Comment by HarelM** [comment]
Duplicate of #2601
