### ISSUE TITLE
Code Splitting based on functionality used

### ISSUE THREAD

**Issue by andreapernici** [maplibre/maplibre-gl-js#277]
## Motivation

Considering the growing importance of speed and the upcoming Core Web Vitals metric usage in Google could be a good idea to let developers include only needed features in the js bundle reducing a lot the weight of it in most of the cases.

## Design Alternatives

Code splitting.

-------------

Something similar to this https://twitter.com/Firebase/status/1430586974318989315

**Comment by HarelM** [comment]
We are in the final stages of migrating to typescript so this might be better handled going forward.
Having said that, I'm not sure how to push such an effort.
If you would like to push this forward feel free. I world suggest to start with a design document to present the required changes.
 Good luck :-)

**Comment by StephenStrickland** [comment]
@HarelM is there a ETA on typescript, maybe a site/branch where we can monitor progress? @andreapernici are you interested in heading this effort up?

**Comment by wipfli** [comment]
We merged the typescript pull request into main. Pre-releases of version 2 are on NPM. Best place to monitor status is probably the changelog.

**Comment by wipfli** [comment]
This seems related to named exports. See the discussion in #623.

**Comment by HarelM** [comment]
I'm not sure named exports will solve this.
It requires a more granular approach to architecture and design - exporting a map object that does everything is exactly the opposite for example.
Unfortunately, I don't think we know the code good enough to support this at the moment.
This is somewhat similar to this request #166 - i.e. be able to use just part of this library or part of the funcionality.
We should aim to get there, but I don't think we are right now... :-(
