### ISSUE TITLE
Sample script to show the vector layer doesn't work

### ISSUE THREAD

**Issue by Ajiro3** [maplibre/maplibre-gl-js#2771]
Hi,
The sample script shown in
https://maplibre.org/maplibre-gl-js-docs/example/third-party/
doesn't work.
Please let me know the way to fix it.
![MapLibre_vectorError](https://github.com/maplibre/maplibre-gl-js/assets/132320670/76bf5619-9691-421b-835e-e3e3a60462e0)

**Comment by HarelM** [comment]
The tiles are restricted in some places. You need map tiler key or another source of tiles.
The demo is an iframe that shows that this works...
