### ISSUE TITLE
The sample script to add a third paty vector tile doesn't work

### ISSUE THREAD

**Issue by Ajiro3** [maplibre/maplibre-gl-js#2773]
**maplibre-gl-js version**: 3.1.0

**browser**: Edge

### Steps to Trigger Behavior

 1. Copy the scripts shown in https://maplibre.org/maplibre-gl-js-docs/example/third-party/
 2. Set my maptiler token into the script
 3. Only base map of Chaicago is displayed.
 4. There are errors shown on the consol of Edge. (Attached PNG file)

### Expected Behavior
Draw some lines by the vector data from the server.
![VectroServer_AccError](https://github.com/maplibre/maplibre-gl-js/assets/132320670/3192e4af-8b64-41ca-9bbd-fd8093e866e9)

### Actual Behavior
Only base map is shown.

**Comment by HarelM** [comment]
Please use the discussion section for trouble shooting problems.
The issues are for real issues.
Slack is even better for that.
Maptiler tiles are working as expected, also the console error is self explanatory.

**Comment by wipfli** [comment]
Thanks @Ajiro3 for reporting this error. See the linked issue in the documentation repo maplibre-gl-js-docs for more info. We keep problems with the docs website in the maplibre-gl-js-docs repo and problems with the actual library maplibre-gl-js here in this repo... 

My guess is that Mapillary changed an API path. But let's see.
