### ISSUE TITLE
 Bring in the docs repo - CI

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#2776]
Acceptance criteria:
1. On each CI run the docs build process is ran and checked that there are no errors or warnings
2. When running a release pipeline the docs are build and push to gh-pages branch. note that gh-pages branch is not empty and should be kept that way - we are pushing some build artifact there.

Part of #2150 
@cc: @krishnaglodha

**Comment by krishnaglodha** [comment]
Hi, so once the mkdocs build is done, where should the folder go ?

**Comment by HarelM** [comment]
In github pages, I don't know if it should be in a docs folder or not though...

**Comment by krishnaglodha** [comment]
We can use https://squidfunk.github.io/mkdocs-material/publishing-your-site/#material-for-mkdocs to directly push to gh-pages but I believe it'll remove previous content

**Comment by HarelM** [comment]
There is valuable data there, please check it on a repo you create to make sure other content is not removed.
If the content is removed, then a folder in the gh pages would probably be the right solution.

**Comment by krishnaglodha** [comment]
ok, I'll test first 
and keep you posted

**Comment by krishnaglodha** [comment]
<img width="1496" alt="Screenshot 2023-07-05 at 11 21 26 AM" src="https://github.com/maplibre/maplibre-gl-js/assets/47075664/811d1e94-888a-4999-a0f1-7e38d4960d69">
It replaces everything in `gh-pages` 

but after `mkdocs build` we get `site` folder which I think we can use to point github pages manually

**Comment by HarelM** [comment]
What about base-href? base folder? I'll be surprized if this is not supported at all.
But in case it's not, we can copy the `site` folder to gh-pages as part of the build process, it should be complicated.
I would advise to try that in your repo as well...

**Comment by krishnaglodha** [comment]
base as in you mean root folder ?

**Comment by HarelM** [comment]
There is the base-href - where the folders will be relative to the host it will published in.
There is the base folder where the docs will be in the gh-pages.
I expect there should be a configuration for each separately.

**Comment by krishnaglodha** [comment]
ok, so now I'm working on CI, which will essentially add a `site` folder to current gh-pages branch

**Comment by krishnaglodha** [comment]
Hi @HarelM , I'm getting 
```
remote: Permission to krishnaglodha/maplibre-gl-js.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/krishnaglodha/maplibre-gl-js/': The requested URL returned error: 403
``` 
in my CI file

**Comment by HarelM** [comment]
Bounty was removed as I ended implementing this.
