### ISSUE TITLE
TypeScript: Use 'typeof' to refer to class contructors

### ISSUE THREAD

**Issue by drwestco** [maplibre/maplibre-gl-js#279]
In the TypeScript conversion, the following substitution was made:

    constructor(LayoutArray: Class<StructArray>,
    constructor(LayoutArray: {
      new (...args: any): StructArray
    },

Pretty sure the 'new' syntax can be simplified to:

    constructor(LayoutArray: typeof StructArray,  

_Originally posted by @drwestco in https://github.com/maplibre/maplibre-gl-js/pull/209#discussion_r698527817_

**Comment by drwestco** [comment]
Existing syntax (with `new (...args: any)` may be correct, though there's room for improved readability here.
See also first answer at https://stackoverflow.com/questions/13407036/how-does-interfaces-with-construct-signatures-work

**Comment by HarelM** [comment]
This seems like a good improvement, keeping it open for now...

**Comment by wipfli** [comment]
@drwestco what is your plan for this one? Should we leave it closed?
