### ISSUE TITLE
TypeScript: Enforce consistent member delimeters

### ISSUE THREAD

**Issue by drwestco** [maplibre/maplibre-gl-js#280]
Turn on member-delimiter-style rule to enforce consistent use of TypeScript-preferred semicolon member delimeters:

https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/member-delimiter-style.md

_Originally posted by @drwestco in https://github.com/maplibre/maplibre-gl-js/pull/209#discussion_r698518951_

**Comment by HarelM** [comment]
This was fixed as part of #209.
