### ISSUE TITLE
Unimplemented type: 3 with tippecanoe tiles

### ISSUE THREAD

**Issue by Ajiro3** [maplibre/maplibre-gl-js#2809]
**maplibre-gl-js version**: maplibre-gl@3.1.0

**browser** :Edge

### Steps to Trigger Behavior
 1. Get OSM data with JOSM
 2. Convert OSM data to pbf with osmosis tool
 3. Convert pbf file to geojson
 4. Create the tiled pbf directory from this geojson with tippecanoe and -e option
 5. The tiled pbf directory is the style of {z}/{x}/{y}.pbf
 6.  Set the tiled pbf directory as a local server with IIS on Windows
 7.  Add the tiled directory as a vector layer with MapLibre

### Link to Demonstration
I can visualize this tiled pbf directory as a vector layer with QGIS.

### Actual Behavior
![MapLibre_error](https://github.com/maplibre/maplibre-gl-js/assets/132320670/246acdf4-b4d1-49a3-ba4c-f3fc793dee41)

**Comment by bdon** [comment]
You probably need to configure IIS to return the `Content-Encoding: gzip` header, otherwise the browser doesn't know the tile is gzipped; or use the `--no-tile-compress` tippecanoe option

**Comment by HarelM** [comment]
This is probably one of the worst messages we have... :-(
Would be great to improve that message to say - expected gzipped content but didn't get it or the other way around...
Checking for gzip is easy...

**Comment by sebastianoscarlopez** [comment]
The pbf library raises the message error.
 https://github.com/mapbox/pbf/blob/bfaaa5daea7e2a57e5e0b22cca75037113000e33/index.js#L211

**Comment by HarelM** [comment]
I'm sure we can try-catch it here and return a better error message or open a PR to the other library with an improved error message...

**Comment by HarelM** [comment]
I've created a PR in order to improve the situation around this issue and the error message.
Does anyone here has a server I can test with in order to see this issue before I merge?

**Comment by bdon** [comment]
@HarelM you should be able to output a small directory of tiles from tippecanoe, and upload it to s3 without setting proper Content-Encoding header metadata, and see the error.

**Comment by HarelM** [comment]
Any chance you can help me with that?

**Comment by bdon** [comment]
https://r2-public.protomaps.com/tmp/countries/{z}/{x}/{y}.pbf

maxzoom is 2

let me know when I can delete it

**Comment by HarelM** [comment]
Thanks!! You can remove it I believe. The following is the new error:
<img width="1403" alt="image" src="https://github.com/maplibre/maplibre-gl-js/assets/3269297/ee14c756-cb8d-49ab-bfe2-23cdb1d8e989">
I think it's a good improvement. :-)
