### ISSUE TITLE
TypeScript: Simplify type signature for uninitialized variables

### ISSUE THREAD

**Issue by drwestco** [maplibre/maplibre-gl-js#281]
TypeScript conversion created this awkward syntax:

From:
`    let nextNormal = ((undefined: any): Point);`

To:
`    let prevVertex = undefined as Point;`

This reads better as:
`    let prevVertex: Point = undefined;`

Or just:
`    let prevVertex: Point;`

Search for the `undefined as xxx` or `null as xxx` pattern to find and fix any similar awkward initializations.

_Originally posted by @drwestco in https://github.com/maplibre/maplibre-gl-js/pull/209#discussion_r698516391_

**Comment by HarelM** [comment]
Closed as part of #209
