### ISSUE TITLE
Some vector tile styles are not displayed when using v3.1.0

### ISSUE THREAD

**Issue by dayjournal** [maplibre/maplibre-gl-js#2812]
**maplibre-gl-js version**: v3.1.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. When using v3.1.0, some vector tile styles are not displayed on the screen after setting.

### Expected Behavior
Styles appear correctly on the screen.

### Actual Behavior
Styles do not appear correctly on the screen.
With v2.4.0, everything is displayed correctly.

- OSM style is OK.
  - https://tile2.openstreetmap.jp/styles/osm-bright/style.json
- Basic style of MapTiler is not a problem.
  - https://api.maptiler.com/maps/basic-v2/style.json?key=[APIKey]
- MIERUNE style of MapTiler is not displayed.
  - https://api.maptiler.com/maps/a592c75a-d9ab-4027-b1d3-68cad51d4233/style.json?key=[APIKey]
- The HERE style of Amazon Location Service is not displayed.
  - https://maps.geo.[region].amazonaws.com/maps/v0/maps/[URL]/style-descriptor?key=[APIKey]

MIERUNE style in MapTiler
![スクリーンショット 2023-07-07 14 24 11](https://github.com/maplibre/maplibre-gl-js/assets/7871642/e8940b8a-1df5-45bd-a979-30b48ad972a3)

HERE style in Amazon Location Service
![スクリーンショット 2023-07-07 14 25 28](https://github.com/maplibre/maplibre-gl-js/assets/7871642/ea495894-5edc-49f7-8dbe-3666df2c5e19)

**Comment by Kanahiro** [comment]
I made demo with MapTiler official style.
https://cloud.maptiler.com/maps/jp-mierune-streets/

v2.4.0
https://jsbin.com/jeworijugu/edit?html,output

v3.1.0
https://jsbin.com/vowuhegepu/edit?html,console,output

**Comment by HarelM** [comment]
Thanks for the info!
I believe this is related to a recent change in the color parsing logic.
Cc: @kajkal @ChrisLoer

**Comment by kajkal** [comment]
Currently, we use a [custom color](https://github.com/maplibre/maplibre-style-spec/blob/601ab81d03dde7ff339319f4aebbcd0724aa04f0/src/util/parse_css_color.ts) parser that does not allow leading or trailing spaces. So `" rgba(220, 230, 200, 1)"` is treated as invalid. A simple `.trim()` [here](https://github.com/maplibre/maplibre-style-spec/blob/601ab81d03dde7ff339319f4aebbcd0724aa04f0/src/util/parse_css_color.ts#L33) should be enough to fix this.
I will open a PR soon.

**Comment by HarelM** [comment]
@kajkal Can you open a PR against this repo with the version bump in order to resolve this issue?
