### ISSUE TITLE
Cooperative gestures example

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#2819]
After the introduction of cooperative gestures https://github.com/maplibre/maplibre-gl-js/pull/1234, it would be great to have an example demonstrating this new feature.

**Comment by HarelM** [comment]
I can assign a S bounty to this if anyone is interested.

**Comment by visitskyworld** [comment]
@HarelM can I take this one?

**Comment by HarelM** [comment]
Sure

**Comment by visitskyworld** [comment]
INVOICE: https://opencollective.com/maplibre/expenses/149451

**Comment by HarelM** [comment]
Great! Thanks!
