### ISSUE TITLE
Update supported example

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#2822]
Due to the removal of `supported` this example should be updated:
https://maplibre.org/maplibre-gl-js-docs/example/check-for-support/
It's worth adding some simple code to solve this instead of a full package...

**Comment by HarelM** [comment]
Assigning S bounty.
Bounty direction:
https://github.com/maplibre/maplibre/issues/191

**Comment by visitskyworld** [comment]
@HarelM  @wipfli can I take this one?

**Comment by visitskyworld** [comment]
@HarelM `supported` is now removed from `maplibregl`. Then how do we check if `maplibregl` is supported in the browser?

**Comment by HarelM** [comment]
You can also take a look at the supported package code, it's open.

**Comment by visitskyworld** [comment]
INVOICE: https://opencollective.com/maplibre/expenses/149452

**Comment by HarelM** [comment]
Thanks!!
If you happen to see other things that need to be addressed that are related to documentation, performance, 3D or any of the other bounty directions here:
https://github.com/maplibre/maplibre/labels/bounty%20direction
Feel free to open an issue and request a bounty assignment, I'll be happy to allocate.
