### ISSUE TITLE
Add documentation on best practices for working with large datasets

### ISSUE THREAD

**Issue by jokroese** [maplibre/maplibre-gl-js#2823]
I'm using maplibre-gl-js to map a relatively large dataset. However, within maplibre-gl-js there's not any documentation on how to do this well.

After searching, I found a [Mapbox help page on the topic](https://docs.mapbox.com/help/troubleshooting/working-with-large-geojson-data/#store-geojson-at-url). I assume that most of the tips carry across to maplibre-gl-js. I also started a discussion page to collect best practices (https://github.com/maplibre/maplibre-gl-js/discussions/2319).

As large datasets are part of many mapping projects, it would be good to have a collection of these best practices within the maplibre-gl-js documentation. I'm imagining that this could look similar to Mapbox's help page, with some maplibre-gl-js specific examples.

**Comment by mikebelanger** [comment]
What's the status of this?  Could these best practices be a subsection [here](https://maplibre.org/maplibre-gl-js/docs/)?  Until there's a more rounded out tutorials section.

**Comment by HarelM** [comment]
If it's not too long it can be in the intro, otherwise, we can place it somewhere else.
But I think the main gap here is actually writing it, if there's an article about it we'll find where to place it...
It can even be written here in github as a reference to be placed somewhere else...

**Comment by jokroese** [comment]
I had the time to start writing this last week and now have a collection of best practices I've found. As digital mapping isn't my background, there are a few that I'm still trying to understand!

I was also wondering the same thing about where to put this so that I can create a branch and PR with it. Should I just add it as a markdown file to the `docs/` folder and then we figure it out from there?

**Comment by HarelM** [comment]
Yes, let's start like that.

**Comment by jokroese** [comment]
I've created a PR with a first draft of a guide on working with large GeoJSON datasets (https://github.com/maplibre/maplibre-gl-js/pull/3307). If any of you want to have a look over it, I'd appreciate it!

To house it, I created a 'Guides' section which I felt could also accommodate other topics like best practices for accessibility.
