### ISSUE TITLE
improved Minimap

### ISSUE THREAD

**Issue by wiesehahn** [maplibre/maplibre-gl-js#2829]
Often it is nice to have a Minimap to give an overview of the current map view in a different scale. 

Currently the suggested option to do so is via the plugin developed for mapbox.
https://github.com/aesqe/mapboxgl-minimap

However, the shown view extent is very simplified if the map is tilted (it does not show the actual view extent with wider field of view in the distance) and it dies not account for rotated map view. 

As the code was modified in 2020 for the last time it might be nice if this could be improved for maplibre in the future.

**Comment by HarelM** [comment]
You are more than welcome to fork and update it.
I'll be happy to add that new plugin to the docs.
Unfortunately, I don't think this code should be part of this repo.

**Comment by birkskyum** [comment]
@wiesehahn , it has also since been possible to keep two maps in sync reactively like this [this](https://maplibre.org/news/2023-05-23-maplibre-gl-js-v3/#transformcameraupdate) - so that is an alternative approach with a lot of room for customization.

**Comment by birkskyum** [comment]
Closing as a fork of the plugin wouldn't be a change to this repository.
