### ISSUE TITLE
Custom markers are broken in 3.2.0

### ISSUE THREAD

**Issue by dbrnz** [maplibre/maplibre-gl-js#2855]
**maplibre-gl-js version**:
v3.2.0

**browser**:
Any

### Steps to Trigger Behavior
Go to the MapLibre's [custom markers example](https://maplibre.org/maplibre-gl-js/docs/examples/custom-marker-icons/).

### Link to Demonstration
As above.

### Expected Behavior
Kitten faces should show on the markers.

### Actual Behavior
Standard markers are shown.

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue!
The example is using a non-documented construction of passing an HTMLElement to the consturctor.
The solution is to pass to the marker the element with a parameter: `new Marker({element: el})`.
I'll change the example.
I've added that in the changelog as well:
https://github.com/maplibre/maplibre-gl-js/blob/main/CHANGELOG.md#-features-and-improvements-1
