### ISSUE TITLE
Warn against using underscore-prefixed symbols

### ISSUE THREAD

**Issue by 1ec5** [maplibre/maplibre-gl-js#2861]
The new documentation pages include entries for formerly private methods that are prefixed with an underscore, such as [`_applyUpdatedTransform`](https://maplibre.org/maplibre-gl-js/docs/API/classes/maplibregl.Map/#_applyupdatedtransform). To my knowledge, these methods are not intended to be used by consumers of the library in general, although some plugins use them by necessity. They should either be hidden by default or appropriately marked, so that developers unfamiliar with the underscore convention won’t inadvertently depend on an unstable part of the API. External usage beyond plugins could make it more difficult to ensure backwards compatibility going forward. Even prefacing the description with the word “Internal” would be sufficient I think.

**Comment by HarelM** [comment]
The right thing to do from a code perspective is to mark those as private.
Having said that, there was a request not to do it as part of #333.
The other option is to add `@hidden`, `@internal` or `@private` to all these method/properties in order to exclude them from the docs.

Setting M bounty.
Bounty direction:
https://github.com/maplibre/maplibre/issues/191

**Comment by visitskyworld** [comment]
@HarelM can I take this one?

**Comment by HarelM** [comment]
I think @ZeLonewolf is currently working on it.
But there's a lot to solve in the docs besides this issue.
Go ahead and explore them so you could suggest other improvements.

**Comment by 1ec5** [comment]
#2861 addresses my concern with respect to the underscore-prefixed symbols by hiding them. I wasn’t suggesting a runtime warning, just a ⚠️ warning message in the documentation, but hiding the symbols from the documentation has the same effect as far as downstream developers are concerned.

#2916 is a follow-up issue for internal types.

**Comment by HarelM** [comment]
Resolved by #2863
@ZeLonewolf you are welcome to submit an expense in open collective to collect your bounty.
If you don't plan to do so, please let me know and I'll remove the bounty from this issue.
THANKS!

**Comment by ZeLonewolf** [comment]
I do not intend to seek a bounty.
