### ISSUE TITLE
Custom Markers are broken with v3.2.0

### ISSUE THREAD

**Issue by jwoodwardtfx** [maplibre/maplibre-gl-js#2864]
Go to the custom marker example page at https://maplibre.org/maplibre-gl-js/docs/examples/custom-marker-icons/

The custom markers used to be images of kittens (in v3.1.0), now it's just the default blue tear drop (in v3.2.0).

I've seen the same regression in my own projects using custom markers.

**Comment by HarelM** [comment]
Duplicate of #2855
