### ISSUE TITLE
Features with identical location: only one is displayed when using GeoJson source

### ISSUE THREAD

**Issue by DNikitenko** [maplibre/maplibre-gl-js#2866]
In my project there can be multiple features sharing the same location. For example:
```
map.addSource('some id', {
   type: 'geojson',
   data: {
       "type": "FeatureCollection",
       "features": [
        {
           "type": "Feature",
           "properties": {
               "DeviceId": "ed1a8845-c707-40e8-89d5-0b68511a0df6",
           },
           "geometry": {
               "type": "Point",
               "coordinates": [
                    [
                        -16.3669383,
                        33.0629733
                    ]
                ]
           }
       },
       {
           "type": "Feature",
           "properties": {
               "DeviceId": "f9b5f838-a35f-403d-9d7d-0a50574868aa",
           },
           "geometry": {
               "type": "Point",
               "coordinates": [
                    [
                        -16.3669383,
                        33.0629733
                    ]
                ]
           }
       }]
   }
});
```

**maplibre-gl-js version**: 3.2.0

**browser**: Google Chrome 114.0.5735.199

### Expected Behavior
All the features within the same location are rendered.

### Actual Behavior
When using GeoJSON source, only one of them is rendered (returned by the `queryRenderedFeatures` method), however it works fine with vector tiles.

**Comment by HarelM** [comment]
I would guess that the problem is with geojson-vt package in the worker source, but I guess you'll need to look into it.
Can you share a jsbin or stackblitz example for this issue?

**Comment by DNikitenko** [comment]
I created a snippet and... it works. Found a bug in my application. Sorry for bothering :)
