### ISSUE TITLE
Marker displacement when switching between 2D and 3D view   

### ISSUE THREAD

**Issue by jashanbhullar** [maplibre/maplibre-gl-js#2868]
**maplibre-gl-js version**: latest/main branch 

**browser**: Mozilla Firefox 114.0 20230605223242 20230605223242 

### Steps to Trigger Behavior

 1.On your local branch `npm start`
 2.Open `3d-Terrain.html` 
 3.Add the following marker 
```javascript 
        const marker = new maplibregl.Marker()
            .setLngLat([11.39067, 47.305513])
            .addTo(map);
```
4. Switch between 2D and 3D, the underlying map changes position but not the marker 
5. Moving the map fixes the marker's position 

### Link to Demonstration

https://output.jsbin.com/vatekax#11.9/47.28354/11.40553/0/52
https://jsbin.com/vatekax/2/edit?html,output

### Expected Behavior
The marker should be at right place when switching between 2D and 3D view 

### Actual Behavior
The marker doesn't change it's screen position but the underlying map does when switching between views 

[Screencast from 16-07-23 04:06:20 PM IST.webm](https://github.com/maplibre/maplibre-gl-js/assets/20891087/a2639ca0-65cc-47b3-8eab-114a54e6f9c6)

Found when working on this: https://github.com/maplibre/maplibre-gl-js/issues/1134 
Might be related

**Comment by visitskyworld** [comment]
@HarelM  can I take this one?

**Comment by HarelM** [comment]
@jashanbhullar, are you working on those?

**Comment by jashanbhullar** [comment]
Yes @HarelM . I am working on all the issues related to markers! Will mention them here!

**Comment by HarelM** [comment]
Sorry @visitskyworld, since @jashanbhullar opened the issues and asked to work on them I will assign them to him.
If you happen to find other issues either already open or that needs to be reported and you would like to have a bounty assigned to them let me know.

**Comment by HarelM** [comment]
@jashanbhullar where are we with these bugs?
It's been over a month, and I haven't seen any PR related to these issues.
