### ISSUE TITLE
Marker opacity doesn't change when switching from 3D to 2D

### ISSUE THREAD

**Issue by jashanbhullar** [maplibre/maplibre-gl-js#2869]
**maplibre-gl-js version**: latest/main branch 

**browser**: Mozilla Firefox 114.0 20230605223242 20230605223242  

### Steps to Trigger Behavior

 1.On your local branch `npm start`
 2.Open `3d-Terrain.html` 
 3.Add the following marker 
```javascript 
        const marker = new maplibregl.Marker()
            .setLngLat([11.39067, 47.305513])
            .addTo(map);
```
4. Go behind the mountain, the marker will be less visible 
5. Switch to 2D, the marker still remains it's original opacity 

### Link to Demonstration

https://output.jsbin.com/vatekax#11.9/47.28354/11.40553/0/52
https://jsbin.com/vatekax/2/edit?html,output

### Expected Behavior
The marker should be opaque when switched to 2D from 3D

### Actual Behavior
The marker opacity doesn't change when switching from 3D to 2D

[Screencast from 16-07-23 04:14:11 PM IST.webm](https://github.com/maplibre/maplibre-gl-js/assets/20891087/fa346c44-1e1f-4cfc-88aa-4ff501790bd3)

Found when working on this: https://github.com/maplibre/maplibre-gl-js/issues/1134 
Might be related

**Comment by visitskyworld** [comment]
@HarelM can I take this issue?

**Comment by HarelM** [comment]
Same as the other one, sorry...

**Comment by SnailBones** [comment]
Is anyone working on this? I'd be interested unless @visitskyworld or @jashanbhullar still wants to go for it!

> Same as the other one, sorry...

@HarelM Is this the same issue as #1134? If so perhaps this one should be closed so they can be tracked in one place?

**Comment by HarelM** [comment]
No, same response as #2868 

I'm not aware of any current effort to solve these bugs.
The previous bug was closed, but there are still more bugs in this area.

Since I didn't see any progress lately, feel free to take it.

**Comment by SnailBones** [comment]
https://opencollective.com/maplibre/expenses/176000
