### ISSUE TITLE
Marker opacity changes before it's behind the mountain

### ISSUE THREAD

**Issue by jashanbhullar** [maplibre/maplibre-gl-js#2870]
**maplibre-gl-js version**: latest/main branch 

**browser**: Mozilla Firefox 114.0 20230605223242 20230605223242 

### Steps to Trigger Behavior

 1.On your local branch `npm start`
 2.Open `3d-Terrain.html` 
 3.Add the following marker 
```javascript 
        const marker = new maplibregl.Marker()
            .setLngLat([11.39067, 47.305513])
            .addTo(map);
```
4. Change the angle so are somewhat looking at horizon, move close the mountain
5. The opacity of the marker changes even before it's behind the mountains

### Link to Demonstration

https://output.jsbin.com/vatekax#11.9/47.28354/11.40553/0/52
https://jsbin.com/vatekax/2/edit?html,output

### Expected Behavior
The marker visibility should only change when completely behind the mountain

### Actual Behavior
The opacity of the marker changes even before it's behind the mountains

[Screencast from 16-07-23 04:37:27 PM IST.webm](https://github.com/maplibre/maplibre-gl-js/assets/20891087/07e65570-4ea6-434f-9454-3789494684cb)

Found when working on this: https://github.com/maplibre/maplibre-gl-js/issues/1134 
Might be related

**Comment by SnailBones** [comment]
@HarelM I'm interested in this

**Comment by HarelM** [comment]
Good luck!

**Comment by SnailBones** [comment]
Thanks @prozessor13! I've implemented a second visibility check as you suggest in https://github.com/maplibre/maplibre-gl-js/pull/3431.
