### ISSUE TITLE
Marker flies off in the distance when chaning view angles 

### ISSUE THREAD

**Issue by jashanbhullar** [maplibre/maplibre-gl-js#2871]
**maplibre-gl-js version**: latest/main branch 

**browser**: Mozilla Firefox 114.0 20230605223242 20230605223242 

### Steps to Trigger Behavior

 1.On your local branch `npm start`
 2.Open `3d-Terrain.html` 
 3.Add the following marker 
```javascript 
        const marker = new maplibregl.Marker()
            .setLngLat([11.39067, 47.305513])
            .addTo(map);
```
4. Change the angle so are somewhat looking at horizon
5. The marker flies off to the horizon 
6. Comes back when looking at more perpendicular view angle 

### Link to Demonstration

https://output.jsbin.com/vatekax#11.9/47.28354/11.40553/0/52
https://jsbin.com/vatekax/2/edit?html,output

### Expected Behavior
The marker should not fly off but should remain at the same place

### Actual Behavior
The marker flies off to some random distance 

[marker-flies-off-low.webm](https://github.com/maplibre/maplibre-gl-js/assets/20891087/dcaaf7cd-2b02-4e74-a200-2e44515b1814)

Found when working on this: https://github.com/maplibre/maplibre-gl-js/issues/1134 
Might be related

**Comment by tbo47** [comment]
I can not reproduce with Firefox 115.3.0esr (64-bit). Is it still a bug?

**Comment by HarelM** [comment]
@sbachinin let me know if you would like to collect the bounty.

**Comment by sbachinin** [comment]
@HarelM, yes

**Comment by HarelM** [comment]
Make sure to follow this guide:
https://maplibre.org/roadmap/step-by-step-bounties-guide/

**Comment by sbachinin** [comment]
https://opencollective.com/maplibre/expenses/191778

**Comment by HarelM** [comment]
THANKS!
FYI @wipfli.
