### ISSUE TITLE
Breaking changes v2.0.0

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#288]
Version 2.0.0 of this library is coming soon. The migration to Typescript removes support for internet explorer and the public API does not expose the version anymore. See `CHANGELOG.md` of the `typescript` branch.

Breaking changes that most likely will follow are:

* Removal of `accessToken` support
* Removal of the Mapbox CSS classes

**Comment by HarelM** [comment]
This is a great heads up! But shouldn't it be a discussion and not an issue?

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/discussions/290
