### ISSUE TITLE
Raster DEM sources are not serialized correctly

### ISSUE THREAD

**Issue by neodescis** [maplibre/maplibre-gl-js#2889]
Currently any Raster DEM source is not serialized correctly. When serialized, the source will not pass style validation when used again. This is because undefined values are included in the serialization, which do not pass validation. This behavior comes from [here](https://github.com/maplibre/maplibre-gl-js/blob/main/src/source/raster_dem_tile_source.ts#L46). Given that all properties for this source type are optional, a potential fix would be to filter the returned object's properties by whether their values are undefined.

**maplibre-gl-js version**: 3.2.0
**browser**: Chrome 114

### Steps to Trigger Behavior

 1. Set map style to something with a raster DEM source
 2. Serialize the map style
 3. Set the map style to the serialized value
 4. See errors in console

### Link to Demonstration

https://jsbin.com/danosah/edit?html,output

### Expected Behavior

No crash

### Actual Behavior

Crash

**Comment by HarelM** [comment]
Thanks for taking the time to report this!
Feel free to open a PR to fix this, sounds like an easy fix in general.
