### ISSUE TITLE
MapLibre 3.2.0 Typing Errors

### ISSUE THREAD

**Issue by neodescis** [maplibre/maplibre-gl-js#2896]
I'm trying to upgrade our project from 3.1.0 to 3.2.0, but I'm running into a few typing problems and cannot build against the new version.

1. The maplibre-gl.d.ts typings file now references supercluster. The supercluster package does not provide its own typings, and MapLibre only lists @types/supercluster as a dev dependency, so the typings for it are not installed with MapLibre. We have noImplicitAny set to true for our project, so this import fails to build. Can we elevate the @types/supercluster package to a regular dependency since it is now part of the public API?
2. In the exported Hash class, there is now a member function typed like this: `_updateHash: () => NodeJS.Timeout;`. Not only does this not build for me, but the typing looks incorrect since this code isn't running on Node. I'm not sure where the type is coming from though.
3. The generated typing for event handlers is broken because the order of the signatures of the Map's "on" function changed, with the most generic version now being listed first. In some cases I'm now seeing the type of my handler function as "any", and in some cases I'm seeing it as all-the-things. Manually changing the declaration order in the .d.ts file back to what it was fixes this.

**maplibre-gl-js version**: 3.2.0

**browser**: N/A

**Comment by neodescis** [comment]
I'm happy to work a PR for these. @HarelM , would you have any idea where the typing for #2 above is coming from?

**Comment by HarelM** [comment]
No clue, maybe an issue with dts bundle generator or the tsconfig, but I'm just guessing...

**Comment by HarelM** [comment]
Feel free to push this forward, I'm planning a new release soon, let me know if you would like to push this through fast so it will be included.

**Comment by neodescis** [comment]
I can at least knock out 1 and 3. I'll investigate 2 further and see if I can figure it out.

**Comment by HarelM** [comment]
I don't see these issues in any of the libraries I maintain, so it's worth making sure this is covered in tests somehow, much like I did with the tsconfig for the dist `d.ts` file.

**Comment by neodescis** [comment]
I'll have a PR up in a sec and we can discuss there... not sure how 1 and 2 would be covered by tests.
