### ISSUE TITLE
Quickstart using npm

### ISSUE THREAD

**Issue by rbrtmrtn** [maplibre/maplibre-gl-js#2899]
Hello! Thank you for all the awesome work on this project :)

I typically add MapLibre GL JS to new projects with npm. (I use Vue and, more recently, Svelte).

I find myself not remembering the steps for getting the SDK added and bootstrapping a map. I was thinking it could be helpful to others as well to have this documented in an additional/alternative "quickstart" to the CDN version.

**Comment by HarelM** [comment]
Maplibre is a pure js library, I believe most wrappers have their quickstart guide according to technology.
The awesome-maplibrec repo holds some of them.

**Comment by rbrtmrtn** [comment]
Hi @HarelM, I see what you mean that for some folks it may make more sense to use a component / wrapper for the frontend framework they're using. The `awesome-maplibre` repo looks like a great resource 👍 

My perhaps my line of thinking was more: if MapLibre GL is an npm package, and if you can `npm install maplibre-gl`, maybe that one-liner should be in the docs. The framework I use (Vue) isn't listed in the `awesome-maplibre` repo, and I imagine there are other scenarios where someone wants to install just Maplibre, but not a third-party binding.

As another point of reference, the Mapbox GL [quickstart](https://docs.mapbox.com/mapbox-gl-js/guides/install/#quickstart) has this npm snippet (which I use with some regularity):

![image](https://github.com/maplibre/maplibre-gl-js/assets/1463553/03cb6275-b8af-41a6-9c88-241b84204b57)

**Comment by HarelM** [comment]
Sure! Feel free to open a PR to update the readme of the repo.
Also worth adding a note to the readme of the docs folder which will be presented here:
https://maplibre.org/maplibre-gl-js/docs/
Thanks!

**Comment by HarelM** [comment]
Closing this issue, a PR can be opened regardless to improve the docs at any point in time.
