### ISSUE TITLE
Check if MapLibre GL JS is supported does not detect whether WebGL is disabled

### ISSUE THREAD

**Issue by gio0v** [maplibre/maplibre-gl-js#2912]
For my web application, it is very important that I detect when users have WebGL either not supported or disabled, such that I can make our pages display a Leaflet or OpenLayers fallback. However, the official example of how to detect whether MapLibre GL JS is supported (in which effectively what is being detected is if WebGL is supported and enabled) seems to fail to detect when I disabled browsers' WebGL hardware acceleration.

**maplibre-gl-js version**:
3.2.1

**browser**:
Chrome 115.0.5790.102, Firefox 102.0.1, Vivaldi 6.1. 3035.111

### Steps to Trigger Behavior

 1. I disabled WebGL hardware accelerator in Chrome, Firefox and Vivaldi.
 2. I re-launched the 3 browsers and checked that the change went through.
 3. I setup the code sample from https://maplibre.org/maplibre-gl-js/docs/examples/check-for-support/ open the page in a browser (I tried Chrome, Firefox and Vivaldi)
 4. the map from that example is generated (albeit very slow to use), instead of catching the try-catch error that would identify that WebGL is supported but disabled.

### Link to Demonstration
I am literally just running the official code sample that checks if MapLibre GL JS is supported:
https://maplibre.org/maplibre-gl-js/docs/examples/check-for-support/

### Expected Behavior
Catching an error to identify that WebGL is supported but disabled.

### Actual Behavior
With all 3 browsers, the map from that example is generated (albeit very slow to use), because the code is not detecting that WebGL is disabled.

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue!
This is a new addition to the docs as we have removed the supported package that was used in the past.
If you think this should be better defined or altered please feel free to submit a PR to update this example.

**Comment by zhangyiatmicrosoft** [comment]
> Thanks for taking the time to report this issue! This is a new addition to the docs as we have removed the supported package that was used in the past. If you think this should be better defined or altered please feel free to submit a PR to update this example.

No change in the control is needed. Just pass true for failIfMajorPerformanceCaveat when creating map. (Default is false)
It will fail if browser is in a "software" mode.
https://github.com/maplibre/maplibre-gl-js/blob/01e5f51cf15421cb40ad0ff4798f8f536f816a0c/src/ui/map.ts#L590

The check for support sample (https://maplibre.org/maplibre-gl-js/docs/examples/check-for-support/) could be updated with the same option.

**Comment by HarelM** [comment]
@zhangyiatmicrosoft can you make a PR with this fix? The example is here:
https://github.com/maplibre/maplibre-gl-js/blob/01e5f51cf15421cb40ad0ff4798f8f536f816a0c/test/examples/check-for-support.html

**Comment by zhangyiatmicrosoft** [comment]
> @zhangyiatmicrosoft can you make a PR with this fix? The example is here: https://github.com/maplibre/maplibre-gl-js/blob/01e5f51cf15421cb40ad0ff4798f8f536f816a0c/test/examples/check-for-support.html

Software mode is a well-supported mode though by all means.

**Comment by HarelM** [comment]
Not sure I understand the last comment, can you make a PR against the above file?

**Comment by HarelM** [comment]
Can this issue be closed then?

**Comment by neodescis** [comment]
As written, I think the issue can be closed. The example mentioned does not detect if WebGL is using software rendering, but as @zhangyiatmicrosoft points out, that should not be confused with whether MapLibre is supported. So, I agree that the example should not be updated to add that check.

However, we could certainly add another example that checks if WebGL is using software mode, using the failIfMajorPerformanceCaveat option.

**Comment by HarelM** [comment]
A comment in the current example seems like the right solution to me - telling the user that `failIfMajorPerformanceCaveat` can be used too.
