### ISSUE TITLE
将多种自定义图标显示在海图上

### ISSUE THREAD

**Issue by dbc1129** [maplibre/maplibre-gl-js#2917]
想要将海图上的符号用canvas画出来并且转换成图片缓存起来，再通过后端给的数据获取相应的位置进而将缓存的图片放上去，这种操作可以在maplibre上完成吗？

**Comment by HarelM** [comment]
Please write in English, otherwise, please close the issue.

**Comment by typebrook** [comment]
@dbc1129

Yes, you can. Maplibre use sprite file to define icons in style, you may be interested about related spec or tools:
https://maplibre.org/maplibre-style-spec/sprite/
https://github.com/mapbox/spritezero-cli

If you don't know where to ask, visit [community](https://maplibre.org/community/) list and ask community.

可以，Maplibre 使用 sprite 檔案來自訂地圖中使用的圖標，相關的文件和工具可見：
https://maplibre.org/maplibre-style-spec/sprite/
https://github.com/mapbox/spritezero-cli

提 issue 前可以先在 [community](https://maplibre.org/community/) 列表中，找到適當的管道徵詢意見。

總之請先關掉這個 issue，這並不屬於 Bug Report 或 Feature Request 的範籌。

**Comment by wipfli** [comment]
We have to be careful to use a language which everyone can understand, so let's only communicate in English on GitHub. Thank you for understanding that his is a hard requirement for all questions / contributions.
