### ISSUE TITLE
`queryRenderFeature` emits `Out of bounds.` Error in 3.2.1 version 

### ISSUE THREAD

**Issue by marucjmar** [maplibre/maplibre-gl-js#2923]
Hi,

I noticed that in version 3.2.1 there is an "Out of bounds" error. The error does not always occur because race condition occurs in the code. After a brief investigation, I determined that a change from this PR #1874 caused the problem. 

**maplibre-gl-js version**: 3.2.1

**browser**: all

### Steps to Trigger Behavior

 1. Init map with vector styles
 2. Add empty GeoJSON source to map after load event
 3. Add symbol layer with created source
 4. Add mouse event listener
 5. Update the source by `setData` method
 6. Trigger mouse event on symbol from this layer or use `queryRenderedFeatures` on layer

### Link to Demonstration

[fiddle](https://jsfiddle.net/fpt35enj/)

https://github.com/maplibre/maplibre-gl-js/assets/5881368/df665528-bdd5-470d-9f35-9b1d9961eb7b

### Expected Behavior
No error

### Actual Behavior
`Out of bounds.` Error

**Comment by HarelM** [comment]
Cc @ambientlight

**Comment by ambientlight** [comment]
Hm, interesting, will investigate this later today and follow-up here.

**Comment by HarelM** [comment]
I've just noticed this too, I can reproduce this issue on my app relatively easily.
When I move back to version 3.2.0 the error is not there, but it happens all the time on my app with version 3.2.1.
@ambientlight please update soon, otherwise I'll need to revert and publish a new version.

**Comment by ambientlight** [comment]
@HarelM: let me see if I can send a PR with a fix today, if not, let's revert it then.

**Comment by HarelM** [comment]
This looks solved now in 3.2.2.
Thanks @ambientlight!!

**Comment by ambientlight** [comment]
@HarelM: thanks for the timely heads-up here!
