### ISSUE TITLE
when layout.visibility = "none" when layers are added to the map, their visibility can never be changed

### ISSUE THREAD

**Issue by spelexander** [maplibre/maplibre-gl-js#2936]
Hi! First off thanks for maintaining this incredible piece of open source software.

when layout.visibility = "none" for a new layer added to the map, that layer can never be rendered. Even if it's visibility is later updated to "visible"

You can see in the minimal example the layers visibility value is changed but it can never be rendered. Even if forcefully re-rendering the map.

**maplibre-gl-js version**: 3.2.1 (But I've confirmed this happens as far back as 2.4.0)

**browser**: Chrome 115

### Steps to Trigger Behavior

 1. Add a layer to a map with `layout: { visibility: "none" }`
 2. Later (after map is idle) try: `layer.setLayoutProperty("visibility", "visible")` or `layer.visibility = "visible"`

### Link to Demonstration

https://jsbin.com/febibulute/edit?html,console,output

### Expected Behavior

The layer should render on the map.

### Actual Behavior

The layer is never rendered on the map.

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue!
Seems like this is not the first issue with set paint property...
Feel free to investigate and open a PR. 😀

**Comment by spelexander** [comment]
I'll see if I can get a PR up with a fix. Diving into the codebase for the first time, do you have any tips/ideas on where the culprit might be?

**Comment by drwestco** [comment]
`layer.setLayoutProperty` is not part of the public API. Change that line to `map.setLayoutProperty("circle", "visibility", "visible")`, and the sample works as expected.

**Comment by drwestco** [comment]
#2916 affects this. These non-public methods shouldn't be in the .d.ts file or public documentation.

**Comment by HarelM** [comment]
Ahh, missed that part, I thought the example uses the map and not the layer...
Can this be closed then?
