### ISSUE TITLE
The declared type of `Map.getLayer()` doesn't match the documentation or behaviour

### ISSUE THREAD

**Issue by RoystonS** [maplibre/maplibre-gl-js#2968]
**maplibre-gl-js version**: 3.3.0

**browser**: N/A

### Steps to Trigger Behavior

 1. Write code that calls `map.getLayer()`.
 2. According to the declared TypeScript types, it returns an object of type `StyleLayer`, despite its documentation saying it will return a layer if present, and `undefined` otherwise. Some linters and type analytics then complain if the result is checked against `undefined`, as the declared type says it _can't be_ `undefined`.

### Link to Demonstration

N/A (It's a compile-time typing issue that won't demonstrate via jsbin.com.)

### Expected Behavior

* `Map.getLayer()` should be defined as returning `StyleLayer | undefined`, as documented, instead of `StyleLayer`.  `Map.getSource()` gets this correct, returning `Source | undefined`.

(The same is true of `Style.getLayer()`, similarly.)

### Actual Behavior

* `Map.getLayer()` returns something of type `StyleLayer`, indicating that it will _not_ return `undefined`, despite the documentation stating that it can return `undefined`.

### Notes

I'm happy to put a PR together to fix this.

**Comment by HarelM** [comment]
PRs are more than welcome :-)

**Comment by RoystonS** [comment]
PR is #2969
