### ISSUE TITLE
[Feature request]Custom select webgl version

### ISSUE THREAD

**Issue by zouyaoji** [maplibre/maplibre-gl-js#2970]
## User Story

Can the user choose the webgl version when initializing the map? I currently still have a lot of shaders that use webgl1, but the new version uses webgl2 by default, and only the v2 version uses webgl1. So I hope to add a parameter webgl2: boolean when initializing the map

```
       const gl =
         this._canvas.getContext('webgl2', attributes) as WebGL2RenderingContext ||
         this._canvas.getContext('webgl', attributes) as WebGLRenderingContext;

         if (!gl) {
             const msg = 'Failed to initialize WebGL';
             if (webglcontextcreationerrorDetailObject) {
                 webglcontextcreationerrorDetailObject. message = msg;
                 throw new Error(JSON. stringify(webglcontextcreationerrorDetailObject));
             } else {
                 throw new Error(msg);
             }
         }

         this.painter = new Painter(gl, this.transform);
```

**Comment by HarelM** [comment]
There are a lot of places in the code this affects, and maintaining those is a hassle we would like to avoid...
I don't see a good way to solve this unfortunately... 😕

**Comment by zouyaoji** [comment]
Thank you, I understand, it seems that only the 2.4 version is currently in use. Or upgrade my shaders to webgl2. Is it enough to upgrade glsl100 to glsl300? I use the "twgl.js" auxiliary library to create textures, buffers, and programs. I have upgraded my shaders to glsl300, but there are still errors.

![3P@J3NX}MD0_YC$O@QGB9NF](https://github.com/maplibre/maplibre-gl-js/assets/24430116/4a9dc139-0b05-48bb-96be-c9ded5ee7de9)

**Comment by HarelM** [comment]
@birkskyum can probably explain this better than I can...

**Comment by birkskyum** [comment]
Hi, all our shaders are still compiled down to glsl100 before they are executed, so you should be fine

**Comment by zouyaoji** [comment]
![image](https://github.com/maplibre/maplibre-gl-js/assets/24430116/e60c422a-570a-4b49-8c70-4f8d8ed6b166)

Yes, as shown in the above image, can you identify the reason? The same code works fine on Mapbox. If possible, I can prepare a demo that reproduces this issue and upload it to GitHub. Would you mind taking a look and providing assistance?

**Comment by birkskyum** [comment]
It would be great with a repro of maplibre 2.4 and 3.x to investigate

**Comment by zouyaoji** [comment]
OK, please wait, I need to take a moment to get some sensitive information out. I'll report back once I'm ready.

**Comment by zouyaoji** [comment]
@birkskyum 

Please go to https://github.com/zouyaoji/vue-map-demo and clone the repository.
```bash
pnpm install
pnpm dev
```

Then you can reproduce the issue by accessing http://localhost:3200/.

However, accessing the Mapbox map route renders correctly at http://localhost:3200/mapbox.

Stop the program and install maplibre-gl@2 version. After that, accessing http://localhost:3200/maplibre-gl should also work correctly for the project.

```bash
pnpm add maplibre-gl@2
pnpm dev
```

**Comment by birkskyum** [comment]
@zouyaoji , excellent, thanks!

**Comment by zouyaoji** [comment]
@birkskyum I should also thank you, and I hope you can point out whether this is an issue with my code or a bug in maplibre-gl.

**Comment by birkskyum** [comment]
@zouyaoji , if you add `useWebGL2: true,` to the mapbox example, it'll break as well. I'm still trying to figure how to add webgl2 support for this.

**Comment by birkskyum** [comment]
I made a PR to your repository with a way for you to get this working.

**Comment by zouyaoji** [comment]
Wow, that's really cool! You've been a big help. Thank you so much!

**Comment by zouyaoji** [comment]
If you encounter similar issues when working with WebGL textures, you can try setting the internalFormat of the texture to RGBA32F when creating it. This might help avoid certain problems.
