### ISSUE TITLE
White flickering on resize in version 3.x.x

### ISSUE THREAD

**Issue by predirector** [maplibre/maplibre-gl-js#2971]
**maplibre-gl-js version**:
3.3.0 and 3.2.0
**browser**:
Firefox & Chrome
### Steps to Trigger Behavior

 1. Resize your browser with a full screen map

### Expected Behavior
Does not flicker. 
Especially because the behaviour in 2.4.0 on resize was better. Only the resized area was rerendered but not the complete map. 

### Actual Behavior
In Firefox is flickers very heavy on resize. In Chrome it gets completely white for a short time.

Thank you

**Comment by HarelM** [comment]
This has changed recently to better support container resize and not just window resize.
The following PR is the relevant one I believe: #2157.
It might be that there's a need to throttle this event, IDK.
Feel free to suggest a solution.

**Comment by neodescis** [comment]
It does seem to behave a lot nicer if a debounce is used; I tried it with 50 milliseconds. Should it be configurable?

**Comment by HarelM** [comment]
I'm not sure this should be configurable, but then hardcoded stuff tend to make their way to being configurable... IDK...

**Comment by neodescis** [comment]
I agree. I'll start with 25 or 50, whatever seems like it works best, and we can go from there.
