### ISSUE TITLE
Update code to use MapLibre

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre-gl-js#3]
Update all code to use MapLibre. Fork any libraries that are no longer open source, or keep referencing MapBox's libs if they still are.

**Comment by snickell** [comment]
As discussed with @nyurik , we should probably defer this for our second release, first release's priorities are "build is solid+reliable, easy to switch to by a string replace, remove trademarks from human visible bits, doesn't break, published to npm asap"

**Comment by HarelM** [comment]
What's the status of this bug?
I believe this was implemented, wasn't it? Are there more items in this issue that we would like to push forward?
