### ISSUE TITLE
Proposal: Support custom sources

### ISSUE THREAD

**Issue by ibesora** [maplibre/maplibre-gl-js#3022]
Note: Although the title is similar to [this issue](https://github.com/maplibre/maplibre-gl-js/issues/29), it's nothing like that.

## Current problem
Maplibre currently uploads all raster tiles with an RGBA internal format to the GPU. (see the hardcoded value [here](https://github.com/maplibre/maplibre-gl-js/blob/3e6aa0dbd6794831fba689b6ec07a1091c1b8e59/src/source/raster_tile_source.ts#L155)). RGBA is an unsigned-byte format, unsigned-byte values are "interpreted" as values ranging from 0.0 to 1.0 and only support sampling them as floating-point values (see [section 8.8](https://registry.khronos.org/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf) in the GLSL ES 3.0 spec). 

This makes it impossible to make a custom layer that works on raster tile sources and that uses any other kind of sampler. To do that, we'd need to implement a custom source that uploads the texture to the GPU with another internal format... but that doesn't seem possible right now.

The motivation to do so is that the conversion from unsigned byte to float is lossy and depends on the supported precision on the GPU so converting back the unsigned integer from the floating-point value might not result in the exact same value. This would be solved if we could use an unsigned integer sampler instead. Terrain-RGB encoded raster tiles would also benefit from this.

## Proposed solution
Similar to what @ChrisLoer proposed as one of the solutions to https://github.com/maplibre/maplibre-gl-js/issues/2507, having a way to plug-in custom source types would allow us to do this kind of thing without having to add it as a core part of Maplibre. 
In my head I can see it working like this:
```js
class CustomSource implements Source {
  ...
  loadTile(tile: Tile, callback: Callback<void>) {
    // New functionality here
  }
}
 
map.addCustomSource("uint-raster", CustomSource);
```

At Felt we have a use case for this and would like to see something like this, where we could plug-in custom behavior (which might not be useful for anybody else) to Maplibre instead of adding it to the core, as a big win.

**Comment by HarelM** [comment]
Can addProtocol along side custom layer solve this?

**Comment by acalcutt** [comment]
The addProtocol way for this sounds similar to the test page I made to generate color-relief and contour lines from TerrainRGB, like this test page https://wifidb.net/demo/contours/isolines-worker.html. Is that type of on the fly editing of a RGBA what you are tryin to do? This was based on the examples in the MIERUNE [interview article](https://maplibre.org/news/2022-06-10-mierune-announcement/), where they generated terrainrgb from a different format.

**Comment by ibesora** [comment]
> Can addProtocol along side custom layer solve this?

I don't think so. It's not that we want to change the fetched data in any way (which @acalcutt test is a good example of), we want to change how it's uploaded to the GPU which happens after the `loadFn` in `addProtocol` is resolved.

To be more precise we want to be able to change the implementation of the callback in https://github.com/maplibre/maplibre-gl-js/blob/3e6aa0dbd6794831fba689b6ec07a1091c1b8e59/src/source/raster_tile_source.ts#L137 and create a different texture object than what's currently done there. We would need access to the gl context and `Tile`

**Comment by HarelM** [comment]
What about this method?
https://github.com/maplibre/maplibre-gl-js/blob/50b88a82e1e00323612150022aca7ca1ca2f1e0d/src/ui/map.ts#L2055

**Comment by ibesora** [comment]
Yeah, I was just looking at that. I'll try to hack something with it tomorrow and see if that fits our needs.

**Comment by HarelM** [comment]
This was never properly documented. If you happen to succeed it will be great if you could share this example somehow, maybe as one of the examples in this repo.

**Comment by HarelM** [comment]
I've refactored the code around custom sources as part of version 4, added some documentation and I hope now it's possible to some extent.
Closing this issue. Feel free to request to reopen if the definition of what is needed is more detailed.
