### ISSUE TITLE
Map zooms to the wrong area when double clicking 

### ISSUE THREAD

**Issue by acalcutt** [maplibre/maplibre-gl-js#3048]
When trying to zoom in by double click, sometimes I am zoomed into a location on the other side of the world (for example, clicking australia it might zoom into africa or the altlantic ocean). This seems to only happen when 3d terrain is enabled.  I am told in slack maybe this has to do with the antimeridian line, which makes sense since it seems to occur when the map center is to the right of this line and I am clicking to the left of it.

**maplibre-gl-js version**:

**browser**:

### Steps to Trigger Behavior

 1. Go to https://stackblitz.com/edit/web-platform-whmqdc?file=index.html
 2. Double click australia to zoom in. when it zooms in it brings you to the altlantic ocean

### Link to Demonstration
Here is an example video using the [3d terrain example page](https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/)

https://github.com/maplibre/maplibre-gl-js/assets/3792408/949b8110-0a49-406d-a10b-5daa15e4cb84

### Expected Behavior

Double clicking austrailia should zoom into austrailia 

### Actual Behavior

Double clicking austrailia zooms into the atlantic ocean

**Comment by HarelM** [comment]
Thanks for reporting this issue!
Can you create some code that demonstrate this in a reproducible way - since double clicking requires a specific place it might be hard to reproduce for someone reading this in the future.

**Comment by acalcutt** [comment]
For now I at least added a better test page at https://stackblitz.com/edit/web-platform-whmqdc?file=index.html

That centerpoint seems to consistently bring me somewhere else when i double click anywhere near austrailia 

https://github.com/maplibre/maplibre-gl-js/assets/3792408/919ba87c-9f24-456e-b0be-8ab3a83b1323

**Comment by friendlymatthew** [comment]
May I take on this issue?

**Comment by HarelM** [comment]
Sure, let me know if you would like me to assign a bounty as well.

**Comment by tguen** [comment]
It looks to me like this happens any time the map center and the mouse click location are on opposite sides of the 180th meridian. I'd bet this results in a longitude value outside the -180 to 180 range being set to zero.
