### ISSUE TITLE
Map Popup is in wrong position when zoomed out (SolidJS)

### ISSUE THREAD

**Issue by Ali5937** [maplibre/maplibre-gl-js#3067]
When you set a popup on the map, at certain coordinates and zoom out, the popup shows up at the bottom of the map. 
For example: I set a popup to be at the position of Rome (Italy) [12.49, 41.9]. Initially the popup is in the Antarctica. If I zoom in further the popup slowly moves towards Rome. When fully zoomed in the popup is actually in Rome, where it should be.

**maplibre-gl-js version**: "maplibre-gl": "^3.3.1",

**browser**: Chrome

### Stackblitz Example
https://stackblitz.com/edit/solidjs-templates-ewy3yi?file=src%2FApp.tsx,src%2Findex.css 

### Steps to Trigger Behavior

 1. Start a new SolidJS project with Typescript
 2. npm i maplibre-gl
 3. Add the following code into App.tsx

```import { onMount, type Component } from "solid-js";
import maplibregl from "maplibre-gl";
import logo from "./logo.svg";
import styles from "./App.module.css";

const App: Component = () => {
	let map: maplibregl.Map;
	let mapContainer: HTMLDivElement;

	// Create a ref function to get the reference to the mapContainer element
	const mapContainerRef = (element: HTMLDivElement) => {
		mapContainer = element;
	};

	onMount(() => {
		map = new maplibregl.Map({
			container: mapContainer,
			style: `https://tiles.stadiamaps.com/styles/${"alidade_smooth_dark"}.json`,
			center: [0, 0],
			zoom: 2,
			minZoom: 2,
			maxZoom: 20,
			attributionControl: false,
		});

		let popup = new maplibregl.Popup({
			className: "my-class",
		})
			.setLngLat([12.49, 41.9])
			.setHTML("<h1>This Popup should be in Rome</h1>")
			.setMaxWidth("300px")
			.addTo(map);
	});

	return (
		<div class={styles.App}>
			<div ref={mapContainerRef} class={`map`}></div>
		</div>
	);
};

export default App; 
```

 4. Zoom in to see the popup move upwards towards Rome

Here is an image of what the problem looks like:
![rome-popup](https://github.com/maplibre/maplibre-gl-js/assets/116338481/e77faa99-5f23-4ee9-8ee2-b4690de3c307)

### Expected Behavior
The popup should always be exactly over Rome

### Actual Behavior
The popup starts out at the bottom of the map and moves closer to where it should go, the more you zoom in.

**Comment by HarelM** [comment]
Can you reproduce this without solidjs?

**Comment by Ali5937** [comment]
> Can you reproduce this without solidjs?

Here it is in React:
https://stackblitz.com/edit/stackblitz-starters-vciamu?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx,src%2Fstyle.css&title=React%20Starter

**Comment by HarelM** [comment]
I don't see that maplibre css  is loaded in any of the examples you provided, which probably explains this issue.
