### ISSUE TITLE
Globe view - Earth is not flat

### ISSUE THREAD

**Issue by Gustavo22Soaresh** [maplibre/maplibre-gl-js#307]
## Motivation
Hello, I think it would be interesting when zooming out instead of duplicating the merchant projection it would be nice to show the view of the entire globe, similar to google earth and the new Apple Maps

## Design Alternatives

[![i-OS-15-Maps-Feature.jpg](https://i.postimg.cc/FHzQmVnq/i-OS-15-Maps-Feature.jpg)](https://postimg.cc/3dsqFmhC)
[![globe-view.png](https://i.postimg.cc/d35SSzv0/globe-view.png)](https://postimg.cc/K3gN1p1X)

**Comment by HarelM** [comment]
I think this would be great, but I don't have the slightest clue how to implement this.
Your best approach would be to submit a PR after implementing this. I also think this should be configurable for people that wouldn't want this...
Also there's a need to make sure this does not cause performance issues in terms of fetching too many tiles...
But, sure, this feature would be very nice to have :-)

**Comment by wipfli** [comment]
Happy to review pull requests on this too. Here is a link that @klokan gave me:

https://observablehq.com/@fil/webmercator-to-globe?collection=@fil/glsl-projections

**Comment by Malvoz** [comment]
I'm not sure if/how relevant this MapBox GL JS issue is: https://github.com/mapbox/mapbox-gl-js/issues/10784, perhaps informative if anything?

**Comment by HarelM** [comment]
Well, looks like someone from mapbox is coding it so we can't use it sure to licencing issues.
By the amount of corner cases that this thread is talking about it seems like a huge effort, but if you are up for the challenge, why not? :-)

**Comment by wipfli** [comment]
@Malvoz thanks for posting the related Mapbox link here. If someone is going to implement this feature in MapLibre GL JS you could maybe act as a referee who makes sure that we don't copy-paste their proprietory code.

**Comment by rbrundritt** [comment]
I suspect this would be a pretty large work effort to achieve and would only be good for a small subset of business scenarios. This would not be good for data visualizations where users are looking to get business insights most of the time as they will need to see all the data.

**Comment by HarelM** [comment]
This can be an opt-in. I don't see a problem in theory if someone world like to do this.

**Comment by rbrundritt** [comment]
My main concern would be how much this feature would in flat the project. If it grows the code base by 10% for something that would be use 5% of the time, should this be out of the box, or is there a modular approach that could be implemented?

**Comment by HarelM** [comment]
Let's have this discussion if someone decides to implement this, this is currently not the case as far as I know...

**Comment by nyurik** [comment]
The title sounds so self-righteous, like the author knows everything! What if it is? :earth_africa: -- it could be flat if you look from its side :)

**Comment by alienatorZ** [comment]
Has there been any movement on this?

**Comment by wipfli** [comment]
Not that I know...

**Comment by wipfli** [comment]
Would it be nice for you to have?

**Comment by am2222** [comment]
Would be nice to have the discussion and steps to take.

**Comment by klokan** [comment]
Anybody keen in jumping on implementation of the "Adaptive Composite Map Projection" (google this)?

It is the math. R&D done 10 years ago. Going from [Orthographic projection](https://en.wikipedia.org/wiki/Orthographic_map_projection) of the globe to the Mercator as you zoom in.
This is what Google Maps implemented - and now Mapbox too - on the upper zoom levels.

https://berniejenny.info/demos/AdaptiveCompositeMapProjections/
https://github.com/OSUCartography/adaptive-composite-map-projections

If you want it to be done - send a vote to https://roadmap.maplibre.org/ on it :-)

**Comment by HarelM** [comment]
Might be related to #168 I guess...

**Comment by prozessor13** [comment]
I think the easies way to implement globe-view would be to:
* reuse terrain render-to-texture logic to create raster-tiles for the current style
* create a new shader for globe view, which projects tile-coordinates from the terrain-mesh to a sphere via:
  * project to epsg4326 (= degrees)
  * and then with sin/cos to a sphere
  * fill the poles with trianles from terrain-mesh to the poles
* paint the raster-tiles to the sphere terrain-mesh

This approach has nothing to do with other projections like albert or so, but may this can be done in a similar way?

**Comment by wipfli** [comment]
Interesting @prozessor13. Would that also handle labels?

**Comment by tangzijun** [comment]
expect
