### ISSUE TITLE
Rename output files in dist/ dir to maplibre

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre-gl-js#31]
Currently all of maplibre's [dist files](https://unpkg.com/browse/maplibre-gl@1.13.0-rc.3/dist/) are generated as `mapbox*`, and while this could be considered part of the API, it would be great if we could rename them as part of the initial release.

**Comment by lseelenbinder** [comment]
We probably want to support both `maplibre` and `mapbox` in the first release? Otherwise certain aspects of a drop-in replacement are gone.

**Comment by HarelM** [comment]
I think this was implemented.
Can we close this issue?
