### ISSUE TITLE
map.setStyle() doesn't repaint map

### ISSUE THREAD

**Issue by slaviczavik** [maplibre/maplibre-gl-js#3101]
**maplibre-gl-js version**: `^3.3.1`

**browser**: `Chrome 116`, `Safari 16.6`

### Steps to Trigger Behavior
> Easiest way to trigger the behavior is to run the example (link below) and trigger the Red, Green, Blue buttons. **You will never get back to the original style**.
 1. Init MapLibre with a style
 2. Set an updated map about new layer color via `map.setStyle`
 3. Set origin state via `map.setStyle`

### Link to Demonstration
[JS Bin with simplest example](https://jsbin.com/hojuwapoye/1/edit?html,output).

### Expected Behavior
MapLibre should repaint map with the original style.

### Actual Behavior
MapLibre won't repaint the map with the original style.

**Comment by HarelM** [comment]
Hmm... interesting...
Probably related to the differential update that was introduced a few versions ago.
It's worth checking if this was an issue in previous versions and if so in what version it was introduced, it might help narrow down the issue.
Might be related to #2587

**Comment by slaviczavik** [comment]
> #2587

Just tested, do not work from version `3.0.0`.

**Comment by bdon** [comment]
I'm also experiencing this. A workaround is to set a "dummy" layer with a cachebuster ID:

```js
let id = 0;
layers.concat([{type:'fill',source:'mysource','id':'' + id++,'source-layer':'none'}]
```

That way you never have the same layers twice.

**Comment by bolollo** [comment]
Using the {diff: false}[1] option in setstyle[2] works correctly. So, the problem must be in the differential update.

[1] https://maplibre.org/maplibre-gl-js/docs/API/types/maplibregl.StyleSwapOptions/
[2] https://maplibre.org/maplibre-gl-js/docs/API/classes/maplibregl.Map/#setstyle
