### ISSUE TITLE
Add setTiles capability to RasterTileSource

### ISSUE THREAD

**Issue by wagewarbler** [maplibre/maplibre-gl-js#3207]
## User Story

Add ability to dynamically `setTiles` on a RasterTileSource, similar to [what's already possible for VectorTileSource](https://github.com/maplibre/maplibre-gl-js/blob/9dcb8715d82107f415fddc0eea932a348a973b39/src/source/vector_tile_source.ts#L155). 

## Rationale

Our map application has the ability to select dates and update layers on-the-fly with geospatial data from the date selected. We're using GeoJSON, vector tile sources, and would like to add imagery as well, but we're currently blocked by the inability to update tile sources with the lastest URL & params. The workaround is to completely remove the source & associated layers and then re-add it as a new source with an updated tiles field, but it's not a smooth experience.

## Impact

Vector and vector tile sources are certainly where a lot of modern development is happening, but there is a lot of satellite imagery captured and served in raster format. Having the capability to show this imagery over time is really powerful.

**Comment by HarelM** [comment]
Yup, API wise, this makes sense.
Feel free to open a PR.
