### ISSUE TITLE
Serializing a map's style does not include 3D terrain

### ISSUE THREAD

**Issue by neodescis** [maplibre/maplibre-gl-js#3214]
It seems that map.getStyle() does not include a serialization of the style's terrain (when present). The getStyle() function ultimately calls the [style's serialize() function](https://github.com/maplibre/maplibre-gl-js/blob/572d6071fd5fce9f71bdb267f05532616e8d7be0/src/style/style.ts#L1209), and indeed terrain is not included there.

**maplibre-gl-js version**:
3.5.0

**browser**:
Any

### Steps to Trigger Behavior
 1. Instantiate a map that uses 3D terrain
 2. Call map.getStyle()
 3. See that the serialized style does not include the "terrain" property

### Link to Demonstration
https://jsbin.com/visufuqewi/edit?html,output

### Expected Behavior
Console output of the serialized style should include terrain

### Actual Behavior
Console output of the serialized style does not include terrain

**Comment by kumiko-haraguchi** [comment]
@neodescis I'd be happy to take this task if no one has worked on it yet! I've made a draft [PR](https://github.com/maplibre/maplibre-gl-js/pull/3234). If it's already taken care of, I'll close it.

**Comment by neodescis** [comment]
Nope, I don't think anyone has looked at it yet. I've been on vacation, but I can take a look at your PR tomorrow unless @HarelM beats me to it. Thanks!

**Comment by HarelM** [comment]
Thanks @kumiko-haraguchi! I've reviewed the PR and added a few comments.
