### ISSUE TITLE
Regression in safari on Observable HQ in maplibre-gl@2.0.0-pre.1 ReferenceError: Can't find variable: ImageBitmap

### ISSUE THREAD

**Issue by thejimmyg** [maplibre/maplibre-gl-js#324]
**maplibre-gl-js version**:

maplibre-gl@2.0.0-pre.1

**browser**:

Safari

### Steps to Trigger Behavior

 1. Visit https://observablehq.com/@jimmyg/gmaplibre-regression in the Safari browser
 2. You'll see `ReferenceError: Can't find variable: ImageBitmap`
 3. If you change the import at the top to `maplibregl = await require("maplibre-gl@1.15.2")` it works fine

When inspecting the debug console I see:

```
worker ↑
Object

errors: Map {15 => {message: "Can't find variable: ImageBitmap", stack: "update@https://cdn.jsdelivr.net/npm/maplibre-gl@2.…gl.js:35:318889↵↵promiseReactionJob@[native code]", input: undefined, name: "ReferenceError"}} (1)

type: "errors"

Object Prototype
```

Safari doesn't support `ImageBitmap` so this suggests to me that perhaps the code that does feature detection isn't working correctly as it tries to use `ImageBitmap` in the worker. It works fine in Chrome.

Of course this could just be an issue in the ObservableHQ environment, I don't know enough about the maplibre-gl-js project to know.

I don't consider this a serious issue for me at the mo, but wanted to flag it in case it points to a genuine problem in the 2.0.0 branch and later effects that release.

### Link to Demonstration

I've ported the first example in the docs from https://maplibre.org/maplibre-gl-js-docs/example/simple-map/ to ObservableHQ syntax:

https://observablehq.com/@jimmyg/gmaplibre-regression

### Expected Behavior

The map should display in Safari (it works fine Chrome).

### Actual Behavior

`ReferenceError: Can't find variable: ImageBitmap`

**Comment by HarelM** [comment]
This is a great input! Thanks for reporting this!
Can you share a bit more about the env?
Which safari version? Which OS and version?
I will look into it soon I hope.
Can I count on you to retest it once I release a fix?

**Comment by thejimmyg** [comment]
Thanks @HarelM 

Sorry for not adding these full details originally.

Safari Version 14.1.2 (16611.3.10.1.3) on macOS 11.5 (20G71) - the latest versions of both.

The same thing happens on Safari on mobile, using the latest version on iOS 14.7.1 but is resolved if you switch to maplibre-gl-js version 1.15.2, just as on Desktop.

Yes, of course, happy to re-test once you've made a release.

Thank you!

**Comment by HarelM** [comment]
@thejimmyg Feel free to review my changes at #325.
I opened the safari in the debug page and saw that I don't get any errors, but I'm not sure it fully checks this issue.
Let me know if you need me to release a new prerelease for you to test this or if you can test this straight from the repo.
In any case thanks a lot for testing this! It will allow us to make sure the version we ultimately release will be as bug-less as possible!

**Comment by thejimmyg** [comment]
Thank you for being so quick. Yes, I'll review your changes after reading the typescript link in your PR. I'll also make a build and then try to find a way to get Observable to load it so that I can make an end to end test. That might take a little while, but I'll do my best.

**Comment by thejimmyg** [comment]
I've done the following:

```
git clone git@github.com:maplibre/maplibre-gl-js.git maplibre-gl-js@2.0.0-pre2
git clone git@github.com:maplibre/maplibre-gl-js.git maplibre-gl-js@325
cd maplibre-gl-js@325
gh pr checkout 325
cd ..
```

Then in both:

```
npm i
npm build-prod
npm build-css
```

Then I've created two example HTML pages like this, each referencing one of the repos:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Display a map</title>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
<script src="/maplibre-gl-js%402.0.0-pre.2/dist/maplibre-gl-unminified.js"></script>
<link href="/maplibre-gl-js%402.0.0-pre.2/dist/maplibre-gl.css" rel="stylesheet" />
<style>
	body { margin: 0; padding: 0; }
	#map { position: absolute; top: 0; bottom: 0; width: 100%; }
</style>
</head>
<body>
<div id="map"></div>
<script>
var map = new maplibregl.Map({
container: 'map', // container id
style: 'https://demotiles.maplibre.org/style.json', // style URL
center: [0, 0], // starting position [lng, lat]
zoom: 1 // starting zoom
});
</script>
 
</body>
</html>
```

The one referencing current `main` fails with the same error: 

```
ReferenceError: Can't find variable: ImageBitmap
```

The one with your pull request works great:

<img width="948" alt="Screenshot 2021-09-09 at 11 31 42" src="https://user-images.githubusercontent.com/287936/132670604-2d49de99-5e95-48d9-bc8a-1c588e19a0ee.png">

I've also done the same test on mobile safari with the Web Inspector open and get exactly the same behaviour there. This PR fixes it on Mobile safari too.

So, I'm fairly confident this resolves the issue.

I've had a look at the code itself but I'm not confident enough reviewing it I'm afraid, I'd need to be more familiar with typescript.

I don't think I'll be able to test on observable before you make another pre-release, but happy to do so when you do.

Let me know if there is anything else I can do. Thanks again.

**Comment by thejimmyg** [comment]
Update @HarelM: I've found a way to test in Observable HQ by creating a workbook that allows you to upload the `.js` file to require, as described here:

    https://observablehq.com/@observablehq/require

Using this method I've created a new example here:

    https://observablehq.com/@jimmyg/gmaplibre-regression-325

By uploading the code built from #325 as described above, you can see that your changes now work in Observable too:

<img width="990" alt="Screenshot 2021-09-09 at 12 18 42" src="https://user-images.githubusercontent.com/287936/132676641-5a85faae-57e9-4a95-adea-c0a28ef67de9.png">
