### ISSUE TITLE
Map is not able to be loaded only in production environment

### ISSUE THREAD

**Issue by wongpeterhy** [maplibre/maplibre-gl-js#3268]
maplibre-gl version:3.5.1
browser: Chrome Version 118.0.5993.89

First of all, really sorry that I am not able to provide any codesandbox for reproduce this issue.
My code actually work fine in local environment, however, after production build I encounter this error.

In local environment it's working fine..
![image](https://github.com/maplibre/maplibre-gl-js/assets/134259157/50d66f26-8671-4829-a375-dc7cf8886811)

Seems like sprite.json and tiles.json is loaded successfully without any error

Does anyone meet this error before?

Uncaught ReferenceError: y is not defined
    at 9b2f47a5-8394-476f-a6b7-438a3f2b4f98:1:5756
    at 9b2f47a5-8394-476f-a6b7-438a3f2b4f98:1:356813
(anonymous) @ 9b2f47a5-8394-476f-a6b7-438a3f2b4f98:1
(anonymous) @ 9b2f47a5-8394-476f-a6b7-438a3f2b4f98:1

![image](https://github.com/maplibre/maplibre-gl-js/assets/134259157/7bf3e06d-58b1-444d-8f48-589fb83cdc9f)

**Comment by wongpeterhy** [comment]
Found that there're already a closed issue to solve this.

https://github.com/maplibre/maplibre-gl-js/issues/1011

**Comment by onuryb** [comment]
Thanks a lot my proplem is solved thanks to
