### ISSUE TITLE
Improve browser tests coverage for super basic scenarios

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#329]
## Motivation
I'm not sure right now is the right time but rather after #273 but after #325 and #324 it seems that the browser test are not fully covering the most basic scenarios in terms of console error catching, so we need to either add test now to check that the console doesn't have any errors or make sure we do it later on in the next framework we move to.
I'm just not sure how to do it now with the current framework...
Opening this issue in order not to forget to do it...

**Comment by wipfli** [comment]
Thanks for opening this issue. I also wonder how people do automated tests on mobile browsers.

**Comment by HarelM** [comment]
The situation was improved after fixing the render tests. However,  this is still important, reopening.

**Comment by HarelM** [comment]
We have browser tests now with minimal coverage.
I generally think the coverage of the test is good and stuff that don't need a browser are not using it so I'll close this issue.
Test coverage can always be better, but I don't think this issue will help solve this.
