### ISSUE TITLE
Rename primary build artifact to dist/maplibre-gl.js, but maintain full compat

### ISSUE THREAD

**Issue by snickell** [maplibre/maplibre-gl-js#33]
What I’m planning to do if I find time, and if somebody else finds time I’d encourage them to try this path first, is….

1. Change the build to output dist/maplibre-gl.js as the primary dist file (css too, but I won’t list it for the rest of this, too much words). This mainly means changing rollup.config.js (https://github.com/maplibre/maplibre-gl-js/blob/main/rollup.config.js#L11:L12), and package.json
2. Then modify rollup to ALSO generate a wrapper JS in dist/mapbox-gl.js that is the webpack equivalent of export * from ./maplibre-gl.js , and prints a deprecation warning if you import it
3. Finally, I plan to NOT update the dist/mapbox-gl.js filename in the tests, this will ensure that we are testing the compatibility shim fully for v1.13.0 (which will in turn test ./maplibre-gl.js since it just imports it)

I believe this combination of actions will allow us to have our cake and eat it to:
- Tested full compat with the existing filepaths
- Our “real code” is in a separate file under the maplibre-gl.js name
- Minimal+safe build system change we can be confident in even though we’re relative n00bs at releasing this codebase

I think the biggest question is **if we should make this the primary change in v1.14.0, or if we should block release of v1.13.0 on this**. I'm leaning toward including this in v1.13.0, but its going to depend on me having time to do it.

**Comment by snickell** [comment]
This is related to the tracking issue #27

**Comment by snickell** [comment]
Basically, after this change:
`dist/maplibre-gl.js` would be the the main code
`dist/mapbox-gl.js` is almost a symlink that prints a deprecation warning (its just an import *, export * wrapper js)

**Comment by nreese** [comment]
> I think the biggest question is if we should make this the primary change in v1.14.0, or if we should block release of v1.13.0 on this. I'm leaning toward including this in v1.13.0, but its going to depend on me having time to do it.

I see no problem in including this in v1.13.0 release
