### ISSUE TITLE
 RollupError: Could not resolve "../../staging/maplibregl/shared" from "build/rollup/maplibregl.js"

### ISSUE THREAD

**Issue by nicky132** [maplibre/maplibre-gl-js#3303]
**maplibre-gl-js version**:3.5.2

**browser**:版本 118.0.5993.118（正式版本） （64 位）

### Steps to Trigger Behavior

 1.npm install
 2.npm run watch-dev
 3.
`bundles build/rollup/maplibregl.js → dist/maplibre-gl-dev.js...
[!] RollupError: Could not resolve "../../staging/maplibregl/shared" from "build/rollup/maplibregl.js"`

### Expected Behavior
npm run watch-dev and npm run build-dist both work 
### Actual Behavior
![95274849cd72c4e5cd125de572e52904](https://github.com/maplibre/maplibre-gl-js/assets/34881461/6316dd56-78c1-4537-a31e-6bd05a84aee2)

**Comment by HarelM** [comment]
The build is constantly passing CI, on entry major platform.
please make sure you are using the right now version (18).

**Comment by nicky132** [comment]
> The build is constantly passing CI, on entry major platform. please make sure you are using the right now version (18).
I am using the latest version for sure.
![b9cff7d808948e5e581d554b3497c373](https://github.com/maplibre/maplibre-gl-js/assets/34881461/ba530015-2de0-4f02-a6b1-c5cd7880f9a4)

**Comment by nicky132** [comment]
> The build is constantly passing CI, on entry major platform. please make sure you are using the right now version (18).
I am using the latest version,that is for sure.
![1698910821315_53C83446-1DFE-4555-A472-0D019A12D80B](https://github.com/maplibre/maplibre-gl-js/assets/34881461/3a70be58-2c9f-40b4-bbe5-337d48e74bd7)

**Comment by HarelM** [comment]
I can't reproduce this using nodejs 18.
make sure to run `nvm install` and check out the contributing guide:
https://github.com/maplibre/maplibre-gl-js/blob/main/CONTRIBUTING.md

**Comment by nicky132** [comment]
> I can't reproduce this using nodejs 18. make sure to run `nvm install` and check out the contributing guide: https://github.com/maplibre/maplibre-gl-js/blob/main/CONTRIBUTING.md

Of  course,my node version is v18.0.0,i have no idea about the problem
![c30154467987811553d5ef833a8b79dd](https://github.com/maplibre/maplibre-gl-js/assets/34881461/695c622e-2125-433b-b077-96df3dba0705)

**Comment by HarelM** [comment]
I advise to use GitHub's Codespaces instead of a local environment that seems to have issues. I use it regularly and it works as expected.
I have no clue what's not working on your machine, CI runs on both Ubuntu, Windows and I use a mac for developement, everything is working as expected there.
You can also use WSL on windows, it's a lot faster.

**Comment by nicky132** [comment]
> I advise to use GitHub's Codespaces instead of a local environment that seems to have issues. I use it regularly and it works as expected. I have no clue what's not working on your machine, CI runs on both Ubuntu, Windows and I use a mac for developement, everything is working as expected there. You can also use WSL on windows, it's a lot faster.

Certainly,i used to use WSL on my computer,but still no idea about the error until i tried out `npm install canvas --canvas_binary_host_mirror=https://registry.npmmirror.com/-/binary/canvas`first,then everything works well

**Comment by HarelM** [comment]
Glad it solved the issue for you!
