### ISSUE TITLE
Mutipolygon buildings do not work well with 3d terrain, show floating or underground.

### ISSUE THREAD

**Issue by acalcutt** [maplibre/maplibre-gl-js#3313]
When using a planetiler 0.7.0 generated pmtiles file in maplibre-js with 3d terrain enabled, I observed floating buildings and buildings going under the ground. With a file generated with planetiler 0.6.0, this issue did not occur. After discussion on slack in https://osmus.slack.com/archives/C03TFH5NE83/p1698949699781319 , I think this relates to a change in planetiler 0.7.0 which merges buildings with the same tags into a single multipolygon to save space. In 0.6.0 each building was it's own polygon and each was tagged individually.

0.6.0
![image](https://github.com/maplibre/maplibre-gl-js/assets/3792408/df0c2333-00a6-4452-ab50-b6daf5db651a)

0.7.0
![image](https://github.com/maplibre/maplibre-gl-js/assets/3792408/cb510fdb-15cf-4014-8425-329235e3c9a9)

While this could be considered a planetiler issue, I am also not sure that maplibre-js is handling the multipolygon properly with 3d terrain enabled.

For example, I pulled this building geojson out of a planetiler 0.7.0 pbf file with [vt2geojson](https://github.com/mapbox/vt2geojson)
`vt2geojson --layer building https://tiles.wifidb.net/data/planetiler-0-7-0_pmtiles/14/3094/6569.pbf > 14-3094-6569.geojson`
this makes a multipolygon like
![multipolygon](https://github.com/maplibre/maplibre-gl-js/assets/3792408/dbaa5152-a7b6-4686-b006-683a2c675ce9)
[14-3094-6569.geojson.txt](https://github.com/maplibre/maplibre-gl-js/files/13255723/14-3094-6569.geojson.txt)

If I put that into the maplibre building example I get this stackblitz example page
https://stackblitz.com/edit/web-platform-zaxezv?file=index.html
In this example you can see these buildings floating in the zoom 14 range
![floating_buildings](https://github.com/maplibre/maplibre-gl-js/assets/3792408/4f5dec57-caf6-4efd-9b4d-88f3f5345e01)
it looks like they get placed at a height in the center of the multipolygon above, which is much higher than the terrain where the building sits, causing them to float.

I also made this example using a live planetiler 0.7.0 pmtiles file, you can see it looks much worse than the geojson example, with this issue showing past zoom 14
https://stackblitz.com/edit/web-platform-qmqmrs?file=index.html
not only do you see building floating, but you also see large groups of buildings completely or partially underground
![image](https://github.com/maplibre/maplibre-gl-js/assets/3792408/8a510fea-5338-481a-8395-88466d74b004)

**maplibre-gl-js version**: 3.5.2 
**browser**: chrome

**Comment by HarelM** [comment]
If I needed to guess it has to do with the fact that it probably treats the entire multiploygon with the same elevation.
Having said that, it does act weird in the transition between zoom 13 and zoom 14, and between zoon 14 and zoom 15.
If I disable all the styling related to height and min base, I still see the buildings jump up and down when changing the zoom levels, not sure why...

**Comment by acalcutt** [comment]
I did notice that with the geojson source. in the second example with full planet file it seems to be floating at all zoom levels and they don't jump around like that. I'm not quite sure the difference though since that geojson was pulled from the tile...maybe something to do with being stiched with other tiles in the full planet example.

**Comment by prozessor13** [comment]
Hi, yes, elevation is pulled per feature only once. I dont know if this is a bug or not? More a design decision? Why there is a difference between geojson and normal vectortile, i also dont know.

**Comment by HarelM** [comment]
@prozessor13 how complicated it would be to split the elevation calculation to be per polygon?

**Comment by prozessor13** [comment]
Hi Harel,

it should be simple: https://github.com/maplibre/maplibre-gl-js/blob/main/src/data/bucket/fill_extrusion_bucket.ts#L163
* move the `centroid` variable into the polygon-for-loop
* emplace the `centroid` foreach polygon into the `centroidVertexArray`. https://github.com/maplibre/maplibre-gl-js/blob/main/src/data/bucket/fill_extrusion_bucket.ts#L279

but i am not sure if thats the way to go. Think about multipolygon buildings, like churches or other complex buildings in heavy terrain.

**Comment by HarelM** [comment]
I see, thanks for the input!
cc: @msbarry - see comment above related to planetiler polygon compression...

**Comment by msbarry** [comment]
Thanks! It might be useful to find one counterexample multipolygon building here that you want to retain this behavior. To me it seems like we've got these cases:

- If the building has multiple parts at different heights to define a complex roofline then those will be separate polygons anyway since they have different height tags.
- If a multipolygon building has multiple parts with the same height tag that spans a large area over heavy terrain then what does that even mean? To me it seems like the height would apply to the elevation above the ground for each part

Maybe what we're getting at here is the need to explicitly group several [`building:part`](https://wiki.openstreetmap.org/wiki/Key:building:part) polygons into one "height group" that share the same base elevation. A multipolygon without this would get a new base for each part. A single multipolygon with this would get the same base for each part. Many polygons/multipolygons with the same value would all get the same base height.

**Comment by prozessor13** [comment]
> * If the building has multiple parts at different heights to define a complex roofline then those will be separate polygons anyway since they have different height tags.

Ah, did not thought about this, you are right. Changing grabbing elevation for each polygon is definitely worth to try.

**Comment by acalcutt** [comment]
Fixed by https://github.com/maplibre/maplibre-gl-js/pull/3841
