### ISSUE TITLE
Make all `_` fields private

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#333]
## Motivation

The motivation is to properly define all methods and members of classes with their appropriate modifier (public, private mainly).
This is a big challenge that requires a lot of work.
Having said that, doing it for `_` prefixed fields and methods should be relatively simple and an easy win.

**Comment by rbrundritt** [comment]
I wonder if this would break any workarounds people have implemented in production.

**Comment by HarelM** [comment]
This is what 2.0 is for...

**Comment by drwestco** [comment]
Unless the project is using a minifier that mangles private class member names (not common practice), marking members as private shouldn't affect such debug console hacks.

**Comment by douglasg14b** [comment]
This would break tons of workaround that people use.... I even have some of these kicking around.

**Comment by douglasg14b** [comment]
Oh boy, stale bot.

**Comment by HarelM** [comment]
Unfortunately, due to the large echo system around maplibre I think this won't help anyone but only cause pain.
Having said that, I urge people who are using these private fields to open issues with API request changes/improvements so that they will be able to use fields that they need without the fear of things breaking...
