### ISSUE TITLE
README outdated community leadership

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#3342]
The readme part about community leadership is a bit outdated. I plan to open a pull request to fix this.

> [Community Leadership](https://github.com/maplibre/maplibre-gl-js#community-leadership)
You can find the official status of the backing community and steering committee in the [COMMUNITY.md](https://github.com/maplibre/maplibre-gl-js/blob/main/COMMUNITY.md) document.

We also need to get the maplibre.org/roadmap section of the website online again because it is linked in the readme but that is a ticket for the website repo.

**Comment by HarelM** [comment]
@wipfli what's the status of this? Any chance to close this issue?

**Comment by wipfli** [comment]
I would just delete the COMMUNITY.md file. Good with you @HarelM ?

**Comment by HarelM** [comment]
Sure, sounds good.
