### ISSUE TITLE
TypeScript - cannot import const enums when isolatedModules or verbatimModuleSyntax is set

### ISSUE THREAD

**Issue by nhardy** [maplibre/maplibre-gl-js#3364]
MapLibre currently exports some `const enum`s. Given that MapLibre has a `tsconfig.json` with `"isolatedModules": true`, this has the effect of turning these into runtime enums in the transpiled code, but incorrectly recording these as `const enum` in the type definitions.

I came across this issue when utilising the [`@typescript-eslint/no-unsafe-enum-comparison`](https://typescript-eslint.io/rules/no-unsafe-enum-comparison/) lint rule which enforces referencing enums where applicable rather than literal values. I have raised a bug against `@typescript-eslint` (https://github.com/typescript-eslint/typescript-eslint/issues/7908), but believe these `const enum`s in MapLibre should be converted to regular enums to improve the usability here.

**maplibre-gl-js version**: v3.6.0

**browser**: N/A - not a runtime issue

### Steps to Trigger Behavior

 1. Consuming application has tsconfig with either `"isolatedModules": true` or `"verbatimModuleSyntax": true`
 2. Attempt to import a const enum from `maplibre-gl`, e.g. `import { ResourceType } from "maplibre-gl";`
 3. See error message: `Cannot access ambient const enums when 'isolatedModules' is enabled. (2748)`

### Link to Demonstration

https://www.typescriptlang.org/play?isolatedModules=true#code/JYWwDg9gTgLgBAbwEoFMDOECuUDGKAqAnmCgL5wBmUEIcA5CAIZgA2wARlCgLQDmLdANwBYAFBiAJihwtGXODggA7NPABujFphQAuOKgzY8REiNHAKcABQatKOAF4n+9FlwFiKAHT5gLFACUiGJipGJAA

### Expected Behavior

No TS Error message

### Actual Behavior

TS Error message:
> Cannot access ambient const enums when 'isolatedModules' is enabled. (2748)

**Comment by HarelM** [comment]
If you ask me, enums in typescript is a total miss... It's always not working as you'd expert it to work...
I prefer a type definition of string for readability or numbers narrowing. i.e. `type SomeThing = "a" | "b".`
We are closing in to make a breaking version release, if you want to use that to remove some of the enums in the code I would guess it would be the best approach...?

**Comment by HarelM** [comment]
I guess there's no real interest in this... closing...
