### ISSUE TITLE
Can't capture attribution by using "map.getCanvas().toDataURL()"

### ISSUE THREAD

**Issue by haiduong87** [maplibre/maplibre-gl-js#337]
**maplibre-gl-js version**: 1.15.2

### Question
HI maplibre,

I have a task to capture high dpi map, and this is what I'm doing:
- Increase dpi
- Call map.resize();
- Wait for the resizing -> I choose to use "idle" event
- Capture the new map

 
Here's the code:

`

            map.on('idle', function() {
                    console.log('A idle event occurred.');
             });

            function print() {

                function afterIdled() {
                     map.off('idle', afterIdled);
                     var img = map.getCanvas().toDataURL("image/png");

                     var modal = document.getElementById("myModal");
                     var modalImg = document.getElementById("img01");

                     modal.style.display = "block";
                     modalImg.src = img;

                      setDPI(actualPixelRatio);
                     map.resize();
                 }

            actualPixelRatio = window.devicePixelRatio;

            setDPI(300 / 96);

            map.on('idle', afterIdled);
            var m = map.resize();
        }

         function setDPI(dpi) {
             Object.defineProperty(window, "devicePixelRatio", {
                   get: function() {
            return dpi;
           }
              });
          }
`

I think it works fine, but with a big problem: I can't capture the credit (attribution)
Please take a look
- Capture result
![image](https://user-images.githubusercontent.com/22165935/133369990-eb8c7761-fb13-49a2-81ac-972a9c38401d.png)
- Console log
![image](https://user-images.githubusercontent.com/22165935/133370019-47d6ce77-2fcc-4deb-88ce-b7bc7ca5970f.png)

So the question is:
- Is the "idle" event fit my requirement? 

If "idle" event is fit, how can I capture the credit? Or I just need to capture image when the 2nd event is raised?
If "idle" event is not fit, please guide me another way.

Thanks,

**Comment by HarelM** [comment]
Latest version has a render synchronous call. Can you test that?

**Comment by haiduong87** [comment]
Hi @HarelM,

I tried this https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/map.ts#L2614 (v2.0.0-pre.3)

- It does not resize the map.
- Can't capture attribution

**Comment by HarelM** [comment]
I'm not sure why the attribution is missing, your best bet is to debug and send a PR with the fix...

**Comment by haiduong87** [comment]
Hi @HarelM,

Sorry for a misleading issue.
My problem is not about the "idle" event, actually this line is the problem

`var img = map.getCanvas().toDataURL("image/png");`

We just can't get the attribution with this line.

I have no idea too.

I will try to debug.

Thanks

**Comment by haiduong87** [comment]
Attribution is not a part of the canvas.

![image](https://user-images.githubusercontent.com/22165935/133468810-b387b1e2-a5a4-4f65-91b5-604962f667ab.png)

**Comment by HarelM** [comment]
Yup, it's not, it's html.
Can this issue be closed then? I don't think there's much to do here, right?
