### ISSUE TITLE
Incorrect CSS Color Prevents `arcgis/navigation` maps from loading

### ISSUE THREAD

**Issue by sheeley820** [maplibre/maplibre-gl-js#3376]
I have not been able to determine when this bug was introduced, but can confirm that it exists in the latest version.

In the "Water point/Dam or weir" property of the `arcgis/navigation` map CSS (https://basemapstyles-api.arcgis.com/arcgis/rest/services/styles/v2/styles/arcgis/navigation) the `paint.text-halo-color` is set to `#fffffr`, which is an invalid hexadecimal color.

An example can be seen [here](https://developers.arcgis.com/esri-leaflet/samples/switching-basemaps/) by selecting the "arcgis/navigation" layer.  In the console you will see the following error:
```javascript
Error: layers[142].paint.text-halo-color: color expected, "#fffffr" found
```

**maplibre-gl-js version**: 3.3.1

**browser**: All

### Steps to Trigger Behavior

 1. Load the `arcgis/navigation` may layer
 2. See the map not load

### Link to Demonstration

https://developers.arcgis.com/esri-leaflet/samples/switching-basemaps/

### Expected Behavior

The map should load without an error.

### Actual Behavior

The map does not load.

**Comment by acalcutt** [comment]
Wouldn't this be a arcgis style issue? obviously "#fffffr" is invalid since "r" is not valid hex.

**Comment by sheeley820** [comment]
@acalcutt Yes, for sure.  But this was as close to the source of that style file as I can figure out how to get.  If someone knows how to contact someone as Esri that would be great.  I've been trying to find a proper way to contact them on their site.

**Comment by HarelM** [comment]
We have switched to use a different css color parser, which I believe is more strict, which might have uncovered this issue in ESRI.
See the following PR:
https://github.com/maplibre/maplibre-gl-js/pull/2376
This was introduces in version 3 I believe.

**Comment by sheeley820** [comment]
Ok, thank you for the update.  This gives context as to why the error started appearing when I upgraded my version of `esri-leaflet-vector`.  I have emailed the appropriate parties at Esri and am just waiting for a response.  I will update this issue when there is a resolution.

**Comment by sheeley820** [comment]
I have reached out to Andy Green at Esri and he has informed me that they plan on releasing a fix on November 29'th. Once that fix is released I will close this issue.

**Comment by sheeley820** [comment]
Esri has merged a fix for the style bug, so I am closing this issue.  Successful map loading can be seen [here](https://github.com/maplibre/maplibre-gl-js/issues/3376#:~:text=https%3A//developers.arcgis.com/esri%2Dleaflet/samples/switching%2Dbasemaps/) by selecting the `arcgis/navigation` base map.
