### ISSUE TITLE
Part of the text in the popup is hidden by focus of close button.

### ISSUE THREAD

**Issue by naogify** [maplibre/maplibre-gl-js#338]
## Motivation

When I set a popup on a marker and click on it, the focus is on the close button (x) and part of the text in the popup is hidden. This happens only when you click on the marker for the first time.

https://user-images.githubusercontent.com/8760841/133375189-6e17a229-41c7-4e03-a493-4ab5da528463.mov

### Demo on CodePen
https://codepen.io/naogify/pen/VwWMBJb

## Design Alternatives

I think there are two solutions.

### 1. Change default value of options.focusAfterOpen.

When I set false to options.focusAfterOpen, it did not happen.

![スクリーンショット 2021-09-15 14 30 42](https://user-images.githubusercontent.com/8760841/133376108-9947716f-9591-43ca-b0cb-ebc57e254548.png)
https://maplibre.org/maplibre-gl-js-docs/api/markers/#:~:text=options.focusAfterOpen

### 2. Set padding-top 15px to popup card.

`.maplibregl-popup-content` has `padding-top :10px` and  `padding-bottom: 15px`. We can solve this problem by setting `padding-top: 15px`.

![スクリーンショット 2021-09-15 14 39 08](https://user-images.githubusercontent.com/8760841/133377051-8a901002-bdcb-4f6c-b35e-135d06098c12.png)

## Design

I think the solution of "Change default value of options.focusAfterOpen" is better.  But if it is difficult to change the default value, we can choose the solution of adding padding-top 15px.

**Comment by HarelM** [comment]
This is interesting... I don't see this behavior in my site, but I'm using ngx-maplibre-gl as a wrapper around maplibre which might did this under the hood.
I think we can change the default as part of 2.0 breaking changes.
Changing padding is less ideal from my point of view too...
@wipfli what do you think?

**Comment by wipfli** [comment]
Changing the default to `false` is fine for me.

**Comment by tunnelpuzzle** [comment]
It seems like the padding-top should be changed regardless, even if the default for focusAfterOpen is changed the close button hover/focus still overlaps the popup content. Focusing an element within a popup/modal after it's opened is a pretty common accessibility feature.

**Comment by naogify** [comment]
@HarelM @wipfli 
Thank you for the reply. I created the PR for it https://github.com/maplibre/maplibre-gl-js/pull/344.

@tunnelpuzzle
Yes, if we change the default value of focusAfterOpen, the hover/focus will still overlap the popup content, but it will be more readable.  

![スクリーンショット 2021-09-16 12 31 08](https://user-images.githubusercontent.com/8760841/133544956-c3c37098-e0ff-4b3c-9edd-39ca568ed962.png)
↑ hover screenshot 

I think adding padding-top is an option. But, I'm worried about affecting the users who already added padding-top to fix this issue. What do you think about it?

**Comment by HarelM** [comment]
If this is planned for version 2.0 we are allowed to break as long as we add the relevant comment in the changelog.
I'm not sure we want to do both changes - padding and default change.
For accessibility I have a feeling padding is the better solution... I don't know...

**Comment by naogify** [comment]
I also prefer padding-top for accessibility reasons. I commented here https://github.com/maplibre/maplibre-gl-js/pull/344#issuecomment-922211086 for the detail.

So, I created PR for adding padding-top. https://github.com/maplibre/maplibre-gl-js/pull/354
