### ISSUE TITLE
Terrain 3D zoom is reversed in high pitch, when pointing above horizon

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#3398]
Demo here: https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/

Try holding the mouse over the white sky, and scroll - it'll move in the opposite direction compared to if the mouse is on a mountain.

I'm scrolling my mouse in the same direction direction all the time, but the map zoom in opposite direction depending on what i hover

https://github.com/maplibre/maplibre-gl-js/assets/74932975/0f5ff5da-9fc5-4c2c-b12a-dabc2d525ba7

**Comment by HarelM** [comment]
Relevant discussion can be found here about this can be found here:
https://github.com/maplibre/maplibre-gl-js/pull/3312

**Comment by Pheonor** [comment]
@HarelM I have a fix for this issue. Could you assign it to me ?

**Comment by HarelM** [comment]
@Pheonor let me know if you would like me to assign a bounty on this issue.

**Comment by Pheonor** [comment]
Thank you @HarelM but I do not a bounty for this one.
