### ISSUE TITLE
Do we need to import ImageData ?

### ISSUE THREAD

**Issue by astridx** [maplibre/maplibre-gl-js#340]
### Question

While playing around with Jest I get the following error message at this point: https://github.com/maplibre/maplibre-gl-js/blob/16c6c3f99bc05ff0ecefc764805ad5300b4b14b8/test/unit/data/dem_data.test.js#L137

```
ReferenceError: ImageData is not defined

      154 |     }
      155 |
    > 156 |     if (input instanceof ImageData) {
          |                          ^
      157 |         if (transferables) {
      158 |             transferables.push(input.data.buffer);
      159 |         }

      at serialize (src/util/web_worker_transfer.ts:156:26)
      at Object.<anonymous> (test/unit-jest/data/dem_data.test.ts:135:37)


```

I think ImageDate is this: https://developer.mozilla.org/en-US/docs/Web/API/ImageData

Could it be that we have to import this via

`Import ImageData from 'canvas'`

in the file https://github.com/maplibre/maplibre-gl-js/blob/main/src/util/web_worker_transfer.ts ?

or am I missing something?

**Comment by HarelM** [comment]
I mocked this in current tests in stub_loader.js file. I think you can do the same...

**Comment by astridx** [comment]
OK. Thank you.
