### ISSUE TITLE
Labels don't appear when enabling terrain at high zooms

### ISSUE THREAD

**Issue by SnailBones** [maplibre/maplibre-gl-js#3454]
**maplibre-gl-js version**: main

**browser**: Firefox and Chrome

### Steps to Trigger Behavior

 1. Create a map with labels and a terrain source ([e.g. MapTiler's example](https://www.maptiler.com/news/2022/05/maplibre-v2-add-3d-terrain-to-your-map/))
 2. Ensure terrain is disabled
 3. Zoom in (>15.5)
 4. Enable terrain

### Link to Demonstration

https://codepen.io/snailbones/pen/rNPoZpe

### Expected Behavior
Labels should be visible. Here is the 2d map before enabling terrain:
![image](https://github.com/maplibre/maplibre-gl-js/assets/14878684/a6fd1da7-369d-454a-bb3b-c38a5be056bd)

### Actual Behavior

Labels are missing. They do not load until the user triggers a map update.
![image](https://github.com/maplibre/maplibre-gl-js/assets/14878684/4480ae38-b1e8-49c3-8cbf-ccdc1fd28618)

**Comment by HarelM** [comment]
Bounty direction:
https://github.com/maplibre/maplibre/issues/189
Assigning S bounty.

**Comment by SnailBones** [comment]
@HarelM I'm interested in fixing this!

**Comment by SnailBones** [comment]
https://opencollective.com/maplibre/expenses/181572
