### ISSUE TITLE
`setOpacity` and opacity options for `Marker`

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#3458]
## User Story

As a user I would like to be able to set the opacity of a marker when terrain 3D is on in case I override it with css or for whatever other reason

## Rationale

When terrain is on and the marker is behind terrain the opacity is set to 0.2 and returned to 1.0 when not behind terrain.
If I set this value in the css I'll get a behavior that is not intended, and therefore there's a need to disable it or define other values beside 0.2 and 1.

## Impact
The is a workaround as one can programmatically change this so this is a "nice to have" API for the marker.

**Comment by sbachinin** [comment]
This has to be closed I guess

**Comment by HarelM** [comment]
Fixed by #3620
