### ISSUE TITLE
Tile URL replace all occurrences of {x}{y}{z}

### ISSUE THREAD

**Issue by boldtrn** [maplibre/maplibre-gl-js#346]
## Motivation

I'd like to use raster tiles from maps-for-free. The url format of these tiles are: `https://maps-for-free.com/layer/relief/z{z}/row{y}/{z}_{x}-{y}.jpg`.

I am aware that this is a rather uncommon url scheme.

### Implementation

Right now it seems that maplibre-gl-js only replaces the first occurrence of each of the variable and not all occurrences.

Probably `replace` should be replaced with `replaceAll` [here](https://github.com/maplibre/maplibre-gl-js/blob/e78ad7944ef768e67416daa4af86b0464bd0f617/src/source/tile_id.ts#L36).

**Comment by HarelM** [comment]
Can transform request help in this case?

**Comment by boldtrn** [comment]
Ah you are right, with some further string search and replace functions it should be possible to extract the `z` and `y` values again from the url. 

But I am not sure if this is a general issue? For example Leaflet is replacing all occurrences.

**Comment by HarelM** [comment]
I see your point.
Your best bet is to send a PR. This should be relatively simple I guess...

**Comment by rbrundritt** [comment]
I came across this issue a few years ago and felt at the time it was an edge case, and at the time just used a request transform. Seeing that someone ran into this, I've made a small PR to address this. #348

**Comment by HarelM** [comment]
The change is so minor I don't see a reason not to add this... Thanks!!

**Comment by boldtrn** [comment]
Thanks a lot for integrating this change 🎉
