### ISSUE TITLE
When updating the style with `diff:true` and terrain change the map doesn't change

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#3463]
There is a way to have the map look for changes in the style and apply them automatically, which is a great feature, but it doesn't take the terrain part of the spec into consideration.

Here's an example:
https://jsbin.com/muriqipaba/edit?html,output
When switching from `diff: true` to `diff:false` the 3D is removed, but it should also work for diff mode of update style.

Motivation:
I tried to add the terrain configuration to maputnik only to discover this doesn't work due to this issue.
Also maputnik doesn't use typescript, so upgrading to version 3/4 from the current version (2.4) will be a nightmare...

**Comment by neodescis** [comment]
A workaround is to call `setTerrain` instead, but it would be great to have this fixed. The default for `diff` is true if not specified.

**Comment by HarelM** [comment]
This requires a change in both spec package and here apparently.
But the fix is pretty simple.
I'll change how the diff operations are applied while on it, to improve readability.
