### ISSUE TITLE
cooperativeGestures in fullscreen: allow single finger dragPan (default behaviour)

### ISSUE THREAD

**Issue by elgandoz** [maplibre/maplibre-gl-js#3482]
**maplibre-gl-js version**: 3.6.2

**browser**: Chrome Android

### Steps to Trigger Behavior

 1. On a touch  device, visit https://maplibre.org/maplibre-gl-js/docs/examples/cooperative-gestures/
 2. Enable fullscreen in the example
 3. Drag the map with one finger

### Expected Behavior
The map should pan when using a single finger. 

### Actual Behavior
The map is still unresponsive to single finger drag.
Oddly, 2 fingers drag handles both panning (incorrect) and tilting (correct), but the other gesture behaves like expected.

-------

According to #661  and #1488, the expected behaviour should be dragging the map like `cooperativeGesture` wouldn't be enabled at all.

This is indeed what happens with MapBox (https://docs.mapbox.com/mapbox-gl-js/example/cooperative-gestures/).

Even by re-enabling programmatically the drag behaviour (with `dragPan.enable()`) doesn't resolve the issue.

I saw that there is some refactoring happening concerning the cooperativeGesture for the upcoming 4.0.0, but this issue doesn't seem to be addressed (not that I could find).

**Comment by HarelM** [comment]
I've refactored the hell out of this component.
Please let me know if this is not addressed in 4.0.0-pre.2 version.

**Comment by elgandoz** [comment]
It works as expected in 4.0.0.
https://codepen.io/elgandoz/pen/dyaBvNE

Thanks for your work.

**Comment by elgandoz** [comment]
@HarelM do you know if the correct behaviour can be achieved on an earlier version?

**Comment by HarelM** [comment]
Maybe you can use patch-package with cherry picking.
Backporting is time consuming and we prefer not to do it...
