### ISSUE TITLE
icon-image not displaying

### ISSUE THREAD

**Issue by elgandoz** [maplibre/maplibre-gl-js#3483]
**maplibre-gl-js version**: 4.0.0-pre.2

**browser**: Chrome MacOS

### Steps to Trigger Behavior

 1. Use the icon-image example from the documentation
 2. Swap the library version from 3.6.2, to 4.0.0-pre.2

### Link to Demonstration
https://codepen.io/elgandoz/pen/ExrBwzy

### Expected Behavior
The image of the cat appear at the given coordinates (like https://maplibre.org/maplibre-gl-js/docs/examples/add-image/)

### Actual Behavior
The image doesn't appear. No error thrown in the console, but you can see the image is loaded in the network tab.

**Comment by HarelM** [comment]
loadImage and addImage example and API changed on 4.0 from callbacks to promises... It is expected.

**Comment by HarelM** [comment]
If there's anything specific that need to be done please reply.
For now I'll be closing this issue, I'll reopen if needed.
