### ISSUE TITLE
Map gets blurry when canvas width exceeds 2200 pixels

### ISSUE THREAD

**Issue by timsluis** [maplibre/maplibre-gl-js#3503]
Map instances becomes gradually more blurry as the canvas width exceeds 2200 pixels. This issue impacts the visual quality of the map when it's displayed in larger dimensions.

**maplibre-gl-js version**: 3.6.2 (3.6.1 in JS Bin)

**browser**: Chrome, Firefox

### Steps to Trigger Behavior

1. Create a MapLibre GL map instance.
2. Set the map width to a value greater than 2200 pixels, for example, 2500 pixels.
3. Load map data and tiles onto the map.
4. Observe the map gradually becoming blurrier as the map width increases.

### Link to Demonstration

https://jsbin.com/hazuxoceco/1/edit?html,output

### Expected Behavior

The map should maintain a consistent level of visual clarity and detail regardless of the map width.

### Actual Behavior

As the map width exceeds 2200 pixels, it starts to exhibit gradual blurriness, reducing the overall quality of the map.

**Comment by HarelM** [comment]
Looks very similar to me, what am I missing?
![image](https://github.com/maplibre/maplibre-gl-js/assets/3269297/1b02e9da-091c-4276-bdbe-53fe5a82dc72)

**Comment by neodescis** [comment]
I can tell the difference. The one on top does indeed look blurry, in both Firefox and Chrome.

**Comment by timsluis** [comment]
This is how it is for me (on MacBook M1):
![Screenshot 2023-12-19 at 17 26 40](https://github.com/maplibre/maplibre-gl-js/assets/235880/ddb35d6a-caae-467a-a135-c3ff21f76255)

Same effect on iPhone. 

v3.1.0 is still sharp, the bug seems to be introduced in v3.2.0.

**Comment by timsluis** [comment]
Can image it might be related to: https://github.com/maplibre/maplibre-gl-js/pull/2674

**Comment by HarelM** [comment]
@timsluis did you try and set a larger value to maxCanvasSize to see if it solves this issue?
CC: @HandyMenny

**Comment by HandyMenny** [comment]
> Can image it might be related to: #2674

Yes, maplibre internally is limiting pixelRatio (ie. density) to respect maxCanvasSize (defaults to 4096px).
You can raise it to any value (even infinity), but pixelRatio is still limited if you are above what your webgl context can render.

**Comment by timsluis** [comment]
@HarelM It doesn't make a difference.

@HandyMenny @HarelM When I switch the maplibre version in the JS Bin to v3.1.0, the map renders with a higher quality and without distortions.

See: https://jsbin.com/recahoyine/edit?html,output

With my default pixelRatio of 2 is still working perfectly. Only when I manually set it to 11, distortions start to appear. Maybe the downgrading is a bit too strict? Should it be something you can opt in for?

**Comment by HandyMenny** [comment]
> @HarelM It doesn't make a difference.
> 

so do you see this one as blurry? https://jsbin.com/xivosevoco/1/edit?html,output ?

**Comment by timsluis** [comment]
Thanks, that explains.

This is my viewport:
DPR: 2.00
Screen Size: 3360 × 1418 (map on full screen, but it starts to get blurry using widths >2200px)

The use case is a map on a large touch table. Although not sure if it would exceed these dimensions.

**Comment by HandyMenny** [comment]
> but it starts to get blurry using widths >2200px

That's because 2 x 2200px is above 4096px.


> The use case is a map on a large touch table. Although not sure if it would exceed these dimensions.

Thanks, so I would say there is no need to update the default value. But I would add some warnings, so developers are aware of what's going on under the hood
