### ISSUE TITLE
terrarium-encoded raster-dem source does not work if `url` is used

### ISSUE THREAD

**Issue by zstadler** [maplibre/maplibre-gl-js#3527]
**maplibre-gl-js version**: 3.6.2

**browser**: Firefox, Chrome

### Steps to Trigger Behavior

1. Create a raster-dem source with a `url` containing an appropriate TileJSON URL
2. Add `"encoding": "terrarium"` to this source
3. Create a hillshade layer using that source

No hillshade is shown

### Link to Demonstration

- [Terrarium source using `url`](https://jsbin.com/nosijew/2/edit?html,output) - no hillshade
- [Terrarium source using `tiles`](https://jsbin.com/nosijew/5/edit?html,output) - proper hillshade
- [TerrariainRGB source using `url`](https://jsbin.com/nosijew/4/edit?html,output) - proper hillshade

### Expected Behavior
![image](https://github.com/maplibre/maplibre-gl-js/assets/1304610/264f45fb-aa29-41fb-a7d3-32b9edede78d)

### Actual Behavior
![image](https://github.com/maplibre/maplibre-gl-js/assets/1304610/3d365df1-ac01-435f-8fbe-22d26d50723c)

**Comment by HarelM** [comment]
Can you check if this is also the behavior in 4.0.0-pre.2 version?
I don't see any difference between the processing of tilejson between the terrainum and mapbox encoding.
The only thing I can think of is that mapbox is the default and for some reason terranium is not updated as part of the tilejson loading.
Relevant parts of the code:
Default initialization:
https://github.com/maplibre/maplibre-gl-js/blob/d7dec1b4b9bec1b6cf4a5e623498a0613a119647/src/source/raster_dem_tile_source.ts#L48C9-L48C54
Update class parameters with tilejson values:
https://github.com/maplibre/maplibre-gl-js/blob/d7dec1b4b9bec1b6cf4a5e623498a0613a119647/src/source/raster_tile_source.ts#L97
Sending to worker:
https://github.com/maplibre/maplibre-gl-js/blob/d7dec1b4b9bec1b6cf4a5e623498a0613a119647/src/source/raster_dem_tile_source.ts#L79
In the worker:
https://github.com/maplibre/maplibre-gl-js/blob/d7dec1b4b9bec1b6cf4a5e623498a0613a119647/src/source/raster_dem_tile_worker_source.ts#L19

**Comment by zstadler** [comment]
Yes, this is also the case with 4.0.0-pre.2

**Comment by acalcutt** [comment]
Seems to work fine for me on this test page
https://stackblitz.com/edit/web-platform-vakaha?file=index.html

**Comment by acalcutt** [comment]
One thing i notice in your tilejson is bounds is all 0, I think that may cause this layer to be hidden

your tilejson
```
{
  "tilejson": "3.0.0",
  "scheme": "xyz",
  "tiles": [
    "https://pmtiles.israelhikingmap.workers.dev/pmtiles/jaxa_terrarium0-11/{z}/{x}/{y}.png"
  ],
  "attribution": "<a href=https://earth.jaxa.jp/en/data/policy/>AW3D30 (JAXA)</a>",
  "description": "JAXA ALOS World 3D 30m (AW3D30) converted with rio rgbify",
  "name": "jaxa_terrarium_0-11",
  "version": "1",
  "bounds": [
    0,
    0,
    0,
    0
  ],
  "center": [
    0,
    0,
    0
  ],
  "minzoom": 0,
  "maxzoom": 11
}
```

vs mine
```
{
  "tiles": [
    "https://tiles.wifidb.net/data/jaxa_terrarium/{z}/{x}/{y}.png"
  ],
  "name": "jaxa_terrarium_0-11",
  "format": "png",
  "basename": "jaxa_terrarium0-11.mbtiles",
  "id": "jaxa_terrarium0-11",
  "description": "JAXA ALOS World 3D 30m (AW3D30) converted with rio rgbify",
  "version": "1",
  "type": "baselayer",
  "attribution": "<a href=https://earth.jaxa.jp/en/data/policy/>AW3D30 (JAXA)</a>",
  "minzoom": 0,
  "maxzoom": 11,
  "bounds": [
    -180,
    -85.05112877980659,
    180,
    85.0511287798066
  ],
  "center": [
    0,
    0,
    5
  ],
  "tilejson": "2.0.0"
}
```

**Comment by acalcutt** [comment]
I tested changing the bounds in your tilejson and it seemed to fix it for me with your source
https://stackblitz.com/edit/web-platform-1t8wrr?file=tiles.json

**Comment by zstadler** [comment]
@acalcutt ,
Nice catch!

The `jaxa_terrarium0-11.pmtiles` I use has incomplete/incorrect metadata.

```
> pmtiles show jaxa_terrarium0-11.pmtiles
pmtiles spec version: 3
tile type: Raster PNG
bounds: 0.000000,0.000000 0.000000,0.000000
min zoom: 0
max zoom: 11
center: 0.000000,0.000000
center zoom: 0
addressed tiles count: 5255125
tile entries count: 2309770
tile contents count: 2215124
clustered: true
internal compression: 2
tile compression: 1
format png
name jaxa_terrarium_0-11
type baselayer
version 1
attribution <a href=https://earth.jaxa.jp/en/data/policy/>AW3D30 (JAXA)</a>
description JAXA ALOS World 3D 30m (AW3D30) converted with rio rgbify
``` 

P.S., I probably downloaded it using the torrent from [your post](https://www.techidiots.net/downloads/open-base-map-torrents/pmtiles/jaxa_terrarium0-11_pmtiles-torrent/view).

**Comment by acalcutt** [comment]
Looking at this an I confirm what you see with my local file. it is most likely because the original mbtiles file I converted from does not have bounds in it's metadata, so that converted to 0s

```
# sqlite3 jaxa_terrarium0-11.mbtiles
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> select * from metadata;
format|png
name|jaxa_terrarium_0-11
description|JAXA ALOS World 3D 30m (AW3D30) converted with rio rgbify
version|1
type|baselayer
attribution|<a href=https://earth.jaxa.jp/en/data/policy/>AW3D30 (JAXA)</a>
```


In the case of tileserver-gl I had put in some code that replaces empty bounds, which is probably why I haven't noticed it here
https://github.com/maptiler/tileserver-gl/blob/master/src/pmtiles_adapter.js#L71-L80

**Comment by zstadler** [comment]
As a workaround to the missing info in the TileJSON, the bounds can be specified in the source definition.

```
"sources": {
  "terrarium_url": {
    "type": "raster-dem",
    "encoding": "terrarium",
    "url": "https://pmtiles.israelhikingmap.workers.dev/pmtiles/jaxa_terrarium0-11.json"
    "bounds": [
      -180,
      -85.0511287,
      180,
      85.0511287
    ],
  }
}
```
