### ISSUE TITLE
Replace odd usage of "+" to coerce to number with parseInt

### ISSUE THREAD

**Issue by thiccaxe** [maplibre/maplibre-gl-js#3539]
Should instances of "+" that are meant to coerce strings into numbers be replaced with parseInt?

Files in `camera.ts`, e.g. 

https://github.com/maplibre/maplibre-gl-js/blob/71f092a73d87bca8f76231e37b5bba67cc3503e2/src/ui/camera.ts#L1318

seem to be offenders. Haven't encountered it anywhere else, but thought it odd. Will PR.

**Comment by HarelM** [comment]
In typescript, + supports both string and number, while parseInt or parseFlout doesn't...

**Comment by thiccaxe** [comment]
In this specific case, isn't the type on duration `number` anyway? 

Well, I don't know. More clear code with typescript annotation might be better, and code minifiers would probably convert that back to +...

**Comment by HarelM** [comment]
I don't see a huge benefit of replacing this, do you?
