### ISSUE TITLE
queryRenderedFeatures within feature collection not working

### ISSUE THREAD

**Issue by rbrtmrtn** [maplibre/maplibre-gl-js#3540]
**maplibre-gl-js version**: 3.6.2

**browser**: Brave 1.61.109 (Chromium 120.0.6099.144)

### Steps to Trigger Behavior

 1. Add a point layer
 2. Call `queryRenderedFeatures` on the point layer, providing a `filter` with a `within` expression and a GeoJSON feature collection of polygons that contain the points
 3. Only points within the _first_ feature are returned; should be all

### Link to Demonstration

I've created a minimal example of this which

- queries rendered points `within` a feature collection of polygons
- sets the feature state of points returned by the query so they turn red on the map

https://codepen.io/rbrtmrtn/pen/abMvYvK

### Expected Behavior

Both points should turn red because both of the are `within` the feature collection.

### Actual Behavior

Only one is red. The issue seems to be that `queryRenderedFeatures` is only returning a single point — the one that falls within the first polygon encountered in the feature collection. Looking at the [docs](https://maplibre.org/maplibre-style-spec/expressions/#within) for `within` expressions, however, it looks like a feature collection should be a valid argument.

![image](https://github.com/maplibre/maplibre-gl-js/assets/1463553/08c5b048-122b-4928-a06a-ef1616cdf8a4)

**Comment by HarelM** [comment]
Yes, this looks like a bug.
As a workaround, I found out that using a `Feature` of type `MultiPolygon` instead of a list of polygons works as expected (don't use `FeatureCollection`).

I also tried to add a test to the expressions test with this use case and it seems to fail, so it looks like an actual bug that should be easy to test, reproduce, and hopefully solve.
https://github.com/maplibre/maplibre-gl-js/tree/main/test/integration/expression

Let me know if you would like to try and tackle this.

**Comment by rbrtmrtn** [comment]
Thanks so much for the prompt dive into this @HarelM ! Really appreciate that.

I would like to help with a fix. I'm a bit low on cycles right now so I may have to use the `MultiPolygon` workaround, but will keep this on my radar and report back when I can dive in further.

Thanks again!

**Comment by HarelM** [comment]
Found the issue, it does only take the first one apparently.
I'll move the tests and code to the relevant repo. I'll link it here shortly.

**Comment by rbrtmrtn** [comment]
Thank you @HarelM, glad to hear you tracked the problem down 🤩 (And thank you @sbachinin for putting in a fix!) I'll keep an eye on https://github.com/maplibre/maplibre-style-spec/pull/477 and start using that code once it's merged.
