### ISSUE TITLE
4.0.0-pre.3 does not export `Map` in typescript

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#3563]
This is basically described here:
https://github.com/timocov/dts-bundle-generator/issues/287

I would like to have the `dts-bundle-generator` fix this, worst case we can revert to version 8.1.2.

**Comment by timocov** [comment]
> does not export Map in typescript 

and `Event` as well. As I mentioned in the ticket the problem is in the build script here https://github.com/maplibre/maplibre-gl-js/blob/b364c529d63d39012e28e7e1a4882e1c413d2a7d/build/generate-typings.ts#L14

**Comment by HarelM** [comment]
I've created the following PR:
https://github.com/maplibre/maplibre-gl-js/pull/3564
I'm not sure this is the right solution as every new exported class will need to be added in two places and every type that is part of a method signature will need to be manually added, which is a maintenance burden and error prone... :-/
