### ISSUE TITLE
Raster zoom or layer replace flicker when raster layer takes up most of the browser viewport

### ISSUE THREAD

**Issue by wagewarbler** [maplibre/maplibre-gl-js#3595]
**maplibre-gl-js version**: 3.5.0

**browser**: Chrome 120.0.6099.224

### Steps to Trigger Behavior

 1. Load raster layer
 2. Try stepping back & forth with raster layer taking up ~2/3 or less of the browser viewport 
 3. Decrease size of browser so that the raster layer takes up all or nearly all of the browser viewport and step back & forth between the same 2 zoom levels. Observe flicker

### Link to Demonstration

I'm not sure how clear this demo is since these videos get auto-resized to fit, but please understand that both of these demonstrations are moving between 2 zoom levels that request that same tile zoom/z of 5. The only difference between them is the size of the viewport. Also, apologies for video jankiness in general, but I think you can still see the load hesitation and flicker on the 2nd one, even with the jank factor.

## What works fine

[Screencast from 2024-01-18 20-57-54.webm](https://github.com/maplibre/maplibre-gl-js/assets/133472204/0669612b-c242-4669-978e-0fa16c9f7e8f)

## What doesn't work as well, same zoom levels, smaller viewport

[Screencast from 2024-01-18 20-58-51.webm](https://github.com/maplibre/maplibre-gl-js/assets/133472204/5ae0101b-48b9-4314-b345-97df2ffc6c2e)

### Why I care

I'd like to understand if this is avoidable behavior. I'm currently working on cache-driven playback capability and this is the simplest repeatable example I can provide to show the issue that affects my ability to "play" layers back over time. Basically, I have a setup that supports swapping out raster layers quickly, and it works really well when the layer doesn't take up most of the viewport, but there's a clear flicker and queue backlog when the raster layer takes up most of the viewport.

Happy to tackle a fix (if fixable) provided someone can help me understand the problem!

**Comment by HarelM** [comment]
Without a minimal reproduction of the problem there's not much we can do...

**Comment by wagewarbler** [comment]
Hmm, Ok. I'm using proxied raster tile resources so I can't easily share my exact setup, but I'll start looking into a repeatable public-facing setup. That said, I don't get the impression this is source-specific. It seems like a behavior related to general raster rendering. Maybe I just need to dig into the details of how that works so I can better understand the problem. I was just hoping someone might've seen something similar or have some cursory thoughts on it

**Comment by neodescis** [comment]
Have you by chance tried setting `raster-fade-duration` to 0? I know a non-zero value causes some unexpected behavior on video layers.

**Comment by wagewarbler** [comment]
I did indeed try that. No real difference unfortunately.

I may be narrowing in on the problem. Since my approach involves building up cache, I'm using a service worker to intercept MapLibre fetches to retrieve responses from cache when possible. This is in no way specific to MapLibrea but FWIW, here's the code:

```ts
    sw.addEventListener("fetch", function (event: FetchEvent) {
      const cacheUrl = event.request.url;

      return event.respondWith(
        caches.match(cacheUrl).then(function (response) {

          return (
            response ||
            fetch(event.request).then(function (response) {
              const responseClone = response.clone();
              caches.open("mapClientCache").then(function (cache) {
                cache.put(cacheUrl, responseClone);
              });
              return response;
            })
          );
        })
      );
    });
```

My hunch is that there's a render timing difference for different layer/viewport situations that's imperceptible for normal use, and therefore not a real problem, but the lag I'm introducing brings it into the realm of being an issue. I'll keep working to verify the issue, if I'm correct I'll go ahead and close the issue.

**Comment by wagewarbler** [comment]
Upon further investigation, I think what I'm seeing is a real issue, there's a similar issue captured for MapBox [here](https://github.com/mapbox/mapbox-gl-js/issues/12707).

**Comment by HarelM** [comment]
There's no question if this is a real issue or not, but in order for us to be able to help, we'll need a minimal reproduction of the issue, you'll need that too if you want to fix this.
Generally speaking, the main code related to raster is in `raster_tile_source.ts` and `source_cache.ts`.

**Comment by wagewarbler** [comment]
I've created a demo example of the issue here: https://codepen.io/wagewarbler/pen/BaEgpbv

Thanks to fairly responsive map servers and browser caching, the tile switches are actually pretty performant here, but if you stare at the map during the transitions (or if need be, slow down your network bandwidth in browser dev tools), you can see a flash of the underlying basemap labels between raster layer loads. This of course becomes more of an issue when you're dealing with slower servers and/or more frequent updates (in my case both of these are in effect).
