### ISSUE TITLE
[accessibility] Consider conveying only one of `aria-label` and `title` in controls

### ISSUE THREAD

**Issue by Malvoz** [maplibre/maplibre-gl-js#362]
Most controls use both `aria-label` and `title` with identical values,
for example the zoom in control:

```html
<button ...
  title="Zoom in"
  aria-label="Zoom in">
  <span class="maplibregl-ctrl-icon" aria-hidden="true"></span>
</button>
```

This would cause some screen readers, such as NVDA, to announce <q>Zoom in</q> twice. Although this is considered a bug (https://github.com/nvaccess/nvda/issues/7841, in the case of NVDA) the issue can be fixed by conveying only one of `title` or `aria-label`.

To avoid double speak while maintaining the native tooltips from `title` the `title` attribute could be set on the `maplibregl-ctrl-icon` icon instead:
```html
<button ...
  aria-label="Zoom in">
  <span class="maplibregl-ctrl-icon" aria-hidden="true" title="Zoom in"></span>
</button>
```

In this case the `aria-label` would be conveyed to <span title="Assistive technology">ATs</span> and the native tooltip still available on hover. But there would be no double speak as the `title` is hidden from ATs due to `aria-hidden="true"`.

<hr>

(The same issue was also reported with MapBox: https://github.com/mapbox/mapbox-gl-js/issues/11036.)

**Comment by rbrundritt** [comment]
Good distinction on both and when to use one, the other, or both: https://mauss.dev/posts/aria-label-vs-title-attribute
