### ISSUE TITLE
Unit test "Map#isSourceLoaded (equivalent to event.isSourceLoaded)" may have stability issue

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#3623]
### Steps to Trigger Behavior

 1. npm run test-unit

### Expected Behavior
100% stable and all pass

### Actual Behavior
Roughly 10% chance it would fail on one test "Map#isSourceLoaded (equivalent to event.isSourceLoaded)"

I narrowed it down by commenting out all others in that file and leave only 2:
https://github.com/maplibre/maplibre-gl-js/blob/4ed9cf07b8ee6cb2ad5ed2258287d988252bfa8d/src/ui/map.test.ts#L557C1-L593C12
and running just these two, almost 50% time it would fail.

Interesting enough, running them one by one will always success. I am not sure if the problem is from test cases or production code itself.

This test was added by:
https://github.com/maplibre/maplibre-gl-js/commit/ded439d314293afb20751ba9652483821228c0dd#diff-1369f2165e0778abbb2cdd9a17b1527434e25ed2cd4f9dd49dfe31396d51c426

@ambientlight would you mind to take a look? Anyone else is available to help? Greatly appreciated !!
Meanwhile I will try to find some time to keep digging.

**Comment by HarelM** [comment]
I've seen it too, seems like some sort of race condition with dirty state, but it was too complicated to understand and needed more time.
Feel free to pursue this, I generally think there's an actual bug here...
