### ISSUE TITLE
Navigation Control zooming in very small increments

### ISSUE THREAD

**Issue by Justgo13** [maplibre/maplibre-gl-js#3624]
**maplibre-gl-js version**: v3.6.2

**browser**: chrome

### Steps to Trigger Behavior

 1. Click zoom in button 
 2. Have to click zoom in button multiple times and zoom is going in very small increments

https://github.com/maplibre/maplibre-gl-js/assets/37590812/d30a5b37-f04d-4597-82e5-1486c2c6cdc9

### Expected Behavior
Zoom control zooms in quick

### Actual Behavior
Zoom control zooms in at very small increments

**Comment by HarelM** [comment]
You can create a zoom control that zooms more.
The default is to increase 1 level of zoom.

**Comment by Justgo13** [comment]
How would i do that?
