### ISSUE TITLE
IOS capacitor (webview) crash

### ISSUE THREAD

**Issue by loremru** [maplibre/maplibre-gl-js#3626]
Error: Timed-out while waiting for reply for WebPage_TouchEventSync
Behavior: App freezes and map disappears
Additional info: Only map with vector, raster ok
Mapbox has same behavior

**Comment by HarelM** [comment]
Might be something in your code.
I have a capacitor app that is working as expected.
Not that this is an indication, as there might be bugs in maplibre too.

**Comment by loremru** [comment]
> Might be something in your code. I have a capacitor app that is working as expected. Not that this is an indication, as there might be bugs in maplibre too.

Yea, I see your app works good. I will provide reproduction repository

**Comment by loremru** [comment]
> Might be something in your code
You was right, there was something with my code. Definetly mistake was use mapbox instead of maplibre...
It's only mapbox issue
