### ISSUE TITLE
[accessibility] Accessible target size for controls

### ISSUE THREAD

**Issue by Malvoz** [maplibre/maplibre-gl-js#363]
The <span title="Web Content Accessibility Guidelines">WCAG</span> 2.1 <span title="Success Criterion">SC</span> [2.5.5 Target Size](https://www.w3.org/TR/WCAG21/#target-size) requires targets for [_pointer input_](https://www.w3.org/TR/WCAG21/#dfn-pointer-inputs) to be at least **44 by 44 in CSS pixels**. Meeting this requirement has [multiple benefits](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html#benefits), it'd be great to pass this criteria for the commonly used controls:

- Attribution control (`maplibregl-ctrl-attrib-button`)
- Popup close button (`maplibregl-popup-close-button`)
- Fullscreen control (`maplibregl-ctrl-fullscreen`)
- Location control (`maplibregl-ctrl-geolocate`)
- Markers (`maplibregl-marker`)
- Navigation controls:
  - Zoom in (`maplibregl-ctrl-zoom-in`)
  - Zoom out (`maplibregl-ctrl-zoom-out`)
  - Compass/reset bearing (`maplibregl-ctrl-compass`)
- etc.?

It may not be desirable to increase the size of the icons themselves, in which case [`padding` can be used to increase the  size of the tap targets](https://web.dev/tap-targets/#how-to-fix-your-tap-targets).

<hr>

(The same issue was also reported with MapBox: https://github.com/mapbox/mapbox-gl-js/issues/11037.)

**Comment by alexclaydon** [comment]
Shame this was closed - it's a fantastic idea. Particularly - but not only - for those with motor control challenges.

**Comment by mjpauly** [comment]
Rem scaling would be great. Font/icon/layout sizing can then scale according to the user device's system font size if the root font is set appropriately on a page. [E.g. for Apple.](https://dev.to/colingourlay/how-to-support-apple-s-dynamic-text-in-your-web-content-with-css-40c0) A workaround is to add one's own overrides for Maplibre's CSS to change px definitions to rem.

**Comment by HarelM** [comment]
Feel free to submit a PR.
I'm having a hard time understanding exactly how to solve this issue as I'm not an expert in this field.
I'd be happy to review and merge any PR related to improved accessibility.
