### ISSUE TITLE
Change altitude of look at point?

### ISSUE THREAD

**Issue by Philip2809** [maplibre/maplibre-gl-js#3683]
## User Story
As a developer where I am making 3d buildings with toggleable floors I would benefit from having a way of changing the altitude of camera look at/rotation around point, I think it is called the focal point of the camera.

## Rationale
Because having a 3d map with toggleable floors, either tough extrusions or three js, it would be nice to be able to change the altitude of the camera look at point. I know this is possible today because of the terrain and when you have different altitudes in the terrain this works. I would appreciate if someone who is more familiar with the codebase could help me find where this calculations of the altitude happens and maybe I can work to implement something myself from there. 

## Impact
Would make 3d worlds more enjoyable and easier to navigate for everyone!

**Comment by HarelM** [comment]
What's preventing you from doing it now?

**Comment by Philip2809** [comment]
I can't find where I would do this today?

**Comment by HarelM** [comment]
This is probably similar to what's here, maybe with a few different parameters:
https://github.com/maplibre/maplibre-gl-js/blob/90a946355deed13b74f8de38d85795a2d32c0fb4/src/ui/camera.ts#L919

**Comment by Philip2809** [comment]
Does this change the altitude of the focal point?

**Comment by HarelM** [comment]
Not sure I understand the question. Play with it and see if it helps.

**Comment by Philip2809** [comment]
Managed to figure out what I wanted in more detail. In the transform.ts file, If I set the this.elevation and this._elevation to 180. (hard coded to demonstrate) I get exactly what I want:
![firefox_aNUR1U5dR7](https://github.com/maplibre/maplibre-gl-js/assets/51290462/691f635d-440d-4a58-8b92-6e03e7f9f245)
Rotation around a point that is above the ground, Is this called the pivot point?
May I make a pull request where you can set an additional variable to "add" more elevation like this?
I am not very familiar with the codebase but an option to when displaying "fill-extrusion" could be to automatically change this value when your "camera look at point" (pivot point?) is above a building? But just a feature were I can change this value and the height of your camera automatically would be awesome when making toggleable floors on a 10+ floor building

**Comment by Philip2809** [comment]
Yes, I was thinking about that, changing this in the transform class might cause a lot of problems in other places. There is some automated tests today that you can run to test this? For a bigger feature like this, a design post/document would be smart, where do you have that stuff today?

**Comment by HarelM** [comment]
There are a lot of tests, opening a PR would run them all and you can look into the readme scattered in this repo to better understand how to run all kind of tests.
Regarding design, you can either update the initial post in this issue, or create a PR with the design (although a PR is usually after you write some code, but you can create a draft PR I guess).
There are also the docs in the developer guides, I don't know if this is the right place, there are some design documents there...
In any case, the important thing is the design, we can later on decide where to put it.

**Comment by Philip2809** [comment]
Played around with it a bit more and found this so far:
instead of using the ._elevation and .elevation in the _calcMatrices function I make a variable "elevation", add my pivot elevation and then use this in the function in place of the elevation. This seams to work perfectly where the elevation is 0, in a city and stuff, but when trying this on the terrain example it falls apart. If you go to the example:
https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/
There is already a little "jump" when moving around, zoom in far around a mountain. Another bug that is there today is when you don't move but hold the right mouse button to pan down and then the map center moves. Both of these bugs are exaggerated when adding more height with this pivotelevation. 

Issue on terrain example today:
![firefox_wZ21OOj1St](https://github.com/maplibre/maplibre-gl-js/assets/51290462/953e4047-93ca-415f-9dc4-713c1e546f97)
Load in, get center, hold right mouse button, move down, repeat a couple of times this happens:
![image](https://github.com/maplibre/maplibre-gl-js/assets/51290462/878eeddb-0f61-4271-9081-878c91afa9ac)

As said before, these or other issues are exaggerated when I add more altitude and I get some different bugs depending on if I set add the elevation variable or only use the pivotelevation in the _calcMatrices function.

**Comment by HarelM** [comment]
Yes, we have some bugs related to zoom and terrain unfortunately which appear to be hard to solve, see:
- #2094

**Comment by HarelM** [comment]
I think the following PR will allow this requirement.
- #4851
