### ISSUE TITLE
Style.setState ignores validation options

### ISSUE THREAD

**Issue by dsshep** [maplibre/maplibre-gl-js#3709]
**4.0.0**:

### Steps to Trigger Behavior

 1. Create a map with `{ validateStyle: false }`
 2. Update the style with `map.setStyle(..., { validate: false })`
 3. The style is validated, despite both settings.

### Link to Demonstration
E.g. something like this should not cause a validation error: 

```lang=js
const map = new maplibregl.Map({
  container: 'map',
  style: {
    version: 8,
    sources: {},
    layers: []
  },
  center: [12.550343, 55.665957],
  zoom: 8,
  validateStyle: false
});

map.addSource("invalid", { type: "invalid" });

map.setStyle({ ...map.getStyle() }, { validate: false });

```

### Expected Behavior
Style is not validated.

### Actual Behavior
Console error if the style is invalid. The bug appears to be in `style.ts` where the validation option is not checked: https://github.com/maplibre/maplibre-gl-js/blob/3bea9a10acf741caf0913eb3792ef0a268f6fbe3/src/style/style.ts#L662-L667

Would be happy to submit a PR with a fix :thumbsup:

**Comment by HarelM** [comment]
Feel free to submit a PR 😃
