### ISSUE TITLE
css bug: the .maplibregl-ctrl-attrib.maplibregl-compact text color is not set and vanishes in dark mode

### ISSUE THREAD

**Issue by Fil** [maplibre/maplibre-gl-js#3732]
I'm testing maplibre with a light mode/dark mode responsive environment, and see that the attribution pill shows as light fill on light background. The bug is coming from this definition, which only defines a background color but does not specify any **color**, which then defaults to the page-level color, which is light when in dark mode.

https://github.com/maplibre/maplibre-gl-js/blob/0aeb2c0f926fcb4f922791642f0e3ee8119043a2/src/css/maplibre-gl.css#L448

![maplibre-gl dark mode bug](https://github.com/maplibre/maplibre-gl-js/assets/7001/43de8911-d444-49d2-bde3-171438ae5860)

**maplibre-gl-js version**: 4.0.2

**browser**: chrome

I'm fixing it locally by adding this:

```html
<style>
  .maplibregl-ctrl-attrib.maplibregl-compact,
  .maplibregl-ctrl-attrib.maplibregl-compact a {
    background-color: #fff;
    color: #444;
  }
</style>
```

**Comment by HarelM** [comment]
Not sure I fully understand the issue, but feel free to open a PR to update the CSS to solve this.

**Comment by Fil** [comment]
To clarify, the issue is that this is setting a (white) background-color but leaves the text color unspecified — so it is whatever it is globally on the map's container. If that happens to be white (or very light), the text is unreadable.
