### ISSUE TITLE
queryRenderedFeatures ignores symbol draw order

### ISSUE THREAD

**Issue by drwestco** [maplibre/maplibre-gl-js#374]
**maplibre-gl-js version**: 1.14+

**browser**: Chrome

### Steps to Trigger Behavior

 1. Two overlapping symbols, using symbol-sort-key so first symbol draws on top of the second
 2. queryRenderedFeatures at a pixel location covered by both symbols
 3. Examine the order of the features returned

### Link to Demonstration

https://jsfiddle.net/drwestco/2z6mtgrk/5/

### Expected Behavior

Per the documentation (https://maplibre.org/maplibre-gl-js-docs/api/map/#map#queryrenderedfeatures):

> The topmost rendered feature appears first in the returned array, and subsequent features are sorted by descending z-order.

### Actual Behavior

Rendered z-order seems to be ignored. Features are returned in the reverse order they appear in the source, regardless of the values set by symbol-sort-key.

Red symbol (id: 163) is drawn on top of green symbol (id: 164):
![image](https://user-images.githubusercontent.com/743030/134236005-c57cdf13-ee93-4cdb-b816-227ae7ab160a.png)

But the IDs returned by queryRenderedFeatures has them reversed:
```
[164, 163, 153]
```

The order order of features returned by queryRenderedFeatures does not change if the zorder of the points in the source data is swapped. It looks like the returned order is strictly based on the order the features appear in the data source.

**Comment by drwestco** [comment]
query_features.ts, line 128. `featureSortOrder` is only populated in symbol_bucket.ts, if `sortFeaturesByY` is set `symbol-z-order === 'viewport-y'`. Otherwise, queryRenderedFeatures falls back to returning results in source order. Per the docs, it should return them in rendered order regardless of `symbol-z-order`?

```typescript
layerSymbols.sort((a, b) => {
    // Match topDownFeatureComparator from FeatureIndex, but using
    // most recent sorting of features from bucket.sortFeatures
    const featureSortOrder = queryData.featureSortOrder;
    if (featureSortOrder) {
        // queryRenderedSymbols documentation says we'll return features in
        // "top-to-bottom" rendering order (aka last-to-first).
        // Actually there can be multiple symbol instances per feature, so
        // we sort each feature based on the first matching symbol instance.
        const sortedA = featureSortOrder.indexOf(a.featureIndex);
        const sortedB = featureSortOrder.indexOf(b.featureIndex);
        assert(sortedA >= 0);
        assert(sortedB >= 0);
        return sortedB - sortedA;
    } else {
        // Bucket hasn't been re-sorted based on angle, so use the
        // reverse of the order the features appeared in the data.
        return b.featureIndex - a.featureIndex;
    }
});
```

**Comment by drwestco** [comment]
The order of symbols returned from queryRenderedFeatures only matches draw order is when symbol-z-order is set to 'viewport-y'. But in that mode, symbol-sort-key is ignored, so that z-order is not a valid workaround.

**Comment by drwestco** [comment]
Ouch. If the query region is large enough to span multiple tiles, the result order is even less sensible. It appears to be sorted in source order, but grouped by tile+layer (bucketInstanceId), so the result set is all chopped up.

**Comment by wipfli** [comment]
That's very interesting. I have seen strange z-ordering before too. Does it matter if one uses a style.json file or adds things dynamically?

**Comment by xabbu42** [comment]
I could also reproduce the issue with mapbox-gl-js 1.13.0 just to make sure it is not a regression from maplibre-gl-js commits. I'll look into writing a test for this.

@wipfli just to be sure we are on the same page, the issue here is not about the rendering where the z-order is correct (i.e. the red circle above the green circle) but about the return value of queryRenderedFeatures, where the red circle feature is the second result of three.

**Comment by wipfli** [comment]
Good, so if we fix this we can add a unit test. A render test will not be required.
