### ISSUE TITLE
Issue with types of Source given from map.getSource

### ISSUE THREAD

**Issue by FaXaq** [maplibre/maplibre-gl-js#3753]
I was following a tutorial [https://maplibre.org/maplibre-gl-js/docs/examples/cluster/](https://maplibre.org/maplibre-gl-js/docs/examples/cluster/). When calling `map.getSource` I get type errors to call methods beloging to a source type. To reproduce the bug you just have to create a new project and follow what is wrote on the tutorial.

**maplibre-gl-js version**:
4.0.2

### Steps to Trigger Behavior

 1. Retrieve a source with `map.getSource` within a typescript file where a map is created and loaded.
 2. Try to call `getClusterExpansionZoom` on the given back source.
 3. Get a typescript warning : `Property 'getClusterExpansionZoom' does not exist on type 'Source'.` Even with typing guards.

### Expected Behavior

We should be able to call it with a type test like :
```ts
    const features = map.queryRenderedFeatures(e.point, {
      layers: [clusterLayer.id],
    });
    const clusterId = features[0].properties.cluster_id;

    const source = await map.getSource("data");
    if ("getClusterExpansionZoom" in source) {
      const clusterZoom = source.getClusterExpansionZoom(clusterId);
      map.easeTo({
        center:
          "coordinates" in features[0].geometry
            ? (features[0].geometry.coordinates as [number, number])
            : [-1, -1],
        zoom: clusterZoom,
      });
    }
```

### Actual Behavior
![Screenshot 2024-02-26 at 17 43 35](https://github.com/maplibre/maplibre-gl-js/assets/5200291/f04ecc4e-3cf9-41ac-a5dc-b7696e1f2204)

The only way to get away is to type the source to any, or use `@ts-ignore`.

I walked through the repo and I here are two solutions, I've thought of : 
- Make `Source` types available for casting in user code.
- Correct the `Source` type to be a union of possible sources. Favoring user code to be the guard. I'll try to post a PR right after.

**Comment by HarelM** [comment]
The return type is a source interface, you need to cast it to the relevant source you are expecting. I don't see a good reason to complicate it...
