### ISSUE TITLE
map.cameraForBounds returns undefined which is not mentioned in type definition

### ISSUE THREAD

**Issue by yarkoyarok** [maplibre/maplibre-gl-js#3760]
**maplibre-gl-js version**: 2.4.0

**browser**: Chrome

### Steps to Trigger Behavior

We did not find exact way to reproduce error in runtime, we had only exception report from user.

### Link to Demonstration

Cannot be provided

### Expected Behavior

`map.cameraForBounds` to return values of type defined

### Actual Behavior

Sometimes we receive `undefined` from `cameraForBounds(bounds: LngLatBoundsLike, options?: CameraForBoundsOptions): CenterZoomBearing` but it not mentioned in type definition.

Here is actual return: 

https://github.com/maplibre/maplibre-gl-js/blob/0aeb2c0f926fcb4f922791642f0e3ee8119043a2/src/ui/camera.ts#L725-L728

**Comment by HarelM** [comment]
I'm not sure I fully understand the issue.
If this is a typing issue of the return value, feel free to open a PR to fix this.
Note that we usually don't patch old versions, so if you would like to fix it in 2.4 it's on you.
