### ISSUE TITLE
activateUIButton("myMode") and deactivate functionality

### ISSUE THREAD

**Issue by basaran** [maplibre/maplibre-gl-js#3788]
## User Story

I create my own custom mode as per documentation:

``` typescript
const mapboxDraw = new MapboxDraw({
        //...
	modes: {
		...MapboxDraw.modes,
		myMode: MyMode,
	},
        // PS. Object.assign gives me type error so I spread the existing modes.

``` 

Then in MyMode.ts

```typescript
MyMode.onSetup = function (opt) {
	this.activateUIButton("myMode");
        // doesn't work
}

MyMode.onStop = function (state) {
	this.activateUIButton();
        // deactivates stock Mode buttons (i.e Polygon)
        // but when stock Mode is active, does not deactivate myMode.
}
```

I was able to work the activation by creating a toggle function to add the ".active" class.
I was unable to work the second issue, if I click a stock Mode, it does not deactivate MyMode button.

## Rationale
Somewhat Inconsistent UX experience.

**Comment by basaran** [comment]
My futile attempt to override the constants also didn't yield to any results.

```
MapboxDraw.constants.types.MYMODE = "freehand";
MapboxDraw.constants.classes.CONTROL_BUTTON_MYMODE =
	"mapbox-gl-draw_mymode";
```

**Comment by HarelM** [comment]
Mapbox draw is not part of this repo...

**Comment by basaran** [comment]
I am sorry, I was moving too fast and it's a bit late :)
