### ISSUE TITLE
Line breaks with \n or \r not working properly for symbol layers with line or line-center placements

### ISSUE THREAD

**Issue by DanielForniessoria-TomTom** [maplibre/maplibre-gl-js#3814]
**maplibre-gl-js version**: 4+

**browser**: chrome (probably any)

### Steps to Trigger Behavior

 1. Create a GeoJSON source and symbol layer
 2. Show a piece of text with "text-field" containing a line break in it \n
 3. Start with "symbol-placement": "point", give it some coordinates
 4. The text should appear correctly in 2 lines
 5. Now change the source to a line string, draw a basic line
 6. Change the symbol placement to "line" or "line-center"
 7. BUG: the text now appears in one line
 8. GLITCH: if you zoom all the way out, wait a moment, and zoom back in, now the text might appear in 2 lines

### Expected Behavior

Symbol layers with "line" or "line-center" placement containing "text-field" values with line breaks should display such texts in multiple lines.

### Actual Behavior

Symbol layers with "line" or "line-center" placement containing "text-field" values with line breaks are displaying the text on a single line.

**Comment by HarelM** [comment]
JSbin/codepen link would be great to show the problem I believe.
Thanks for taking the time to open this issue!

**Comment by naogify** [comment]
Thank you for creating the issue. 
I can reproduce the error. Here is the sample code.

### symbol-placement: line
https://codepen.io/naogify/pen/XWwWYyz

### symbol-placement: point
https://codepen.io/naogify/pen/MWdWBYE
