### ISSUE TITLE
geolocate_control.ts  Some events are missing

### ISSUE THREAD

**Issue by mrajaei76** [maplibre/maplibre-gl-js#3846]
## User Story
I was creating a custom button for geolocation, utilizing the events thrown by the Geolocate class. I noticed that the Geolocate class has six states in _watchState, but it doesn't emit events for each of these states.

The states and their corresponding events are as follows:

WAITING_ACTIVE: trackuserlocationstart
ACTIVE_LOCK: geolocate
OFF: trackuserlocationend
BACKGROUND: trackuserlocationend
BACKGROUND_ERROR: error
ACTIVE_ERROR: error

However, I'm unable to distinguish when the Geolocator turns off or when the user drags the map, among other actions, due to the lack of specific events for each state.

## Rationale
This limitation prevents me from fully customizing the button and handling related events accurately.

## Impact
I can submit a pull request to address this issue if desired.

**Comment by HarelM** [comment]
A PR would be great. Thanks!
