### ISSUE TITLE
Example check-for-support is outdated

### ISSUE THREAD

**Issue by xabbu42** [maplibre/maplibre-gl-js#3857]
It seems like maplibre-gl-js 3.0.0 dropped support for old iphones with webgl, but the suggested test in the example check-for-support was not updated. This is a consequence of https://github.com/maplibre/maplibre-gl-js/pull/2157.

**maplibre-gl-js version**:

3.0.0 and later

**browser**:

Safari on IOS before 13.4

### Steps to Trigger Behavior

 1. Open https://maplibre.org/maplibre-gl-js/docs/examples/check-for-support/
 
### Expected Behavior

Either the alert that this browser does not support Maplibre GL or preferably a working map.

### Actual Behavior

No alert and also no map. Instead we get the error: Caught Exception:"ReferenceError: Can't find variable: ResizeObserver“

**Comment by neodescis** [comment]
That example merely checks if WebGL is supported on a browser. It is not really meant to check for runtime compatibility for other things.

In my opinion, the benefits of using a ResizeObserver over window.resize greatly outweigh supporting browsers from four years ago. However, we should be able to degrade gracefully in this instance by checking for support for ResizeObserver before using it. If it's not supported, then the map would not handle resize events.

**Comment by HarelM** [comment]
Feel free to open a PR with resizeObserver guard, I would also recommend adding a warnOnce just in case someone will want to read the console log.
Generally speaking, old versions supports old browsers, new versions support newer browsers.

**Comment by xabbu42** [comment]
Even with the guard i could not get an old iphone with ios 13 to work on browserstack. as far as I can see there would be no new hardware working because of the guard and it seems therefore unnecessary.

> That example merely checks if WebGL is supported on a browser. It is not really meant to check for runtime compatibility for other things.

The example has the title "Check if MapLibre GL JS is supported" which imho implies a different intend. Either the title should be changed to "Check if WebGL is supported" or the the check should be adapted.

I personally think the latter is much more useful. We for example have a fallback raster map which works on old hardware and need a check if MapLibre GL JS is supported. So I'd suggest to adapt the code of the example to do what is described in the title. I'm not sure what the best way to do that is, perhaps add a test for ResizeObserver Api?

**Comment by xabbu42** [comment]
As said above I was not really able to meaningful increase compatibility. So as I understand you we should just change the misleading title of the example and can then close this issue?

**Comment by HarelM** [comment]
Yup, sounds like the right direction.

**Comment by xabbu42** [comment]
Fixed by #3933.
