### ISSUE TITLE
Unwanted pan-jump as requested pan action finishes (3D terrain)

### ISSUE THREAD

**Issue by olsen232** [maplibre/maplibre-gl-js#3872]
This is not about inertia. Any panning that happens due to inertia is outside the scope of this bug -
so, this is not a duplicate of https://github.com/maplibre/maplibre-gl-js/issues/1303

I believe this is only happens when 3D terrain is enabled.

**maplibre-gl-js version**: v4.1.1

**browser**: Brave

### Steps to Trigger Behavior

Here is one way I've found of reliably triggering an unwanted pan.
(There may be others - this is a bug I've come across by using ML, and it seems to be better in some circumstances, worse in others, hard to say if this way of demonstrating it showcases the only relevant bug at its most extreme, or if there are other ways to trigger similar bugs or worse instances of this bug).

 1. Open `test/examples/3d-terrain.html`
 2. Zoom in the maximum amount (18).
 3. Drag the map around and let go.
 4. Observe that, on occasion, once the map has finished panning, it jumps back in the opposite direction, part way or all of the way back to where it started.

### Link to Demonstration

https://github.com/maplibre/maplibre-gl-js/assets/7425442/47a95225-1b5c-4815-b9e9-93a0049e2c09

### Expected Behavior
Pan should continue in the same direction until it drag stops / inertia runs out, then stop.

### Actual Behavior
Pan jumps back the way it came in a single-frame unwanted discontinuity.

**Comment by olsen232** [comment]
On another PR, @prozessor13 who I believe wrote some of this code, wrote the following: https://github.com/maplibre/maplibre-gl-js/pull/3836#issuecomment-1999838674

> Beside that fix i notice still some small jumps at mouse-moveend. Now, that recalcuteZoom is fixed, i am pretty sure that this issue is located [here](https://github.com/maplibre/maplibre-gl-js/blob/7308da584248c76e17f20f1f17df0b63acd34ade/src/render/terrain.ts#L329). This issue can either be fixed with:
>
> - calculate correct position with ray/triangle intersection from camera to terrain-mesh
> - or the pragmatic, still not perfect way: grab more than only pixel from the coords-framebuffer and make some sort of interpolation to get a more accurate position.

I've done some digging and I mostly agree with Max - this is an issue caused by `Terrain.pointCoordinate` returning bad values. However, I don't think it's due to poor accuracy that could be improved by a larger sample - I think the data in `coords` framebuffer is simply stale.

The following line of code
https://github.com/maplibre/maplibre-gl-js/blob/main/src/render/painter.ts#L386
checks if the `coords` framebuffer needs to be updated - the relevant condition is `!mat4.equals(this.terrainFacilitator.matrix, this.transform.projMatrix)` which will be true whenever projMatrix differs noticeably from what projMatrix was last time the `coords` frameBuffer was updated.
However, one possible source of the bug is in that phrase "differs noticeably" - `mat4.equals` returns true if the two matrices elements are "approximately equal" - https://glmatrix.net/docs/mat4.js.html#line1972
This condition lets the user change the pan the view some amount without the `coords` framebuffer updating, which would mean that, at the end of the pan, when `Terrain.pointCoordinate` is used to find the new center, it would return the same coordinate as was previously at the center of the screen, causing the map to recenter on that coordinate and snap back the way it came.

I don't know what the largest change you can make to the projection matrix is without it becoming noticeably different (in terms of the elements still being approximately equal) - so, I don't know for sure if this issue is the sole or worst cause of the all the pan-bounching I've ever seen. However, changing that line to `mat4.exactEquals` seems to at least fix it so the "steps to trigger behavior" that I gave above no longer cause an issue. I'll open a draft PR.

**Comment by olsen232** [comment]
Draft PR is opened at https://github.com/maplibre/maplibre-gl-js/pull/3873
@prozessor13 can you have a look at this, since you suggested looking into it, and try out the proposed fix

**Comment by HarelM** [comment]
I'm not sure this is fully solved.
I can easily reproduce this on my site (israelhiking.osm.org.il), but it doesn't reproduce on the examples so I need to reduce some "noise factors" before I can write something useful.
I can open a different if needed instead of reopening this one.
I'll follow up once I have more info. I'll deploy the latest version just to be on the safe side.
I've tested version 4.0, 4.1.0 and they seem to have the same issue, so it might not be the same root case.

**Comment by HarelM** [comment]
Ok, I found out the cause in my site for these jumps, I'll open a different issue.

**Comment by HarelM** [comment]
This is the relevant issue:
- #4125 

Let me know if you would like me to assign a bounty to it and if you would like to try and tackle it.
