### ISSUE TITLE
Benchmarks are broken: window.maplibreglBenchmarks is undefined

### ISSUE THREAD

**Issue by kubapelc** [maplibre/maplibre-gl-js#3894]
**maplibre-gl-js version**: v4.0.0-pre5, and any newer version up to current v4.1.1

**browser**: Firefox 115.9.1esr, Chrome 122.0.6261.131

### Steps to Trigger Behavior

 1. `npm run start-bench`
 2. Open any benchmark in the browser, such as http://localhost:9966/test/bench/versions/index.html#Layout

### Expected Behavior

An empty benchmark graph appears and the benchmark starts executing. No errors in console.

### Actual Behavior

Empty page with errors in the console.

On firefox:

```
TypeError: can't convert undefined to object
    runComparison http://localhost:9966/test/bench/versions/index.html#Layout:33
```

On Chrome:

```
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME

index.html:69 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at runComparison (index.html:33:50)
```

### Notes

I've tried to binary search for the commit that broke this, and the first commit with broken benchmarks is [15afd542](https://github.com/maplibre/maplibre-gl-js/commit/15afd542c12192a7de413b26b18d58d7c4f60506), which is a merge of https://github.com/maplibre/maplibre-gl-js/pull/3601

**Comment by HarelM** [comment]
Bummer, I should've ran the benchmarks to see that they still run after this commit.
Thanks for the update!
Let me know if you prefer to let me handle this or open a PR to solve this.

**Comment by kubapelc** [comment]
I prefer to let you handle it, I have no idea what might be causing this or how to fix it. I would try to binary search the commits of the PR to see what actually caused the benchmarks to break and look for clues there, but that branch doesn't seem to be around anymore.

**Comment by HarelM** [comment]
The changes there are minimal in terms of code, it's more about how maplibre is packed and exposed. Since the benchmark are also packing maplibre in a different way I can imagine why this broke, but I'll still need to find where to fix it.
It might take a few days though...
