### ISSUE TITLE
Type def of `Map` constructor option `localIdeographFontFamily` doesn't accept `false`

### ISSUE THREAD

**Issue by Kanahiro** [maplibre/maplibre-gl-js#3895]
**maplibre-gl-js version**: 4.1.1

https://maplibre.org/maplibre-gl-js/docs/examples/local-ideographs/
According to above document, if you need to use glyphs of CJK fonts from server, you have to set `false` to `localIdeographFontFamily`.
However, current typedef of this options doesn't accept `boolean` (only `string`).
https://github.com/maplibre/maplibre-gl-js/blob/f6035db6670de1af2d294e3cb5f6702f8616b53f/src/ui/map.ts#L295

It may be easy to modify typedef to `string | boolean` but the case that `localIdeographFontFamily` is true couldn't occurs so it doesn't look good approach..

related https://github.com/maplibre/maputnik/pull/893

**Comment by HarelM** [comment]
I believe you could define the type as `string | false`, would that work?

**Comment by Kanahiro** [comment]
https://github.com/maplibre/maplibre-gl-js/blob/f6035db6670de1af2d294e3cb5f6702f8616b53f/src/render/glyph_manager.ts#L35

This constructor only treat `localIdeographFontFamily` as `string | null` and this is not correspond to type of the class variable. Other `localIdeographFontFamily` seems to be `string?`.

current behavior of `localIdeographFontFamily` is: 
1.  `undefined`: CJK fonts not loaded local or server.
2. `string`: load local fonts name defined as string.
3. `false`: load CJK fonts from server.

if this has misunderstanding, plz point it :)

**Comment by HarelM** [comment]
Probably because of this line:
https://github.com/maplibre/maplibre-gl-js/blob/f6035db6670de1af2d294e3cb5f6702f8616b53f/src/render/glyph_manager.ts#L124
I'm not against changing the code parts to align with the new definition.
