### ISSUE TITLE
Enable CI on Windows hosts

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre-gl-js#39]
Following up to #4, need to set up automated Windows testing.  CC: @msbarry

**Comment by msbarry** [comment]
Looking at the existing config from .circleci/config.yml I see these steps that I don't think would be too hard to convert to github actions:
- lint (lint, lint-docs, lint-css)
- build (build-prod, build-prod-min, ... test-build)
- check-size
- collect-stats (node bench/gl-stats.js)
- test-flow
- test-unit
- test-render (yarn run test-render then upload artifacts)
- test-query (yarn test-query then upload artifacts)
- test-browser (depends on selenium and a headless browser being present)
- test-expressions

Do you think we should try to get all of them running on windows, mac, and ubuntu? Or try to have ubuntu do all of those, and  mac/windows do a subset (ie. just lint, build, and tests)?  Concretely I was running into trouble with flow on windows and found that flow isn't fully supported on windows so it might not be feasible to support the whole pipeline on windows.
