### ISSUE TITLE
Layer `type` change causing a full map reload

### ISSUE THREAD

**Issue by slaviczavik** [maplibre/maplibre-gl-js#3954]
**maplibre-gl-js version**: 4.1.2

**browser**: Chrome 123.0.6312.105

### Steps to Trigger Behavior
> Easiest way to trigger the behavior is to run the example (link below) and switch style with buttons above map.

 1. Init MapLibre with an initial style.
 2. Updates the map's style via the `map.setStyle` method with an alternative style.

### Link to Demonstration
[JS Bin with simplest example](https://jsbin.com/bicuqahafi/edit?html,output).

### Expected Behavior
Changing one layer type for example from `fill` to `line` should not trigger full map reload.

### Actual Behavior
Map is fully reloaded even if there is a small visual change.

**Comment by HarelM** [comment]
You need to call `setStyle(newStyle, {diff: true})`.

**Comment by slaviczavik** [comment]
> You need to call `setStyle(newStyle, {diff: true})`.

Even with `diff` attribute it has same result.

**Comment by sbachinin** [comment]
@HarelM
I looked into this and it occurs to be an intended behaviour.
When layer's type is changed, its source is cleared, that is, all tiles for this source are removed.
It was done so to avoid certain bugs.
It is explained in this [comment](https://github.com/maplibre/maplibre-gl-js/blob/bec0505d94c86f7bbbfc0fceda261b534528c5a0/src/style/style.ts#L938).
So it actually triggers not a full reload but a reload of a particular source.

**Comment by HarelM** [comment]
Thanks for looking into it @sbachinin!
This is basically a limitation of current implementation. I don't think we have any plans to change that.

**Comment by slaviczavik** [comment]
Thank you for the clarification!
