### ISSUE TITLE
Id missing on MapGeoJsonFeature on map.on('click', layerid, event)

### ISSUE THREAD

**Issue by dennemark** [maplibre/maplibre-gl-js#3970]
Without the id it is not possible to relate back to the original feature within a geojson.

**maplibre-gl-js version**: latest / 4.1.2

**browser**: Chrome

### Steps to Trigger Behavior

1. Use GeoJson with features like 
```
{
      "id": "myid",
      "type": "Feature",
      "properties": {
        "prop2": 2
      },
      "geometry": {
        "coordinates": [
          [......],
        "type": "Polygon"
      }
    }
```
2. call 
```
map.on('click', 'layerid', (e)=>{
 console.log(e.features[0]) // id is undefined
})
```
click on feature and see console.log.

### Link to Demonstration
Click on red square
https://jsbin.com/rigukusabu/edit?html,output

### Expected Behavior

`id: 'myid'` 

### Actual Behavior
`id: undefined`

**Comment by HarelM** [comment]
I believe only numbers are supported as ids due to mvt limitation.
I believe this is a duplicate of: 
- #1043

**Comment by dennemark** [comment]
Wow this explains a lot! Thanks for the solution!!! Going to close this.
