### ISSUE TITLE
Set up CI / unit testing

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre-gl-js#4]
Make all commits automatically go through (github actions?) tests.

**Comment by jdesboeufs** [comment]
+1 for GitHub Actions

**Comment by jdesboeufs** [comment]
Unit tests run on Node.js 10 only.
Test suite (integration) is too slow for GitHub Actions.
Do we add some build steps to the default workflow? Maybe `build-css` and `build-prod-min`?

**Comment by nyurik** [comment]
First thing is to establish the same build/test pipeline as in mapbox-gl, and later we could change it in some way

**Comment by snickell** [comment]
FYI, as of https://github.com/maplibre/maplibre-gl-js/pull/17 being merged, I believe that a CI could execute tests (unit, integration, smoke, etc) by running:

```
./build/prepare-release.sh "yarn test"`
```

**Comment by nyurik** [comment]
It seems github actions will not work because the VMs do not have GPUs, so we will need to set up [self hosted runner](https://docs.github.com/en/free-pro-team@latest/actions/hosting-your-own-runners/about-self-hosted-runners) with GPU support. Hopefully it can be done with either Azure or Google Cloud.
