### ISSUE TITLE
Fork of mapbox/mapbox-gl-js not mapbox/mapbox-gl 

### ISSUE THREAD

**Issue by mloskot** [maplibre/maplibre-gl-js#40]
I'd suggest a tiny change to the description of the repository, from

```
- MapLibre GL is a free and open-source fork of @mapbox/mapbox-gl 
+ MapLibre GL is a free and open-source fork of @mapbox/mapbox-gl-js
```

The https://github.com/mapbox/mapbox-gl name is deprecated

![image](https://user-images.githubusercontent.com/80741/102274028-86a07500-3f23-11eb-85fb-b7908019a5ef.png)

**Comment by kylebarron** [comment]
The [repository name](https://github.com/mapbox/mapbox-gl-js) is `mapbox-gl-js`. The [NPM name](https://www.npmjs.com/package/mapbox-gl) is `mapbox-gl`.

**Comment by stevage** [comment]
Which means the "@mapbox/mapbox-*" wording is ambiguous and should be avoided. 

+ MapLibre GL is a free and open-source fork of Mapbox GL JS.

**Comment by mloskot** [comment]
I meant  the description in here
![image](https://user-images.githubusercontent.com/80741/102319860-cbf09100-3f7b-11eb-9e81-83b9145dc821.png)

The "MapLibre GL" without further qualification is ambiguous as it may suggest MapLibre project forks the complete "Mapbox GL" ecosystem, which (does not seem to be the case](https://lists.osgeo.org/pipermail/discuss/2020-December/039172.html).

**Comment by marcelnormann** [comment]
Done. No code changes needed.
