### ISSUE TITLE
Ability to modify the map background

### ISSUE THREAD

**Issue by chrisgervang** [maplibre/maplibre-gl-js#4036]
## User Story

As a designer, I can set the clearColor to something other than transparent so that the horizon color in exported images isn't "black" or "transparent" when camera pitch is set to high values.

## Rationale

This is very useful for a basic sky implementation. While there is a sky spec coming along, a solid color sky is a considerably simpler and desirable solution for minimalistic map styles.

Our workaround today is to patch the maplibre node module with a reassigned clear color. There is no top level map parameter to modify WebGL parameters.

While setting the DOM background color works when compositing in-browser, it is insufficient when compositing the canvas to an image.

Of note, I'm a deck.gl user that uses the `@deck.gl/mapbox` submodule to perform interleaved rendering. Deck.gl provides a parameters property to override WebGL parameters, however Maplibre is overriding my settings. 

I see at least two possible solutions, either a new map option to set the background color (ideal), or an option to disable maplibre's behavior of setting clearColor.

## Impact

The impact of doing nothing is the image exports will look different than what the end user sees in the browser.

**Comment by HarelM** [comment]
I believe there's a sky branch already which you can use as a intermediate workaround. 
There's no point in adding a option which will be redundant. 
Another option is to use afork or patch-paxkage to solve your issue until things land here. 
Also you can help out push the sky spec and implementation forward, as there's no real stopper besides people who actually needs this.

**Comment by chrisgervang** [comment]
Thank you! I see #3645 has shipped, so I'll use that. Yay!
