### ISSUE TITLE
Is it time to move to ES2017 and how

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#4045]
## User Story

MapLibre currently compiles to ES2016 version, and maybe should upgrade to ES2017; the most important benefit would be the native support of async/await.

99% of browsers should have ES2017 support, see more: https://caniuse.com/?search=ES2017

When it comes to how, there could be two options, and both are pretty straight forward.
1) Modify tsconfig and be done. One line change.
2) A new tsconfig can be added, and with minor build script tweaking, both es2016 and es2017 or any newer version can be built at same time so app developers can choose whichever they want to use in their app. This maintains maximum backward compatibility and more friendly for the community in general.

## Rationale
 - Much more pleasant debugging experience when source map is unavailable in various hosting apps, because async/await statements will not be converted to TS helpers, which are quite verbose and confusing.
 - Smaller script (~3kb reduction), negligible for end consumers but every bit counts.  :)

**Comment by HarelM** [comment]
Check out the following discussion: 
https://github.com/maplibre/maplibre-gl-js/discussions/3210
The end result of it was to downgrade to es2016.
I think the way forward would be to use esm build with modern es20xx keep that running in parallel for a few versions and then drop the support for old style commonjs.
IDK...

**Comment by HarelM** [comment]
It's also worth noting that it seems angular did make an effort to fix the issue, but I don't think it will be available soon enough: 
https://github.com/angular/angular-cli/issues/22191#issuecomment-2068217280

**Comment by birkskyum** [comment]
When Angular developers have a path forward supporting async/await, then we can move too - can't really do it before. I don't know if that is Angular 18, and if it's trivial enough for angular devs to migrate to angular 18 for us to say "just upgrade and it'll work again".

**Comment by wmertens** [comment]
having the

**Comment by zhangyiatmicrosoft** [comment]
Closing it for now. Does not look like it is happening for the next several months.
