### ISSUE TITLE
Extrusion line geometry 

### ISSUE THREAD

**Issue by exotfboy** [maplibre/maplibre-gl-js#4073]
Hi, I found [Mappedin](https://www.mappedin.com/) became a sponsor from maplibre [news](https://maplibre.org/news/2024-03-26-mappedin-announcement/). Then I took a look at their official site. I have to say Mappedin create a amazing SAAS platform for indoor mapping.

And I found their map SDK can render the wall with height just like a polygon.

![wall_height](https://github.com/maplibre/maplibre-gl-js/assets/16457917/3e981533-b1a0-4bf9-b214-e2e9129a2f4d "")

And I am sure the wall is represented as linesting instead of polygon, I wonder if maplibre can support that?

**Comment by HarelM** [comment]
I'm pretty sure this is maplibre.
You can create buildings that are thin to show as walls. 
You can define the minimal height to have them float in the air.
See the comment here: 
- https://github.com/maplibre/maplibre-gl-js/issues/644#issuecomment-1820531569

**Comment by HarelM** [comment]
Can you clarify what the issue here is? 
Is it an enhancement request? Should I convert it into a discussion?

**Comment by exotfboy** [comment]
From [documents ](https://developer.mappedin.com/web/v6/mvf/data-model/#obstruction)of  Mappedin, the wall and door is kind of linestring.  

As you said we can make a buffer to the line at runtime and render them as extruded polygons.  I am just curious about if support extruding line out of box if possible. Have not idea how mappedin make that.

**Comment by HarelM** [comment]
Current implementation can't do that out of the box, you'll need to either write a custom layer or something different to pre-precess the tiles to create fill extrusions.
