### ISSUE TITLE
Add `getData` method for GeoJSON sources.

### ISSUE THREAD

**Issue by smellyshovel** [maplibre/maplibre-gl-js#4080]
## User Story

I suggest adding a `getData` method to `GeoJSON` sources as a unified way of accessing all the source's features regardless of their visibility.

## Rationale

There are currently 4 (?) known ways to that kind of thing:

1. `queryRenderedFeatures` - it allows to query the features of a source, but only those in the viewport.
2. `querySourceFeatures`  - as it turned out, the name is a bit misleading. If the target feature's not in the viewport, it won't locate it (just like with `queryRenderedFeatures`). It also can provide duplicates of real data, which leads to mandatory client-side filtering thus decreasing the performance.
3. Use `map.getSource(sourceId)._data`. This `_data` property seems to be holding all the features of a given source. The issue's that it's not a part of the public API, so it's a bad thing to rely on it. Secondly, it won't reflect the changes to the source made with the `updateData` method.
4. Use a separate features pool. Basically, write functions like `addFeatures`, `removeFeatures` and so on where it'd be required not only to call the `source.updateData` , but also to write into some kind of a local pool of features. That way, all the saved features will then be available to search through them.

It's been advised to use option number 4 as our current way-to-go. However, I consider it to be not a very nice one for the following reasons:

1. Retreiving data is a pretty common operation. Making all the users have their own omplementation of such a common thing is not a good idea, as it's something that could be done on the level of the library.
2. Holding such a features pool increases the complexity of data manipulation: it's like re-inventing the `updateData` method but the one which writes to a different location.
3. All the source data exists all the time and the map knows about it. There should be no need to store a separate copy of that data.

Another reason I think why it might be a good idea to have such an API is that there are already methods like `setData` and `updateData`, which logically leads to also having a read-only counterpart `getData`. And at the moment it's not there.

## Impact

If we don't provide this method, nothing special would happen. It's just a metter of convenience.
On the other hand, having such a functionality might help to decrease some unnecessary performance overhead for the users of MapLibre.

**Comment by smellyshovel** [comment]
> The only issue I can think of is the requirement to move the update process into the tile generation in the worker.

Sounds to me like a separate task.

> Currently the data is duplicated: one copy in the worker is in the tiles and the other copy in an in-memory variable.

I guess it's the `_data` field I talk about in the OP. And yes, there's a line which updates it in `setData`, but there's no such line in `updateData`, which is expected since in the case with `updateData` the `diff` is sent to the worker, not the real "parsed" data. So it seems to me that 
1. this `_data` field is redundant (I don't really see any usages of it in the main thread code)
2. even if it's not redundant, it's not updated in `updateData`, so the code shouldn't rely on it anyway.

Given all that, there currently *is* a single source of truth: data inside the worker.

> To be on the safe side I would recommend getting the data from the worker so that we consider the worker data as the source of truth

Exactly. I think there's no other option anyway.

The question, however, is **how**. Trying to dive deeper into the source code, but I'm getting confused with between-threads communication.

I can see that the main thread sends requests to the worker thread using the `sendAsync` method of `actor`. But how should I send the data back? Should it also be the same (or a similar one) call? Or maybe there's some events-based mechanism?

Namely, what I'm talking about, is the following:

here's the `_updateWorkerData` method (which is called from either `setData` and `updateData`): https://github.com/maplibre/maplibre-gl-js/blob/3d0f0db03ea8726258bafd14c7a7829f9306d276/src/source/geojson_source.ts#L315

then it calls (https://github.com/maplibre/maplibre-gl-js/blob/3d0f0db03ea8726258bafd14c7a7829f9306d276/src/source/geojson_source.ts#L328) `this.actor.sendAsync` to send some data to the worker thread.

My question is, whether there's an example somewhere of a vice-versa process? Where a worker needs to send data back to the main thread?

---

Another thing. There are events like `sourcedata` which happen after the source data gets updated. Should I do anything about them? Like listening to that event to be fired before responding to the main thread with GeoJSON?

And is it OK for the `getData` method to be async? As I understnand, it must be, since there is communication in-between threads going on. It's also the case with `setData` and `updateData`, but those are not async because 1) interaction is events-based and 2) it doesn't really matter *when* the data gets set/updated, as we don't really want to do anything with it.

**Comment by HarelM** [comment]
Looking at the PR I'm guessing that you figured out the answer to your questions, if there's anything that still needs my help let me know. We can continue the discussion in the PR or here, which ever works better for you. 
I rewrote the entire actor communication layer, so it should be fairly easy to use it to send a message and get the response back with data.

**Comment by HarelM** [comment]
Another question that came to my mind is what happens if the data is big? So the worker message have a size limit? Is paging needed in that case?

**Comment by smellyshovel** [comment]
> Another question that came to my mind is what happens if the data is big? So the worker message have a size limit? Is paging needed in that case?

That's a good question. Didn't think of it as I didn't even know there are limitations regarding the message size. I'll try to check what happens in such cases. Thanks for pointing that out.
