### ISSUE TITLE
Map.flyTo padding not being cleared -> fitBounds is summing it up with it's own padding argument

### ISSUE THREAD

**Issue by rczobor** [maplibre/maplibre-gl-js#4095]
It seems that when Map.flyTo is being called with padding. The global padding is not cleared and if fitBounds is called with a padding then it will sum it together with the uncleared global padding.

Similar issue has been reported in mapbox-gl-js: https://github.com/mapbox/mapbox-gl-js/issues/11831

**maplibre-gl-js version**: 4.2.0

**browser**: Chrome Version 124.0.6367.119 (Official Build) (arm64)

### Steps to Trigger Behavior

 1. Click fitBounds button - Fits view to given bounds with given padding.
 2. Click flyTo button - Flies to given coordinates with given padding, zoom, etc..
 3. Click fitBounds button again

### Link to Demonstration

https://jsbin.com/zuhohet/edit?html,console,output

### Expected Behavior
Fits view to given bounds with given padding. Same as it step 1.

### Actual Behavior
Throws "Map cannot fit within canvas with the given bounds, padding, and/or offset." warning or (depending on view width) fits view to given bounds with given padding PLUS the padding from the previous flyTo action.

### Workaround
Call `setPadding({ top: 0, right: 0, bottom: 0, left: 0 })` before calling `fitBounds`.

**Comment by HarelM** [comment]
I believe this was discussed here:
- #2984

Let me know if other information is needed.
