### ISSUE TITLE
Automate changelog updates

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#412]
## Motivation

Instead of asking everyone to update the changelog in every PR we might consider using the following Github action:
https://github.com/marketplace/actions/generate-changelog
I'm using it in another project I'm maintaining and I think it does a decent job.
this should be relatively easy to implement and can be seen here to as an example:
https://github.com/HaylLtd/cordova-background-geolocation-plugin/blob/stable/.github/workflows/changelog-generator.yaml

@msbarry @wipfli I know you guys like this stuff, feel free to integrate it :-)

If this is implemented, we should update the bug/feature template to remove this section.

**Comment by wipfli** [comment]
I do indeed like this stuff. What about https://github.com/github-changelog-generator/github-changelog-generator ?

**Comment by HarelM** [comment]
LGTM
