### ISSUE TITLE
Add autoprefixer postcss Plugin

### ISSUE THREAD

**Issue by coliff** [maplibre/maplibre-gl-js#4157]
## User Story

I noticed in the maplibre-gl.css that some css selectors had vendor prefixes but others didn't. I also see some vendor prefixed properties which are likely no longer needed. 

## Rationale

I think it'd be better to remove the vendor prefixes (e.g. `-moz-user-select: none; -webkit-user-select: none; -ms-user-select: none;`) and instead use the [autoprefixer](https://github.com/postcss/autoprefixer )PostCSS plugin to handle them all.

## Impact

Some css rules are missing vendor prefixes and some are needlessly included. For example ` -ms-user-select: none;` isn't needed anymore... but `cursor: -webkit-grab;` may need to be added to support older Safari browsers.

**Comment by HarelM** [comment]
Sounds good. Can this run as part of the linting process?

**Comment by coliff** [comment]
It's run as part of the build process - it's all automatic. It's really popular and used by most front-end frameworks and as you already use PostCSS adding it should be pretty easy.
