### ISSUE TITLE
White flickering of the map when resizing the window

### ISSUE THREAD

**Issue by Kurioni** [maplibre/maplibre-gl-js#4158]
Hi all!
Recently I encountered a problem when using a library in a project. When I changed the size of the window (respectively, if the size of the `<canvas>` changed), I noticed that the map began to flicker white. I started researching this problem, I noticed that this problem has existed for a long time, but it turns out it still exists. I opened the examples on your site and noticed that this problem was also reproduced there.

[screencast-maplibre.org-2024.05.webm](https://github.com/maplibre/maplibre-gl-js/assets/113048205/a638c863-805e-450b-90bb-a24d2ef41a76)

**maplibre-gl-js version**: 4.3.2

**browser**: Chrome 124.0.6367.210

### Steps to Trigger Behavior

 1. Open any example on the site, for example: https://maplibre.org/maplibre-gl-js/docs/examples/fullscreen/
 2. Slowly resize window

### Expected Behavior
When resizing the window, the map should not flicker.

**Comment by HarelM** [comment]
Yup, this has been a pain point from the dawn of history.
In most cases, window resizes are sparse, so the flickering is minimal.
Feel free to dive into it!
