### ISSUE TITLE
Maplibre >=4.2.0: can't use "within" filter in "all" filter anymore: ["all", ["within", ...], ...]

### ISSUE THREAD

**Issue by azarz** [maplibre/maplibre-gl-js#4212]
Hi, thank you for the amazing work on Maplibre GL JS! Without it, we could not have made anything close to what we made. I am running into an issue while trying to upgrade from 3.6.2 to 4.3.2

**maplibre-gl-js version**: 4.3.2

**browser**: Chromium

### Steps to Trigger Behavior (4.3.2)

 1. Create a filter with a "within" filter in a "all" filter
 2. Try to apply it to the map
 3. This appears in the console:
 ```
Error: layers.layerId.filter[2][1][0]: expected one of [==, !=, >, >=, <, <=, in, !in, all, any, none, has, !has], "within" found
```

### Link to Demonstration

Filter working (maplibre gl js 3.6.2) : https://jsbin.com/dozeqofofa/1/edit?html,css,js,output
Filter not working (maplibre gl js 4.3.2) : https://jsbin.com/wuzowelebo/1/edit?html,css,js,output

### Expected Behavior (3.6.2)
 1. Create a filter with a "within" filter in a "all" filter
 2. Try to apply it to the map
 3. The filter works and ther is no errors in the console.

**Comment by HarelM** [comment]
Can you try and find the last version this worked? 
I think it has to do with a change I made in the spec when I added the distance expression support.
Generally speaking, this error indicates you are mixing "old" and "new" expression syntax.

**Comment by HarelM** [comment]
Use ["!", [in, ...]] Instead of !in also.

**Comment by azarz** [comment]
Thanks a lot for the quick response!

When I try converting `"!in"` into `"!", ["in ...` in my style json, I get the following error :
```
layers.POI OSM isochrone$$$OSM.POI$GEOPORTAIL:GPP:TMS.filter[1][0]: expected one of [==, !=, >, >=, <, <=, in, !in, all, any, none, has, !has], "!" found
```
I will try to convert everything to "new" expression syntax, and let you know which specific version causes the issue next week!

**Comment by azarz** [comment]
I've tested the issue with several versions, and it seems that it appeared between 4.1.3 and 4.2.0.

Working example : (4.1.3) https://jsbin.com/fisuyubuna/edit?html,css,js,output
Not working example : (4.2.0) https://jsbin.com/nebucuvaqu/edit?html,css,js,output

**Comment by HarelM** [comment]
I think it's the distance support and the changes I made here: 
https://github.com/maplibre/maplibre-style-spec/pull/642

If you turn style validation off, does it work with latest version?

**Comment by azarz** [comment]
I added
```js
  validateStyle: false
```
in the map options, and it does not seem to change anything: https://jsbin.com/qikecefawi/edit?html,css,js,output

**Comment by HarelM** [comment]
I don't think there's an easy way to check that the syntax is ok besides using the validation function, which doesn't help much.
I would consider "complicating" the expression step by step and see when it starts to fail.
I'll see if I can improve the deprecated docs in the style spec to help understand how to properly migrate an old expression to new.

**Comment by azarz** [comment]
I managed to convert all my filter to "new" syntax, I needed more ["get", "..."] and ["literal",["...",

Thanks a lot for the help!!

**Comment by HarelM** [comment]
@azarz can you help me update the following doc to better explain how to migrate from old syntax to new syntax:
https://github.com/maplibre/maplibre-style-spec/blob/main/docs/deprecations.md
