### ISSUE TITLE
Marker hovers above Globe when moving the map

### ISSUE THREAD

**Issue by KookaburraShell** [maplibre/maplibre-gl-js#4216]
**maplibre-gl-js version**: globe branch latest

**browser**: chromium and firefox

### Steps to Trigger Behavior

Add marker to any location on the map

### Link to Demonstration

https://github.com/maplibre/maplibre-gl-js/assets/71338293/2a0f757f-ad19-4e50-a717-f1901d728ce4

### Expected Behavior
Marker stays on globe when moving the map
### Actual Behavior
Marker floats on globe when moving

I want to thank everyone that is working on the globe projection, maplibre is great!

**Comment by HarelM** [comment]
Please comment on the relevant PR, this party if the code in not in main and was not implemented yet. 
You are welcome to help.
Closing...
