### ISSUE TITLE
Filter based on zoom level gives wrong results

### ISSUE THREAD

**Issue by dbrnz** [maplibre/maplibre-gl-js#4249]
**maplibre-gl-js version**: 4.3.2

**browser**: Chrome, Firefox

### Steps to Trigger Behavior

Zoom in and out of the demonstration map, in particular with a zoom range between 3 and 5.

### Link to Demonstration

A gist is [here](https://gist.github.com/dbrnz/86465af324f521eec177fe6f80b2ba61) -- I can't seem to get jsbin to play...

### Expected Behavior

A single, central marker should be shown with a zoom level less than 4, with this marker disappearing and three other markers appearing when zoomed above level 4.

### Actual Behaviour

Only two markers show between zoom 4 and about zoom 4.82, instead of the expected three.

Zoom level 3.89:

<img width="331" alt="Screenshot 2024-06-09 at 7 58 53 PM" src="https://github.com/maplibre/maplibre-gl-js/assets/239220/7ac79a64-bcd0-4d3b-9225-b7d5dafcc432">

Zoom level: 4.66:

<img width="440" alt="Screenshot 2024-06-09 at 7 59 09 PM" src="https://github.com/maplibre/maplibre-gl-js/assets/239220/d9924a4d-7a96-4da0-b9ee-79b3c7e7e5e9">

Zoom level 4.93:

<img width="461" alt="Screenshot 2024-06-09 at 7 59 18 PM" src="https://github.com/maplibre/maplibre-gl-js/assets/239220/22f0dc4d-652d-4e81-817a-6a2ac63bae2c">

**Comment by dbrnz** [comment]
I suspect that #4217 could be related.

**Comment by HarelM** [comment]
Are you sure this is not related to symbol collision?

**Comment by dbrnz** [comment]
My apologies, you are absolutely right!!

**Comment by wipfli** [comment]
To see collisions by the way you can do something like:
```js
const map = maplibregl.Map({...});
map.showCollisionBoxes = true;
```
