### ISSUE TITLE
Add an `.editorconfig` config

### ISSUE THREAD

**Issue by coliff** [maplibre/maplibre-gl-js#4253]
[EditorConfig](https://editorconfig.org/) is very popular and very helpful in helping maintain consistent code formatting. I think it'd be a good idea to add an `.editorconfig` file to the projects root. I suggest somethng like this:

```yml
# https://editorconfig.org
root = true

[*]
charset = utf-8
end_of_line = lf
indent_size = 4
indent_style = space
insert_final_newline = true
trim_trailing_whitespace = true
```

EditorConfig is one of the most [downloaded VS Code extensions](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig) so if this config was present then it will ensure that there aren't unnecessary trailing whitespaces and files are saved with the correct line endings etc. It could be added to the recommended extensions file too in `.vscode/extensions.json`.

**Comment by HarelM** [comment]
I believe we have lint for that.
I don't think (hope) another tool is needed...?

**Comment by coliff** [comment]
There isn't a lint in the repo for this, and no configuration for it either. I noticed many instances of inconsistent trailing spaces and some files having final newlines and others without. Including this config will help keep things consistent. GitHub Web UI even has built in support for it!
