### ISSUE TITLE
Suggest installing newer version of maplibre-gl

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#4273]
in the [docs](https://maplibre.org/maplibre-gl-js/docs/), there is a guide to pin the maplibre version installed, and it's suggesting a very old version. In case anyone just copies it over it would be nice to have at least the latest major there. 

<img width="705" alt="Screenshot 2024-06-15 at 01 17 25" src="https://github.com/maplibre/maplibre-gl-js/assets/74932975/dd44648d-9267-428c-a546-5727b61ac0d6">

**Comment by HarelM** [comment]
There's is a "latest" line. 
We can simply remove the other line as I don't think we should really explain how unpkg works, they have their own docs...
