### ISSUE TITLE
Docs: Images are not lazy loaded on Examples page

### ISSUE THREAD

**Issue by coliff** [maplibre/maplibre-gl-js#4274]
**browser**: Edge v126 on mac0S

### Steps to Trigger Behavior

 1. https://maplibre.org/maplibre-gl-js/docs/examples/
 2. Observe the `{ loading=lazy }` below each image
 3.

the `{ loading=lazy }` should be included in the markdown like this:
https://squidfunk.github.io/mkdocs-material/reference/images/?h=lazy#image-lazy-loading

**Comment by HarelM** [comment]
Wasn't this addressed as part of: 
- #4247?

**Comment by coliff** [comment]
unfortunately not addressed yet. `{ loading=lazy }` is appearing on the actual live production site.

I'm unfortunately still unable to get Docker running so can't test this locally.

**Comment by HarelM** [comment]
What errors do you get?
You might need to comment out the social part of the mkdocs config to get the docker working, at least this is what I do on my mac...

Please try and address this ASAP, and if you can't, please open a PR to revert this change, we can't have the docs site like this.

**Comment by HarelM** [comment]
If I read the docs correctly, the following plugin is needed:
https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists

Adding it seems to remove the `{ loading = lazy }`, but I don't know if it is configured correction, as I see `loading=loading` in the html...

**Comment by HarelM** [comment]
I've opened the following PR:
- #4278

But I'm not 100% sure it is working as expected...
