### ISSUE TITLE
Allow adding multiple layers to map.on() event handler

### ISSUE THREAD

**Issue by AgentSmith0** [maplibre/maplibre-gl-js#4279]
## User Story

It is currently not possible to directly create an event handler for multiple layers. (https://maplibre.org/maplibre-gl-js/docs/API/classes/Map/#on)

## Rationale

It would be more convient to directly pass a layer list instead of having to create the same event handler again for every layer in a list.
Mapbox GL JS has this feature already implemented: https://github.com/mapbox/mapbox-gl-js/pull/11114

## Impact

You would have to create a new event handler for every layer in your list e.g. through a for loop.

**Comment by HarelM** [comment]
Feel free to pursue this. 
Please make sure not to infringe mapbox copyright by copying their code.

**Comment by birkskyum** [comment]
Closed by #4570
