### ISSUE TITLE
Clustering customization

### ISSUE THREAD

**Issue by MichalNemec** [maplibre/maplibre-gl-js#429]
## Motivation

Make clustering more customizable for end user.

## Design

Based on this plugin for leaflet, functionality wise:
https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html

### Implementation
Based on this plugin for leaflet:
https://leaflet.github.io/Leaflet.markercluster/example/marker-clustering-realworld.388.html
could be done the clustering coverage (on/off/hover/click) + more options for developers to tweak clusters.

**Comment by HarelM** [comment]
I'm using ngx-maplibre which uses supercluster under the hood, I think supercluster is a good way to add this capabilities without adding it to this repo. Am I missing anything?

**Comment by MichalNemec** [comment]
I didnt even think of the supercluster, that would be nice to add it there. Because as i checked last time, the coverage i just didnt find.

**Comment by MichalNemec** [comment]
Its not going to be implemented. So there is that :) closing the issue
