### ISSUE TITLE
Documentation: Broken Link: maplibre-native

### ISSUE THREAD

**Issue by jlpoolen** [maplibre/maplibre-gl-js#4305]
Broken link:  https://maplibre.org/maplibre-gl-js/docs/

First paragraph under the first section titled "Introduction"

> ... with a pendant for Mobile, Desktop, Servers called MapLibre Native.

	
"Maplibre Native" links to https://maplibre.org/projects/maplibre-native/

Following the link results in:

```
404
404

Page not found :(

The requested page could not be found.

```

**Comment by HarelM** [comment]
Right, thanks for letting us know! Feel free to open a PR to fix that.

**Comment by jlpoolen** [comment]
I'm guessing this is the document that the link should be pointing to?  https://maplibre.org/maplibre-native/docs/book/introduction.html
Unfortunately, I have not been able to create pull requests in Git Hub despite my ill-fated effort to do so in another project, I'm just git-hubchallenged, I guess.  Though, the link I'm providing here may be to an older style document?  At least this is known problem now.

**Comment by HarelM** [comment]
You should be able to use the pencil straight from the github UI to edit the relevant file.
But I'm not sure either what's the link to the native docs as there are a few in the landing page of maplibre.org...
CC: @louwers

**Comment by louwers** [comment]
Thanks for reporting. I can make a PR.
