### ISSUE TITLE
Filter for BaseHeight and Height Comparison in Fill Extrusion Layer Causes Error

### ISSUE THREAD

**Issue by NasimAwabdy** [maplibre/maplibre-gl-js#4321]
maplibre-gl-js version: 4.4.1

browser: Chrome

### Steps to Reproduce

1. Add a fill extrusion layer to the map with the following filter
```
[
    ['all'],
    ['has', 'height'],
    ['has', 'baseHeight'],
    ['!=', ['get', 'baseHeight'], ['get', 'height']]
]
```

3. Observe the error:
`layers.d-furniture-extrusion.hot.filter[8][2]: string, number, or boolean expected, array found.`

### Link to Demonstration
[Demo](https://codepen.io/NasimAwabdy/pen/oNRyjqO)

### Expected Behavior
The filter should correctly exclude features where baseHeight is equal to height.

### Actual Behavior
An error is thrown, indicating that the filter expression is not valid because it expects a string, number, or boolean, but finds an array.

### Context
I have developed a program to draw indoor maps directly on the Maplibre GL JS interface. In my program, each feature with extruded properties can be viewed either in 2D or 3D, allowing users to toggle the extrusion view with a button. When the extrusion view is enabled, I want features with the same baseHeight and height values to be viewed only from their 2D layers, effectively filtering them out of the extrusion layers.

The toggling mechanism simply sets the visible property of the extruded layers to true. Since the extruded layers are ordered above the 2D layers, they cover the 2D layers when visible. However, for features where baseHeight equals height, these should not appear in the extruded view, ensuring that they are only visible in the 2D representation. The current issue arises because the filter expression intended to exclude these features from the extrusion layers is not functioning as expected due to an error in the filter syntax.

### Layer Definition
```
{
  id: DesignerLayerIds.FURNITURE_EXTRUSION,
  type: 'fill-extrusion',
  filter: [
    'all',
    ['==', '$type', 'Polygon'],
    ['has', 'displayType'],
    ['==', 'displayType', 'furniture'],
    ['has', 'height'],
    ['has', 'baseHeight'],
    ['!=', ['get', 'baseHeight'], ['get', 'height']]
  ],
  paint: {
    'fill-extrusion-color': '#fff',
    'fill-extrusion-opacity': 1,
    'fill-extrusion-base': ['to-number', ['get', 'baseHeight']],
    'fill-extrusion-height': ['to-number', ['get', 'height']],
  },
}
```

### GeoJSON Feature Definition
```
{
  "id": "xF67Mb",
  "type": "Feature",
  "geometry": {
    "type": "Polygon",
    "coordinates": [[[6.10040318, 50.77965077], [6.10040186, 50.77965062], [6.1004007, 50.7796502], [6.10039983, 50.77964955], [6.10039937, 50.77964875], [6.10039937, 50.77964791], [6.10039983, 50.77964711], [6.1004007, 50.77964646], [6.10040186, 50.77964604], [6.10040318, 50.77964589], [6.10040449, 50.77964604], [6.10040566, 50.77964646], [6.10040652, 50.77964711], [6.10040698, 50.77964791], [6.10040698, 50.77964875], [6.10040652, 50.77964955], [6.10040566, 50.7796502], [6.10040449, 50.77965062], [6.10040318, 50.77965077]]]
  },
  "properties": {
    "id": "xF67Mb",
    "height": 0,
    "baseHeight": 0,
    "description": "Furniture",
    "displayType": "furniture"
  }
}
```

**Comment by HarelM** [comment]
The template here is for a reason, please do not ignore it...
There's still a need for version number and reproduction example using jsbin/codepen etc ..

**Comment by NasimAwabdy** [comment]
Issue Updated

**Comment by HarelM** [comment]
Try the following, this uses the non-deprecated syntax:
```
[
      'all',
      ['==', ['geometry-type'], 'Polygon'],
      ['has', 'displayType'],
      ['==', ['get', 'displayType'], 'furniture'],
      ['has', 'height'],
      ['has', 'baseHeight'],
      ['==', ['get', 'baseHeight'], ['get', 'height']]
],
```
https://maplibre.org/maplibre-style-spec/deprecations/

**Comment by NasimAwabdy** [comment]
Thank you for your prompt response and the recommendation on using the non-deprecated syntax.

The main issue I'm facing is with this part of the filter:
```
['!=', ['get', 'baseHeight'], ['get', 'height']]
`
``

I want to compare the baseHeight and height properties to exclude features where these two values are equal. Specifically, the filter should exclude features from the extrusion layer when baseHeight is equal to height.

**Comment by HarelM** [comment]
I'm not sure I understand your last comment. Using non-deprecated expression this will work as intended.
