### ISSUE TITLE
npm run test-query-node fails in main

### ISSUE THREAD

**Issue by xabbu42** [maplibre/maplibre-gl-js#437]
### Steps to Trigger Behavior

 1. npm install
 2. npm run test-query-node

### Expected Behavior

In the 1.x branch and using yarn, the query tests are run.

### Actual Behavior
```
> maplibre-gl@2.0.0-pre.2 test-query-node /home/gass/src/maplibre-gl-js-test
> node --experimental-specifier-resolution=node --experimental-json-modules test/query.test.js

(node:13745) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/gass/src/maplibre-gl-js-test/rollup/build/tsc/index' imported from /home/gass/src/maplibre-gl-js-test/test/suite_implementation.js
    at finalizeResolution (internal/modules/esm/resolve.js:274:11)
    at moduleResolve (internal/modules/esm/resolve.js:708:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! maplibre-gl@2.0.0-pre.2 test-query-node: `node --experimental-specifier-resolution=node --experimental-json-modules test/query.test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the maplibre-gl@2.0.0-pre.2 test-query-node script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by HarelM** [comment]
Interesting, I thought this never ran as it was not part of the CI.
Feel free to try and restore this functionality.
Let me know if you are on it or not.

**Comment by xabbu42** [comment]
Yeah it never ran as part of the CI, but it did work in 1.x. There are a lot of failing tests though. I only found it recently searching for a place to add a test for #374.

I assume this regression is related to the the typescript refactor? If not I can search for the offending commit, but if it is the typescript refactor I'd rather leave fixing this to people who know what they are doing.

**Comment by HarelM** [comment]
If the tests are failing in 1.x I'm not sure it's worth fixing. Query tests are running in the browser, I believe.
TS probably broke it in terms of making it run, but fixing the tests is not something we did until now...

**Comment by xabbu42** [comment]
I got the following summary on 1.x:
```
85 passed (66.4%)
1 ignored (0.8%)
42 failed (32.8%)
```

I'll look into running the tests in the browser but I do think there is value in tests running from command line.

**Comment by HarelM** [comment]
The tests are running in the CI, as other have noted, running browser code on node is probably not the best approach as you need to mock a lot of stuff. running the tests in the browser make a lot of sense to me :-)
I'm not sure it's worth trying to make the tests pass since third of them are failing. Feels to me like the right direction is to remove this from the code base to reduce time waisted on it.
But I don't mind if someone wants to make it work.
I can help making the tests run and hopefully get the same results, but fixing tests that pass in the browser seems a bit too much for my taste :-)

**Comment by xabbu42** [comment]
Ah I see now, I was not aware that these tests are automatically run and all pass if run correctly. So I agree just removing this is best. I'll send a pull request.

**Comment by HarelM** [comment]
Cool! thanks!
