### ISSUE TITLE
The map still adds the hash after calling map.remove()

### ISSUE THREAD

**Issue by petr-hajek** [maplibre/maplibre-gl-js#4375]
**maplibre-gl-js version**: 4.5.0

**browser**: Chrome / any

### Steps to Trigger Behavior

 1. Use the map with `hash:true`  in Next.js
 3. Click on Next.js `<Link>` which triggers client side navigation (possibly it could happen with other React frameworks)
 4. Map is removed by calling  `map.remove()` in the cleanup of the useEffect which initializes the map
 5. It navigates to the new page but it receives the map's hash

### Link to Demonstration

[codesandbox](https://codesandbox.io/p/devbox/great-franklin-hzq6hm?file=%2Fapp%2FMap.tsx%3A9%2C45&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clycrrwu10006356mrj49130u%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clycrrwu10002356m5g3a91w5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clycrrwu10004356mp1u2kxv1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clycrrwu10005356mp5fwo7du%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B44.483128938678014%252C55.516871061321986%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clycrrwu10002356m5g3a91w5%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clycrrwu10001356mjc1dsq26%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clycsvcji0002356sujdek3dq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A45%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A45%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252FMap.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clycrrwu10002356m5g3a91w5%2522%252C%2522activeTabId%2522%253A%2522clycsvcji0002356sujdek3dq%2522%257D%252C%2522clycrrwu10005356mp5fwo7du%2522%253A%257B%2522id%2522%253A%2522clycrrwu10005356mp5fwo7du%2522%252C%2522activeTabId%2522%253A%2522clycrs74i0020356mple21vp5%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clycrs74i0020356mple21vp5%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%25234%252F49%252F11%2522%257D%255D%257D%252C%2522clycrrwu10004356mp1u2kxv1%2522%253A%257B%2522id%2522%253A%2522clycrrwu10004356mp1u2kxv1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clycrrwu10003356mhmtfowb6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clycrrwu10003356mhmtfowb6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Expected Behavior
After calling `map.remove()` it does not add the hash anymore

### Actual Behavior
It adds the hash to the page it navigated to even though the map has been removed.

**Comment by HarelM** [comment]
Thanks for taking the time to open this issue!
Feel free to submit a fix, it should be fairly straight forward I think.
