### ISSUE TITLE
Example in README not working

### ISSUE THREAD

**Issue by fredj** [maplibre/maplibre-gl-js#442]
The codepen in README (https://codepen.io/klokan/pen/WNoZRyx) is not working:
```
Uncaught SyntaxError: The requested module 'https://cdn.skypack.dev/maplibre-gl' does not provide an export named 'GeolocateControl'
```

**Comment by HarelM** [comment]
This is using version 2.0.1-pre.1 which is a problematic version (and was release by accident as release and not pre-release).
I would suggest to use either 1.15.x or use 2.0.1-pre.5.
If you happen to have time to test it with 2.0.1-pre.5 it would be great.

**Comment by astridx** [comment]
This is fixed [here](https://github.com/maplibre/maplibre-gl-js/pull/555), right?

**Comment by fredj** [comment]
yes, fixed
