### ISSUE TITLE
Remove `watch` scripts from `package.json`

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#445]
In the benchmark migration we came across a bunch of scripts in `package.json` which are broken or not used anymore. We might want to remove all scripts of the form `watch-*` and clean up historic CI-related scripts that are now replaced with GitHub Actions like `prepublishOnly`, `print-release-url`, and `diff-tarball`.

**Comment by xabbu42** [comment]
Does this mean that the watch-* scripts are no longer necessary to automatically trigger rebuilds or that we will no longer have this feature?

**Comment by wipfli** [comment]
The idea is to remove the watch functionality.

**Comment by jaapster** [comment]
For development the watch functionality is very useful but at the moment it seems that the 'build' folder is watched, not the 'src' folder which seems strange as I would expect changes to be made to files in 'src'. 
Is that on purpose?

**Comment by HarelM** [comment]
It's useful but broken. Feel free to submit a PR to fix this.

**Comment by jazzzz** [comment]
I have [a branch that fixes the `watch` scripts](/jazzzz/maplibre-gl-js/tree/watch), I intend to make a PR but I still need to fix some things, mostly moving back the `types` directory to the root directory.

**Comment by HarelM** [comment]
Types directory were removed, weren't they?

**Comment by jazzzz** [comment]
> Types directory were removed, weren't they?

Then it will be easier!

**Comment by jazzzz** [comment]
I created the PR: #704.

**Comment by HarelM** [comment]
Fixed by #704

**Comment by xabbu42** [comment]
Is it possible/easy to also resurrect and fix watch-benchmarks and use the watch scripts in start-bench? This way we would have the full original functionality back.

**Comment by HarelM** [comment]
@xabbu42 feel free to pursue this :-) Maybe @jazzzz can help out as well.

**Comment by xabbu42** [comment]
@jazzzz it would be great if you can look into this. I did nothing yet as i don't know the involved tools very well.

**Comment by jazzzz** [comment]
> Is it possible/easy to also resurrect and fix watch-benchmarks and use the watch scripts in start-bench? This way we would have the full original functionality back.

#754

**Comment by xabbu42** [comment]
Thank you very much!
