### ISSUE TITLE
Calling .setStyle() on modified object broken at v3

### ISSUE THREAD

**Issue by gavinr-maps** [maplibre/maplibre-gl-js#4472]
**maplibre-gl-js version**: 3.0.0 and greater

**browser**: all

### Steps to Trigger Behavior

```
const newStyle = map.getStyle();
// then modify newStyle object in some way
map.setStyle(newStyle);
```

In version 2 of `maplibre-gl-js`, the new style would be applied. In version 3 of `maplibre-gl-js`, the new style is not applied.

 

### Link to Demonstration

1. Go to https://jsbin.com/susahek/6/edit?html,output which uses maplibre-gl-js@2.4.0
     - Expected: parcels have different colors: yellow, green, red, blue.
     - Actual: parcels have different colors: yellow, green, red, blue. ✅  ![image](https://github.com/user-attachments/assets/915a68ac-863c-4274-9349-b6848ec5ad00)

 2. Go to https://jsbin.com/susahek/8/edit?html,output which is the same code as above, but uses maplibre-gl-js@3.0.0

      - Expected: parcels have different colors: yellow, green, red, blue.
     - Actual: parcels are not styled ❌ ![image](https://github.com/user-attachments/assets/e5d2da14-6296-4ed4-b3d0-55d3adf058a9)

### Note

Note this is still broken in the latest version, v4.5.0: https://jsbin.com/susahek/9/edit?html,output

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue. 
I think there was a change in set style in v3 that allowed supporting diff, which might fail for this case. Feel free to investigate and open a PR.

**Comment by HarelM** [comment]
BTW, the following does work for this specific case, and in general this would be the preferred way to update the style, nevertheless, there is a bug here.
```ts
      const newStyle = map.getStyle();
      map.setPaintProperty(newStyle.layers[0].id, "fill-color", ['case',
                       ['==', ['get','UseType'], 'Residential'], '#E8E191', // Yellow
                       ['==', ['get','UseType'], 'Commercial'], '#E580A2', // Red
                       ['==', ['get','UseType'], 'Government'], '#79E284', // Green
                       ['==', ['get','UseType'], 'Industrial'], '#C080E5', // Purple
                       ['==', ['get','UseType'], 'Institutional'], '#80BBE5', // Blue
                       '#bfbfbf'
       ]);
```

**Comment by gavinr-maps** [comment]
I went back in the commit history, and the first commit that this issue started happening was 3157c340e5573699e46ce4b3fc17e9e670442e1a which is the merge of https://github.com/maplibre/maplibre-gl-js/pull/2306.

**Comment by HarelM** [comment]
Yeah, that caused a few issues in the past 😕

**Comment by gavinr-maps** [comment]
I have figured out a more "core" issue that is the root cause of the originally reported issue. So I'll open up a separate issue to focus on that.

Thanks for your responses @HarelM.
