### ISSUE TITLE
Rendering of vector tiles in wrong y-order

### ISSUE THREAD

**Issue by josch0** [maplibre/maplibre-gl-js#4500]
I am currently setting up my own tile-server with Martin. In the process, I came across a strange behavior. I can't explain what is causing the error. I currently suspect that the problem lies somewhere in maplibre-gl. (... or is it my fault?)

My setup:
Martin is running on my server and provides a basemap via MBTiles. The basemap is based on the open-source OSM tileset from https://openmaptiles.org/. There is no additional config in Martin, just serving the MBTiles as source.

I have created my own style via Maputnik.
https://api.worldsirenmap.net/map/styles/wsm2.json (tile.json URL)
https://api.worldsirenmap.net/map/styles/wsm.json (direct tiles URL)

Now the problem:
If I set the tile.json URL from Martin, the tiles are rendered in the wrong y-order.

```
"sources": {
    "basemap": {
      "url": "https://api.worldsirenmap.net/map/tiles/basemap",
      "type": "vector"
    }
  },
```

If I enter the direct tiles URL in the style, the tiles are rendered correctly.

```
  "sources": {
    "basemap": {
      "tiles": [
           "https://api.worldsirenmap.net/map/tiles/basemap/{z}/{x}/{y}"
      ],
      "type": "vector"
    }
  },
```

**maplibre-gl-js version**: 4.5.0

**browser**: Chrome, Edge

### Steps to Trigger Behavior

 1. Go to JsBin. Look. :-)

### Link to Demonstration

https://jsbin.com/guyulogelu/edit?html,output

### Expected Behavior

It should make no difference whether I specify the tiles.json URL or the URL to the tiles directly.

### Actual Behavior

There is something wrong.

**Comment by HarelM** [comment]
I think you have scheme tns in the tilejson, which is what's causing the flip...?

**Comment by josch0** [comment]
Thanks for your answer, that was the right hint, but:
As you can see from the code snippet above, the source has no "scheme" set at all. According to the Maplibre style spec, "scheme" is optional and the default value is "xyz".

But apparently not in my case. If I explicitly set "scheme" to "xyz", the map is displayed correctly. 

```
  "sources": {
    "basemap": {
      "url": "https://api.worldsirenmap.net/map/tiles/basemap",
      "type": "vector",
      "scheme": "xyz"
    }
  },
```

I have added a new Jsbin example. ("explicit scheme" vs. "default scheme"). Can you perhaps take a look at why the default obviously does not correspond to the spec?

https://jsbin.com/biqehatoci/edit?html,output

**Comment by josch0** [comment]
Yes, you're right.

I didn't even look at the scheme in the tile.json.

I looked at the Maplibre Style Spec, it says in "sources/scheme" that "xyz" is the default value. But obviously the default value is what is in the tile.json. Fortunately, I can explicitly set "scheme" in the style and thus overwrite the tile.json.

The spec is somewhat imprecise at this point. 
Thanks for the hint. Can be closed.
