### ISSUE TITLE
Replace some manual script detection with regular expressions

### ISSUE THREAD

**Issue by 1ec5** [maplibre/maplibre-gl-js#4541]
For several years, I’ve been manually maintaining a relevant subset of the Unicode Character Database that GL JS uses to detect scripts for vertical layout, ideographic line breaking, complex text layout, and right-to-left layout. This solution works reasonably efficiently, but it’s difficult to keep it up-to-date as Unicode evolves, because relatively few contributors are familiar with these parts of the Unicode standard or the associated text layout conventions.

I think the custom script detection logic should be replaced by Unicode-aware regular expressions where possible. I’ve identified two such opportunities; there may be others.

It should be possible to replace the following function:

https://github.com/maplibre/maplibre-gl-js/blob/007ad7b6e58dc13e12366f2cdf4f648a741bc0f8/src/util/script_detection.ts#L268-L275

with the following code:

```js
export function charInComplexShapingScript(char: number) {
    return /\p{Sc=Arab}/u.test(String.fromCodePoint(char));
}
```

and replace the following function:

https://github.com/maplibre/maplibre-gl-js/blob/007ad7b6e58dc13e12366f2cdf4f648a741bc0f8/src/util/script_detection.ts#L37-L63

with the following code:

```js
export function charAllowsIdeographicBreaking(char: number) {
    return /\p{Ideo}/u.test(String.fromCodePoint(char));
}
```

This will make the functions more future-proof, so that we don’t need to notice that a new CJK-related block has been added to Unicode etc. The downside is that this requires a relatively recent version of ECMAScript. This codebase has [never used](https://github.com/search?q=repo%3Amaplibre%2Fmaplibre-gl-js+%2F%5C%2F%5Cw*u%5Cb%7CRegExp%5C%28%5B%27%22%5D%5B%5E%27%22%5D%2B%3F%5B%27%22%5D%2C%5Cs*%5B%27%22%5D%5Cw*u%2F&type=code) a Unicode regular expression so far, let alone a [Unicode character escape](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Regular_expressions/Unicode_character_class_escape). Does GL JS still maintain capability with Chrome 63, Firefox 77, or Safari 11.0 or earlier versions of these browsers?

Unfortunately, it isn’t currently possible to replace `charHasUprightVerticalOrientation()`, `stringContainsRTLText()`, or `unicodeBlockLookup` with something more robust, because the ECMAScript standard [doesn’t yet allow](https://tc39.es/ecma262/multipage/text-processing.html#sec-runtime-semantics-unicodematchproperty-p) a regular expression to match on the `Vertical_Orientation`, `Bidi_Class`, or `Block` property, respectively.

**Comment by HarelM** [comment]
There's no need to support old browsers. Newer version of maplibre will support new browsers while old versions can support old browsers (given that the old version does not have a "big" market share).
I think the suggestion above is a good simplification and moves the responsibility to regexp, which is better than hardcoding stuff like it is right now.
