### ISSUE TITLE
support css color without comma separated

### ISSUE THREAD

**Issue by JinIgarashi** [maplibre/maplibre-gl-js#4598]
## User Story

CSS color has another way to express without comma separated like `rgb(255 255 0)` or `rgba(34 12 64 / 0.6)`. Currently maplibre only support comma separated color. It would be nice if it can support this color style as well

## Rationale

I think chroma.js is a great library work with colors in JavaScript. I realized chroma.js stopped supporting to export legacy comma separated css color like `rgb(255, 255, 0)` or `rgba(34,12,64,0.6)` since v3. 

Chroma v3 release note
https://github.com/gka/chroma.js/releases/tag/v3.0.0

CSS color doc
https://developer.mozilla.org/en-US/docs/Web/CSS/color

## Impact

There is no negative impact by adding new css color style to support.
But it will be more compatible with CSS color style, and it become easier to work with JavaScript, particularly with Chroma.js

**Comment by HarelM** [comment]
This was actually added to maplibre a while back: 
https://github.com/maplibre/maplibre-style-spec/pull/175
See the following file: 
https://github.com/maplibre/maplibre-style-spec/blob/e2c0e0056556a0825106afd26f88820b557b8e8e/src/util/parse_css_color.ts

**Comment by JinIgarashi** [comment]
@HarelM Thanks. and I am sorry I missed it has been fixed in style repo. so should maplibre gl js work with this css color style?

I tested the color style in [charites](https://github.com/unvt/charites) editor. maybe the version in this library is old. I will check with the latest version.

**Comment by HarelM** [comment]
It seems that charites is using version 19.3 of the style-spec package and the code above was introduced in version 19.0-19.1, so it should be OK, assuming they have released the version in the main branch:
https://github.com/unvt/charites/blob/ad3e36bd76f081cb3560072cd93b1eef998b069d/package.json#L20

**Comment by JinIgarashi** [comment]
@HarelM Charites use 2.4.0 from CDN

https://github.com/unvt/charites/blob/ad3e36bd76f081cb3560072cd93b1eef998b069d/provider/default/index.html#L5-L8

I just manually upgrade maplibre, and tried this css style. and it works perfectly! let me close this
