### ISSUE TITLE
Support non-sprite images

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#46]
## Motivation

When designing a map one needs to place all the icons inside a sprite. Our site provides a way to show custom styles created by users. But the sprite is "hard coded" and updating even the basic site style has to be on two steps: 1. Update sprite, 2. Update style.

## Design Alternatives

Should facilitate easier map design.

## Design

Allow using `icon: url` in style spec

### Implementation

I was thinking of using the loadImage method somehow, still not sure... Need to investigate...

**Comment by AbelVM** [comment]
Actually, with current version you can easily use `loadImage`, and you can even enable the style to change the image color (using `sdf: true` option and then `'icon-color' property), and scale or rotate it.

```javascript
map.loadImage('path/to/my_image.png', function(error, image) {
         if (error) throw error;
         map.addImage('my_icon', image, { sdf: true });
});

map.addLayer({
        'id': 'my_layer',
        'source': 'point',
        'type': 'symbol',
        'layout': {
                'icon-image': 'my_icon',
                'icon-rotate': my_rotation
        },
         'paint':{
                'icon-color': my_color
         }
 });
```

Other approach is to create full HTML markers, as in [this example](https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/)

Does this solve your problem?

**Comment by HarelM** [comment]
I don't think it does, unfortunately.
Consider the following use case:
I'm running a site that has a "hard coded" sprite.
I let a designer work on a style.
When this designer finishes his work I would like to simply use the style he uploaded somewhere to the cloud let say at `http://www.example.com/his-style.json`
If my site uses this uploaded style and this style now contains icons that are not in the sprite I have, they won't show up.
Now I can workaround this by loading the style, looking for icons that are url-like and use `loadImage` and replace the attribute in the style that I loaded in memory, but I would prefer if this library would do that out of the box, allowing designers to shed the need to create a sprite and push it along side their style.json file...

**Comment by AbelVM** [comment]
Hmm, if I understand it right, what you need is to let the designers upload both the style and the sprite used in the style (if needed). You should be able to do so using the current version too, like described [here](https://docs.mapbox.com/mapbox-gl-js/style-spec/sprite/)

**Comment by HarelM** [comment]
In theory you are right, in practice there's no set sprite method, and when using the setStyle method everything falls apart when you have multiple layers that were added after you set the original style.
I might be wrong and just suffered a result of bad dude that I wrote, but this was a painful experience...

**Comment by AbelVM** [comment]
Hmm, now I get it. 

What about using [styleimagemissing](https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:styleimagemissing) event to add the images on-the-fly as needed? (check the [example](https://docs.mapbox.com/mapbox-gl-js/example/add-image-missing-generated/) there). That might give you the flexibility you need.

**Comment by HarelM** [comment]
I'm guessing that I could implement this on my end, i.e:
```
{
    version: 8,
    sources: {
        ...
    },
    layers: [{
        type: "symbol"
        source: "my-source"
        layout: {
            "icon-image": "https://www.example.com/my-icon.png",
        }
    }],
    glyphs: "...",
    sprite: "..."
}
```
And then use the `styleimagemissing` event to get the image and add it.
But I was thinking this can be beneficial to other people, and not just me and therefore should be a first class citizen in this library...
I think the whole concept of sprite is creating an unneeded complexity - If I told you that in order to build a website all the images that are used in any page need to be placed inside a huge image you would say that I'm crazy, wouldn't you :-)
I understand the performance considerations, and when someone prefers performance over dynamic content a sprite is a good solution, but for my needs, I need the style to be able to be more dynamic...

**Comment by russss** [comment]
I was struggling with sprites recently, and I think there's definitely an argument to deprecate sprites and make it easier to use individual images.

I currently generate a sprite from SVGs for OpenInfraMap, and it's a pain. Mapbox's [spritezero](https://github.com/mapbox/spritezero) is nice, but it has a dependency on our old friend mapnik (!) which invariably fails to compile. Mapbox provides precompiled versions for certain (unspecified) combinations of node.js and OS, but never the ones I need.

There used to be a solid performance argument for sprites (and many performance-conscious people did build their websites using them!) however the benefit of sprites should be fairly nonexistent now that HTTP/2 is commonplace, as long as the images are fetched in parallel.

So I think it would be nice to provide a more straightforward way of loading images individually, perhaps by referencing them in the style, so I don't have to write code to do `loadImage` all the time.

I also think that the Mapbox documentation does steer you towards using sprites (I didn't find out about `loadImage` until quite recently), and once Maplibre has its own docs we should reconsider that.

**Comment by HarelM** [comment]
Just a side note, I use spritezero with a docker image to avoid os nodejs issues as you said... I also needed a way to generate sdf sprite so I needed a fork of spritezero that supports this, but that's another side note...

**Comment by HarelM** [comment]
I'll see if I can add support for this and send a PR to be reviewed.

**Comment by HarelM** [comment]
For future reference, this is basically covered here:
https://maplibre.org/maplibre-gl-js-docs/example/add-image-missing-generated/
We have decided that the example above is a good enough solution to this issue in the steering committee meeting.
The implementation can be seen here:
https://github.com/IsraelHikingMap/Site/blob/6aa2ec0cfb8891fa048b1d9e2a4fc7d4cbcc8c97/IsraelHiking.Web/src/application/services/map.service.ts#L46L57

**Comment by tordans** [comment]
If anyone come here looking for a React / React Map GL Example, there is a good thread at https://github.com/visgl/react-map-gl/issues/2086#issuecomment-1462609215.
