### ISSUE TITLE
`line-offset` is not supported for polygons

### ISSUE THREAD

**Issue by CommanderStorm** [maplibre/maplibre-gl-js#4623]
**maplibre-gl-js version**: v4.6.0
**browser**: chrome, latest

### Steps to Trigger Behavior

 1. Add the `paint.line-offset` property to a `type: "fill"` `StyleLayer`
 2. See maplibres style check the style, find it invald and reject it
    - typecript definitions don't allow said field
    - the validation rejects it with `Error: layers.box.paint.line-offset: unknown property "line-offset`

### Link to Demonstration

(the stye below is just for demonstration, **see the browser console**)
=> this should be the same as [here](https://maplibre.org/maplibre-gl-js/docs/examples/geojson-polygon/), but with an inset line

https://jsbin.com/hinonen/edit?html,output

### Expected Behavior

According to the `Layers` spec ([here](https://maplibre.org/maplibre-style-spec/layers/#line-offset)) (last line is the relevant part I am expecting ^^)

> ## line-offset
> [Paint](https://maplibre.org/maplibre-style-spec/layers/#paint) property. Optional [number](https://maplibre.org/maplibre-style-spec/types/#number). Units in pixels. Defaults to 0. Supports [feature-state](https://maplibre.org/maplibre-style-spec/expressions/#feature-state) and [interpolate](https://maplibre.org/maplibre-style-spec/expressions/#interpolate) expressions. Transitionable.
> 
> The line's offset. For linear features, a positive value offsets the line to the right, relative to the direction of the line, and a negative value to the left. ***For polygon features, a positive value results in an inset, and a negative value results in an outset.***

I would appreciate feedback if this is a bug in the spec or in the implementation
=> if I should provide a PR to remove that line from the docs or look into implementing that part of the spec ^^

### Actual Behavior

Validation does not allow the insetting of `fill` layers.

### Additional Information

If this is a bug in `maplibre-gl-js` (instead of the spec), I would be more than happy to work on an implementation.
If this is a bug in the spec, I can also provide a PR against the spec removing that part ^^
That a `line-offset` affects the `fill-inset` seems somewhat.. wierd, but also kind of makes sense.

<details><summary>My motivation for doing this</summary>
<p>

The reason why I want inset/offsetting `fill` layers, is that this way, I can have doors be properly displayed on an indoor map.
How I am doning this is a bit hacky, but works supprisingly well:

![image](https://github.com/user-attachments/assets/5da7ef85-8901-4709-97af-ef9c75959ac4)

=> I do this the following way:

- first draw a regular room WITH outline
- the block out the door with the same background color as the room => no line is there anymore
- then draw the walkable space outside with a different color and WITHOUT an outline.
  Problem: this reduces the line-width by half

</p>
</details>

**Comment by HarelM** [comment]
You are using a `fill` layer and not a `line` layer - this is what's causing the issue you are describing.
If you'd take a look at the documentation table of content on the right, you'd notice that this is part of the documentation for line layer:
![image](https://github.com/user-attachments/assets/391904b5-5a3d-4666-8b86-75aa052d0fb0)

**Comment by CommanderStorm** [comment]
Oh, sorry.
I just noticed that the documentation (somewhat subtely) differentiates between `Polygon` and `fill`.
`fill` implies `Polygon`, but `Polygon` does not imply `fill`
