### ISSUE TITLE
[Bug] After rotating the map, calling the fitBounds() method will cause the map to rotate.

### ISSUE THREAD

**Issue by chilsa** [maplibre/maplibre-gl-js#4633]
**maplibre-gl-js version**: 4.5.0 or 4.6.0

**browser**: chrome

### Steps to Trigger Behavior

 1. Render a map
 2. Rotate the map
 3. Call map.fitBounds()

### Link to Demonstration
https://output.jsbin.com/mexomey

### Expected Behavior
The map should fitBounds on the new rotation angle

### Actual Behavior
The map will first be rotated back to the initial orientation and then fitBounds will be performed

**Comment by HarelM** [comment]
Jsbin gives 404.
Can you pass `bearing` to the fitBounds?

**Comment by chilsa** [comment]
> Jsbin gives 404. Can you pass `bearing` to the fitBounds?

sorry, i updated the demo with "bearing: 60", you could just click the button to check the effect.
https://jsbin.com/ruzilat/edit?html,output

**Comment by chilsa** [comment]
> Jsbin gives 404. Can you pass `bearing` to the fitBounds?

To avoid to be 404 again, I put the demo code below. Thank you!

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Display a map</title>
    <meta property="og:description" content="Initialize a map in an HTML element with MapLibre GL JS." />
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel='stylesheet' href='https://unpkg.com/maplibre-gl@4.6.0/dist/maplibre-gl.css' />
    <script src='https://unpkg.com/maplibre-gl@4.6.0/dist/maplibre-gl.js'></script>
    <style>
        body { margin: 0; padding: 0; }
        html, body, #map { height: 100%; }
        button {
            position: absolute;
            left: 0;
            top: 0;
        }
    </style>
</head>
<body>
<div id="map"></div>
<button onclick="handleFitBounds()">fitBounds</button>
<script>
	const map = new maplibregl.Map({
		container: 'map', // container id
		style: 'https://demotiles.maplibre.org/style.json', // style URL
		center: [0, 0], // starting position [lng, lat]
		zoom: 1, // starting zoom
		maplibreLogo: true,
		bearing: 60,
	});
	function handleFitBounds() {
		map.fitBounds([[-156.97265624999827, -76.1429584647982], [156.97265625000085, 76.14295846479854]]);
    }
</script>
</body>
</html>

**Comment by HarelM** [comment]
The following seems to work as expected I believe:
```js
function handleFitBounds() {
		map.fitBounds([[-156.97265624999827, -76.1429584647982], [156.97265625000085, 76.14295846479854]], {bearing: map.getBearing()});
    }
```

**Comment by chilsa** [comment]
> The following seems to work as expected I believe:
> 
> ```js
> function handleFitBounds() {
> 		map.fitBounds([[-156.97265624999827, -76.1429584647982], [156.97265625000085, 76.14295846479854]], {bearing: map.getBearing()});
>     }
> ```

The real effect is: the map will be rotated back to bearing: 0 then fit bounds. Shouldn't the map be kept at bearing: 60 with fit bounds?

**Comment by chilsa** [comment]
> The following seems to work as expected I believe:
> 
> ```js
> function handleFitBounds() {
> 		map.fitBounds([[-156.97265624999827, -76.1429584647982], [156.97265625000085, 76.14295846479854]], {bearing: map.getBearing()});
>     }
> ```

I am sorry i did not see the full codes just now, i tried your codes, it works! Thank you so much!!
