### ISSUE TITLE
Introduce code coverage to jest tests

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#464]
## Motivation

In order to better understand and see that we cover most code with the exiting unit test we need to introduce code coverage to our CI.
From very limited google search I found this, but there might be other that are better:
https://github.com/marketplace/actions/jest-coverage-report
@wipfli @astridx I think this can help us see which functions and methods are covered by the changes we do in jest.
What do you think?

**Comment by astridx** [comment]
I would not add it automatically during migration because it takes a lot of time.
You can run it via 
npm run test-jest -- --coverage
manually

**Comment by birkskyum** [comment]
@HarelM  I tried to run it just now:

npm run test-unit: 26.12 s
npm run test-unit -- --coverage:  95.894 s

**Comment by HarelM** [comment]
I think it's worth the extra 1.5 minute. but we should publish it as part of the CI using a bot or something...?
We can probably publish it to codecov too as a different approach.

**Comment by birkskyum** [comment]
I think it's worth it too, but I'm not familiar with codecov and how to set it up.

**Comment by wipfli** [comment]
See #487

**Comment by HarelM** [comment]
Can we try and revive this PR?

**Comment by HarelM** [comment]
This is still interesting

**Comment by HarelM** [comment]
Fixed by #1527
