### ISSUE TITLE
[Feature request] FlatGeobuf source

### ISSUE THREAD

**Issue by indus** [maplibre/maplibre-gl-js#468]
## Motivation

I would like to make use of the [FlatGeobuf](https://github.com/flatgeobuf/flatgeobuf) format as a source and benefit from the smaller network footprint and the faster processing times. I would like to replace some cases where I use GeoJSON atm. FlatGeobuf has already gained some adoption and there are quite a number of tools to produce/serve them: http://flatgeobuf.org/#supported-applications--libraries

## Design Alternatives

FlatGeobuf converts to GeoJSON. So one option would be to use it like in the leaflet and openlayers examples. The FlatGeobuf gets deserialized to GeoJSON and then added to the map with its default API. This could be done easily in the user code already.

A more interesting design would integrate FlatGeobuf to maplibre as a regular source type. The GeoJSON step could be skiped and the map API could make use of the filter function of FlatGeobuf.

## Design

The second design would have better perfomance and better usability. 

### Mock-Up
```
map.addSource('some id', {
  type: 'flatgeobuf',
  data: 'https://flatgeobuf.org/test/data/UScounties.fgb'
//  filter: 'viewport' optional
});
```

### Concepts

It should be a 1:1 replacement/alternative for GeoJSON with benefits for bigger datasets.  The "filter" functionality is a bonus.

### Implementation

?

**Comment by indus** [comment]
When using GeoJSON as intermediate format I don't see the need for an example as it just uses a the regular GeoJSON API of maplibre. And examples of how to convert FlatGeobuf to GeoJSON exist on their website.
Nevertheless I made one here: https://jsfiddle.net/eo2pbm9L/9/
Integration in all platforms would be challange. But is this necessary right from the beginning?

**Comment by HarelM** [comment]
It's not needed straight up, but we need to make sure this is possible in all platforms and that someone will pick this up in other platforms, otherwise we are deliberately creating inconsistency, which we do not want...

**Comment by HarelM** [comment]
Steering committee decision: Maplibre-gl-js can support features that are not supported in other platforms.
This needs to be documented in the maplibre docs repository to indicate that a feature is only supported in a specific platform.
There's also a need to open an issue for the others repo, preferably with the relevant implementation in the supported platform.
Feel free to submit a PR with the relevant code changes.
Don't forget to update the style definitions, generate the code based on the updated style definition and add the relevant tests.
If you have any questions, feel free to pint me.
Thanks!

**Comment by indus** [comment]
I no longer think custom formats should be intergrated into maplibre itself. I made a library [`mapsrc`](https://github.com/indus/mapsrc) that allows integration of multiple custom sources formats: https://mapsrc.js.org
While it has the shortcoming that it requires a detour via GeoJSON, I think it is much more flexible and easier to extend for other geo-formats. It also doesn't increase the size of maplibre-gl-js itself.

Nevertheless you may want to think about making the class of GeoJSONSource accesible from the public API. This would make [this hack](https://github.com/indus/mapsrc/blob/main/packages/utils/src/utils.ts#L18) unnecessary and give devs a easy way to extend it with format specific subclasses.

**Comment by wipfli** [comment]
@indus want to keep this open?

**Comment by indus** [comment]
No - you can close this.Am 01.05.2022 16:09 schrieb Oliver Wipfli ***@***.***>:
@indus want to keep this open?
