### ISSUE TITLE
Example `add-deckgl-layer-using-rest-api` doesn't load on localhost

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#4680]
This [example](https://maplibre.org/maplibre-gl-js/docs/examples/add-deckgl-layer-using-rest-api/) have tile requests blocked when running on localhost.

It's using a basemap from https://maps.clockworkmicro.com/

I've reached out to the team, and they'll investigate this week, because the requests are supposed to go through, similar to the tile providers used in the other examples (stadia maps, maptiler etc.).

Opening this as a tracking ticket, so it's followed up.

**Comment by HarelM** [comment]
@birkskyum can you check and close this issue if this is no longer a problem?

**Comment by birkskyum** [comment]
It's indeed working now, thanks @ilci66 !
