### ISSUE TITLE
Docs: Split new category from UI plugins

### ISSUE THREAD

**Issue by petr-hajek** [maplibre/maplibre-gl-js#4682]
## User Story

As a developer using MapLibre I can find the plugin I need more easily in https://maplibre.org/maplibre-gl-js/docs/plugins/ 

## Rationale

[User Interface Plugins](https://maplibre.org/maplibre-gl-js/docs/plugins/#user-interface-plugins) has 24 items and more coming. 

## Impact

It's hard to find the plugin I need

## Solution:
Have more categories.
One new category could be called Search or Geocoding - there are several such plugins in the list
If you have some more ideas for another new category, let me know

**Comment by petr-hajek** [comment]
I'll wait for the other PRs to be merged here and then I'll make a PR

**Comment by HarelM** [comment]
The relevant PR is the following, it should be merged soon:
- #4707

It will create the plugin page based on maplibre-awesome readme, so feel free to simply improve maplibre-awesome readme, and this repo will fetch it from there.
If you want more sections please write in the above linked PR, preferably before it gets merged.
