### ISSUE TITLE
maplibre-gl 2.0.0-pre.5 on angular 12

### ISSUE THREAD

**Issue by catalinconstant** [maplibre/maplibre-gl-js#474]
Hello! I wanted to give a try of maplibre-gl 2.0.0-pre.5 in Angular 12 but I get the following errors:

Error: node_modules/maplibre-gl/types/util/vectortile_to_geojson.d.ts:6:25 - error TS2304: Cannot find name 'VectorTileFeature'.

6     _vectorTileFeature: VectorTileFeature;
                          ~~~~~~~~~~~~~~~~~


Error: node_modules/maplibre-gl/types/util/vectortile_to_geojson.d.ts:6:25 - error TS2304: Cannot find name 'VectorTileFeature'.

6     _vectorTileFeature: VectorTileFeature;
                          ~~~~~~~~~~~~~~~~~

Error: node_modules/maplibre-gl/types/util/vectortile_to_geojson.d.ts:7:36 - error TS2304: Cannot find name 'VectorTileFeature'.

7     constructor(vectorTileFeature: VectorTileFeature, z: number, x: number, y: number, id: string | number | void);
Error: node_modules/maplibre-gl/types/util/vectortile_to_geojson.d.ts:6:25 - error TS2304: Cannot find name 'VectorTileFeature'.

6     _vectorTileFeature: VectorTileFeature;
                          ~~~~~~~~~~~~~~~~~


Error: node_modules/maplibre-gl/types/util/vectortile_to_geojson.d.ts:7:36 - error TS2304: Cannot find name 'VectorTileFeature'.

7     constructor(vectorTileFeature: VectorTileFeature, z: number, x: number, y: number, id: string | number | void);

535             mousemove?: undefined;
                ~~~~~~~~~


Error: node_modules/maplibre-gl/types/ui/map.d.ts:536:13 - error TS2411: Property 'mouseout' of type 'undefined' is not assignable to string index type '(e: any) => void'.

536             mouseout?: undefined;
                ~~~~~~~~


Error: node_modules/maplibre-gl/types/util/vectortile_to_geojson.d.ts:6:25 - error TS2304: Cannot find name 'VectorTileFeature'.

6     _vectorTileFeature: VectorTileFeature;
                          ~~~~~~~~~~~~~~~~~

Error: node_modules/maplibre-gl/types/util/vectortile_to_geojson.d.ts:7:36 - error TS2304: Cannot find name 'VectorTileFeature'.

7     constructor(vectorTileFeature: VectorTileFeature, z: number, x: number, y: number, id: string | number | void);
                                     ~~~~~~~~~~~~~~~~~




** Angular Live Development Server is listening on 0.0.0.0:4200, open your browser on http://localhost:4200/ **



535             mousemove?: undefined;
                ~~~~~~~~~


Error: node_modules/maplibre-gl/types/ui/map.d.ts:536:13 - error TS2411: Property 'mouseout' of type 'undefined' is not assignable to string index type '(e: any)
 => void'.

536             mouseout?: undefined;
                ~~~~~~~~


Error: node_modules/maplibre-gl/types/util/vectortile_to_geojson.d.ts:6:25 - error TS2304: Cannot find name 'VectorTileFeature'.

6     _vectorTileFeature: VectorTileFeature;
                          ~~~~~~~~~~~~~~~~~

Error: node_modules/maplibre-gl/types/util/vectortile_to_geojson.d.ts:7:36 - error TS2304: Cannot find name 'VectorTileFeature'.

7     constructor(vectorTileFeature: VectorTileFeature, z: number, x: number, y: number, id: string | number | void);
                                     ~~~~~~~~~~~~~~~~~

**Comment by catalinconstant** [comment]
I have tried in stackbiltz and is working (https://stackblitz.com/edit/angular-ivy-vuttfs?file=src/app/hello.component.ts).
It seems that in local env maplibre-gl library is skipped by Ivy / ngcc compiler.

**Comment by HarelM** [comment]
This might also be related to the following comment:
https://github.com/maplibre/maplibre-gl-js/issues/370#issuecomment-972923342
I need to properly fix the typescript definitions anyway...
