### ISSUE TITLE
speed regressions in main relativ to 1.x

### ISSUE THREAD

**Issue by xabbu42** [maplibre/maplibre-gl-js#476]
The benchmarks seem to be quite good at picking up even minor speedups and slowdowns so I'm not sure we actually need to address all or even any of the following slowdowns. On the other hand its not yet always clear to me what are benchmarks for hotpathes in inner loops where even minor slowdowns are a problem and what are more end-to-end benchmarks.

Anyway comparing to 1.x (`npm run start-bench`, go to http://localhost:9966/bench/versions?compare=1.x) I see the following consistent "larger" (that is >1ms and >2%) slowdowns:
http://localhost:9966/bench/versions?compare=1.x#QueryPoint got ca 5% slower (1.5ms)
http://localhost:9966/bench/versions?compare=1.x#QueryBox got ca 5% slower (10ms)
http://localhost:9966/bench/versions?compare=1.x#Placement got ca 5% slower (1ms)
http://localhost:9966/bench/versions?compare=1.x#PropertyLevelRemove got ca 3% slower (3ms)
http://localhost:9966/bench/versions?compare=1.x#LayerTextWithVariableAnchor got ca 4% slower (2ms)

This are all very minor, but at least the Query slowdowns of 5% seem to be worth addressing as this functions are usually called a lot (for example for hover popups).

**Comment by HarelM** [comment]
Typescript is traspiled to javascript, we reverted most of the changes to fix the failing tests.
So basically the javascript code after traspilation should be very very similar to how it was before the migration.
Dependencies update is a good point to consider.
Bottom line, I don't know where to start in order to solve this, but dependencies is a good idea to explore.

**Comment by wipfli** [comment]
@xabbu42 I guess the dependencies for the benchmarks are still an issue, right?

**Comment by xabbu42** [comment]
I finally got around to play with the benchmarks a bit more today.

I could not reliably reproduce these slowdowns comparing current main to v1.15.2 in safari. they are mostly non-existing when using run-benchmarks.ts, that is on chromium. all together if speed is a concern the limited time is probably better used just looking at the status quo and finding optimizations than tracking down such minor slowdowns which may not even exist or at least do not exist for all browsers. so this issue can imho remain closed. sorry for the noise.

**Comment by HarelM** [comment]
No worries, thanks for taking the time to look at this! Truly appreciated!
