### ISSUE TITLE
`queryRenderedFeatures` gets very slow with complex maps due to O(n^2) layerId lookup in `loadMatchingFeature`

### ISSUE THREAD

**Issue by tomhicks** [maplibre/maplibre-gl-js#4770]
I know exactly how to fix this: we need to pass `layers` as a `Set` rather than a list and use `.has` instead of `arrayIntersects` and `filterLayerIDs.indexOf(layerID)`.

The problem here is that this is likely to alter the signature of some parts of MapLibre that might be considered public. For instance, although this is accessed usually via `map.queryRenderedFeatures` there are other entry points such as via the `Tile` class.

How should I proceed in making a PR here? We could accept either and check if it's an Array or Set all the way down?

**maplibre-gl-js version**: 4.7

**browser**: All

### Steps to Trigger Behavior

 1. Have a complex map with lots of layers (100s of layers are needed)
 2. Use query rendered features and look at the performance trace

### Link to Demonstration

An immense amount of time being spent in `loadMatchingFeatures`
<img width="607" alt="image" src="https://github.com/user-attachments/assets/950ac26d-a417-4113-ad11-77e81bab47f4">

### Expected Behavior

It shouldn't get quadratically slower as layers are added.

### Actual Behavior

It gets quadratically slower as layers are added.

**Comment by HarelM** [comment]
Map is the relevant public API, tile is less interesting.
If you have a good solution you are welcome to open a PR.
We are also nearing version 5, so we might be able to introduce a breaking change.
