### ISSUE TITLE
tiles are not displayed correctly when both terrain and the new globe projection are used

### ISSUE THREAD

**Issue by programingjd** [maplibre/maplibre-gl-js#4792]
If you use the new `globe` projection, things display properly until you enable `terrain`.
A `hillshade` layer from the same `raster-dem` source works, but not the `terrain` option.

This is using the 5.0.0-pre.1 alpha release.

https://codepen.io/programingjd/pen/jOgWepY

You can toggle the terrain from the checkbox and see how simply resetting terrain to null makes the raster tiles display correctly.

This is not for raster tiles only, the same thing happens with vector tiles.

**Comment by HarelM** [comment]
Thanks for taking the time to report this.
