### ISSUE TITLE
Ocean stripes over continent

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#4799]
**maplibre-gl-js version**:
5.0.0-pre.1

**browser**:
chrome on ubuntu

### Steps to Trigger Behavior

 1. Open https://jsbin.com/rulalux/edit?html,output
 2. observe stripes of ocean blue over continent

#### 5.0.0-pre.1

bug present:

https://jsbin.com/rulalux/edit?html,output

![image](https://github.com/user-attachments/assets/a6413656-62a3-472d-a387-7c9a37e66e70)

#### 4.7.1

bug not prensent

https://jsbin.com/kiqetew/edit?html,output

![image](https://github.com/user-attachments/assets/7d6189c8-230d-491a-b8a6-d5d160c54255)

### Expected Behavior

no stripes like in v4

### Actual Behavior

stripes

**Comment by wipfli** [comment]
The stripes are also visible in the globe mode.

**Comment by HarelM** [comment]
Thanks for taking the time to report this! 
Can you try and make a smaller reproduction to narrow down the relevant layer?

**Comment by wipfli** [comment]
Updated the map style to have only one layer

**Comment by HarelM** [comment]
Let's keep this one open for now, if it's the same root cause then a PR to solve it can close the other issue as well. 
Thanks for looking into this!
