### ISSUE TITLE
Text-Labels should always be be hidden if on the backside of the globe.

### ISSUE THREAD

**Issue by zerda-ocm** [maplibre/maplibre-gl-js#4802]
**maplibre-gl-js version**: 5.0.0-pre.1

**browser**: Edge, Chrome

### Steps to Trigger Behavior

 1. set projection to globe
 2. set "text-allow-overlap" to true or "text-overlap" to "always" on symbol layers

### Link to Demonstration

https://jsbin.com/quluxolemo/edit?html,output

### Expected Behavior

Labels on the back of the globe are hidden

### Actual Behavior

Labels on the back of the globe are displayed as if they are in front of the globe. For example Taiwan is written over Kanada.

![Screenshot 2024-10-05 130643](https://github.com/user-attachments/assets/86da9130-9838-4480-a6ac-d467d63e2fef)

Maybe there should be an option for both behaviours, in case someone wants to have a transparent globe.

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue! 
Style spec changes are harder to nail down, but I think the default should be not presenting label on the back side of the globe. 
Later on we can decide if there is a user case for presenting them and what definition to add.
