### ISSUE TITLE
Memory leak on map.remove()

### ISSUE THREAD

**Issue by elo58** [maplibre/maplibre-gl-js#4811]
hello, 

I have a website where several pages contain a maplibre map. It's a SPA so maplibre-gl.js is not unloaded/reloaded for each map. Maps are created and destroyed over the navigation.
I have issues with memory consumption which increase each time i create and then destroy a map.

My work is based on maplibre 4.1 but i have also tested with maplibre 4.7.1 and the issue is the same (may be a little better with 4.7.1)

**maplibre-gl-js version**: 4.7.1

**browser**: Chrome 128 / linux

### Steps to Trigger Behavior

 1. map = new maplibregl.Map({ ... })
 2. map.remove()
 3. monitor memory consumption

### Link to Demonstration
I have wrote a sample code to reproduce my problem : 
https://output.jsbin.com/vumugiroma
Each time you press 'space' key you create or destroy a map. 
The total used memory increase at each time (Check with Chrome task manager or memory in Devtools)

### Expected Behavior

Don't increase memory consumption after several creation and destruction of maps.

### Actual Behavior

Some objects are not released

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue!
Feel free to investigate further and open a PR to fix this. 
There is a lot of cleaning up code in map.remove method, but there might be places that were not handled properly.

**Comment by HarelM** [comment]
There's also this report, which has a root cause investigated already: 
- #4650

**Comment by kamil-sienkiewicz-asi** [comment]
@HarelM Hey, I've already fixed `map.remove()` memory leak in mapbox, maybe it's somewhat similar/in similar place?

https://github.com/mapbox/mapbox-gl-js/pull/13110
https://github.com/mapbox/mapbox-gl-js/pull/13116

Not aware of maplibre code yet, so I'm just guessing and throwing ideas.
Might take a look at it at some point.

**Comment by HarelM** [comment]
I can't look at the linked code since I don't want to infringe copyright laws, but you are more than welcome to tackle the memory leak in this lib.

**Comment by HarelM** [comment]
I've opened a PR to fix the relevant memory leak I observed using chrome devtools.
