### ISSUE TITLE
Make overzoom options configurable when adding the source

### ISSUE THREAD

**Issue by mshubin** [maplibre/maplibre-gl-js#4823]
## User Story

As a developer, when adding a source, I want to be able to specify overzoom options so that points with transparent opacity or clusters are rendered without showing leftover features from lower zoom levels.

## Rationale

We have optimized cluster rendering using Tippecanoe, but we're encountering some rendering issues.

[mvt_plateform_3_13_segment.webm](https://github.com/user-attachments/assets/a0492972-2591-43ac-bbaa-ce2173be57a8)

In the linked video, features from lower zoom levels are still visible when they shouldn't be. For example, the "rose" circles should disappear when the yellow ones appear at higher zoom levels. This creates clutter and confusion.

We found the solution by hardcoding the following values in maplibre-gl source code:
```
SourceCache.maxOverzooming = 0;
SourceCache.maxUnderzooming = 0;
``` 

[mvt_plateform_0_0_segment.webm](https://github.com/user-attachments/assets/39b20c41-c475-420e-9318-a1ac1e030fce)

This adjustment gave us the expected cluster rendering, with the exception of some glitches in background layers, which we can avoid if this feature request will be implemented.

Additionally, a similar issue occurs with isolated points that have transparent opacity, as seen in the first video. As zoom levels increase, points from lower levels accumulate, making the color less transparent. Unfortunately, I couldn't reproduce this issue in a live example, so we're unsure if this is due to a mistake in our use of the library, a bug, or if a feature request is warranted.

PS. Thank you for your amazing library!

**Comment by HarelM** [comment]
This sounds like something that you should be able to solve using layers, filters and source definitions, is this not the case? 
Can you share a minimal reproduction of the issue with the clusters?

**Comment by mshubin** [comment]
I've been able to reproduce the issue [here](https://jsfiddle.net/oeknxsL0/)

Curious fact: it works as expected with the pmtiles protocol, but when using the direct link to pbf tiles, the bug occurs :thinking:

**Comment by HarelM** [comment]
Thanks for taking the time to report back.
What is `imagery` source? Is it part of the pmtiles? in general, clustering only works for geojson source in the client side, so if you did the clustering by yourself, you should check that the data that is there is correct...

**Comment by HarelM** [comment]
I saw some error is the console when using the mvt tiles:
![image](https://github.com/user-attachments/assets/9e80b405-c56d-410a-b205-9f1b51bc7899)
I don't know if this is related, but it might be:
- https://github.com/maplibre/maplibre-gl-js/issues/4613

Did you try this with older version of maplibre? Maybe there was a regression bug introduced...?

**Comment by mshubin** [comment]
Great observation!

I've tested several versions, and it seems the regression for my issue was introduced with v4.0.0. So, it's clear to me that we can resolve the issue by either using the older version 3.6.2 or upgrading to at least 4.5.0.

Thank you very much for your help!
