### ISSUE TITLE
mapbox-gl-rtl-text v0.3.0 support

### ISSUE THREAD

**Issue by dbauszus-glx** [maplibre/maplibre-gl-js#4850]
We are loading maplibre-gl 4.7.1 dynamically from esm which works well.

This allows us to use the mapbox-gl-rtl-text@0.2.3 loaded from the unpkg cdn.

When we are trying to update the plugin to the latest version https://unpkg.com/@mapbox/mapbox-gl-rtl-text@0.3.0/dist/mapbox-gl-rtl-text.js we hit an error on plugin registration and arabix text is not displayed.

![image](https://github.com/user-attachments/assets/9778ac08-2cc8-4bc5-9347-54eebe1cea6a)

"RTL Text Plugin failed to import scripts from https://unpkg.com/@mapbox/mapbox-gl-rtl-text@0.3.0/dist/mapbox-gl-rtl-text.js"

This is not a big issue since 0.2.3 version is working as expected though I would like to understand the nature of the issue.

```js
  // Create promise to load maplibre from esm.sh
  if (!promise) promise = new Promise(async resolve => {

    try {

      const mod = await import('https://esm.sh/maplibre-gl@4.7.1')

      maplibregl = mod.default

      // Avoid loading RTL Text Plugin twice, else it will error
      if (!['deferred', 'loaded'].includes(maplibregl.getRTLTextPluginStatus())) {
        maplibregl.setRTLTextPlugin(
          'https://unpkg.com/@mapbox/mapbox-gl-rtl-text@0.2.3/mapbox-gl-rtl-text.min.js',
          true // Lazy load the plugin
        );
      }

      resolve()

    } catch {

      console.error('Failed to load maplibre-gl library.')
      resolve()
    }
  })
```

**Comment by HarelM** [comment]
I think version 0.3.0 is loading the method in a async manner, and the code expects it to run immediately.
I'm not sure I know how to solve this without a "sleep".
I'll look into it.
The code is here basically if you want to try and tackle this:
https://github.com/maplibre/maplibre-gl-js/blob/86ed382324ad605e6174b19da7bf2fc3de5b0904/src/source/worker.ts#L206

The following method is expected to call right await, but it doesn't in the new version:
https://github.com/maplibre/maplibre-gl-js/blob/86ed382324ad605e6174b19da7bf2fc3de5b0904/src/source/worker.ts#L85

**Comment by HarelM** [comment]
I've created a PR to fix this issue, any chance you can also test it on your end?

**Comment by dbauszus-glx** [comment]
Awesome. Thanks so much for picking this up quickly.
