### ISSUE TITLE
Sky shouldn't be visible on low zoom in Globe-Mercator projection

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#4853]
When using a globe, and going to a high pitch, the non-globe sky  is shown

Demo:
https://cartes.app/?style=transports&choix+du+style=oui#2.08/66.22/-14.38/47/85

<img width="939" alt="Screenshot 2024-10-18 at 00 21 59" src="https://github.com/user-attachments/assets/1ee10c93-97fc-46ed-920b-06bbde984ef0">

**Comment by HarelM** [comment]
I tent to think this is the sky. 
It us best to create a minimal reproduction as it's hard to understand what the style definition is in the linked site...

**Comment by birkskyum** [comment]
@laem can you help with a minimal repro of the sky issue seen here?

**Comment by birkskyum** [comment]
@HarelM , repro here :
https://codepen.io/birkskyum-1471370946/pen/mdNwGOo

**Comment by HarelM** [comment]
Thanks @birkskyum!
Globe still doesn't support sky well.
I've linked it in the v5 breaking change issue in order to see if this can be supported as well.

**Comment by ibesora** [comment]
What are the expectations here? Should we just disable sky? The current implementation tries to simulate sunlight on the earth but that doesn't obviously work on globe

**Comment by laem** [comment]
Thanks for the issue. I've had some problems understanding the sky spec. 

I'm still very happy with the globe feature.

**Please note that the capture in the initial issue body is a heavily tilted view**, as shown by this GIF. 

![Recording 2024-10-21 at 14 57 18](https://github.com/user-attachments/assets/70c00e82-7687-40b6-8c35-254b646cd01c)

**Comment by birkskyum** [comment]
@ibesora , you've got me thinking about this twice. Since the sky simulate the scattering through the atmosphere, it only really makes sense to show when the camera is close to the globe (underneath the atmosphere), and could be removed on lower zoom in globe mode. What I'm missing is maybe more the sky-box (like stars) and some sort of glow around the globe, but it's arguably a different feature altogether.
