### ISSUE TITLE
Basic TypeScript project with MapLibre fails to compile without skipLibCheck set to true

### ISSUE THREAD

**Issue by JamesLMilner** [maplibre/maplibre-gl-js#4855]
When building a simple TypeScript project that uses MapLibre GL on my local macOS machine, I am unable to build it without skipLibCheck being set to `true` in `tsconfig.json`. Weirdly, I cannot reproduce this on GitHub CodeSpaces (see the repository below), which makes me think it may be related to the environment in some way. I appreciate this issue seems quite niche, but perhaps it is affecting others so thought I would create it any way.

**maplibre-gl-js version**: 4.7.1

**browser**: Node, build time error

### Steps to Trigger Behavior

 1. Create a fresh TypeScript project with MapLibre GL installed, i.e. a `package.json` like this:
 
 ```json
{
  "name": "maplibre-tsc-example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build:tsc": "tsc"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "typescript": "^5.6.3"
  },
  "dependencies": {
    "maplibre-gl": "^4.7.1"
  }
}
```

2. Create an entry point like `src/index.ts` with very simple Maplibre GL code:

```typescript 
import maplibregl from 'maplibre-gl'

const map = new maplibregl.Map({
    container: 'map',
    style: 'https://maps.geoapify.com/v1/styles/osm-carto/style.json',
    center: [0, 0],
    zoom: 2,
})
```

 3. Run Typescript compilation:

```shell
npm run build:tsc
```

### Link to Demonstration

Here's a reproduceable GitHub repo:

https://github.com/JamesLMilner/maplibre-tsc-skiplibcheck

CodeSpace:

https://[verbose-palm-tree-766xj55vr53r59v.github.dev](https://verbose-palm-tree-766xj55vr53r59v.github.dev/)/

### Expected Behavior

The basic MapLibre / TypeScript file compiles without TypeScript error, unless `skipLibCheck: true` is set. (see [the docs page for skipLibCheck for more info on what it does](https://www.typescriptlang.org/tsconfig/skipLibCheck.html). Ideally it shouldn't have to be set if the types are correct for a library.

### Actual Behavior

The following error is given:

```shell
> maplibre-tsc-example@1.0.0 build:tsc
> tsc

../../node_modules/@types/css-font-loading-module/index.d.ts:22:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'display' must be of type 'FontDisplay | undefined', but here has type 'string | undefined'.

22         display?: string | undefined;
           ~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:557:5
    557     display?: FontDisplay;
            ~~~~~~~
    'display' was also declared here.

../../node_modules/@types/css-font-loading-module/index.d.ts:42:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'display' must be of type 'FontDisplay', but here has type 'string'.

42         display: string;
           ~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:8609:5
    8609     display: FontDisplay;
             ~~~~~~~
    'display' was also declared here.


Found 2 errors in the same file, starting at: ../../node_modules/@types/css-font-loading-module/index.d.t
```

It appears there is some sort of type conflict between `lib.dom.d.ts` and `css-font-loading-module`.

I tried installing `@types/css-font-loading-module` but it appears to result in even more errors:

```shell

node_modules/@types/css-font-loading-module/index.d.ts:44:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'onloading' must be of type '(this: FontFaceSet, ev: Event) => any', but here has type '(this: FontFaceSet, event: FontFaceSetLoadEvent) => any'.

44         onloading: ((this: FontFaceSet, event: FontFaceSetLoadEvent) => any) | null;
           ~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:8646:5
    8646     onloading: ((this: FontFaceSet, ev: Event) => any) | null;
             ~~~~~~~~~
    'onloading' was also declared here.

node_modules/@types/css-font-loading-module/index.d.ts:45:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'onloadingdone' must be of type '(this: FontFaceSet, ev: Event) => any', but here has type '(this: FontFaceSet, event: FontFaceSetLoadEvent) => any'.

45         onloadingdone: ((this: FontFaceSet, event: FontFaceSetLoadEvent) => any) | null;
           ~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:8648:5
    8648     onloadingdone: ((this: FontFaceSet, ev: Event) => any) | null;
             ~~~~~~~~~~~~~
    'onloadingdone' was also declared here.

node_modules/@types/css-font-loading-module/index.d.ts:46:9 - error TS2717: Subsequent property declarations must have the same type.  Property 'onloadingerror' must be of type '(this: FontFaceSet, ev: Event) => any', but here has type '(this: FontFaceSet, event: FontFaceSetLoadEvent) => any'.

46         onloadingerror: ((this: FontFaceSet, event: FontFaceSetLoadEvent) => any) | null;
           ~~~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:8650:5
    8650     onloadingerror: ((this: FontFaceSet, ev: Event) => any) | null;
             ~~~~~~~~~~~~~~
    'onloadingerror' was also declared here.


Found 3 errors in the same file, starting at: node_modules/@types/css-font-loading-module/index.d.ts:44
```

**Comment by HarelM** [comment]
We are checking our typescript definitions using strict in our build to make sure this won't happen to our users. 
Looking at the above errors this doesn't look like it's coming from this library...
Looks like an issue with css-font-loading-module.

**Comment by JamesLMilner** [comment]
@HarelM thanks for getting back to me here - turns out this was an environment issue on my side where a package.json file had been erroneously placed in the folder above and was causing trouble. The issue went away on removing it, and as such I think we can close the issue.
