### ISSUE TITLE
Polygon vertices render with circles after setFilter()

### ISSUE THREAD

**Issue by jmou** [maplibre/maplibre-gl-js#4896]
**maplibre-gl-js version**: 4.7.1

**browser**: Chromium, Firefox

Hi I've run into this issue which appears to be a bug. When I set a filter on a layer of points, it seems to draw that style over my layer of polygons also. It doesn't seem to matter what the filter is (this example just unsets it). The layers share the same source data but filter by geometry-type.

### Steps to Trigger Behavior

 1. Go to the link below
 2. Click "filter point"

### Link to Demonstration
https://jsbin.com/zedejarico/edit?html,output

### Expected Behavior
Polygon renders a simple triangle.

### Actual Behavior
The triangle is rendered but each vertex now has a circle as well.

**Comment by neodescis** [comment]
This appears to me to be working as intended. A circle layer will render vertices for polygons unless filtered out by type, as you have done in the initial state of your example. When the click action removes the filter, then circles are rendered for the polygon vertices in addition to the other point.

**Comment by jmou** [comment]
Oh I see! I misunderstood how layers worked. I agree this is working correctly. Thanks for helping me understand!
