### ISSUE TITLE
Possible to allow setting `MercatorTransform` > `pixelsToGLUnits`?

### ISSUE THREAD

**Issue by wagewarbler** [maplibre/maplibre-gl-js#4898]
#3963 Swaps out `Transform` for `MercatorTransform`, and is a huge step in the right direction! :fireworks: That said, it changed the shape of the map transform to not allow direct modification of `pixesToGLUnits` breaking support in downstream libs like [react-map-gl]( https://github.com/visgl/react-map-gl/blob/7a415a443a0056b43c3fb089c0681b2f98b895b4/src/utils/transform.ts#L12) for instance. Would it be possible to allow the same sort of assignment in the new API or will this require downstream updates?

**Comment by HarelM** [comment]
5.0 is a breaking change version. 
Manipulating the trasform object is not advised for the reason you just mentioned, it's not part of the public API.
My advise would be to define what's needed in terms of public API to support the relevant functionality.
