### ISSUE TITLE
projection setting on map object (outside style)

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#4909]
## User Story

I'd like to be able to set a projection on my map, and change style at will.

## Rationale

If i have a style object, then I can apply the projection directly with a spread, or by editing the object before setting the style:

`GoogleSatStyle.projection = { type: 'globe' } `
or
`style: { ...GoogleSatStyle, projection: { type: 'globe' } }`, 

If I have a style url, with or without api keys (like Positron "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json"), then it's more tedious, because I'd have to download the style, then editing it, and then setting it like above, every time setStyle is called, like:

```
async function downloadStyleObject(url: string) {
    return await fetch(url)
	.then((response) => response.json())
	.then((data) => data)
	.catch((error) => {
		console.error("Error fetching or parsing JSON:", error);
		return null;
	});
}
```
and then the same as prior

`style: {...(await downloadStyleObject(getBasemap())), projection: {type:'globe'}}`

## Impact

It would be an override, so if it's not set there is no impact

**Comment by HarelM** [comment]
Thanks for opening this issue! Yes I had the same thoughts and added it to the v5 issue. 
Feel free to open a PR to solve this, should be fairly simple I believe.

**Comment by birkskyum** [comment]
@HarelM , I'm a bit hesitant here, because i'm unsure if the `projection` is just the latest symptom on a need for a more generic styleOverride.

My hesitation comes from cases like below link, where I'm loading a maptiler satellite layer, for the tile service, and then have a need to manipulate the style projection, layers, sources, terrain, sky etc. afterwards.

https://github.com/maplibre/maplibre-gl-js/blob/01cbe7af5a206a2e7bce1cecafdd6b95063c3ba6/test/examples/globe-3d-terrain-satellite.html

**Comment by HarelM** [comment]
You can supply a style diff method, this already exists right now.
https://maplibre.org/maplibre-gl-js/docs/API/type-aliases/TransformStyleFunction/

**Comment by HarelM** [comment]
No, style URL is not part of the `StyleSpecification` definitions, but you probably find some info in the metadata.
Aslo, these 5 lines of code to manipulate a fetched style are not something that complicated to write if one needs a more complicated scenario...
