### ISSUE TITLE
The unsupported Fog/Horizon is isn't disabled properly on Globe with Terrain3D

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#4928]
Repro here:
- #4926 

Changing the pitch will remove all texture, resulting in a white screen:

https://github.com/user-attachments/assets/25a589f3-a148-4a23-a108-84f977ab0a47

**Comment by kubapelc** [comment]
This also happens with mercator projection. I've noticed this a while back and tried to find when this bug got introduced. It has something to do with the big transform refactor around june. I'll try to debug this further.

**Comment by birkskyum** [comment]
on a raster tile layer, it give negative colors:

https://github.com/user-attachments/assets/9ff48348-fd99-48a3-94c1-8845a0a0f13d

**Comment by birkskyum** [comment]
There's a link to the horizon-color. I tried setting it to red, and got this:

`'horizon-color': '#f00',`

https://github.com/user-attachments/assets/a4bdf2ab-9ed8-44b3-aeb0-c017b0985abf

**Comment by birkskyum** [comment]
Basically, if the terrain.fragment.glsl just returns `gl_FragColor = surface_color;` and disabled the fog, there is no issue, so it's strictly linked to that.

**Comment by birkskyum** [comment]
Reopened, because apaprently, if the `sky` isn't set in the style, this the terrain isn't rendered. Better fix in
- #4977
