### ISSUE TITLE
Raster satellite blurred in Terrain3D at vertical field of view < 15 deg 

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#4940]
**maplibre-gl-js version**:

d3f2bca19

**browser**:

Chrome on ubuntu

### Steps to Trigger Behavior

 1. go to https://jsbin.com/muvadukome/edit?html,output (uses latest main after #4914)
 2. move fov slider to 5 deg
 3. see how raster satellite get blurred

### Link to Demonstration

https://jsbin.com/muvadukome/edit?html,output

![image](https://github.com/user-attachments/assets/54435b71-f2e6-4620-a116-876a57a8f760)

### Expected Behavior

Raster satellite stays sharp also at low fov

### Actual Behavior

Raster satellite tiles are blurred

**Comment by HarelM** [comment]
CC: @NathanMOlson can you please check this?

**Comment by birkskyum** [comment]
Does it behave differently with these changes applied?
- https://github.com/maplibre/maplibre-gl-js/pull/4779

**Comment by NathanMOlson** [comment]
This looks like a tile selection problem. It looks a lot better in the `lodfix_globe` branch.

Left: main, right: lodfix_globe

<img width="958" alt="image" src="https://github.com/user-attachments/assets/584ca46b-031c-474c-907f-1f552181ef57">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/8c775674-1102-483c-a78e-185135eba442">
