### ISSUE TITLE
Atmosphere is visible at too high zoom

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#4952]
At very low zoom, the atmosphere is quite nice:

<img width="1051" alt="Screenshot 2024-10-31 at 23 56 35" src="https://github.com/user-attachments/assets/75206ad1-5f1b-4ebe-9a41-4177fcd7abd7">

At higher zoom, but long before transitioning to mercator, the atmosphere around the globe starts to be problematic, like a black overlay the globe, and it would be best to remove it before this zoom level is reached:

<img width="1670" alt="Screenshot 2024-10-31 at 23 57 33" src="https://github.com/user-attachments/assets/2bfda604-38ff-446c-b337-5d02c284d58b">

zooming just a bit further in, it is removed, while the projection is still a glove, so can the zoom for this transition simply be lowered further?
<img width="1644" alt="Screenshot 2024-10-31 at 23 59 56" src="https://github.com/user-attachments/assets/ac730c45-345c-4df2-8265-6ee8c66dc4e0">

**Comment by HarelM** [comment]
I think you can define it as you see fit, see the atmosphere blend: 
https://maplibre.org/maplibre-style-spec/sky/

**Comment by birkskyum** [comment]
Ah, that's great, did get it was in the style. Will look into it.
