### ISSUE TITLE
Globe: Flickering and missing layers when panning/zooming

### ISSUE THREAD

**Issue by zerda-ocm** [maplibre/maplibre-gl-js#5025]
**maplibre-gl-js version**: 5.0.0-pre.6

**browser**: bing, chrome

### Steps to Trigger Behavior

 1. create a vector map with line layers
 3. set projection to globe 
 3. zoom or move around

### Link to Demonstration

https://jsbin.com/zusijan/edit?html,output

https://github.com/user-attachments/assets/933bf854-c75a-483b-a4c9-c51784c16840

### Expected Behavior

No flickering and complete drawing of layers.

### Actual Behavior

This bug is apparently present since the merge of https://github.com/maplibre/maplibre-gl-js/issues/3983

**Comment by birkskyum** [comment]
It says `pmtiles` not defined. Maybe there's a script tag missing?

**Comment by HarelM** [comment]
You have linked an issue and not a PR. The relevant PR is:
https://github.com/maplibre/maplibre-gl-js/pull/4779

Please create a minimal reproduction of this issue, as the linked jsbin contains a lot of complicated logic around tile loading...

**Comment by HarelM** [comment]
Cc: @NathanMOlson

**Comment by zerda-ocm** [comment]
> Please create a minimal reproduction of this issue, as the linked jsbin contains a lot of complicated logic around tile loading...

https://jsbin.com/jakoxob/edit?html,console,output

**Comment by HarelM** [comment]
This style still has too many layers, can you simplify it, and hopefully revive the PMTiles related code (as those can introduce noise)?

**Comment by birkskyum** [comment]
as a sidenote - I don't understand where the js bin get the pmtiles script tag injected. I can execute the example in jsbin, but not locally yet, which makes it harder for me to debug

**Comment by birkskyum** [comment]
It looks a lot like z-fighting to me.

**Comment by birkskyum** [comment]
Do we see issues only with the `line` layer?

**Comment by zerda-ocm** [comment]
> This style still has too many layers, can you simplify it, and hopefully revive the PMTiles related code (as those can introduce noise)?

I will try to replicate this with some geojson, but that will take some time.

**Comment by zerda-ocm** [comment]
> Do we see issues only with the `line` layer?

I haven't seen this issue with other layer types.

**Comment by russss** [comment]
I'm also seeing this issue on OpenInfraMap, which isn't using PMTiles. I believe it's only happening on line layers.

**Comment by birkskyum** [comment]
I do see some flickering in `mercator` projection too:

https://github.com/user-attachments/assets/280e4b91-49cc-4031-b2f6-137460031a64

**Comment by zerda-ocm** [comment]
Demo with geojson as a source and less line-layers.
https://jsbin.com/novugaxewo/edit?html,console,output

Less geometry and layers seemingly makes it a little bit harder for the bug to show up, but zooming in on one of the lines should work.

**Comment by HarelM** [comment]
Can you add a video of the problem in the latest shared jsbin? I'm not sure I can't see the issue...

**Comment by birkskyum** [comment]
I zoomed in quite far, and got this:

https://github.com/user-attachments/assets/39677ce7-ff2b-43c1-99c9-d2fa08adbd6a

**Comment by HarelM** [comment]
Thanks @birkskyum for the video!

**Comment by HarelM** [comment]
@NathanMOlson any updates on this? Any change you could take a look and think what might have caused this regressions?

**Comment by NathanMOlson** [comment]
I don't know what's going on here.

I can only get this to manifest at pitch > 60 or with terrain, which makes me think it is related to the variation of tile zoom.

This picture shows that the issue starts/ends at tile boundaries:
![Image](https://github.com/user-attachments/assets/30873a3e-905c-47bc-9b92-926d0db0bd89)

Maybe this is related to the fact that starting in 5.0.0-pre.6, sometimes tiles from different sources are using different zoom levels, as you can see in this picture:
![Image](https://github.com/user-attachments/assets/e01eb679-6704-4abc-b71e-08c725fe3ecc)

I don't know why this is, I expect all sources (as long as they are the same tileSize, and not used for terrain) to use the same zoom for each tile.

Making a set of vector debug tiles might help troubleshooting this issue.

**Comment by NathanMOlson** [comment]
This issue seems to disappear when terrain is enabled.

**Comment by kubapelc** [comment]
When I disable stencil test on the line layer the flickering stops. It seems that it might be an issue with the stencil mask. But I have no idea why fill layer seems to be unaffected, because since the merge of #4868 fill also uses the stencil mask again.

**Comment by NathanMOlson** [comment]
When I make the lines and raster tiles semi-transparent, the missing blue lines do not appear. So it seems like they are gone altogether, not being drawn under the other lines.

![Image](https://github.com/user-attachments/assets/330ea95a-b8ce-4989-863b-88df6e959218)

**Comment by HarelM** [comment]
It's worth noting that the source is a single geojson source and all the layers are line layers, so it's strange that some are drawn and other aren't...
Having said that, when I removed the "base map" the issue does not manifest, which is also weird...

**Comment by ibesora** [comment]
> It seems that it might be an issue with the stencil mask.

This seems to be the case and it matches it working with terrain enabled since we use another stencil setting when that happens.
I'll keep digging

**Comment by kubapelc** [comment]
@ibesora Very nice!
