### ISSUE TITLE
3D model added using Three.js not visible in Custom Layer

### ISSUE THREAD

**Issue by alexaac** [maplibre/maplibre-gl-js#5032]
**maplibre-gl-js version**: 5.0.0-pre.6

**browser**: Firefox

### Steps to Trigger Behavior

 1. Add a custom layer following the example from the website
 2. Change the Maplibre GL Js version
 3. Refresh the page

### Link to Demonstration

Working : https://codesandbox.io/p/sandbox/goofy-pike-3vd26f

Not working: https://codesandbox.io/p/sandbox/kgpk7d

### Expected Behavior
The 3D model should be visible.

### Actual Behavior
The 3D model is not visible.

**Comment by HarelM** [comment]
In version 5 we have changed how custom layer works, can you check if the example currently in main branch does not work?

**Comment by HarelM** [comment]
I mean that the docs are using version 4.7, which is compatible with how version 4.7 works, version 5.0 is working a bit differently...

**Comment by alexaac** [comment]
I will check the latest examples; thanks. I have used the example from here: https://maplibre.org/maplibre-gl-js/docs/examples/add-3d-model/

**Comment by alexaac** [comment]
It works now. I've upgraded the code using the 'Add a 3D model with shadow using three.js' example. I suppose you've made those changes to accommodate the new 'globe' projection. Thanks

https://codesandbox.io/p/sandbox/pensive-water-zg24r3

**Comment by alexaac** [comment]
Hi @HarelM, 

The model is displayed correctly when using the 'Mercator' projection.
What changes must we make to display the model when using the 'Globe' projection?
Should we add the Earth radius to the z value, like we do when we add a 3D model to a terrain? (Eg, https://stackoverflow.com/a/77571101)

https://codesandbox.io/p/sandbox/elastic-sammet-g59fwy?workspaceId=ws_Sow94516aNZKmsqkDWJ6Wp

**Comment by kubapelc** [comment]
Hi, see the example `globe-3d-model.html`. The code there should work in either projection.

But note that the API will change slightly before the main release, and that custom layer 3D models on globe are somewhat broken in the current prerelease. There is already a PR that fixes it and has the updated API, see #5150 . In particular it fixes the model disappearing when globe transitions to mercator at high zooms and the model disappearing during the transition itself.

**Comment by alexaac** [comment]
Thanks, @kubapelc, it works now: https://codesandbox.io/p/sandbox/vigilant-murdock-2clsvy?workspaceId=ws_Sow94516aNZKmsqkDWJ6Wp
