### ISSUE TITLE
Incorrect cooperative gestures help text in iFrames

### ISSUE THREAD

**Issue by timsluis** [maplibre/maplibre-gl-js#5052]
When embedding a map in an iFrame, the cooperative gestures feature incorrectly displays the MobileHelpText when the iFrame width is smaller than 480px, regardless of the parent page's width or whether the user is on a desktop device.

**maplibre-gl-js version**: 4.7.1

**browser**: Arc 1.67.2 

### Steps to Trigger Behavior

1. Embed a map in an iFrame on another website and set the iFrame width to less than 480px.
2. Attempt to scroll within the map in the iFrame.
3. Notice the help text displayed.

### Expected Behavior

The desktop help text for cooperative gestures should appear when the device is not mobile, even if the iFrame is narrow.

### Actual Behavior

The mobile help text for cooperative gestures appears when the iFrame width is under 480px, even on desktop devices.

### Possible solutions

- Update the CSS media query: Replace (width <= 480px) in maplibre-gl.css with a more accurate condition, such as (pointer: coarse), to detect mobile devices.
- Handle logic in JavaScript: Modify ui/handler/cooperative_gestures.ts to detect mobile devices programmatically and dynamically update the help text, similar to how the CMD key is checked for macOS/Windows differentiation. This approach eliminates the need for the CSS media query.

**Comment by timsluis** [comment]
If we can agree on a possible solution, I’m happy to work on a pull request to implement it.

Let me know your thoughts!

**Comment by HarelM** [comment]
Which ever of the two you feel is "the right one".
I think both options are fine. Css seems easier to me.
