### ISSUE TITLE
Projection expression support

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#5056]
There's a number of things that has to happen before the style.projection.type can be used fully as an expression to replace the hardcoded zoom stops of `globe`.

It's in the MapLibre Style Spec, released per 22.0.0
- https://github.com/maplibre/maplibre-style-spec/pull/899
- https://github.com/maplibre/maplibre-style-spec/pull/909

Then GL JS needs to update, which Dependabot will do, allowing createExpression to work with projections
- #5061 

**Blockers** - A number of refactors has to take place, before the expressions can be hooked up to the map style
- The globe projection should have a way to adjust globeness from the outside
- The Projection.name probably should not be used inside of Painter
- #4985

**Comment by HarelM** [comment]
I believe this can be closed as it's not related to fog support.
- Resolved by #5139.
