### ISSUE TITLE
Performance degradation in render time in 5.0.0 version

### ISSUE THREAD

**Issue by kamil-sienkiewicz-asi** [maplibre/maplibre-gl-js#5070]
4.7.1 render time:
![image](https://github.com/user-attachments/assets/90f24ae8-cd52-4bbe-a711-651a5c951905)

Chrome dev tools buffer usage:

![image](https://github.com/user-attachments/assets/2a2c3025-715e-4cd3-9dd4-1a8c72066f05)

5.0.0-pre.6 render time:

![image](https://github.com/user-attachments/assets/9dc72e10-f5b5-4302-992c-1d3788699acf)

Chrome dev tools buffer usage:

![image](https://github.com/user-attachments/assets/39a8f64b-b0d2-4c42-9dbe-3cade7ffb522)

Notice how buffer differs, 47 seconds and it's almost empty vs 4 seconds and it's full. Both tests are done in mercator projection.

**maplibre-gl-js version**: 5.0.0-pre6 but seems like every 5.0.0 has this issue

**browser**: Google Chrome Version 130.0.6723.117 (Official Build) (arm64)

### Steps to Trigger Behavior

 1. Open codesandbox, go to console -> performance -> start recording
 2. Move map for a second or two, stop recording
 3. Version 5.0.0 takes ~10x longer to render and fills dev tools buffer usage immediately.

### Link to Demonstration

https://codepen.io/kamil-sienkiewicz-asi/pen/qBeGYaJ?editors=1010

### Expected Behavior

Render time takes around ~1ms with basic layers from demotiles

### Actual Behavior

Render time takes from ~9ms to ~30ms with same layers from demotiles

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue.
We'll try and look into it, but feel free to dig into it as well, we'll need any help we can get...

**Comment by HarelM** [comment]
CC: @ibesora @kubapelc

**Comment by kubapelc** [comment]
I think this might be related to passing float64 matrices to WebGL. Almost all time is spent inside `glUnifomMatrix4fv`, which is very similar to what I saw when I first noticed that there is a perf difference between float32 and float64. Later I couldn't replicate it, but I guess I was only trying it in Firefox.

I will investigate further.

**Comment by kubapelc** [comment]
I think it was the float64 matrices, after conversion to float32 I no longer see the very fast Chrome buffer fillup and `glUniformMatrix4fv` no longer shows up in the profile.

@kamil-sienkiewicz-asi please confirm that the issue is also resolved on your machine. Patched demo:

https://codepen.io/kubapelc/pen/poMmZbz?editors=1010

I will create a PR if this works.

**Comment by kamil-sienkiewicz-asi** [comment]
Hey @kubapelc , yep, seems like it did the trick, nice! Render time went down to ~1ms
<img width="264" alt="image" src="https://github.com/user-attachments/assets/e923030e-2940-4aa9-99f0-11cf22315eab">
