### ISSUE TITLE
Images in symbol features with placement other than "point" get scaled when moving the globe around the poles

### ISSUE THREAD

**Issue by JakubJagoda** [maplibre/maplibre-gl-js#5090]
**maplibre-gl-js version**: 5.0.0-pre.7
_EDIT: I originally created this issue against version 5.0.0-pre.6, but then I noticed that 5.0.0-pre.7 was out, so checked against it as well and updated the description._

**browser**: Chrome 131.0.6778.85 (Official Build) (arm64) / Firefox 132.0b9 (aarch64)

### Steps to Trigger Behavior

 1. Create map with globe projection
 2. Add a symbol layer rendering an image with `symbol-placement` set to value other than `"point"`
 3. Move the globe so that one of the poles is in the center

### Link to Demonstration
https://codepen.io/kuba-jagoda-asi/pen/YzmojqQ

### Expected Behavior
The rendered image should visually retain its size

### Actual Behavior
The image gets scaled up way too much

### Some more info
It seems that this was also enlarging texts, but has been fixed somewhere between 5.0.0-pre.1 and 5.0.0-pre.6 (if you change the version to 5.0.0-pre.1 in the pen and repeat the steps, you'll see that the text was also scaled. This doesn't happen on 5.0.0-pre.6). This + the fact that it doesn't happen in Mapbox (example for reference: https://codepen.io/kuba-jagoda-asi/pen/JjgQBJE?editors=1010) makes be believe that it's not intended, but rather a bug.
Changing layer's `symbol-placement` to `point` prevents this from happening. So does changing `icon-pitch-alignment` to `"viewport"`. But both render the layer in a bit different way (the image is not "sticked" to the globe anymore, but rather faces the camera).
Here's some images to quickly show what I'm talking about:

Maplibre 5.0.0-pre.6 (notice the large gray trapezoid):
![Image](https://github.com/user-attachments/assets/aebba4dd-3aa4-46bd-93cf-633a727e63be)

Mapbox (the image remained non-scaled):
![Image](https://github.com/user-attachments/assets/861edcb3-c7ad-4cd7-8159-06c2775cc1b0)

Maplibre 5.0.0-pre.1 (where text also got scaled - but this was fixed):
![Image](https://github.com/user-attachments/assets/6cde1521-802f-4b66-8129-db02c9f2c5f4)

**Comment by HarelM** [comment]
I'm guessing you are referring to this issue, right?
- #4786

Which was fixed by the following PR as part of pre.5
- #4925

CC: @kubapelc

**Comment by JakubJagoda** [comment]
@HarelM yeah, I guess that was the issue for text. But just to be sure we're on the same page - this issue is about image. I only mentioned the text, because seeing it suffered the same problem and being fixed at some point, confirms to me that what I'm seeing with image is indeed a bug.

**Comment by HarelM** [comment]
Sure, sure, I'm expecting a similar solution, that's why I mentioned it.

**Comment by pcardinal** [comment]
The following code line in draw_symbol.ts
const alongLine = rotationAlignment !== 'viewport' && layer.layout.get('symbol-placement') !== 'point';

is part of the problem. If alongLine is set to false then everything seams ok but it will not be as simple because alonLine is used several times in the drawLayerSymbols() function.

**Comment by HarelM** [comment]
@ibesora is currently working on a fix. Thanks for your patience...
