### ISSUE TITLE
GeoJSON layers not behaving as expected when using `["geometry-type"]`

### ISSUE THREAD

**Issue by dschep** [maplibre/maplibre-gl-js#5103]
When looking into the impact of maplibre/maplibre-style-spec#519 on [Ultra](https://gitlab.com/TrailStash/ultra) which makes heavy use of GeoJSON sources, I discovered that geojson-vt transforms all single geometry types into multis. This manifests as a bug in MapLibre GL JS.

**maplibre-gl-js version**: v5 & v4, probably all?

**browser**: All

### Steps to Trigger Behavior

 1. Make a GeoJSON source containing MultiPoints and Points (applicable to [Multi]LineString and [Multi]Polygon geometries too)
 2. Add a layer using `["geometry-type"]` to style Points and MultiPoints differently
 3. In v4 all [Multi]Points are rendered as points and in v5 all re rendered as MultiPoints

### Link to Demonstration
* v4: https://glitch.com/edit/#!/geometry-type-bug-v4?path=index.html
* v5: https://glitch.com/edit/#!/geometry-type-bug-v5?path=index.html
* expected behavior, faked by including geometry type as a property: https://glitch.com/edit/#!/geometry-type-bug-expected?path=index.html

### Expected Behavior

![Image](https://github.com/user-attachments/assets/76e09bc1-2040-44bc-9213-525a394c7070)

#### v4

![Image](https://github.com/user-attachments/assets/1be6cd78-fabe-4486-8e8f-85495f947143)

#### v5

![Image](https://github.com/user-attachments/assets/7e463e6d-00a8-4528-8b4d-3045559022f1)

**Comment by HarelM** [comment]
I've checked this locally, I'm still struggling with multipolygon, but otherwise the rest of the stuff looks good.
Note that it looks like geojson-vt is flattening the multi stuff in case they are not needed (probably to improve performance).
If your multi point is more than one point, it should work, I don't know how to categorize this honestly...
See here:
https://jsbin.com/vuguyuvili/2/edit?html,output

**Comment by HarelM** [comment]
Your example still has a multipoint with one point.
This is what I think causes your confusion (I fully understand why this can be confusing).
If you change the content of the geometry of multipoint to be more than one point you'll see that it behaves as expected.
As I said above, I guess that the geojson conversion is optimizing to look at the content of the geometry.

**Comment by HarelM** [comment]
I see your point now, the filter is not acting as it should be.
The text field is working as expected though as far as I can tell...
I'll update my jsbin,

**Comment by HarelM** [comment]
I think the bug is here:
https://github.com/maplibre/maplibre-style-spec/blob/40f6fe71dcb0b24527ad45e88c2648d3624c8d4e/src/expression/compound_expression.ts#L464C27-L464C47

Filters are converted to special use case for some reason (probably an historic one... :-/)

**Comment by HarelM** [comment]
@dschep if you have a way to test my fix it would be great to see if I didn't miss anything (this is in the style spec repo right now).
See here:
- https://github.com/maplibre/maplibre-style-spec/pull/924

**Comment by dschep** [comment]
I'll test as soon as I can, but that probably won't be today 🦃
