### ISSUE TITLE
map.easeTo does not save padding in globe projection

### ISSUE THREAD

**Issue by kamil-sienkiewicz-asi** [maplibre/maplibre-gl-js#5133]
I want to be able to smoothly set padding for map (use case where im opening panel from the left side and want globe to be centered in visible space between floating HTML elements), it works fine in mercator projection, however in globe projection seems like `easeTo` does nothing, padding remains the same.

**maplibre-gl-js version**: 5.0.0-pre.8

**browser**: Google Chrome Version 131.0.6778.86 (Official Build) (arm64)

### Steps to Trigger Behavior

 1. Call map.easeTo() with padding in globe projection

### Link to Demonstration
https://jsbin.com/hihisehaku/edit?html,css,js,output

![Image](https://github.com/user-attachments/assets/53580a90-654e-4862-b1a5-512da2ae66e5)

### Expected Behavior

map.easeTo({padding:{}}) will smoothly add padding to map

### Actual Behavior

map.easeTo({padding:{}}) does nothing in globe projection

**Comment by pjamessteven** [comment]
possibly related to https://github.com/maplibre/maplibre-gl-js/issues/4891
