### ISSUE TITLE
Add powerPreference support to MapLibre GL

### ISSUE THREAD

**Issue by alexkn80** [maplibre/maplibre-gl-js#5135]
**Description:**  
Currently, MapLibre GL does not allow direct configuration of the `powerPreference` attribute, which is part of the WebGL context creation settings. This feature is essential for optimizing performance and energy efficiency on various devices, such as mobile phones or laptops.  

In particular, some Intel-based MacBook Pro models experience significant performance degradation when `powerPreference` is not explicitly set to `high-performance`. Allowing developers to configure this setting directly would help mitigate such issues.  

**Proposed solution:**  
Add a new `powerPreference` option to the `Map` constructor. This option would directly influence the WebGL context creation and allow developers to optimize their application's performance based on their specific needs.  

Example usage:  

```javascript
const map = new maplibregl.Map({
  container: 'map',
  style: 'https://demotiles.maplibre.org/style.json',
  center: [0, 0],
  zoom: 2,
  powerPreference: 'high-performance', // Optional: 'default' | 'low-power'
});
```  

**Expected behavior:**  
- If `powerPreference` is provided, MapLibre GL passes it to the WebGL context during initialization.  
- If not specified, the default browser behavior (`default`) is used.  

**Benefits:**  
- Improves usability for developers by providing a clear and direct way to control GPU performance preferences.  
- Enhances support for power-sensitive devices and applications requiring high-performance rendering.  
- Mitigates performance issues on Intel-based MacBook Pro models by enabling explicit GPU preference.  

**References:**  
- [[MDN WebGLRenderingContext](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext)](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext)  
- [[WebGL Specification](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2)](https://www.khronos.org/registry/webgl/specs/latest/1.0/#5.2)  
- Related closed PR: [[Add powerPreference to Map options #2213](https://github.com/maplibre/maplibre-gl-js/pull/2213)](https://github.com/maplibre/maplibre-gl-js/pull/2213)  

**Additional context:**  
Many modern web applications need to balance between performance and energy efficiency. Adding `powerPreference` as a standalone option aligns MapLibre GL with current WebGL best practices and addresses performance bottlenecks on specific hardware, such as Intel-based MacBook Pro models.

**Comment by HarelM** [comment]
I belive so, yes.

**Comment by alexkn80** [comment]
Sounds like a breaking change. Plus, at first glance, I don't see any other WebContext attributes that would need to be moved to the MapLibre settings. There aren't many attributes there anyway. :) Maybe a simpler and less disruptive solution would be to add a setting at the top level, as was done in the closed PR. Ideally, just reopen the PR since everything is already implemented there as needed.

**Comment by HarelM** [comment]
It is a breaking change, but I want to future proof this part if other parameters will be needed...
We are in the middle of releasing a breaking change version so this is a good time to introduce suck a change.
