### ISSUE TITLE
recalculated zoom is not a number if scroll quickly (terrain)

### ISSUE THREAD

**Issue by kkokkojeong** [maplibre/maplibre-gl-js#5141]
**maplibre-gl-js version**: 4.7.1

**browser**: Chrome (macOS)

### Steps to Trigger Behavior

 1. [3D Terrain example](https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/)
 2. After map loaded, Do scroll **very quickly**.
 3. Errors occurs with empty screen.

As a result of debugging, **the recalculated zoom level** is Not A Number.

![Image](https://github.com/user-attachments/assets/3a6596bc-9456-4ccf-845c-c5938eeab82c)

### Link to Demonstration
- https://maplibre.org/maplibre-gl-js/docs/examples/3d-terrain/

### Expected Behavior
- After panning finished, It is rendered normally without errors.

### Actual Behavior
- ![Image](https://github.com/user-attachments/assets/dc81dac6-0a1b-4254-a983-e8f29b50f7b0)

**Comment by HarelM** [comment]
I think this was mentioned here:
https://github.com/maplibre/maplibre-gl-js/pull/4551#discussion_r1782227028

Can you check if this issue also happens in latest pre-release version?

**Comment by kkokkojeong** [comment]
In lastest 5.0.0-pre.8 version, It isn't happens. 

I close this issue that has been resolved. Thanks for your checking.
