### ISSUE TITLE
how to show a line cuted off a short piece at begin or end 

### ISSUE THREAD

**Issue by roshomon** [maplibre/maplibre-gl-js#5146]
In maplibre, is there any way to draw a line that's shorter than its actual length in pixel unit, just like [CIMGeometricEffectCut in ArcGIS Maps SDK for js](https://developers.arcgis.com/javascript/latest/api-reference/esri-symbols-CIMSymbol.html#CIMGeometricEffectCut), 
Any reply would be greatly appreciated!

**Comment by HarelM** [comment]
There is the dash-array and line-pattern
See here for example: 
https://maplibre.org/maplibre-style-spec/layers/#line-dasharray
Let me know if this is what you were looking for.

**Comment by roshomon** [comment]
thanks for reply!
just like this 
![Image](https://github.com/user-attachments/assets/0c70e19c-6e80-4ff1-adcd-e6340082a673)
dash-array cannot cut only in begin and end. 
Maybe it can do it  by calculated line length in screen. For example, the length of a line is 100px, I'll cut 10px in the begin and the end. The line-dasharray is [0,10,80,10]. But it cannot solve so many lines in a layer. Also line-dasharray don't support data expressions

**Comment by HarelM** [comment]
Will the following feature request solve this issue?
- https://github.com/maplibre/maplibre-gl-js/issues/1235

**Comment by roshomon** [comment]
After a fashion, data-driven styling for line-dasharray paired with calculating line length can solve the problem. However, it will add a lot of work to calculate and store length of every line. If the source data update frequently, it would be even more difficult

**Comment by HarelM** [comment]
I'm honestly not sure I understand the requirement to be honest from a map designer perspective...

**Comment by roshomon** [comment]
Actually,the requirement is to show icons with transparent backgrounds at the ends of line. The icons is in a point layer over a line layer.  Now the result is ![Image](https://github.com/user-attachments/assets/d33d488f-3713-4ee5-acc5-510ed8e42797)
My ideal result is ![Image](https://github.com/user-attachments/assets/a44b1efe-2f04-425c-ac2f-c8138fea508e)
So is there a good way in MapLibre style?

**Comment by HarelM** [comment]
Wouldn't it be easier to fill the inside of the icon?

**Comment by roshomon** [comment]
The icons are drawn dynamically and have many kinds,at the same time I want to keep the transparent background of icon as many icons have no obvious border 
![Image](https://github.com/user-attachments/assets/9215690e-7f98-4848-835c-290b36550143)
so can't fill inside.

**Comment by roshomon** [comment]
ok thanks for relay and professional advise. Maybe I should think about the design of line crossing icon is good in geographic map, as the 
design inspiration is from electrical connect graph.
![Image](https://github.com/user-attachments/assets/3a4c94cc-bc1a-4a4b-98e3-316120facf1a)
