### ISSUE TITLE
Paint benchmark crashes: ReactDOM.render is not a function

### ISSUE THREAD

**Issue by kubapelc** [maplibre/maplibre-gl-js#5187]
**maplibre-gl-js version**: latest main branch as of writing this issue (commit `a1647916` ), also happens on 5.0pre9

**browser**: Firefox 128.5.1esr

### Steps to Trigger Behavior

 1. run `npm run start-bench`, wait for it to start up
 2. open http://localhost:9966/test/bench/versions/index.html#Paint
 3. benchmark crashes on error:

```
TypeError: ReactDOM.render is not a function
    updateUI http://localhost:9966/test/bench/benchmarks_view_generated.js:5332
    run http://localhost:9966/test/bench/benchmarks_view_generated.js:5346
    __awaiter http://localhost:9966/test/bench/benchmarks_view_generated.js:30
    __awaiter http://localhost:9966/test/bench/benchmarks_view_generated.js:26
    run http://localhost:9966/test/bench/benchmarks_view_generated.js:5335
    runComparison http://localhost:9966/test/bench/versions/index.html#Paint:57
    async* http://localhost:9966/test/bench/versions/index.html#Paint:15
index.html:69:25
    runComparison http://localhost:9966/test/bench/versions/index.html#Paint:69
    <anonymous> http://localhost:9966/test/bench/versions/index.html#Paint:15
```

**Comment by HarelM** [comment]
This might be related to the following update of types which is why typescript wasn't complaining.
I'll see if I can solve this.
- #5180

**Comment by HarelM** [comment]
I've fixed the problem (I believe) in the depebdabot PR.
Should be merged automatically when CI finishes running.
