### ISSUE TITLE
TouchEvent is not defined on Firefox on Ubuntu

### ISSUE THREAD

**Issue by alexaac** [maplibre/maplibre-gl-js#5220]
**maplibre-gl-js version**:
^v5.0.0-pre.1
**browser**:
Firefox v133.0 for Ubuntu
### Steps to Trigger Behavior

 1. Add a map
 2. Add maplibregl.NavigationControl
 3. The controls are not visible
 4. If you add the controls outside 'style.load' you get the error 'TouchEvent is not defined' only on Firefox

### Link to Demonstration

https://codesandbox.io/p/sandbox/epic-moon-tv6x38?workspaceId=ws_Sow94516aNZKmsqkDWJ6Wp
https://codesandbox.io/p/sandbox/icy-monad-rwxgh4?workspaceId=ws_Sow94516aNZKmsqkDWJ6Wp

### Expected Behavior
Navigation controls should be visible

### Actual Behavior
Navigation controls are not visible

![Image](https://github.com/user-attachments/assets/5387af93-5a57-42fa-bb98-399def950ad2)
![Image](https://github.com/user-attachments/assets/d9ad8354-d7a8-4f56-99fe-9a89ceaccb64)
![Image](https://github.com/user-attachments/assets/4f76c65a-1237-4108-97a3-e16510f2c4c8)
![Image](https://github.com/user-attachments/assets/e5dfde5e-dffb-4514-b1b3-29f68ec15fed)

**Comment by HarelM** [comment]
Can you please check with the latest version from main?
I believe this was fixed here:
- #5205

**Comment by alexaac** [comment]
Hi @HarelM , 

It worked with 4.7.1 earlier today. I've made a test: https://codesandbox.io/p/sandbox/exciting-shockley-nrzdkv

But it does not work for v5.0.0-pre.1 to v5.0.0-pre.9. Thanks

**Comment by HarelM** [comment]
Latest commits to main were not released yet, can you check a version from main by any chance?

**Comment by alexaac** [comment]
Sure, I will try.

**Comment by alexaac** [comment]
It works on the latest version of main. Thanks :)

![Image](https://github.com/user-attachments/assets/3cf93a1f-2877-4535-896d-b1e0dd758512)
