### ISSUE TITLE
Vector tiles disappear when more detailed tile is being fetched

### ISSUE THREAD

**Issue by kamil-sienkiewicz-asi** [maplibre/maplibre-gl-js#5248]
**maplibre-gl-js version**: 5.0.0-pre.10

**browser**: chrome

### Steps to Trigger Behavior

 1. Enter webpage with maplibre
 2. Set throttling to networking in chrome dev tools / have slow internet connection
 3. Sometimes tiles are completely disappearing and only background is rendered

### Link to Demonstration

https://codepen.io/kamil-sienkiewicz-asi/pen/zxOZeaP

### Expected Behavior

Less detailed vector tile is rendered until more detailed tile is completely fetched

### Actual Behavior

Less detailed vector tiles is removed at the start of fetch of new tile - which results in some period of time without any tile at all.

https://github.com/user-attachments/assets/796e46ea-beb1-45b7-94c9-4d2fab8a009c

**Comment by kamil-sienkiewicz-asi** [comment]
@HarelM I mean, sort of, I think it's somewhere in-between bug and a feature request, I think that on mercator projection tiles are behaving in more "natural" way, where on globe they can disappear without clear reason, especially when camera is facing poles.

On my video I have no clue why tiles disappeared when I zoomed in, on mercator they would just wait for higher resolution to be fetched, where on globe I got empty sphere

**Comment by HarelM** [comment]
Ahh, so this is a globe only related problem, interesting...
