### ISSUE TITLE
Add examples and proper documentation for the globe projection

### ISSUE THREAD

**Issue by satanch** [maplibre/maplibre-gl-js#5254]
## User Story

I wanted to realize a map with a globe after reading globe view issue https://github.com/maplibre/maplibre-gl-js/issues/307 
But combining globe projection and OSM tiles is not working at all.

Simple example: https://jsbin.com/decimutago/edit?html,js,output

Reading style docs and API docs is not helping at all. There is no specific example or doc's page about `globe` projection. How to use it with OSM tiles? Maybe it's clear for the contributors, GIS developers, MapLibre developers but not for a regular developer. Everything is **clear, well documented and working**, but globe projection is a some kind of mystery.

After several hours of searching and asking AI still no results. Earth is still flat.

## Rationale

Making globe projection documentation/example is clear could help everyone.

Maybe you could provide some proper example and explanation in this issue.

Thank you a lot!

**Comment by ingalls** [comment]
I think the docs will be updated once the 5.0.0 release is official and not a pre-release tag but in the meantime if you are blocked you can checkout some of the examples like:

https://codepen.io/ingalls-the-bold/pen/jENmLGe

Listen for the `load` event and then call setProjection.

**Comment by HarelM** [comment]
Closing this issue for now as 5.0 was not released yet and the docs are showing the non globe version still. 
If this is still relevant after 5.0 will be released please write here and I'll reopen this issue.
