### ISSUE TITLE
** Breaking Change ** stopped supporting IE (internet explorer) in v2.0.0

### ISSUE THREAD

**Issue by bothness** [maplibre/maplibre-gl-js#527]
**maplibre-gl-js version**: 2.0.0

### Question

I noted from the [changelog](https://github.com/maplibre/maplibre-gl-js/blob/main/CHANGELOG.md) that it seems IE 11 will no longer be supported from Maplibre v2.0.0 onwards. I couldn't seem to find a discussion around this, so am posting as an open question instead.

Part of our reason as an organisation for migrating from Mapbox v1 to Maplibre was to have a product with longer term support for IE, which is a requirement of all UK govenment websites for at least the medium term (there are a surprising number of people who still use IE unfortunately). So, I was keen to understand the reasoning for dropping IE support in v2, and whether there's an intention for continued support and bug fixes for v1 beyond verson 1.15.2?

**Comment by wipfli** [comment]
Please post this at https://github.com/maplibre/maplibre-gl-js/discussions/71

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/discussions/71#discussioncomment-331692
