### ISSUE TITLE
Remove @mapbox/geojson-rewind dependency

### ISSUE THREAD

**Issue by cigone-openindoor** [maplibre/maplibre-gl-js#54]
## Motivation

The goal is to reduce dependency to mapbox

## Design Alternatives

rewind is just a short method, could be integrated into maplibre-gl-js main project

## Design

We need to take care of license, adding rewind copyright.

Current source code is here:
https://github.com/mapbox/geojson-rewind
https://github.com/mapbox/geojson-rewind/blob/main/index.js

**Comment by HarelM** [comment]
@cigone-openindoor do you want to send a PR for this? We've done it for "point" dependency, so far there were no issues...

**Comment by HarelM** [comment]
@cigone-openindoor any updates on this?

**Comment by clement-igonet** [comment]
No time, no need.
Thx

**Comment by HarelM** [comment]
@birkskyum any chance you could look into it?

**Comment by birkskyum** [comment]
@HarelM , the other day I was trying to make a proper esm build, and found that frankly all these tiny mapbox libraries we depend on are only commonjs exported, not properly maintained, and only in js too. We need a solution for all of them, so I think this becomes just one in a bunch that needs an overhaul. 

This is the full list from our package.json. I've already experimented with about half of them at this point, so let's include it in that process. For instance Unitbezier is another tiny library, that you even [added definitions for](https://github.com/mapbox/unitbezier/commit/fdd4c56d63b204b5b8c10ff4e1b05c7578d48aab), and it's also easy to convert to ts and include directly.

runtime deps
    "@mapbox/geojson-rewind": "^0.5.2",
    "@mapbox/jsonlint-lines-primitives": "^2.0.2",
    "@mapbox/mapbox-gl-supported": "^2.0.1",
    "@mapbox/point-geometry": "^0.1.0",
    "@mapbox/tiny-sdf": "^2.0.5",
    "@mapbox/unitbezier": "^0.0.1",
    "@mapbox/vector-tile": "^1.3.1",
    "@mapbox/whoots-js": "^3.1.0",

dev deps    
     "@mapbox/gazetteer": "^5.1.0",
    "@mapbox/mapbox-gl-rtl-text": "^0.2.3",
    "@mapbox/mvt-fixtures": "^3.10.0",
