### ISSUE TITLE
Move psydo-unit test `symbol/shaping.test.js`

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#545]
`symbol/shaping.test.js` is a psydo-unit test because it generates files and compares the current output against them. We should not treat it the same way we treat the other unit tests and move it to some special place in the `test/` folder.

**Comment by birkskyum** [comment]
Fixed by #952

**Comment by HarelM** [comment]
Thanks for closing this!! I knew there was an issue somewhere we opened in order to take care of this :-)
