### ISSUE TITLE
Replace `sinon` with `nise`

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#554]
## Motivation

It seems that we are using `sinon` mainly for the fake http server.
`nise` is this part of sinon exactly and their typings is a bit better than sinon's.
I would advise to add `nise` to the jest test migration effort and remove `sinon` once we are done with the migration.

**Comment by HarelM** [comment]
@birkskyum thanks for pushing this forward!!

**Comment by birkskyum** [comment]
Sure! I'm still trying to figure out how we can get the remaining integration tests modernized too and leaved test'em etc. behind for good.
