### ISSUE TITLE
Support for devices without "highp" fragment shader precision

### ISSUE THREAD

**Issue by JannikGM** [maplibre/maplibre-gl-js#579]
Some of the maplibre shaders assume the existence of `highp` support in fragment shaders, although this is an optional feature in WebGL.
Also see the discussion in https://github.com/maplibre/maplibre-gl-js/pull/416#discussion_r733742057

Please leave a message if you think that you (or your users) are affected by the lack of `highp` support on some device, so we can see if it's worth discussing.

**Comment by valoricDe** [comment]
We saw this error today in our logs. But it is occuring very rarely
