### ISSUE TITLE
Financial Support

### ISSUE THREAD

**Issue by thomashermine** [maplibre/maplibre-gl-js#58]
We are a Belgian startup relying a lot on MapBox toolset and open libraries.
Like a lot of people, we where surprised by the [TOS & License changes in MapBox GL 2.0](https://github.com/mapbox/mapbox-gl-js/issues/10162)

We are more than willing to bet on MapLibre, and are in the progress of migrating all our projects towards it — we will probably contribute to the project at some point during this process. 

Meanwhile, we would like to financially support the project at our small scale — and I'm pretty sure that would be the case of a lot of other organisations.

Would you open an Patreon or OpenCollective account ?

**Comment by cigone-openindoor** [comment]
Good to know :-)
I would be glad to contribute on maplib project for your needs.
I'm leading a french startup for OSM indoor solution and my company would be glad to support on maplibre improvements.
Feel free to contact me: clement.igonet@openindoor.io

**Comment by cigone-openindoor** [comment]
Also the question is: who would take the lead on OpenCollective ?
What organization ?
For the moment, I don't see any... :-/

**Comment by ForsakenHarmony** [comment]
Maybe it could become part of the [OpenJS Foundation](https://openjsf.org/)

**Comment by rcheetham** [comment]
Azavea is also interested in an ability to make a contribution. We allocate a portion of our annual profits to both charitable organizations and open source projects, and my colleagues nominated MapLibre as a potential recipient in 2020.

**Comment by lseelenbinder** [comment]
Thanks for the offers @thomashermine, @cigone-openindoor, and @rcheetham!

We (the Steering Committee) are actively working on the foundation issue. It's a bit tricky for various reasons, but we have made some solid progress (mostly ruling out options we were hoping would work, unfortunately ☹️ ). There are a few good solutions, but they all take time to setup. I don't think we have a timeline yet, but it's high priority for the project.

**Comment by wipfli** [comment]
https://github.com/sponsors/maplibre
