### ISSUE TITLE
Tracking requests to mapbox

### ISSUE THREAD

**Issue by primozs** [maplibre/maplibre-gl-js#589]
Is maplibre still making requests to mapbox for tracking?

Errors in brave.

![Screenshot from 2021-11-01 12-08-52](https://user-images.githubusercontent.com/1006789/139662790-a500e4eb-95b4-4b45-84a3-6b20b76fdfe1.png)

**Comment by HarelM** [comment]
Which version are you testing?
In 2.x it shouldn't...

**Comment by primozs** [comment]
@HarelM Sorry I should write it before.

I just did "yarn add maplibre-gl"

"maplibre-gl": "^2.0.0-pre.1",

**Comment by HarelM** [comment]
Can you test against pre.5?
pre.1 is a version that should not be out there...

**Comment by primozs** [comment]
@HarelM Yes in pre.5 its ok.
Thank You!
Cheers
