### ISSUE TITLE
@types/maplibre-gl missing padding field in CameraOptions

### ISSUE THREAD

**Issue by MikkoSteerpath** [maplibre/maplibre-gl-js#60]
Padding is missing in CameraOptions type definitions.

source: https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/camera.js#L65
```
export type CameraOptions = {
    center?: LngLatLike,
    zoom?: number,
    bearing?: number,
    pitch?: number,
    around?: LngLatLike,
    padding?: PaddingOptions
};
```

types: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/maplibre-gl/index.d.ts#L1781

```
    export interface CameraOptions {
        /** Map center */
        center?: LngLatLike;
        /** Map zoom level */
        zoom?: number;
        /** Map rotation bearing in degrees counter-clockwise from north */
        bearing?: number;
        /** Map angle in degrees at which the camera is looking at the ground */
        pitch?: number;
        /** If zooming, the zoom center (defaults to map center) */
        around?: LngLatLike;
    }
```

While the types have the padding option for bounds related methods, it looks like the other methods like jumpTo and easeTo take the padding into consideration:

https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/camera.js#L810

**Comment by HarelM** [comment]
I've migrated the types into this repository.
Please submit a PR to this repo and I'll be happy to merge it :-)

**Comment by HarelM** [comment]
Probably not relevant any more, typings is generated from typescript code.
