### ISSUE TITLE
Clusters disappear when "clusterRadius" is very small

### ISSUE THREAD

**Issue by igal1c0de4n** [maplibre/maplibre-gl-js#61]
Details in https://github.com/mapbox/mapbox-gl-js/issues/2898#event-4239547971
Any chance to backport fix?

**Comment by mkv123** [comment]
As far as I understand, anyone who works on this is not allowed to have looked at their code for the fix, so I have not looked at their code.

From the comments on that issue, it seems two things are needed:

 - uncapping the clustering so it is used at zoom levels over 18
 - Update supercluster dependency to the latest version that fixes issue where small radius clusters were not working.

However looking through the maplibre source I could not directly find the cap they are referring to, however a geojson source has a default maxzoom of 18:

https://github.com/maplibre/maplibre-gl-js/blob/2112766af5d68a7ea885156c8c186c72a4e912ca/src/source/geojson_source.js#L99

So reading the maplibre code, I think we likely need to do two things: 

1) Update the supercluster dependency to the latest version (it still has a friendly license)
2) Update the documentation to say clusterMaxZoom beyond 18 requires to also set maxzoom.

**Comment by mkv123** [comment]
A quick test of just setting the maxzoom and clusterMaxZoom for a geojson source to a higher value makes clusters appear on higher zoom levels, so I think in order to make the cluster appearing reliable the supercluster dependency bump would be enough (+ clarification in documentation)

**Comment by igal1c0de4n** [comment]
@mkv123 Amazing! thank you for looking into it and for coming up with the fix!
Looking forward to see the commit 🙏

**Comment by mourner** [comment]
> However looking through the maplibre source I could not directly find the cap they are referring to

This one: 

https://github.com/maplibre/maplibre-gl-js/blob/15b99116014909a61c061e2189d1b0ceca979f6b/src/source/geojson_source.js#L139

**Comment by HarelM** [comment]
@mkv123 or @igal1c0de4n 
Please submit a PR id you can and I'll be happy to go over it.
If you can't please at least add a codepen/jsfiddler example showing the issue...

**Comment by turban** [comment]
Any progress on this? :-)

**Comment by HarelM** [comment]
@turban can you create a test that reproduce this and send a PR for it? I'm sure that one we have a test for this it will be easy to fix the issue.
As far as I understand the changes need to be updating supoercluster package and removing the above `Math.min` and using `options.clusterMaxZoom`.
Submitting a test to showcase this issue would be great.

**Comment by turban** [comment]
Codepen: https://codepen.io/turban-the-looper/pen/NWavKqW

The issue is that the cluster is not shown on the innermost zoom level (18).

**Comment by HarelM** [comment]
@turban thanks! any chance you can create a unit/render test in this repo?

**Comment by turban** [comment]
Sorry, I don't have the capacity.

**Comment by HarelM** [comment]
I've created a PR for this: #798
