### ISSUE TITLE
Publish version 2

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#610]
MapLibre GL JS 2.0.0 is about to be published. Here are the remaining tasks:

- [x] Test pre-release 
- [x] Update changelog
- [x] Prepare docs repo
- [ ] Update readme
- [ ] Explain access token and tracking code removal
- [ ] Write a note on usage with third-party data providers
- [ ] index.d.js

**Comment by HarelM** [comment]
Changelog is up to date as far as I know, it was automatically copied to the releases part of github, I don't know what will happen in the coming release, but worst case we can manually copy it...

**Comment by HarelM** [comment]
Thanks for the reminder, I'll setup the test later this week.

**Comment by astridx** [comment]
> @wipfli  MapLibre GL JS 2.0.0 is about to be published. Here are the remaining tasks:
> 
> * [x]  Update changelog (@HarelM @astridx)
> * [ ]  Update readme (@astridx)

Do you mean the Readme [here ](https://github.com/maplibre/maplibre-gl-js/blob/main/README.md) and in the docs-Folder, or are there some more ?

I have entered an addition in the changelog. I assume that this will be placed under the version created when publishing, right? I don't have to do anything more, do I?

**Comment by wipfli** [comment]
Apologies if my list was not clear. We should make sure that the readme talks about version 2 and not version 1, for example here:
```diff
  "dependencies": {
-    "mapbox-gl": "^1.13.0"
+    "maplibre-gl": ">=1.14.0"
  }
```

**Comment by astridx** [comment]
@wipfli Please see https://github.com/maplibre/maplibre-gl-js/pull/611

**Comment by frank-unovica** [comment]
Currently 2.0.0-pre1 is installed by default (yarn), but has raster tile artifacts. Forcing pre5 (or 1.x) fixes this. I don't know if this is important, just saying.

**Comment by HarelM** [comment]
I've tried version 2.0 with my project and it seems that the typings are a bit off.
I'll see how this can be fixed before we publish this version, as releasing it as is right now will cause whoever is using it with typescript some pain...

**Comment by HarelM** [comment]
"a bit off" was an understatement unfortunately...
There are some major gaps between the typings that were written to facilitate the usage of typescript before the typescript migration and the typings that are now generated.
The typings that are now being generated are lacking in some areas.
I've created the following draft PR to allow collaboration: #623, feel free to comment there about this issue.
From my point of view this is gating for a release of an official version. I know the `pre.1` is the default version in npm but I'm not sure we should create a non pre-release with this issue. A possible intermediate solution would be to release another pre-release that will replace pre.1 to improve the current situation for developers...

**Comment by astridx** [comment]
> @HarelM . A possible intermediate solution would be to release another pre-release that will replace pre.1 to improve the current situation for developers...


I have too little knowledge regarding typescript and do not fully understand the problem. I only use javascript so far. 
Your suggestion sounds like a good solution to me. I would then explain it in the readme like this.

**Comment by wipfli** [comment]
I'm happy to release a new 1.x. @xabbu42 do you have anything in particular that you would like to pack into the next 1.x version or should I just go ahead?

**Comment by xabbu42** [comment]
Go ahead 👍. I think a working stable release as default installation is long overdue.

**Comment by HarelM** [comment]
I don't think a new version 1.x from 1.x branch has anything to add to the previous version 1.x, so I don't see the benefit here, correct me if I'm wrong.
Creating an official version 2.x is not a good idea as typescript users will suffer, me among them (as I said in my previous post), if anyone is willing to help me fix it, it will allow releasing an official version 2.x sooner.
What I offered is to create another pre-release to replace 2.0.pre.1 as pre.1 is broken.
Make it the default to fix the problem with pre.1 but still not release an official version 2.x.
I hope my intensions are clearer now...

**Comment by xabbu42** [comment]
> I don't think a new version 1.x from 1.x branch has anything to add to the previous version 1.x, so I don't see the benefit here, correct me if I'm wrong.

The benefit is that new people just checking out maplibre-gl-js get the latest **stable** version after `npm install maplibre-gl-js`.

**Comment by HarelM** [comment]
@wipfli just fixed that using npm API. Thanks @wipfli!!

**Comment by wipfli** [comment]
You are welcome. Sorry for not fixing this earlier @mactrem and @xabbu42. I tested `npm install maplibre-gl` just now and it correctly downloaded `1.15.2`.

**Comment by HarelM** [comment]
This issue also has to be solved before releasing 2.0: #370 as it prevents building this library in webpack.
I'll look into it as I think I'm finishing up with the typescript stuff...

**Comment by HarelM** [comment]
We also might want to wait for #165 to be merged assuming all the tests, review etc are done.

**Comment by HarelM** [comment]
I've published 2.0.0-pre.6 and initial tests seems to look good, I haven't found any issues yet...

**Comment by astridx** [comment]
I've tested 2.0.0-pre.6 with a [GatsbyJs ](https://www.gatsbyjs.com/) Website.

The Code for the Site is in the Repo https://github.com/astridx/gatsby-maplibre-blog-tutorial/

The `main `branch with `"maplibre-gl": "^1.15.2",` works fine.

The `test_maplibre_v2 `branch with `"maplibre-gl": "^2.0.0-pre.6",` has error while building.

```
$ gatsby build
success open and validate gatsby-configs, load plugins - 0.622s
success onPreInit - 0.009s
success delete worker cache from previous builds - 0.006s
success initialize cache - 0.192s
success copy gatsby files - 0.203s
success Compiling Gatsby Functions - 0.394s
success onPreBootstrap - 0.414s
success createSchemaCustomization - 0.009s
success Checking for changed pages - 0.004s
success source and transform nodes - 0.257s
info Writing GraphQL type definitions to /home/astrid/git/websites/gatsby-maplibre-blog-tutorial/.cache/schema.gql
success building schema - 1.123s
success createPages - 0.157s
success createPagesStatefully - 0.130s
info Total nodes: 39, SitePage nodes: 7 (use --verbose for breakdown)
success Checking for changed pages - 0.002s
success Cleaning up stale page-data - 0.005s
success onPreExtractQueries - 0.006s
success extract queries from components - 2.710s
success write out redirect data - 0.004s
success onPostBootstrap - 0.002s
info bootstrap finished - 10.949s
success write out requires - 0.015s
success Building production JavaScript and CSS bundles - 2.057s
success Building HTML renderer - 1.792s

 ERROR 

performance is not defined



  ReferenceError: performance is not defined
  
  - maplibre-gl.js:31 
    [gatsby-starter-default]/[maplibre-gl]/dist/maplibre-gl.js:31:2522
  
  - maplibre-gl.js:22 define
    [gatsby-starter-default]/[maplibre-gl]/dist/maplibre-gl.js:22:1
  
  - maplibre-gl.js:35 
    [gatsby-starter-default]/[maplibre-gl]/dist/maplibre-gl.js:35:1
  
  - maplibre-gl.js:3 
    [gatsby-starter-default]/[maplibre-gl]/dist/maplibre-gl.js:3:61
  
  - maplibre-gl.js:6 Object.4613
    [gatsby-starter-default]/[maplibre-gl]/dist/maplibre-gl.js:6:2
  
  - bootstrap:19 __webpack_require__
    /home/astrid/git/websites/gatsby-maplibre-blog-tutorial/.cache/page-ssr/routes/webpack:/gatsby-starter-default/webpack/bootstrap:19:1
  
  - render-page.js:1782 Object.1938
    /home/astrid/git/websites/gatsby-maplibre-blog-tutorial/.cache/page-ssr/routes/render-page.js:1782:19
  
  - bootstrap:19 require
    /home/astrid/git/websites/gatsby-maplibre-blog-tutorial/.cache/page-ssr/routes/webpack:/gatsby-starter-default/webpack/bootstrap:19:1
  
  - gatsby-ssr.js:8 Object.1890
    /home/astrid/git/websites/gatsby-maplibre-blog-tutorial/.cache/page-ssr/routes/webpack:/gatsby-starter-default/gatsby-ssr.js:8:17
  
  - bootstrap:19 require
    /home/astrid/git/websites/gatsby-maplibre-blog-tutorial/.cache/page-ssr/routes/webpack:/gatsby-starter-default/webpack/bootstrap:19:1
  
  - api-runner-ssr.js:3 Module.9874
    /home/astrid/git/websites/gatsby-maplibre-blog-tutorial/.cache/page-ssr/routes/webpack:/gatsby-starter-default/.cache/api-runner-ssr.js:3:15
  
  - bootstrap:19 require
    /home/astrid/git/websites/gatsby-maplibre-blog-tutorial/.cache/page-ssr/routes/webpack:/gatsby-starter-default/webpack/bootstrap:19:1
  
  - static-entry.js:15 
    /home/astrid/git/websites/gatsby-maplibre-blog-tutorial/.cache/page-ssr/routes/webpack:/gatsby-starter-default/.cache/static-entry.js:15:39
  
  - render-page.js:9497 
    /home/astrid/git/websites/gatsby-maplibre-blog-tutorial/.cache/page-ssr/routes/render-page.js:9497:3
  
  - render-page.js:9502 Object.<anonymous>
    /home/astrid/git/websites/gatsby-maplibre-blog-tutorial/.cache/page-ssr/routes/render-page.js:9502:12
  
  - v8-compile-cache.js:192 Module._compile
    [gatsby-maplibre-blog-tutorial]/[v8-compile-cache]/v8-compile-cache.js:192:30
  

not finished Execute page configs - 0.275s

```


Do I make a mistake?

**Comment by HarelM** [comment]
I'm not familiar with gatsby, but the error seems like the problem we had with jest where performance is a global field of window and is not recognize by node environment.
I don't know if and how this is related but I know we changed it as part of the typescript migration.
If you are using gatsby you'll need to investigate what is the right solution I guess.
I don't mind waiting for this to be fixed before releasing version 2 if you would like to hack this.

**Comment by astridx** [comment]
I have found a solution to my problem: https://github.com/astridx/gatsby-maplibre-blog-tutorial/commit/9a2c007c55ab54bb72099f7ce37182a0beb8b09b

More informations are here: https://www.gatsbyjs.com/docs/debugging-html-builds/#fixing-third-party-modules

**Comment by wipfli** [comment]
What is the status on the index.d.js file @HarelM? I feel like I lost track there a bit.

**Comment by HarelM** [comment]
I think it's OK now, it can be improved but in general I was able to create a branch of ngx-maplibre-gl that complies and works as expected with version 2.0-pre.6

**Comment by wipfli** [comment]
Great. Thanks for the update.

**Comment by wipfli** [comment]
In the changelog I read this

** Breaking Change ** removed baseApiUrl as it was used only for mapbox related urls

I guess this means that sources starting with `mapbox://` won't be supported anymore. If so, I think we need to reflect this breaking change also in the style spec and bump its major version. We also need to update the style spec validation script.

**Comment by wipfli** [comment]
@HarelM can you comment on the status of the `mapbox://` protocol in version 2?

**Comment by HarelM** [comment]
`mapbox://` is not supported anymore in 2.0 out of the box. You can use `addProtocol` to customize it as you want.
