### ISSUE TITLE
MapLibre logo shown when using Mapbox source

### ISSUE THREAD

**Issue by frank-unovica** [maplibre/maplibre-gl-js#631]
**maplibre-gl-js version**:
1.15.2

**browser**:
Chrome 95

### Steps to Trigger Behavior

 1. Initialize maplibre with mapbox:// source (style string not tested)

### Link to Demonstration
Use this map style:
```
{
	version: 8,
	sources: {
		bla: {
			type: 'raster',
			url: 'mapbox://mapbox.satellite'
		}
	},
	layers: [
		{
			id: 'bla',
			type: 'raster',
			source: 'bla',
		}
	]
}
```

### Expected Behavior
MapLibre logo should not be shown unless specified/bundled. Mapbox logo should be shown when using mapbox sources.

### Actual Behavior
MapLibre logo is shown

**Comment by HarelM** [comment]
Thanks for taking the time to report this issue!
We have removed most things related to Mapbox in version 2.x.
I don't think this issue can be reproduced in version 2.0-pre.5 of this library.

**Comment by wipfli** [comment]
Logo logic was updated by @acalcutt. I think this can be closed.
