### ISSUE TITLE
fix or remove specific debug pages

### ISSUE THREAD

**Issue by xabbu42** [maplibre/maplibre-gl-js#633]
Since commit 8a49205cf09a479579142a4d745c932eef49c2b1 a lot of the specialized maps in https://github.com/maplibre/maplibre-gl-js/tree/main/debug no longer work or at least no longer have the original use. For example https://github.com/maplibre/maplibre-gl-js/blob/main/debug/satellite.html is now just the same as index.html instead of a map with satellite imagery. And https://github.com/maplibre/maplibre-gl-js/blob/main/debug/heatmap.html throws an error instead of actually adding the heatmap layer as it expects a particular layer to exist in the map.

For each of the specialized debug pages we should:
- check if they are useful to us and if they work
- fix or remove them if necessary

I currently don't have the time to do this but wanted to have an issue as a reminder.

**Comment by wipfli** [comment]
I guess this is still an issue, right @xabbu42 ?

**Comment by HarelM** [comment]
We probably should organize this folder, maybe even create an index page as part of `npm install` so that you can easily browse all the different pages.
Should be a fun task, I'll keep it in mind :-)

**Comment by xabbu42** [comment]
still an issue, the example satellite.html still only is a copy of index.html.

**Comment by HarelM** [comment]
I've created a way to index all the pages, it should be simple now to open the browser and see which pages are broken and which are working.
@xabbu42 any chance you can do it?

**Comment by xabbu42** [comment]
I will try to look at a few, but its usually not just as simple as having a quick check if they work. Some seem to work but no longer cover the same use case like satellite, others don't work but are clearly useful and should be fixed instead of deleted like heatmap.

**Comment by xabbu42** [comment]
I decided to push a solution to #198 first, as some of the debug pages need style specific fixes and we should first use a more complex style and data for our debug pages.

**Comment by austyle** [comment]
New path to debug pages for this issue: https://github.com/maplibre/maplibre-gl-js/tree/main/test/debug-pages

**Comment by austyle** [comment]
After reviewing the Debug Pages, my notes and suggestions can be found here: https://github.com/maplibre/maplibre-gl-js/discussions/1823

**Comment by rotu** [comment]
@HarelM Yes, this project is community driven. And demo pages are a good example of something that discourages my (and probably others') ability to confidently contribute.

Unfortunately, they debug pages are prominently recommended as a [way to validate new development](https://github.com/maplibre/maplibre-gl-js/blob/47389f8b04a381c5bb97bbbfb66c7d24d135357b/CONTRIBUTING.md#serving-the-debug-page). Could you (or another veteran) at least update `CONTRIBUTING.md` accordingly?

**Comment by HarelM** [comment]
The discussion about this specific part of this repo can be found here:
https://github.com/maplibre/maplibre-gl-js/discussions/1823
Feel free to share your experience and thought there, I'm sure they are valuable and would give another perspective to the discussion.
I would hate to push my opinion before hearing more thought about this topic...
Once decided, we can open an issue to track the next steps such as updating the contributing guide etc.
I'm sorry to hear this discourage you from contributing, if there's anything I can do to help you in that aspect please let me know. Also please don't take any of my code review change requests personally, I simply want to make sure the quality of this library stays good over time, and sometimes it doesn't pass well when writing. Feel free to ping me via slack if you think something I said was not in place or you need some guidance.

**Comment by rotu** [comment]
@HarelM, no worries! You have been very welcoming and I'm not offended at all by this or any code review comments. I hope that I haven't been out of line either!

The things that can help contribute significantly:

1. Edit the [PR template](https://github.com/maplibre/maplibre-gl-js/blob/main/.github/PULL_REQUEST_TEMPLATE.md) to be actionable.
  - Briefly describe the changes in this PR. (Where? In addition to the changelog entry?)
  - Post benchmark scores. (How? How do I know if the benchmark scores are acceptable?)
  - Manually test the debug page. (Which debug page? How? What am I looking for?)

2. Resolve benign build warnings and errors. (I have a number of pull requests for this)
3. Update `CONTRIBUTING.md`
  - This [recommends](https://github.com/maplibre/maplibre-gl-js/blob/47389f8b04a381c5bb97bbbfb66c7d24d135357b/CONTRIBUTING.md#serving-the-debug-page) using the debug page. How, which subpages, and what am I actually looking for?

**Comment by HarelM** [comment]
Thanks for the input! I'll see how I can improve the PR template to better explain how to do things, generally speaking, there are good documentation in this repo that explain how to do stuff, I'll see if I can link them from the PR template for better actionable points.

**Comment by xabbu42** [comment]
Seems like this issue can be closed as most of the debug pages were removed.
