### ISSUE TITLE
Nominatim and maplibre-gl-geocoder

### ISSUE THREAD

**Issue by cigone-openindoor** [maplibre/maplibre-gl-js#636]
We have no demo with a working example of geocoding tool

So I suggest to rely on this code to fix it:
https://github.com/open-indoor/open-indoor.github.io/blob/master/examples/maplibre-gl-geocoder.html

**Comment by wipfli** [comment]
Beautiful. Want to add it to the examples in the docs repo?

**Comment by wipfli** [comment]
Demo: https://open-indoor.github.io/examples/maplibre-gl-geocoder.html

**Comment by cigone-openindoor** [comment]
Pull request here:
https://github.com/maplibre/maplibre-gl-js-docs/pull/93
