### ISSUE TITLE
Suggest a non empty default style

### ISSUE THREAD

**Issue by cigone-openindoor** [maplibre/maplibre-gl-js#638]
As a beginner, I would be please to start using maplibre library without having to register to a style provider.

As example, this style could be a default one:
```
        {
            "id": "raster",
            "version": 8,
            "name": "Raster style",
            "center": [0, 0],
            "zoom": 0,
            "sources": {
                "raster-tiles": {
                    "type": "raster",
                    "tiles": [
                        "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
                    ],
                    "tileSize": 256,
                    "minzoom": 0,
                    "maxzoom": 19
                }
            },
            "layers": [{
                "id": "background",
                "type": "background",
                "paint": {
                    "background-color": "#e0dfdf"
                }
            }, {
                "id": "simple-tiles",
                "type": "raster",
                "source": "raster-tiles"
            }],
        }
```

**Comment by HarelM** [comment]
I tend to agree this is a good idea, I always find myself making a typo when creating a simple repo to reproduce an issue when all I need is a map that shows something...
Having said that, the main value for maplibre is vector tiles which is not in use here, so I'm not sure if the default should be raster.
This is just a though, I think this idea is better than the current behavior...

**Comment by xabbu42** [comment]
I also think that having a raster map as default would be a bit misleading. New users could get the impression they should build on that when in reality they need to find a vector data source and a style as useful starting point.

**Comment by astridx** [comment]
Please have a look at https://maplibre.org/maplibre-gl-js-docs/example/simple-map/

Is his what you want?

**Comment by cigone-openindoor** [comment]
Nice !

**Comment by wipfli** [comment]
Let's close this issue. Feel free to submit a pull request to the docs repo.
