### ISSUE TITLE
Attribution not working at full screen

### ISSUE THREAD

**Issue by acalcutt** [maplibre/maplibre-gl-js#640]
I think the recent changes to attribution_control.ts have broken my attribution list at full screen (above 615px width). The attribution button shows when the window is smaller, but when the screen is bigger it used to show as a list of attributions but now doesn't show anything at all. I have tested reverting the changes in this commit and it fixes the issue ( https://github.com/astridx/maplibre-gl-js/commit/0d1d7956484dcdd030574b21096159bc1adfcb83#diff-7489f127e6e44739b4d10d3d5102ca30e47ff444ebba85ea9921e558e9468676)

I am testing in this Terrain3d branch here, but this seems to have started when they merged in the main repository on Nov 8, which included [this change](https://github.com/maplibre/maplibre-gl-js/issues/359)

Latest version at above 615px width, missing attributions
![attrib_missing](https://user-images.githubusercontent.com/3792408/141647828-a718d440-e9be-4b51-90ce-7fb295968cc0.png)

Latest version below 615px width, the attributions show up as a button like they should
![attrib_smaller](https://user-images.githubusercontent.com/3792408/141647915-b2c84b1b-647c-4327-948e-6e88bcfdd09f.png)

This is how it looked when it was working on the previous version (which I compiled 10/19) above 615px, all my attribution show as a list at the bottom, until the screen gets below a certain size (around 615px) and it turns into a button

![attrib_working](https://user-images.githubusercontent.com/3792408/141648078-f0ba1efa-038e-4c44-8356-72b9c3a9cf12.png)

_Originally posted by @acalcutt in https://github.com/maplibre/maplibre-gl-js/issues/359#issuecomment-968079847_

**Comment by astridx** [comment]
@acalcutt It would be great if you can check if https://github.com/maplibre/maplibre-gl-js/pull/643 fixes the problem for you.

**Comment by acalcutt** [comment]
@astridx 

I tested that change and it does fix the issue.

**Comment by astridx** [comment]
Great. Thanks for the quick feedback and sorry for my mistake.

**Comment by acalcutt** [comment]
Thanks for fixing it. Most of the maps I created and use are free but require some type of attribution. while I doubt anyone is going to come after my small project, I'd rather be complying by the licenses :-)

**Comment by acalcutt** [comment]
After some further testing, I still don't think this is quite right. The fix above did make it so the attribution works at full screen, however when it shows up as a button and I click it, I am not seeing any attributes, like this 

![image](https://user-images.githubusercontent.com/3792408/143783355-70bdac1d-50ce-4884-a075-c877d078e6e7.png)

Here is an example ( https://stackblitz.com/edit/web-platform-tejxta?file=index.html )
- In this example it is using maplibre-2.0.0-pre.6. The dots on the map have the attribution 'Custom Attribution'. when the windows is big enough, the attribution shows. when the window is smaller, the button shows but has nothing when I click it (the html for the text is there it just isn't viewable)

Here is the same example with maplibre-2.0.0-pre.5 ( https://stackblitz.com/edit/web-platform-tkbuxa?file=index.html )
- In this example you can see it works as it should as full text when big enough. when the window is smaller, the button shows and clicking it shows the attribution
![image](https://user-images.githubusercontent.com/3792408/143783569-c404e002-c098-4db1-81d3-8a20c84e0c29.png)

**Comment by acalcutt** [comment]
I've tested the fixes in ( https://github.com/maplibre/maplibre-gl-js/pull/668 ) and they seem to work as expected (after a bit of back and forth there). they fix my issue observed in  ( https://github.com/maplibre/maplibre-gl-js/issues/640#issuecomment-981141058 )

I think it would be a good idea to approve them since the one currently in the repository does not work right. without these fixes, the previous working version was ( https://github.com/maplibre/maplibre-gl-js/blob/7149e8ac2fe6db1ea3641f40139b234b4be3b4e8/src/ui/control/attribution_control.ts )

**Comment by HarelM** [comment]
Fixed by #668
