### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by marcelnormann** [maplibre/maplibre-gl-js#65]
MapLibre still needs a logo! There are some contributions on [Twitter](https://twitter.com/maplibre/status/1336828663275335688) but its seems there is not an obvious winner. 

Logo
- needs to be copyrighted to the MapLibre project
- needs to be in vector format (e.g. SVG)
- should also work (partially) in very small and/or quadratic sizes like in favicons

**Comment by marcelnormann** [comment]
Proposed by [Steve Cline](https://twitter.com/maplibre/status/1336828663275335688)
![image](https://user-images.githubusercontent.com/18212012/105879326-522fd680-6002-11eb-82ee-3c6e6a89ac7c.png)

**Comment by marcelnormann** [comment]
Proposed by [Sanghee Shin](https://twitter.com/endofcap/status/1336989837782466561)
![image](https://user-images.githubusercontent.com/18212012/105879426-74c1ef80-6002-11eb-8980-3add12950c4b.png)

**Comment by marcelnormann** [comment]
Proposed by [WhereGroup](https://twitter.com/WhereGroup_com/status/1337066595139653632)
![image](https://user-images.githubusercontent.com/18212012/105879594-a9ce4200-6002-11eb-9478-f78b143585e1.png)

**Comment by marcelnormann** [comment]
Proposed by @klokan:
![image](https://user-images.githubusercontent.com/18212012/105879745-d6825980-6002-11eb-86a0-9b86f4437615.png)

**Comment by klokan** [comment]
Yep - the different ideas proposed by @tomasklanica, the designer @MapTiler, are at: 
https://www.figma.com/file/hVmulAVC8dMwYS14ovGd3w/MapLibre-image-%2F-logo

**Comment by JannikGM** [comment]
I prefer the one by @klokan / @tomasklanica, but would also like to see a favicon variant. I'd imagine that's just the libre head? Or just the marker on the maplibre-blue?

I'd also prefer if we set a deadline on the decision process so this doesn't drag on for another couple of weeks. I've seen that problem with way too many projects.

**Comment by lseelenbinder** [comment]
The agency that offered their efforts is still working on this for us. We should have an initial variation soon.

**Comment by klokan** [comment]
@edtjones it is great @errorstudio agency has proposed to help in MapLibre web design. Do you have any approach to logo or website - mock-ups or anything else to review?

**Comment by martincf** [comment]
Hi @klokan ! Yes, first draft design ideas are being finalised for the logo this week, and will be sent around accordingly :)

**Comment by stevage** [comment]
Not sure if comments are being sought or not, but...

I'm not a big fan of the "Statue of Liberty holding a map pin" design. Because:
- the Statue of Liberty symbolises New York and the USA much more than it symbolises FOSS (to me, anyway)
- IMHO the emphasis here should be on "this is a really great mapping library" rather than "this is something with a FOSS licence".

Just like the OpenLayers and Leaflet logos don't have any explicit FOSS elements, I don't think it is required here.

(Also, Tangram -- or Mapbox GL JS for that matter -- doesn't seem to have a logo, so maybe logos aren't all that essential for mapping libraries :) )

**Comment by curran** [comment]
![image](https://user-images.githubusercontent.com/68416/106195742-90520500-617e-11eb-92aa-bdbd47e2f2d6.png)

**Comment by Joxit** [comment]
I vote for @klokan v5 with for banner or long version and the rounded square version for favicon/avatar

I would like a small change however on v5, remove `© MapTiller © OpenStreetMap contrib` from the screenshot (the end of attribution is missing) and add `© OpenStreetMap contributors` in a nicer way. With the same font as MapLibre ?

**Comment by klokan** [comment]
Attribution to MapTiler not intentional - and not wanted on any logo (of course!). The design posted was made for the blog post https://www.maptiler.com/news/2021/01/mapbox-gl-open-source-fork/ - and the designer has just used a screenshot from our product there.

I encourage anybody here to fork the design and move it forward in Figma or otherwise - please take the chance and modify and change. The work we have done on this is in public domain - vectors are in Figma too, the original shape of the Statue of Liberty was also without usage limits IMHO.

**Comment by mike-marcacci** [comment]
My vote is for a standalone symbol using the "place" symbol in place of the torch over a solid background almost exactly like this:
<img width="220" alt="image" src="https://user-images.githubusercontent.com/690517/106301456-f8ebc100-6214-11eb-974f-48e385f6ca03.png">

...but less cropped in, such that the full bust of Lady Liberty is visible, with the lower line, as in this one:

<img width="114" alt="image" src="https://user-images.githubusercontent.com/690517/106301527-0a34cd80-6215-11eb-9178-fb1cfe8615da.png">

The symbolism of "raising the place icon to light the way" is spectacular, and with the name "liberty" already part of the project, the fit just feels perfect to me. Making sure the symbol can stand alone in any context is pretty important, so while the "map background" might be a great "header" I think it's important that the "core logo" stands by itself, and also doesn't require cropping (which would make it awkward to, for example, center it on a page).

**Comment by lseelenbinder** [comment]
> @edtjones it is great @errorstudio agency has proposed to help in MapLibre web design. Do you have any approach to logo or website - mock-ups or anything else to review?

Yes—as of yesterday we have some mockups to work through with the steering committee in our next meeting.

**Comment by akuckartz** [comment]
Statue of Liberty => New York => US
and
US => liberty for the rich

Do you really want this semantic for a logo of a global Open Source project?

**Comment by nyurik** [comment]
@akuckartz a bit farfetched won't you say? :)

**Comment by nyurik** [comment]
P.S. I do like the idea of the statue of liberty holding the map icon tbh

**Comment by bothness** [comment]
I'd agree 100% with @akuckartz on this. For people in a lot of the world the statue of liberty is a symbol of US imperialism

**Comment by lseelenbinder** [comment]
@nyurik / @akuckartz / @bothness the agency working on the branding for us already mentioned their concerns with the Statue of Liberty as a symbol of project for similar reasons.

As an (expat) American, I thought it was clever, but I can't deny the prevalent negative associations (despite what the statue _should_ represent—obviously there's a lot of nuance here we needn't dredge through). Regardless, I think such an overt association with a national symbol like that is unwise for a global project, politics aside.

I think once everyone is able to see a final draft of the logo proposals, we'll be happy with what the agency is working on—they're the professionals here, after all. 😄 (We'd put them in this thread now, but they're not ready for that level of critique just yet.)

**Comment by bothness** [comment]
Just to follow up on this... I had actually been thinking about the idea of a simpler logo with a map marker in place of the dot on the 'i', so just put this together now. It's a little generic, but I think pretty versatile and maybe even memorable. The font is Ubuntu, which is free to use (I was looking for something sans serif with a curling lower case L). The colours are all just suggestions. My 7 year old son can take half the credit on those. I think would probably be good not to be mapbox blue.

![maplibre-logo-01](https://user-images.githubusercontent.com/13994145/106358187-27e85c80-6313-11eb-9e75-2dd353361429.png)
![maplibre-logo-02](https://user-images.githubusercontent.com/13994145/106358188-29198980-6313-11eb-85ec-471c134c8751.png)
![maplibre-logo-03](https://user-images.githubusercontent.com/13994145/106358189-29198980-6313-11eb-9897-e395c5b61b52.png)
![maplibre-logo-04](https://user-images.githubusercontent.com/13994145/106358190-29b22000-6313-11eb-9efd-775505e8f962.png)
![maplibre-logo-05](https://user-images.githubusercontent.com/13994145/106358191-2a4ab680-6313-11eb-9eeb-c78f5ea22770.png)
![maplibre-logo-06](https://user-images.githubusercontent.com/13994145/106358192-2a4ab680-6313-11eb-8347-b20b6ecf49da.png)
![maplibre-logo-07](https://user-images.githubusercontent.com/13994145/106358193-2ae34d00-6313-11eb-8571-7b86441d61b4.png)
![maplibre-logo-08](https://user-images.githubusercontent.com/13994145/106358194-2b7be380-6313-11eb-9296-edd3de4e6f64.png)

**Comment by NasH5169** [comment]
By the way, the Liberty Statue has been offered by the French to the US to celebrate the 100 years of the US declaration of independence. So this is universal symbol of freedom. It is a shame that this symbol could be link to politics thoughts. Anyway, a simpler logo may be a good idea.

**Comment by lseelenbinder** [comment]
@NasH5169

> By the way, the Liberty Statue has been offered by the French to the US to celebrate the 100 years of the US declaration of independence. So this is universal symbol of freedom. It is a shame that this symbol could be link to politics thoughts. Anyway, a simpler logo may be a good idea.

Agreed, in spirit. Unfortunately, original intent and current perceptions are different, as I see it. 🙂

**Comment by bothness** [comment]
Sorry. Couldn't resist one last version. I'm all for a professional logo though.
![maplibre-logos-02](https://user-images.githubusercontent.com/13994145/106367661-e70d3980-634c-11eb-8b70-7b74f8c9a776.png)

**Comment by nyurik** [comment]
After reading the whole thread, it seems the statue of liberty causes controversy, and therefor should not be used (despite me personally loving it).  Logo could be either "meh" or "love it", but it should never "hate it".  If a logo causes dislike among significant portion of the users, we can't use it.  The last one by @bothness seems like a good alternative, perhaps with some minor stylistic cleanup? (i'm not a designer :) ).  One thing I am a bit unhappy about is the color -- I thought the `#275DA9` of the statue of liberty was a better pick:

![image](https://user-images.githubusercontent.com/1641515/108582296-4b923780-7300-11eb-877c-ef9e736fae88.png)

**Comment by bothness** [comment]
Hey. I'd be happy to offer some more options both on design and colours (no attachment whatsoever to the purple, but slightly hesitant about adopting a colour too close to mapbox brand). Was thinking that maybe a map pin that somehow integrates a flame could be interesting. So it kind of references the statue of liberty, but also Olympic flame, phoenix from the flames (keeping the OSS torch burning). Will try to find some time for it first half of this week.

**Comment by nyurik** [comment]
Thanks @bothness, I also kinda liked the torch idea intermixed with the pushpin, without the explicit reference to the statue of liberty. I looked at the mapbox's site but couldn't find any similar colors there - why do you say the color is similar to theirs? Closest is the blue/purplish i saw at [this page](https://www.mapbox.com/legal/privacy).

**Comment by klokan** [comment]
![image](https://user-images.githubusercontent.com/59284/108612107-90dc6500-73e5-11eb-8c7d-538b7969eb20.png)
https://www.figma.com/file/hVmulAVC8dMwYS14ovGd3w/MapLibre-image-%2F-logo

**Comment by bothness** [comment]
Hi all. Here's an updated version of the logo I shared previously with a flame in the map pin. I'm hoping that the flame also makes the pin element distinctive enough to use as a kind of icon. I've also attach a few colour variants, and also a ZIP file with SVG vector files.
![maplibre-logo-v3a-03](https://user-images.githubusercontent.com/13994145/108963094-59d6af80-7682-11eb-9013-7ba078673fec.png)
![maplibre-logo-v3a-02](https://user-images.githubusercontent.com/13994145/108963104-5d6a3680-7682-11eb-90c8-8d4589040dcd.png)
![maplibre-logo-v3a-05](https://user-images.githubusercontent.com/13994145/108963116-60fdbd80-7682-11eb-9c54-89b502e1208c.png)
![maplibre-logo-v3a-04](https://user-images.githubusercontent.com/13994145/108963125-62c78100-7682-11eb-97aa-3e3ac72af148.png)
![maplibre-logo-v3a-01](https://user-images.githubusercontent.com/13994145/108963133-64914480-7682-11eb-8a54-9f28bbc71a5f.png)
[maplibre-svg.zip](https://github.com/maplibre/maplibre-gl-js/files/6034108/maplibre-svg.zip)

**Comment by marcelnormann** [comment]
The steering committee decided to have a closed voting on the logo issue. We are happy to announce, that MapLibre now has an official logo: 
![110671790-36a61700-81cf-11eb-8608-642a55222f54](https://user-images.githubusercontent.com/18212012/114588799-5bd2ed00-9c87-11eb-9c55-c796bebf0710.png)
You can find all resources related to the logo at [Figma](https://www.figma.com/file/hVmulAVC8dMwYS14ovGd3w/MapLibre-Logo-%2F-Visuals?node-id=402%3A73). Thanks to everyone how contributed to the logo decision, whether by design proposal or by commenting!

**Comment by Seriosus** [comment]
If figma file says OLD then which one is the actual/new logo? 💀

**Comment by HarelM** [comment]
You can scroll down in the following page to get everything you need:
https://maplibre.org/about/

**Comment by Seriosus** [comment]
> You can scroll down in the following page to get everything you need: https://maplibre.org/about/

Do you guys have a discord or something more direct, to ask things about MapLibre?

Like this one, if my app has very different color palettes, can I edit the colors of the logo to match it?

**Comment by HarelM** [comment]
We have a slack channel. 
I don't know about using different colors though...
