### ISSUE TITLE
[Jest] Some unit tests are not really unit tests

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#651]
Some unit tests like `test/unit/style-spec/migrate.test.js` and `test/unit/style-spec/validate.test.js` have logic to modify the expected test outcome based on an environment variable `process.env.UPDATE`. I would argue that these are not really unit tests because their test outcome is not just a small unit, it is a full file. What would be a better name for these tests and where should we store them?

**Comment by wipfli** [comment]
https://github.com/maplibre/maplibre-gl-js/blob/b7625d6606b7b2358751e7e2a03b93f42e3041be/test/unit/style-spec/migrate.test.js#L128-L139

**Comment by HarelM** [comment]
I think these types of tests are integration tests.
I think `render` and `query` are also of that kind where you can update the expected results when needed (I also think they use the same env variable, right?).
I believe they should be in the `test/integration` folder much like the other integration tests, maybe in a folder of their own - `migration-tests`?

**Comment by HarelM** [comment]
As a side note, the `integration` test folder can use some cleanup and order - i.e. put all the data in the `data` folder, put all the tests in `test-somthing` folder, leave the orchestration code in the `lib` folder and leave as little as possible files in the main folder.
