### ISSUE TITLE
Define sky layout

### ISSUE THREAD

**Issue by cigone-openindoor** [maplibre/maplibre-gl-js#659]
After letting maxpitch going until 85, we see a black sky.
See: https://github.com/maplibre/maplibre-gl-js/pull/574

How could I change the default black sky ?

![image](https://user-images.githubusercontent.com/69067574/143035725-ea6dd291-5242-4e86-828e-d165b69d285f.png)

**Comment by HarelM** [comment]
This is probably the default color of the canvas/web gl, I wonder where it's defined...
Feel free to investigate and send a PR. I guess this should be configurable... :-)

**Comment by cigone-openindoor** [comment]
That's OK. background-color CSS is OK !
```
#map {
  background-color : black;
}
```
I could create a specific example in the doc...

**Comment by cigone-openindoor** [comment]
```
#map {
    background: linear-gradient(0deg, white 0%, #ffffff 50%, #6489e6 100%);
}
```

<img width="1440" alt="Screenshot 2021-11-23 at 16 37 12" src="https://user-mages.githubusercontent.com/69067574/143054905-f9d93e6e-b489-448b-9119-c38b54f1d228.png">

**Comment by HarelM** [comment]
A specific example with the gradient in issue #574 that looks like sunset can be great! :-)
