### ISSUE TITLE
Outdated Chrome version on CI server

### ISSUE THREAD

**Issue by marcelnormann** [maplibre/maplibre-gl-js#66]
The CI jobs are broken due to an outdated Chrome version on the CI server. I am not sure, who in control of this server, @snickell ?

See https://github.com/maplibre/maplibre-gl-js/pull/64/checks?check_run_id=1776132265 for an example.

**Comment by msbarry** [comment]
I set this up initially. This config controls the test-browser step: https://github.com/maplibre/maplibre-gl-js/blob/29c5e84938a98ac280b8d77c25bf9644eef21fbb/.github/workflows/ci.yml#L116-L141.  Looks like they pushed version 88 of chromedriver 5 days ago https://www.npmjs.com/package/chromedriver which broke this.  I'll try out a fix in a few
