### ISSUE TITLE
Offline cached raster tiles?

### ISSUE THREAD

**Issue by petrot** [maplibre/maplibre-gl-js#662]
**maplibre-gl-js version**:

### Question

Is it possible to save raster tiles like in this leaflet/pouchDB solution? Can I catch the loaded images somehow?
https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached

**Comment by HarelM** [comment]
You can use the `addProtocol` and decide exactly how to handle the fetching and caching of the tiles.
I'm using it with cordova and sqlite. I think there was another issue or discussing about it, is worth searching...
I also answered a SO question about it, but I'm have a hard time finding it.
In general, this is possible...

**Comment by petrot** [comment]
@HarelM ok, thaks! So I can save tile data to db and load tiles from db throught the addProtocol logic?

**Comment by HarelM** [comment]
Exactly. Pouchdb is a bit slow when it comes to 100k items, I'm using dexie.js in order to use indexdb straight.
