### ISSUE TITLE
[TypeScript] map.flyTo(options) - the "options" doesn't implement CameraOptions nor AnimationOptions

### ISSUE THREAD

**Issue by smellyshovel** [maplibre/maplibre-gl-js#663]
**maplibre-gl-js version**: 1.15.2

**browser**: -

### Steps to Trigger Behavior

 1. Try to pass `padding: { left: 100 }` to the `flyTo`'s `options` parameter.

### Link to Demonstration

![Screenshot_20211126_154731](https://user-images.githubusercontent.com/9782236/143583416-6b41c5d6-88c3-4a93-b2e2-43ec6c40151d.png)

### Expected Behavior

TSC shouldn't complain.

### Actual Behavior

The Docs [say](https://maplibre.org/maplibre-gl-js-docs/api/map/#flyto-parameters) that the `options` is `CameraOptions` and `AnimationOptions` together with a bunch of other fields. But in fact typescript only recognizes these "additional options".

In contrary, easeTo works as expected:
![Screenshot_20211126_155247](https://user-images.githubusercontent.com/9782236/143584024-e7a2d419-80d2-44b2-902f-c6e5c4fb305c.png)

**Note**: there's no runtime-errors nor incorrect behavior. It's just typing that doesn't work properly.

**Comment by HarelM** [comment]
I've recently changed this a bit, can you check if I made the right correction? It should be in map.ts file.

**Comment by smellyshovel** [comment]
@HarelM Not sure what you're talking about. Should I look for map.ts in sources?

Here's what I've managed to find in `src/index.d.ts`:
![Screenshot_20211126_162248](https://user-images.githubusercontent.com/9782236/143587553-655f9196-d777-42f4-b8c8-290363b1f0e3.png)

Looks legit to me, though there's still no proper type ingeritance.

**Comment by HarelM** [comment]
Version 2.0.0-pre.6 is using the latest code which is already written in typescript.
If the flyTo method is correctly typed it means that this is solved in latest version...

**Comment by smellyshovel** [comment]
@HarelM Ah, now I see. Thanks for the response.

**Comment by HarelM** [comment]
Seems like this was fixed. Closing.
If there's still an issue please feel free to write here.
