### ISSUE TITLE
How would one access vector tile data as JSON?

### ISSUE THREAD

**Issue by jayarjo** [maplibre/maplibre-gl-js#664]
I'd ask it on SO, but I think it is too specific/advanced. Basically what I wonder about is whether there is a way to access a result of vector tile to JSON conversion?

I've inspected `MapEventData` in `sourcedata` and noticed that there's some data stored as ArrayBuffer under `tile.latestRawTileData`, but how would I extract that? Simply convert to text? I believe there should be some kind of utility in the source code already that does that right away. Can you help?

**Comment by HarelM** [comment]
There's a npm package to convert pbf to geojson called vt-geojson.
But I'm not sure I understand the question entirely.
Can you elaborate on the scenario please?
