### ISSUE TITLE
MapDataEvent#isSourceLoaded is true when a "dataloading" event fires for a GeoJSONSource 

### ISSUE THREAD

**Issue by vanilla-lake** [maplibre/maplibre-gl-js#694]
**1.15.2**:

### Steps to Trigger Behavior

Call `GeoJSONSource#setData(...)` with a `dataloading` event listener registered.

### Link to Demonstration

https://jsbin.com/bigupoyejo/2/edit?html,console

### Expected Behavior

`MapDataEvent#isSourceLoaded` should be `false` when the `dataloading` event fires for the GeoJSON source.

### Actual Behavior

`MapDataEvent#isSourceLoaded` is `true` when the `dataloading` event fires for the GeoJSON source.

**Comment by HarelM** [comment]
@vanilla-lake is this still an issue?

**Comment by vanilla-lake** [comment]
I don't think so. It should have been fixed by PR #695.
