### ISSUE TITLE
 throw  error mismatched image size  , when text-field is chinese

### ISSUE THREAD

**Issue by 1042041156** [maplibre/maplibre-gl-js#718]
**maplibre-gl-js version**:2.0.0-pre.6

**browser**:chrome

### Steps to Trigger Behavior

 1. when symbol layer > layout> text-field is chinese
 2.  throw error  "mismatched image size"
 

[maplibre-gl-unminified.txt](https://github.com/maplibre/maplibre-gl-js/files/7724218/maplibre-gl-unminified.txt)
[testhtml.txt](https://github.com/maplibre/maplibre-gl-js/files/7724220/testhtml.txt)

**Comment by 1042041156** [comment]
plese  Change the suffix with .js an .html

**Comment by smellman** [comment]
I get same error with Japanese text-field.

https://codepen.io/smellman/pen/dyVwjYm

**Comment by smellman** [comment]
It raise from here.
https://github.com/maplibre/maplibre-gl-js/blob/main/src/util/image.ts#L24

We provides English style and Japanese style.
English style: https://tile.openstreetmap.jp/styles/maptiler-basic-en/style.json
Japanese style: https://tile.openstreetmap.jp/styles/maptiler-basic-ja/style.json
English style run well but Japanese style can't run in v2 release.

**Comment by smellman** [comment]
I fixed it with `localIdeographFontFamily: null` to disable local font.

**Comment by smellman** [comment]
maybe fix this issue by [PR 775](https://github.com/maplibre/maplibre-gl-js/pull/775)

**Comment by Nikkolast88** [comment]
me too !

**Comment by 1042041156** [comment]
> 我也是！
The above method can solve this problem

**Comment by HarelM** [comment]
The above linked PR should solve this I assume, but we need someone to create a test to make sure this is actually solving the issue and making sure it won't break in the future.
Can any of you write a test? even here in this thread and I'll copy it to the relevant place in the tests.
Here are some instruction we wrote to help with writing tests:
https://github.com/maplibre/maplibre-gl-js/tree/main/test#writing-unit-tests

**Comment by HarelM** [comment]
I've updated the tests to use tinySDF so I think the tests part is covered.
But when I surf to https://codepen.io/smellman/pen/dyVwjYm I don't see any console warning or errors.
What am I missing?

**Comment by HarelM** [comment]
See #917

**Comment by HarelM** [comment]
Closed by #917 I believe.
