### ISSUE TITLE
Incorrect near/far planes on low FOV

### ISSUE THREAD

**Issue by lachlanphillips** [maplibre/maplibre-gl-js#719]
**maplibre-gl-js version**: 1.15.2

**browser**: Chrome

### Steps to Trigger Behavior

 1. Place a 3D object in your environment (I'm using [LittlestTokyo.gltf](https://github.com/mrdoob/three.js/blob/dev/examples/models/gltf/LittlestTokyo.glb))
 2. Set the FOV to something small via map.transform.fov = 1

### Expected Behavior
Changing the FOV will elegantly adjust the nearZ value

### Actual Behavior
Changing the FOV leads to artifacting, especially as FOV approaches 0. (as nearZ also approaches infinite distance from centre along with it)

### My current fix
I can't figure out the exact formula here, but perhaps someone else can. There's some relationship between the FOV and the nearZ (or it may be a relationship to the this.cameraToCenterDistance) 

This is my current fix. Tested against my use case only. I would also suggest exposing a nearZMultiplier to the end user as use cases can differ.

Original line:
`var nearZ = this.height / 50;`

Modified to take into account FOV.
`
var fovMult = 1;
if (this.fov <= 0.02) {
	fovMult = 0.01750//0.1
} else if (this.fov < 2) {
	fovMult = 0.020//0.1
} else if (this.fov < 10) {
	fovMult = 0.1//0.1
} else if (this.fov < 20) {
	fovMult = 0.5//0.9//0.1
} else if (this.fov < 30) {
	fovMult = 0.55//0.1
} else {
	fovMult = 0.9//0.1
}
var nearZ = this.height / (this.fov * fovMult);
`

**Comment by HarelM** [comment]
Can you please provide a jsbin or codepen to help show what this issue is and what's wrong?

**Comment by HarelM** [comment]
No reproduction was shared. Closing. If this a reproduction will be shared I'll be happy to re-open.
