### ISSUE TITLE
Some events can be fired after Map#remove has been called when the WebGL context is lost and restored

### ISSUE THREAD

**Issue by vanilla-lake** [maplibre/maplibre-gl-js#726]
**maplibre-gl-js version**: 1.15.2

### Steps to Trigger Behavior

 1. Create a `Map`.
 2. Register a "webglcontextlost" event handler on the `Map` that registers a "move" event handler and then calls `Map#remove` followed by `WEBGL_lose_context#restoreContext`.
 3. Call `WEBGL_lose_context#loseContext`.
 4. Notice that the "move" event fires even though the map has been removed.

### Link to Demonstration

https://jsbin.com/buzucagaqo/1/edit?html,console

### Expected Behavior

The "move" event should not fire after `Map#remove` has been called.

### Actual Behavior

The "move" event fires after `Map#remove` has been called.

**Comment by HarelM** [comment]
Fixed by #727
