### ISSUE TITLE
TypeError: done.fail is not a function

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#729]
In the Jest migration, we have replaced `t.fail('error x occurred')` with `done.fail('error x occurred')`, see here: https://github.com/maplibre/maplibre-gl-js/search?q=done.fail

However, when I intentionally make a test reach such a `done.fail` statement, I get this error in the console:

```
● Map › does not fire "webglcontextrestored" after #remove has been called

    TypeError: done.fail is not a function

      931 |         const canvas = map.getCanvas();
      932 |
    > 933 |         done.fail('houps');
          |              ^
      934 |         map.once('webglcontextlost', () => {
      935 |             map.once('webglcontextrestored', () => done.fail('"webglcontextrestored" fired after #remove has been called'));
      936 |             map.remove();
```

Are we sure that `done.fail` is the right way to fail a test in Jest?

**Comment by HarelM** [comment]
I guess it's not clear and I don't know the answer.
The following thread is talking about it:
https://github.com/facebook/jest/issues/2129
Also this SO question:
https://stackoverflow.com/questions/42176642/in-jest-how-can-i-make-a-test-fail
Can you test using just `fail()` without `done.fail()`?

**Comment by wipfli** [comment]
According to the [Jest documentation](https://jestjs.io/docs/asynchronous#callbacks), one should use `done('error message')`. The docs provides the following example:

```js
test('the data is peanut butter', done => {
  function callback(data) {
    try {
      expect(data).toBe('peanut butter');
      done();
    } catch (error) {
      done(error);
    }
  }

  fetchData(callback);
});
```
