### ISSUE TITLE
Project does not match click event

### ISSUE THREAD

**Issue by jedgar1mx** [maplibre/maplibre-gl-js#73]
I notice that the pixel coordinates that I get from `project()` do not match the ones from a `click event`.

**mapbox-gl-js version**:
1.13.0-rc.4
**browser**:
chrome
### Steps to Trigger Behavior
 1.  Pass a `lat` & `lng` to `project()`
 2. Get the coordinates of the same location via click event
 3. See missmatch 

### Expected Behavior
Pixel coordinates should match or at least be close to each other.

### Actual Behavior
Disparity is very large
`click`: {x: 647, y: 360}
`project`: {x: 929.5205772562595, y: 28167.563284346284}

**Comment by mactrem** [comment]
It seems that you try to use map.transform.project to transform geographic coordinates (lon/lat) to pixel coordinates. 
But this method transforms geographic coordinates to world (spherical mercator) coordinates (in OpenGL terms). To get pixel coordinates from world coordinates the pixelMatrix (map.transform.pixelMatrix) can be used (multiply and divide by w see geo.transform.coordinatePoint). Internally the projMatrix (map.transform.projMatrix) is used to transform world coordinates to NDC (-1 ... 1). Use https://github.com/maplibre/maplibre-gl-js/blob/15b99116014909a61c061e2189d1b0ceca979f6b/src/ui/map.js#L851 to directly calculate pixel coordinates which should match with the coordinates from the click event.
