### ISSUE TITLE
Plans for shared code formatter?

### ISSUE THREAD

**Issue by j8seangel** [maplibre/maplibre-gl-js#759]
### Question

I've been struggling with the default vscode-prettier formatting rules so I needed to disable the formatOnSave for this project.

Is there any plan for adding [prettier](https://prettier.io/docs/en/why-prettier.html) on the project? (I could do it)
or any reason to avoid it?

**Comment by HarelM** [comment]
I don't have any objections.
We currently use lint for the code.
If lint doesn't cover this, than prettier is probably a good solution.
Can you elaborate which part is not cover by lint and can't be covered by adding a new rule?

**Comment by astridx** [comment]
I think the addition of prettier is comfortable. You don't always have to call `npm run lint`. The editor formats when saving. There are no other advantages, right? 
The disadvantage is that we then have another dependency that has to be kept up to date.

**Comment by j8seangel** [comment]
> Can you elaborate which part is not cover by lint and can't be covered by adding a new rule?

Prettier and Eslint do different things, prettier only takes care of formatting while eslint takes care of code quality [link](https://prettier.io/docs/en/comparison.html#how-does-it-compare-to-eslinttslintstylelint-etc) 
We can define rules like: `max-len`, `no-mixed-spaces-and-tabs`, `comma-style` and be consistent across the codebase and it can be run as an [Eslint plugin](https://prettier.io/docs/en/integrating-with-linters.html) so the integration should be effortless. 

> I think the addition of prettier is comfortable. You don't always have to call npm run lint. The editor formats when saving. 

I've found the way of fixing eslint issues on save with vscode without the need of installing an extra dependency adding this config in the `.vscode/settings.json` file:
```
    "editor.formatOnSave": false,
    "editor.codeActionsOnSave": {
      "source.fixAll.eslint": true
    },
```
which makes it more confortable however it won't cover the commented above

**Comment by HarelM** [comment]
Which part won't be covered by lint? I'm not familiar enough with prettier and reading your comment again wasn't enough for me to understand, sorry for nagging, but as @astridx said, we have enough dependencies we are struggling to maintain :-)

**Comment by j8seangel** [comment]
> Which part won't be covered by lint?

It takes care of things like the max length of a line, cleans white-spaces or ensures every indentation is consistent but I understand the charge of adding more dependencies so I'm going to close this for now.

@HarelM I just wanted to share [an example](https://github.com/GlobalFishingWatch/maplibre-gl-js/pull/3/files) by running prettier in the entire project so you know a bit more about prettier. Hope you find it useful for other projects!

**Comment by HarelM** [comment]
The above 4 example exists for lint as well. I'm all for adding more rules to lint, don't get me wrong... If there are other stuff perttier can help with it might be beneficial, IDK...

**Comment by astridx** [comment]
My comment should not be misunderstood, too. I can see the advantages of prettier, especially editong one file in the editor. Maybe it's just not knowing. I believe that it takes a lot of effort to keep eslint and prettier in sync. 

I run my configuration of prettier once and saved it in this [commit](https://github.com/maplibre/maplibre-gl-js/pull/758/commits/283e90dc2b012da795d878c022d89a15cbca3197). 
After that I called `eslint -- --fix`. 
The differences are big. 

So I think configuring and combining prettier and eslint together is cumbersome. 

We definitely need eslint to find errors in the code besides formatting. 

But as I said. Maybe it's just not knowing how to do it the easiest way?

**Comment by j8seangel** [comment]
> So I think configuring and combining prettier and eslint together is cumbersome.

It should be solved by the [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) config

> We definitely need eslint to find errors in the code besides formatting.

Completely agree, eslint is a must but I just think the combination of both makes the code style more robust and for example easier to keep in sync with other forks.

It has its benefits but I've just realised it also comes a lot of effort as there will be a lot of changes and potential conflicts in every PR open.

**Comment by HarelM** [comment]
I don't have strong feelings either way, I know prettier is widely used and is considered the standard, but I don't want to introduce it as pre-commit step as it takes to long to run...

**Comment by rotu** [comment]
I agree that we shouldn't have it running on pre-commit for all files. I personally like something like https://github.com/okonet/lint-staged so that it doesn't check unchanged files.
