### ISSUE TITLE
setClusterProperties

### ISSUE THREAD

**Issue by gregorwebdev** [maplibre/maplibre-gl-js#761]
## Motivation
To dynamically create clusterProperties in an existing geojson source/layer.  Therefore we could set the expressions created from the data's property. 

### Implementation
Like setData method, but on workerOptions.clusterProperties, before the expression validation runs. setClusterProperties would accept an object with property names(keys) and with expressions as values. 
I'm already started to implement this function, but i'm a newbie in programming so it won't be nice if i can accomplish it. I will show my code, if i could make it.

**Comment by HarelM** [comment]
It's unclear from the above comment what is the problem statement and proposed solution.
A code example of what is currently the problem and how an api change can solve it along a screenshot or an animated gif could go a long way :-)

**Comment by gregorwebdev** [comment]
Maybe it's just related to my framework, because my stylesheet is an external yaml file.
This is my mock up case: https://codepen.io/gregi1991/pen/qBPEjMm
But in reality i don't know about the exact number of colors(clusterProperties), so i need to generate these expressions on the fly.

**Comment by berkayoruc** [comment]
Is there any changes about programmaticaly set clusterProperties?

**Comment by HarelM** [comment]
This was merged recently:
https://github.com/maplibre/maplibre-gl-js/pull/1998
It might solve this issue, IDK.
This wasn't released though, so you can test it by building the main branch.

**Comment by berkayoruc** [comment]
I think, that merge just affect some cluster options, not clusterProperties. BTW, thank you.

**Comment by IhsenBen** [comment]
> I think, that merge just affect some cluster options, not clusterProperties. BTW, thank you. Maybe @IhsenBen give more information about merge.

it does affect available cluster options indeed, therefore allowing customization of the clusterRadius and maxZoom.
you can read the pull request or the comments I put on the code for more informations.

:)
