### ISSUE TITLE
[v2] performance is not defined

### ISSUE THREAD

**Issue by vincent-lecrubier-skydio** [maplibre/maplibre-gl-js#768]
**maplibre-gl-js version**: v2.0.0.pre.6

**browser**: Chrome

### Steps to Trigger Behavior

 1. install maplibre-gl v2 in a nextJS app
 2. run the app
 

<img width="996" alt="Screenshot 2022-01-13 at 11 12 47" src="https://user-images.githubusercontent.com/94416008/149320177-8fb82c6b-39af-4f51-98c8-cc4826c1cf16.png">

### Link to Demonstration

https://codesandbox.io/s/sharp-shirley-7pxbp?file=/pages/index.js

### Expected Behavior

No bug

### Actual Behavior

"performance is not defined" error.

**Comment by HarelM** [comment]
Does this work with version 1.15?

**Comment by vincent-lecrubier-skydio** [comment]
Yes

**Comment by HarelM** [comment]
I'm not a nextJS expert, so you'll probably need to investigate it on your own.
I know that in version 2.0 we have switched from using `window.performance` to just `performance`, which sounds like the root of this issue.
Having said that, it was done to simplify the build and the code and in general didn't cause any issues in the browser. So it would be great if you could try and tackle this, or even send a PR.
Thanks and sorry...

**Comment by acalcutt** [comment]
I've seen this "performance is undefined" error before when I was working on my IE compatible version. It was something with the code in src/util/browser.ts

```
const now = performance && performance.now ?
    performance.now.bind(performance) :
    Date.now.bind(Date);
```

I wasn't sure how to fix it correctly there so I ended up [just changing it](https://github.com/acalcutt/maplibre-gl-js/commit/c26cbf716ed784bdcff58a085c8255b3a2805e2e)
`const now = Date.now.bind(Date);`
which helped me get around it for my use.  

I doubt this helps you much, but the error is the same so maybe it is related to that same line in browser.ts

**Comment by astridx** [comment]
In a plugin there was an issue with nextJs and `windows`, what is sollen:
https://github.com/maplibre/maplibre-gl-compare/issues/3#issuecomment-898772048

**Comment by Kanahiro** [comment]
Thank you good discussions. I have met same problem and found workaround.
This issue may be caused by nextjs SSR processes.

```tsx
// a component include 'maplibre-gl': ./src/components/Map.tsx
// This include no special workaround
import { Map, NavigationControl, StyleSpecification } from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';

// ...

export default MapComponent;
```

Avoid reference error by Dynamic Import.

```tsx
// a component needs MapComponent: ./src/pages/map.tsx
import dynamic from 'next/dynamic';
const MapComponent = dynamic(() => import('../components/Map'), {
    ssr: false,
});
<MapComponents />
```

It is good if this could help you.

**Comment by Kanahiro** [comment]
or if you use href by <a> instead <NextLink>, try to use <NextLink>

**Comment by vincent-lecrubier-skydio** [comment]
Solved it in Next JS by using `await import("maplibre-gl-js")` as @astridx @acalcutt [mentionned](https://github.com/maplibre/maplibre-gl-js/issues/768#issuecomment-1012515975) it's definitely caused by this line of code. This needs to be preceded by a check on `typeof window === "undefined"`

**Comment by HarelM** [comment]
feel free to submit a PR in order to fix this. but since maplire-gl is mainly client side I guess you'll have more issues like that and I'm not sure solving them with "if not in client" will do the work... IDK.. just my 2 cents...

**Comment by frodrigo** [comment]
I got the same issue. After some testing I think it is linked to the nodejs version. The issue does no more appear when using nodejs >= 16.
