### ISSUE TITLE
Allow setting a custom pixel ratio

### ISSUE THREAD

**Issue by vanilla-lake** [maplibre/maplibre-gl-js#769]
## Motivation

When exporting a map to an image, there are many cases where we might want the image to have a different size in pixels than the in-app map all while keeping the same extent and zoom level. In other words, we want to scale the map. One reason to do this is to allow exporting at a certain DPI, like https://github.com/watergis/maplibre-gl-export does.

## Design Alternatives

The way maplibre-gl-export addresses this problem is by overriding the `Window#devicePixelRatio` property: https://github.com/watergis/maplibre-gl-export/blob/3977f96e829bf589d9988270da26444fdab807d9/lib/map-generator.ts#L148-L151

While it works, it relies on changing some global state, which could easily have some unintended consequences, especially when the code is asynchronous.

## Design

We could add a new `MapOptions#pixelRatio` property along with a new `Map#setPixelRatio` method. Instead of using the `Window#devicePixelRatio` property, maps would now keep their own pixel ratio value. In addition to making the above use case much less brittle, this would make testing easier as there would be no more need to override the `Window#devicePixelRatio` property.

One drawback is that it adds a bit more complexity to the `Map` interface. However, since maps' pixel ratio would default to the value stored in the `Window#devicePixelRatio` property when `MapOptions#pixelRatio` is not specified and `Map#setPixelRatio` has not been called, users would not have to think about this unless they need the new functionality, so existing code could remain unchanged.

### Mock-Up

As an example, maplibre-gl-export could get rid of the code snippet linked above and do something like the following at https://github.com/watergis/maplibre-gl-export/blob/3977f96e829bf589d9988270da26444fdab807d9/lib/map-generator.ts#L162-L175: 
```javascript
const renderMap = new MapLibreMap({
    /* ... */
    pixelRatio: this._dpi / 96
});
```

### Concepts

Some documentation will have to be written for the above additions to the public interface. The terminology we should use is "pixel ratio" as that will already be familiar to Web developers because of the `Window#devicePixelRatio` property. It is also already used internally by MapLibre GL JS.

### Implementation

We could add a new `MapOptions#pixelRatio` property, along with some new `Map#setPixelRatio` and `Map#getPixelRatio` methods.

Internally, the code would need to keep its own pixel ratio value instead of reading the `Window#devicePixelRatio` property.

**Comment by HarelM** [comment]
I'm not sure this should be a map property and not a global property like base url and access token were...?

**Comment by vanilla-lake** [comment]
I'm not sure... Having it as a global property would be a lot less useful in my opinion, since we wouldn't be able to set it on a per-map basis. It can be useful to create a separate map for exporting to an image, and having it as a global property would unnecessarily affect all maps.

**Comment by vanilla-lake** [comment]
FWIW, this seems to have been requested for some time in Mapbox GL's issue tracker: https://github.com/mapbox/mapbox-gl-js/issues/1953. Someone even proposed a similar solution: https://github.com/mapbox/mapbox-gl-js/issues/1953#issuecomment-561604595.

**Comment by vanilla-lake** [comment]
Another possibility could be to have a global setting, but also allow it to be overridden on a per-map basis.

**Comment by HarelM** [comment]
I see you point, both global and per map is a bit confusing I think.
I'll review the PR later this week.

**Comment by vanilla-lake** [comment]
Thank you!

**Comment by astridx** [comment]
Is it ok if I close the issue because we have a PR:
https://github.com/maplibre/maplibre-gl-js/pull/772 ?
Then the conversation is in one place.

**Comment by vanilla-lake** [comment]
@astridx That is fine with me.
