### ISSUE TITLE
Return type of map.getSource() does not allow type-safe access to source specific functions

### ISSUE THREAD

**Issue by lukashass** [maplibre/maplibre-gl-js#785]
**maplibre-gl-js version**: 2.0.1

**browser**: -

### Steps to Trigger Behavior

 1. Try using `map.getSource("key").setData(...)` with a strict typescript config

### Link to Demonstration

https://codesandbox.io/s/beautiful-orla-djvjz?file=/src/index.ts

### Expected Behavior

There should be a way to call the source specific functions like `setData()` in a type-safe way.

### Actual Behavior

Typescript error: `Property 'setData' does not exist on type 'Source'. ts(2339)`

**Comment by lukashass** [comment]
I'm currently trying to use [Type Guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) to solve this issue:

```ts
const isGeoJsonSource = (source?: Source): source is GeoJSONSource => source?.type === 'geojson';

const source = map.getSource('key');
if (isGeoJsonSource(source)) {
  source.setData({});
}
```

Though the problem with this is that `GeoJSONSource` and the other source types are not exported by maplibre.

Possible solutions I can think of would be:

- export source types so everyone can cast the return value or implement type guards as above
- include type guards in maplibre
- provide functions for each source type like `getGeoJSONSource()`

**Comment by HarelM** [comment]
I've seen this issue too.
It was `any` before I changed it to `Source`.
Feel free to hack this and send a PR.
The main difficulty is the generation of the `.d.ts` file that is done using a third party tool.
See #776.
I don't have an objection to export the sources for better typings and casting...

**Comment by ma7moudat** [comment]
Has this been resolved? We're stuck with 1.15.2 because of it!

**Comment by lukashass** [comment]
While this was not explicitly resolved, the `Source` types are exported since [v2.1.2](https://github.com/maplibre/maplibre-gl-js/releases/tag/v2.1.2).

That means you can now cast the return value like this:

```ts
const source = map.getSource('geojson') as GeoJSONSource;
source.setData({});
```

or use a type guard like I proposed in https://github.com/maplibre/maplibre-gl-js/issues/785#issuecomment-1013874115.

**Comment by ma7moudat** [comment]
Thank you 🙏

**Comment by petrot** [comment]
For me, casting the getSource method is not enough:

I have the following variables:
```
export const userPointFeatureCollection = {
  type: 'FeatureCollection',
  features: [
    {
      type: 'Feature',
      geometry: {
        type: 'Point',
        coordinates: [0, 0],
      },
    },
  ],
};
```

With this object, I have to cast the marker feature collection, too:

```
(this._mainMap?.getSource('userPointSource') as GeoJSONSource)?.setData(
    this._userMarkerFC as GeoJSON.GeoJSON
);
```

With this hack, it works well.

**Comment by HarelM** [comment]
I'm not sure there's something that can be done here as there's no info in the id of the source to let the code know which type of source it is, so I think casting is the best option.
Closing for now, if there's something else you would like to propose please open a different issue/PR/Keep writing here.
