### ISSUE TITLE
Remove vector-tile module declaration

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#788]
## Motivation

After fixing #787 I wanted to remove the not so optional solution with the vector tile typings I did.
@webberig will hopefully make a PR to definitely typed repo, after that the module declaration of mapbox vector tile can be removed from the code and the post build step.

This issue is to follow on the progress of this.

**Comment by webberig** [comment]
PR created:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58320

ETA:
> I've submitted a pull request. How long until it is merged?
> It depends, but most pull requests will be merged within a week. Some PRs can be merged by the owners of a module, and they can be merged much faster. Roughly:
