### ISSUE TITLE
Fork mapbox-gl-leaflet plugin and support maplibre

### ISSUE THREAD

**Issue by thesocialdev** [maplibre/maplibre-gl-js#79]
> tried several times to integrate MapBox Tiles into leaflet (tried several plugins), but was not successful.

Actually, you can integrate vector tiles from Mapbox (or Maptiler, or your own vector tileserver ) in leaflet with the help of "mapbox-gl-leaflet" plugin: [https://github.com/mapbox/mapbox-gl-leaflet](url)

_Originally posted by @Jonibigoud in https://github.com/maplibre/maplibre-gl-js/issues/59#issuecomment-765316948_

## Motivation

In order to use maplibre-gl fork, one might need to use it as a Leaflet plugin, like the [mapbox-gl-leaflet](https://github.com/mapbox/mapbox-gl-leaflet) official plugin

**Comment by SuperPat45** [comment]
It would be awesome if we can have a smaller version of maplibre-gl.js with only the need for showing the vector layer for leaflet and nothing else (no marker, no control...) 

This would make it possible to reduce a little the size of the loaded JavaScript which reaches the megabyte.

**Comment by tobwen** [comment]
Maybe both projects could be merged in the future?

**Comment by wipfli** [comment]
MapLibre has a repo now for leaflet bindings: https://github.com/maplibre/maplibre-gl-leaflet
