### ISSUE TITLE
"sourcedataloading" events are not always followed by "sourcedata" or "error" events

### ISSUE THREAD

**Issue by vanilla-lake** [maplibre/maplibre-gl-js#794]
**maplibre-gl-js version**: 1.15.2

### Steps to Trigger Behavior

 1. Move the map to a position A and wait for the tiles to load
 2. Move the map to a position B
 3. Before the tiles at position B finish loading, move back to position A

### Link to Demonstration

https://jsbin.com/zamemuyuxa/2/edit?html,console,output

### Expected Behavior

Every "sourcedataloading" event should be followed by a "sourcedata" or "error" event, per https://maplibre.org/maplibre-gl-js-docs/api/map/#map.event:sourcedataloading

### Actual Behavior

Some "sourcedataloading" events may not be followed by a "sourcedata" or "error" event if the above steps are followed. As an example, this makes it impossible to determine when to hide a spinner shown when a "sourcedataloading" event is fired.

**Comment by vanilla-lake** [comment]
The `sourcedataloading` event is fired here: https://github.com/maplibre/maplibre-gl-js/blob/9348083c88467ee36712dab059936fb6e6be2473/src/source/source_cache.ts#L732

Normally, the `sourcedata` or `error` events are fired from the `SourceCache#_tileLoaded` method passed as callback to   `SourceCache#_loadTile`. However, when `VectorTileSource#abortTile` is called, the callback is not fired.

I'll probably be able to start working on a PR tomorrow, but just to confirm, should we fire the `sourcedata` event when a tile request is canceled or should we have a separate event like `sourcedataabort`?

**Comment by j8seangel** [comment]
I'm facing the same issue and I've been using the `idle` event as a workaround so @vanilla-lake please let me know when you have the PR open. I will take a look at your solution and hopefully help you in any way.

I'd vote for having a new `sourcedataabort` which I find it easier to understand and use

**Comment by j8seangel** [comment]
wow that was fast  🙇 🪄 ✨
amazing work @vanilla-lake and thanks!

**Comment by vanilla-lake** [comment]
@j8seangel You are welcome! 😄

**Comment by wipfli** [comment]
@vanilla-lake are you in the osmus slack channel? Can you send me a direct message there?

Here is how you can join the slack: https://github.com/maplibre/maplibre-gl-js#getting-involved

**Comment by vanilla-lake** [comment]
@wipfli I tried signing in, but it says `user_disabled`. This might be related to me signing in at some point but then leaving.
