### ISSUE TITLE
`Point.convert()` with `{x: number, y: number}`

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#808]
The convert function of `@mapbox/point-geometry`:

https://github.com/mapbox/point-geometry/blob/bf471dc7ceb56299d4f5152c4badbeba193b0903/index.js#L304-L312

```js
Point.convert = function (a) {
    if (a instanceof Point) {
        return a;
    }
    if (Array.isArray(a)) {
        return new Point(a[0], a[1]);
    }
    return a;
};
``` 

does not do the same as our v2.0.0 `convert` function that we made in the TypeScript migration:

```js
    static convert(a: PointLike | {x: number; y: number}): Point {
        if (a instanceof Point) {
            return a;
        }
        if (Array.isArray(a)) {
            return new Point(a[0], a[1]);
        }
        if (typeof a.x === 'number') {
            return new Point(a.x, a.y);
        }
        throw new Error(`Unable to convert to point: ${JSON.stringify(a)}`);
    }
```

With pull request #800, we roll back from our `Point` class to the mapbox one. Let's keep an eye on this change.

**Comment by HarelM** [comment]
@wipfli do we want to do something here or can this be closed?

**Comment by wipfli** [comment]
Thanks for the issue triage, @HarelM. Can be closed since no problems were reported.
