### ISSUE TITLE
Missing `package.json` file in version 2.0.3 dist in npm

### ISSUE THREAD

**Issue by HarelM** [maplibre/maplibre-gl-js#811]
I have no clue what could have caused this but the results are the following:
In version 2.0.3 there's a missing package.json file in the dist folder.
Can be easily seen using unpkg:
https://unpkg.com/browse/maplibre-gl@2.0.2/dist/maplibre-gl.js
This file is important for webpack to know how to read the maplibre-gl.js file.
Looking at the releases and in version 2.0.3 dist.zip in github the file is there so it was generated during the build.
The only suspect I have is npm publish ignoring it due to the migration to node 16.
@birkskyum @wipfli I could really use you help here as I don't know how to proceed here.
We could try and create a version 2.0.4 or 2.0.4-pre.1 to test if this was a glitch, I don't know...

**Comment by wipfli** [comment]
![image](https://user-images.githubusercontent.com/53421382/150656802-eaa5fd34-f749-4587-bd52-ae925176568d.png)

seems good now
