### ISSUE TITLE
Use MapLibre logo icon

### ISSUE THREAD

**Issue by nyurik** [maplibre/maplibre-gl-js#82]
Replace mapbox's icon with maplibre's as part of the first release.

**Comment by rbrundritt** [comment]
Related to https://github.com/maplibre/maplibre-gl-js/issues/65

**Comment by klokan** [comment]
@nyurik - the SVG prepared for this purpose for now is here:

[maplibregl-ctrl-logo.svg.zip](https://github.com/maplibre/maplibre-gl-js/files/6130066/maplibregl-ctrl-logo.svg.zip)

**Comment by klokan** [comment]
An improved version, visually the same - but minified, with smaller (half of the) size in KBytes.

[MapLibre-logo-stroke-gray.svg.zip](https://github.com/maplibre/maplibre-gl-js/files/6164323/MapLibre-logo-stroke-gray.svg.zip)

**Comment by wipfli** [comment]
Mapbox stores their favicon at https://static-assets.mapbox.com/branding/favicon/v1/favicon.ico, see [here](https://github.com/maplibre/maplibre-gl-js-docs/blob/533acd5385be25a4b82b2cf458c2ce5b579911ac/vendor/docs-page-shell/react-page-shell.js#L157) for the docs usage.

Maybe it could make sense to start a ```branding``` repo where the MapLibre logo is stored. With GitHub Pages hosting the docs website and other MapLibre websites could then access for example the favicon asset at https://maplibre.github.io/branding/favicon.ico

**Comment by klokan** [comment]
@wipfli see https://maplibre.org/favicon.ico - committed to https://github.com/maplibre/maplibre.github.io/blob/main/favicon.ico

I am going to post the Design manual and prepared logo to #65

**Comment by petr-pokorny-1** [comment]
Resolved: https://github.com/maplibre/maplibre-gl-js/commit/bb44c571ca8a9a86ad83de82d60951000f5bf178
