### ISSUE TITLE
showTileBoundaries fails to ignore raster sources as documented

### ISSUE THREAD

**Issue by jleedev** [maplibre/maplibre-gl-js#833]
When I have a raster layer, `map.showTileBoundaries = true` is showing 0kb:

![Screenshot 2022-01-23 17 42 05](https://user-images.githubusercontent.com/23022/150700939-5b3c6d8f-e809-4024-898c-be8a0b8ed907.png)

But it is documented as:

> The uncompressed file size of the first vector source is drawn in the top left corner of each tile, next to the tile ID.

Which means that it should be skipping the raster layer and showing the size of my vector source.

When I hide the raster layer with `map.setLayoutProperty('simple-tiles','visibility','none');`, it works correctly:

![Screenshot 2022-01-23 17 42 17](https://user-images.githubusercontent.com/23022/150700983-c7f65268-8621-4a5e-b856-68ea772b8644.png)

Note that the raster tiles were 256px, while the vector tiles are 512px.

Also, `kb` should be `kB`.

Runnable example: https://jsbin.com/fohaxat

**Comment by HarelM** [comment]
This is waiting for #1395 to be merged.
