### ISSUE TITLE
if image is created with pixelRatio > 1, use it at run time as "fill-pattern" will cause flash

### ISSUE THREAD

**Issue by zhangyiatmicrosoft** [maplibre/maplibre-gl-js#860]
**maplibre-gl-js version**:  2.0.1

**browser**: Chrome 97.0.4692.71

### Steps to Trigger Behavior

 1. addImage and set pixelRatio to a value > 1
 2. create a polygon with any other fill-pattern initially
 3. at run time switch the pattern in step 1 via setPaintProperty

### Link to Demonstration
https://jsbin.com/zogepuw/edit?html,js,output

### Expected Behavior
After 2 seconds, when swathes from "pattern" to "pattern2", it should be smooth and seamlessly.
### Actual Behavior
Watch the fill pattern flashes to an unexpected state before settling.

**Comment by HarelM** [comment]
Fixed by #1765
