### ISSUE TITLE
benchmarks_generated.js is not properly deployed on new releases

### ISSUE THREAD

**Issue by xabbu42** [maplibre/maplibre-gl-js#861]
I don't know what exactly went wrong but benchmarks_generated.js is missing for all 2.0.x releases.
This means that if you follow https://github.com/maplibre/maplibre-gl-js/blob/main/bench/README.md you get an empty page instead of running benchmarks, as https://maplibre.org/maplibre-gl-js/benchmarks/v2.0.5/benchmarks_generated.js does not exist.

**Comment by xabbu42** [comment]
@wipfli can you look into the github workflow which should generate and deploy this files?
I'll generate the missing files by hand and make a pull request to gh-pages to add them.

**Comment by xabbu42** [comment]
also the generated default BENCHMARK_VERSION is wrong for releases. either we adapt the default in package.json or we set the env variable explicitly in the workflow.

**Comment by xabbu42** [comment]
#863 adds the missing files for the already made releases. to close this issue we still need to fix the workflow to generate and deploy this files on a new release.

**Comment by xabbu42** [comment]
I think it would be better to build and deploy benchmarks_generated.js as part of the release workflow. this way we have a stronger guaranty that release and benchmarks_generated.js match exactly as we actually use the same checkout instead of relying on reproducible builds. @wipfli @HarelM What do you think?

**Comment by HarelM** [comment]
I agree. I think the easiest solution would be to add it to the build process and add it to npm published files, but I'm not sure if it's possible to do it to already released versions...
Making sure it complies and wrapped in the npm package is easy...
