### ISSUE TITLE
Re-add ability to use Mapbox vector tiles

### ISSUE THREAD

**Issue by aapeliv** [maplibre/maplibre-gl-js#879]
## Motivation

We'd like to use Maplibre due to its open license and no-lockin (so we can in the future choose a different tile provider or produce our own), also the custom tile loading protocols (`addProtocol`) is super useful for us and we'd like to use that.

To take advantage of the new features and stay within the FOSS ecosystem, it'd be very useful to have a way to use `mapbox://` URLs or have a relatively straightforward workaround.

(Also, thanks everyone who's taken charge and created this fork and pushed it forward. I've switched several projects over, and you're doing super valuable work! I and a lot of others very much appreciate it!)

## Design Alternatives

It might be that it's relatively easy to look at the Mapbox style spec (which includes `mapbox://` URLs for glyphs/etc) and write the equivalent generic style JSON, then maybe this could be worked around with some docs?

## Design

I imagine the easiest way to do this would be to add a `mapbox` custom protocol loader. I am not sure what the ramifications for the Mapbox ToS are, from a quick look it seems you're allowed to call the APIs and reconstruct the rough behavior of v1.15 without reusing code from there and that might get around the ToS violation issue?

This could maybe be done in just a separate plugin that implements the protocol loader?

**Comment by HarelM** [comment]
You can read more about it here:
https://github.com/maplibre/maplibre-gl-js/discussions/290
You are free to create a plugin that will support the `mapbox://` protocol (probably using addProtocol and some code from 1.15) and use it at your own risk or continue using version 1.15.
We have decided not to support a specific vender as part of this library.
You are also feel free to write a tutorial in your favorite blog for other to use :-)
I'm closing this issue as there are other issues about it and also discussions there's no need for another one...

**Comment by aapeliv** [comment]
Okay, thank you!
