### ISSUE TITLE
Consider an OSS azure-map-control for maplibre to get higher-level APIs

### ISSUE THREAD

**Issue by rbrundritt** [maplibre/maplibre-gl-js#9]
My team created a wrapper of the Mapbox gl js SDK to create a more enterprise API interface, add better accessibility support and make it easier to create extensions. We had planned to make it open source once there was enough added value in it (we recently started to feel this is the case). Would there be any interest in this if we make this open source. Here is the docs: https://docs.microsoft.com/en-us/azure/azure-maps/how-to-use-map-control and here is the API interface: https://docs.microsoft.com/en-us/javascript/api/azure-maps-control/?view=azure-maps-typescript-latest The Mapbox Map instance can be accessed and used directly for those who want to use the existing Mapbox API through the "map.map" property. This SDK does use Azure Maps services, however, if you set the map style to blank and disable telemetry, the SDK won't make any calls to Azure Maps and you can use any tile service you want, no need for any Azure Maps authentication details either.

**Comment by lseelenbinder** [comment]
I don't know if it makes sense to open source it or not, but I'm all for better and simpler APIs. 

When in doubt, I always say yes, make it open. You never know who will benefit!

**Comment by rbrundritt** [comment]
We already open sourced a bunch of the modules here: https://github.com/microsoft/Maps/blob/master/AzureMaps.md#open-web-sdk-modules

There is another half dozen planned to be released over the next week.

**Comment by curran** [comment]
Seems not directly related to this repo? Can be closed perhaps?

**Comment by rbrundritt** [comment]
@curran This wrapper uses Mapbox gl js now and will likely move to MapLibre in the future. With MapLibre there will likely be some discussions on where the community wants to take the project. If an enterprise API interface is of interest, then this project might be a good starting point for that. My purpose for this question is to get thoughts from the community. Either way myself and likely others from my team plan to be a part of the MapLibre community and contribute to it.

**Comment by snickell** [comment]
Hi @rbrundritt , I see exactly what your thinking! I think something like this /would/ be of interest, but my guess is most immediately it would be another git repo in the same github org, e.g. `@maplibre/___namehere__`

Could you help me understand more about what enterprises need here, i.e. what an "enterprise API" is? I do like the API I'm seeing in those docs, but I haven't quite guessed what makes it enterprise :-)

**Comment by snickell** [comment]
I will say that `mapbox-gl-js` is amazing, but its definitely "a powerful abstract API upon which one can construct great+user friendly APIs", not a user friendly API in and of itself ;-) Our existing API is optimized for completeness of expression and "can do anything", very much NOT "make easy things easy".

Having an officially blessed higher-level API as part of maplibre (think: closer to leaflet, which is MUCH easier to use) would probably help many many devs who just need "easy things to be easy".

**Comment by stevage** [comment]
>I will say that mapbox-gl-js is amazing, but its definitely "a powerful abstract API upon which one can construct great+user friendly APIs", not a user friendly API in and of itself

IMHO it varies. Some things are very easy to do in Mapbox GL JS that are hard to do in, say, OpenLayers (arrows along lines for instance, omg, or popups). But other things that should be easy are pretty messy, like switching cursor when hovering over a layer, or displaying a layer switcher control (no support at all).

Just throwing into the mix my own "higher level API", [mapbox-gl-utils](https://github.com/stevage/mapbox-gl-utils). It's not much higher, but cleans up a few of the rough edges and pain points. It'd be cool maybe to get some of those concepts integrated here.

**Comment by rbrundritt** [comment]
@snickell agree, this isn't anything urgent, just thought I would mention this as an option to gauge interest and possible fast track this if there was a lot of interest/demand for it.

Also agree that the mapbox-gl-js SDK is powerful but at the same not very user friendly to developers who use the API. A great example is the CSS naming conventions of properties. In JavaScript/TypeScript, this requires wrapping these properties with quotes which means more typing and also a pain for many web developers who are used to camelCase convention for APIs. For example:

Some other things:

- Closer alignment with other enterprise mapping products. For example:
     - when you update the values of a shape, the map updates automatically, no need to clear/reload the data source manually.
     - easily switch between different base map styles. This is a single line of code to do in our API.
- Additional error handling and validation of options to help catch errors. When we started using Mapbox an error often lead to a blank map canvas and no error message which made it very hard to debug issues. Mapbox has gotten a lot better though in the past year or so.
- Much better accessibility support by default. This was really important to us as we can't ship a product without meeting certain accessibility support standards. We tried using the Mapbox module for this but the reality is that accessibility should be built in by default and never be a bolt on. There were a lot of limitations with the module approach, especially since we had to also create our own UI controls as per Mapbox licensing requirement. Powering the screen reader in a cost effective way was a fun challenge. We came up with a really cool way to leverage vector tiles to power this to reduce cost while also increasing the accuracy of the descriptions of the map. I was actually meant to present this at an accessibility summit but then the pandemic happened and the summit got cancelled.
- Support for more complex authentication methods (Azure Active Directory) in addition to subscription keys.

**Comment by stevage** [comment]
> In JavaScript/TypeScript, this requires wrapping these properties with quotes which means more typing and also a pain for many web developers who are used to camelCase convention for APIs.

Yeah, you noticed the same pain point :) Mapbox-gl-utils addresses that both by allowing camelCase in property names in styles, and also functions like `setCircleRadius()`. I really like the way it plays out in practice, `map.U.setCircleRadius('mylayer', 10)` it feels much less clumsy than `map.setPaintProperty("circle-radius", "mylayer", 10)`.

From a cursory look at the Azure docs, it looks like that has full classes for layers, which is probably even better.

>    easily switch between different base map styles. This is a single line of code to do in our API.

Definitely a big pain point that everyone runs into, and  for some reason, Mapbox has never addressed.

>Additional error handling and validation of options to help catch errors. When we started using Mapbox an error often lead to a blank map canvas and no error message which made it very hard to debug issues.

Yup, especially the "Map is not loaded" one, which is a massive pain point (and again, Mapbox for some reason won't address it).

>Much better accessibility support by default

I'd be interested to hear more about what the specific accessibility challenges are, and what the potential solutions are.


So anyway, I guess there are a couple of paths forward here, like:

- address these above pain points directly by fixing the library in ways Mapbox hasn't been willing to do
- support integration with "higher level" libraries that do these things.

**Comment by rbrundritt** [comment]
@stevage I would love to get several of these things addressed in MapLibre, but at the same time, mindful that some of these changes may result in code that isn't backwards compatible, so that would need more discussion and a major version number. 

In regards to accessibility, Microsoft has its own accessibility standards and grading system which is a combination of the few main standards that are out there. There is a fairly strict minimum level of support required. When we tried using all Mapbox accessibility module there was a pretty big gap in support to meet the min requirements. At one point we had a handful of users with different accessibility needs using our maps for weeks providing feedback while we made improvements. We have gone well beyond the minimum as we typically have found maps industry in general hasn't really done a great job in this area and something we wanted to change. I'm a big advocate for better accessibility in tech in general. 

Having full classes for layers and sources has also made it handle for creating custom layers/sources. For example: https://github.com/Azure-Samples/azure-maps-gridded-data-source

**Comment by curran** [comment]
>code that isn't backwards compatible
This is a Big Decision for the project and I'd vote "Hell yes", let's welcome non-backwards-compatible changes in this fork.

**Comment by lseelenbinder** [comment]
> code that isn't backwards compatible

I think we can certainly (and should eventually) introduce new code that isn't backwards compatible with consideration and a new version (v2).

However, at this point I don't think we're in a place where we can make those decisions yet. We need a few folks to have a strong technical and architectural understanding of the entire project (and an idea of where to head with it), and we aren't there yet.

**Comment by rbrundritt** [comment]
Good discussion, although getting a bit off track the original topic. I'll keep the task of the Azure Maps team making it's wrapper open source lower priority for now. As it is we will likely look at how we might bring over some of the features to MapLibre in the future, such as screen reader support based on vector tiles.
