### ISSUE TITLE
Flaky unit test for camera 

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#908]
This test is flaky, and breaks our CI validation very often.

https://github.com/maplibre/maplibre-gl-js/blob/main/src/ui/camera.test.ts

```ts
test('resets duration to 0 if it exceeds maxDuration', done => {
    let startTime, endTime, timeDiff;
    const camera = createCamera({center: [37.63454, 55.75868], zoom: 18});

    camera
        .on('movestart', () => { startTime = new Date(); })
        .on('moveend', () => {
            endTime = new Date();
            timeDiff = endTime - startTime;
            expect(timeDiff).toBeLessThan(10);
            done();
        });

    camera.flyTo({center: [-122.3998631, 37.7884307], maxDuration: 100});
});
```

The timeDiff is often 15 especially on mac, so it fails. I don't really understand this test tbh, so I would love if anyone could explain to me how we are testing that duration is reset to 0, and what that even means, because the timeDiff doesn't seem to be reset anywhere.

**Comment by HarelM** [comment]
I have no clue... :-/
