### ISSUE TITLE
No compass in the navigation control

### ISSUE THREAD

**Issue by fungiboletus** [maplibre/maplibre-gl-js#916]
![image](https://user-images.githubusercontent.com/45740/151578129-4edd0dc8-edc4-4849-99f5-a38f91939215.png)

**maplibre-gl-js version**: 2.1.0

**browser**: All

### Steps to Trigger Behavior

 1. Create a map with a navigation control and a compass.

### Expected Behavior

The navigation control should display a compass icon in the button.

### Actual Behavior

No icon is displayed.

### Potential issue:

It looks like the `span` has for class `mapboxgl-ctrl-compass-arrow` instead of `mapboxgl-ctrl-icon`. Either the class in the JavaScript or the class in the CSS needs to be updated.

**Comment by HarelM** [comment]
Thanks for taking the time to report this!
I don't think we changed much in this control lately, so this sounds like something that doesn't work for some time now.
Can you share a jsbin or something similar just to make sure it's not a problem with something else?

**Comment by HarelM** [comment]
I can't seems to be able to reproduce.
Please share the code that you are using.
The following is what I use with latest version and it seems to show the icon:
```js
let map = new maplibregl.Map({
    container: 'map',
    zoom: 12.5,
    center: [-77.01866, 38.888],
    style: 'https://demotiles.maplibre.org/style.json',
    hash: true,
});

map.addControl(new maplibregl.NavigationControl());
```
![image](https://user-images.githubusercontent.com/3269297/151675393-f6f1d3c7-4d65-4412-8886-668f2f9e3dda.png)

**Comment by taekwombo** [comment]
In my case the problem was that I used [`css-loader`](https://webpack.js.org/loaders/css-loader/#object).
This loader transpiled `url("data:image/svg+xml...")` into uri component - effectively all spaces became `%20`'s and this broke the svg.
I had to add a filter option to `css-loader`.

```js
{
  // This code existed.
  test: '/node_modules/**/*.(sc|sa|c)ss',
  loader: 'css-loader',
  // This code was added.
  options: {
    url: {
      filter: (url, resourcePath) => {
        // Do not change `"data:image/svg"` url values in maplibre-gl.
        if (resourcePath.endsWith('maplibre-gl.css')) {
          return !url.startsWith('data:image/svg');
        }
        return true;
      },
    },
  },
}
```

**Comment by HarelM** [comment]
Sound like a bug in css-loader, isn't it? I don't think the css here is invalid, right?
Can this issue be closed then?

**Comment by taekwombo** [comment]
If the cause of the problem was the same for @fungiboletus then yes, this issue can be closed.

**Comment by HarelM** [comment]
Ok wait a few more days to see if I get a relay, if not, I'll close this issue.

**Comment by fungiboletus** [comment]
Hei, I took the time to check again. Sorry for the issue, `maplibre-gl` was perfectly fine all along.

The issue was coming from my usage of `react-map-gl` and I did read carefully the code to rule out this library. But I did read the code on the main branch and not the version 6 I had installed. They released a new version 7 since my issue, I just upgraded and everything works as expected.
