### ISSUE TITLE
[Question] Sources tagging

### ISSUE THREAD

**Issue by petr-pokorny-1** [maplibre/maplibre-gl-js#92]
I am wondering if there is any plan to tag sources when releasing npm packages.
This was original Mapbox practice - source code tags were in sync with released npm packages.

Currently there is a problem with `maplibre-gl-js-docs`. I am trying to migrate `mapbox-jl-js` submodule to `maplibre-gl-js` but the pinning test (the submodule-migration branch https://github.com/maplibre/maplibre-gl-js-docs/tree/submodule-migration) is failing currently:

```bash
yarn run test
```

yields

```bash
yarn run v1.22.10
$ yarn run lint
$ eslint --ext .html docs/pages/example --ext .js .
$ tape test/*.test.js | tap-min && yarn run lint-md && yarn run test-content && jest

Mapbox GL JS submodule is not pinned to the latest stable release version. Latest: v0.0.0. Currently checked out: v2.0.0. To proceed, pull the latest from publisher-production and merge with "git merge publisher-production" from the feature branch. Or, notify @mapbox/docs.
        at:       '<anonymous> (/Volumes/Src/src/MapTiler/Documentation/maplibre-gl-js-docs/test/latest-version.test.js:24:11)'
        operator: ok
        expected: true
        actual:   false
```

In the test above the version resolved from npm is:

```bash
npm info maplibre-gl versions --json
```

```json
[
  "0.0.0",
  "1.13.0-rc.0",
  "1.13.0-rc.1",
  "1.13.0-rc.2",
  "1.13.0-rc.3",
  "1.13.0-rc.4",
  "1.13.0-rc.5"
]
```

And the version resolved from MapLibre repo is

```bash
git rev-parse HEAD
# => fdafaf665a9313c5075adfc0248d839eaf34c5d2
git rev-list -n 1 fdafaf665a9313c5075adfc0248d839eaf34c5d2
# => fdafaf665a9313c5075adfc0248d839eaf34c5d2
git tag --contains fdafaf665a9313c5075adfc0248d839eaf34c5d2
# =>
# style-spec@13.18.0
# style-spec@13.18.1
# v2.0.0
# v2.0.1
```

And since the expected tag format is [v*.*.*](https://github.com/maplibre/maplibre-gl-js-docs/blob/1d0ce8e28dc23cac3cd34098e0d0cbd8264ad795/test/helpers.js#L9), it resolves to v2.0.0.

I could tweak the tag format in the script but I need source code to be tagged when releasing npm packages. 
The pinning test is a good practice I think, it enforces that the submodule is checked out at the latest published version.

**Comment by nyurik** [comment]
That's a great idea, and I should probably go through our RCs and tag them. In the future, I hope to automate the release - i.e. the NPM publish should not be done manually, but instead should be done when a new release is created.

**Comment by petr-pokorny-1** [comment]
mapbox-jl-js sources will be tagged as described in https://github.com/maplibre/maplibre-gl-js/pull/95
