### ISSUE TITLE
Support ThreeJS for global coordinate

### ISSUE THREAD

**Issue by tan9710630** [maplibre/maplibre-gl-js#94]
MapboxGL has a [example](https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/) to render ThreeJS scene by using a CustomLayer. They just transforms the coordinate from global to local ,they used (0,0,0) for one particular latitude and longitude coordinate in world. I know this way they can avoid the accuracy lost in GPU, and it work every very in a small area. But if I want add  multiple 3D-Object to map in a very large scale, I have build multiple scene and renderer to CustomLayer. obviously that's very expensive and clearly not the best way.
I try to fix this problem by my own, but I don't have the ability to solve that, so I turn to you gays. If this feature request can't get in to roadmap, please at least show me how to do that, just show me a path is probable enough.
PS: I'm not a native English speaker, so if you see any grammatical errors, please just ignore that, I did my best to write these words.

**Comment by JannikGM** [comment]
> If this feature request can't get in to roadmap,

It's more of a ThreeJS issue than maplibre / mapbox.

I don't think maplibre should take care of it, other than documenting the issue and providing samples for common frameworks like ThreeJS.

That said, a custom-layer type which is using the mapbox coordinate system and requests rendering for each tile separately could solve this issue partially.
However, there are more important shortcomings with the custom-layer interface.

> I have build multiple scene and renderer to CustomLayer. obviously that's very expensive and clearly not the best way.

maplibre / mapbox uses a tile-local coordinate system itself.

So this is one of the best solutions; although your implementation might not be the best. Someone could take a look at your implementation if you share your code.
I have no experience with ThreeJS, but you can probably set up clipping and render different tiles, too.

Other than tiling, I don't think there's any good alternative if the custom-layer renderer doesn't have high-precision coordinates (in vertices and matrices). It can be handled either on the CPU or the GPU.

>  I know this way they can avoid the accuracy lost in GPU, and it work every very in a small area

The ThreeJS sample is actually much better than the barebones custom-layer which shows significant amounts of jittering when zooming in: https://docs.mapbox.com/mapbox-gl-js/example/custom-style-layer/
*(In addition, that also uses a broken color for pre-multiplied alpha, which breaks on my Linux machine)*

>  please at least show me how to do that, just show me a path is probable enough.

I use RTC rendering (https://help.agi.com/AGIComponents/html/BlogPrecisionsPrecisions.htm) for our companies WebGL custom layers. Some engines (as far as I know, Unity for example) can handle RTC out-of-the-box.

We might switch to tile-based rendering, but we usually deal with a relatively small number of features, and we can render them in a single draw call by using RTC.

---

A general warning: maplibre-gl-js / mapbox-gl-js are *slow* and seemingly not meant for animations.
On most machines, we can't achieve stable 60FPS with a fullscreen map, if the camera is moving.
Rendering the map also consumes a lot of CPU and GPU time, so the fans will spin up.

These performance issues can be a distraction while our customers work with our webapps, so we try to combat this issue (by optimizing our own maplibre / mapbox fork, but also by optimizing how we use our map).
Eventually we might even drop mapbox based projects and switch to another map renderer.

Our products mostly have a static camera, so we optimize in 2 ways:

- Use raster tiles for the basemap, and only draw symbol layers locally.
    - Symbol layers are mostly calculated on the CPU, so we also try to keep these to a minimum.
    - In our fork, we'll likely move some of the label placement into the shaders (in the future).
- Use 2 canvases:
    1. Canvas for mapbox (only updated when camera moves).
    2. Canvas for our custom-layer overlays (updated at 30 or 60 FPS).
 
We are about to deploy these optimizations in our products.
However, we are already aware of different performance issues with mixing those 2 canvases on high-DPI displays.
So it's not ideal.

Note that the performance issues don't seem to be as severe with the native versions (mapbox-gl-native / maplibre-gl-native). However, there are other issues with their custom-layer APIs (or lack thereof), which make it very hard, if not impossible, to render in RTC mode (namely, I believe the matrix you get is single-precision floats, and the inputs for the matrix calculation are rounded, too).
So custom-layers don't seem to be a cross-platform feature (or well supported anywhere) in maplibre / mapbox.

**Comment by tan9710630** [comment]
@JannikGM Thanks man, I did try the [threebox](https://github.com/jscastro76/threebox) before, but it turn out very slow, just not work very well in muti-Object scene. RTC rendering look like a nice solution, I can try that out. Thanks again.
