### ISSUE TITLE
Crash when imported under Node

### ISSUE THREAD

**Issue by Pessimistress** [maplibre/maplibre-gl-js#950]
**maplibre-gl-js version**: 2.1.1

**browser**: node.js

### Steps to Trigger Behavior

 In Node, run `require('maplibre-gl')`

### Expected Behavior

Successfully imports the library

### Actual Behavior

Throws error `Uncaught ReferenceError: performance is not defined`

This breaks server-side rendering unless the user application dynamically imports this dependency based on the runtime environment. This was fixed in mapbox-gl v1.11 by https://github.com/mapbox/mapbox-gl-js/pull/9749

**Comment by HarelM** [comment]
Seems like a duplicate if #791

**Comment by HarelM** [comment]
Duplicate of #768
