### ISSUE TITLE
Factor out custom stringify function

### ISSUE THREAD

**Issue by birkskyum** [maplibre/maplibre-gl-js#967]
In test/integration/expression/lib/util.ts we have a stringify and the following comment:

```ts
import compactStringify from 'json-stringify-pretty-compact';

// we have to handle this edge case here because we have test fixtures for this
// edge case, and we don't want UPDATE=1 to mess with them
export function stringify(v) {
    let s = compactStringify(v);

    if (s.indexOf('\u2028') >= 0) {
        s = s.replace(/\u2028/g, '\\u2028');
    }
    if (s.indexOf('\u2029') >= 0) {
        s = s.replace(/\u2029/g, '\\u2029');
    }
    return s;
}
```

Investigate if we can get avoid having this function at all.

**Comment by birkskyum** [comment]
keep

**Comment by HarelM** [comment]
@birkskyum where are we on this?

**Comment by HarelM** [comment]
I don't think this method is in use anymore, we can probably remove it...

**Comment by smellman** [comment]
There are no files to use `json-stringify-pretty-compact` in maplibre-gl-js (also it available on maplibre-style-spec), so I think OK to remove this package from package.json.
