### ISSUE TITLE
MapLibre doesn't work Angular 13.2.2

### ISSUE THREAD

**Issue by peteresteris** [maplibre/maplibre-gl-js#970]
Hello! Thanks for contributing.  For the fastest response and resolution, please:

Hi pals!
I have used maplibre in angular but after last version 13.2.2 through some misterious errors. This is my versions:
imagen

![imagen](https://user-images.githubusercontent.com/53539821/153208807-4cbc42ab-30cb-4161-9ab5-943c4288db13.png)

I have intalled MapLibreGl by command:
npm install maplibregl @types/maplibregl @types/geojson

I followed all instructions like:

    add "node_modules/maplibre-gl/dist/maplibre-gl.css" to styles in angular.json

But, in the first moment I put "import { Map } from 'maplibre-gl';" into .ts file, it throughs me a very strange pack of errors:

Compiled with problems:X

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:3:19 - error TS7016: Could not find a declaration file for module '@mapbox/point-geometry'. 'D:/PROJECTS/ANGULAR/homelasvegasnevada/node_modules/@mapbox/point-geometry/index.js' implicitly has an 'any' type.
Try npm i --save-dev @types/mapbox__point-geometry if it exists or add a new declaration (.d.ts) file containing declare module '@mapbox/point-geometry';

3 import Point from '@mapbox/point-geometry';
~~~~~~~~~~~~~~~~~~~~~~~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:5:52 - error TS7016: Could not find a declaration file for module '@mapbox/vector-tile'. 'D:/PROJECTS/ANGULAR/homelasvegasnevada/node_modules/@mapbox/vector-tile/index.js' implicitly has an 'any' type.
Try npm i --save-dev @types/mapbox__vector-tile if it exists or add a new declaration (.d.ts) file containing declare module '@mapbox/vector-tile';

5 import { VectorTileFeature, VectorTileLayer } from '@mapbox/vector-tile';
~~~~~~~~~~~~~~~~~~~~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:2232:61 - error TS2344: Type 'Us' does not satisfy the constraint '{}'.
Type 'unknown' is not assignable to type '{}'.

2232 export declare type UniformValues = $ObjMap<Us, (u: Uniform) => V>;
~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:2622:13 - error TS2503: Cannot find namespace 'GeoJSON'.

2622 _geometry: GeoJSON.Geometry;
~~~~~~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:2627:18 - error TS2503: Cannot find namespace 'GeoJSON'.

2627 get geometry(): GeoJSON.Geometry;
~~~~~~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:2628:18 - error TS2503: Cannot find namespace 'GeoJSON'.

2628 set geometry(g: GeoJSON.Geometry);
~~~~~~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:4588:13 - error TS2503: Cannot find namespace 'GeoJSON'.

4588 features?: GeoJSON.Feature[];
~~~~~~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:4591:13 - error TS2503: Cannot find namespace 'GeoJSON'.

4591 features?: GeoJSON.Feature[];
~~~~~~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:6511:41 - error TS2503: Cannot find namespace 'GeoJSON'.

6511 setGeoJSONSourceData(id: string, data: GeoJSON.GeoJSON | string): void;
~~~~~~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:8635:4 - error TS2411: Property 'mousemove' of type 'undefined' is not assignable to 'string' index type '(e: any) => void'.

8635 mousemove?: undefined;
~~~~~~~~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:8636:4 - error TS2411: Property 'mouseout' of type 'undefined' is not assignable to 'string' index type '(e: any) => void'.

8636 mouseout?: undefined;

I don't know what to make else. I left bulletless trying to solve this problem.

**Comment by HarelM** [comment]
If you are using angular I suggest to use npx-maplibre-gl.
Regardless, @types/maplibre-gl is no longer needed in latest version of maplibre.
You can look at my project if you would like to see what is installed there:
https://github.com/IsraelHikingMap/Site/blob/102d443c90450abb84f9a97ba30789b25a05969e/IsraelHiking.Web/package.json

**Comment by peteresteris** [comment]
Thanx for responding me pal. Certainly, I am using npx-maplibre-gl and it installed all I needed. But I have the same issue.

**Comment by HarelM** [comment]
Please share a stackblitz or something similar.

**Comment by peteresteris** [comment]
It happens after I import map from maplibregl

**Comment by peteresteris** [comment]
Ok pal.
I made a stackblitz and it worked. But, this don't happen on my VSC
This is the [link ](https://angular-ivy-jyfuir.stackblitz.io)
In my VSC when I compile; compiler fail on import map line.
It trigger this errors:

Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:3:19 - error TS7016: Could not find a declaration file for module '@mapbox/point-geometry'. 'D:/PROJECTS/ANGULAR/homelasvegasnevada/node_modules/@mapbox/point-geometry/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/mapbox__point-geometry` if it exists or add a new declaration (.d.ts) file containing `declare module '@mapbox/point-geometry';`

3 import Point from '@mapbox/point-geometry';
                    ~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:5:52 - error TS7016: Could not find a declaration file for module '@mapbox/vector-tile'. 'D:/PROJECTS/ANGULAR/homelasvegasnevada/node_modules/@mapbox/vector-tile/index.js' implicitly 
has an 'any' type.
  Try `npm i --save-dev @types/mapbox__vector-tile` if it exists or add a new declaration (.d.ts) file containing `declare module '@mapbox/vector-tile';`     

5 import { VectorTileFeature, VectorTileLayer } from '@mapbox/vector-tile';    
                                                     ~~~~~~~~~~~~~~~~~~~~~     


Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:2232:61 - error TS2344: Type 'Us' does not satisfy the constraint '{}'.
  Type 'unknown' is not assignable to type '{}'.

2232 export declare type UniformValues<Us extends any> = $ObjMap<Us, <V>(u: Uniform<V>) => V>;
                                                                 ~~


Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:8635:4 - error TS2411: Property 'mousemove' of type 'undefined' 
is not assignable to string index type '(e: any) => void'.

8635    mousemove?: undefined;
     1m   ~~~~~~~~~


Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:8636:4 - error TS2411: Property 'mouseout' of type 'undefined' is not assignable to string index type '(e: any) => void'.

8636    mouseout?: undefined;
        ~~~~~~~~
        
ERRORS HAPPENED INTO maplibre-gl.d.ts

**Comment by peteresteris** [comment]
I tried installing:
npm i --save-dev @types/mapbox__point-geometry
npm i --save-dev @types/mapbox__vector-tile
and 2 first errors changed to those:

3 import Point from '@mapbox/point-geometry';
         ~~~~~

  node_modules/@types/mapbox__point-geometry/index.d.ts:46:1
    46 export = Point;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.


Error: node_modules/maplibre-gl/dist/maplibre-gl.d.ts:2232:61 - error TS2344: Type 'Us' does not satisfy the constraint '{}'.
  Type 'unknown' is not assignable to type '{}'.

2232 export declare type UniformValues<Us extends any> = $ObjMap<Us, <V>(u: Uniform<V>) => V>;
                                                                 ~~

**Comment by HarelM** [comment]
Last error seems like the issue with #934 and tracked in #790.
Closing as this is a duplicate.
I don't know what causes this or how to easily reproduce.
Any help would be appreciated.

**Comment by wipfli** [comment]
Maybe I can adapt https://github.com/wipfli/maplibre-typescript such that it runs @peteresteris Angular project...

**Comment by rajakumar-durga** [comment]
Even I had the same error building my project with 1.15.2 maplibrgl version. I remove it from package.json and used the below npm install that resolved my issue. 

Ref : https://www.geoapify.com/tutorial/angular-leaflet-mapbox-maplibre-openlayers#angular-maplibre

npm i maplibre-gl@1.x
npm i --save-dev @types/geojson







ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:5:52 - error TS7016: Could not find a declaration file for module '@mapbox/vector-tile'. 'D:/PROJECTS/ANGULAR/homelasvegasnevada/node_modules/@mapbox/vector-tile/index.js' implicitly has an 'any' type.
Try npm i --save-dev @types/mapbox__vector-tile if it exists or add a new declaration (.d.ts) file containing declare module '@mapbox/vector-tile';

5 import { VectorTileFeature, VectorTileLayer } from '@mapbox/vector-tile';
~~~~~~~~~~~~~~~~~~~~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:2232:61 - error TS2344: Type 'Us' does not satisfy the constraint '{}'.
Type 'unknown' is not assignable to type '{}'.

2232 export declare type UniformValues = $ObjMap<Us, (u: Uniform) => V>;
~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:2622:13 - error TS2503: Cannot find namespace 'GeoJSON'.

2622 _geometry: GeoJSON.Geometry;
~~~~~~~

ERROR

node_modules/maplibre-gl/dist/maplibre-gl.d.ts:2627:18 - error TS2503: Cannot find namespace 'GeoJSON'.

2627 get geometry(): GeoJSON.Geometry;
~~~~~~~

**Comment by wipfli** [comment]
Just out of curiosity, why do you use v1 @rajakumar-durga ?

**Comment by rajakumar-durga** [comment]
> Just out of curiosity, why do you use v1 @rajakumar-durga ?

We are using angular 10.2.x , if I use >v1 I am end up seeing the same error. 

waiting
ERROR: node_modules/@maplibre/maplibre-gl-style-spec/dist/index.d.ts:66:3 - error TS1005: ',' expected.

66  r: number,
     ~
node_modules/@maplibre/maplibre-gl-style-spec/dist/index.d.ts:67:3 - error TS1005: ',' expected.

67  g: number,
     ~
node_modules/@maplibre/maplibre-gl-style-spec/dist/index.d.ts:68:3 - error TS1005: ',' expected.

68  b: number,
     ~
node_modules/@maplibre/maplibre-gl-style-spec/dist/index.d.ts:69:7 - error TS1005: ',' expected.

69  alpha: number
         ~
node_modules/@maplibre/maplibre-gl-style-spec/dist/index.d.ts:78:3 - error TS1005: ',' expected.

78  h: number,

**Comment by neodescis** [comment]
FWIW, I have the latest MapLibre (v3.3.1) working just fine with Angular 16!
