### ISSUE TITLE
Make it easier for new people to join the MapLibre community

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#98]
I am new to the MapLibre community and would like to contribute to the project because I like maps and I have been using mapbox in a personal project previously. In this issue I would like to share what confuses me about this project from the point of view of an outsider and I would like give some feedback how the project could make it easier for new people to join.

## Who are the people behind MapLibre?

Currently there is a [COMMUNITY.md](https://github.com/maplibre/maplibre-gl-js/blob/main/COMMUNITY.md) file which says who are the members of the steering committee and there are the [members of the GitHub organization](https://github.com/orgs/maplibre/people). These two lists are not identical which is confusing to me. Also, I have heard in talks that big companies like Microsoft and Elastic Search are supporting the project but I can't find this written anywhere.

As a feedback I suggest to compile a list companies that back the project for example in the form of paying some contributors to work on MapLibre. Also a list of the individuals who have commit rights and a way of contacting them would be helpful.

## How do I get support?

For people having questions about how to use MapLibre it is probably best to read about Mapbox at the moment. It is unclear to me where I should ask for help if I am stuck with a technical problem which is not a bug. The [README.md](https://github.com/maplibre/maplibre-gl-js/blob/main/README.md) points to Slack but to me it feels strange to ask there because it seems to be for general discussions which are not lead in the form of a pull request or an issue on GitHub.

As a feedback I suggest to motivate people in the [README.md](https://github.com/maplibre/maplibre-gl-js/blob/main/README.md) file to ask their questions on stackoverflow.com. This will make the answers visible to people having the same question in the future. Note that as of now only three questions appear on [stackoverflow when searching for ```maplibre```](https://stackoverflow.com/search?q=maplibre). So this has a lot of potential.

## What should I do if no one answers?

For outsiders like me it can become quickly frustrating if no one answers to my Issue or Pull Request. I guess new people come in with a lot of motivation but if nobody reacts to their input they will walk away and fragmentation will take place.

As a feedback I suggest to document in words how Issues and Pull Requests are treated by the maintainers of MapLibre. Explain the time it usually takes you to look over them and maybe implement automatic closing after 30 days of inactivity. By making a list of people who have commit rights it also gets easier for outsiders to ping someone who is a maintainer.

## Where can I report harassment?

First, I don't feel harassed, don't worry. I just want to point out that in online conversations maybe somewhere in a hidden Slack room it can happen quickly that the tone is not appropriate or that people say things in an unnecessarily crude way. For me as an outsider it is really important that the conversations I find are friendly and welcoming. But if something bad happens, there should be a way of reporting it. Currently the [CODE-OF-CONDUCT.md](https://github.com/maplibre/maplibre-gl-js/blob/main/CODE-OF-CONDUCT.md) says that ```Be kind, thoughtful and respectul to everyone.``` This is a good start but not enough.

As a feedback I suggest to use a more complete code of conduct such as for example [Contributor Covenant](https://www.contributor-covenant.org/version/1/4/code-of-conduct/). It is important to nominate a person who is responsible for enforcing the code of conduct and to share a way of contacting them.

If you have questions about this feedback don't hesitate to ask me. I am happy to answer.

**Comment by nyurik** [comment]
Thanks, great point!

* large company support
The large company support has not yet been crystalised. There are many individual developers in large companies that love the project and want to migrate to it, e.g. Elasticsearch's Kibana already has a pull request to migrate to it. Some large companies are looking into formalizing donations, etc.  With large orgs, it always takes some time for various approvals (e.g. legal), but individuals are already on board :)

* harassment - i'm all for improving the process, feel free to update that file in a pull request, and the steering committee can vote on it during our next sync. We could also nominate someone responsible to address such issues (though to be honest it is not very straightforward when the project is mostly driven by part-time efforts, but we can certainly try!)

* non-responsiveness - i think Slack is the best answer there -- there are some people in that channel, could always start a conversation there.  The issue with merging at the moment is that we must release a compatible version out first, before we start making breaking changes.

hope it helps :)

**Comment by snickell** [comment]
@wipfli this is a few issues in one :) If you'd like to refile each point as an issue, we can discuss each one there? Here are some quick thoughts.

**Code of Conduct**

My opinion: distraction, this project is already WAY too much talking and writing docs and way too little actually doing anything technical. I've never seen a code of conduct be actually relevant to changing behavior in a project at our phase. Once you're "firefox", well heck yeah, but we just .... aint'. "you are not google, and you're also not GNOME"

 @wipfli have you had specific bad experiences that a code of conduct helped you resolve? Could you link to these discussions so we can learn from them? If there's a specific issue you're having wrt to code of conduct we can problably help you out?

Long version: I'm personally not in favor of a complex code of conduct, its a nice thing, and a total distraction at this point when the project doesn't /really/ exist at some "code on the ground" level. IMO, at this point, velocity should be project #1, #2, and #3 priorities. If and when this is actually a healthy project, and there is NEED of one that goes beyond "sensible kind people excerising wisdom" (which formal documents don't really avoid anyway, you STILL need sensible kind leadership). Enough said on my part, I certainly wouldn't stand in the way of a steering kine person who was contributing already and wanted to own code of conduct, but too often these are boilerplate abandonware.

**Comment by wipfli** [comment]
You are right, these are actually multiple topics. Let me close this and open individual issues.
