### ISSUE TITLE
WorkerTransfer benchmark 3x slower on `main` compared to `v2.1.1`

### ISSUE THREAD

**Issue by wipfli** [maplibre/maplibre-gl-js#981]
The WorkerTransfer benchmarks is 3x slower on `main` compared to `v2.1.1`. 

@HarelM @birkskyum, might recent changes have something to do with this?

Steps to reproduce:

```
git checkout main
npm ci
npm run benchmark -- WorkerTransfer

                          v2.1.1      main 0263cc0 
 WorkerTransfer      19.9715 ms⚠️       93.1357 ms      +73.1641 ms
```

**Comment by HarelM** [comment]
I agree we should release a new version soon, I doubt that changing the worker code that was a simple replacement of file would've affected the performance, but everything is possible... :-)

**Comment by birkskyum** [comment]
http://localhost:9966/test/bench/versions#WorkerTransfer

**Comment by HarelM** [comment]
See my comment here:
https://github.com/maplibre/maplibre-gl-js/pull/913#issuecomment-1035488118
I see this error in the console, I think it is related to this #913 PR...
Can anyone confirm this is not only happening to me?

**Comment by wipfli** [comment]
Happened to me too.

**Comment by birkskyum** [comment]
But that was merged before 2.1.1, which seems to perform okay.
![release211](https://user-images.githubusercontent.com/74932975/153493479-41a36382-74d4-42ac-8abe-9fbbfbce2996.png)

**Comment by HarelM** [comment]
It's a different issue, I don't think it is related to the worker transfer performance, or 2.1.1 is faster because this fails fast :-)

**Comment by HarelM** [comment]
This probably needs a bisect... :-( too late for me though...

**Comment by birkskyum** [comment]
I found something... checking out the commit from v 2.1.1, and somehow it's different from v2.1.1 column.

![211-vs-main-vs-211](https://user-images.githubusercontent.com/74932975/153497861-32ff10ea-6392-4927-9b5c-aaa8ba73dfc8.png)

The third colum is commit (f47e53cb5a0411b5802a5ce5945997c597cb839e), and it should really be the same as the first.

**Comment by HarelM** [comment]
I'm talking about this PR: #704

**Comment by HarelM** [comment]
I wanted to see if this happens also in previous version, and I'm getting the following results:
`npm run benchmark -- WorkerTransfer --compare v1.15.2 --compare v2.1.1`
```
                            1.x cb3a420                    v2.1.1  move-bench-dirty 99107f3 
 WorkerTransfer              16.4234 ms                95.4176 ms               101.4773 ms 
```
```
                                 v2.1.0                    v2.1.1  move-bench-dirty 99107f3 
 WorkerTransfer              16.6740 ms                98.1929 ms               106.5554 ms
```
So it seems that for some reason the first run is very fast but the next runs are not. I don't have a clue what can cause this though.

**Comment by birkskyum** [comment]
From what I can reason it must mean that this issue is to be found in  /test/bench, and not in /src or benchmarks_generated.js, because the builds perform the same.

My current theory is that workers are enabled for the first run only.

**Comment by HarelM** [comment]
I think we should release 2.1.2, even today.
We need to iron out any issues that might have been introduced from the build changes before we release the 3D. The community will hopefully help in that aspect.

**Comment by birkskyum** [comment]
I have investigated a bit, and the only way the worker poll is being terminated is through:

Map._updateStyle() > Style._remove(); > Dispatcher.remove(); > WorkerPool.release()

So if we could also release the worker pool after each benchmark, that would probably help.

**Comment by birkskyum** [comment]
All the map workers start when we trigger 

```ts
function loadScript(src) {
            return new Promise((resolve, reject) => {
                const s = document.createElement('script');
                s.src = src;
                s.onload = resolve;
                s.onerror = reject;
                document.head.appendChild(s);
            });
        }
```

It would be much easier if we could actually use the maplibre api from the benchmarks, instead of going through benchmarks_generated.js

**Comment by HarelM** [comment]
Yup, see #982 .
But it's not an easy task as the current implementation checks the performance deep into the library code which is very powerful.
